#!/bin/bash
# launch_qa_secuura_batch1218-t2.sh — cross-project QA agent, ONE BATCHED TIER-2 gate over EIGHT Secuura/Blockchain PRs of round 21 (the round's THIRD
# tier-2 batch; three seats, one checkout): #1218 KS-897+KS-896 ROUND 2 (Seat L4, the pre-push base suite + a new guard suite), #1219 KS-1277 (T3) +
# #1223 KS-1118 ROUND 2 + #1233 KS-1133 (spec; legs 3/4/8 OWED) + #1237 KS-1229 + #1238 KS-1158 (T3) (Seat L1), #1235 KS-1140 + #1236 KS-1110 (Seat B 25th).
# TIER 2 on six, TIER 3 on two. 11 paths, pairwise disjoint. FROZEN at eight by Wednesday (#1223 round 2 widened in at 06:3xZ).
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate21T2c.py, a scratch clone FROM ORIGIN) at 2026-09-25T08:17:03Z, never adopted from a mail.
# BASE-INVARIANT: every head was cut from the OLD develop 6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7; develop at generation d9515f4a06e0db0396a059ccd8c76b610f22a22b (18 ahead of BASE); END_TREE of the eight
# over it 15dfe75db96e0816e2280ce70d2b4e1f83e33b73; declared overlap active at generation: YES for #1219 (develop carries #1225), #1237 (develop carries #1221). The compare check asserts each PR's merge_base, ahead, behind AND its file
# NAMES (the PR's own paths), not a count alone.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — re-fill there: repin_and_launch_gate21T2c.sh does).
# exit 3-5: capture / prompt / repo missing.
# exit 6:  any head is not at its branch AND refs/pull/N/head on origin — a STALE HEAD REFUSES (the refusal names the PR).
# exit 8:  eight rows; the prompt must open with the thinking directive, name the capture + the commission, and carry no unfilled double-brace fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base == BASE, ahead as pinned (#1218: 3, #1223: 2, #1236: 2), behind == 18, files ==
#          the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate21T2c.sh (it re-reads, re-measures and regenerates in ONE action).
# exit 20: the capture AND the prompt must name every head in full.   exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 23: the verdict subject prefix, coagent@ as sender, EIGHT verdict lines.   exit 25: the MERGE ADDENDUM rules.   exit 26: merge authority + the GO string.
# exit 30: the capture AND the prompt must BOTH carry the seat items.   exit 31: BASE / the launch develop / the END_TREE in full.
# exit 32: the capture AND the prompt must BOTH state which ticket each PR is.   exit 33: the by-name keyword ladder.   exit 7: tier lines (T2 x6, T3 x2).
# exit 34: the BASE-INVARIANT rule incl. BOTH DECLARED OVERLAPS (#1221 x #1237, #1225 x #1219).   exit 35: the STACK / LEGS rule (#1233 only; highest free slot; the
#          served-spec probe; leg-4 honesty; NOT RUN / OWED never green; Docker Desktop is not the gate's).   exit 36: the RED-PROOF rule.
# exit 37: #1218's REQUIRED CELLS + the no-standalone-run rule (cwd outside any repo; local bare / no-push:// origins; the anchored abort line).
# exit 38: the LOAD rule (KS-1155) + the conditional anchoring wording (KS-562).   exit 39: the HOLDS.   exit 40: the TIER-3 HYGIENE rule (#1219, #1238).
# exit 41: #1223's ROUND-2 rule (T5 over the WHOLE suite; the squash body's legs line).   exit 42: #1236's rule (routing + the canary).
# exit 43: the LOGIN_STUB REAPER rule.   exit 44: THE NEW PASS COUNT FOR THE FLEET STOP RULE.
# QAB1218_CUR_DEV / QAB1218_HEAD_1238 / QAB1218_PATHS_1236 / QAB1218_BRIEF / QAB1218_PROMPT: test overrides (--check only); a launch with any set refuses (exit 16).
# Generated by fill_gate21T2c.py at 2026-09-25T08:17:04Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1218-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-25_gate21T2c'
BRIEF="${QAB1218_BRIEF:-$GS/mail_gate21T2c_ready.md}"
PROMPT_FILE="${QAB1218_PROMPT:-$GS/2026-09-25_secuura-batch1218-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1218|KS-897|refs/heads/feature/ks-897-build-fixture-swallows-its-own-failure-l4-fixtureabort-1|d971aa4f24665bb192765a0c6e82f719996efb92|2|3|Blockchain/Dev/scripts/__tests__/pre_push_hook_base.test.sh,Blockchain/Dev/scripts/__tests__/pre_push_hook_base_fixture_guard.test.sh|T2"
  "1219|KS-1277|refs/heads/feature/ks-1277-stale-obo-comments-l1-a-1|5d5129a03af0bf1586c26403a453ce283ae0be2f|1|1|Blockchain/Dev/services/originate/src/routes/documents.ts|T3"
  "1223|KS-1118|refs/heads/feature/ks-1118-verify-hash-precedence-l1-c-1|2892e528630d93a5b1b1482efa6978edce4211f1|1|2|Blockchain/Dev/services/originate/src/routes/verification.ts|T2"
  "1233|KS-1133|refs/heads/feature/ks-1133-verify-alias-order-spec-l1-d-1|6892124d9304ae014c52f7ea08a17e9468d411bf|2|1|Blockchain/Dev/docs/openapi/secuura-api.yaml,Blockchain/Dev/services/originate/src/originate.openapi.ts|T2"
  "1235|KS-1140|refs/heads/feature/ks-1140-ks879-guard-the-cell-walks-the-tree-on-its-own-r21-handedlist-1|1c899947ea31e7a6628f5256174c1c353e6587af|1|1|Blockchain/Dev/packages/shared/src/__tests__/ks879-no-raw-control-bytes-repo-wide.test.ts|T2"
  "1236|KS-1110|refs/heads/feature/ks-1110-two-k6-unit-tests-parse-configscenariosyml-with-js-yaml-r21-readyaml-1|4296ba6d090c212d0849f488f882d00a2985245e|2|2|systemTest/performance/tests/unit/config/sheddingCeiling.test.ts,systemTest/performance/tests/unit/package_scripts.test.ts|T2"
  "1237|KS-1229|refs/heads/feature/ks-1229-version-truthy-cell-l1-e-1|cfa16eb70ba28c5833101e39e4e1cb1680b8dd6c|1|1|Blockchain/Dev/services/originate/src/__tests__/ks1213-a-derived-writer-relabel-is-refused.test.ts|T2"
  "1238|KS-1158|refs/heads/feature/ks-1158-stale-header-lines-l1-f-1|0f3ffbb0947a82b7ec1c2866fd1a82ff4c94b2c1|1|1|Blockchain/Dev/services/originate/src/__tests__/ks1059-sim-leg-must-not-resurrect-a-terminal-document.test.ts|T3"
)
BASE_SHA='6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7'
DEVELOP_SHA='d9515f4a06e0db0396a059ccd8c76b610f22a22b'
DEV_BEHIND='18'
END_TREE='15dfe75db96e0816e2280ce70d2b4e1f83e33b73'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate21T2c.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 8 ] || { echo "REFUSING: ${#PRS[@]} rows, the batch is eight (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate21T2c_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p _tier <<< "$_pr"
  [ "$_n" = 1238 ] && [ -n "${QAB1218_HEAD_1238:-}" ] && _h="$QAB1218_HEAD_1238"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1218_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate21T2c.sh (it re-reads, re-measures and regenerates in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf, na, paths, tier = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p _tier <<< "$_pr"
  [ "$_n" = 1236 ] && [ -n "${QAB1218_PATHS_1236:-}" ] && _p="$QAB1218_PATHS_1236"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${BASE_SHA} ahead=${_a} behind=${DEV_BEHIND} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not merge_base $BASE_SHA / ahead as pinned / behind $DEV_BEHIND / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p _tier <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_tier" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_tier'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'TIER 2 on six' && has 'TIER 3 on two (#1219, #1238)' && has 'ROUND 2 of 2 under the two-NO-GO cap' || { echo "REFUSING: TIER 2 on six / TIER 3 on two / round 2 of 2 for #1218 and #1223" >&2; exit 7; }
for _w in \
  'd971aa4f24665bb192765a0c6e82f719996efb92' \
  '5d5129a03af0bf1586c26403a453ce283ae0be2f' \
  '2892e528630d93a5b1b1482efa6978edce4211f1' \
  '6892124d9304ae014c52f7ea08a17e9468d411bf' \
  '1c899947ea31e7a6628f5256174c1c353e6587af' \
  '4296ba6d090c212d0849f488f882d00a2985245e' \
  'cfa16eb70ba28c5833101e39e4e1cb1680b8dd6c' \
  '0f3ffbb0947a82b7ec1c2866fd1a82ff4c94b2c1' \
  '4 passed, 2 failed' \
  '6 passed, 0 failed' \
  '28 passed, 0 failed' \
  '52cb0fc5b18d' \
  'ce4a25b62a20' \
  'SUBJ_SH' \
  'HOOK_SH' \
  '_bf_rc=$?' \
  'env -u HOOK_SH' \
  'rc 0 with all 28 cells green' \
  '58 passed, 0 failed (of 58)' \
  '3bad652d17cf' \
  ':1612' \
  ':1971' \
  ':2160' \
  ':2344' \
  ':2341' \
  ':124' \
  'recordOnBehalfOf' \
  '2 failed / 861' \
  '#1149' \
  'ks1118-verify-documenthash-over-hash.test.ts' \
  '575' \
  'accept-split' \
  'BAD_REQUEST' \
  '405 example blocks' \
  '20+/6-' \
  'src/originate.openapi.ts' \
  'QVT1/2/3' \
  '3 failed / 111' \
  '74 / 867' \
  'd4cf7e3cf' \
  'crypto-agility.guard' \
  '5053 ms' \
  '920/920' \
  '1085/1085' \
  '1089/1089' \
  '14/3' \
  '13/3' \
  '--recount --ignore-whitespace' \
  '839-byte' \
  'format:check OK' \
  'Item C' \
  'GF-3' \
  'failed=1'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'TIER 2 on six' \
  'TIER 3 on two' \
  'THROUGH-CODE REVIEW' \
  'RED-PROOF CHECK OF THE PR'"'"'S OWN PROOF' \
  'RED AT BASE and GREEN AT HEAD' \
  'RESTORE BYTE-IDENTICALLY' \
  'FINDINGS ONLY' \
  'A VERDICT IS VALID ONLY AT ITS HEAD' \
  'FROZEN at eight' \
  'PRIOR ROUNDS' \
  'ITS REPORT IS ON DISK AT' \
  'RE-READ develop at your start' \
  'EVERY MERGE CHECK IS BASE-INVARIANT' \
  'THE DECLARED OVERLAP' \
  'THE RED PROOFS — RE-RUN' \
  'T5 = ' \
  'T-V = ONLY the `/version` guard' \
  'THREE plants' \
  'ROUTING: `readYaml`' \
  'THE CANARY' \
  'THE STACK — ONCE, FOR #1233 ONLY' \
  'S0 CENSUS BEFORE' \
  'S1 THE ENGINE IS NOT YOURS' \
  'S3 SLOT' \
  'SECUURA_STACK_SLOT' \
  'S4 BUILD ONCE' \
  'S5 THE SERVED-SPEC PROBE' \
  'S6 LEGS 3/4/8' \
  'LEG 4 HONESTY' \
  'REACH (measure, then grade)' \
  'S9 TEAR DOWN, ALWAYS' \
  'VOLUMES KEPT' \
  'NEVER quit Docker Desktop' \
  '#1218 — THE REQUIRED CELLS' \
  '(A) T897b' \
  '(B) the cwd-inside-a-scratch-repo case' \
  '(C) the seat'"'"'s guard suite' \
  '(D) THE NEW PASS COUNT FOR THE FLEET STOP RULE' \
  '(E) errexit' \
  '(F) KS-896' \
  '#1223 ROUND 2' \
  'TIER 3 — HYGIENE' \
  'removeComments' \
  'LOAD (standing' \
  'KS-1155' \
  'ANCHORING WORDING' \
  'LOGIN_STUB REAPER — YOUR OWN ONLY' \
  'LEADS for you to grade' \
  'BY-NAME ITEMS' \
  'TIER AND ROUND' \
  'PER-FILE TYPECHECK DELTA 0' \
  'CENSUS v2' \
  'NEVER connect to a database port' \
  'LINEAR LINK HYGIENE' \
  'MERGE ADDENDUM' \
  'MG-1' \
  'MG-3' \
  'MG-11' \
  'STAY In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'CARRY-FORWARD' \
  'READ THE WHOLE TEST FILE' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'NEVER a fetch into it' \
  'Never enter any seat worktree' \
  '.push-lock-21' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'never print a credential value' \
  'No memory maintenance' \
  'Datasec files and mail are out of scope entirely' \
  'EVIDENCE CLASS' \
  'NOT-TESTED.written-first.md' \
  'THE CONTEXT RULE' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '2026-09-25-batch1218-t2c' \
  '2026-09-25-batch1215-t2-r1' \
  '2026-09-25-batch1224-t1-r1' \
  '2026-09-23-batch1202-t2-r1' \
  'the merging seat re-predicts' \
  'HOLDS (standing)' \
  'mail_gate21T2c_ready.md' \
  'COMMISSION.md' \
  'answer_seatB25_movedbase' \
  'FIXTURE-GITENV-WORKTREE' \
  'READYAML-CANARY' \
  'QVT-SIGN' \
  'State the FAIL condition before each run'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'a sibling batch merging is not a difference' && has 'THE DECLARED OVERLAP (#1221 × #1237)' && has "develop's blob at that path == #1221's head blob d0e886e959258bc0fa962c03727453eb422196b3" && has 'THE DECLARED OVERLAP (#1225 × #1219)' && has "develop's blob at that path == #1225's squash blob 8331f626cd82b977204da3c5193c64df91908ce7" && has 'Anything else on an own path refuses' || { echo "REFUSING: the BASE-INVARIANT rule / the declared overlap" >&2; exit 34; }
has 'LEGS 3/4/8 — OWED FOR #1233 ONLY' && has 'take the HIGHEST free N in 4, 3, 2' && has 'THE SERVED-SPEC PROBE' && has 'you do NOT start, restart, quit, kill or reset Docker Desktop' && has 'Start_Up/start-secuura.sh --rebuild' && has 'Start_Up/start-secuura.sh --stop' && has 'A SKIP or an rc 2 is NOT RUN, never a pass' && has 'NEVER "green"' && has 'mint NO credential' && has 'NO leg can witness #1233' || { echo "REFUSING: the STACK / LEGS rule (#1233 only; highest free slot; the served-spec probe; Docker Desktop not the gate's; leg-4 honesty; NOT RUN / OWED never green)" >&2; exit 35; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has 'NO STANDALONE RUN of `pre_push_hook_base.test.sh` or `run-shell-suites.sh` except #1218' && has '`scripts/run-shell-suites.sh` NOT AT ALL' && has 'every run from a cwd OUTSIDE any git repo' && has 'a LOCAL bare repo you created under your report dir, or `no-push://…` — never a real remote' && has 'a line STARTING `FIXTURE BUILD FAILED`' && has 'HEAD, refs and config byte-identical' && has "set YOUR clone's \`remote.origin.pushurl\` to \`no-push://gate21T2c\`" || { echo "REFUSING: #1218's REQUIRED CELLS / the no-standalone-run rule" >&2; exit 37; }
has 'KNOWN FALSE-RED (ticket KS-1155)' && has 'an ASSERTION failure is REAL' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO action on any container, volume, image or network you did not start, NO Docker Desktop start / restart / quit. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'TIER 3 — HYGIENE (#1219 and #1238): no red proof is owed' && has 'AST-EQUIVALENT BASE vs head' || { echo "REFUSING: the TIER-3 HYGIENE rule" >&2; exit 40; }
has 'T5 over the WHOLE originate suite' && has 'the HEAD under T5 → 2 failed / 861 with THE SAME two cells and NOTHING ELSE' && has 'the squash body carries the legs line' || { echo "REFUSING: #1223's ROUND-2 rule" >&2; exit 41; }
has 'ROUTING: `readYaml`' && has 'THE CANARY' && has 'KS-1110' && has 'THE PRE-PUSH HOOK RAN NO Blockchain/Dev LEG' || { echo "REFUSING: #1236's rule (routing + the canary)" >&2; exit 42; }
has 'never by name, never pid 1' && has 'report the count before / after' || { echo "REFUSING: the LOGIN_STUB REAPER rule" >&2; exit 43; }
has 'THE NEW PASS COUNT FOR THE FLEET STOP RULE' && has '(the squash body must state it, rule 2' || { echo "REFUSING: THE NEW PASS COUNT FOR THE FLEET STOP RULE" >&2; exit 44; }
has "WEDNESDAY'S signed GO naming each head" && has '`GO: merge #1218, #1219, #1223, #1233, #1235, #1236, #1237, #1238 batch`' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE equality target PER PR FILE (2/1/1/2/1/2/1/1 = 11 over 11 paths)' && has 'KEY-FREE' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 BATCH GATE #1218-#1238 round 21' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'EIGHT lines, one per PR' || { echo "REFUSING: the verdict subject / sender / eight lines" >&2; exit 23; }
grep -qF -- "$BASE_SHA" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of BASE $BASE_SHA); heads at branch AND pull/N/head:$HEADS_NOTE; END_TREE $END_TREE"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compares (GitHub API), develop...head per PR (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; eight rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, each ticket, and 53 seat items; the prompt carries 93 by-name keywords, the base-invariant + declared-overlap / stack+legs / red-proof / #1218 required-cells / load+anchoring / holds / tier-3 / #1223 round-2 / #1236 / reaper / STOP-count rules, the merge authority + GO string, the MERGE ADDENDUM rules, the verdict subject / sender, BASE / develop / END_TREE in full"
  [ -n "${QAB1218_CUR_DEV:-}${QAB1218_HEAD_1238:-}${QAB1218_PATHS_1236:-}${QAB1218_BRIEF:-}${QAB1218_PROMPT:-}" ] && echo "  (a QAB1218_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1218_BRIEF:-}${QAB1218_PROMPT:-}${QAB1218_HEAD_1238:-}${QAB1218_PATHS_1236:-}${QAB1218_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
