#!/bin/bash
# launch_qa_secuura_batch1215-t2.sh — cross-project QA agent, ONE BATCHED ROUND 1 TIER-2 gate over SIX Secuura/Blockchain PRs of round 21 (four lane
# seats, one checkout): #1215 KS-1288 + #1222 KS-1181 (Seat L3, packages/shared tests), #1218 KS-897+KS-896 (Seat L4, a bash suite), #1220 KS-1129
# (Seat L2, services/anchoring product — legs 3/4/8 OWED), #1221 KS-1266 + #1223 KS-1118 (Seat L1, originate tests; #1223 one product COMMENT).
# TIER 2 on all six. 14 paths, pairwise disjoint. FROZEN at six by Wednesday.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate21T2.py, a scratch clone FROM ORIGIN) at 2026-09-25T03:54:24Z, never adopted from a mail.
# Develop read at generation: 6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7 (0 ahead of BASE 6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7); END_TREE of the six over it 75b43d7d4e3a4ea3c6ddff374a50ef7e63a0e7dd.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — re-fill there: repin_and_launch_gate21T2.sh does).
# exit 3-5: capture / prompt / repo missing.
# exit 6:  any head is not at its branch AND refs/pull/N/head on origin — a STALE HEAD REFUSES (the refusal names the PR).
# exit 8:  six rows; the prompt must open with the thinking directive, name the capture + the commission, and carry no unfilled double-brace fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base == BASE, ahead as pinned (#1218: 2), behind == 0, files as pinned.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate21T2.sh (it re-reads, re-measures and regenerates in ONE action).
# exit 20: the capture AND the prompt must name every head in full.   exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 23: the verdict subject prefix, coagent@ as sender, SIX verdict lines.   exit 25: the MERGE ADDENDUM rules.   exit 26: merge authority + the GO string.
# exit 30: the capture AND the prompt must BOTH carry the seat items.   exit 31: BASE / the launch develop / the END_TREE in full.
# exit 32: the capture AND the prompt must BOTH state which ticket each PR is.   exit 33: the by-name keyword ladder.   exit 7: tier lines.
# exit 35: the LEGS rule (NOT run ×5 stated; OWED for #1220; the tier-1 stack is never touched; RAN only against an up stack; NOT RUN is never green).
# exit 36: the RED-PROOF rule (re-run RED at BASE and GREEN at HEAD, restore byte-identically).   exit 37: the PORT PROBE rule (#1221's ECONNREFUSED).
# exit 38: the LOAD rule (KS-1155 timeouts are a known false-red; an assertion failure is real) + the mandatory anchoring wording (KS-562).   exit 39: the HOLDS.
# QAB1215_CUR_DEV / QAB1215_HEAD_1223 / QAB1215_BRIEF / QAB1215_PROMPT: test overrides (--check only); a launch with any set refuses (exit 16).
# Generated by fill_gate21T2.py at 2026-09-25T04:17:38Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1215-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-25_gate21T2'
BRIEF="${QAB1215_BRIEF:-$GS/mail_gate21T2_ready.md}"
PROMPT_FILE="${QAB1215_PROMPT:-$GS/2026-09-25_secuura-batch1215-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead
PRS=(
  "1215|KS-1288|refs/heads/feature/ks-1288-legd-text-pins-l3-r1-1|5e3419a46db5a1a4e7e640aee2e60dd89db3912a|1|1"
  "1218|KS-897|refs/heads/feature/ks-897-build-fixture-swallows-its-own-failure-l4-fixtureabort-1|999623d28f7cc3f11140cf379cfd3169e6530b57|1|2"
  "1220|KS-1129|refs/heads/feature/ks-1129-anchoring-blocknumber-number-l2-bignum-1|9c2021ba3e770abc9ad464b62fdc245a920389cb|2|1"
  "1221|KS-1266|refs/heads/feature/ks-1266-anchoring-url-hermetic-l1-b-1|0a561a5db393e8f0ced82b86af572c7231330d64|7|1"
  "1222|KS-1181|refs/heads/feature/ks-1181-errorhandler-canary-hit-l3-r1-1|9bce90229ad60b4ab988248648530b3b9a0d951d|1|1"
  "1223|KS-1118|refs/heads/feature/ks-1118-verify-hash-precedence-l1-c-1|759726d8d046e6098e720d4768c87e114d0c363c|2|1"
)
BASE_SHA='6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7'
DEVELOP_SHA='6ab9d5021e96ea1481cb6c6ff2d6d33b414aecb7'
DEV_BEHIND='0'
END_TREE='75b43d7d4e3a4ea3c6ddff374a50ef7e63a0e7dd'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate21T2.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 6 ] || { echo "REFUSING: ${#PRS[@]} rows, the batch is six (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate21T2_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a <<< "$_pr"
  [ "$_n" = 1223 ] && [ -n "${QAB1215_HEAD_1223:-}" ] && _h="$QAB1215_HEAD_1223"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1215_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate21T2.sh (it re-reads, re-measures and regenerates in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf, na = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); print("%s %s ahead=%d behind=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a <<< "$_pr"
  printf '%s\n' "$COMPARE" | grep -q "^${_n} ${BASE_SHA} ahead=${_a} behind=${DEV_BEHIND} files=${_f}\$" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not merge_base $BASE_SHA / ahead as pinned / behind $DEV_BEHIND / files as pinned:" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n T2" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n T2'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'TIER 2 on all six' && has 'round 1 of 2' || { echo "REFUSING: TIER 2 on all six / round 1 of 2" >&2; exit 7; }
for _w in \
  '5e3419a46db5a1a4e7e640aee2e60dd89db3912a' \
  '999623d28f7cc3f11140cf379cfd3169e6530b57' \
  '9c2021ba3e770abc9ad464b62fdc245a920389cb' \
  '0a561a5db393e8f0ced82b86af572c7231330d64' \
  '9bce90229ad60b4ab988248648530b3b9a0d951d' \
  '759726d8d046e6098e720d4768c87e114d0c363c' \
  '918' \
  '922' \
  '919' \
  '863' \
  '864' \
  '334 passed / 1 failed' \
  '344 passed / 1 failed' \
  '2 failed / 8 passed' \
  '10/10' \
  '1 failed / 8 passed' \
  '9 failed' \
  '1 failed / 14 passed' \
  '28 passed, 0 failed' \
  'FIXTURE BUILD FAILED' \
  'upstream=NONE' \
  '57 passed, 0 failed (of 57)' \
  '3.2.57' \
  'entity.too.large' \
  '127.0.0.1:2' \
  'anchoring:4005' \
  'threadTokenMint' \
  'deterministic per-seed policyId' \
  'KS-562' \
  'T5' \
  '#1136' \
  'OWED at the gate' \
  'toBlockNumber' \
  'shouldForward' \
  'expected [ 845, 858, 891 ] to include 873' \
  'contributes' \
  'KS-973' \
  'ks1213' \
  '17' \
  '26'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'TIER 2 on all six' \
  'THROUGH-CODE' \
  'RED-PROOF CHECK OF THE PR'"'"'S OWN PROOF' \
  'RED AT BASE and GREEN AT HEAD' \
  'RESTORE BYTE-IDENTICALLY' \
  'FINDINGS ONLY' \
  'A VERDICT IS VALID ONLY AT ITS HEAD' \
  'MEASURE, not conclude' \
  'RULE WHETHER IT BLOCKS' \
  'FROZEN at six' \
  'TIER AND ROUND' \
  'is re-graded TIER 1' \
  'RE-READ develop at your start' \
  'THE RED PROOFS — RE-RUN' \
  'THE PORT PROBE' \
  'does NOT record the OUTCOME' \
  'PRECONDITION: `lsof -nP -iTCP:2 -sTCP:LISTEN` empty' \
  'LEGS 3/4/8 — NOT RUN' \
  'THE STACK IS NOT YOURS TO START' \
  'IF THE STACK IS UP' \
  'OTHERWISE' \
  'SAY WHOSE ANCHORING ANSWERED' \
  'REACH (measure, then grade)' \
  'THE CONSUMERS' \
  'ANCHORING WORDING — MANDATORY' \
  'LOAD (standing' \
  'KS-1155' \
  'LEADS for you to grade' \
  'BY-NAME ITEMS' \
  'PER-FILE TYPECHECK DELTA 0' \
  'CENSUS v2' \
  'NEVER connect' \
  'LINEAR LINK HYGIENE' \
  'MG-11' \
  'MG-3' \
  'MERGE ADDENDUM' \
  'stays In Progress' \
  'STAY In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'CARRY-FORWARD' \
  'READ THE WHOLE TEST FILE' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'NEVER a fetch into it' \
  'Never enter any seat worktree' \
  '.push-lock-21' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'never print a credential value' \
  'No memory maintenance' \
  'Datasec files and mail are out of scope entirely' \
  'NOT-TESTED.written-first.md' \
  'THE CONTEXT RULE' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '2026-09-25-batch1215-t2-r1' \
  '2026-09-23-batch1202-t2-r1' \
  '2026-09-25-batch1213-t1-r1' \
  'the merging seat re-predicts' \
  'HOLDS (standing)' \
  'mail_gate21T2_ready.md' \
  'COMMISSION.md' \
  'GIT_DIR' \
  'KS-1086' \
  'the filter ANSWERS it' \
  'FORWARDING_HANDLERS' \
  'comment-only' \
  'KS-1143 GF-2'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'LEGS 3/4/8 — NOT RUN FOR #1215, #1218, #1221, #1222, #1223; OWED FOR #1220' && has 'THE STACK IS NOT YOURS TO START' && has 'the tier-1 gate is bringing Docker and ONE platform stack up' && has 'IF THE STACK IS UP' && has 'RUN legs 3/4/8 for #1220 against it' && has 'legs 3/4/8 for #1220 are OWED' && has 'A SKIP or an rc 2 is NOT RUN, never a pass' && has 'NEVER "green"' || { echo "REFUSING: the LEGS rule (NOT run ×5; OWED for #1220; run only against an up stack; the tier-1 stack is never touched; NOT RUN is never green)" >&2; exit 35; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has 'THE PORT PROBE (#1221' && has "cause.code === 'ECONNREFUSED'" && has 'does NOT record the OUTCOME' || { echo "REFUSING: the PORT PROBE rule" >&2; exit 37; }
has 'KNOWN FALSE-RED (ticket KS-1155)' && has 'an ASSERTION failure is REAL' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing at develop 6ab9d5021 (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'deploy of any kind, NO Docker start and NO container action. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming each head" && has '`GO: merge #1215, #1218, #1220, #1221, #1222, #1223 batch`' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE equality target PER PR FILE (1/1/2/7/1/2 = 14 over 14 paths)' && has 'KEY-FREE' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 BATCH GATE #1215-#1223 round 21' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'SIX lines, one per PR' || { echo "REFUSING: the verdict subject / sender / six lines" >&2; exit 23; }
grep -qF -- "$BASE_SHA" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of BASE); heads at branch AND pull/N/head:$HEADS_NOTE; END_TREE $END_TREE"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compares (GitHub API), develop...head per PR:"; printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  capture, prompt, QA project and repo present; kit at its filled home; six rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, each ticket, and 40 seat items; the prompt carries 71 by-name keywords, the legs / red-proof / port-probe / load+anchoring / holds rules, the merge authority + GO string, the MERGE ADDENDUM rules, the verdict subject / sender, BASE / develop / END_TREE in full"
  [ -n "${QAB1215_CUR_DEV:-}${QAB1215_HEAD_1223:-}${QAB1215_BRIEF:-}${QAB1215_PROMPT:-}" ] && echo "  (a QAB1215_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1215_BRIEF:-}${QAB1215_PROMPT:-}${QAB1215_HEAD_1223:-}${QAB1215_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
