#!/bin/bash
# launch_qa_secuura_batch1204-t1.sh — cross-project QA agent, ONE BATCHED ROUND 1 TIER-1 gate over SEVEN Secuura/Blockchain PRs of round 20 (one pane,
# Secuura/Blockchain-B; Seat B 21st raised seat PRs 3, 6, 7 and its successor Seat B 22nd raised 8, 9, 10 and — on Wednesday's AMENDMENT 18:1x — 11):
# #1204 KS-851 test_only (PII surface, kyc tamper) · #1208 KS-1287 code_patch + the REGENERATED OpenAPI spec · #1207 KS-1245 bash_patch · #1209 KS-1033
# bash_patch (fail-closed design change) · #1210 KS-1239 code_patch (pure removal) · #1211 KS-1084 code_patch (the P0; two stages, one file) · PR 11
# KS-1143 self-testing code_patch (ONE file = product + test; red-first BY HUNK). TIER 1 on all seven. 14 paths; +503/-26; ZERO overlap with the tier-2 four.
# EVERY VALUE HERE IS A SEAT MEASUREMENT RE-DERIVED BY THE DRAFTER, never adopted: heads by ls-remote (branch AND refs/pull/N/head), blobs / modes / trees
# by a scratch clone FROM ORIGIN, the sub-tree / merged trees / END_TREE by REAL merge-tree chains in three orders (predict_batch_scratch_*.out).
# THE BASE MOVED: every head's parent is BASE 2bc5ccf63b8c40911afb568b03cace066238ffcf; develop was READ at generation as 72f480ca3584ce6eb2fb8ae87247135fbc3106ce (4 commits ahead of BASE — the tier-2
# squashes); the gate grades every merged tree and the END_TREE (073e658618cf5cbfb88308c1fa36e30c6cf30bec) over THAT develop. This launcher REFUSES if develop is not that reading
# (exit 17/18/19 — re-pin with repin_and_launch_gate20T1.sh, which re-reads, re-predicts and regenerates in ONE action).
# THE SHAPE per PR, read by the GitHub compare develop...head at EVERY run: merge_base == BASE, ahead 1, behind == 4, files as pinned (exit 10).
# exit 6:  any head is not at its branch AND at refs/pull/N/head on origin (the refusal names the PR) — a STALE HEAD REFUSES.
# exit 7:  the prompt must carry TIER 1 on all seven and each PR's own tier line.
# exit 8:  the prompt must open with the thinking directive and name the brief path + the READY capture.
# exit 10: the compare per PR (merge_base == BASE, ahead 1, behind == the pinned develop distance, files as pinned).
# exit 17/18/19: develop != the pinned launch develop, judged by CONTENT over the 14 targets (19 a tier-1 head blob LANDED; 18 a target CHANGED; 17 disjoint).
# exit 20: the READY capture AND the prompt must name every pinned head in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. `--check` runs headless (it launches nothing).
# exit 23: the prompt must carry the exact verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient, SEVEN verdict lines.
# exit 25: the MERGE ADDENDUM rules (ONE equality target PER PR FILE, the `## MERGE ADDENDUM` heading, KEY-FREE).
# exit 26: WEDNESDAY'S signed GO as each PR's merge authority.
# exit 30: the READY capture AND the prompt must BOTH carry the seat items (the BOTH list); MEASURE, not conclude; RULE WHETHER IT BLOCKS.
# exit 31: the prompt must name BASE, the launch develop and the END_TREE in full.
# exit 32: the READY capture AND the prompt must BOTH state which ticket each PR is (PR #1204 is KS-851. …).
# exit 33: the by-name keyword ladder.
# exit 34: PARTIAL — a PENDING-PR- or PR11-NOT-YET-RAISED token in the prompt, fewer than 7 rows, or a row whose head is not 40-hex.
# exit 35: the SELF-TESTING rule for PR 11 (red-first BY HUNK; the test hunk ALONE reds; the fix changes what the analyser counts).
# exit 36: the SPEC-REGENERATION rule for #1208 (the YAML is exactly what `npm run generate-openapi` produces from the head, with a control that FIRES).
# exit 37: this file is a CONTROL COPY (six rows, PR 11 not yet raised) — it can be --checked, never launched.
# exit 38: the BASE-MOVE rule (grade over the develop read at launch; tier-1 ∩ tier-2 = EMPTY; 0 bytes under services/auth/).
# exit 39: the BODY-CLAIMS rule (#1211 cross-tenant NOT measured + Part B; #1209 design change; #1210 the dangling-comment FINDING; the engine fix is tooling).
# QAB1204_CUR_DEV (test override, --check only): stands in for origin develop. QAB1204_HEAD_1212 (test override): stands in for the last row's head.
# QAB1204_BRIEF / QAB1204_PROMPT (test overrides): stand in for the READY capture / the prompt. A launch with any QAB1204_* override set refuses (exit 16).
# Generated by gatesets/2026-09-23_gate20T1_seatB/gen_launcher_gate20T1.py at 2026-09-23T08:54:44Z.
# Usage: launch_qa_secuura_batch1204-t1.sh [--check]
set -u
CONTROL_COPY=0
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
BRIEF="${QAB1204_BRIEF:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-23_gate20T1_seatB/mail_gate20T1_ready.md}"
PROMPT_FILE="${QAB1204_PROMPT:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-23_gate20T1_seatB/2026-09-23_secuura-batch1204-t1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
PRS=(
  "1204|KS-851|refs/heads/feature/ks-851-residues-from-the-round-2-gate-g-1-column-ordinal-r18-quotedname-1|6edffa3a96d08a96b4fd016b65bf12c10cd67869|1"
  "1208|KS-1287|refs/heads/feature/ks-1287-openapi-path-parameter-index-on-get-apistatusidcheckindex-is-r16b-pathrequired-1|c5e517eb3a80ca48df10b045b004c4daa8ccf5e2|3"
  "1207|KS-1245|refs/heads/feature/ks-1245-f-1-scriptssmoke-testsh107-fails-any-healthdeep-check-that-r16b-degradedwarn-1|aa4c486bedb4f647ec192cb4ebbe20e49a50d4ed|2"
  "1209|KS-1033|refs/heads/feature/ks-1033-residue-the-three-guards-that-could-not-be-wired-and-r17-missingbase-1|34f264cfbd8656860e4714f1a584fee1469f5a37|2"
  "1210|KS-1239|refs/heads/feature/ks-1239-r-1-the-indexts347-rawauthorization-capture-is-dead-code-0-r16b-rawauthdead-1|231ab8b5c898488b40ffe0c3672116b4bf5c80f7|2"
  "1211|KS-1084|refs/heads/feature/ks-1084-read-only-unverified-the-gateways-own-authorization-only-r16b-r17-sigtenant-tpvtenant-1|5c8e185513935dc6909710057ce1513962cca88c|3"
  "1212|KS-1143|refs/heads/feature/ks-1143-ks781-leg-f-guard-walk-a-mention-of-a-guard-bound-local-r19-guardmention-selftest-1|ebb5d85ee0ed7ea524c686c87d504d5fa114962b|1"
)
BASE_SHA='2bc5ccf63b8c40911afb568b03cace066238ffcf'
DEVELOP_SHA='72f480ca3584ce6eb2fb8ae87247135fbc3106ce'
DEV_BEHIND='4'
END_TREE='073e658618cf5cbfb88308c1fa36e30c6cf30bec'
# path|BASE blob or ABSENT|the head blob — the content judgement of a develop that is not the pinned launch develop
JUDGED=(
  "Blockchain/Dev/services/kyc/src/__tests__/ks386-no-image-payload-written.test.ts|8a4cb4eed74a1b4e60ce21129f3cd2fbeaf88a07|1515cd415d6acd30a64f0896463abe607f4cf30d"
  "Blockchain/Dev/services/vc-issuer/src/__tests__/ks1287-status-check-index-path-param-is-required.test.ts|ABSENT|c71651e8c48053909ca7c22d05b4acc626345b8f"
  "Blockchain/Dev/services/vc-issuer/src/vc-issuer.openapi.ts|6ab97ceb863a2d0a3725259670307d165918e9ba|a451d545b514fff23a23313330b7d330677e729e"
  "Blockchain/Dev/docs/openapi/secuura-api.yaml|1871025e2c1196aeb6ff33e9bc74b916d3eb9e9e|834b0c3d2d2c3b8b1d5af504338c804cfbb473b6"
  "Blockchain/Dev/scripts/__tests__/smoke_test_degraded_warns.test.sh|ABSENT|3a1b00d6f19ea6640fcc9046b6ce02ee7d8d8e11"
  "Blockchain/Dev/scripts/smoke-test.sh|d5d34357a0e4dd36d1ed951367a9ee189a337214|fb270385f40bc6a86ee4caacc679cf32ad76630c"
  "Blockchain/Dev/scripts/__tests__/check_no_demo_mutation_missing_base.test.sh|ABSENT|5c7fb19da54a1bf730d36798911b63399888bd49"
  "Blockchain/Dev/scripts/check-no-demo-mutation.sh|3b4af5b463b1d3045866c781b69b27408349b90c|4cc7c080b8a92c7bee7c76e836963ebec387910e"
  "Blockchain/Dev/services/api-gateway/src/__tests__/ks1239-index-takes-no-pre-auth-rawauthorization-copy.test.ts|ABSENT|77fad39207274ec08281c253f5dc7390dcfe6dfa"
  "Blockchain/Dev/services/api-gateway/src/index.ts|4e7fc1174d5453f9d6f71e3a69f166fc6a08db49|3bccc6696567d9ed1ea3a118b52599a7f017e89f"
  "Blockchain/Dev/services/api-gateway/src/__tests__/ks1084-signatories-forwards-x-tenant-id.test.ts|ABSENT|48340bf9a196eacbbbf8384e22cc4c0388ee63c6"
  "Blockchain/Dev/services/api-gateway/src/__tests__/ks1084-third-party-verifiers-forwards-x-tenant-id.test.ts|ABSENT|4f9f400122a7e68fc5a76a657e35c41ee7cef2d0"
  "Blockchain/Dev/services/api-gateway/src/routes/proxy.ts|795ae7ca3bdc76be3e563e87fc34a8cc221e5632|5168d809a51b366bab7bfb11c3cbfd2e844818e6"
  "Blockchain/Dev/packages/shared/src/__tests__/ks781-p3-3-body-parser-order.test.ts|bc4815c4ec9cae2f065e29dec6b938cdf49f2d23|9d0b59ae7199624247d635c31b019a9502ad701d"
)
[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief (READY capture) missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }
grep -qF 'PENDING-PR-' "$PROMPT_FILE" && { echo "REFUSING: the prompt is PARTIAL (a PENDING-PR- token) — a partial gate is not a gate" >&2; exit 34; }
[ "$CONTROL_COPY" = 1 ] || ! grep -qF 'PR11-NOT-YET-RAISED' "$PROMPT_FILE" || { echo "REFUSING: the prompt is the CONTROL prompt (PR 11 not yet raised) — never a launch prompt" >&2; exit 34; }
[ "${#PRS[@]}" -eq 7 ] || { echo "REFUSING: PARTIAL — ${#PRS[@]} rows, the tier-1 batch is 7 (#1204 #1207 #1208 #1209 #1210 #1211 and PR 11 KS-1143)" >&2; exit 34; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s' "$_h" | grep -qE '^[0-9a-f]{40}$' && printf '%s' "$_n" | grep -qE '^[0-9]+$' || { echo "REFUSING: PARTIAL — row '$_n $_t' has no pinned head ($_h): PR 11 not yet taken (take_pr11_gate20T1.sh)" >&2; exit 34; }
done
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF 'fleet/briefs_staged/2026-09-23_raise_seatB_21.md' "$PROMPT_FILE" && grep -qF 'mail_gate20T1_ready.md' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the brief path and the READY capture" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  [ "$_n" = "1212" ] && [ -n "${QAB1204_HEAD_1212:-}" ] && _h="$QAB1204_HEAD_1212"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong, or the PR is gone); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1204_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
if [ "$CUR_DEV" != "$DEVELOP_SHA" ]; then
  JUDGE="$(
    set -a; . "$SECUURA_ENV"; set +a
    JUDGED_FLAT="$(printf '%s\n' "${JUDGED[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request, urllib.parse
t = os.environ.get("GH_TOKEN", ""); base = "https://api.github.com/repos/Secuura/Distributed_Secuura/contents/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
worst = "DISJOINT"
for row in os.environ["JUDGED_FLAT"].splitlines():
    path, dev, landed = row.split("|")
    try: cur = get(base + urllib.parse.quote(path) + "?ref=" + os.environ["CUR_DEV"])["sha"]
    except Exception: cur = "ABSENT"
    if cur == dev: continue
    if cur in landed.split(","): print("LANDED", path, cur); worst = "LANDED"
    else: print("CHANGED", path, dev, "->", cur); worst = "CHANGED" if worst != "LANDED" else worst
print("VERDICT", worst)
PY
  )"
  printf '%s\n' "$JUDGE" >&2
  case "$JUDGE" in
    *"VERDICT LANDED"*) echo "REFUSING: a tier-1 target already LANDED on develop $CUR_DEV (the pinned launch develop is $DEVELOP_SHA) — a merge happened; re-pin" >&2; exit 19;;
    *"VERDICT CHANGED"*) echo "REFUSING: develop $CUR_DEV (the pinned launch develop is $DEVELOP_SHA) changed a tier-1 target path — re-predict by hand" >&2; exit 18;;
    *) echo "REFUSING: develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA (a disjoint move) — every merged tree and the END_TREE are unverified there: run repin_and_launch_gate20T1.sh (it re-reads, re-predicts and regenerates in one action)" >&2; exit 17;;
  esac
fi
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
base = os.environ["CUR_DEV"]
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf = pr.split("|")
    try:
        c = get(api + base + "..." + h); print("%s %s ahead=%d behind=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s\n' "$COMPARE" | grep -q "^${_n} ${BASE_SHA} ahead=1 behind=${DEV_BEHIND} files=${_f}\$" || _bad=1
done
if [ "$_bad" = 1 ]; then
  echo "REFUSING: a compare is not merge_base $BASE_SHA / ahead 1 / behind $DEV_BEHIND / files as pinned (develop moved, a head moved, or the API failed):" >&2
  printf '%s\n' "$COMPARE" >&2
  exit 10
fi
DEV_NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND commits ahead of BASE $BASE_SHA); ${#PRS[@]} compares merge_base == BASE, ahead 1, behind $DEV_BEHIND, files as pinned; END_TREE over it $END_TREE"
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the READY capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
done
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the READY capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
done
PROMPT_JOINED0="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in '#1204 T1' '#1208 T1' '#1207 T1' '#1209 T1' '#1210 T1' '#1211 T1' '#1212 T1'; do grep -qF -- "$_w" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '$_w'" >&2; exit 7; }; done
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'TIER 1 on all seven' && grep -qF -- 'round 1 of 2' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry TIER 1 on all seven / round 1 of 2" >&2; exit 7; }
for _w in \
  '(128, 0, 0, 128, 1)' \
  '.push-lock-20' \
  '/api/batch' \
  '0 bytes under `services/auth/`' \
  '073e658618cf5cbfb88308c1fa36e30c6cf30bec' \
  '08f413f2b6d99a5c8b58ae2e903bc9e8b60523f8' \
  '1 failed / 232 run' \
  '12/15' \
  '1515cd415d6a' \
  '1c36a7542970dc7ed2ae19abe66f2c1a9c9e55a3' \
  '231 passed / 231' \
  '231ab8b5c898488b40ffe0c3672116b4bf5c80f7' \
  '232 passed / 232' \
  '29/29' \
  '29e249e84057' \
  '2bc5ccf63' \
  '30/30' \
  '34f264cfbd8656860e4714f1a584fee1469f5a37' \
  '3a1b00d6f19e' \
  '3bccc6696567' \
  '48340bf9a196' \
  '4c3beea0b1e7' \
  '4c4abb587b5a6a539d16afe20459166b40ffbaea' \
  '4cc7c080b8a9' \
  '4f9f400122a7' \
  '513390fde5d2e1626af60243ea72f458301d6844' \
  '5168d809a51b' \
  '5c7fb19da54a' \
  '5c8e185513935dc6909710057ce1513962cca88c' \
  '655c450d8f3eee7a45db23ad8c9ebd317314e4b4' \
  '6edffa3a96d08a96b4fd016b65bf12c10cd67869' \
  '72f480ca3584ce6eb2fb8ae87247135fbc3106ce' \
  '735c31b2c56615634c43cb444c60db7189e747da' \
  '742 -> 746' \
  '77fad3920727' \
  '834b0c3d2d2c' \
  '834b0c3d2d2c3b8b1d5af504338c804cfbb473b6' \
  '864c199baf389172cfa948685c72f9cc597268ac' \
  '8a67471cef2c' \
  '917/917' \
  '918/918' \
  '9d0b59ae7199' \
  'CONTROL 2' \
  'GO: merge #1204, #1207, #1208, #1209, #1210, #1211, #1212 batch' \
  'In Progress' \
  'KS-1033' \
  'KS-1084' \
  'KS-1143' \
  'KS-1239' \
  'KS-1245' \
  'KS-1287' \
  'KS-851' \
  'MID_BLOB' \
  'PROTOCOL-CLEAN' \
  'Part B' \
  'QUOTEDWRITE' \
  'SKIPPED' \
  'SMOKE_BASE_URL' \
  'TS2322' \
  'a451d545b514' \
  'aa4c486bedb4f647ec192cb4ebbe20e49a50d4ed' \
  'baseline.api-gateway.json' \
  'bc4815c4ec9c' \
  'c5e517eb3a80ca48df10b045b004c4daa8ccf5e2' \
  'c71651e8c480' \
  'calls the P0 closed' \
  'check_no_demo_mutation_base.test.sh' \
  'contributes' \
  'cross-tenant effect is NOT measured' \
  'd13a26e19c8d1b2faf25f9e41cc087fbcd51ec47' \
  'ebb5d85ee0ed7ea524c686c87d504d5fa114962b' \
  'ee5c6b40654e9626d97f278c61dcf0f738f47496' \
  'exit 2' \
  'f85c25b427cd9fd5962d1b9b323e4ed57b2f335e' \
  'fb270385f40b' \
  'ks1215-the-connector-branch-never-carries-the-callers-bearer.test.ts' \
  'ks1238-hand-forwarded-routes-send-no-caller-bearer.test.ts' \
  'login_stub' \
  'raise20.py.pre-0755-hunkcum' \
  'raise20.py:509' \
  'required: false' \
  'required: true' \
  'routes/platform.ts:204' \
  'scripts/preflight/preflight.sh:670' \
  'scripts/run-code-guards.sh:116' \
  'stopped-ks1084' \
  'testonlyopts' \
  'verify_pr21.py'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the READY capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
grep -qF 'MEASURE, not conclude' "$PROMPT_FILE" && grep -qF 'RULE WHETHER IT BLOCKS' "$PROMPT_FILE" || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS missing" >&2; exit 30; }
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s+", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in \
  'TIER AND ROUND' \
  'ASSIGN the tier from the files' \
  'STATE BOTH' \
  'round 1 of 2' \
  'PRODUCT vs SCRIPT vs TEST-FILE-ONLY vs GENERATED exactly as each READY declares' \
  'TREES over `2bc5ccf63` AND over the launch develop' \
  'in >= 3 orders' \
  '0 overlap with the tier-2 four' \
  'CANONICAL-PATCH IDENTITY' \
  'CELLS per lane' \
  'read, do not compose' \
  'PER-FILE TYPECHECK DELTA 0' \
  'CENSUS v2' \
  'NEVER connect' \
  'LINEAR LINK HYGIENE' \
  'attachmentsForURL per PR exactly its own key' \
  'subjects <= 92 chars ASCII' \
  'THE ONE-PANE TWO-SEAT ARTEFACTS' \
  'BOARD GUARD' \
  'THE SEATS'"'"' OWN FINDINGS/SLIPS' \
  'CONFIRMED / REFUTED' \
  'INTERMITTENTS per PR (do not block)' \
  'RULE WHETHER IT BLOCKS' \
  'MERGE ADDENDUM' \
  'SEVEN lines VERBATIM in report.md' \
  '1/3/2/2/2/3/1' \
  'stays In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'READ THE WHOLE TEST FILE' \
  'NOT-TESTED first' \
  'CONTEXT RULE' \
  'at ctx 80' \
  'BASE_GO' \
  'END_TREE' \
  '## MERGE ADDENDUM' \
  'MEASURE, not conclude' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'node_modules PER ENTRY' \
  'never print a credential value' \
  'No memory maintenance' \
  'NOT-TESTED.written-first.md' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '[QA -> Wednesday] TIER-1 BATCH GATE #1204-#' \
  'fleet/briefs_staged/2026-09-23_raise_seatB_21.md' \
  'fleet/briefs_staged/2026-09-23_raise_seatB_22.md' \
  'WEDNESDAY'"'"'S signed GO naming each head' \
  'Never enter any seat worktree' \
  '2026-09-23_seatB-21st' \
  '2026-09-23_seatB-22nd' \
  'HANDOVER-seatB-21st-successor-2026-09-23.md' \
  'mail_gate20T1_ready.md' \
  'THE BASE MOVED' \
  'the merging seat must re-predict' \
  'Datasec files and mail are out of scope entirely' \
  'CARRY-FORWARD' \
  'AMENDMENT 18:1x' \
  'KS-1143-R19-SELFTEST.md' \
  'smoke-test.sh is 100755' \
  'RE-READ develop at your start' \
  'LEG F'; do
  printf '%s' "$PROMPT_JOINED" | grep -qF -- "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE GATE PROVES RED-FIRST BY HUNK' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'the W6 cell hunk ALONE at BASE reds' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'CHANGES WHAT THE ANALYSER COUNTS, NOT JUST THAT THE SUITE IS GREEN' || { echo "REFUSING: the PR 11 self-testing rule (red-first by hunk, the W6 hunk alone reds, the fix changes what the analyser counts) is not in the prompt" >&2; exit 35; }
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE GATE VERIFIES THE YAML IS EXACTLY WHAT `npm run generate-openapi` PRODUCES FROM THE HEAD' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'a planted control that FIRES' || { echo "REFUSING: the #1208 spec-regeneration rule (the YAML == the generator's output at the head, with a control that fires) is not in the prompt" >&2; exit 36; }
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'grade over the develop read at launch' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'tier-1 ∩ tier-2 = EMPTY' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- '0 bytes under `services/auth/` across all 14 paths' || { echo "REFUSING: the base-move rule (grade over the launch develop; tier-1 ∩ tier-2 empty; 0 bytes under services/auth/) is not in the prompt" >&2; exit 38; }
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE CROSS-TENANT EFFECT IS NOT MEASURED AND THE BODY MUST SAY SO' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'Part B (`/api/batch`) is OUT' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE GATE CHECKS THE BODY SAYS SO' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE RULED DANGLING-COMMENT FINDING MUST BE IN THE BODY AS STATED, NOTHING FIXED OR FILED' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'THE SEAT'"'"'S TOOLING, NOT THE PRODUCT' || { echo "REFUSING: the body-claims rule (#1211 cross-tenant NOT measured + Part B; #1209 design change; #1210 FINDING; the engine fix is tooling) is not in the prompt" >&2; exit 39; }
grep -qF -- "WEDNESDAY'S signed GO naming each head" "$PROMPT_FILE" || { echo "REFUSING: merge authority" >&2; exit 26; }
grep -qF -- '## MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF -- 'ONE equality target PER PR FILE' "$PROMPT_FILE" && grep -qF -- 'KEY-FREE' "$PROMPT_FILE" || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-1 BATCH GATE #1204-#' "$PROMPT_FILE" && grep -qF -- 'FROM coagent@agentmail.to' "$PROMPT_FILE" && grep -qF -- 'SEVEN lines, one per PR' "$PROMPT_FILE" || { echo "REFUSING: the verdict subject / sender / seven lines" >&2; exit 23; }
grep -qF -- "$END_TREE" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$BASE_SHA" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the END_TREE not in full" >&2; exit 31; }
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  [ "$CONTROL_COPY" = 1 ] && echo "  *** CONTROL COPY — six rows, PR 11 not yet raised; it can never launch (exit 37) ***"
  echo "  heads on origin (branch AND refs/pull/N/head):$HEADS_NOTE"
  echo "  compares (GitHub API), develop...head per PR (merge_base + ahead + behind + files):"
  printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  $DEV_NOTE"
  echo "  READY capture, prompt, QA project and repo all present; ${#PRS[@]} rows each with a 40-hex head; the prompt is not PARTIAL; opens with the thinking directive; names the brief path and the capture"
  echo "  prompt carries TIER 1 on all seven and each PR tier (#1204 T1 #1208 T1 #1207 T1 #1209 T1 #1210 T1 #1211 T1 #1212 T1); round 1 of 2"
  echo "  READY capture and prompt both name every pinned head in full and which ticket each PR is"
  echo "  READY capture and prompt BOTH carry the seat items (88 tokens); the prompt says MEASURE, not conclude, and RULE WHETHER IT BLOCKS"
  echo "  prompt carries the by-name items (67 keywords), the PR 11 self-testing rule, the #1208 spec-regeneration rule, the base-move rule, the body-claims rule, the merge authority, the MERGE ADDENDUM rules, the verdict subject / sender / seven lines, BASE / the launch develop / the END_TREE in full"
  [ -n "${QAB1204_CUR_DEV:-}" ] && echo "  (develop read from the QAB1204_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$CONTROL_COPY" = 1 ] && { echo "REFUSING: this is a CONTROL COPY (six rows, PR 11 not yet raised) — it is never launched" >&2; exit 37; }
[ -z "${QAB1204_BRIEF:-}${QAB1204_PROMPT:-}${QAB1204_HEAD_1212:-}${QAB1204_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
