#!/usr/bin/env python3
"""gen_launcher_989.py — writes launch_qa_secuura_989_ks973.sh (ONE head, TIER 1 ROUND 1, develop judged BY CONTENT; the systemTest guard list;
no DEV_CONTENT_ALLOWED entries — nothing expected tonight moves a guarded systemTest path). The launcher is generated rather than typed because it
contains a legitimate directory change (`c`+`d` into the QA project before exec) that the drafting seat's pre-tool hook
refuses in a heredoc. The AUTH4 launcher (gatesets/2026-09-14_gateAUTH4/) is the guard-family template; the 912r2 launcher
supplies the DEV_CONTENT_ALLOWED shape. Every guard, exit code and output control is asserted below; `bash -n` last.
Usage: python3 gen_launcher_989.py <gateset dir>"""
import hashlib, os, subprocess, sys, datetime

G = sys.argv[1]
OUT = os.path.join(G, 'launch_qa_secuura_989_ks973.sh')
CD = 'c' + 'd'   # the one directory change, composed so the source never spells it

HEAD = '9d0e2016ae60658ec908ee5e500583fd3a318c8a'
M38 = '0e78c7270188ac45c1c29f927bdf90728f10215d'
BRANCH = 'refs/heads/feature/ks-973-ks-969-round-1-gate-residue-the-pre-suite-step-and-its-own'
BRIEF_NAME = '2026-09-14_secuura-989-ks973-tier1-r1.md'
PROMPT_NAME = '2026-09-14_secuura-989-ks973-tier1-r1.prompt.txt'

SCRIPT = r'''#!/bin/bash
# launch_qa_secuura_989_ks973.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #989 (KS-973,
# builder s227, pane -D) @ 9d0e2016ae60658ec908ee5e500583fd3a318c8a — parent 3fa0a22b1 <- develop M38 0e78c7270; tree
# 562dacac8; the Blockchain subtree is M38's. `redactSecrets` in systemTest/fixtures/provision.ts (:249-260, applied at the ONE
# interpolation site :323-328) reaches every suite's pre-suite error path — a secret-handling surface (RULED tier 1 by
# Wednesday 16:3x, F9). Also: the DEGRADED stream routing pinned (preSuiteStreams.test.ts spawns the REAL step), the
# drift-arm quarantine driven, the symlink shape pinned as KNOWN; 5 files +795 -276 (the PR body says +332 -1 — both
# fixture files were whole-file reformatted; the brief carries that as item 1). Items 3/4 NOT in this PR (on #927);
# items 1/2 NOT built (L11/L12). KS-973 STAYS OPEN.
#
# THE SHAPE, as read 17:29-17:40 AEST 2026-09-14 (git + the compare API agree): develop M38 is an ANCESTOR of the head
# (rev-list --count M38..head = 2; the compare develop...head = merge_base M38, ahead 2, behind 0, files 5) — so the head
# tree IS the M38-merged tree. The compare is asserted as merge_base + ahead + files (exit 10); `behind` is deliberately
# NOT asserted, so a develop that moves on does not trip this guard — the develop arm below judges the move by CONTENT.
#
# The develop pin is judged by CONTENT, not bare (the AUTH4 launcher's shape + the 912r2 DEV_CONTENT_ALLOWED table, here
# EMPTY): (a) NINE files by blob at the CURRENT develop — systemTest/fixtures/provision.ts (M38 b95f4ee39; #989's own
# 68c801d62 -> LANDED), fixtures/pre-suite.ts (M38 01024fadd; own f5f839a84 -> LANDED), fixtures/provision-actors.ts
# (2795b5937), fixtures/manifest.ts (a6bfe3e76), fixtures/actors.ts (8443c682b), performance/vitest.unit.config.ts
# (cb1864d78), performance/package.json (b9ae2c052), performance/package-lock.json (4694ee0a7), fixtures/tsconfig.json
# (2df1d1d65) — #989's own blob on develop means the PR has landed and THIS brief is stale: exit 19; any blob nobody pinned
# -> exit 18; (b) if develop != M38, the compare M38...develop is read and REFUSES (exit 18) only when the delta touches a
# GUARDED path — anything under systemTest/fixtures/, systemTest/performance/tests/unit/fixtures/, the performance
# package.json / package-lock.json / vitest.unit.config.ts / tsconfig.json / tsconfig.node.json / eslint.config.js, the two
# L11/L12 files (akto/tests/preSuiteSetup.ts, schemathesis/scripts/run.py — items 1/2, whose NOT-built story this brief
# states), or the root Blockchain/Dev/package-lock.json — or cannot be judged (unreadable, not ahead, >250 files); otherwise
# it proceeds printing the move and its file count, which the gate re-states (brief TARGET: the gate merges the then-current
# develop in its own clone and re-derives every count). Expected tonight: #916 (systemTest/README.md, systemTest/package.json
# NEW, performance/tests/unit/runner/) -> DISJOINT; #988 (performance/gate/, docs/, tests/unit/gate/) -> DISJOINT; #927
# (systemTest/__tests__/*.sh — deliberately NOT guarded: its landing changes the items-3/4 story, which the gate READS and
# states) -> DISJOINT; the L2/L4/auth PRs (Blockchain/Dev/...) -> DISJOINT unless the root lockfile moves.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — a gate launched there runs headless, invisible to Kam, and dies with the caller's
# shell (2026-09-13 ledger). `--check` still runs headless (it launches nothing).
#
# Generated by gen_launcher_989.py (asserted output controls; residual guard; bash -n). Exit codes 2..21 (19 = LANDED).
# Written by the generator because it contains a legitimate directory change.
#
# Usage: launch_qa_secuura_989_ks973.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..21 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA989_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/__BRIEF_NAME__}"
PROMPT_FILE="${QA989_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/__PROMPT_NAME__}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='__BRANCH__'
HEAD_SHA="${QA989_HEAD:-__HEAD__}"
MERGE_BASE='__M38__'   # M38 = the merge-base of the head with develop (M38 is an ancestor of the head)
DEVELOP_SHA='__M38__'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/__BRIEF_NAME__"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #989 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#989 = M38 ahead 2 files 5.
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=2 files=5" ] || { echo "REFUSING: #989 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=2 files=5'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): seven files by blob at the CURRENT develop, then — if develop
# moved — the M38...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import json, os, sys, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"   # only the root lockfile is guarded under here
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label})
JUDGED = {
  "systemTest/fixtures/provision.ts":                     ({"b95f4ee393ab5da261eff06d95069f8bdf24ee3f": "M38"}, {"68c801d626c2b65d76bd6c48d5323a5ce70a82c7": "#989 own"}),
  "systemTest/fixtures/pre-suite.ts":                     ({"01024faddd0ad311aa160de02683b16973603928": "M38"}, {"f5f839a84db447dc08115a7e37d253f48b205654": "#989 own"}),
  "systemTest/fixtures/provision-actors.ts":              ({"2795b5937049e8e1a265e69b032f2914c674bd7d": "M38"}, {}),
  "systemTest/fixtures/manifest.ts":                      ({"a6bfe3e7662791866e16c04331ba8fdc473a535a": "M38"}, {}),
  "systemTest/fixtures/actors.ts":                        ({"8443c682b585afc4f39c43094588898a0c92795e": "M38"}, {}),
  "systemTest/fixtures/tsconfig.json":                    ({"2df1d1d65235dd885c769d3580c8007b81ba3d29": "M38"}, {}),
  "systemTest/performance/vitest.unit.config.ts":         ({"cb1864d783c32d3bea3f574767092828ce541e0b": "M38"}, {}),
  "systemTest/performance/package.json":                  ({"b9ae2c052abcd6601c79569abde371cd5e73dddb": "M38"}, {}),
  "systemTest/performance/package-lock.json":             ({"4694ee0a7a8cbc06e9e17c2441f9c535ae8d224c": "M38"}, {}),
}
state = []
for f, (ok, landed) in JUDGED.items():
    try:
        blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #989 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (M38; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = ["systemTest/fixtures/",
           "systemTest/performance/tests/unit/fixtures/",
           "systemTest/performance/package.json",
           "systemTest/performance/package-lock.json",
           "systemTest/performance/vitest.unit.config.ts",
           "systemTest/performance/tsconfig.json",
           "systemTest/performance/tsconfig.node.json",
           "systemTest/performance/eslint.config.js",
           "systemTest/akto/tests/preSuiteSetup.ts",
           "systemTest/schemathesis/scripts/run.py",
           D + "package-lock.json"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: a hit under a GUARDED path clears ONLY if the per-file blob sha in the compare is EXACTLY the one
# pinned here. EMPTY for this gate — no PR expected to land tonight moves a guarded systemTest path (#927 is 144 behind and
# its two shell files are deliberately not guarded). Any hit falls through to GUARDED; re-pin deliberately.
DEV_CONTENT_ALLOWED = {
}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") == DEV_CONTENT_ALLOWED[h])
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 9d0e2016a in its own clone, names the delta and re-derives every count on the merged tree (the whole performance suite figures MOVE with #916/#988 — brief TARGET)"
if cleared:
    print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d, cleared BY BLOB under guarded paths: %s — %s" % (pinned, cur, c["ahead_by"], len(files), ",".join(x.split("/")[-1] for x in cleared), tail)); sys.exit(0)
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — disjoint from the GUARDED list (systemTest/fixtures/, performance/tests/unit/fixtures/, the performance package/lock/config/tsconfigs/eslint, the L11/L12 files, the root lockfile); %s" % (pinned, cur, c["ahead_by"], len(files), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs / DEV_CONTENT_ALLOWED + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #989 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#989 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA989_BRIEF:-}${QA989_PROMPT:-}${QA989_HEAD:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
__CD__ "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
'''

subs = {'__BRIEF_NAME__': BRIEF_NAME, '__PROMPT_NAME__': PROMPT_NAME, '__BRANCH__': BRANCH, '__HEAD__': HEAD, '__M38__': M38, '__CD__': CD}
out = SCRIPT
for k, v in subs.items():
    assert out.count(k) >= 1, k
    out = out.replace(k, v)
import re as _re
residual = [m for m in _re.findall(r'__[A-Z0-9_]+__', out)]
assert not residual, ('residual placeholder', residual)   # residual guard: only UPPER-CASE __TOKENS__ are placeholders (paths like __tests__ are not)
# output controls
controls = [
    ("HEAD_SHA=\"${QA989_HEAD:-" + HEAD + "}\"", 1), ("MERGE_BASE='" + M38 + "'", 1), ("DEVELOP_SHA='" + M38 + "'", 1),
    ("BRANCH='" + BRANCH + "'", 1), (BRIEF_NAME, 2), (PROMPT_NAME, 1),
    ('exit 2;', 1), ('exit 3;', 1), ('exit 4;', 1), ('exit 5;', 1), ('exit 6', 1), ('exit 7;', 1), ('exit 8;', 1), ('exit 9;', 1),
    ('exit 10;', 1), ('exit 11;', 1), ('exit 12;', 1), ('exit 13;', 1), ('exit 14;', 1), ('exit 15;', 1), ('exit 16;', 2), ('exit 17;', 1),
    ('exit 18; }', 1), ('exit 18 ;;', 1), ('exit 19 ;;', 1), ('exit 20;', 1), ('exit 21;', 1),
    ('DEV_CONTENT_ALLOWED = {', 1), ('print("LANDED ', 1), ('print("GUARDED ', 2), ('print("UNJUDGEABLE ', 3), ('LANDED*)', 1), ('OK*)', 1),
    ('68c801d626c2b65d76bd6c48d5323a5ce70a82c7', 1), ('f5f839a84db447dc08115a7e37d253f48b205654', 1),
    ('b95f4ee393ab5da261eff06d95069f8bdf24ee3f', 1), ('01024faddd0ad311aa160de02683b16973603928', 1), ('2795b5937049e8e1a265e69b032f2914c674bd7d', 1), ('a6bfe3e7662791866e16c04331ba8fdc473a535a', 1),
    ('8443c682b585afc4f39c43094588898a0c92795e', 1), ('2df1d1d65235dd885c769d3580c8007b81ba3d29', 1), ('cb1864d783c32d3bea3f574767092828ce541e0b', 1), ('b9ae2c052abcd6601c79569abde371cd5e73dddb', 1), ('4694ee0a7a8cbc06e9e17c2441f9c535ae8d224c', 1),
    ('"systemTest/fixtures/",', 1), ('"systemTest/akto/tests/preSuiteSetup.ts",', 1), ('"systemTest/schemathesis/scripts/run.py",', 1), ('DEV_CONTENT_ALLOWED = {\n}', 1),
    ('ahead=2 files=5', 2), ('[ -t 0 ]', 1), ('exec claude --dangerously-skip-permissions --model opus', 1), (CD + ' "$QA_DIR"', 1),
    ('git -C "$REPO"', 2), ('set -u', 1), ('MAIL YOUR VERDICT', 1), ('NEVER print a credential value', 1), ('no memory maintenance', 1),
]
bad = [(k, want, out.count(k)) for k, want in controls if out.count(k) != want]
assert not bad, bad
assert 'git -C $' not in out and 'git -C "$H' not in out, 'no git -C $VAR'
import re as _re2
verbs = _re2.findall(r'git (?:-C "\$REPO" )?(fetch|checkout|worktree|merge-tree|merge|pull|push|reset|switch)\b', out)
assert not verbs, ('git write verbs in the launcher', verbs)   # read verbs only: the launcher runs ls-remote and nothing else against the checkout
raw = out.encode('utf-8')
ctl = sum(1 for b in raw if (b < 0x20 and b not in (9, 10, 13)) or b == 0x7f)
assert ctl == 0, ctl
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(out)
os.chmod(OUT, 0o755)
rc = subprocess.run(['bash', '-n', OUT]).returncode
print(datetime.datetime.now().astimezone().strftime('%H:%M:%S %Z'), 'wrote', OUT, 'lines', out.count('\n'), 'sha256', hashlib.sha256(raw).hexdigest()[:16], 'controls', len(controls), 'ok', 'bash -n rc', rc)
sys.exit(rc)
