#!/bin/bash
# launch_qa_secuura_batch1357.sh — cross-project QA agent, ONE gate (gate49b, round 49b) over TWO Secuura/Blockchain PRs, FROZEN at TWO, plus a POST-MERGE AUDIT of #1358:
# #1357 KS-1054 (T1, ITEM 1a: a present-but-broken python3 fails closed) · #1359 KS-1054 (T1, ITEM 1c: the rc-1 wording in deploy.sh / deploy-all.sh),
# both by Seat B 49th, merged by Seat D 1st on ONE GO. #1358 KS-1380 (merged by PeterObeden 07:28:02Z, before any gate) is audited, no GO.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate49b.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-30T07:47:21Z.
# develop d8b6c2a7a520ad715417435cde235346c92f7acc; END_TREE d485add27eabcbbcfa12242158d14cafd71bb01b (the simulated squash chain, all 6 orders). Shape copied from gate49a's launcher, three rows.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  a head is not at its branch AND refs/pull/<n>/head on origin.   exit 8: thinking directive / the kit files named + present / an unfilled token / row count.
# exit 10: the GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name each head in full.   exit 7: the tier lines + FROZEN at THREE + the rounds + the tiering rule.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state each ticket.   exit 33: the by-name keyword ladder (each keyword AS A TOKEN).   exit 39: the HOLDS + the named exceptions.
# exit 34: the BEHAVIOUR-FIRST rule.   exit 36: the authority line.   exit 26: merge authority + the ONE GO string + the merge seat + the order.
# exit 37: the LEG-14 trap.   exit 40: the POST-MERGE AUDIT section + its verbatim statement.   exit 38: the client-comment rule.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST.   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G49B_* test override set.
# G49B_CUR_DEV / G49B_HEAD_<n> / G49B_PATHS_<n> / G49B_BRIEF / G49B_PROMPT: test overrides (--check only).
# Generated by fill_gate49b.py at 2026-09-30T07:49:13Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1357.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-30_gate49b'
BRIEF="${G49B_BRIEF:-$GS/mail_gate49b_ready.md}"
PROMPT_FILE="${G49B_PROMPT:-$GS/2026-09-30_secuura-batch1357.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1357|KS-1054|refs/heads/feature/ks-1054-a-present-but-broken-python3-fails-closed-b47-1|236f9dce38982c17bf5868f3a3ec17c08393d871|2|1|377989cf3829e46cf47ef957746f01c2f600a370|13|Blockchain/Dev/deployment/azure/check-startup-migrations.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_scripts_read_startup_migrations.test.sh|T1"
  "1359|KS-1054|refs/heads/feature/ks-1054-rc1-reads-failed-or-unverified-b49-1c|acac1f5e28ea4c983891dc50d7ed4b08a34d7e39|4|1|377989cf3829e46cf47ef957746f01c2f600a370|13|Blockchain/Dev/deployment/azure/deploy-all.sh,Blockchain/Dev/deployment/azure/deploy.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_all_rc1_message.test.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_sh_rc1_message.test.sh|T1"
)
DEVELOP_SHA='d8b6c2a7a520ad715417435cde235346c92f7acc'
END_TREE='d485add27eabcbbcfa12242158d14cafd71bb01b'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate49b.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is TWO PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
for _f in mail_gate49b_ready.md COMMISSION.md lockdelta_1.out overlaps_1.out gh_read_1.out keyscan_1.out claims_1.out drafts_gate49b.md gh_body_1357.md gh_body_1359.md gh_body_1358.md; do
  [ -s "$GS/$_f" ] && grep -qF "$GS/$_f" "$PROMPT_FILE" || { echo "REFUSING: the kit file $GS/$_f is missing, empty, or not named in the prompt" >&2; exit 8; }
done
grep -qF "2026-09-30-batch1356-g49a/report.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the previous round report (gate49a)" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
grep -qF '<''PR>' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unpinned PR placeholder" >&2; exit 8; }   # spelled split so this file itself carries no placeholder
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + every branch + every pull/head
CUR_DEV="${G49B_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate49b.sh (it re-pins and re-fills in one action)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G49B_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G49B_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
for _pk in '1357|KS-1054' '1359|KS-1054' '1358|KS-1380'; do
  _pn="${_pk%|*}"; _pt="${_pk#*|}"
  has "PR #$_pn is $_pt" && grep -qF -- "#$_pn is $_pt" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state 'PR #$_pn is $_pt'" >&2; exit 32; }
done
has '#1357 T1' && has '#1359 T1' && has 'The gate is FROZEN at TWO PRs' && has 'TIER 1 = THE DEPLOY PATH' && has 'ROUND 1 of 2 on its class' && has 'a round-1 NO GO goes back to the author for round 2' && has 'ship the closed instances, ticket the residue' || { echo "REFUSING: the tier lines / FROZEN at TWO / the rounds / the tiering rule" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control" >&2; exit 33; }
for _w in POST-MERGE-AUDIT MERGED-BEFORE-GATE CLEAN-MERGE DISJOINT END-TREE ORDER-INDEPENDENT MODES EXEC-BITS COLLISION-CENSUS BEHAVIOUR-1357 RED-FIRST-1357 PREDICATE-CONTRACT CALLERS-READ RULING-VERBATIM BEHAVIOUR-1359 GOLDENS-BYTE-EQUAL RED-FIRST-1359 NO-COUNTER-CHANGE MESSAGE-TRUE IMAGE-BUILDS LOCK-DELTA-15 LANDED-EQUALS-HEAD DEPENDENT-RANGES REGISTRY-TRUE LOCK-AGREEMENT AUDIT-LEGS-DEVELOP TSC-NOT-A-RED-PROOF SUITES SHELL-RUNNER SHARED-BUILT-FIRST SUBJECT-KEY-SCAN SUBJECT-LANDS-AT SUBJECT-TRUE-OF-DIFF REFS-OWN-KEY NO-CLOSING-KEYWORD PR-BODY-CLAIMS DRAFTED-COMMENTS NO-REPEAT-49AFF833 FOLLOW-ONS FUSE-COUNT OUT-OF-SCOPE TIERING DISK-ENOSPC REPORT-HASH-LAST; do   # AS A TOKEN: bounded by a non-[A-Za-z0-9-] character (MODES is not satisfied by MODES-X)
  printf '%s' "$PROMPT_JOINED" | grep -qE -- "(^|[^A-Za-z0-9-])$_w([^A-Za-z0-9-]|\$)" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'you EXECUTE the changed code' && has 'the BEHAVIOUR line FIRST' && has 'A NOT MEASURED behaviour line on a T1 PR is not a GO' || { echo "REFUSING: the BEHAVIOUR-FIRST rule" >&2; exit 34; }
has 'The 09-09 baseline grant is NOT used.' && has 'Its STOP conditions' && has 'an ordinary gated change under v1.3' || { echo "REFUSING: the authority line" >&2; exit 36; }
has 'THE LEG-14 TRAP (SHARED-BUILT-FIRST)' || { echo "REFUSING: the LEG-14 trap" >&2; exit 37; }
has 'POST-MERGE AUDIT of #1358 (T2, information + findings; no GO is needed for it)' && has '#1358 was merged by PeterObeden at 07:28:02Z as a merge commit, before any gate.' && has 'with no judgement words' && has 'The #1358 audit writes NO GO' || { echo "REFUSING: the POST-MERGE AUDIT section / its verbatim statement" >&2; exit 40; }
has 'every sentence carries its instrument or "unmeasured"' && has 'POST AS-IS / POST AMENDED' && has 'Nothing is posted by you.' || { echo "REFUSING: the client-comment rule" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' && has 'Never read or write a real `.env`' && has 'Docker runs are `--rm --network none` with the source mounted READ-ONLY' && has 'NO checklist tick' && has 'no Akto scan against any stack' && has 'No audit-baseline row edited' && has 'THE NAMED EXCEPTIONS to those holds — these and NO others' && has 'NEVER `up`, `down`' && has '"no lock regenerated" means no REAL lock' && has '`deploy.sh` / `deploy-all.sh` are NEVER run whole' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the heads" && has 'GO (Seat D 1st): merge 1357 1359 on gate49b' && has 'The merge seat for both PRs is Seat D 1st' && has 'in the order #1357 -> #1359, on the ONE GO' || { echo "REFUSING: merge authority / the GO string / the merge seat / the order" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE, naming EACH PR' && has 'KEY-FREE' && has 'MG-11 subject <= 92' && has 'the FLEET STOP after this merge' && has 'MG-1 2 over 2 then 4 over 4 paths' && has 'tree <per-step tree>' && has 'BASELINE audit-baseline.json == develop blob' && has 'FUSE 2026-10-09 rows at END' && has 'EVERY SUBJECT YOU PROPOSE MUST BE TRUE OF THE DIFF' && has 'the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE49B #1357 #1359 (Seat D1 merger; T1 KS-1054 broken python3 fails closed + T1 KS-1054 rc-1 wording) + POST-MERGE AUDIT #1358 (T2 KS-1380)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-09-30-batch1357-g49b/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G49B_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-500
  echo "  capture, lockdelta / overlaps / gh / keyscan / claims reads, the drafts table, the three PR bodies (#1358's for the audit), prompt, QA project and repo present; kit at its filled home; TWO rows; thinking directive; every kit file + commission + gate49a report named; no unfilled token, no PR placeholder"
  echo "  2 of 2 heads at branch AND pull/head (whole-field); the GitHub compare == the pins for each; capture and prompt BOTH carry every head in full and every ticket"
  echo "  the prompt carries 44 by-name keywords (as tokens), the tier lines, the BEHAVIOUR-FIRST rule, the authority line, the LEG-14 trap, the post-merge audit section, the client-comment rule, the holds + named exceptions, the GO string, merge seat and order, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G49B_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
