#!/bin/bash
# launch_qa_secuura_batch1290.sh — cross-project QA agent, ONE BATCH gate (gate29, tiers 1 and 2) over 2 Secuura/Blockchain PRs of round 29, FROZEN at two:
# #1290 KS-1341 (B 31st (local-model patch, Spark spark-dsv4flash under Wednesday's brief-B rev B, re-verified by the seat), T1) · #1291 KS-1337 (B 31st (local-model patch, Ornith, product hunk byte-identical; test file + the package's own eslint --fix per Wednesday's ruling (b)), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate29.py, a --no-local scratch clone fetched from origin) at 2026-09-26T09:21:11Z, never adopted
# from a mail. develop at generation 179a4f32ec0643689b55a8d7207e63f6ec3d3831; the PRs' merge-bases: 179a4f32ec0643689b55a8d7207e63f6ec3d3831 for #1290, #1291; END_TREE 0cc6669f3a6ed3ac2841e9cf17c6229e890e0250.
# The compare check is three-dot (develop...head): merge_base, ahead, behind AND the file NAMES, per PR.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate29.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  two rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate29.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at two.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the #1290 T1 runtime probe. exit 41: the #1290 arm R3. exit 49: the #1290 rotate-secret secret path. exit 42: the #1290 declared two. exit 44: the #1291 red design and disclosure. exit 43: the #1291 own lint and unit suite. exit 37: the #1291 fleet STOP NOT APPLICABLE. exit 35: no Docker / no stack / no port. exit 47: the MG-3 key scan. exit 46: the Linear link kinds.
# QAB29_CUR_DEV / QAB29_HEAD_<n> / QAB29_PATHS_<n> / QAB29_BRIEF / QAB29_PROMPT: test overrides (--check only); a launch with any QAB29_* set refuses (16).
# Generated by fill_gate29.py at 2026-09-26T09:27:36Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1290.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/private/tmp/claude-501/-Volumes-DevMASTER-WEDNESDAY/d0b2ec3e-4b50-4d96-87d2-4a998799b9cd/scratchpad/gate29'
BRIEF="${QAB29_BRIEF:-$GS/mail_gate29_ready.md}"
PROMPT_FILE="${QAB29_PROMPT:-$GS/2026-09-26_secuura-batch1290.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1290|KS-1341|refs/heads/feature/ks-1341-webhooks-500-part-b-b31-3|a53228515d25b6652b998de7279659df6b4e1c66|2|1|179a4f32ec0643689b55a8d7207e63f6ec3d3831|0|Blockchain/Dev/services/originate/src/__tests__/ks1341b-webhooks-500-never-answers-err-message.test.ts,Blockchain/Dev/services/originate/src/routes/webhooks.ts|T1"
  "1291|KS-1337|refs/heads/feature/ks-1337-presuite-path-with-a-space-b31-4|2c9022c519bd26e9b58acddeed817f4413d92449|2|1|179a4f32ec0643689b55a8d7207e63f6ec3d3831|0|systemTest/performance/runner/cli.ts,systemTest/performance/tests/unit/runner/ks1337-preSuitePathWithASpace.test.ts|T2"
)
DEVELOP_SHA='179a4f32ec0643689b55a8d7207e63f6ec3d3831'
END_TREE='0cc6669f3a6ed3ac2841e9cf17c6229e890e0250'
_ovr() { local v="QAB29_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate29.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 2 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate29_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB29_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate29.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at two' && has 'TIER 1: THROUGH-CODE PLUS RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at two" >&2; exit 7; }
for _w in \
  'message: err.message in this file goes 5 -> 2' \
  'ARM R3: PASS' \
  '6 failed / 5 passed / 11 total' \
  'bare 951 / patched 962' \
  '22 problems (0 errors, 22 warnings)' \
  'the patch was produced by the local model' \
  'The last two sites (`:391`, `:416`) — part C.' \
  'Still false after part B' \
  'The other two occurrences of the pattern, measured on develop and NOT in this PR' \
  'is approximated, not met.' \
  'a missing gate is not a passing gate' \
  '6 problems (6 errors, 0 warnings)' \
  '1114 passed / 0 failed' \
  'One hunk, 15 lines, 3,481 → 3,524 bytes' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'FAIL500-RUNTIME-NODE-ENV' \
  'CATCH-REACHED-PER-ENV' \
  'ARM-R3-PROD-ONLY-LOG' \
  'KS1344-CLOSED-IN-B' \
  'SECRET-PATH-UNCHANGED' \
  'ROTATE-SECRET-VIA-ENCRYPTFIELD' \
  'DELETE-MEASURED-LEAK' \
  'PATCH-400-BRANCH' \
  'NON-ERROR-THROWS' \
  'UNCONVERTED-TWO' \
  'DOCBLOCK-STILL-FALSE' \
  'GOLDEN-BLOB-IDENTITY' \
  'LOCAL-MODEL-PROVENANCE' \
  'ORIGINATE-951-962' \
  'TSC-EXCLUDES-TESTS' \
  'LINT-22-WARNINGS' \
  'FILEURLTOPATH-FIX' \
  'SPACED-PATH-RED' \
  'DOD2-APPROXIMATION' \
  'NOT-COVERED-TRUE' \
  'DOD3-SWEEP-COUNT' \
  'KS1337-STAYS-OPEN' \
  'FORMATTER-DELTA' \
  'OWN-LINT-AND-UNIT' \
  'NO-PLATFORM-PREFLIGHT' \
  'PERF-1114-1117' \
  'HARNESS-BASELINE-1114' \
  'BASE-FIGURES-PER-PR'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'RUNTIME PROBE FOR #1290 — THROUGH THE REAL ROUTER' && has 'throw a LEAK of YOUR OWN that does NOT contain '\''does not exist'\''' && has 'under NODE_ENV production, development, test and UNSET' && has 'the catch was REACHED IN THAT ENVIRONMENT' && has 'it MUST leak on all three routes in all four environments' || { echo "REFUSING: the #1290 T1 runtime probe" >&2; exit 40; }
has 'ARM R3 FOR #1290 — THE GATE RUNS IT' && has 'all three `RED KS-1341 B1` rows must go RED' && has 'IF ANY B1 ROW STAYS GREEN UNDER R3' || { echo "REFUSING: the #1290 arm R3" >&2; exit 41; }
has 'SECRET HANDLING ON ROTATE-SECRET MUST BE UNCHANGED APART FROM THE CATCH BODY' && has 'a probe that never learns the secret cannot show it absent' || { echo "REFUSING: the #1290 rotate-secret secret path" >&2; exit 49; }
has 'THE TWO UNCONVERTED SITES ARE DECLARED SCOPE, NOT A NO GO' && has 'byte-identical to their merge-base lines' || { echo "REFUSING: the #1290 declared two" >&2; exit 42; }
has 'RED DESIGN AND DISCLOSURE FOR #1291' && has 'Grade whether that disclosure is TRUE and complete' || { echo "REFUSING: the #1291 red design and disclosure" >&2; exit 44; }
has 'so YOU run the package'\''s own gates' && has '`npm run test:unit` (vitest, vitest.unit.config.ts) at develop, head and END_TREE' || { echo "REFUSING: the #1291 own lint and unit suite" >&2; exit 43; }
has 'For #1291 the fleet STOP count is NOT APPLICABLE' || { echo "REFUSING: the #1291 fleet STOP NOT APPLICABLE" >&2; exit 37; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'both PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1290, #1291 batch`' && has 'so both are squashed by Seat B 31st, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (2 over 2 paths) for #1290 and #1291' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE29 batch #1290 #1291 (Seat B31, round 29; #1290 T1 KS-1341 part B)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE"
_ANY_OVR="$(env | grep -c '^QAB29_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 2 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 15 seat items; the prompt carries 28 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the #1290 T1 runtime probe / the #1290 arm R3 / the #1290 rotate-secret secret path / the #1290 declared two / the #1291 red design and disclosure / the #1291 own lint and unit suite / the #1291 fleet STOP NOT APPLICABLE / no Docker / no stack / no port / the MG-3 key scan / the Linear link kinds rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB29_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
