#!/bin/bash
# launch_qa_secuura_ks763_1036.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #1036
# (KS-763, Seat B 1st successor, PR-4: qs in range on express 4 — 20 manifests overrides.body-parser 1.20.6 -> 1.20.8, 29 regenerated locks
# express 4.22.3 / body-parser 1.20.8 / qs 6.16.0 / side-channel 1.1.1, audit-baseline.json 29 -> 26: GHSA-4mjr-xmp4-gh2g + GHSA-x5fp-wj9c-mxmx (KS-763,
# EXPIRE 2026-09-24) + GHSA-q8mj-m7cp-5q26 (KS-531 / KS-775, Wednesday's 2026-09-17 13:50:18Z ruling))
# @ 4b251997a96034ee8a3359aac357ee17d222c3ef — THREE commits: c9e034744 (the change, on bb848b828), c93d84c9b (a merge of develop 3961c2add = #1029 + #1031 + #1033),
# 4b251997a (q8mj removed). 50 files vs the merge-base: 29 package-lock.json + 20 package.json + scripts/audit/audit-baseline.json. TIER 1 because
# express, body-parser and qs are prod runtime dependencies in every express service image (Wednesday's receipt, 2026-09-18).
#
# THE SHAPE, as read 2026-09-22 08:00:41 AEST by the generator (git ls-remote + local object reads): head = refs/pull/1036/head = the branch; origin develop
# 3916eacd12af23bfd464440b4c770f7da0f2dd96 (142 commits past the merge-base, 6 merges; it moves often). compare develop...head = merge_base 3961c2add, status diverged,
# ahead 3, behind 142, files 50. Asserted: merge_base + ahead + files (exit 10); behind is NOT asserted. MERGED TREE over that develop
# (merge-tree, both orders, 0 conflicts) = 04b05e093ad8b3d6e55b0fe553d7deb96b247050 — printed, not a guard (the gate re-predicts over the develop it reads).
#
# THE DEVELOP ARM IS JUDGED BY PATH BLOBS, NEVER BY DEVELOP'S SHA. GUARDED PATHS, each read from its parent directory's GitHub contents listing at
# the CURRENT develop (30 listings): (a) the 49 non-audit PR paths (29 locks + 20 manifests); (b) EVERY file of Blockchain/Dev/scripts/audit/
# (13 at draft, incl. audit-baseline.json, audit-gate.mjs, audit-locks.mjs); the listing must name exactly these 13; (c) 3 REACH paths with no #1036
# blob: the api-gateway, auth and originate Dockerfiles (the runtime `npm ci --omit=dev` steps). Every path at its merge-base blob -> OK (develop's SHA
# is printed, not judged). ALL 50 PR paths at their #1036 blobs (reach paths unmoved) -> exit 19 LANDED. Any path at a blob nobody pinned, a file
# absent, a scripts/audit/ file added or removed, or a PARTIAL landing -> exit 18 GUARDED. TEN open Dependabot PRs share these paths (#949 #948 #947
# #946 #945 #649 #639 #635 #575 #572): one landing first REFUSES here by design — re-pin deliberately (README section 0).
#
# exit 6:  the head is not at the branch AND refs/pull/1036/head on origin.
# exit 7 / 15: the READY capture (BRIEF) and the prompt must carry TIER 1 / ROUND 1.
# exit 10: the compare (merge_base 3961c2add ahead=3 files=50). exit 13: compare unreadable. exit 18/19: the develop arm (above).
# exit 20: the READY capture AND the prompt must name the head SHA in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit pane, never inside a
#          Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: node_modules farmed PER ENTRY. exit 23: the exact #1036 verdict subject, coagent@ sender, wednesday-agent@ recipient.
# exit 24: the REPORT DIRECTORY + NOT-TESTED.written-first.md. exit 25: the MERGE ADDENDUM (+ `## MERGE ADDENDUM`, `GO: merge #1036`, BASE_GO).
# exit 26: unique container names, --runInBand in containers, the host load average beside every timed run.
# exit 27: RUNTIME REACH FIRST. exit 28: the npm-version dependent root-lock recipe (host npm cannot reproduce the seat's locks; a false NO GO trap).
# exit 29: MERGEABILITY at the CURRENT develop, with the merge-base, the develop pin and the predicted merged tree named in FULL.
# exit 30: Wednesday's ELEVEN by-name items and the standard closing (the keyword ladder, 93 keywords).
# exit 31: THE CONTEXT RULE (report.md at ctx 80%). exit 32: THE CENSUS RULE v2 with the :5432 / :4000 / :4003 / :8080 lsof lines.
# exit 33: a PARTIAL prompt (any `PENDING` token) refuses — --check and launch alike. exit 34: a `deadbeef` literal in the prompt refuses.
# exit 35: every one of the 50 head blobs (the equality targets) must appear in the prompt.
# exit 36: the READY capture AND the prompt must BOTH carry the seat's items (46 tokens, case-insensitive).
# QA1036_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED arms can be proven. QA1036_HEAD / QA1036_PROMPT /
# QA1036_BRIEF (test overrides). A launch with any QA1036_* override set refuses (exit 16).
#
# Generated by gatesets/2026-09-22_gate1036_ks763/gen_launcher_gate1036.py (pins re-read at origin + local objects + dry ladder + heredoc parity +
# bash -n) in the shape of gen_launcher_1033.py / gen_launcher_gate16C.py. Exit codes 2..36 (19 = LANDED).
#
# Usage: launch_qa_secuura_ks763_1036.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..36 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1036_BRIEF:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate1036/mail_1036_ready.md}"
PROMPT_FILE="${QA1036_PROMPT:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/briefs/2026-09-22_secuura-1036-ks763-qs-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-763-qs-in-range'
HEAD_SHA="${QA1036_HEAD:-4b251997a96034ee8a3359aac357ee17d222c3ef}"
MERGE_BASE='3961c2add8e1637b32e638f8f0952c328c00833e'   # the merge-base of the head with develop = the develop c93d84c9b merged in (#1033 squash)
DEVELOP_SHA='3916eacd12af23bfd464440b4c770f7da0f2dd96'   # develop at generation (ls-remote 2026-09-22 08:00:41 AEST) — PRINTED, never a guard
MERGED_TREE='04b05e093ad8b3d6e55b0fe553d7deb96b247050'   # merge-tree(develop at generation, head), 0 conflicts — PRINTED, never a guard
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-22-ks763-1036-4b251997a-tier1-r1/'
SUBJECT='[QA -> Wednesday] TIER 1 GATE #1036 (KS-763) 4b251997a — '
REAL_BRIEF="/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate1036/mail_1036_ready.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief (READY capture) missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }
/usr/bin/grep -qF 'PENDING' "$PROMPT_FILE" && { echo "REFUSING: the prompt is PARTIAL (a PENDING token) — a partial gate is not a gate" >&2; exit 33; }
/usr/bin/grep -qiF 'deadbeef' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries a deadbeef literal — a placeholder pin is not a pin" >&2; exit 34; }

# The head, pinned at its branch AND at refs/pull/1036/head on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH" refs/pull/1036/head)"
if ! printf '%s\n' "$LSR" | /usr/bin/grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$" || ! printf '%s\n' "$LSR" | /usr/bin/grep -q "^${HEAD_SHA}[[:space:]]refs/pull/1036/head\$"; then
  echo "REFUSING: #1036 — $HEAD_SHA is not at $BRANCH AND refs/pull/1036/head on origin — the head moved; the prompt is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1036 = 3961c2add ahead 3 files 50 (behind 142 at generation — deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=3 files=50" ] || { echo "REFUSING: #1036 develop...head reads '$COMPARE', the pin is '$MERGE_BASE ahead=3 files=50'" >&2; exit 10; }

# The develop arm, judged by PATH BLOBS (see the header) — never by develop's SHA, never by a pinned...develop compare.
CUR_DEV="${QA1036_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import json, os, sys, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
# path -> [merge-base blob = develop-OK, the #1036 blob = LANDED, empty for the 3 REACH Dockerfiles]; read by the generator with git diff --raw / rev-parse
JUDGED = {
  "Blockchain/Dev/connectors/whatsapp-bot/package-lock.json": ["1b01823bc754353bbf20fc841f8bfbfe5bea53dd", "86e1f26ad3a12b45392193cb1912c89ae06827b6"],
  "Blockchain/Dev/frontend/issuer/package-lock.json": ["d51db26d56e17dc147e0672c86e1301934503110", "d0991a22f6c458464404be947bda8b9ef2fce4ba"],
  "Blockchain/Dev/package-lock.json": ["646c19f6f7f735ba32bfb20bef8b936835184949", "54ba290e54f77725d4f757e974d51eeb3564400f"],
  "Blockchain/Dev/packages/shared/package-lock.json": ["5cf24ef21d0d473f388288f24b2b47c1eb7383c0", "77b5dba5ac05a23c28927f5742929d0f18227902"],
  "Blockchain/Dev/packages/shared/package.json": ["3957692311221fbe87c4ab19447de8cec44aa19a", "4a4a58de3c79b2f33f335a0fbf845781a2fde127"],
  "Blockchain/Dev/services/analytics/package-lock.json": ["687607af6f23a8d4df98f709c0f99c5356b74878", "55e724a0f8dc499dd6f0c0dab8756c1032d01f38"],
  "Blockchain/Dev/services/analytics/package.json": ["50015a885cb4bcfaefa08c770d3bf830642faf07", "1e9f2f1ec91792129ecd725872c3f066cca9636a"],
  "Blockchain/Dev/services/anchoring/package-lock.json": ["7ef3f65a35b48bec2591df4b2859bab9aa237334", "d77ac9080f591c30a840b4abdd21f3019a308d2a"],
  "Blockchain/Dev/services/api-gateway/package-lock.json": ["5ec55d86d83f93e70dc03676293331fd3bc250e5", "cd2851509155ec1f45290b63e0f0b35675be4cdf"],
  "Blockchain/Dev/services/api-gateway/package.json": ["841d8c6adcd71e885c01e65c22da9418daff276a", "3f7dfd358c9e2a8506a8f6bc77b8984617a549ab"],
  "Blockchain/Dev/services/auth/package-lock.json": ["2d91a356aa8426304dc291e0090dbd6893d53c00", "a9f32ff8814343219ff65677dd2cba00e6787d27"],
  "Blockchain/Dev/services/auth/package.json": ["814e88419470b811f26f1593984071bb317608d8", "66edc57735a8d43c0e682118da4a212d29d287f5"],
  "Blockchain/Dev/services/billing/package-lock.json": ["4467d01413d80dec5f5fa00afe9080ed7d0f1983", "1b0afc4b4e6fa133e0af0b6d4bd4d988aa80eebf"],
  "Blockchain/Dev/services/billing/package.json": ["c228d7244b7c52005dcb1c065f5b60b1118b6c63", "b2e1dca8609ea236f92a7acb85612d6d5716d11c"],
  "Blockchain/Dev/services/demo-service/package-lock.json": ["64b0c9374dbb42054260790f2dfb0df692fdf040", "59bb884bce2a541160549a1ac999e299922fff3b"],
  "Blockchain/Dev/services/demo-service/package.json": ["02aef8bbc26660fc295251f3705ac971f8ff0405", "e6605a147581794b43bf89e293224fcc056e8d9c"],
  "Blockchain/Dev/services/governance/package-lock.json": ["5fae8f62ca58252800146606ea47877ad9a9a3a6", "430b5326031ed626a3a3892d02ceae1cf1b8b6a4"],
  "Blockchain/Dev/services/governance/package.json": ["e0644b07509ee7dfbd0b8d267e4246dd3a1e2f65", "7d10ab12c03cd61cfdf8a704c5a4146ae4366bcb"],
  "Blockchain/Dev/services/guardian/package-lock.json": ["d1cefe1a226b35b74e64ba021ddf793e571d8aa0", "bc41b57dc73ab48e59e3f9fe2f519adeb575a9ef"],
  "Blockchain/Dev/services/guardian/package.json": ["232c3db77c4e0c65b309965fd2916e32463a3b8c", "dac05291a73b8f226394de0d04914499411a0944"],
  "Blockchain/Dev/services/kyc/package-lock.json": ["b96b7a75b81303f10dfb77b863919aa746181a84", "13c0af8239cc9585f9b953a45e68b597304db55b"],
  "Blockchain/Dev/services/m365-integration/package-lock.json": ["803ca79bda38706715ee9637adc52bf649345f1e", "f1abd89c537192c8d54fb05b0bf9bd66ea20d0ba"],
  "Blockchain/Dev/services/m365-integration/package.json": ["e21d4cfb525dbe7c994aace244d049c8ffc050da", "76e6a235a347b20d7a87baa9570d7d4640b7a4d5"],
  "Blockchain/Dev/services/mcp-server/package-lock.json": ["780b4cbcb86ad9edc285f2efc66cf708a97f092d", "bfb275b8fa0cf4253ddb30f156cd3c0757bb47d8"],
  "Blockchain/Dev/services/nft-certificate/package-lock.json": ["c831aee6f5e1ec085bbe5c45bf6c10c2a93528a1", "db3f02648fadac19984bc8e244b4da50b5fb441a"],
  "Blockchain/Dev/services/originate/package-lock.json": ["4c1800aee48392e6ca2efa80526b1b2627cec34d", "c1033c41a6e9fb2938542e01beab0fc17028431f"],
  "Blockchain/Dev/services/prism/package-lock.json": ["0f982cc4464e674c04f7ddbe5da79c2bc4d9a804", "eb4d1ced732f223a99ce113db227e8c2884e8de8"],
  "Blockchain/Dev/services/prism/package.json": ["cb7eb842797932bbeb578ca5368c01d939b04583", "f0a9109e4f43d256387c5ae1801d732ecc72e7ae"],
  "Blockchain/Dev/services/queue/package-lock.json": ["922cd071d80aa4289eb00ef42a7db35bc282f1a4", "ca249663fe5b9386c98107e566cf8ce39db7537e"],
  "Blockchain/Dev/services/queue/package.json": ["d5652ee9d0b1b3b3c3de1dba2542e72fe41026cd", "03118e9348c5cf55f369806c1430d66984577373"],
  "Blockchain/Dev/services/referral/package-lock.json": ["c7bd745800eae211d7fe21d978cd8b316b9f6ba5", "5c57c89a705f1bb036828ff3d7df2c21d4d72823"],
  "Blockchain/Dev/services/referral/package.json": ["1bc18b51f0ee6100b70ea65ee2610b9bf0220d7f", "a6d079cce024e6ab1611cd623523fc44318f6edf"],
  "Blockchain/Dev/services/security/package-lock.json": ["2675691235597a521c8952a5058df29203b4eb8c", "bef281994ca18af88eff80cc245b2df51fc0970c"],
  "Blockchain/Dev/services/security/package.json": ["a2f2e03ff75b5aba19a9aac97a827cb7a6c50aba", "0a1c576318875306b0ba9f6d8346fcde39e2d558"],
  "Blockchain/Dev/services/shared/package-lock.json": ["13d6191f30ca150d31b57b3dace52e10f176df40", "e1b3ce647b046c8b29e3b48072de7aa399b86d1b"],
  "Blockchain/Dev/services/shared/package.json": ["7551485afc6e3d444d484ab4abb5959eb9ceeef4", "13a176851e9f8d6cb27db7d7b1a84af0ac61b7be"],
  "Blockchain/Dev/services/staking/package-lock.json": ["ad74908c566d552972eef88f204e303086f64e18", "7ed3e5a22af106219e313b25d68f72105504b732"],
  "Blockchain/Dev/services/staking/package.json": ["7dcce97c7d4aeb4363bd36a11a70e818f321936c", "f4c625bcea26a096c4db74c71cf39eb8c4c420a7"],
  "Blockchain/Dev/services/tenant-provisioning/package-lock.json": ["ec65822f50dc09c844a08726ee96818acadb3a9b", "a0107e74ca4e105c535508f680c1ff6f619d8d45"],
  "Blockchain/Dev/services/tenant-provisioning/package.json": ["c5b24fba535b295e16f840dd775a832f8fd03af6", "13efef83b061812f6158858c830311d56cf435f9"],
  "Blockchain/Dev/services/timestamping/package-lock.json": ["c2f5b451133aef7cb8f00d5e19aba929075d7113", "45d4ecc0efe31dcb7558543b2627da7843277918"],
  "Blockchain/Dev/services/timestamping/package.json": ["450cb6dc189a8552eb0923a44a4a7b29d4b1eb69", "d21deb9016cabca38085090505b737deea116c97"],
  "Blockchain/Dev/services/tokenisation/package-lock.json": ["ecb12e1da93ad2d8342096bf5a21dafae9433ddd", "66d19e1599b510f18da266dfee84f8688f28004b"],
  "Blockchain/Dev/services/tokenisation/package.json": ["647077b07acceefb8b112b639648cffa1302202a", "814f929de4fd8921cc14b15b36b3f65672e42266"],
  "Blockchain/Dev/services/transfer/package-lock.json": ["cfaed9c882bcd146cfbb41a1ee7a08d0314dca4f", "bad23f929c508b6ff840d9e4311508b10b09977a"],
  "Blockchain/Dev/services/transfer/package.json": ["b1c83dbb237c6162e9f341daf8f7e0f362927d3d", "76269fdee30373b4e8a54d3b4f97f96d3b7397d1"],
  "Blockchain/Dev/services/vc-issuer/package-lock.json": ["b0b66b5018e556731056875d4c1720945e3478e7", "80ce378ad067ccadc06686af4c5925504e6dee02"],
  "Blockchain/Dev/services/wallet-connector/package-lock.json": ["c7d33bd92a63acf97df48313a502ec9e1a21c136", "d54e47677531ca0f472d0c777fbcd5714a8dde88"],
  "Blockchain/Dev/services/wallet-connector/package.json": ["4f6ef932488fe7719097d46ea78983d4fcca1f21", "e66c06db6ab817f8ccc1d91b6a58f23bb208f71e"],
  "Blockchain/Dev/services/api-gateway/Dockerfile": ["6faa70472448c8d3ccbce4a2760c65185d38e6d6", ""],
  "Blockchain/Dev/services/auth/Dockerfile": ["9402b0de370d0eab2e54329fce1e16255df0e5d0", ""],
  "Blockchain/Dev/services/originate/Dockerfile": ["ac2fb91bf7d814b407f41bcca904793b6d6d91c1", ""],
}
# EVERY file of Blockchain/Dev/scripts/audit/ -> [merge-base blob, #1036 blob or empty]; the listing must name exactly these
AUDIT_DIR = "Blockchain/Dev/scripts/audit"
AUDIT = {
  "advisory-fetch-stub.mjs": ["29c9fc48f32857d4f24ef944b9868639e0171435", ""],
  "audit-baseline.json": ["91d8b71c9701e742c60a1c53049fd6fb5873486c", "648e8ee7bbf22b5737597e3dd61ee92922628e58"],
  "audit-gate.mjs": ["8e236ee70ce1a4634552596fb86fcffce234f221", ""],
  "audit-locks.mjs": ["aff23b0420ced863884787443a35f28cf727bd09", ""],
  "baseline-contract.mjs": ["2504d9a28dc017fcaabfc88248bf1c64431eb38a", ""],
  "baseline-contract.test.mjs": ["2379c0aeee6e3e3f0c4ef3a2512e3a590ad47d29", ""],
  "could-not-check.mjs": ["92eea6087a6c442f1a14e735ba9fcca74493bd0a", ""],
  "expected-case-count": ["04f9fe46068b397a6fc24d647b7e3ec4315c15e7", ""],
  "gate-exit-codes.test.mjs": ["40079f6fb41e146a34a66463e352b9c0a49f91e8", ""],
  "lock-discovery.mjs": ["3dd903b527f26c758cc1da84b10cc0a0db3b1d46", ""],
  "lock-discovery.test.mjs": ["f102d9d4c4523091fe4e3119d6c539fb29bfd904", ""],
  "package-lock.json": ["ffb2b110a2d69c2c9a10e6caf5666c5fa08ec62c", ""],
  "package.json": ["d5977b6a13638558ef57e8c294809d7ada8be6cd", ""],
}
for n, v in AUDIT.items():
    JUDGED[AUDIT_DIR + "/" + n] = v
dirs = sorted({p.rsplit("/", 1)[0] for p in JUDGED})
seen = {}
for d in dirs:
    try:
        listing = get("/contents/" + d + "?ref=" + cur)
    except Exception as e:
        print("UNJUDGEABLE contents listing unreadable for " + d + ": " + type(e).__name__); sys.exit(0)
    for x in listing:
        seen[d + "/" + x["name"]] = x["sha"] if x.get("type") == "file" else "type-" + str(x.get("type"))
    if d == AUDIT_DIR:
        names = sorted(x["name"] for x in listing)
        if names != sorted(AUDIT):
            print("GUARDED develop " + cur[:9] + " scripts/audit/ file set differs from the pin: " + ",".join(sorted(set(names) ^ set(AUDIT)))); sys.exit(0)
landed, unpinned, ok = [], [], 0
for p, (base, own) in JUDGED.items():
    b = seen.get(p, "ABSENT")
    if b == base:
        ok += 1
    elif own and b == own:
        landed.append(p.replace(D, ""))
    else:
        unpinned.append(p.replace(D, "") + " " + b[:9])
owned = sum(1 for v in JUDGED.values() if v[1])
if unpinned or (landed and len(landed) != owned):
    print("GUARDED develop %s: %d guarded path[s] at a blob nobody pinned %s; %d of %d at the #1036 blob" % (cur[:9], len(unpinned), unpinned[:6], len(landed), owned)); sys.exit(0)
if landed:
    print("LANDED develop %s: all %d #1036 blobs present — #1036 has landed; this prompt is stale" % (cur[:9], owned)); sys.exit(0)
note = "= the generation pin" if cur == pinned else "MOVED from the generation pin " + pinned[:9] + ", not judged by SHA (the gate re-predicts the merged tree over the tip it reads)"
print("OK develop %s %s: %d of %d guarded paths at their merge-base blobs [49 PR paths + 3 reach Dockerfiles + all %d files of scripts/audit/], read from %d directory listings" % (cur[:9], note, ok, len(JUDGED), len(AUDIT), len(dirs))); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } — re-pin deliberately: a different gate" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop $CUR_DEV is not provably clean on the guarded paths: ${DEV_JUDGEMENT:-no judgement} — confirm the delta (a Dependabot PR landing first is the expected mover), then re-pin deliberately (README section 0)" >&2
     exit 18 ;;
esac
/usr/bin/grep -q 'TIER 1' "$BRIEF" && /usr/bin/grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: READY capture and prompt disagree about the tier (TIER 1)" >&2; exit 7; }
/usr/bin/grep -q 'ROUND 1' "$PROMPT_FILE" && /usr/bin/grep -q 'round 1 of 2' "$PROMPT_FILE" || { echo "REFUSING: prompt does not carry ROUND 1 / round 1 of 2" >&2; exit 15; }
head -1 "$PROMPT_FILE" | /usr/bin/grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
/usr/bin/grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the READY capture path" >&2; exit 9; }
/usr/bin/grep -qF "$HEAD_SHA" "$PROMPT_FILE" && /usr/bin/grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: READY capture or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
/usr/bin/grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
/usr/bin/grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
/usr/bin/grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
/usr/bin/grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
/usr/bin/grep -qi 'farmed per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY" >&2; exit 22; }
/usr/bin/grep -qF "$SUBJECT" "$PROMPT_FILE" && /usr/bin/grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && /usr/bin/grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact #1036 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
/usr/bin/grep -qF "$REPORT_DIR" "$PROMPT_FILE" && /usr/bin/grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not name the report directory $REPORT_DIR or NOT-TESTED.written-first.md" >&2; exit 24; }
/usr/bin/grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && /usr/bin/grep -qF '## MERGE ADDENDUM' "$PROMPT_FILE" && /usr/bin/grep -qF 'GO: merge #1036' "$PROMPT_FILE" && /usr/bin/grep -qF 'BASE_GO' "$PROMPT_FILE" && /usr/bin/grep -qF 'path blob (mode)' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the MERGE ADDENDUM (the ## heading, the GO string, BASE_GO, the path blob (mode) targets)" >&2; exit 25; }
/usr/bin/grep -qi 'name it uniquely' "$PROMPT_FILE" && /usr/bin/grep -qF -- '--runInBand' "$PROMPT_FILE" && /usr/bin/grep -qi 'load average' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require unique container names, --runInBand in containers, or the host load average beside timed runs" >&2; exit 26; }
/usr/bin/grep -qF 'RUNTIME REACH FIRST' "$PROMPT_FILE" || { echo "REFUSING: prompt does not carry the RUNTIME REACH FIRST rule" >&2; exit 27; }
/usr/bin/grep -qi 'npm-version dependent' "$PROMPT_FILE" && /usr/bin/grep -qF 'INSTRUMENT ARTEFACT' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the npm-version dependent lock-recipe finding (host npm cannot reproduce the locks)" >&2; exit 28; }
/usr/bin/grep -qF 'MERGEABILITY at the CURRENT develop' "$PROMPT_FILE" && /usr/bin/grep -qF "$MERGE_BASE" "$PROMPT_FILE" && /usr/bin/grep -qF "$DEVELOP_SHA" "$PROMPT_FILE" && /usr/bin/grep -qF "$MERGED_TREE" "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry MERGEABILITY at the CURRENT develop with the merge-base, the develop pin and the predicted merged tree in full" >&2; exit 29; }
for _w in 'TIER AND ROUND' \
          'round 1 of 2' \
          'FULL WEIGHT' \
          'real-browser half' \
          'Any product byte' \
          'MERGEABILITY at the CURRENT develop' \
          'BOTH orders' \
          'conflicts BY PATH' \
          'CONSERVATION' \
          'develop'"'"'s minus EXACTLY the three rows' \
          'MEASURE develop'"'"'s row count NOW' \
          'FINDING for the seat' \
          'THE LOCKS: parse EVERY tracked package-lock.json' \
          '0 qs < 6.16.0' \
          'ONLY non-family move is side-channel 1.1.0 -> 1.1.1' \
          'NO major jumps' \
          'mysql2 3.23.1' \
          'vitest 4.1.11' \
          'PLANTED-VIOLATION CONTROL' \
          'THE SHIPPED AUDIT SCRIPTS at the head' \
          'NEGATIVE CONTROL' \
          'CLEANUP naming exactly GHSA-4mjr + GHSA-x5fp' \
          'Tee vulnerable_versions' \
          'INSTALL + SUITES from the head'"'"'s locks' \
          'THE WORKSPACE MATRIX' \
          'RE-RUN, do not copy' \
          'threadTokenMint = KS-562' \
          'own-lock `npm ci`' \
          'lockfile-cleanroom.sh 35/35' \
          'THE TWO THINGS THE READY SAYS ARE NOT COVERED' \
          'RUNTIME REACH FIRST' \
          'IMAGE BUILD' \
          'docker build' \
          'never fake it' \
          'RUNTIME LOAD TRACE' \
          'SERVES ONE REQUEST' \
          'a[b]=1&a[c]=2' \
          'a[0]=x,y' \
          'module.registerHooks' \
          'DEPENDABOT OVERLAP' \
          'SUPERSEDES' \
          'LINEAR LINK HYGIENE' \
          'attachmentsForURL(pull/1036)' \
          'EXACTLY KS-763 `contributes` + KS-775 `contributes`' \
          'READ BACK' \
          '<= 92 chars ASCII' \
          'THE SEAT'"'"'S OWN SLIPS' \
          'CONFIRMED / REFUTED' \
          'whitespace-split' \
          'root loop re-picking express' \
          'patched once' \
          'MERGE ADDENDUM' \
          '## MERGE ADDENDUM' \
          'ONE line VERBATIM' \
          'BASE_GO' \
          'GO: merge #1036' \
          'path blob (mode)' \
          'SHIPS-WITH <= 3 sentences' \
          'NOT-PINNED: none' \
          'INTERMITTENTS do not block' \
          'RULED (WHETHER IT BLOCKS)' \
          'THE CONTEXT RULE' \
          'ctx 80%' \
          'NOT-TESTED.written-first.md' \
          'THE CENSUS RULE v2' \
          'lsof -nP -iTCP:5432 -sTCP:LISTEN' \
          'lsof -nP -iTCP:4000 -sTCP:LISTEN' \
          'lsof -nP -iTCP:4003 -sTCP:LISTEN' \
          'lsof -nP -iTCP:8080 -sTCP:LISTEN' \
          'login_stub' \
          'farmed per ENTRY' \
          'name it uniquely' \
          '--runInBand' \
          'load average' \
          'npm-version dependent' \
          'INSTRUMENT ARTEFACT' \
          'MEASURE, not conclude' \
          'FINDINGS-ONLY' \
          'NEVER print a credential value' \
          'no memory maintenance' \
          'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' \
          'NEVER touch the push-window lock directory' \
          'MAIL YOUR VERDICT' \
          'WRITE report.md BEFORE THE MAIL' \
          'sha256 + byte count IN the mail' \
          'coagent@agentmail.to' \
          'wednesday-agent@agentmail.to' \
          'GO, GO WITH FINDINGS, or NO GO' \
          'Never enter any seat'"'"'s worktree' \
          'count-objects' \
          'No Datasec' \
          'Docker daemon was DOWN' \
          'never a wholesale symlink'; do
  /usr/bin/grep -qF -- "$_w" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 30; }
done
/usr/bin/grep -qF 'THE CONTEXT RULE' "$PROMPT_FILE" && /usr/bin/grep -qF 'ctx 80%' "$PROMPT_FILE" || { echo "REFUSING: prompt does not carry THE CONTEXT RULE (report.md at ctx 80%)" >&2; exit 31; }
/usr/bin/grep -qF 'THE CENSUS RULE v2' "$PROMPT_FILE" && /usr/bin/grep -qF 'lsof -nP -iTCP:5432 -sTCP:LISTEN' "$PROMPT_FILE" && /usr/bin/grep -qF 'lsof -nP -iTCP:4000 -sTCP:LISTEN' "$PROMPT_FILE" && /usr/bin/grep -qF 'lsof -nP -iTCP:4003 -sTCP:LISTEN' "$PROMPT_FILE" && /usr/bin/grep -qF 'lsof -nP -iTCP:8080 -sTCP:LISTEN' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry THE CENSUS RULE v2 with the :5432 / :4000 / :4003 / :8080 lsof lines" >&2; exit 32; }
for _b in '86e1f26ad3a12b45392193cb1912c89ae06827b6' \
          'd0991a22f6c458464404be947bda8b9ef2fce4ba' \
          '54ba290e54f77725d4f757e974d51eeb3564400f' \
          '77b5dba5ac05a23c28927f5742929d0f18227902' \
          '4a4a58de3c79b2f33f335a0fbf845781a2fde127' \
          '55e724a0f8dc499dd6f0c0dab8756c1032d01f38' \
          '1e9f2f1ec91792129ecd725872c3f066cca9636a' \
          'd77ac9080f591c30a840b4abdd21f3019a308d2a' \
          'cd2851509155ec1f45290b63e0f0b35675be4cdf' \
          '3f7dfd358c9e2a8506a8f6bc77b8984617a549ab' \
          'a9f32ff8814343219ff65677dd2cba00e6787d27' \
          '66edc57735a8d43c0e682118da4a212d29d287f5' \
          '1b0afc4b4e6fa133e0af0b6d4bd4d988aa80eebf' \
          'b2e1dca8609ea236f92a7acb85612d6d5716d11c' \
          '59bb884bce2a541160549a1ac999e299922fff3b' \
          'e6605a147581794b43bf89e293224fcc056e8d9c' \
          '430b5326031ed626a3a3892d02ceae1cf1b8b6a4' \
          '7d10ab12c03cd61cfdf8a704c5a4146ae4366bcb' \
          'bc41b57dc73ab48e59e3f9fe2f519adeb575a9ef' \
          'dac05291a73b8f226394de0d04914499411a0944' \
          '13c0af8239cc9585f9b953a45e68b597304db55b' \
          'f1abd89c537192c8d54fb05b0bf9bd66ea20d0ba' \
          '76e6a235a347b20d7a87baa9570d7d4640b7a4d5' \
          'bfb275b8fa0cf4253ddb30f156cd3c0757bb47d8' \
          'db3f02648fadac19984bc8e244b4da50b5fb441a' \
          'c1033c41a6e9fb2938542e01beab0fc17028431f' \
          'eb4d1ced732f223a99ce113db227e8c2884e8de8' \
          'f0a9109e4f43d256387c5ae1801d732ecc72e7ae' \
          'ca249663fe5b9386c98107e566cf8ce39db7537e' \
          '03118e9348c5cf55f369806c1430d66984577373' \
          '5c57c89a705f1bb036828ff3d7df2c21d4d72823' \
          'a6d079cce024e6ab1611cd623523fc44318f6edf' \
          'bef281994ca18af88eff80cc245b2df51fc0970c' \
          '0a1c576318875306b0ba9f6d8346fcde39e2d558' \
          'e1b3ce647b046c8b29e3b48072de7aa399b86d1b' \
          '13a176851e9f8d6cb27db7d7b1a84af0ac61b7be' \
          '7ed3e5a22af106219e313b25d68f72105504b732' \
          'f4c625bcea26a096c4db74c71cf39eb8c4c420a7' \
          'a0107e74ca4e105c535508f680c1ff6f619d8d45' \
          '13efef83b061812f6158858c830311d56cf435f9' \
          '45d4ecc0efe31dcb7558543b2627da7843277918' \
          'd21deb9016cabca38085090505b737deea116c97' \
          '66d19e1599b510f18da266dfee84f8688f28004b' \
          '814f929de4fd8921cc14b15b36b3f65672e42266' \
          'bad23f929c508b6ff840d9e4311508b10b09977a' \
          '76269fdee30373b4e8a54d3b4f97f96d3b7397d1' \
          '80ce378ad067ccadc06686af4c5925504e6dee02' \
          'd54e47677531ca0f472d0c777fbcd5714a8dde88' \
          'e66c06db6ab817f8ccc1d91b6a58f23bb208f71e' \
          '648e8ee7bbf22b5737597e3dd61ee92922628e58'; do
  /usr/bin/grep -qF -- "$_b" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the head blob $_b (an equality target)" >&2; exit 35; }
done
for _w in '4b251997a' \
          'KS-763' \
          'KS-775' \
          '29 -> 26' \
          'GHSA-4mjr' \
          'GHSA-x5fp' \
          'GHSA-q8mj' \
          '6.16.0' \
          '4.22.3' \
          '1.20.8' \
          'side-channel 1.1.0 -> 1.1.1' \
          'npm 11.19.0' \
          'node:24-alpine' \
          '251' \
          'KS-562' \
          'lockfile-cleanroom' \
          '35/35' \
          '09d6f7c6-eb10-4e1f-8f98-16bf8254b689' \
          '1b1eb4d3-aa0f-4e38-8e70-9fbcb407a787' \
          '#949' \
          '#948' \
          '#947' \
          '#946' \
          '#945' \
          '#649' \
          '#639' \
          '#635' \
          '#575' \
          '#572' \
          'audit-baseline.json' \
          'Image build' \
          'runtime load trace' \
          'NOT COVERED' \
          '851/851' \
          '556/556' \
          '762/762' \
          '741/741' \
          '213/213' \
          '237/238' \
          '12/12' \
          'contributes' \
          'In Progress' \
          '2026-09-03' \
          '13:50:18Z' \
          'whatsapp-bot' \
          'frontend/issuer'; do
  /usr/bin/grep -qiF -- "$_w" "$PROMPT_FILE" && /usr/bin/grep -qiF -- "$_w" "$BRIEF" \
    || { echo "REFUSING: the READY capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 36; }
done

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1036 $HEAD_SHA at $BRANCH AND refs/pull/1036/head"
  echo "  compare (GitHub API): develop...#1036 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  generation pins (printed, not guards): develop $DEVELOP_SHA, merged tree $MERGED_TREE"
  echo "  READY capture, prompt, QA project and repo all present; the prompt is not PARTIAL and carries no deadbeef literal"
  echo "  READY capture and prompt agree on TIER 1; prompt names ROUND 1 / round 1 of 2"
  echo "  prompt opens with the thinking directive and names the READY capture"
  echo "  READY capture and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict; forbids pushing / the real hook / preflight in the Secuura checkout; forbids memory maintenance; forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY; unique container names; --runInBand in containers; the host load average beside timed runs"
  echo "  prompt carries the exact verdict subject ($SUBJECT...); names coagent@ -> wednesday-agent@"
  echo "  prompt names the report directory and NOT-TESTED.written-first.md"
  echo "  prompt carries the MERGE ADDENDUM (## heading, GO: merge #1036, BASE_GO, path blob (mode)), RUNTIME REACH FIRST, the npm-version dependent finding, MERGEABILITY at the CURRENT develop (merge-base + develop + merged tree in full)"
  echo "  prompt carries Wednesday's ELEVEN by-name items and the standard closing (93 keywords), THE CONTEXT RULE, THE CENSUS RULE v2 (:5432 / :4000 / :4003 / :8080)"
  echo "  prompt carries all 50 head blobs (the equality targets); READY capture and prompt BOTH carry the seat's items (46 tokens)"
  echo "  guarded paths (blobs at the current develop): the 49 non-audit PR paths + 3 reach Dockerfiles (api-gateway, auth, originate) + every file of Blockchain/Dev/scripts/audit/ (13, incl. audit-baseline.json)"
  [ -n "${QA1036_CUR_DEV:-}" ] && echo "  (develop read from the QA1036_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1036_BRIEF:-}${QA1036_PROMPT:-}${QA1036_HEAD:-}${QA1036_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
