#!/bin/bash
# launch_qa_secuura_ks1207_1023.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #1023 (KS-1207, Seat A)
# @ 2f74491ebd6211e722f778838339c55e8add008d — a failed optional API key falls through to the Bearer check. The fix commit 0f8b699b4 (parent d7e95cd9f):
# services/api-gateway/src/middleware/auth.ts +14 -10 (a presented sk_ key that fails validation on an OPTIONAL mount no longer calls next() at once; the Bearer
# path and its KS-257 session-revocation check run; with no Bearer the request stays anonymous) + the ks1207 test +185. 2f74491eb = a merge of develop 581c9db0d
# into 9bd0fd333 (a merge of f8c7aaa39 into 0f8b699b4); no file overlap. TIER 1: authentication middleware on every optional-auth mount.
#
# THE SHAPE, as read 18:06-18:19 AEST 2026-09-17 (git ls-remote + the PR, compare and contents APIs agree): develop 581c9db0d is the head merge-base AND an
# ANCESTOR of the head, so compare develop...head = merge_base 581c9db0d, ahead 3, behind 0, files 2 (asserted as merge_base + ahead + files, exit 10; behind NOT
# asserted). Merged tree over develop = the head tree 4bdf1b8c7 (= merge-tree 0f8b699b4 x 581c9db0d in the drafter clone = the seat prediction).
#
# The develop pin is judged by CONTENT, not bare: (a) SEVENTEEN files by blob at the CURRENT develop — the PR two (auth.ts 7c985bdce, the ks1207 test ABSENT; at
# their PR blobs -> exit 19 LANDED), index.ts, rateLimitEnforce.ts, routes/proxy.ts, routes/admin.ts, services/redis.ts, config/services.ts, rateLimitSkip.ts, the
# ks1195 and auth unit tests, api-gateway package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json, Dev eslint.config.mjs, shared session-validation.ts —
# any blob nobody pinned -> exit 18 (no region judgement: auth.ts is judged by exact blob); (b) if develop moved past 581c9db0d, the compare pinned...develop
# REFUSES (exit 18) when the delta touches a GUARDED path — services/api-gateway/src/ and its config files, packages/shared/src/, eslint.config.mjs, the Dev
# lockfile — or the move cannot be judged. DEV_CONTENT_ALLOWED is EMPTY.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate R-6: a wholesale link can write through to the checkout .vite).
# exit 23: the prompt must carry the exact #1023 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY and the PRIOR REPORT that found the defect (#1017 round 1, Record R-4; the QA agent has no inbox), and
#          the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition.
# QA1023_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA1023_AUTH_FILE (test fixture, --check only): a local file stands in for develop middleware/auth.ts (its git blob) so the LANDED and GUARDED arms can be
# proven without a real develop commit.
# A launch with any QA1023_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1023/gen_launcher_1023.py from launch_qa_secuura_ks1187_1019r2.sh (asserted substitutions + residual guard + output
# controls + bash -n): same guard set and exit codes 2..25 (19 = LANDED), re-pointed at #1023 ROUND 1, the proxy.ts region judgement removed.
#
# Usage: launch_qa_secuura_ks1207_1023.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1023_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1023-ks1207-tier1.md}"
PROMPT_FILE="${QA1023_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1023-ks1207-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-1207-security-an-unknown-sk_-key-on-an-optional-auth-mount-skips'
HEAD_SHA="${QA1023_HEAD:-2f74491ebd6211e722f778838339c55e8add008d}"
MERGE_BASE='581c9db0db4201c42cbbf702f339b750989acdb1'   # the merge-base of the head with develop = develop itself, the second parent of the head merge 2f74491eb (#1019s squash)
DEVELOP_SHA='581c9db0db4201c42cbbf702f339b750989acdb1'   # develop at drafting, an ANCESTOR of the head (git ls-remote 18:06:47; compare API 18:19:23 AEST)
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1207-1023-2f74491eb-tier1-r1/'
PRIOR_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1195-1017-cbe29597d-tier1-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1023-ks1207-tier1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1023 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1023 = 581c9db0d ahead 3 files 2 (behind 0 at draft close; behind deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=3 files=2" ] || { echo "REFUSING: #1023 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=3 files=2'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): seventeen files by blob at the CURRENT develop (no region judgement), then — if develop
# moved — the pinned...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="${QA1023_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
G = D + "services/api-gateway/"
AU = G + "src/middleware/auth.ts"
DV = "develop"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  AU:                                                                  ({"7c985bdcefc26293815bfbe0cbf315f929b48835": DV}, {"b8fce678a85ecbac82f1e468fd0180059447a43e": "#1023 own"}),
  G + "src/__tests__/ks1207-a-failed-optional-api-key-falls-through-to-the-bearer-check.test.ts": ({"ABSENT": DV}, {"f56bd48b9e9213d5afb85df6c94a5eada3c5aa22": "#1023 own"}),
  G + "src/index.ts":                                                  ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": DV}, {}),
  G + "src/middleware/rateLimitEnforce.ts":                            ({"90bd29378508c8fee54e010b54cdc72ff992aafa": DV}, {}),
  G + "src/routes/proxy.ts":                                           ({"795ae7ca3bdc76be3e563e87fc34a8cc221e5632": DV}, {}),
  G + "src/routes/admin.ts":                                           ({"f47dd6a655702ffbfc402ca920a33c4619d62c4b": DV}, {}),
  G + "src/services/redis.ts":                                         ({"47659ee9c9f06acf9ac64e09b2dc207113ba92ea": DV}, {}),
  G + "src/config/services.ts":                                        ({"6110888aac8c834c291b5385710943f9b6adf57b": DV}, {}),
  G + "src/middleware/rateLimitSkip.ts":                               ({"cfde7cdffb7ab73214c5f009d4be0609d040c2ab": DV}, {}),
  G + "src/__tests__/ks1195-per-key-rate-limiter-runs-after-authentication.test.ts": ({"4b1fc017da158de4e7a3a47565b7dbccc1ea3872": DV}, {}),
  G + "src/__tests__/auth.test.ts":                                    ({"72348995a66ea324ffe78dc64136f46e64985aad": DV}, {}),
  G + "package.json":                                                  ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  G + "vitest.config.ts":                                              ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  G + "vitest.setup.ts":                                               ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  G + "tsconfig.json":                                                 ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "eslint.config.mjs":                                             ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
  D + "packages/shared/src/security/session-validation.ts":            ({"297a0bbd31be5c3868beb1a94d33c8e9d1dcf98d": DV}, {}),
}
# No REGION judgement for #1023: auth.ts is judged by exact blob (a develop move of auth.ts refuses, exit 18 — KS-744 edits the same file next).
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA1023_AUTH_FILE", "") if f == AU else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #1023 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (= the head merge-base, an ANCESTOR of the head: merged tree = the head tree 4bdf1b8c7ea3a679e6b20a21c5970d375ba8776f; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [G + "src/",
           G + "package.json",
           G + "vitest.config.ts",
           G + "vitest.setup.ts",
           G + "tsconfig.json",
           D + "packages/shared/src/",
           D + "eslint.config.mjs",
           D + "package-lock.json"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: EMPTY. #1017 and #1019 have MERGED (on develop 581c9db0d, the pin), so no sibling blob is pre-cleared.
# Every guarded hit falls through to exit 18. Re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 2f74491eb in its own clone, rebuilds the shared dist there, re-runs the optional-mount census, the legitimate-caller table and the limiter rows on the MERGED tree beside the head and develop trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 2, 3, 6, 7)"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — disjoint from the GUARDED list (services/api-gateway/src/ + its config files, packages/shared/src/, eslint.config.mjs, the Dev lockfile); %s" % (pinned, cur, c["ahead_by"], len(files), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 1 GATE #1023 (KS-1207) 2f74491eb' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact #1023 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR and the PRIOR REPORT $PRIOR_REPORT (Record R-4 found the defect), or the prompt does not name NOT-TESTED.written-first.md — the QA agent has no inbox" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition — the merge seat equality targets and the In Progress hold ride on it" >&2; exit 25; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1023 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1023 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact #1023 verdict subject, coagent@ sender, wednesday-agent@ recipient"
  echo "  brief and prompt name the report directory and the #1017 PRIOR REPORT (R-4); prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM and require CLOSED / STILL OPEN / NEW per finding"
  [ -n "${QA1023_CUR_DEV:-}" ] && echo "  (develop read from the QA1023_CUR_DEV test override, not ls-remote)"
  [ -n "${QA1023_AUTH_FILE:-}" ] && echo "  (develop middleware/auth.ts read from the QA1023_AUTH_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1023_BRIEF:-}${QA1023_PROMPT:-}${QA1023_HEAD:-}${QA1023_CUR_DEV:-}${QA1023_AUTH_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
