#!/bin/bash
# launch_qa_secuura_ks1180p1_1029.sh — cross-project QA agent, ONE TIER 2 ROUND 1 gate over Secuura/Blockchain PR #1029 (KS-1180 part 1, Seat A)
# @ cd3580e1f7c6d00ac2ff05d2f3703460feaf34cc — TEST-ONLY: services/api-gateway/src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts
# 4ad1cdcd1 -> d9c98320e (+16 -3). postTier2 now witnesses tier 2 by the stub anchor store's requests (exactly one read of this document) instead of
# blockchain.source (which reads 'persisted' on BOTH tiers: P-1016-1), plus a new control (an absent document: 404 after exactly one anchor-store request).
# Three commits: a4dc0d8ee (the change, parent d7e95cd9f) -> 7553821fc (merge of develop 81ee4b729) -> cd3580e1f (merge of develop 20ab16f9a). TIER 2.
#
# THE SHAPE, as read 21:03-21:14 AEST 2026-09-17 (git ls-remote + the PR and compare APIs agree): compare develop...head = merge_base 20ab16f9a, ahead 3,
# files 1 (asserted, exit 10; behind NOT asserted: develop was 75ad0e55c = #1026, auth only, at draft). The drafter re-derived IN ITS CLONE: merge-tree
# a4dc0d8ee x 81ee4b729 = tree(7553821fc) = 02f3ab417 and merge-tree 7553821fc x 20ab16f9a = tree(cd3580e1f) = 5138ce742; each merge's first-parent diff
# = develop's own delta (name set AND patch-id equal); merged over 75ad0e55c = tree 1227ecc82 (api-gateway + shared subtrees = the head's).
#
# The develop arm judges PATH BLOBS at the CURRENT develop, never develop's SHA and never a path prefix. GUARDED PATHS (Blockchain/Dev/...):
#   services/api-gateway/src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts   develop-OK 4ad1cdcd1 · LANDED d9c98320e (exit 19)
#   services/api-gateway/src/routes/verification.ts 28fb58343 · services/api-gateway/src/services/redis.ts 47659ee9c · services/api-gateway/src/utils/logger.ts
#   77200ea9c (the test's import closure inside api-gateway) · services/api-gateway/package.json 841d8c6ad · vitest.config.ts 5888e0b32 · vitest.setup.ts
#   22c110768 · tsconfig.json c981e6a92 (the suite's configuration) · packages/shared/src TREE 960758bcb (the in-tree @secuura/shared dist is built from it)
# Any of those at a blob nobody pinned -> exit 18. A develop move anywhere else clears, and the api-gateway files it touches are LISTED in the --check
# output (the gate re-measures the whole-suite denominator on its merged tree). WHY: develop moves often tonight; what the gate measures is the one test
# file running the real verification router, so only those bytes can make this brief about different code.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate R-6: a wholesale link can write through to the checkout .vite).
# exit 23: the prompt must carry the exact verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY, and the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM (the merge seat equality targets and the In Progress hold ride on it).
# exit 26: the prompt must carry the probe-location rule — probe files OUTSIDE services/* (the #1018 F-3 lesson: src/qa_probe/ sat inside tsc -p . and
#          vitest's default include).
# QA1029_CUR_DEV (test override, --check only): stands in for origin develop so the GUARDED / LANDED refusals can be proven.
# QA1029_TEST_FILE (test fixture, --check only): a local file stands in for develop's ks1072 test (its git blob) so the LANDED and GUARDED arms can be
# proven without a real develop commit.
# A launch with any QA1029_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1029/gen_launcher_1029.py from launch_qa_secuura_ks1050_1018.sh (asserted substitutions + two whole-block
# replacements + pins re-read from the repo + residual guard + output controls + bash -n): exit codes 2..26 (19 = LANDED), path-blob develop judgement.
#
# Usage: launch_qa_secuura_ks1180p1_1029.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..26 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1029_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1029-ks1180p1-tier2.md}"
PROMPT_FILE="${QA1029_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1029-ks1180p1-tier2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-1180-ks1073-verify-cells-the-tier-guard-is-not-a-tier-witness-the'
HEAD_SHA="${QA1029_HEAD:-cd3580e1f7c6d00ac2ff05d2f3703460feaf34cc}"
MERGE_BASE='20ab16f9a80c5c3c75e613d8c670efefd8f5cafb'   # the merge-base of the head with develop = the head's second parent (#1027s squash), merged in by cd3580e1f
# NO develop SHA pin: develop is judged by PATH BLOBS (header). At draft develop was 75ad0e55c6335a5f34f6d0b74dfe00b334b2eb2e (#1026s squash; git ls-remote 21:09:56, branches API 21:13:04 AEST).
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1180-1029-cd3580e1f-tier2-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1029-ks1180p1-tier2.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1029 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1029 = 20ab16f9a ahead 3 files 1 (behind 1 at draft; behind deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=3 files=1" ] || { echo "REFUSING: #1029 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=3 files=1'" >&2; exit 10; }

# The develop judgement, by PATH BLOBS at the CURRENT develop (see the header) — never develop's SHA, never a prefix. Other moves are listed, not refused.
CUR_DEV="${QA1029_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  MERGE_BASE="$MERGE_BASE" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; mb = os.environ["MERGE_BASE"]
D = "Blockchain/Dev/"
G = D + "services/api-gateway/"
TEST = G + "src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts"
DV = "develop"
# path -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  TEST:                                    ({"4ad1cdcd1e45044efdbb0b8e4e6eaf358453d780": DV}, {"d9c98320ea64638c3ab5ef2f35c102aba6d1207a": "#1029 own"}),
  G + "src/routes/verification.ts":        ({"28fb5834308a502f5f7b806e3b49a77627601eff": DV}, {}),
  G + "src/services/redis.ts":             ({"47659ee9c9f06acf9ac64e09b2dc207113ba92ea": DV}, {}),
  G + "src/utils/logger.ts":               ({"77200ea9c44109bb9e8d63734575fc8e3fa8b083": DV}, {}),
  G + "package.json":                      ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  G + "vitest.config.ts":                  ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  G + "vitest.setup.ts":                   ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  G + "tsconfig.json":                     ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
}
SHARED_SRC_OK = "960758bcb07a2c5c42a0da4b1b1f742b258601da"
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA1029_TEST_FILE", "") if f == TEST else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #1029 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9])
try:
    src = [x for x in get("/contents/" + D + "packages/shared?ref=" + cur) if x.get("name") == "src"]
except Exception as e:
    print("UNJUDGEABLE packages/shared listing unreadable: " + type(e).__name__); sys.exit(0)
if not src or src[0].get("sha") != SHARED_SRC_OK:
    print("GUARDED develop packages/shared/src tree " + (src[0].get("sha", "?")[:9] if src else "ABSENT") + " — a version nobody pinned"); sys.exit(0)
state.append("packages/shared/src tree " + SHARED_SRC_OK[:9])
state = "; ".join(state) + " (all = develop-OK)"
if cur == mb:
    print("OK " + state + " | origin develop = the head merge-base " + mb[:9] + " (merged tree = the head tree 5138ce742)"); sys.exit(0)
try:
    c = get("/compare/" + mb + "..." + cur)
    files = c.get("files") or []
    gwf = sorted(x["filename"].replace(D, "") for x in files if x["filename"].startswith(G))
    moved = "compare status %s, ahead %d behind %d, files %d, api-gateway files %d%s" % (c.get("status"), c.get("ahead_by", -1), c.get("behind_by", -1), len(files), len(gwf), (": " + " ".join(gwf[:6])) if gwf else "")
except Exception as e:
    moved = "delta unread (" + type(e).__name__ + "), not a guard"
tail = "the gate merges the then-current develop onto cd3580e1f in its own clone, names the merged-tree OID, and re-measures the api-gateway denominator and the tamper table there (brief items 1, 3)"
print("OK " + state + " | origin develop is " + cur + ", not the head merge-base " + mb[:9] + " (" + moved + ") — no guarded path moved; " + tail); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV and a GUARDED path moved or could not be judged: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 2' "$BRIEF" && grep -q 'TIER 2' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 2 GATE #1029 (KS-1180) cd3580e1f' "$PROMPT_FILE" && grep -qF '[QA -> Wednesday] TIER 2 GATE #1029 (KS-1180) cd3580e1f' "$BRIEF" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not carry the exact verdict subject, or the prompt lacks the coagent@ sender or the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR, or the prompt does not name NOT-TESTED.written-first.md — the report must land where Wednesday reads it, NOT-TESTED first" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM — the merge seat's equality targets and the In Progress hold ride on it" >&2; exit 25; }
grep -qF 'probe files OUTSIDE services/' "$PROMPT_FILE" && grep -qF 'probe files OUTSIDE services/' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the probe-location rule (probe files OUTSIDE services/*: the #1018 F-3 lesson)" >&2; exit 26; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1029 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1029 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 2 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  brief and prompt carry the exact #1029 verdict subject; prompt names coagent@ sender, wednesday-agent@ recipient"
  echo "  brief and prompt name the report directory; prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM"
  echo "  brief and prompt carry the probe-location rule (probe files OUTSIDE services/*)"
  [ -n "${QA1029_CUR_DEV:-}" ] && echo "  (develop read from the QA1029_CUR_DEV test override, not ls-remote)"
  [ -n "${QA1029_TEST_FILE:-}" ] && echo "  (develop ks1072 test read from the QA1029_TEST_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1029_BRIEF:-}${QA1029_PROMPT:-}${QA1029_HEAD:-}${QA1029_CUR_DEV:-}${QA1029_TEST_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
