#!/bin/bash
# launch_qa_secuura_ks744_1028.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #1028 (KS-744, Seat A)
# @ e39521cfb54cb5fd47c6bdae64ce707b3c9befce — a verified token missing its email or verificationLevel claim is proxied, not answered 500. The fix commit
# 6252f06ac (parent d7e95cd9f): services/api-gateway/src/middleware/auth.ts +3 -2 (x-user-email set only when the claim is truthy; x-verification-level set only
# when truthy, else DELETED) + the ks744 test +93. e39521cfb = a merge of develop 19f1e5475 (which carries #1023 / KS-1207 in the SAME auth.ts) into fb503741a
# (a merge of 81ee4b729 into 6252f06ac); merge-by-content re-derived by the drafter. TIER 1: auth middleware on every proxied route.
#
# THE SHAPE, as read 20:37-20:54 AEST 2026-09-17 (git ls-remote + the PR, compare and contents APIs agree): 19f1e5475 is the head merge-base AND its second
# parent, so compare develop...head = merge_base 19f1e5475, ahead 3, files 2 (asserted, exit 10; behind NOT asserted: develop moved to e02515f8f (#1018),
# 20ab16f9a (#1027) and 75ad0e55c (#1026) while drafting). Head tree b61ed1776 = merge-tree fb503741a x 19f1e5475 in the drafter clone = the seat prediction.
#
# The develop pin is judged by CONTENT, never by develop's SHA: (a) TWENTY-THREE files by blob at the CURRENT develop — the PR two (auth.ts b8fce678a, the ks744
# test ABSENT; at their #1028 blobs -> exit 19 LANDED), trustHeaders.ts (the email half of the fix relies on its strip), index.ts, proxy.ts, admin.ts,
# verification.ts, enforcement.ts, rateLimitEnforce.ts, redis.ts, services.ts, the ks1207 / ks1041 x2 / auth unit tests, api-gateway package.json /
# vitest.config.ts / vitest.setup.ts / tsconfig.json, Dev eslint.config.mjs, shared session-validation.ts / crypto/jwks.ts / db/tenant-guc.ts — any blob nobody
# pinned -> exit 18; (b) if develop moved past 19f1e5475, the compare pinned...develop REFUSES (exit 18) when the delta touches a GUARDED path —
# services/api-gateway/src/ and its config files, packages/shared/src/, eslint.config.mjs, the Dev root lockfile — unless that file's blob is CONTENT-CLEARED,
# or the move cannot be judged. WHY these paths: they are the code the gate runs (the gateway app in-process, the shared auth helpers it imports) and its
# test/type configuration; a develop merge elsewhere (services/auth, other services, frontends, audit baselines) cannot change what the gate measures, so it
# must not make the launcher refuse. DEV_CONTENT_ALLOWED clears ONE blob: Blockchain/Dev/package-lock.json 4831bf207 (#1027: js-yaml and
# baseline-browser-mapping dev bumps; the gate farms node_modules from the checkout install, not from develop's lock).
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate R-6: a wholesale link can write through to the checkout .vite).
# exit 23: the prompt must carry the exact #1028 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY and the PRIOR REPORT on the same file (#1023, KS-1207, merged into this head; the QA agent has no
#          inbox), and the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition.
# QA1028_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA1028_AUTH_FILE (test fixture, --check only): a local file stands in for develop middleware/auth.ts (its git blob) so the LANDED and GUARDED arms can be
# proven without a real develop commit.
# QA1028_LOCK_ALLOW_OFF (test hook, --check only): empties DEV_CONTENT_ALLOWED so the lockfile refusal (exit 18) can be proven.
# A launch with any QA1028_* override, fixture or hook set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1028/gen_launcher_1028.py from launch_qa_secuura_ks1207_1023.sh (asserted substitutions + pins re-read from the repo +
# residual guard + output controls + bash -n): same guard set and exit codes 2..25 (19 = LANDED), re-pointed at #1028 ROUND 1, one content-cleared blob.
#
# Usage: launch_qa_secuura_ks744_1028.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1028_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1028-ks744-tier1.md}"
PROMPT_FILE="${QA1028_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1028-ks744-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-744-gateway-500s-on-every-proxied-route-for-a-token-lacking'
HEAD_SHA="${QA1028_HEAD:-e39521cfb54cb5fd47c6bdae64ce707b3c9befce}"
MERGE_BASE='19f1e54750ce2b65312a687add2db4f5628edb7d'   # the merge-base of the head with develop, the second parent of the head merge e39521cfb (#1025s squash)
DEVELOP_SHA='19f1e54750ce2b65312a687add2db4f5628edb7d'   # the pin = the merge-base; develop was 75ad0e55c at draft close (moves judged by CONTENT: git ls-remote 21:07:47; compare API 20:42 AEST)
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks744-1028-e39521cfb-tier1-r1/'
PRIOR_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1207-1023-2f74491eb-tier1-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1028-ks744-tier1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1028 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1028 = 19f1e5475 ahead 3 files 2 (behind 2 at draft close; behind deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=3 files=2" ] || { echo "REFUSING: #1028 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=3 files=2'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): twenty-three files by blob at the CURRENT develop (no region judgement), then — if develop
# moved — the pinned...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="${QA1028_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
G = D + "services/api-gateway/"
AU = G + "src/middleware/auth.ts"
DV = "develop"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  AU:                                                                   ({"b8fce678a85ecbac82f1e468fd0180059447a43e": DV}, {"6e16683624b3c38a365ece44cccb4fdfac892c71": "#1028 own"}),
  G + "src/__tests__/ks744-a-token-missing-a-claim-is-proxied-not-500.test.ts": ({"ABSENT": DV}, {"2ed41a338ffcf2ecbdc952bad431f52a7a981848": "#1028 own"}),
  G + "src/__tests__/ks1207-a-failed-optional-api-key-falls-through-to-the-bearer-check.test.ts": ({"f56bd48b9e9213d5afb85df6c94a5eada3c5aa22": DV}, {}),
  G + "src/utils/trustHeaders.ts":                                       ({"15626e80f6caea4866abd1bb9ad171c79e12e788": DV}, {}),
  G + "src/index.ts":                                                    ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": DV}, {}),
  G + "src/routes/proxy.ts":                                             ({"795ae7ca3bdc76be3e563e87fc34a8cc221e5632": DV}, {}),
  G + "src/routes/admin.ts":                                             ({"f47dd6a655702ffbfc402ca920a33c4619d62c4b": DV}, {}),
  G + "src/routes/verification.ts":                                      ({"28fb5834308a502f5f7b806e3b49a77627601eff": DV}, {}),
  G + "src/middleware/rateLimitEnforce.ts":                              ({"90bd29378508c8fee54e010b54cdc72ff992aafa": DV}, {}),
  G + "src/services/redis.ts":                                           ({"47659ee9c9f06acf9ac64e09b2dc207113ba92ea": DV}, {}),
  G + "src/services/enforcement.ts":                                     ({"be466fbf444178bbb41293fb1d811957e55e1d2d": DV}, {}),
  G + "src/config/services.ts":                                          ({"6110888aac8c834c291b5385710943f9b6adf57b": DV}, {}),
  G + "src/__tests__/ks1041-vouch-header-strip.test.ts":                 ({"a3e1631f4046288339898170bdaa1f2faff347d5": DV}, {}),
  G + "src/__tests__/ks1041-edge-strip-wiring.test.ts":                  ({"c8e279bcc8ba38bf6e9874b625dd19fb99c93199": DV}, {}),
  G + "src/__tests__/auth.test.ts":                                      ({"72348995a66ea324ffe78dc64136f46e64985aad": DV}, {}),
  G + "package.json":                                                    ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  G + "vitest.config.ts":                                                ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  G + "vitest.setup.ts":                                                 ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  G + "tsconfig.json":                                                   ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "eslint.config.mjs":                                               ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
  D + "packages/shared/src/security/session-validation.ts":              ({"297a0bbd31be5c3868beb1a94d33c8e9d1dcf98d": DV}, {}),
  D + "packages/shared/src/crypto/jwks.ts":                              ({"a131d32caa3faf0f55ca9af1a4fcd889a1affa17": DV}, {}),
  D + "packages/shared/src/db/tenant-guc.ts":                            ({"86953b978062eb1d124abf3154fa1da324c6e110": DV}, {}),
}
# No REGION judgement: auth.ts is judged by exact blob (a develop move of auth.ts refuses, exit 18).
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA1028_AUTH_FILE", "") if f == AU else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #1028 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (= the head merge-base, an ANCESTOR of the head: merged tree = the head tree b61ed17766d282009b707053cbac6b5961076a0f; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [G + "src/",
           G + "package.json",
           G + "vitest.config.ts",
           G + "vitest.setup.ts",
           G + "tsconfig.json",
           D + "packages/shared/src/",
           D + "eslint.config.mjs",
           D + "package-lock.json"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: ONE blob. #1027 moved the Dev root lock (js-yaml 3.15.1 to 3.15.2 and baseline-browser-mapping, dev deps only; READ by the drafter).
# The gate farms node_modules from the checkout install, so a develop lock cannot change its substrate. Any OTHER lock blob refuses, exit 18.
# QA1028_LOCK_ALLOW_OFF empties it (a --check control that proves the lockfile refusal fires). Re-pin deliberately.
DEV_CONTENT_ALLOWED = {} if os.environ.get("QA1028_LOCK_ALLOW_OFF") else {D + "package-lock.json": {"4831bf2074779139926fbfda3f872c404eba177f": "#1027 dev-dep lock bumps, content-cleared by the drafter"}}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto e39521cfb in its own clone, asserts the merged api-gateway and shared subtrees equal the head, or re-runs the missing-claim contract rows, the tamper table and the suites on the MERGED tree; names the merged-tree OID (brief items 1, 3, 4, 5)"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — GUARDED hits %d, content-cleared %s (%s) — disjoint from the rest of the GUARDED list (services/api-gateway/src/ + its config files, packages/shared/src/, eslint.config.mjs, the Dev lockfile); %s" % (pinned, cur, c["ahead_by"], len(files), len(hits), " ".join(x.replace(D, "") for x in cleared) or "none", " ".join(by_name[x]["sha"][:9] for x in cleared), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 1 GATE #1028 (KS-744) e39521cfb' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact #1028 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR and the PRIOR REPORT $PRIOR_REPORT (#1023 on the same file, merged into this head), or the prompt does not name NOT-TESTED.written-first.md — the QA agent has no inbox" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition — the merge seat equality targets and the In Progress hold ride on it" >&2; exit 25; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1028 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1028 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact #1028 verdict subject, coagent@ sender, wednesday-agent@ recipient"
  echo "  brief and prompt name the report directory and the #1023 PRIOR REPORT (same file); prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM and require CLOSED / STILL OPEN / NEW per finding"
  [ -n "${QA1028_CUR_DEV:-}" ] && echo "  (develop read from the QA1028_CUR_DEV test override, not ls-remote)"
  [ -n "${QA1028_AUTH_FILE:-}" ] && echo "  (develop middleware/auth.ts read from the QA1028_AUTH_FILE fixture, not the contents API)"
  [ -n "${QA1028_LOCK_ALLOW_OFF:-}" ] && echo "  (QA1028_LOCK_ALLOW_OFF test hook: the lockfile allowlist is EMPTY)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1028_BRIEF:-}${QA1028_PROMPT:-}${QA1028_HEAD:-}${QA1028_CUR_DEV:-}${QA1028_AUTH_FILE:-}${QA1028_LOCK_ALLOW_OFF:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
