#!/bin/bash
# launch_qa_secuura_batch1202-t2.sh — cross-project QA agent, ONE BATCHED ROUND 1 TIER-2 gate over FOUR Secuura/Blockchain PRs raised by Seat B 21st
# (seat PRs 1, 2, 4, 5 of round 20 — KS-851 / seat PR 3 was re-graded to tier 1 by Wednesday's 05:12:13Z ANSWER and is the tier-1 gate's):
# #1202 KS-965 doc_patch · #1203 KS-1019 comment_patch (token equivalence — a NEW kind) · #1205 KS-1081 test_only on a bash suite with a script tamper
# (a NEW kind) · #1206 KS-1139 test_only on a bash suite, two tampers flipped separately. TIER 2 on all four. 4 paths; +30/-2; ZERO overlap with the
# tier-1 batch's 12 paths and the two tamper files.
# EVERY VALUE HERE IS THE SEAT MEASUREMENT RE-DERIVED BY THE DRAFTER, never adopted: heads by ls-remote (branch AND refs/pull/N/head), the per-PR
# trees / blobs / modes by ls-tree in a scratch clone FROM ORIGIN (never --shared from the checkout), the tier-2 sub-tree by REAL merge-tree chains in
# three orders (predict_batch_scratch_2.out), every BOTH-list token asserted present in the READY capture and the prompt.
# PR 5 (#1206) IS A ROW LIKE THE OTHERS: its head is re-read at origin on EVERY run (branch AND refs/pull/1206/head, exit 6). A row whose head is not
# 40-hex (a PENDING PR 5) or a prompt carrying a PENDING-PR- token refuses (exit 34) — the tier-2 gate never launches without PR 5.
# THE SHAPE: each head is ONE commit whose parent IS develop 2bc5ccf63b8c40911afb568b03cace066238ffcf; the compare per PR reads develop...head = merge_base == the pin, ahead 1,
# BEHIND 0, files 1/1/1/1 (exit 10 — a develop move changes `behind` and REFUSES: re-pin deliberately — the tier-1 GO may land its merges first).
# ALL FOUR over develop = d13a26e19c8d1b2faf25f9e41cc087fbcd51ec47 (the TIER-2 SUB-TREE; the END STATE if every merge lands on the pin). The develop pin is judged by CONTENT too — the
# 4 target paths at the CURRENT develop (any head blob present -> exit 19 LANDED; any other change to a target -> exit 18; a disjoint move (the tier-1
# merges) -> exit 17).
# exit 6:  any head is not at its branch AND at refs/pull/N/head on origin (the refusal names the PR).
# exit 7:  the prompt must carry TIER 2 on all four and each PR's own tier line (#1202 T2 #1203 T2 #1205 T2 #1206 T2).
# exit 8:  the prompt must open with the thinking directive and name the brief path + the READY capture.
# exit 10: the compare per PR (merge_base == the pin, ahead 1, behind 0, files as pinned) — develop moving refuses here.
# exit 17/18/19: the develop pin judged by content (above).
# exit 20: the READY capture AND the prompt must name every pinned head in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. `--check` runs headless (it launches nothing).
# exit 23: the prompt must carry the exact verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient, FOUR verdict lines.
# exit 25: the prompt must carry the MERGE ADDENDUM per PR with ONE equality target PER PR FILE, the `## MERGE ADDENDUM` heading, KEY-FREE SHIPS-WITH.
# exit 26: the prompt must name WEDNESDAY'S signed GO as each PR's merge authority.
# exit 30: the READY capture AND the prompt must BOTH carry the seat items (the BOTH list below); the prompt must say MEASURE, not conclude and RULE WHETHER IT BLOCKS.
# exit 31: the prompt must name the tier-2 sub-tree and develop in full.
# exit 32: the READY capture AND the prompt must BOTH state which ticket each PR is (PR #1202 is KS-965. …).
# exit 33: the prompt must carry the twelve by-name items by their keywords (the ladder below) and the standard closing.
# exit 34: PARTIAL — a PENDING-PR- token in the prompt, fewer than FOUR rows, or a row whose head is not 40-hex (PR 5 not yet pinned) — --check and launch alike.
# exit 35: the prompt must carry the KS-1019 TOKEN INSTRUMENT: a planted-token control that FIRES and a planted-comment control, the three counts.
# exit 36: the prompt must carry the bash-kind rule: each tamper ONE AT A TIME, the two tampers' DIFFERENT subsets, the zero-cell STOP.
# QAB1202_CUR_DEV (test override, --check only): stands in for origin develop. QAB1202_HEAD_1206 (test override): stands in for #1206's pinned head.
# QAB1202_BRIEF / QAB1202_PROMPT (test overrides): stand in for the READY capture / the prompt. A launch with any QAB1202_* override set refuses (exit 16).
# Generated by gatesets/2026-09-23_gate20T2_seatB/gen_launcher_gate20T2.py at 2026-09-23T06:53:34Z.
# Usage: launch_qa_secuura_batch1202-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
BRIEF="${QAB1202_BRIEF:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-23_gate20T2_seatB/mail_gate20T2_ready.md}"
PROMPT_FILE="${QAB1202_PROMPT:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/briefs/2026-09-23_secuura-batch1202-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
PRS=(
  "1202|KS-965|refs/heads/feature/ks-965-87-documentary-sites-still-publish-the-retired-admin-r20-adminpwdoc-1|49f419e625d7304f724b4a604f542827b7772458|1"
  "1203|KS-1019|refs/heads/feature/ks-1019-question-the-documents-whole-blockchain-block-is-published-r16b-leaveuntyped-1|81accbcfeae3628f00d8698ef1743c53b946bfce|1"
  "1205|KS-1081|refs/heads/feature/ks-1081-config-drift-two-tracked-env-templates-disagree-by-39-vars-r17-neithertemplate-1|d29a9b21dd70f8e1fb79c56e595e312499edee43|1"
  "1206|KS-1139|refs/heads/feature/ks-1139-bare-arithmetic-command-x-under-set-e-exits-1-at-0-and-bash-r17-errexitbehaviour-1|bfbaf4366897a97ec20c2f88e67448597739ce46|1"
)
DEVELOP_SHA='2bc5ccf63b8c40911afb568b03cace066238ffcf'
ALL_OVER_DEV='d13a26e19c8d1b2faf25f9e41cc087fbcd51ec47'
# path|develop blob or ABSENT|LANDED blobs (comma) — the content judgement of the develop pin
JUDGED=(
  "USER_TESTING/CREDENTIALS-AND-PORTALS.md|82bbf39e9595d6cd023d35b5119c6f2286e431f8|f2487018dea31c2c7b9f491c9ca7ee735673b6a7"
  "Blockchain/Dev/services/originate/src/originate.openapi.ts|2d1b48a0c7ea93521d553cc28ccb53b4fe3fd19c|f9675bf9607787fee7ec619d6893590a6adb9717"
  "Blockchain/Dev/scripts/__tests__/bootstrap_env_canonical_template.test.sh|7f938694b60c97217b7494e8603fd6ba4d5c15da|bbe4907847fa67627eb04c28e9a053840a1cf728"
  "Blockchain/Dev/scripts/__tests__/validate_lint_errexit.test.sh|bde065b6e068b87a731bfeb001fbac9336d18d8b|4d11b28d28f6c30389142bf69819d56b4cc73cc5"
)
[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief (READY capture) missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }
grep -qF 'PENDING-PR-' "$PROMPT_FILE" && { echo "REFUSING: the prompt is PARTIAL (a PENDING-PR- token) — a partial gate is not a gate" >&2; exit 34; }
[ "${#PRS[@]}" -eq 4 ] || { echo "REFUSING: PARTIAL — ${#PRS[@]} rows, the tier-2 batch is FOUR (#1202 #1203 #1205 and PR 5)" >&2; exit 34; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s' "$_h" | grep -qE '^[0-9a-f]{40}$' && printf '%s' "$_n" | grep -qE '^[0-9]+$' || { echo "REFUSING: PARTIAL — row '$_n $_t' has no pinned head ($_h): PR 5 not yet taken (take_pr5_gate20T2.sh)" >&2; exit 34; }
done
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF 'fleet/briefs_staged/2026-09-23_raise_seatB_21.md' "$PROMPT_FILE" && grep -qF 'mail_gate20T2_ready.md' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the brief path and the READY capture" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  [ "$_n" = "1206" ] && [ -n "${QAB1202_HEAD_1206:-}" ] && _h="$QAB1202_HEAD_1206"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong, or the PR is gone); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1202_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
base = os.environ["CUR_DEV"]
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf = pr.split("|")
    try:
        c = get(api + base + "..." + h); print("%s %s ahead=%d behind=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
if [ "$CUR_DEV" != "$DEVELOP_SHA" ]; then
  JUDGE="$(
    set -a; . "$SECUURA_ENV"; set +a
    JUDGED_FLAT="$(printf '%s\n' "${JUDGED[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); base = "https://api.github.com/repos/Secuura/Distributed_Secuura/contents/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
worst = "DISJOINT"
for row in os.environ["JUDGED_FLAT"].splitlines():
    path, dev, landed = row.split("|")
    try: cur = get(base + path + "?ref=" + os.environ["CUR_DEV"])["sha"]
    except Exception: cur = "ABSENT"
    if cur == dev: continue
    if cur in landed.split(","): print("LANDED", path, cur); worst = "LANDED"
    else: print("CHANGED", path, dev, "->", cur); worst = "CHANGED" if worst != "LANDED" else worst
print("VERDICT", worst)
PY
  )"
  printf '%s\n' "$JUDGE" >&2
  case "$JUDGE" in
    *"VERDICT LANDED"*) echo "REFUSING: a target already LANDED on develop $CUR_DEV (the pin is $DEVELOP_SHA) — a merge happened; re-pin" >&2; exit 19;;
    *"VERDICT CHANGED"*) echo "REFUSING: develop $CUR_DEV (the pin is $DEVELOP_SHA) changed a target path — re-predict" >&2; exit 18;;
    *) echo "REFUSING: develop $CUR_DEV != the pin $DEVELOP_SHA (a disjoint move — the tier-1 batch's merges?) — re-predict every tree and re-pin the launcher deliberately" >&2; exit 17;;
  esac
fi
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s\n' "$COMPARE" | grep -q "^${_n} ${DEVELOP_SHA} ahead=1 behind=0 files=${_f}\$" || _bad=1
done
if [ "$_bad" = 1 ]; then
  echo "REFUSING: a compare is not merge_base $DEVELOP_SHA / ahead 1 / behind 0 / files as pinned (develop moved, a head moved, or the API failed):" >&2
  printf '%s\n' "$COMPARE" >&2
  exit 10
fi
DEV_NOTE="origin develop $CUR_DEV == the pin (the heads' parent); 4 compares merge_base == pin, ahead 1, behind 0, files as pinned"
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the READY capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
done
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the READY capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
done
PROMPT_JOINED0="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in '#1202 T2' '#1203 T2' '#1205 T2' '#1206 T2'; do grep -qF -- "$_w" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '$_w'" >&2; exit 7; }; done
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'TIER 2 on all four' && grep -qF -- 'round 1 of 2' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry TIER 2 on all four / round 1 of 2" >&2; exit 7; }
for _w in \
  '.push-lock-20' \
  '1 ok / 3 FAIL' \
  '12/15' \
  '17679' \
  '17731' \
  '17736' \
  '2 ok / 2 FAIL' \
  '2bc5ccf63' \
  '2bc5ccf63b8c40911afb568b03cace066238ffcf' \
  '3f31d9e91e2f' \
  '4 files changed, 30 insertions(+), 2 deletions(-)' \
  '49f419e625d7304f724b4a604f542827b7772458' \
  '4d11b28d28f6' \
  '6 ok / 1 FAIL' \
  '6417b203accd839f' \
  '6beda06e9d9e' \
  '6c6fa6f4efcabf61' \
  '81accbcfeae3628f00d8698ef1743c53b946bfce' \
  '830ed7609143' \
  '86 documentary occurrences' \
  '8c02c7b62858' \
  '8ec20706235387ab' \
  'ADMIN_USER_PASSWORD' \
  'Default-tenant accounts' \
  'FAILPLUSPLUS' \
  'GO: merge #1202, #1203, #1205, #1206 batch' \
  'GUARDGONE' \
  'In Progress' \
  'KS-1019' \
  'KS-1081' \
  'KS-1139' \
  'KS-547' \
  'KS-965' \
  'PASSPLUSPLUS' \
  'PREFLIGHT INCOMPLETE' \
  'PROTOCOL-CLEAN' \
  'Quick smoke' \
  'SKIPPED' \
  'bash -e' \
  'bbe4907847fa' \
  'bfbaf4366897a97ec20c2f88e67448597739ce46' \
  'bootstrap-env.sh' \
  'c4tokens.js' \
  'contributes' \
  'd13a26e19c8d1b2faf25f9e41cc087fbcd51ec47' \
  'd29a9b21dd70f8e1fb79c56e595e312499edee43' \
  'e0875f05bd01dab2' \
  'f2487018dea3' \
  'f32e4b95d1b5cf3d' \
  'f9675bf96077' \
  'kamil.kreiser@secuura.ai' \
  'line 590' \
  'login_stub' \
  'prs.tsv' \
  'raise13.py' \
  'raise15.py' \
  'raise20.py' \
  'run_check' \
  'services/auth/' \
  'tickets_boot.json' \
  'validate-lint.sh' \
  'z.unknown()'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the READY capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
grep -qF 'MEASURE, not conclude' "$PROMPT_FILE" && grep -qF 'RULE WHETHER IT BLOCKS' "$PROMPT_FILE" || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS missing" >&2; exit 30; }
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s+", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in \
  'TIER AND ROUND' \
  'ASSIGN the tier from the files' \
  'STATE BOTH' \
  'round 1 of 2' \
  'PRODUCT vs TEST-FILE-ONLY vs DOC vs COMMENT exactly as each READY declares' \
  'TREES over `2bc5ccf63`' \
  'in >= 3 orders' \
  '0 overlap with the tier-1 batch' \
  'CANONICAL-PATCH IDENTITY' \
  'CELLS per lane' \
  'read, do not compose' \
  'PER-FILE TYPECHECK DELTA 0' \
  'CENSUS v2' \
  'NEVER connect' \
  'LINEAR LINK HYGIENE' \
  'attachmentsForURL per PR exactly its own key' \
  'subjects <= 92 chars ASCII' \
  'THE ONE-SEAT ARTEFACTS' \
  'BOARD GUARD' \
  'THE SEAT'"'"'S OWN FINDINGS/SLIPS' \
  'CONFIRMED / REFUTED' \
  'INTERMITTENTS per PR (do not block)' \
  'RULE WHETHER IT BLOCKS' \
  'MERGE ADDENDUM' \
  'four lines VERBATIM in report.md' \
  '1/1/1/1' \
  'stays In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'READ THE WHOLE TEST FILE' \
  'NOT-TESTED first' \
  'CONTEXT RULE' \
  'at ctx 80' \
  'BASE_GO' \
  'END_TREE' \
  '## MERGE ADDENDUM' \
  'MEASURE, not conclude' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'node_modules PER ENTRY' \
  'never print a credential value' \
  'No memory maintenance' \
  'NOT-TESTED.written-first.md' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '[QA -> Wednesday] TIER-2 BATCH GATE #1202-#1206 (four PRs; tier 2 = #1202, #1203, #1205, #1206: Seat B 21st — doc_patch + comment_patch (token equivalence) + two bash test_only cells with script tampers) —' \
  'fleet/briefs_staged/2026-09-23_raise_seatB_21.md' \
  'WEDNESDAY'"'"'S signed GO naming each head' \
  'Never enter any seat worktree' \
  '2026-09-23_seatB-21st' \
  'mail_gate20T2_ready.md' \
  'if the tier-1 gate' \
  'BASE moves' \
  'TOKEN EQUIVALENCE' \
  'the merging seat must re-predict' \
  'Datasec files and mail are out of scope entirely' \
  'never print the retired admin literal' \
  'CLOSES it' \
  'THE GATE MUST RE-RUN THE TOKEN-EQUIVALENCE PROOF ITSELF' \
  'VACUOUS PASS' \
  'CARRY-FORWARD'; do
  printf '%s' "$PROMPT_JOINED" | grep -qF -- "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'planted-comment control' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'planted-token control that FIRES' && grep -qF -- '17679' "$PROMPT_FILE" && grep -qF -- '17731' "$PROMPT_FILE" || { echo "REFUSING: the KS-1019 token instrument (planted-token control that FIRES + planted-comment control + the counts) is not in the prompt" >&2; exit 35; }
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'ONE AT A TIME' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'DIFFERENT subsets' && printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'zero parsed cells' || { echo "REFUSING: the bash-kind rule (one tamper at a time, different subsets, the zero-cell STOP) is not in the prompt" >&2; exit 36; }
grep -qF -- "WEDNESDAY'S signed GO naming each head" "$PROMPT_FILE" || { echo "REFUSING: merge authority" >&2; exit 26; }
grep -qF -- '## MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF -- 'ONE equality target PER PR FILE' "$PROMPT_FILE" && grep -qF -- 'KEY-FREE' "$PROMPT_FILE" || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 BATCH GATE #1202-#1206 (four PRs;' "$PROMPT_FILE" && grep -qF -- 'FROM coagent@agentmail.to' "$PROMPT_FILE" && grep -qF -- 'FOUR lines, one per PR' "$PROMPT_FILE" || { echo "REFUSING: the verdict subject / sender / four lines" >&2; exit 23; }
grep -qF -- "$ALL_OVER_DEV" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" || { echo "REFUSING: the tier-2 sub-tree / develop not in full" >&2; exit 31; }
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  heads on origin (branch AND refs/pull/N/head):$HEADS_NOTE"
  echo "  compares (GitHub API), develop...head per PR (merge_base + ahead + behind + files):"
  printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  $DEV_NOTE"
  echo "  READY capture, prompt, QA project and repo all present; FOUR rows each with a 40-hex head; the prompt is not PARTIAL; opens with the thinking directive; names the brief path and the capture"
  echo "  prompt carries TIER 2 on all four and each PR tier (#1202 T2 #1203 T2 #1205 T2 #1206 T2); round 1 of 2"
  echo "  READY capture and prompt both name every pinned head in full and which ticket each PR is"
  echo "  READY capture and prompt BOTH carry the seat items (62 tokens); the prompt says MEASURE, not conclude, and RULE WHETHER IT BLOCKS"
  echo "  prompt carries the twelve by-name items (65 keywords), the KS-1019 token instrument, the bash-kind rule, the merge authority, the MERGE ADDENDUM rules, the verdict subject / sender / four lines, the tier-2 sub-tree and develop in full"
  [ -n "${QAB1202_CUR_DEV:-}" ] && echo "  (develop read from the QAB1202_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1202_BRIEF:-}${QAB1202_PROMPT:-}${QAB1202_HEAD_1206:-}${QAB1202_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
