#!/bin/bash
# launch_qa_secuura_batch1180-1197.sh — cross-project QA agent, ONE BATCHED ROUND 1 gate over TWELVE Secuura/Blockchain PRs (Seat C 19th):
# TIER 1 on the NINE bash_patch script PRs (#1180 #1181 #1183 #1185 #1187 #1188 #1190 #1191 #1192 — script bytes in the fleet's own gates and the
# box's boot path: start-secuura.sh x2 (the ONE same-file PAIR, --pair-blob on #1181 after #1180), run-migrations.sh, check-no-demo-mutation.sh,
# check-stack-safety.sh, preflight.sh, .githooks/pre-push, bootstrap-env.sh, validate-lint.sh), TIER 2 on the three KS-1097 docs PRs (#1193 #1195 #1197).
# FOURTEEN READYs (13 R16B rows + 1 Claude-written PRPROCESS) in twelve PRs; 21 paths; +915/-29; ZERO overlap with Seat B 19th/20th's partition.
# EVERY VALUE HERE IS THE SEAT MEASUREMENT RE-DERIVED BY THE DRAFTER, never adopted: heads by ls-remote (branch AND refs/pull/N/head), the per-PR
# trees / blobs / modes by ls-tree in a scratch clone FROM ORIGIN (never --shared from the checkout), the all-12 tree by REAL merge-tree chains in
# three orders (predict_batch_scratch_1.out), every BOTH-list token asserted present in the READY capture and the prompt.
# THE SHAPE: each head is ONE commit whose parent IS develop 3bad652d17cf111c1e2e1bed1ae7686894637487 (tree cd9b0f6c7b84); the compare per PR reads
# develop...head = merge_base 3bad652d1, ahead 1, BEHIND 0, files 2/2/2/2/3/2/2/2/2/1/1/1 (exit 10 — a develop move changes `behind` and REFUSES:
# re-pin deliberately — Seat B 20th's GO may land its merges first). ALL TWELVE over develop = 5a8458a5697f7ee5b1800864b9f49347c8cbe34e (the END STATE if
# every merge lands on 3bad652d1). The develop pin is judged by CONTENT too — the 21 target paths at the CURRENT develop (10 NEW suites judged ABSENT;
# 11 MODIFIED files by blob — any present head blob, or start-secuura.sh at the PAIR blob, -> exit 19 LANDED; any other change -> exit 18; a
# disjoint move -> exit 17).
# exit 6:  any head is not at its branch AND at refs/pull/N/head on origin (the refusal names the PR).
# exit 7:  the prompt must carry TIER 1 on NINE and each PR own tier line (#1180 T1 #1181 T1 #1183 T1 #1185 T1 #1187 T1 #1188 T1 #1190 T1 #1191 T1 #1192 T1 #1193 T2 #1195 T2 #1197 T2).
# exit 8:  the prompt must open with the thinking directive and name the brief path + the READY capture.
# exit 10: the compare per PR (merge_base 3bad652d1, ahead 1, behind 0, files as pinned) — develop moving refuses here.
# exit 17/18/19: the develop pin judged by content (above).
# exit 20: the READY capture AND the prompt must name every pinned head in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. `--check` runs headless (it launches nothing).
# exit 23: the prompt must carry the exact batch verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient, TWELVE verdict lines.
# exit 25: the prompt must carry the MERGE ADDENDUM per PR with ONE equality target PER PR FILE, the `## MERGE ADDENDUM` heading, KEY-FREE SHIPS-WITH.
# exit 26: the prompt must name WEDNESDAY'S signed GO as each PR merge authority.
# exit 30: the READY capture AND the prompt must BOTH carry the seat items (the BOTH list below); the prompt must say MEASURE, not conclude and RULE WHETHER IT BLOCKS.
# exit 31: the prompt must name the all-12 tree and develop in full.
# exit 32: the READY capture AND the prompt must BOTH state which ticket each PR is (PR #1180 is KS-972. …).
# exit 33: the prompt must carry Wednesday's twelve by-name items by their keywords (the ladder below) and the standard closing.
# exit 34: a PARTIAL prompt (any `PENDING-PR-` token) refuses — --check and launch alike.
# exit 35: the prompt must carry the PAIR: `--pair-blob`, the pair blob 58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb in full, and `alone blob`.
# QAB1180_CUR_DEV (test override, --check only): stands in for origin develop. QAB1180_HEAD_1197 (test override): stands in for #1197's pinned head.
# QAB1180_BRIEF / QAB1180_PROMPT (test overrides): stand in for the READY capture / the prompt. A launch with any QAB1180_* override set refuses (exit 16).
# Generated by gatesets/2026-09-22_gate19C_seatC/gen_launcher_gate19C.py at 2026-09-22T07:48:07Z.
# Usage: launch_qa_secuura_batch1180-1197.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
BRIEF="${QAB1180_BRIEF:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-22_gate19C_seatC/mail_gate19C_ready.md}"
PROMPT_FILE="${QAB1180_PROMPT:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/briefs/2026-09-22_secuura-batch1180-1197.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
PRS=(
  "1180|KS-972|refs/heads/feature/ks-972-start-secuurash-banner-prints-adminsecuuracom-admin123-which-r16b-banner-1|ad86ffdbf504c250c1144f7d59ddcdba4966568d|2"
  "1181|KS-1011|refs/heads/feature/ks-1011-stack-marker-reads-unknown-for-r16b-markerwarn-1|b2c0ac2d94387f9ce63c76ec437a465aca63a85f|2"
  "1183|KS-1031|refs/heads/feature/ks-1031-gate-f-4-deploy-condition-apply-048-before-rolling-r16b-exit3-1|03fab6783d5e1ad5893178027abc2291abeb627e|2"
  "1185|KS-1033|refs/heads/feature/ks-1033-residue-the-three-guards-that-could-not-be-wired-and-r16b-demobase-1|46e174169084318329b49f1c2109e210e7b8f743|2"
  "1187|KS-1034|refs/heads/feature/ks-1034-check-stack-safetysh-resolves-the-wrong-repo-root-inside-a-r16b-hookenv-latestslot-1|40d352edcb386a63083ff22422b3604f945575df|3"
  "1188|KS-1040|refs/heads/feature/ks-1040-push-preflight-leg-4-reports-a-published-path-is-unroutable-r16b-sweeprc-1|fa13f78e8a87769d82c51b070d165f24e677a3a3|2"
  "1190|KS-1047|refs/heads/feature/ks-1047-pre-push230-names-the-stack-dependent-legs-as-3-4-7-measured-r16b-stacklegs-2|6b836f0afab7c129747e8818626be9edd1975932|2"
  "1191|KS-1081|refs/heads/feature/ks-1081-config-drift-two-tracked-env-templates-disagree-by-39-vars-r16b-canonenv-1|b7dc03c142c9e65cd5112b5eee63c863bc368a93|2"
  "1192|KS-1139|refs/heads/feature/ks-1139-bare-arithmetic-command-x-under-set-e-exits-1-at-0-and-bash-r16b-errexit-1|fe9cd46daa4a8e50ed37fca3f48fd23e6d05e44a|2"
  "1193|KS-1097|refs/heads/feature/ks-1097-merge-rule-docs-after-957-the-v4-footer-and-two-gate-r16b-contributing-reviewreq-prprocess-1|deb7ddb99c799d50969f1c70720d3d0cc3004d34|1"
  "1195|KS-1097|refs/heads/feature/ks-1097-merge-rule-docs-after-957-the-v4-footer-and-two-gate-r16b-devprocess-1|48061f24a0510e4133a9fa0be51b0f7b30b8fc85|1"
  "1197|KS-1097|refs/heads/feature/ks-1097-merge-rule-docs-after-957-the-v4-footer-and-two-gate-r16b-claudemd-1|661da6c23e233c682f30c3de83b71ef46c8a5bbb|1"
)
DEVELOP_SHA='3bad652d17cf111c1e2e1bed1ae7686894637487'
ALL_OVER_DEV='5a8458a5697f7ee5b1800864b9f49347c8cbe34e'
PAIR_BLOB='58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb'
# path|develop blob or ABSENT|LANDED blobs (comma) — the content judgement of the develop pin
JUDGED=(
  ".githooks/pre-push|1b22d4e146487aa25698310b353152a7d09986b5|ea44b2277e126633bf4922d0880fe2b51d96d8ba"
  "Blockchain/Dev/CONTRIBUTING.md|b3cc10a400898d6ea2211f870984f810897f1dc5|bbcc95cfc9f137ac16218ef2e42921a49849be68"
  "Blockchain/Dev/docs/DEV-PROCESS.md|ab9a70f13e3c18b270117297d5e5dad5f0be38c1|4b86a3d8df445df0d8e8afc12bb5b598a5ed4ed5"
  "Blockchain/Dev/scripts/__tests__/bootstrap_env_canonical_template.test.sh|ABSENT|7f938694b60c97217b7494e8603fd6ba4d5c15da"
  "Blockchain/Dev/scripts/__tests__/check_no_demo_mutation_base.test.sh|ABSENT|78324a8d8fa8583bee278c1523c2111c1dadaaac"
  "Blockchain/Dev/scripts/__tests__/check_stack_safety_hook_env.test.sh|ABSENT|e673f5979922217ee36aee65ed42df739b1a4b0b"
  "Blockchain/Dev/scripts/__tests__/check_stack_safety_latest_slot_symlink.test.sh|ABSENT|25c325a07f51240a8bd39c68504d8e899bba57c4"
  "Blockchain/Dev/scripts/__tests__/pre_push_stack_legs_comment.test.sh|ABSENT|e77bf0be28e12273d51215fc29a65de6f26883b8"
  "Blockchain/Dev/scripts/__tests__/preflight_leg4_sweep_not_run.test.sh|ABSENT|65c09b0f213a325d9d5c078b2cd43b2f894158d7"
  "Blockchain/Dev/scripts/__tests__/run_migrations_failure_exit_code.test.sh|ABSENT|c998bd7ed21de813c5c76950962cd88616eb6eae"
  "Blockchain/Dev/scripts/__tests__/start_secuura_banner.test.sh|ABSENT|60db49e9364cc0b43808a8d49e19e42a62cbf015"
  "Blockchain/Dev/scripts/__tests__/start_secuura_marker_unknown_warning.test.sh|ABSENT|7c3010a18153f5722ba8f56ba3263c3acf4aac18"
  "Blockchain/Dev/scripts/__tests__/validate_lint_errexit.test.sh|ABSENT|bde065b6e068b87a731bfeb001fbac9336d18d8b"
  "Blockchain/Dev/scripts/bootstrap-env.sh|9201fc4226ed545af59a5990c42499d6d4943bf0|76958c117fe821e1fdbcda46aff1e1bdbc65143c"
  "Blockchain/Dev/scripts/check-no-demo-mutation.sh|4d11e288aaa2a1946845814723fe71502d28dfc7|3b4af5b463b1d3045866c781b69b27408349b90c"
  "Blockchain/Dev/scripts/check-stack-safety.sh|9ffde6c63b4227429b7fc4a5af8f2ece6b83a129|894ba4612b169b18add6ca6a7154a6498b9d5a38"
  "Blockchain/Dev/scripts/preflight/preflight.sh|fe29676b7073d4b6b9a71d492de962777cf5bdf8|270b8913c009a360759ea18bf7cf250f466cf67e"
  "Blockchain/Dev/scripts/run-migrations.sh|cd4a945ff8e2c25b42eaf17f3f82a4cdf1ce938b|633e92de23086ca70174be2f17b90d3c4e2c78fc"
  "CLAUDE.md|ef2f8fc2e4cb614c72cf64b2b32bc60509a4a3ea|eccdb71822dae2563de0f6a88620a6ca7d55d769"
  "Start_Up/start-secuura.sh|9cb66f8356e1a867d2697e715cd09ce75a2ee069|1882bb0c5114eceda8ac90c442e852e201b822e7,58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb,9bb5e5e1272d5dad2db6581135b0ddf79b029ba9"
  "systemTest/schemathesis/validate-lint.sh|c11cd8d3d94a4cc9a3ae3bfa2fde33ce6bc49d96|f5fd1883cc7eb9823c3047de1ac4c4a7e6b0d26a"
)
[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief (READY capture) missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }
grep -qF 'PENDING-PR-' "$PROMPT_FILE" && { echo "REFUSING: the prompt is PARTIAL (a PENDING-PR- token) — a partial gate is not a gate" >&2; exit 34; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF 'fleet/briefs_staged/2026-09-22_raise_seatC_19.md' "$PROMPT_FILE" && grep -qF 'mail_gate19C_ready.md' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the brief path and the READY capture" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  [ "$_n" = "1197" ] && [ -n "${QAB1180_HEAD_1197:-}" ] && _h="$QAB1180_HEAD_1197"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1180_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
base = os.environ["CUR_DEV"]
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf = pr.split("|")
    try:
        c = get(api + base + "..." + h); print("%s %s ahead=%d behind=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
if [ "$CUR_DEV" != "$DEVELOP_SHA" ]; then
  JUDGE="$(
    set -a; . "$SECUURA_ENV"; set +a
    JUDGED_FLAT="$(printf '%s\n' "${JUDGED[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); base = "https://api.github.com/repos/Secuura/Distributed_Secuura/contents/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
worst = "DISJOINT"
for row in os.environ["JUDGED_FLAT"].splitlines():
    path, dev, landed = row.split("|")
    try: cur = get(base + path + "?ref=" + os.environ["CUR_DEV"])["sha"]
    except Exception: cur = "ABSENT"
    if cur == dev: continue
    if cur in landed.split(","): print("LANDED", path, cur); worst = "LANDED"
    else: print("CHANGED", path, dev, "->", cur); worst = "CHANGED" if worst != "LANDED" else worst
print("VERDICT", worst)
PY
  )"
  printf '%s\n' "$JUDGE" >&2
  case "$JUDGE" in
    *"VERDICT LANDED"*) echo "REFUSING: a target already LANDED on develop $CUR_DEV (the pin is $DEVELOP_SHA) — a merge happened; re-pin" >&2; exit 19;;
    *"VERDICT CHANGED"*) echo "REFUSING: develop $CUR_DEV (the pin is $DEVELOP_SHA) changed a target path — re-predict" >&2; exit 18;;
    *) echo "REFUSING: develop $CUR_DEV != the pin $DEVELOP_SHA (a disjoint move — Seat B's merges?) — re-predict every tree and re-pin the launcher deliberately" >&2; exit 17;;
  esac
fi
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s\n' "$COMPARE" | grep -q "^${_n} ${DEVELOP_SHA} ahead=1 behind=0 files=${_f}\$" || _bad=1
done
if [ "$_bad" = 1 ]; then
  echo "REFUSING: a compare is not merge_base $DEVELOP_SHA / ahead 1 / behind 0 / files as pinned (develop moved, a head moved, or the API failed):" >&2
  printf '%s\n' "$COMPARE" >&2
  exit 10
fi
DEV_NOTE="origin develop $CUR_DEV == the pin (the heads' parent); 12 compares merge_base == pin, ahead 1, behind 0, files as pinned"
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the READY capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
done
grep -qF -- 'PR #1180 is KS-972.' "$PROMPT_FILE" && grep -qF -- 'PR #1187 is KS-1034.' "$PROMPT_FILE" && grep -qF -- 'PR #1197 is KS-1097.' "$PROMPT_FILE" && grep -F '#1180' "$BRIEF" | grep -qF 'KS-972' && grep -F '#1197' "$BRIEF" | grep -qF 'KS-1097' \
  || { echo "REFUSING: the READY capture and the prompt do not BOTH state which ticket each PR is" >&2; exit 32; }
for _w in '#1180 T1' '#1181 T1' '#1183 T1' '#1185 T1' '#1187 T1' '#1188 T1' '#1190 T1' '#1191 T1' '#1192 T1' '#1193 T2' '#1195 T2' '#1197 T2'; do grep -qF -- "$_w" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '$_w'" >&2; exit 7; }; done
grep -qF -- 'TIER 1 on the NINE' "$PROMPT_FILE" && grep -qF -- 'round 1 of 2' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry TIER 1 on the NINE / round 1 of 2" >&2; exit 7; }
for _w in \
  '--pair-blob' \
  '.push-lock-19' \
  '03fab6783d5e1ad5893178027abc2291abeb627e' \
  '100755' \
  '12/15' \
  '18499832' \
  '1882bb0c5114' \
  '21 files changed, 915 insertions(+), 29 deletions(-)' \
  '215cb4d912865eb4' \
  '221f351eb6139679' \
  '25c325a07f51' \
  '270b8913c009' \
  '2a1027d8bfa1d291' \
  '2f8252aa67c13b08' \
  '3089354086978ae7' \
  '32b68acb0feeb2d9' \
  '397009793d67fefe' \
  '3b4af5b463b1' \
  '3bad652d17cf111c1e2e1bed1ae7686894637487' \
  '40d352edcb386a63083ff22422b3604f945575df' \
  '45 passed, 0 failed (of 45)' \
  '46 passed, 0 failed (of 46)' \
  '46e174169084318329b49f1c2109e210e7b8f743' \
  '47 passed, 0 failed (of 47)' \
  '48061f24a0510e4133a9fa0be51b0f7b30b8fc85' \
  '4b86a3d8df44' \
  '4e327b042aeb8387' \
  '4f36b0df0226ec09' \
  '544029f477a292da' \
  '5772145479' \
  '58b583ae7bd59f2f' \
  '58cdd3dc846b' \
  '58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb' \
  '5a8458a5697f' \
  '5a8458a5697f7ee5b1800864b9f49347c8cbe34e' \
  '60db49e9364c' \
  '6281e19019dbc94e' \
  '633e92de2308' \
  '65c09b0f213a' \
  '661da6c23e233c682f30c3de83b71ef46c8a5bbb' \
  '6b372a204a3ac911' \
  '6b836f0afab7c129747e8818626be9edd1975932' \
  '7333dd7d50c254f2' \
  '76958c117fe8' \
  '78324a8d8fa8' \
  '7c3010a18153' \
  '7f938694b60c' \
  '894ba4612b16' \
  '9373c53b94acf50e' \
  '9bb5e5e1272d' \
  'B4' \
  'B5' \
  'B6' \
  'Claude-written' \
  'GO: merge #1180, #1181, #1183, #1185, #1187, #1188, #1190, #1191, #1192, #1193, #1195, #1197 batch' \
  'KS-480' \
  'KS-501' \
  'KS-522' \
  'KS-721' \
  'KS-726' \
  'KS-978' \
  'PREFLIGHT INCOMPLETE' \
  'PROTOCOL-CLEAN' \
  'Refs KS-1011' \
  'Refs KS-1031' \
  'Refs KS-1033' \
  'Refs KS-1034' \
  'Refs KS-1040' \
  'Refs KS-1047' \
  'Refs KS-1081' \
  'Refs KS-1093' \
  'Refs KS-1097' \
  'Refs KS-1139' \
  'Refs KS-972' \
  'SKIPPED' \
  'a2c7a2b01a5170cb' \
  'ad86ffdbf504c250c1144f7d59ddcdba4966568d' \
  'ae04617ec3fa419a' \
  'attrib19' \
  'b2c0ac2d94387f9ce63c76ec437a465aca63a85f' \
  'b7dc03c142c9e65cd5112b5eee63c863bc368a93' \
  'bash -n' \
  'bbcc95cfc9f1' \
  'bde065b6e068' \
  'c998bd7ed21d' \
  'cd9b0f6c7b84' \
  'check_shared_relink' \
  'core.filemode' \
  'dc54e1f344372f81' \
  'deb7ddb99c799d50969f1c70720d3d0cc3004d34' \
  'e37a7f61a2bd5537' \
  'e673f5979922' \
  'e77bf0be28e1' \
  'ea44b2277e12' \
  'ea928563fe8bd663' \
  'eaa961172883' \
  'ec9d5d280132bbf3' \
  'eccdb71822da' \
  'ef76b4b6252a7499' \
  'f5fd1883cc7e' \
  'fa13f78e8a87769d82c51b070d165f24e677a3a3' \
  'fdf6d090392ceb31' \
  'fe70b038cc4c8b56' \
  'fe9cd46daa4a8e50ed37fca3f48fd23e6d05e44a' \
  'fixmodes19' \
  'ks-666' \
  'ks-754' \
  'ks-926' \
  'login_stub' \
  'measure19' \
  'merge19b' \
  'r16b' \
  'series19' \
  'skips are not a pass' \
  'stacklegs-2' \
  'targets19'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the READY capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
grep -qF 'MEASURE, not conclude' "$PROMPT_FILE" && grep -qF 'RULE WHETHER IT BLOCKS' "$PROMPT_FILE" || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS missing" >&2; exit 30; }
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s+", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in \
  'TIER AND ROUND' \
  'ASSIGN the tier from the files' \
  'STATE BOTH' \
  'round 1 of 2' \
  'SCRIPT BYTES exactly as declared' \
  'assert the mode at every head by `ls-tree`' \
  'TREES over `3bad652d1`' \
  'in >= 3 orders' \
  '0 overlap with Seat B 20th' \
  'CANONICAL-PATCH IDENTITY' \
  'Claude-written sections stated as such' \
  'CELLS: the bash suites' \
  'read, do not compose' \
  'TYPECHECK: n/a for bash' \
  'CENSUS v2' \
  'NEVER connect' \
  'LINEAR LINK HYGIENE' \
  'attachmentsForURL per PR exactly its own key(s)' \
  'subjects <= 92 chars ASCII' \
  'THE TWO-SEAT ARTEFACTS' \
  'CONFIRM it ran on every later push' \
  'THE SEAT'"'"'S OWN FINDINGS/SLIPS' \
  'CONFIRMED / REFUTED' \
  'INTERMITTENTS per PR (do not block)' \
  'RULE WHETHER IT BLOCKS' \
  'MERGE ADDENDUM' \
  'twelve lines VERBATIM in report.md' \
  '2/2/2/2/3/2/2/2/2/1/1/1' \
  'stays In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'READ THE WHOLE TEST FILE' \
  'NOT-TESTED first' \
  'CONTEXT RULE' \
  'at ctx 80' \
  'BASE_GO' \
  'END_TREE' \
  '## MERGE ADDENDUM' \
  'MEASURE, not conclude' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'node_modules PER ENTRY' \
  'never print a credential value' \
  'No memory maintenance' \
  'NOT-TESTED.written-first.md' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '[QA -> Wednesday] BATCH GATE #1180-#1197 (twelve PRs; tier 1 = #1180, #1181, #1183, #1185, #1187, #1188, #1190, #1191, #1192: Seat C 19th — nine bash_patch script PRs on the fleet gates + boot path; tier 2 = #1193, #1195, #1197 docs) —' \
  'fleet/briefs_staged/2026-09-22_raise_seatC_19.md' \
  'WEDNESDAY'"'"'S signed GO naming each head' \
  'Never enter any seat worktree' \
  '2026-09-22_seatC-19th' \
  '#1180 BEFORE #1181' \
  'alone blob by construction; mode 100755' \
  'mail_gate19C_ready.md'; do
  printf '%s' "$PROMPT_JOINED" | grep -qF -- "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
grep -qF -- '--pair-blob' "$PROMPT_FILE" && grep -qF -- "$PAIR_BLOB" "$PROMPT_FILE" && grep -qF -- 'alone blob' "$PROMPT_FILE" || { echo "REFUSING: the PAIR is not in the prompt" >&2; exit 35; }
grep -qF -- "WEDNESDAY'S signed GO naming each head" "$PROMPT_FILE" || { echo "REFUSING: merge authority" >&2; exit 26; }
grep -qF -- '## MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF -- 'ONE equality target PER PR FILE' "$PROMPT_FILE" && grep -qF -- 'KEY-FREE' "$PROMPT_FILE" || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] BATCH GATE #1180-#1197 (twelve PRs;' "$PROMPT_FILE" && grep -qF -- 'FROM coagent@agentmail.to' "$PROMPT_FILE" && grep -qF -- 'TWELVE lines, one per PR' "$PROMPT_FILE" || { echo "REFUSING: the verdict subject / sender / twelve lines" >&2; exit 23; }
grep -qF -- "$ALL_OVER_DEV" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" || { echo "REFUSING: the all-12 tree / develop not in full" >&2; exit 31; }
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  heads on origin (branch AND refs/pull/N/head):$HEADS_NOTE"
  echo "  compares (GitHub API), develop...head per PR (merge_base + ahead + behind + files):"
  printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  $DEV_NOTE"
  echo "  READY capture, prompt, QA project and repo all present; the prompt is not PARTIAL; opens with the thinking directive; names the brief path and the capture"
  echo "  prompt carries TIER 1 on the NINE and each PR tier (#1180 T1 #1181 T1 #1183 T1 #1185 T1 #1187 T1 #1188 T1 #1190 T1 #1191 T1 #1192 T1 #1193 T2 #1195 T2 #1197 T2); round 1 of 2"
  echo "  READY capture and prompt both name every pinned head in full and which ticket each PR is"
  echo "  READY capture and prompt BOTH carry the seat items (116 tokens); the prompt says MEASURE, not conclude, and RULE WHETHER IT BLOCKS"
  echo "  prompt carries Wednesday's twelve by-name items (59 keywords), the PAIR (--pair-blob + the pair blob in full + alone blob), the merge authority, the MERGE ADDENDUM rules, the verdict subject / sender / twelve lines, the all-12 tree and develop in full"
  [ -n "${QAB1180_CUR_DEV:-}" ] && echo "  (develop read from the QAB1180_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1180_BRIEF:-}${QAB1180_PROMPT:-}${QAB1180_HEAD_1197:-}${QAB1180_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
