#!/bin/bash
# launch_qa_secuura_ks1204_1035.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #1035 (KS-1204, Seat A)
# @ 4b1fb0621e58ff00bba096751130bc6e53df4714 — services/api-gateway: a connector allow-list that is not an array fails closed; documentType-over-type is pinned.
# POST /api/documents: a connector whose stored allowedDocumentTypes is present, not null and not an array (a string, an object, an empty string, a number, a
# boolean) is refused 403 FORBIDDEN on EVERY create, typed or untyped, before enforcement (Wednesday's receipt accepted the three veto defaults: 403 FORBIDDEN,
# empty string = configured-not-a-list, untyped refused). ONE commit on develop 732c13459: routes/verification.ts +11 -1, the ks1204 test +292 (9 cells).
# TIER 1: an AUTHORISATION decision on the connector create path; the source is the #1014 round-2 gate's N-2 (a STRING allow-list substring-matched) + N-3
# (no cell pinned documentType-over-type). A GO is NOT a merge authorisation: the merge waits for Kam's tap.
#
# THE SHAPE, as read 01:04-01:20 AEST 2026-09-18 (git ls-remote + the PR and compare APIs agree): the head's only parent 732c13459 is the merge-base; develop has
# moved to 3961c2add (#1033: Dev root package.json / package-lock.json (mysql2 only), audit baseline, originate package files), so compare develop...head =
# merge_base 732c13459, ahead 1, files 2 (asserted, exit 10; behind NOT asserted). Merged tree over 3961c2add = d21341805 (re-drafter clone, 0 conflicts).
#
# The develop pin is judged by CONTENT — PATH BLOBS — never by develop's SHA: (a) NINETEEN files by blob at the CURRENT develop — the PR two (routes/verification.ts
# 28fb58343, the ks1204 test ABSENT; at a #1035 blob -> exit 19 LANDED), and what the gate runs and reads: index.ts (mount order, body parsers, the /api/v1 rewrite),
# routes/admin.ts (the platform-settings writer), services/health.ts (the connector-info reader), services/redis.ts, services/enforcement.ts, middleware/auth.ts,
# middleware/contentType.ts, the ks1176 test, gateway package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json, shared utils/gracefulShutdown.ts, frontend
# admin pages/Settings.tsx (the probe transcribes its save), mcp-server tools/info.ts and package-generator.ts (readers), Dev eslint.config.mjs — any blob nobody
# pinned -> exit 18; (b) if develop moved past 732c13459, the compare pinned...develop REFUSES (exit 18) when the delta touches a GUARDED path —
# services/api-gateway/src/ and its package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json, packages/shared/src/, eslint.config.mjs, Settings.tsx, the two
# mcp-server readers — or the move cannot be judged. WHY these paths: they are the code the gate runs in-process (the real index.ts app, the create route, the
# admin writer, the info reader) and the readers it censuses; a develop merge elsewhere (other services, lockfiles, audit baselines) cannot change what the gate
# measures, so it must not refuse. DEV_CONTENT_ALLOWED is EMPTY. Open PRs #1034 (middleware/auth.ts), #575 / #649 / #1036 (api-gateway package.json), #923 (an
# api-gateway test), #995 (utils/trustHeaders.ts) and #922 (shared src) touch GUARDED paths: if one lands first this REFUSES by design — re-pin deliberately.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate R-6: a wholesale link can write through to the checkout .vite).
# exit 23: the prompt must carry the exact #1035 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY and the PRIOR REPORT (#1014 round 2, KS-1176: its N-2 + N-3 are this ticket; the QA agent has no
#          inbox), and the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition.
# QA1035_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA1035_VER_FILE (test fixture, --check only): a local file stands in for develop routes/verification.ts (its git blob) so the LANDED and GUARDED
# arms can be proven without a real develop commit.
# A launch with any QA1035_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1035/gen_launcher_1035.py from launch_qa_secuura_ks1215_1034.sh (asserted substitutions + pins re-read from the repo +
# residual guard + output controls + bash -n): same guard set and exit codes 2..25 (19 = LANDED), re-pointed at #1035 ROUND 1, no content-cleared blob.
#
# Usage: launch_qa_secuura_ks1204_1035.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1035_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1035-ks1204-tier1.md}"
PROMPT_FILE="${QA1035_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1035-ks1204-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-1204-a-string-alloweddocumenttypes-substring-matches-and-no-cell'
HEAD_SHA="${QA1035_HEAD:-4b1fb0621e58ff00bba096751130bc6e53df4714}"
MERGE_BASE='732c13459d76f5b05ade94bb91de7e47585b0e7d'   # the merge-base of the head with develop (#1031s squash) = the only parent of the one-commit head 4b1fb0621
DEVELOP_SHA='732c13459d76f5b05ade94bb91de7e47585b0e7d'   # the pin = the merge-base; develop was 3961c2add at draft close (moves judged by PATH BLOB and GUARDED paths, never by this SHA: git ls-remote 00:57:58 + 01:05:56; compare API 01:04:26 AEST 2026-09-18)
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks1204-1035-4b1fb0621-tier1-r1/'
PRIOR_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1176-1014r2-9ba0caf78-tier1-r2/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1035-ks1204-tier1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1035 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1035 = 732c13459 ahead 1 files 2 (behind 1 at draft close: develop 3961c2add; behind deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=1 files=2" ] || { echo "REFUSING: #1035 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=1 files=2'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): nineteen files by PATH BLOB at the CURRENT develop (no region judgement), then — if develop
# moved — the pinned...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="${QA1035_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
A = D + "services/api-gateway/"
VERTS = A + "src/routes/verification.ts"
DV = "develop"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  VERTS:                                                                ({"28fb5834308a502f5f7b806e3b49a77627601eff": DV}, {"f888e8cd0bd10c98a508542d75902ab122595157": "#1035 own"}),
  A + "src/__tests__/ks1204-a-non-array-allow-list-fails-closed-and-documenttype-wins.test.ts": ({"ABSENT": DV}, {"f1f9840edd15ba8cbb764f675f5c2fdeef228dc7": "#1035 own"}),
  A + "src/index.ts":                                                    ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": DV}, {}),
  A + "src/routes/admin.ts":                                             ({"f47dd6a655702ffbfc402ca920a33c4619d62c4b": DV}, {}),
  A + "src/services/health.ts":                                          ({"f43052734a10d0b891db11b49aa49b08f66c1ea8": DV}, {}),
  A + "src/services/redis.ts":                                           ({"47659ee9c9f06acf9ac64e09b2dc207113ba92ea": DV}, {}),
  A + "src/services/enforcement.ts":                                     ({"be466fbf444178bbb41293fb1d811957e55e1d2d": DV}, {}),
  A + "src/middleware/auth.ts":                                          ({"6e16683624b3c38a365ece44cccb4fdfac892c71": DV}, {}),
  A + "src/middleware/contentType.ts":                                   ({"5b5b3e7342d04451ea8a7dff0823fc5763122059": DV}, {}),
  A + "src/__tests__/ks1176-connector-key-level-ranks-as-none.test.ts":  ({"43cebf8d75376f5a40252c5096fd02747c4f0a9e": DV}, {}),
  A + "package.json":                                                    ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  A + "vitest.config.ts":                                                ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  A + "vitest.setup.ts":                                                 ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  A + "tsconfig.json":                                                   ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "packages/shared/src/utils/gracefulShutdown.ts":                   ({"5550416464de399e86f6c4041a3279962119af82": DV}, {}),
  D + "frontend/admin/src/pages/Settings.tsx":                           ({"e414630f25c49a954a41d75794a37da781804b3b": DV}, {}),
  D + "services/mcp-server/src/tools/info.ts":                           ({"c0f2268ca0aceeec2d89639bbead5bbc549fe859": DV}, {}),
  D + "services/mcp-server/src/package-generator.ts":                    ({"d040fff2213f40768905f42ce7fbb4250cf130e9": DV}, {}),
  D + "eslint.config.mjs":                                               ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
}
# No REGION judgement: every file is judged by exact blob (a develop move of verification.ts, admin.ts or health.ts refuses, exit 18).
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA1035_VER_FILE", "") if f == VERTS else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #1035 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (= the head merge-base, an ANCESTOR of the head: merged tree = the head tree cad39d37d4fd15b44ff2d095f810813662ae6208; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [A + "src/",
           A + "package.json",
           A + "vitest.config.ts",
           A + "vitest.setup.ts",
           A + "tsconfig.json",
           D + "packages/shared/src/",
           D + "eslint.config.mjs",
           D + "frontend/admin/src/pages/Settings.tsx",
           D + "services/mcp-server/src/tools/info.ts",
           D + "services/mcp-server/src/package-generator.ts"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: EMPTY. No lockfile is guarded: the gate names the vitest version it ran against develop-s lock. Re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 4b1fb0621 in its own clone, asserts the merged services/api-gateway, shared, frontend/admin and mcp-server subtrees equal the head, or re-runs the real-app census, the tamper table and the suites on the MERGED tree; names the merged-tree OID, re-drafter 3961c2add -> d21341805 (brief items 3, 4, 5, 6)"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — GUARDED hits %d — disjoint from the GUARDED list (services/api-gateway/src/ + its package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json, packages/shared/src/, eslint.config.mjs, frontend admin Settings.tsx, mcp-server tools/info.ts + package-generator.ts); %s" % (pinned, cur, c["ahead_by"], len(files), len(hits), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 1 GATE #1035 (KS-1204) 4b1fb0621' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact #1035 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR and the PRIOR REPORT $PRIOR_REPORT (#1014 round 2, KS-1176: its N-2 + N-3 are this ticket), or the prompt does not name NOT-TESTED.written-first.md — the QA agent has no inbox" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition — the merge seat equality targets and the In Progress hold ride on it" >&2; exit 25; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1035 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1035 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact #1035 verdict subject, coagent@ sender, wednesday-agent@ recipient"
  echo "  brief and prompt name the report directory and the #1014 round-2 PRIOR REPORT (KS-1176 N-2 + N-3); prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM and require CLOSED / STILL OPEN / NEW per finding"
  [ -n "${QA1035_CUR_DEV:-}" ] && echo "  (develop read from the QA1035_CUR_DEV test override, not ls-remote)"
  [ -n "${QA1035_VER_FILE:-}" ] && echo "  (develop api-gateway routes/verification.ts read from the QA1035_VER_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1035_BRIEF:-}${QA1035_PROMPT:-}${QA1035_HEAD:-}${QA1035_CUR_DEV:-}${QA1035_VER_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
