#!/bin/bash
# launch_qa_secuura_batch1182-1201.sh — cross-project QA agent, ONE BATCHED ROUND 1 gate over NINE Secuura/Blockchain PRs (Seat B 19th READY 1-3 +
# Seat B 20th READY 4-9, the mid-series hand-over): TIER 1 on the EIGHT PRs carrying PRODUCT / TOOLING bytes or an auth-adjacent surface (#1182
# #1184 #1186 originate; #1196 kyc; #1198 #1199 security — the ONE same-file PAIR services/security/src/index.ts, --pair-blob on #1199 after #1198;
# #1200 systemTest/performance tooling — the RULED (b) Claude-authored whitespace rewrap of the NEW test file, graded by the whitespace-stripped
# byte-stream instrument; #1201 the Claude-written test-only pin whose tamper sits on the ssrf guard), TIER 2 on #1194 (KS-1229 test-only cells).
# ELEVEN READYs (9 R16B rows + 2 Claude-written goldens) in nine PRs; 17 paths; +642/-13 (amended); ZERO overlap with Seat C 19th's partition.
# EVERY VALUE HERE IS THE SEAT MEASUREMENT RE-DERIVED BY THE DRAFTER, never adopted: heads by ls-remote (branch AND refs/pull/N/head), the per-PR
# trees / blobs / modes by ls-tree in a scratch clone FROM ORIGIN (never --shared from the checkout), the all-11 tree by REAL merge-tree chains in
# three orders (predict_batch_scratch_1.out), every BOTH-list token asserted present in the READY capture and the prompt.
# THE SHAPE: each head is ONE commit whose parent IS develop 3bad652d17cf111c1e2e1bed1ae7686894637487 (tree cd9b0f6c7b84); the compare per PR reads
# develop...head = merge_base 3bad652d1, ahead 1, BEHIND 0, files 2/2/2/1/2/4/2/2/1 (exit 10 — a develop move changes `behind` and REFUSES:
# re-pin deliberately — Seat C 19th's GO (gate19C) may land its merges first). ALL NINE over develop = 3df72c02d3250ca584c591fd89734d3391d99337 (the END
# STATE if every merge lands on 3bad652d1). The develop pin is judged by CONTENT too — the 17 target paths at the CURRENT develop (8 NEW test files
# judged ABSENT; 9 MODIFIED files by blob — any present head blob, or security/src/index.ts at the PAIR blob, -> exit 19 LANDED; any other change ->
# exit 18; a disjoint move (Seat C's merges) -> exit 17).
# exit 6:  any head is not at its branch AND at refs/pull/N/head on origin (the refusal names the PR).
# exit 7:  the prompt must carry TIER 1 on the EIGHT and each PR own tier line (#1182 T1 #1184 T1 #1186 T1 #1194 T2 #1196 T1 #1198 T1 #1199 T1 #1200 T1 #1201 T1).
# exit 8:  the prompt must open with the thinking directive and name the brief path + the READY capture.
# exit 10: the compare per PR (merge_base 3bad652d1, ahead 1, behind 0, files as pinned) — develop moving refuses here.
# exit 17/18/19: the develop pin judged by content (above).
# exit 20: the READY capture AND the prompt must name every pinned head in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. `--check` runs headless (it launches nothing).
# exit 23: the prompt must carry the exact batch verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient, NINE verdict lines.
# exit 25: the prompt must carry the MERGE ADDENDUM per PR with ONE equality target PER PR FILE, the `## MERGE ADDENDUM` heading, KEY-FREE SHIPS-WITH.
# exit 26: the prompt must name WEDNESDAY'S signed GO as each PR merge authority.
# exit 30: the READY capture AND the prompt must BOTH carry the seat items (the BOTH list below); the prompt must say MEASURE, not conclude and RULE WHETHER IT BLOCKS.
# exit 31: the prompt must name the all-11 tree and develop in full.
# exit 32: the READY capture AND the prompt must BOTH state which ticket each PR is (PR #1182 is KS-730. …).
# exit 33: the prompt must carry Wednesday's twelve by-name items by their keywords (the ladder below) and the standard closing.
# exit 34: a PARTIAL prompt (any `PENDING-PR-` token) refuses — --check and launch alike.
# exit 35: the prompt must carry the PAIR: `--pair-blob`, the pair blob 2ad45cd8e5552d5d52e48749406203d149967073 in full, and `alone blob`.
# exit 36: the prompt must carry the KS-1164 INSTRUMENT (`whitespace-stripped`, the amended blob b4edbe5b0d12 and the canonical 1d41e7033542, `git diff -w` named as NOT the instrument).
# QAB1182_CUR_DEV (test override, --check only): stands in for origin develop. QAB1182_HEAD_1201 (test override): stands in for #1201's pinned head.
# QAB1182_BRIEF / QAB1182_PROMPT (test overrides): stand in for the READY capture / the prompt. A launch with any QAB1182_* override set refuses (exit 16).
# Generated by gatesets/2026-09-22_gate19B_seatB/gen_launcher_gate19B.py at 2026-09-22T08:28:14Z.
# Usage: launch_qa_secuura_batch1182-1201.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
BRIEF="${QAB1182_BRIEF:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-22_gate19B_seatB/mail_gate19B_ready.md}"
PROMPT_FILE="${QAB1182_PROMPT:-/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/briefs/2026-09-22_secuura-batch1182-1201.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
PRS=(
  "1182|KS-730|refs/heads/feature/ks-730-security-71-inline-handlers-still-return-errmessage-verbatim-r16b-ingest500-1|8c413d78243a47d144f4049e6cd720a473d4dceb|2"
  "1184|KS-1028|refs/heads/feature/ks-1028-gate-f-1-major-a-step-12-throw-skips-the-user_erased-r16b-step12fanout-1|dd9ef92274366dd9975203d1376a87f63e7606a4|2"
  "1186|KS-1160|refs/heads/feature/ks-1160-originate-post-apiwebhooks-persists-the-raw-url-where-patch-r16b-postnormurl-1|8d3c5c9604fc07598bbb67ca2fcdfcead4859df1|2"
  "1194|KS-1229|refs/heads/feature/ks-1229-ks1213-cells-ten-tampers-stay-green-a-refused-issue-can-mint-r16b-loose-sideeffects-1|97d2e3fe493bb65afa14b768cafa21912e58c02b|1"
  "1196|KS-629|refs/heads/feature/ks-629-kyc-livenessvideo-is-accepted-by-spec-and-runtime-then-r16b-livenessrt-1|79a8955667fae3b34f2e6ab31b1dda35911a28f3|2"
  "1198|KS-974|refs/heads/feature/ks-974-published-bound-vs-runtime-bound-on-rate-limit-scope-check-r16b-checkkeycp-scopetrim-1|8ccfed7b64a76627bad51e2402575623d6b6d0e6|4"
  "1199|KS-976|refs/heads/feature/ks-976-rate-limit-refusals-name-the-wrong-field-400-says-key-r19-scope403-claude-1|a94180ce7b24a0654418479f0c4ec3db2a63340c|2"
  "1200|KS-1164|refs/heads/feature/ks-1164-gatereportts-writegatereport-overwrites-the-input-summary-r16b-reportpath-1|3a979effb886437ecc1276a547cc41aed830994e|2"
  "1201|KS-1179|refs/heads/feature/ks-1179-safeoutboundrequest-tests-no-cell-pins-dns-layer-r19-f2f3-claude-1|6e675cb815e984f9fa013f54ec4f214b552e56a2|1"
)
DEVELOP_SHA='3bad652d17cf111c1e2e1bed1ae7686894637487'
ALL_OVER_DEV='3df72c02d3250ca584c591fd89734d3391d99337'
PAIR_BLOB='2ad45cd8e5552d5d52e48749406203d149967073'
# path|develop blob or ABSENT|LANDED blobs (comma) — the content judgement of the develop pin
JUDGED=(
  "Blockchain/Dev/packages/shared/src/__tests__/ks932-timeout-bounds-dns.test.ts|5a2188f6f68d9784efc923fcf8f739ea47417c9c|4022d4ecd2e5d6eca2df7da6765da7d4c7169e01"
  "Blockchain/Dev/services/kyc/src/__tests__/ks629-kyc-livenessvideo-is-accepted-by-spec.test.ts|ABSENT|c845f8b93f8b31a1c30c11dd8879ae9d80f4b9a2"
  "Blockchain/Dev/services/kyc/src/index.ts|ff20c8a152120642e543dd14547af729338668a5|f473857c5a163c1bc7e5231ad33302d93a6391db"
  "Blockchain/Dev/services/originate/src/__tests__/ks1028-step12-throw-does-not-skip-fanout.test.ts|ABSENT|81ccc4535838aa7ca39ad5c7606e2edd81b18293"
  "Blockchain/Dev/services/originate/src/__tests__/ks1160-webhooks-post-persists-normalised-url.test.ts|ABSENT|90859d04ad1dea34f4760bd20d91c5b4c132662d"
  "Blockchain/Dev/services/originate/src/__tests__/ks1213-a-derived-writer-relabel-is-refused.test.ts|bbfcd0f98923ca986a5779d937a75398badc03d1|c881e7c5a17ab925ef69fa84d1afdba2ac21af0e"
  "Blockchain/Dev/services/originate/src/__tests__/ks730a-ingest-500-never-answers-err-message.test.ts|ABSENT|7bed8c23b331d2b0cb2b8c1e14b4f7e257f611cc"
  "Blockchain/Dev/services/originate/src/routes/systemErrors.ts|6b57d8d75f442c2b0511bd1cfe1863089af1d610|baba06edeb88009f63c0e3d6d69c6794183e2150"
  "Blockchain/Dev/services/originate/src/routes/webhooks.ts|c88eb97db5a2466e9456506c2c1bf5094e3c5d4e|eb4efed613817d3603fa56a3db0f3929830bbd02"
  "Blockchain/Dev/services/originate/src/services/gdprService.ts|4d138883c70e651a24d4d9a302df6ec21e2eac33|7d615f33bb9be45ed9bd877568c4b957654227e2"
  "Blockchain/Dev/services/security/src/__tests__/ks974-check-key-bound-code-points.test.ts|ABSENT|67f14e73428a82a6f1f116863d72e87456e32227"
  "Blockchain/Dev/services/security/src/__tests__/ks974-published-bound-vs-runtime-bound-on.test.ts|ABSENT|a0f1ae176918ccd0a91d1e66f86841c125a2f6db"
  "Blockchain/Dev/services/security/src/__tests__/ks976b-rate-limit-403-says-which-scope-claim-failed.test.ts|ABSENT|e508fc97af256ac5704eccb68e1fd0bdf8e777a4"
  "Blockchain/Dev/services/security/src/index.ts|0903ce4380f219765ac63f5f9399d1bf0b4f230a|2ad45cd8e5552d5d52e48749406203d149967073,5bf6fb62dba89b4a53fec4e8368848e4b6e40c63,7bdaa9cad257c48c32cf611c1f4fd15d6290ce2d"
  "Blockchain/Dev/services/security/src/requestSchemas.ts|4973571a95119956d71ce525de678e2a3ea066ab|b8c63d3f0ae5ab10f0e63194982d4c3e3fe907d7"
  "systemTest/performance/gate/report.ts|21d2dbe7d20d27d3e9f4ab1edbc3dd537814ffc7|0a910cd855c32a877d0071bdb8880d6c5f7cb460"
  "systemTest/performance/tests/unit/gate/ks1164-write-gate-report-never-overwrites-its-input.test.ts|ABSENT|b4edbe5b0d12620ddcaa7e17cc9de1831b6c807e"
)
[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief (READY capture) missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }
grep -qF 'PENDING-PR-' "$PROMPT_FILE" && { echo "REFUSING: the prompt is PARTIAL (a PENDING-PR- token) — a partial gate is not a gate" >&2; exit 34; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF 'fleet/briefs_staged/2026-09-22_raise_seatB_19.md' "$PROMPT_FILE" && grep -qF 'mail_gate19B_ready.md' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the brief path and the READY capture" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  [ "$_n" = "1201" ] && [ -n "${QAB1182_HEAD_1201:-}" ] && _h="$QAB1182_HEAD_1201"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1182_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
base = os.environ["CUR_DEV"]
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf = pr.split("|")
    try:
        c = get(api + base + "..." + h); print("%s %s ahead=%d behind=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
if [ "$CUR_DEV" != "$DEVELOP_SHA" ]; then
  JUDGE="$(
    set -a; . "$SECUURA_ENV"; set +a
    JUDGED_FLAT="$(printf '%s\n' "${JUDGED[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); base = "https://api.github.com/repos/Secuura/Distributed_Secuura/contents/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
worst = "DISJOINT"
for row in os.environ["JUDGED_FLAT"].splitlines():
    path, dev, landed = row.split("|")
    try: cur = get(base + path + "?ref=" + os.environ["CUR_DEV"])["sha"]
    except Exception: cur = "ABSENT"
    if cur == dev: continue
    if cur in landed.split(","): print("LANDED", path, cur); worst = "LANDED"
    else: print("CHANGED", path, dev, "->", cur); worst = "CHANGED" if worst != "LANDED" else worst
print("VERDICT", worst)
PY
  )"
  printf '%s\n' "$JUDGE" >&2
  case "$JUDGE" in
    *"VERDICT LANDED"*) echo "REFUSING: a target already LANDED on develop $CUR_DEV (the pin is $DEVELOP_SHA) — a merge happened; re-pin" >&2; exit 19;;
    *"VERDICT CHANGED"*) echo "REFUSING: develop $CUR_DEV (the pin is $DEVELOP_SHA) changed a target path — re-predict" >&2; exit 18;;
    *) echo "REFUSING: develop $CUR_DEV != the pin $DEVELOP_SHA (a disjoint move — Seat C 19th's merges (gate19C)?) — re-predict every tree and re-pin the launcher deliberately" >&2; exit 17;;
  esac
fi
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  printf '%s\n' "$COMPARE" | grep -q "^${_n} ${DEVELOP_SHA} ahead=1 behind=0 files=${_f}\$" || _bad=1
done
if [ "$_bad" = 1 ]; then
  echo "REFUSING: a compare is not merge_base $DEVELOP_SHA / ahead 1 / behind 0 / files as pinned (develop moved, a head moved, or the API failed):" >&2
  printf '%s\n' "$COMPARE" >&2
  exit 10
fi
DEV_NOTE="origin develop $CUR_DEV == the pin (the heads' parent); 9 compares merge_base == pin, ahead 1, behind 0, files as pinned"
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the READY capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
done
grep -qF -- 'PR #1182 is KS-730.' "$PROMPT_FILE" && grep -qF -- 'PR #1198 is KS-974.' "$PROMPT_FILE" && grep -qF -- 'PR #1201 is KS-1179.' "$PROMPT_FILE" && grep -F '#1182' "$BRIEF" | grep -qF 'KS-730' && grep -F '#1201' "$BRIEF" | grep -qF 'KS-1179' \
  || { echo "REFUSING: the READY capture and the prompt do not BOTH state which ticket each PR is" >&2; exit 32; }
PROMPT_JOINED0="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in '#1182 T1' '#1184 T1' '#1186 T1' '#1194 T2' '#1196 T1' '#1198 T1' '#1199 T1' '#1200 T1' '#1201 T1'; do grep -qF -- "$_w" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '$_w'" >&2; exit 7; }; done
printf '%s' "$PROMPT_JOINED0" | grep -qF -- 'TIER 1 on the EIGHT' && grep -qF -- 'round 1 of 2' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry TIER 1 on the EIGHT / round 1 of 2" >&2; exit 7; }
for _w in \
  '(2'"'"')' \
  '+639/-13' \
  '+642/-13' \
  '--pair-blob' \
  '.push-lock-19' \
  '04de3585256bb3ef' \
  '06:14:10Z' \
  '0a910cd855c3' \
  '0d4795bd5f4dea68' \
  '12/15' \
  '144436f251750687' \
  '18499832' \
  '19098d293fab210b' \
  '1b38f41e886ad3dc' \
  '1cc0132e48a8f1fd' \
  '1d41e7033542' \
  '2-prime' \
  '288f56140ea44bcd' \
  '2a91afd2029e' \
  '2ad45cd8e555' \
  '2ad45cd8e5552d5d52e48749406203d149967073' \
  '34728affba20' \
  '39f91fe1ad38b434' \
  '3a979effb886437ecc1276a547cc41aed830994e' \
  '3bad652d17cf111c1e2e1bed1ae7686894637487' \
  '3c3f262105485a07' \
  '3d51eff35b166ab6' \
  '3df72c02d325' \
  '3df72c02d3250ca584c591fd89734d3391d99337' \
  '4022d4ecd2e5' \
  '45 passed, 0 failed (of 45)' \
  '5bf6fb62dba8' \
  '5ffcdc6799894415' \
  '64de96836e46' \
  '67f14e73428a' \
  '6e675cb815e984f9fa013f54ec4f214b552e56a2' \
  '773d42c5e28e4642' \
  '776f3deeed4f4f7a' \
  '79a8955667fae3b34f2e6ab31b1dda35911a28f3' \
  '7bdaa9cad257' \
  '7bed8c23b331' \
  '7d615f33bb9b' \
  '81ccc4535838' \
  '8c413d78243a47d144f4049e6cd720a473d4dceb' \
  '8ccfed7b64a76627bad51e2402575623d6b6d0e6' \
  '8d3c5c9604fc07598bbb67ca2fcdfcead4859df1' \
  '90859d04ad1d' \
  '97d2e3fe493bb65afa14b768cafa21912e58c02b' \
  'Claude-written' \
  'GO: merge #1182, #1184, #1186, #1194, #1196, #1198, #1199, #1200, #1201 batch' \
  'GROUPING' \
  'In Progress' \
  'KS-1093' \
  'KS-480' \
  'KS-501' \
  'KS-522' \
  'KS-721' \
  'KS-726' \
  'KS-727' \
  'KS-978' \
  'PREFLIGHT INCOMPLETE' \
  'PROTOCOL-CLEAN' \
  'RED-FIRST' \
  'Refs KS-1028' \
  'Refs KS-1160' \
  'Refs KS-1164' \
  'Refs KS-1179' \
  'Refs KS-1229' \
  'Refs KS-629' \
  'Refs KS-730' \
  'Refs KS-974' \
  'Refs KS-976' \
  'SKIPPED' \
  'STOP-class 0' \
  'a0f1ae176918' \
  'a94180ce7b24a0654418479f0c4ec3db2a63340c' \
  'aa3d156ce41fd5ff' \
  'amend1164_19' \
  'amend_tree_8' \
  'anchoring:4005' \
  'b4edbe5b0d12' \
  'b5c8de533eba7a72' \
  'b672697ba64ea08d' \
  'b8c63d3f0ae5' \
  'baba06edeb88' \
  'batch11amend_19' \
  'c845f8b93f8b' \
  'c881e7c5a17a' \
  'cat(section_1.diff, section_2.diff) == patch.diff: True' \
  'cd9b0f6c7b84' \
  'commits.tsv' \
  'contributes' \
  'control CAUGHT' \
  'd309bb90f69f' \
  'd64e15b98' \
  'db.retry.test.ts' \
  'dd9ef92274366dd9975203d1376a87f63e7606a4' \
  'e072e663c9ee3de8' \
  'e508fc97af25' \
  'eb4efed61381' \
  'ecdcf272778d341c' \
  'f473857c5a16' \
  'ff75d1d2329d1fb9' \
  'format-gate' \
  'git diff -w' \
  'go19.sh' \
  'hold_state20' \
  'ks-754' \
  'ks1213' \
  'login_stub' \
  'my_files19' \
  'netlog.cjs' \
  'octopus' \
  'postmerge19' \
  'r16b' \
  'ready_build19' \
  'runs/2026-09-22_feed11-drafter-precheck/SCOPE403' \
  'runs/2026-09-22_feed7-drafter-precheck/1179F2F3-R16B' \
  'series19' \
  'skips are not a pass' \
  'ssrf-guard' \
  'stubs=4' \
  'targets19' \
  'typecheck_pre19' \
  'whitespace-stripped' \
  'zero :5432'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the READY capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
grep -qF 'MEASURE, not conclude' "$PROMPT_FILE" && grep -qF 'RULE WHETHER IT BLOCKS' "$PROMPT_FILE" || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS missing" >&2; exit 30; }
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s+", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in \
  'TIER AND ROUND' \
  'ASSIGN the tier from the files' \
  'STATE BOTH' \
  'round 1 of 2' \
  'PRODUCT vs TEST-FILE-ONLY exactly as each READY declares' \
  'code_patch RED/GREEN protocol' \
  'TREES over `3bad652d1`' \
  'in >= 3 orders' \
  '0 overlap with Seat C 19th'"'"'s 21 paths' \
  'CANONICAL-PATCH IDENTITY' \
  'stated as such' \
  'CELLS per lane' \
  'read, do not compose' \
  'PER-FILE TYPECHECK DELTA 0' \
  'CENSUS v2' \
  'NEVER connect' \
  'LINEAR LINK HYGIENE' \
  'attachmentsForURL per PR exactly its own key' \
  'subjects <= 92 chars ASCII' \
  'THE TWO-SEAT ARTEFACTS' \
  'F-GUARD' \
  'THE SEATS'"'"' OWN FINDINGS/SLIPS' \
  'CONFIRMED / REFUTED' \
  'INTERMITTENTS per PR (do not block)' \
  'RULE WHETHER IT BLOCKS' \
  'MERGE ADDENDUM' \
  'nine lines VERBATIM in report.md' \
  '2/2/2/1/2/4/2/2/1' \
  'stays In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'READ THE WHOLE TEST FILE' \
  'NOT-TESTED first' \
  'CONTEXT RULE' \
  'at ctx 80' \
  'BASE_GO' \
  'END_TREE' \
  '## MERGE ADDENDUM' \
  'MEASURE, not conclude' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'node_modules PER ENTRY' \
  'never print a credential value' \
  'No memory maintenance' \
  'NOT-TESTED.written-first.md' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '[QA -> Wednesday] BATCH GATE #1182-#1201 (nine PRs; tier 1 = #1182, #1184, #1186, #1196, #1198, #1199, #1200, #1201: Seat B 19th/20th — six product/tooling code_patch rows incl. the security index.ts pair + two Claude-written + the KS-1164 rewrap; tier 2 = #1194 test-only) —' \
  'fleet/briefs_staged/2026-09-22_raise_seatB_19.md' \
  '2026-09-22_raise_seatB_20.md' \
  'WEDNESDAY'"'"'S signed GO naming each head' \
  'Never enter any seat worktree' \
  '2026-09-22_seatB-19th' \
  '2026-09-22_seatB-20th' \
  '#1198 BEFORE #1199' \
  'alone blob by construction; mode 100644' \
  'mail_gate19B_ready.md' \
  'if gate19C'"'"'s GO lands first' \
  'the BASE moves' \
  'WHITESPACE-STRIPPED BYTE-STREAM EQUALITY' \
  'State which instrument YOU used' \
  'HANDOVER-seatB-19th-successor-2026-09-22.md' \
  'every head unchanged across the hand-over' \
  'foreign-second-key refusal' \
  'graded, not a STOP by itself' \
  'the merging seat re-predicts' \
  'Datasec files and mail are out of scope entirely'; do
  printf '%s' "$PROMPT_JOINED" | grep -qF -- "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
grep -qF -- '--pair-blob' "$PROMPT_FILE" && grep -qF -- "$PAIR_BLOB" "$PROMPT_FILE" && grep -qF -- 'alone blob' "$PROMPT_FILE" || { echo "REFUSING: the PAIR is not in the prompt" >&2; exit 35; }
grep -qF -- 'whitespace-stripped' "$PROMPT_FILE" && grep -qF -- 'b4edbe5b0d12' "$PROMPT_FILE" && grep -qF -- '1d41e7033542' "$PROMPT_FILE" && grep -qF -- 'git diff -w' "$PROMPT_FILE" && grep -qF -- 'NOT the instrument' "$PROMPT_FILE" || { echo "REFUSING: the KS-1164 instrument is not in the prompt" >&2; exit 36; }
grep -qF -- "WEDNESDAY'S signed GO naming each head" "$PROMPT_FILE" || { echo "REFUSING: merge authority" >&2; exit 26; }
grep -qF -- '## MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF -- 'ONE equality target PER PR FILE' "$PROMPT_FILE" && grep -qF -- 'KEY-FREE' "$PROMPT_FILE" || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] BATCH GATE #1182-#1201 (nine PRs;' "$PROMPT_FILE" && grep -qF -- 'FROM coagent@agentmail.to' "$PROMPT_FILE" && grep -qF -- 'NINE lines, one per PR' "$PROMPT_FILE" || { echo "REFUSING: the verdict subject / sender / nine lines" >&2; exit 23; }
grep -qF -- "$ALL_OVER_DEV" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" || { echo "REFUSING: the all-11 tree / develop not in full" >&2; exit 31; }
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  heads on origin (branch AND refs/pull/N/head):$HEADS_NOTE"
  echo "  compares (GitHub API), develop...head per PR (merge_base + ahead + behind + files):"
  printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  $DEV_NOTE"
  echo "  READY capture, prompt, QA project and repo all present; the prompt is not PARTIAL; opens with the thinking directive; names the brief path and the capture"
  echo "  prompt carries TIER 1 on the EIGHT and each PR tier (#1182 T1 #1184 T1 #1186 T1 #1194 T2 #1196 T1 #1198 T1 #1199 T1 #1200 T1 #1201 T1); round 1 of 2"
  echo "  READY capture and prompt both name every pinned head in full and which ticket each PR is"
  echo "  READY capture and prompt BOTH carry the seat items (126 tokens); the prompt says MEASURE, not conclude, and RULE WHETHER IT BLOCKS"
  echo "  prompt carries Wednesday's twelve by-name items (71 keywords), the KS-1164 instrument, the PAIR (--pair-blob + the pair blob in full + alone blob), the merge authority, the MERGE ADDENDUM rules, the verdict subject / sender / nine lines, the all-11 tree and develop in full"
  [ -n "${QAB1182_CUR_DEV:-}" ] && echo "  (develop read from the QAB1182_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1182_BRIEF:-}${QAB1182_PROMPT:-}${QAB1182_HEAD_1201:-}${QAB1182_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
