#!/bin/bash
# launch_qa_secuura_922r2.sh — cross-project QA agent, ONE TIER 2 (through code) ROUND 2 DELTA gate over Secuura/Blockchain PR #922 (KS-679)
# DELTA 8664826e5..30c773ee8 — a ONE-COMMIT FAST-FORWARD (proved by the generator): "KS-679 round 2: bound the E7 <prefix>_<uuid> exemption to the minted
# form". Three files: contract.mjs (the round-1 /^[a-z]+_<uuid>$/i BENIGN_SHAPES entry -> PREFIXED_UUID_RE: 2-12 lower-case letters, lower-case v4 uuid
# with the RFC variant, anchored, no /i, secret-named prefixes refused), the ks256 test (36 -> 80 cells), fixtures.ts (comment only). Head tree 7aa549d70.
# Round 1 at 8664826e5 = GO WITH FINDINGS (F1-F8); this gate grades the fix delta and the merged tree, not the unchanged diff.
# TIER 2 DELTA: a test file, a CI guard regex and a comment; no route, schema, handler or mint path moves.
# MERGE AUTHORITY: #922 does NOT merge on WEDNESDAY'S signed GO alone — Peter's 09-09 "not approving yet" is open; Kam rules on merging over it (exit 26).
#
# THE SHAPE, re-read live 13:00:24-13:02:42 AEST 2026-09-18: head 30c773ee8 on origin (refs/pull/922/head and the branch agree). DEVELOP MOVED since
# round 1: a105cd32b -> 207716440 (#1037 KS-1101, api-gateway + frontend only). compare develop...head = merge_base f6669623c, diverged, ahead 5, files
# 5, behind 2 (ahead and files asserted, exit 10). 0 overlap; the read-only merge-tree of 30c773ee8 against 207716440 is CLEAN — merged tree
# a1b4b6536d1d60fb2defca2886d36c9b9d0ec80e, 0 conflicted paths. The checkout's local branch ref is stale at 2b5075e9f: the head is pinned from ORIGIN only.
#
# The develop pin is judged by CONTENT — the same EIGHTEEN paths as round 1, blobs re-read at 207716440 (unchanged: #1037 touched none). A develop blob
# equal to EITHER round's #922 blob -> exit 19 LANDED; any blob nobody pinned -> exit 18; a develop move touching a GUARDED path -> exit 18.
#
# SOURCE = gatesets/2026-09-18_gate922r2/mail_922r2_ready.md, the seat's READY mail captured verbatim by message id from wednesday-agent@ (03:02:05Z).
#
# exit 7:  the prompt must name TIER 2 and carry no 'TIER 1 ROUND' / 'TIER 1 GATE' line.
# exit 15: the prompt must name ROUND 2 and the DELTA range 8664826e5..30c773ee8.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate R-6: a wholesale link can write through to the checkout .vite).
# exit 23: the prompt must carry the exact #922 round-2 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: the prompt must name the REPORT DIRECTORY, the PRIOR REPORT (round 1 of this PR) and NOT-TESTED.written-first.md.
# exit 25: the prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition.
# exit 26: the prompt must say the merge authority is NOT WEDNESDAY'S signed GO alone, name Kam and Peter, and must NOT carry round 1's
#          "... and on nothing else" signed-GO sentence.
# exit 27: the READY mail AND the prompt must BOTH carry the seat's own words: '12/15 legs ran, 3 SKIPPED' (not a pass), 'key_ is REFUSED' (a decision
#          the gate must verify) and "Peter's review is still open".
# exit 28: the prompt must forbid entering BOTH worktrees that hold this branch.
# QA922R2_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA922R2_CONTRACT_FILE (test fixture, --check only): a local file stands in for develop scripts/spec-examples/check/contract.mjs (its git blob).
# A launch with any QA922R2_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-18_gate922r2/gen_launcher_922r2.py from launch_qa_secuura_922.sh (asserted substitutions + pins re-read + a proved
# fast-forward + a re-derived merged tree + residual guard + output controls + bash -n).
#
# Usage: launch_qa_secuura_922r2.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..28 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA922R2_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate922r2/mail_922r2_ready.md}"
PROMPT_FILE="${QA922R2_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-18_secuura-922r2-tier2-delta.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/kamilkreiser/ks-679-anchor-id-format-false'   # read on ORIGIN only: the checkout's local ref of this name is stale at 2b5075e9f
HEAD_SHA="${QA922R2_HEAD:-30c773ee8f869a7530a9c17521ba442d641aa757}"
MERGE_BASE='f6669623ccae5ab445be6e0e73fb4f19ae2c89d1'   # the merge-base of the head with develop (unchanged from round 1; the delta is a fast-forward)
DEVELOP_SHA='207716440e2a6282b90ed2a118614d9cf98bee1e'   # the pin = develop RE-READ at drafting, after #1037 landed (NOT the merge-base f6669623c; moves judged by PATH BLOB and GUARDED paths: git ls-remote 13:00:24 AEST 2026-09-18)
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks679-922-30c773ee8-tier2-r2/'
PRIOR_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks679-922-8664826e5-tier2-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate922r2/mail_922r2_ready.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #922 round 2 — $HEAD_SHA is not at $BRANCH on origin — the head moved; a verdict is valid ONLY at its head" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#922 = f6669623c ahead 5 files 5 (behind 2: develop moved to a105cd32b then 207716440; behind deliberately NOT asserted). Compare API 03:02:42Z 2026-09-18.
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=5 files=5" ] || { echo "REFUSING: #922 develop...head reads '$COMPARE', the gateset pins '$MERGE_BASE ahead=5 files=5'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): eighteen files by PATH BLOB at the CURRENT develop (no region judgement), then — if develop
# moved — the pinned...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="${QA922R2_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
A = D + "packages/shared/"
X = D + "scripts/spec-examples/"
CONTRACT = X + "check/contract.mjs"
DV = "develop"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  D + "docs/openapi/secuura-api.yaml":                               ({"122d3a2f84cf77bf2b7e2dc51489a0d5f823db1f": DV}, {"16ac8aa78463849864fa6285e20c9946c027fb7b": "#922 own"}),
  A + "src/__tests__/ks256-spec-example-contract.test.ts":           ({"adbe91dfb0f10752057cceec647b727edb186621": DV}, {"4ef040f6f2fbbe6d73a76ff860caf71ac0bbe619": "#922 r2 own", "72533d3b01a4941578b1f777f0def3f9ec9ea6f0": "#922 r1 own"}),
  A + "src/openapi/examples/fixtures.ts":                            ({"ca5d5eae163f492c6703e0017610ea7ece7b9583": DV}, {"4416d7a586b1398793e1c15374d9cf45c318d832": "#922 r2 own", "b54d26929c564d9cd4e2e2f27da12df6d6d85325": "#922 r1 own"}),
  CONTRACT:                                                          ({"43a9c5dea27fc67bf0efc96489a1889833e2cbfd": DV}, {"07d4e9ab6b2879e08acfd587c4575bfaac1d1071": "#922 r2 own", "db726db299f738e2bf6790b3612d917b4d1eb9fc": "#922 r1 own"}),
  D + "services/anchoring/src/anchoring.openapi.ts":                 ({"49b8b38da7764e071711ded751fa006ae21e808d": DV}, {"29c089bb0abcd65d42fe8fca2d6beaff0368fa98": "#922 own"}),
  X + "check-spec-examples.mjs":                                     ({"e9c14a4dedf103850dc1c93fb1c5c67b8489b2a3": DV}, {}),
  X + "check/rules-example.mjs":                                     ({"5d1e7ecaef021de85a12121af94871d86547dfcf": DV}, {}),
  X + "check/rules-global.mjs":                                      ({"f1b447b6d913b8700a47a2a1fff86e5fa18195e1": DV}, {}),
  X + "check/allowlist.mjs":                                         ({"a712f3c61d7ce570c709002ca0e217c8078af8c3": DV}, {}),
  X + "check/collect.mjs":                                           ({"a2da5a4dab146a70818a244033a4032fbd6ec3a6": DV}, {}),
  X + "spec-example-allowlist.json":                                 ({"32bacbc4aa2c8764cc387c4d86919c2f1b08c223": DV}, {}),
  D + "scripts/generate-openapi.ts":                                 ({"e84acdc9e1be073751fcd6a8bb95504e23688019": DV}, {}),
  A + "package.json":                                                ({"3957692311221fbe87c4ab19447de8cec44aa19a": DV}, {}),
  A + "vitest.config.ts":                                            ({"2a226c0068faa65538cda8d43d03bb9bee2944f1": DV}, {}),
  A + "tsconfig.json":                                               ({"1fd016cc28803cc8f36cc84db4628941a2af9c50": DV}, {}),
  D + "services/anchoring/src/index.ts":                             ({"da4abd43292186da45c1533017fe042fa512bd43": DV}, {}),
  D + "package.json":                                                ({"773443a9faa0a2eb7caf01c313b880fbe3251922": DV}, {}),
  D + "eslint.config.mjs":                                           ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
}
# No REGION judgement: every file is judged by exact blob (a develop move of any judged file refuses, exit 18; a #922 blob, exit 19).
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA922R2_CONTRACT_FILE", "") if f == CONTRACT else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #922 has landed; this gateset is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (#1037 KS-1101, api-gateway and frontend only, 0 #922 files, NOT an ancestor of the head: merged tree 30c773ee8 x 207716440 = a1b4b6536d1d60fb2defca2886d36c9b9d0ec80e, 0 conflicts, drafter merge-tree 03:00:36Z; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [A + "src/",
           A + "package.json",
           A + "vitest.config.ts",
           A + "tsconfig.json",
           X,
           D + "scripts/generate-openapi.ts",
           D + "docs/openapi/",
           D + "services/anchoring/src/",
           D + "package.json",
           D + "eslint.config.mjs"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: EMPTY. No lockfile is guarded: the gate names the vitest version it ran against develops lock. Re-pin deliberately.
# A pending PR that rewrites packages/shared/package.json would refuse here if it lands first. That is by design: re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 30c773ee8 in its own clone, asserts the merged packages/shared/src, scripts/spec-examples, docs/openapi and services/anchoring/src subtrees equal the head, or re-runs the tamper table, the guard verdict diff and the suites on the MERGED tree; names the merged-tree OID, drafter 207716440 -> a1b4b6536 (prompt items 1, 2, 7)"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — GUARDED hits %d — disjoint from the GUARDED list (packages/shared/src/ + its package.json / vitest.config.ts / tsconfig.json, scripts/spec-examples/, scripts/generate-openapi.ts, docs/openapi/, services/anchoring/src/, the Dev package.json, eslint.config.mjs); %s" % (pinned, cur, c["ahead_by"], len(files), len(hits), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 2' "$PROMPT_FILE" && ! grep -qE 'TIER 1 (ROUND|GATE)' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not name TIER 2, or still carries a TIER 1 ROUND / GATE line" >&2; exit 7; }
grep -q 'ROUND 2' "$PROMPT_FILE" && grep -qF 'DELTA 8664826e5..30c773ee8' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not name ROUND 2 and the DELTA 8664826e5..30c773ee8 range — a delta gate that does not name its delta regates the whole PR" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the seat's READY mail capture path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: the READY mail or the prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 2 DELTA GATE #922 (KS-679) 30c773ee8' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact #922 round-2 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not name the report directory $REPORT_DIR, the PRIOR REPORT $PRIOR_REPORT (round 1 of this PR) and NOT-TESTED.written-first.md" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition" >&2; exit 25; }
grep -qiF "NOT WEDNESDAY'S signed GO alone" "$PROMPT_FILE" && grep -qF 'Kam' "$PROMPT_FILE" && grep -qF 'Peter' "$PROMPT_FILE" && ! grep -qiF 'and on nothing else' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not say #922's merge authority is NOT WEDNESDAY'S signed GO alone (Kam rules on merging over Peter's open review), or still carries round 1's signed-GO-and-nothing-else sentence" >&2; exit 26; }
grep -qF '12/15 legs ran, 3 SKIPPED' "$PROMPT_FILE" && grep -qF 'key_ is REFUSED' "$PROMPT_FILE" && grep -qF "Peter's review is still open" "$PROMPT_FILE" \
  && grep -qF '12/15 legs ran, 3 SKIPPED' "$BRIEF" && grep -qF 'key_ is REFUSED' "$BRIEF" && grep -qF "Peter's review is still open" "$BRIEF" \
  || { echo "REFUSING: the READY mail and the prompt do not BOTH carry the seat's own words: 12/15 legs ran, 3 SKIPPED / key_ is REFUSED / Peter's review is still open" >&2; exit 27; }
grep -qF 'quarantine/2026-09-15-s233/worktree-ks679' "$PROMPT_FILE" && grep -qF 'worktrees/s-a9-ks679' "$PROMPT_FILE" && grep -qi 'DO NOT ENTER EITHER WORKTREE' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid entering BOTH worktrees that hold this branch (quarantine/2026-09-15-s233/worktree-ks679 and worktrees/s-a9-ks679)" >&2; exit 28; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #922 round 2 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#922 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  READY mail, prompt, QA project and repo all present"
  echo "  prompt names TIER 2 (no TIER 1 ROUND / GATE line), ROUND 2 and the DELTA 8664826e5..30c773ee8"
  echo "  prompt opens with the thinking directive and names the READY mail capture"
  echo "  READY mail and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact #922 round-2 verdict subject, coagent@ sender, wednesday-agent@ recipient"
  echo "  prompt names the report directory, the round-1 PRIOR REPORT and NOT-TESTED.written-first.md"
  echo "  prompt carries the MERGE ADDENDUM and requires CLOSED / STILL OPEN / NEW per finding"
  echo "  prompt says the merge authority is NOT WEDNESDAY'S signed GO alone: Kam rules on merging over Peter's open review"
  echo "  READY mail and prompt BOTH carry: 12/15 legs ran, 3 SKIPPED / key_ is REFUSED / Peter's review is still open"
  echo "  prompt forbids entering both worktrees (the quarantined worktree-ks679 and seat A's s-a9-ks679)"
  [ -n "${QA922R2_CUR_DEV:-}" ] && echo "  (develop read from the QA922R2_CUR_DEV test override, not ls-remote)"
  [ -n "${QA922R2_CONTRACT_FILE:-}" ] && echo "  (develop scripts/spec-examples/check/contract.mjs read from the QA922R2_CONTRACT_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA922R2_BRIEF:-}${QA922R2_PROMPT:-}${QA922R2_HEAD:-}${QA922R2_CUR_DEV:-}${QA922R2_CONTRACT_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
