#!/bin/bash
# launch_qa_secuura_ks763_1033.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #1033
# (KS-763, Seat B, PR-7: mysql2 override to 3.23.1 against prisma's exact pin "3.15.3"; GHSA-rgwj-5xj2-c3m3 moderate + GHSA-3f6p-5ww8-9rcr high)
# @ 2cab54988b4e7b71d403576719f5fd80e470fa92 — TWO commits: 9fd3cb924 (2 manifests, 2 locks, 2 baseline rows removed, 31 -> 29) and 2cab54988
# (a merge of develop bb848b828 = #1026 + #1028 + #1030). 5 files vs develop: Blockchain/Dev/package.json + package-lock.json,
# services/originate/package.json + package-lock.json, scripts/audit/audit-baseline.json. TIER 1 because mysql2 ships in the originate runtime image.
#
# THE SHAPE, as read 22:46-23:02 AEST 2026-09-17 (git ls-remote + the PR and compare APIs): head parents 9fd3cb924 + bb848b828; origin develop
# 27e53ec3a (#1029, one api-gateway test file — 0 of the 5). compare develop...head = merge_base bb848b828, status diverged, ahead 2, behind 1,
# files 5. Asserted: merge_base + ahead + files (exit 10); behind is NOT asserted.
#
# THE DEVELOP ARM IS JUDGED BY PATH BLOBS, NEVER BY DEVELOP'S SHA (develop moves often). GUARDED PATHS, each read from its parent directory's
# GitHub contents listing at the CURRENT develop (5 listings):
#   (a) the 4 non-audit PR paths: Blockchain/Dev/{package.json, package-lock.json}; Blockchain/Dev/services/originate/{package.json, package-lock.json};
#   (b) EVERY file of Blockchain/Dev/scripts/audit/ (13 at draft, incl. audit-baseline.json, audit-gate.mjs, audit-locks.mjs); the listing must
#       name exactly these 13;
#   (c) 3 REACH paths with no #1033 blob: services/originate/Dockerfile (the runtime step), prisma/schema.prisma (the datasource provider),
#       packages/shared/package-lock.json (the /shared tree the image copies).
# Every path at its merge-base blob -> OK (develop's SHA is printed, not judged). ALL 5 PR paths at their #1033 blobs (reach paths unmoved) -> exit 19
# LANDED. Any path at a blob nobody pinned, a file absent, a scripts/audit/ file added or removed, or a PARTIAL landing -> exit 18 GUARDED.
# TEN open Dependabot PRs touch the root lock (#949 #948 #947 #946 #945 #649 #639 #635 #575 #572; #949 prisma 7.8.0 -> 7.10.0 and #575 also
# services/originate/package.json; #945 and #920 the root package.json): one of them landing first REFUSES here by design — re-pin deliberately.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit pane, never inside a
# Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY.
# exit 23: brief AND prompt must carry the exact #1033 verdict subject; the prompt must name coagent@ as sender and wednesday-agent@ as recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY; the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM.
# exit 26: the prompt must require every container named uniquely, jest --runInBand in containers, and the host load average beside every timed run.
# exit 27: brief AND prompt must carry the RUNTIME REACH FIRST rule (the verdict's first line; the tier depends on it).
# exit 28: brief AND prompt must carry the npm-version dependent root-lock finding (host npm cannot reproduce the root lock; a false NO GO trap).
# QA1033_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED arms and an older develop can be proven.
# A launch with any QA1033_* override set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1033/gen_launcher_1033.py from launch_qa_secuura_ks1211_1030.sh (asserted substitutions + segment
# replacement + pins re-read from the repo + residual guard + output controls + bash -n). Exit codes 2..28 (19 = LANDED).
# Written by the generator because it contains a legitimate directory change.
#
# Usage: launch_qa_secuura_ks763_1033.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..28 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1033_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1033-ks763-mysql2-tier1.md}"
PROMPT_FILE="${QA1033_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1033-ks763-mysql2-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-763-override-mysql2'
HEAD_SHA="${QA1033_HEAD:-2cab54988b4e7b71d403576719f5fd80e470fa92}"
MERGE_BASE='bb848b8283eb5ee6a6180067315b76f1321e7b6b'   # the merge-base of the head with develop = the develop 2cab54988 merged in (#1030 squash)
DEVELOP_SHA='27e53ec3aa010b50cd9b2e4a1d15cbb34605ba7d'   # develop at draft = #1029 squash (ls-remote 22:46:44, 22:50:15 and 23:02:00 AEST) — PRINTED, never a guard
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks763-1033-2cab54988-tier1-r1/'
SUBJECT='[QA -> Wednesday] TIER 1 GATE #1033 (KS-763) 2cab54988 — '
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1033-ks763-mysql2-tier1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1033 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1033 = bb848b828 ahead 2 files 5 (behind 1 at draft time: #1029 — deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=2 files=5" ] || { echo "REFUSING: #1033 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=2 files=5'" >&2; exit 10; }

# The develop arm, judged by PATH BLOBS (see the header) — never by develop's SHA, never by a pinned...develop compare.
CUR_DEV="${QA1033_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import json, os, sys, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
# path -> [merge-base blob = develop-OK, the #1033 blob = LANDED, empty for the 3 REACH paths]; read by generator from the Secuura checkout with git rev-parse
JUDGED = {
  "Blockchain/Dev/package-lock.json": ["5bd5680f8ce9853b2fa26778a2609b3d00913b8d", "646c19f6f7f735ba32bfb20bef8b936835184949"],
  "Blockchain/Dev/package.json": ["769b7adbda124bb200dd9827d2e4fbc5883e6124", "773443a9faa0a2eb7caf01c313b880fbe3251922"],
  "Blockchain/Dev/services/originate/package-lock.json": ["040908e22c620b245d7d1c1c0f512409ef94f043", "4c1800aee48392e6ca2efa80526b1b2627cec34d"],
  "Blockchain/Dev/services/originate/package.json": ["749912c592e8630fff348cc60e1bf49677c18ab1", "d4435238d3ece7f7da42f043f56ca7739a611132"],
  "Blockchain/Dev/services/originate/Dockerfile": ["ac2fb91bf7d814b407f41bcca904793b6d6d91c1", ""],
  "Blockchain/Dev/prisma/schema.prisma": ["96c3342fa86777ee520a072a8e2a5146325854af", ""],
  "Blockchain/Dev/packages/shared/package-lock.json": ["5cf24ef21d0d473f388288f24b2b47c1eb7383c0", ""],
}
# EVERY file of Blockchain/Dev/scripts/audit/ -> [merge-base blob, #1033 blob or empty]; the listing must name exactly these
AUDIT_DIR = "Blockchain/Dev/scripts/audit"
AUDIT = {
  "advisory-fetch-stub.mjs": ["29c9fc48f32857d4f24ef944b9868639e0171435", ""],
  "audit-baseline.json": ["b647dd66e6772720a5252af9370655ceeda2b2b9", "91d8b71c9701e742c60a1c53049fd6fb5873486c"],
  "audit-gate.mjs": ["8e236ee70ce1a4634552596fb86fcffce234f221", ""],
  "audit-locks.mjs": ["aff23b0420ced863884787443a35f28cf727bd09", ""],
  "baseline-contract.mjs": ["2504d9a28dc017fcaabfc88248bf1c64431eb38a", ""],
  "baseline-contract.test.mjs": ["2379c0aeee6e3e3f0c4ef3a2512e3a590ad47d29", ""],
  "could-not-check.mjs": ["92eea6087a6c442f1a14e735ba9fcca74493bd0a", ""],
  "expected-case-count": ["04f9fe46068b397a6fc24d647b7e3ec4315c15e7", ""],
  "gate-exit-codes.test.mjs": ["40079f6fb41e146a34a66463e352b9c0a49f91e8", ""],
  "lock-discovery.mjs": ["3dd903b527f26c758cc1da84b10cc0a0db3b1d46", ""],
  "lock-discovery.test.mjs": ["f102d9d4c4523091fe4e3119d6c539fb29bfd904", ""],
  "package-lock.json": ["ffb2b110a2d69c2c9a10e6caf5666c5fa08ec62c", ""],
  "package.json": ["d5977b6a13638558ef57e8c294809d7ada8be6cd", ""],
}
for n, v in AUDIT.items():
    JUDGED[AUDIT_DIR + "/" + n] = v
dirs = sorted({p.rsplit("/", 1)[0] for p in JUDGED})
seen = {}
for d in dirs:
    try:
        listing = get("/contents/" + d + "?ref=" + cur)
    except Exception as e:
        print("UNJUDGEABLE contents listing unreadable for " + d + ": " + type(e).__name__); sys.exit(0)
    for x in listing:
        seen[d + "/" + x["name"]] = x["sha"] if x.get("type") == "file" else "type-" + str(x.get("type"))
    if d == AUDIT_DIR:
        names = sorted(x["name"] for x in listing)
        if names != sorted(AUDIT):
            print("GUARDED develop " + cur[:9] + " scripts/audit/ file set differs from the pin: " + ",".join(sorted(set(names) ^ set(AUDIT)))); sys.exit(0)
landed, unpinned, ok = [], [], 0
for p, (base, own) in JUDGED.items():
    b = seen.get(p, "ABSENT")
    if b == base:
        ok += 1
    elif own and b == own:
        landed.append(p.replace(D, ""))
    else:
        unpinned.append(p.replace(D, "") + " " + b[:9])
owned = sum(1 for v in JUDGED.values() if v[1])
if unpinned or (landed and len(landed) != owned):
    print("GUARDED develop %s: %d guarded path[s] at a blob nobody pinned %s; %d of %d at the #1033 blob" % (cur[:9], len(unpinned), unpinned[:6], len(landed), owned)); sys.exit(0)
if landed:
    print("LANDED develop %s: all %d #1033 blobs present — #1033 has landed; this brief is stale" % (cur[:9], owned)); sys.exit(0)
note = "= the draft pin" if cur == pinned else "MOVED from the draft pin " + pinned[:9] + ", not judged by SHA"
print("OK develop %s %s: %d of %d guarded paths at their merge-base blobs [4 PR paths + 3 reach paths + all %d files of scripts/audit/], read from %d directory listings" % (cur[:9], note, ok, len(JUDGED), len(AUDIT), len(dirs))); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop $CUR_DEV is not provably clean on the guarded paths: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher JUDGED/AUDIT blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'farmed per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY" >&2; exit 22; }
grep -qF "$SUBJECT" "$PROMPT_FILE" && grep -qF "$SUBJECT" "$BRIEF" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not carry the exact #1033 verdict subject, or the prompt does not name the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR, or the prompt does not name NOT-TESTED.written-first.md" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM" >&2; exit 25; }
grep -qi 'name it uniquely' "$PROMPT_FILE" && grep -qF -- '--runInBand' "$PROMPT_FILE" && grep -qi 'load average' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require unique container names, jest --runInBand in containers, or the host load average beside timed runs" >&2; exit 26; }
grep -qF 'RUNTIME REACH FIRST' "$PROMPT_FILE" && grep -qF 'RUNTIME REACH FIRST' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the RUNTIME REACH FIRST rule" >&2; exit 27; }
grep -qi 'npm-version dependent' "$PROMPT_FILE" && grep -qi 'npm-version dependent' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the npm-version dependent root-lock finding (host npm cannot reproduce the root lock)" >&2; exit 28; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1033 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1033 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY; unique container names; jest --runInBand in containers; the host load average beside timed runs"
  echo "  brief and prompt carry the exact verdict subject ($SUBJECT...); prompt names coagent@ -> wednesday-agent@"
  echo "  brief and prompt name the report directory; prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM, the RUNTIME REACH FIRST rule and the npm-version dependent root-lock finding"
  echo "  guarded paths (blobs at the current develop): the 4 non-audit PR paths + 3 reach paths (originate Dockerfile, prisma/schema.prisma, packages/shared lock) + every file of Blockchain/Dev/scripts/audit/ (13, incl. audit-baseline.json)"
  [ -n "${QA1033_CUR_DEV:-}" ] && echo "  (develop read from the QA1033_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1033_BRIEF:-}${QA1033_PROMPT:-}${QA1033_HEAD:-}${QA1033_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
