#!/bin/bash
# launch_qa_secuura_batch1042_1045.sh — cross-project QA agent, ONE BATCHED ROUND 1 gate at the TIER 1 floor over FOUR file-disjoint Secuura/Blockchain PRs
#   #1042 KS-1254 @ 2ad066ae2  ks256 BOUNDARY_ROWS: 3 rows pin the upper-case variant nibble + the credit_ decision, TEST-ONLY  — TIER 2
#   #1043 KS-1228 @ 8d42bb016  originate documents.ts + certifications.ts: a refused request writes no action_provenance row  — TIER 1 (sets the floor)
#   #1044 KS-1258 @ a21691fa4  system-status.ts: a DEGRADED optional service gets read-only advice, never start/restart     — TIER 2
#   #1045 KS-1230 @ 63ecb0930  admin.ts PUT /api/admin/settings: 400 + store nothing on a malformed allowedDocumentTypes     — TIER 1 (allow-list write)
# Batched under Kam's 09:22 rule. FOUR verdicts, one per head; one PR failing does not block the others. Merge authority for each: WEDNESDAY'S signed GO
# naming its head, under Kam's TESTED grant (exit 26).
#
# THE SHAPE, re-read live 15:53:06 AEST 2026-09-18 (git ls-remote develop + refs/pull/N/head) and again by the generator: each PR is ONE commit whose
# parent IS develop 8b9c3f022; compare develop...head = merge_base 8b9c3f022, ahead 1, files 1/4/2/2 (asserted per PR, exit 10). Pairwise file-disjoint
# (9 files). Each PR over develop is a fast-forward (merged tree = head tree). ALL FOUR = tree 816d53a2b, re-derived by the generator by pure tree
# hashing (no git write), equal to the builder's prediction and to its predict commit 93c99760a's tree. #1044 and #1045 are byte-identical to their
# CANONICAL local-model patches (re-applied by the generator in a plain scratch dir); #1042 and #1043 are the seat's own code.
#
# The develop pin is judged by CONTENT — THIRTY-ONE paths by blob at the CURRENT develop: the nine PR files (six at develop blobs, three new tests
# ABSENT; any PR's head blob -> exit 19 LANDED, naming the PR), and what the gate runs or reads: contract.mjs (the #1042 tamper target), shared
# package.json / vitest.config.ts, originate provenance.ts / shareRepo.ts / package.json / package-lock.json / jest.config.js / tsconfig.json,
# api-gateway verification.ts / health.ts / redis.ts (the platform-settings readers), index.ts, package.json / vitest.config.ts / vitest.setup.ts /
# tsconfig.json, the admin Settings page, eslint.config.mjs and the root package-lock.json. GUARDED: api-gateway src/ + config, originate src/ +
# config, packages/shared src/ + config, scripts/spec-examples/, the Settings page, eslint.config.mjs, the root lock, BACKLOG.md.
#
# SOURCE = gatesets/2026-09-18_gate1042to1045/mail_batch1042_ready.md, the seat's READY mail (05:50:47Z) captured verbatim by message id from wednesday-agent@.
#
# exit 6:  any of the four heads is not at its branch AND at refs/pull/N/head on origin (the refusal names the PR).
# exit 7:  the prompt must carry the TIER 1 floor AND each PR's own tier line.
# exit 20: the READY mail AND the prompt must name all four heads.
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY.
# exit 23: the prompt must carry the exact batch verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient, and FOUR verdict lines.
# exit 24: the prompt must name the REPORT DIRECTORY, the PRIOR REPORT (the #1038-#1041 batch) and NOT-TESTED.written-first.md.
# exit 25: the prompt must carry the MERGE ADDENDUM per PR and the CLOSED / STILL OPEN / NEW disposition.
# exit 26: the prompt must name WEDNESDAY'S signed GO as each PR's merge authority, with no Kam's-tap and no "not ... alone" condition.
# exit 27: the READY mail AND the prompt must BOTH carry the seat's own words: 'legs 3/4/8 skipped', 'login_stub' and 'TS2708'.
# exit 28: the prompt must forbid entering any seat worktree and writing in the seat's 2026-09-18_seatA-11th history.
# exit 29: the prompt must require every listener the gate starts ENDED BY PID, with a census (KS-1201).
# exit 30: the prompt must carry the checker note (checker.sh:921, NOT a PR finding) and the #1043 NODE_ENV restore question.
# QAB1042_CUR_DEV (test override, --check only): stands in for origin develop. QAB1042_HEAD_1045 (test override): stands in for #1045's pinned head.
# QAB1042_ADMIN_FILE (test fixture, --check only): a local file stands in for develop services/api-gateway/src/routes/admin.ts (its git blob).
# A launch with any QAB1042_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-18_gate1042to1045/gen_launcher_batch1042_1045.py from launch_qa_secuura_batch1038_1041.sh (asserted block
# substitutions + pins re-read + canonical-patch identity + all-four tree re-derived + residual guard + output controls + bash -n).
#
# Usage: launch_qa_secuura_batch1042_1045.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..30 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QAB1042_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate1042to1045/mail_batch1042_ready.md}"
PROMPT_FILE="${QAB1042_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-18_secuura-batch1042-1045.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# n|ticket|branch|head — pinned from the seat READY (05:50:47Z) and re-read by the drafter (git ls-remote 15:53:06 AEST, branch AND refs/pull/N/head)
PRS=(
  "1042|KS-1254|refs/heads/feature/ks-1254-ks256-cells-pin-the-upper-case-rfc-variant-nibble-and-the|2ad066ae213631e05a6f0d67d5d57b73cdb23dac"
  "1043|KS-1228|refs/heads/feature/ks-1228-a-refused-request-still-writes-an-action_provenance-row|8d42bb01627ba46354d58b5b07c8d1c5c274deb9"
  "1044|KS-1258|refs/heads/feature/ks-1258-systemstatus-tells-operators-to-start-the-service-locally|a21691fa474632e340d36378213d53d9aaa01915"
  "1045|KS-1230|refs/heads/feature/ks-1230-put-apiadminsettings-stores-a-connectors|${QAB1042_HEAD_1045:-63ecb0930a2fc6ababa7e2fd2c189392f67b4269}"
)
DEVELOP_SHA='8b9c3f022bee76b79a47f1b8c5de8ad3ddb4a0ae'   # the pin = develop at 15:53:06 AEST: the #1041 KS-1209 squash, every head's parent
MERGE_BASE="$DEVELOP_SHA"    # every PR is one commit on the pin itself — the compare is asserted against it
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-batch1042-1045-tier1-r1/'
PRIOR_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-batch1038-1041-tier1-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/gatesets/2026-09-18_gate1042to1045/mail_batch1042_ready.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The four heads, each pinned at its branch AND at refs/pull/N/head on origin (one ls-remote per PR). One moved head refuses the launch: re-pin that PR.
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h <<< "$_pr"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved; a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done

# The compare (GitHub compare API) per PR, asserted whole (merge_base + ahead + files; NOT behind — develop is expected to move):
# develop...#1042 = 8b9c3f022 ahead 1 files 1; #1043 files 4; #1044 files 2; #1045 files 2 (git diff --name-only, drafter 15:5x AEST; the launcher reads the compare API).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h = pr.split("|")
    r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + h, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
    c = json.load(r)
    print("%s %s ahead=%d files=%d" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compares develop...head from the GitHub compare API" >&2; exit 13; }
WANT_COMPARE="1042 $MERGE_BASE ahead=1 files=1
1043 $MERGE_BASE ahead=1 files=4
1044 $MERGE_BASE ahead=1 files=2
1045 $MERGE_BASE ahead=1 files=2"
[ "$COMPARE" = "$WANT_COMPARE" ] || { echo "REFUSING: develop...head compares read" >&2; printf '%s\n' "$COMPARE" >&2; echo "the gateset pins" >&2; printf '%s\n' "$WANT_COMPARE" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): thirty-one paths by PATH BLOB at the CURRENT develop (no region judgement), then — if
# develop moved — the pinned...develop delta against the GUARDED list, with NOTHING cleared by content (DEV_CONTENT_ALLOWED is empty).
CUR_DEV="${QAB1042_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
A = D + "services/api-gateway/"
O = D + "services/originate/"
S = D + "packages/shared/"
ADMINTS = A + "src/routes/admin.ts"
DV = "develop"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  S + "src/__tests__/ks256-spec-example-contract.test.ts":                       ({"4ef040f6f2fbbe6d73a76ff860caf71ac0bbe619": DV}, {"c083367c6b75aec1284ac9e48af75dd01beb5597": "#1042 own"}),
  "BACKLOG.md":                                                                  ({"dca47caa155e3f743ad401fc62a56618ec6f47fa": DV}, {"59a1928dc56d9921dbdf2e8d36667e2df6af4024": "#1043 own"}),
  O + "src/routes/certifications.ts":                                            ({"20934ee94abdb0c406df06a9f6025b2d989d4dbd": DV}, {"02dcbe6294b497eab093f11a8fc6c9e275be91c5": "#1043 own"}),
  O + "src/routes/documents.ts":                                                 ({"e3eeb5a6873d1edd7cae0d1c2b1eb2410faedb77": DV}, {"b5e76dc61ae5d4da8667b466b0a1dcf79d5a0498": "#1043 own"}),
  A + "src/routes/system-status.ts":                                             ({"0b0a4af82d5bdc9ddda96aabc86dda9fb6de98aa": DV}, {"e911ce1fdaa4b755e9b7b6428f899cdbd63889cb": "#1044 own"}),
  ADMINTS:                                                                       ({"f47dd6a655702ffbfc402ca920a33c4619d62c4b": DV}, {"20c8a088f5dc34fc1563b3907e7c816e1b9fa3d3": "#1045 own"}),
  D + "scripts/spec-examples/check/contract.mjs":                                ({"07d4e9ab6b2879e08acfd587c4575bfaac1d1071": DV}, {}),
  S + "package.json":                                                            ({"3957692311221fbe87c4ab19447de8cec44aa19a": DV}, {}),
  S + "vitest.config.ts":                                                        ({"2a226c0068faa65538cda8d43d03bb9bee2944f1": DV}, {}),
  O + "src/services/provenance.ts":                                              ({"483aa9eb331d2caa5af285e20d9668a9dbcd92a6": DV}, {}),
  O + "src/repositories/shareRepo.ts":                                           ({"55494e94957560e8415d567ed53560183eb98873": DV}, {}),
  O + "package.json":                                                            ({"d4435238d3ece7f7da42f043f56ca7739a611132": DV}, {}),
  O + "package-lock.json":                                                       ({"4c1800aee48392e6ca2efa80526b1b2627cec34d": DV}, {}),
  O + "jest.config.js":                                                          ({"735183662feea56d39f664eb6379cae1a2eec957": DV}, {}),
  O + "tsconfig.json":                                                           ({"d1b46ece71ad5b2559ccad3648c23a5231e43b09": DV}, {}),
  A + "src/routes/verification.ts":                                              ({"f888e8cd0bd10c98a508542d75902ab122595157": DV}, {}),
  A + "src/services/health.ts":                                                  ({"7bedc074583d816d997bd6d679043db010804aed": DV}, {}),
  A + "src/services/redis.ts":                                                   ({"fbb74be7ccc3f3068b243af527f8dfff7cd63fbb": DV}, {}),
  A + "src/index.ts":                                                            ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": DV}, {}),
  A + "package.json":                                                            ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  A + "vitest.config.ts":                                                        ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  A + "vitest.setup.ts":                                                         ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  A + "tsconfig.json":                                                           ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "frontend/admin/src/pages/Settings.tsx":                                   ({"e414630f25c49a954a41d75794a37da781804b3b": DV}, {}),
  D + "eslint.config.mjs":                                                       ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
  D + "package-lock.json":                                                       ({"646c19f6f7f735ba32bfb20bef8b936835184949": DV}, {}),
  O + "src/__tests__/ks1228-a-refused-request-writes-no-provenance-row.test.ts": ({"ABSENT": DV}, {"0b9be16318b97d1a214afcfdd5a1c0483c27904e": "#1043 own"}),
  A + "src/__tests__/ks1258-degraded-optional-service-advice.test.ts":           ({"ABSENT": DV}, {"9143365cb4571906f6d0c2df13db430645447c72": "#1044 own"}),
  A + "src/__tests__/ks1230-settings-write-validates-allowed-document-types.test.ts": ({"ABSENT": DV}, {"dd5ce85644dde844833989ad482288bf855e3d23": "#1045 own"}),
}
# No REGION judgement: every path is judged by exact blob (a develop move of any judged path refuses, exit 18; any PR head blob, exit 19).
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QAB1042_ADMIN_FILE", "") if f == ADMINTS else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — that PR has landed; this gateset is stale for it"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (the parent of all four heads: each merged tree = its head tree, a fast-forward: #1042 5e38b665c3d87ecfb619a963dc294f7e19175ba9, #1043 5487055f3ca340994314464e74adc00c935cdeb6, #1044 615ffd6c491a349978292bcdc61a0e2b04c8e946, #1045 849cc11bf86afb4da2a95b37e82000090a2b9943; all four together 816d53a2b5189482aab2f763b2b5940ddcd45389, drafter tree-hash = builder prediction; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [A + "src/",
           A + "package.json",
           A + "vitest.config.ts",
           A + "vitest.setup.ts",
           A + "tsconfig.json",
           O + "src/",
           O + "package.json",
           O + "package-lock.json",
           O + "jest.config.js",
           O + "tsconfig.json",
           S + "src/",
           S + "package.json",
           S + "vitest.config.ts",
           D + "scripts/spec-examples/",
           D + "frontend/admin/src/pages/Settings.tsx",
           D + "eslint.config.mjs",
           D + "package-lock.json",
           "BACKLOG.md"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: EMPTY. Nothing is pre-cleared for this batch; any GUARDED move refuses: re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto EACH of the four heads in its own clones, names each merged-tree OID (drafter over the pin: each = its head tree; all four 816d53a2b) and re-runs each PR items and suites on it"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — GUARDED hits %d, cleared by content %d — the rest disjoint from the GUARDED list (api-gateway, originate and packages/shared src/ + config, scripts/spec-examples/, the admin Settings page, eslint.config.mjs, the root lock, BACKLOG.md); %s" % (pinned, cur, c["ahead_by"], len(files), len(hits), len(cleared), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'at the TIER 1 floor' "$PROMPT_FILE" && grep -qF '#1042 KS-1254: TIER 2' "$PROMPT_FILE" && grep -qF '#1043 KS-1228: TIER 1' "$PROMPT_FILE" && grep -qF '#1044 KS-1258: TIER 2' "$PROMPT_FILE" && grep -qF '#1045 KS-1230: TIER 1' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the TIER 1 floor and each PR's own tier line (#1042 T2, #1043 T1, #1044 T2, #1045 T1)" >&2; exit 7; }
grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: prompt does not name ROUND 1" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the seat's READY mail capture path" >&2; exit 9; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h <<< "$_pr"
  grep -qF "$_h" "$PROMPT_FILE" && grep -qF "${_h:0:9}" "$BRIEF" \
    || { echo "REFUSING: the READY mail or the prompt does not name #$_n's head $_h — a gate about another SHA is another gate" >&2; exit 20; }
done
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] BATCH GATE #1042 #1043 #1044 #1045 (KS-1254 KS-1228 KS-1258 KS-1230)' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" && grep -qF 'FOUR lines, one per PR' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact batch verdict subject, coagent@ / wednesday-agent@, and FOUR verdict lines one per PR" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$PRIOR_REPORT" "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not name the report directory $REPORT_DIR, the PRIOR REPORT $PRIOR_REPORT and NOT-TESTED.written-first.md" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM line PER PR' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry a MERGE ADDENDUM line PER PR and the CLOSED / STILL OPEN / NEW disposition" >&2; exit 25; }
grep -qiF "WEDNESDAY'S signed GO naming each head" "$PROMPT_FILE" && ! grep -qiE "waits for Kam.s tap|on Kam.s tap only|signed GO alone" "$PROMPT_FILE" "$BRIEF" \
  || { echo "REFUSING: prompt does not name WEDNESDAY'S signed GO naming each head as the merge authority, or carries a Kam's-tap / not-alone condition" >&2; exit 26; }
grep -qF 'legs 3/4/8 skipped' "$PROMPT_FILE" && grep -qF 'login_stub' "$PROMPT_FILE" && grep -qF 'TS2708' "$PROMPT_FILE" \
  && grep -qF 'legs 3/4/8 skipped' "$BRIEF" && grep -qF 'login_stub' "$BRIEF" && grep -qF 'TS2708' "$BRIEF" \
  || { echo "REFUSING: the READY mail and the prompt do not BOTH carry the seat's words: legs 3/4/8 skipped / login_stub / TS2708" >&2; exit 27; }
grep -qF 'Never enter any seat worktree' "$PROMPT_FILE" && grep -qF '/Volumes/DevMASTER/!CODING/Secuura/Blockchain/5_Project_History/2026-09-18_seatA-11th/' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid entering any seat worktree and writing in the seat's 2026-09-18_seatA-11th history" >&2; exit 28; }
grep -qF 'END EVERY LISTENER YOUR RUNS START, BY PID' "$PROMPT_FILE" && grep -qF 'TCP LISTEN census' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require every listener the gate starts ended by pid with a census (KS-1201)" >&2; exit 29; }
grep -qF 'checker.sh:921' "$PROMPT_FILE" && grep -qF 'NOT a PR finding' "$PROMPT_FILE" && grep -qF 'NODE_ENV' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the checker note (checker.sh:921, NOT a PR finding) and the #1043 NODE_ENV restore question" >&2; exit 30; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  four heads on origin (branch AND refs/pull/N/head):$HEADS_NOTE"
  echo "  compares (GitHub API), develop...head per PR:"
  printf '%s\n' "$COMPARE" | sed 's/^/    /'
  echo "  $DEV_NOTE"
  echo "  READY mail, prompt, QA project and repo all present"
  echo "  prompt carries the TIER 1 floor and each PR's tier (#1042 T2, #1043 T1, #1044 T2, #1045 T1); names ROUND 1"
  echo "  prompt opens with the thinking directive and names the READY mail capture"
  echo "  READY mail and prompt both name all four heads"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact batch verdict subject, coagent@ sender, wednesday-agent@ recipient, FOUR verdict lines"
  echo "  prompt names the report directory, the #1038-#1041 batch PRIOR REPORT and NOT-TESTED.written-first.md"
  echo "  prompt carries a MERGE ADDENDUM line PER PR and CLOSED / STILL OPEN / NEW"
  echo "  prompt names WEDNESDAY'S signed GO naming each head; no Kam's-tap or not-alone condition"
  echo "  READY mail and prompt BOTH carry: legs 3/4/8 skipped / login_stub / TS2708"
  echo "  prompt forbids any seat worktree and the seat's 2026-09-18_seatA-11th history"
  echo "  prompt requires every listener ended by pid with a TCP LISTEN census (KS-1201)"
  echo "  prompt carries the checker note (checker.sh:921, not a PR finding) and the #1043 NODE_ENV restore question"
  [ -n "${QAB1042_CUR_DEV:-}" ] && echo "  (develop read from the QAB1042_CUR_DEV test override, not ls-remote)"
  [ -n "${QAB1042_ADMIN_FILE:-}" ] && echo "  (develop services/api-gateway/src/routes/admin.ts read from the QAB1042_ADMIN_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QAB1042_BRIEF:-}${QAB1042_PROMPT:-}${QAB1042_HEAD_1045:-}${QAB1042_CUR_DEV:-}${QAB1042_ADMIN_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
