#!/bin/bash
# launch_qa_secuura_ks1187_1019r2.sh — cross-project QA agent, ONE TIER 1 ROUND 2 DELTA gate (round 2 of 2 under the cap) over Secuura/Blockchain PR #1019
# (KS-1187, Seat A) @ 82f09c8bd1bfab28e4d23c180cbaffea251685be — round 1 (head 8b8996f8b) was NO GO on F-1019-1: the canonical door verdict popped the door segment
# for a dot segment after it (erasures/..), judged not-door, and the gateway forwarded the RAW path that originate routes to /erasures/:externalRef. The round-2 commit
# 4d551f104 (parent 8b8996f8b): routes/proxy.ts +13 -3 (erasureDoorVerdict answers undetermined for any . or .. segment once the resolved first segment names the door,
# under the door router case rule), the ks1187 test +148 (31 new cells: dot verdicts, real-app test + production, F-1019-2 case-sensitive router, F-1019-3 restore).
# 82f09c8bd = a merge of develop f8c7aaa39 (#1017 squash d7e95cd9f + #1020 squash) into 4d551f104; no file overlap. TIER 1: an authorisation door on a GDPR erasure
# route. ROUND 2 of 2 is the CAP: a NO GO ships the closed instances and tickets the residue.
#
# THE SHAPE, as read 16:44-16:51 AEST 2026-09-17 (git ls-remote x3 + the PR, compare and contents APIs agree): develop f8c7aaa39 is the head merge-base AND an ANCESTOR
# of the head, so compare develop...head = merge_base f8c7aaa39, ahead 4, behind 0, files 3 (asserted as merge_base + ahead + files, exit 10; behind NOT asserted).
# Merged tree over develop = the head tree 99df1503e (= merge-tree 4d551f104 x f8c7aaa39 in the drafter clone = the seat's prediction).
#
# The develop pin is judged by CONTENT, not bare: (a) TWENTY-ONE files by blob at the CURRENT develop — the PR's three (proxy.ts b99f45a4c, the ks843 scope-gate test
# a3c554121, the ks1187 test ABSENT; at their round-1 OR round-2 head blobs -> exit 19 LANDED), #1017's five at their develop blobs (d7e95cd9f), normalisePath.ts,
# scopes.ts, security.ts, config/services.ts, versioning.ts, the ks843 path-bypass test, api-gateway package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json,
# Dev eslint.config.mjs, originate routes/gdpr.ts and originate index.ts — any blob nobody pinned -> exit 18; proxy.ts at ANY OTHER blob is judged by REGION content
# (the import block through the Factory banner, and the erasure door through the gdpr catch-all mount): a move into a region refuses (exit 18), a move outside clears;
# (b) if develop moved past f8c7aaa39, the compare pinned...develop REFUSES (exit 18) when the delta touches a GUARDED path — services/api-gateway/src/ and its config
# files, originate routes/gdpr.ts + index.ts, eslint.config.mjs, the Dev lockfile — unless the hit is proxy.ts cleared by its region judgement (DEV_CONTENT_ALLOWED is
# EMPTY), or the move cannot be judged.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate's R-6: a wholesale link can write through to the checkout's .vite).
# exit 23: the prompt must carry the exact ROUND 2 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the round-2 REPORT DIRECTORY and the ROUND-1 REPORT path (the QA agent has no inbox), and the prompt must name
#          NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition (round 2 of 2: closed instances ship,
#          residue is ticketed).
# QA1019R2_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA1019R2_PROXY_FILE (test fixture, --check only): a local file stands in for develop's routes/proxy.ts (content AND git blob) so the region judgement's
# clear and refuse arms, and the LANDED arm, can be proven without a real develop commit.
# A launch with any QA1019R2_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1019r2/gen_launcher_1019r2.py from launch_qa_secuura_ks1187_1019.sh (asserted substitutions + residual
# guard + output controls + bash -n): same guard set and exit codes 2..23, re-pointed at #1019 ROUND 2, with round-2 exits 24/25. Exit codes 2..25 (19 = LANDED).
#
# Usage: launch_qa_secuura_ks1187_1019r2.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1019R2_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.md}"
PROMPT_FILE="${QA1019R2_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-1187-security-an-absolute-form-request-target-bypasses-the-ks-843'
HEAD_SHA="${QA1019R2_HEAD:-82f09c8bd1bfab28e4d23c180cbaffea251685be}"
MERGE_BASE='f8c7aaa39dabfe6a3916e5be55d9ccd752e7d8ed'   # the merge-base of the head with develop = develop itself, the second parent of the head merge 82f09c8bd (#1020s squash on #1017s squash)
DEVELOP_SHA='f8c7aaa39dabfe6a3916e5be55d9ccd752e7d8ed'   # develop at round-2 drafting, an ANCESTOR of the head (git ls-remote 16:44:13, 16:44:54, 16:48:17; branches API 16:50 AEST)
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019r2-82f09c8bd-tier1-r2/'
R1_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019-8b8996f8b-tier1-r1/'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1019 ROUND 2 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1019 ROUND 2 = f8c7aaa39 ahead 4 files 3 (behind 0 at draft close; behind deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=4 files=3" ] || { echo "REFUSING: #1019 ROUND 2 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=4 files=3'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): twenty-one files by blob at the CURRENT develop (proxy.ts also by region), then — if develop
# moved — the pinned...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="${QA1019R2_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import hashlib, json, os, sys, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
def raw(path, ref):
    return urllib.request.urlopen(urllib.request.Request(api + "/contents/" + path + "?ref=" + ref, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github.raw"}), timeout=60).read().decode("utf-8")
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
G = D + "services/api-gateway/"
PX = G + "src/routes/proxy.ts"
DV = "develop"
S17 = "develop = #1017 squash d7e95cd9f"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  PX:                                                                  ({"b99f45a4c9c89088a7809de5f26c4f56fc94819c": DV}, {"db1534753c571e7496c5e47d58bd9304515132c1": "#1019 round-1 own", "795ae7ca3bdc76be3e563e87fc34a8cc221e5632": "#1019 round-2 own"}),
  G + "src/__tests__/ks843-erasure-scope-gate.test.ts":                ({"a3c5541216a2b6052bc1396310004b12ea89fc25": DV}, {"06b499605e79ff0cc882ff3af82d2d3dd7569455": "#1019 own, rounds 1 and 2"}),
  G + "src/__tests__/ks1187-erasure-door-judges-the-canonical-path.test.ts": ({"ABSENT": DV}, {"389e51e1df153c295064b288c243a41289479513": "#1019 round-1 own", "76c0137ee0accb5c37b376f53565c45789e09890": "#1019 round-2 own"}),
  G + "src/middleware/auth.ts":                                        ({"7c985bdcefc26293815bfbe0cbf315f929b48835": S17}, {}),
  G + "src/middleware/rateLimitEnforce.ts":                            ({"90bd29378508c8fee54e010b54cdc72ff992aafa": S17}, {}),
  G + "src/index.ts":                                                  ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": S17}, {}),
  G + "src/__tests__/ks1195-per-key-rate-limiter-runs-after-authentication.test.ts": ({"4b1fc017da158de4e7a3a47565b7dbccc1ea3872": S17}, {}),
  D + "packages/shared/src/__tests__/ks781-p3-3-body-parser-order.test.ts": ({"bc4815c4ec9cae2f065e29dec6b938cdf49f2d23": S17}, {}),
  G + "src/middleware/normalisePath.ts":                               ({"1a7312a8675ffdfe263060bb5d60aa837111431a": DV}, {}),
  G + "src/middleware/scopes.ts":                                      ({"7aef335b93acf7a94fbcadc61c353d7a5dde90c5": DV}, {}),
  G + "src/middleware/security.ts":                                    ({"69273561925c0924f33b98f5ff9c6d6cf72c2896": DV}, {}),
  G + "src/config/services.ts":                                        ({"6110888aac8c834c291b5385710943f9b6adf57b": DV}, {}),
  G + "src/routes/versioning.ts":                                      ({"697bbb48bd93775572c7bde41c303eb4775ee920": DV}, {}),
  G + "src/__tests__/ks843-erasure-path-bypass.test.ts":                ({"2c8783ac86644ef690201d73f055b3a25b766d41": DV}, {}),
  G + "package.json":                                                  ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  G + "vitest.config.ts":                                              ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  G + "vitest.setup.ts":                                               ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  G + "tsconfig.json":                                                 ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "eslint.config.mjs":                                             ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
  D + "services/originate/src/routes/gdpr.ts":                         ({"a1c7482a250f37b0c2fbd2531e67cd5f367f1045": DV}, {}),
  D + "services/originate/src/index.ts":                               ({"44d4e4f341f5d314f5b95405b209a9450cde1d3e": DV}, {}),
}
# REGION judgement for routes/proxy.ts (brief items 1-7 stand on it); two segments of develop f8c7aaa39 proxy.ts b99f45a4c = the round-1 base blob; SHA re-computed by gen_launcher_1019r2.py, equal to round 1.
SEGS = [["import { CircuitBreaker } from @@Q@@@secuura/shared@@Q@@;", "// Factory"], ["  const erasureDoor = Router();", "proxy(@@Q@@originate@@Q@@, { @@Q@@^/api/gdpr@@Q@@: @@Q@@/api/gdpr@@Q@@ }),"]]
SEGS = [[x.replace("@@Q@@", chr(39)) for x in pair] for pair in SEGS]
WANT = "b550d7f0e8e0fc7d97961d59ecb38ecbfd7af469d4de45cc279b54adec6ba8d4"
def region_sha(text):
    parts = []
    for a, b in SEGS:
        if text.count(a) != 1:
            return "anchor-count-" + str(text.count(a))
        if text.count(b) != 1:
            return "end-anchor-count-" + str(text.count(b))
        i = text.index(a); j = text.index(b)
        if j < i:
            return "end-before-start"
        parts.append(text[i:j + len(b)])
    return hashlib.sha256("\n@@SEG@@\n".join(parts).encode()).hexdigest()
content_cleared = set()
state = []
for f, (ok, landed) in JUDGED.items():
    fixture = os.environ.get("QA1019R2_PROXY_FILE", "") if f == PX else ""
    try:
        if fixture:
            data = open(fixture, "rb").read()
            blob = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
        else:
            blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except urllib.error.HTTPError as e:
        if e.code != 404:
            print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": HTTP " + str(e.code)); sys.exit(0)
        blob = "ABSENT"
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #1019 has landed; this ROUND 2 brief is stale"); sys.exit(0)
    if blob not in ok and f == PX:
        try:
            text = open(fixture).read() if fixture else raw(f, cur)
        except Exception as e:
            print("UNJUDGEABLE develop " + short + " content unreadable: " + type(e).__name__); sys.exit(0)
        rs = region_sha(text)
        if rs != WANT:
            print("GUARDED develop " + short + " blob " + blob[:9] + " — the #1019 region changed: region " + rs[:16] + " vs pinned " + WANT[:16]); sys.exit(0)
        content_cleared.add(f)
        state.append(f.split("/")[-1] + " " + blob[:9] + " = moved OUTSIDE the #1019 region, judged by content: region " + rs[:12])
        continue
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (= the head merge-base, an ANCESTOR of the head: merged tree = the head tree 99df1503e4f18ac444baed015659fecbb912bbb0; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [G + "src/",
           G + "package.json",
           G + "vitest.config.ts",
           G + "vitest.setup.ts",
           G + "tsconfig.json",
           D + "services/originate/src/routes/gdpr.ts",
           D + "services/originate/src/index.ts",
           D + "eslint.config.mjs",
           D + "package-lock.json"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: EMPTY for round 2. #1017 has MERGED (its squash d7e95cd9f is on develop f8c7aaa39, the pin), so no sibling blob is pre-cleared.
# proxy.ts is judged by its REGION above. Every other guarded hit falls through to exit 18. Re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if (h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") in DEV_CONTENT_ALLOWED[h]) or h in content_cleared)
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 82f09c8bd in its own clone, rebuilds the shared dist there, re-runs the round-1 harness census on the MERGED tree beside the round-1, round-2 and head trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 2, 5)"
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — disjoint from the GUARDED list (services/api-gateway/src/ + its config files, originate gdpr routes + index, eslint.config.mjs, the Dev lockfile) or cleared by the proxy.ts region judgement; %s" % (pinned, cur, c["ahead_by"], len(files), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 2' "$BRIEF" && grep -q 'ROUND 2' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 2)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'node_modules per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY (a wholesale link can write through to the checkout .vite cache)" >&2; exit 22; }
grep -qF '[QA -> Wednesday] TIER 1 GATE #1019 ROUND 2 (KS-1187) 82f09c8bd' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not carry the exact ROUND 2 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$R1_REPORT" "$PROMPT_FILE" && grep -qF "$R1_REPORT" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR and the ROUND-1 REPORT $R1_REPORT, or the prompt does not name NOT-TESTED.written-first.md — the QA agent has no inbox; a carry-forward with no pointer can only be answered with I could not" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition — round 2 of 2: closed instances ship and residue is ticketed" >&2; exit 25; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1019 ROUND 2 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1019 ROUND 2 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 2"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY"
  echo "  prompt carries the exact ROUND 2 verdict subject, coagent@ sender, wednesday-agent@ recipient"
  echo "  brief and prompt name the round-2 report directory and the ROUND-1 REPORT; prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM and require CLOSED / STILL OPEN / NEW per finding"
  [ -n "${QA1019R2_CUR_DEV:-}" ] && echo "  (develop read from the QA1019R2_CUR_DEV test override, not ls-remote)"
  [ -n "${QA1019R2_PROXY_FILE:-}" ] && echo "  (develop routes/proxy.ts read from the QA1019R2_PROXY_FILE fixture, not the contents API)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1019R2_BRIEF:-}${QA1019R2_PROMPT:-}${QA1019R2_HEAD:-}${QA1019R2_CUR_DEV:-}${QA1019R2_PROXY_FILE:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
