#!/bin/bash
# launch_qa_secuura_813_ks791.sh — cross-project QA agent, ONE TIER 1 ROUND 1 gate over Secuura/Blockchain PR #813 (KS-791,
# builder s226, wrapped) @ 7b6fb960dafd6c27af1eb9bad2a031f6bfe3a3a4 — a MERGE commit (parents 7be1eccbe + develop M38
# 0e78c7270), tree 49ffe0703. The api-gateway's content-type-confusion perimeter (KS-439, middleware/contentType.ts) takes
# an exception INTO the perimeter for TWO exact paths (/api/verification/verify-file, /api/v2/verification/verify-file;
# application/octet-stream only; the Set at :75-78, the branch at :135, +28 lines), and the two verify-file operations are
# published with `minLength: 1` on both request bodies (originate.openapi.ts:2044 / :2093, the regenerated yaml +175).
# TIER 1 because every /api/* request carrying a body passes this middleware (RULED by Wednesday 16:2x: reach wins).
#
# THE SHAPE, as read 17:29-17:38 AEST 2026-09-14 (git + the compare API agree): develop M38 is an ANCESTOR of the head
# (rev-list --count M38..head = 4; the compare develop...head = merge_base M38, ahead 4, behind 0, files 4) — so the head
# tree IS the M38-merged tree and no merge is needed at M38. The compare is asserted as merge_base + ahead + files (exit
# 10); `behind` is deliberately NOT asserted, so a develop that moves on does not trip this guard — the develop arm below
# judges the move by CONTENT.
#
# The develop pin is judged by CONTENT, not bare (the AUTH4 launcher's shape + the 912r2 DEV_CONTENT_ALLOWED table):
# (a) SEVEN files by blob at the CURRENT develop — contentType.ts (M38 6dcdaa6e0; #813's own 5b5b3e734 -> LANDED),
# contentType.test.ts (M38 1799ef843; own d77981707 -> LANDED), originate.openapi.ts (M38 12fb03ba6 OR #919's 509f13abb
# once #919 squashes; own 5e2c499f1 -> LANDED), docs/openapi/secuura-api.yaml (M38 298d95e4a OR #919's 8c3df7194; own
# d11a5a237 -> LANDED), api-gateway index.ts (6f38c819e), middleware/csrf.ts (1f16e2f89), scripts/generate-openapi.ts
# (e84acdc9e) — #813's own blob on develop means the PR has landed and THIS brief is stale: exit 19; any blob nobody pinned
# -> exit 18; (b) if develop != M38, the compare M38...develop is read and REFUSES (exit 18) only when the delta touches a
# GUARDED path — anything under services/api-gateway/, originate's originate.openapi.ts / routes/verification.ts /
# routes/verificationV2.ts, the yaml, scripts/generate-openapi.ts, scripts/spec-examples/, packages/shared/src/openapi/, the
# ks860 loopback-guard test, or the root package-lock.json — UNLESS every hit is cleared BY BLOB in DEV_CONTENT_ALLOWED
# (#919's two blobs: its squash on an unmoved M38 yields exactly them — read 17:38 from 4736e2277), or cannot be judged
# (unreadable, not ahead, >250 files); otherwise it proceeds printing the move and its file count, which the gate re-states
# (brief TARGET: the gate merges the then-current develop in its own clone, runs check:openapi on the merged tree FIRST and
# re-derives every count). Expected tonight: #919 (originate.openapi.ts + yaml + documents.ts + a new test) -> ALLOWED;
# #939 (documents.ts, documentRepo.ts, a new test) -> DISJOINT; #916/#988/#989/#927 (systemTest/) -> DISJOINT; L4's #805 /
# #922 (the yaml, 160/146 behind — a squash regenerates it) -> exit 18, re-pin deliberately.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — a gate launched there runs headless, invisible to Kam, and dies with the caller's
# shell (2026-09-13 ledger). `--check` still runs headless (it launches nothing).
#
# Generated by gen_launcher_813.py (asserted output controls; residual guard; bash -n). Exit codes 2..21 (19 = LANDED).
# Written by the generator because it contains a legitimate directory change.
#
# Usage: launch_qa_secuura_813_ks791.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..21 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA813_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-14_secuura-813-ks791-tier1-r1.md}"
PROMPT_FILE="${QA813_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-14_secuura-813-ks791-tier1-r1.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-791-publish-verify-file-v1v2-in-the-spec-coupled-with-the'
HEAD_SHA="${QA813_HEAD:-7b6fb960dafd6c27af1eb9bad2a031f6bfe3a3a4}"
MERGE_BASE='0e78c7270188ac45c1c29f927bdf90728f10215d'   # M38 = the merge-base of the head with develop (M38 is an ancestor of the head)
DEVELOP_SHA='0e78c7270188ac45c1c29f927bdf90728f10215d'
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-14_secuura-813-ks791-tier1-r1.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #813 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#813 = M38 ahead 4 files 4.
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=4 files=4" ] || { echo "REFUSING: #813 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=4 files=4'" >&2; exit 10; }

# The develop pin, judged by CONTENT (see the header): seven files by blob at the CURRENT develop, then — if develop
# moved — the M38...develop delta against the GUARDED list with the DEV_CONTENT_ALLOWED blobs cleared.
CUR_DEV="$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import json, os, sys, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label})
JUDGED = {
  D + "services/api-gateway/src/middleware/contentType.ts":        ({"6dcdaa6e005f73e779008691f366cd71cf7ca30d": "M38"}, {"5b5b3e7342d04451ea8a7dff0823fc5763122059": "#813 own"}),
  D + "services/api-gateway/src/__tests__/contentType.test.ts":    ({"1799ef843a09c707484143ce8c0cc9ecb7957ff0": "M38"}, {"d77981707ab8b1d4c9a93a8c4e3f8f0fcee79f73": "#813 own"}),
  D + "services/originate/src/originate.openapi.ts":               ({"12fb03ba61041abd0b1a38cf382258e926c39d06": "M38", "509f13abb2910ea51fe1d0093d6268caf579f750": "#919 landed (KS-739)"}, {"5e2c499f1a987fa9bd6632d381b9c9ccd7d03637": "#813 own"}),
  D + "docs/openapi/secuura-api.yaml":                              ({"298d95e4a12b2384f360f83878c6ae84773cf00b": "M38", "8c3df719459a21ecd119aea8ca125130289f7e92": "#919 landed (KS-739)"}, {"d11a5a23721296e45767624d87c4fc1a8f9622f5": "#813 own"}),
  D + "services/api-gateway/src/index.ts":                          ({"6f38c819e48162e3179aaf557085766f91beecc1": "M38"}, {}),
  D + "services/api-gateway/src/middleware/csrf.ts":                ({"1f16e2f899af46b8afc5e3872261e079c2cf88f5": "M38"}, {}),
  D + "scripts/generate-openapi.ts":                                ({"e84acdc9e1be073751fcd6a8bb95504e23688019": "M38"}, {}),
}
state = []
for f, (ok, landed) in JUDGED.items():
    try:
        blob = get("/contents/" + f + "?ref=" + cur)["sha"]
    except Exception as e:
        print("UNJUDGEABLE develop blob unreadable for " + f.split("/")[-1] + ": " + type(e).__name__); sys.exit(0)
    short = f.replace(D, "")
    if blob in landed:
        print("LANDED develop " + short + " blob " + blob[:9] + " = " + landed[blob] + " — #813 has landed; this brief is stale"); sys.exit(0)
    if blob not in ok:
        print("GUARDED develop " + short + " blob " + blob[:9] + " — a version nobody pinned"); sys.exit(0)
    state.append(f.split("/")[-1] + " " + blob[:9] + " = " + ok[blob])
state = "; ".join(state)
if cur == pinned:
    print("OK " + state + " | origin develop still " + pinned + " (M38; git ls-remote)"); sys.exit(0)
try:
    c = get("/compare/" + pinned + "..." + cur)
except Exception as e:
    print("UNJUDGEABLE compare unreadable: " + type(e).__name__); sys.exit(0)
files = c.get("files") or []
if c.get("status") != "ahead" or len(files) > 250:
    print("UNJUDGEABLE status=%s files=%d" % (c.get("status"), len(files))); sys.exit(0)
GUARDED = [D + "services/api-gateway/",
           D + "services/originate/src/originate.openapi.ts",
           D + "services/originate/src/routes/verification.ts",
           D + "services/originate/src/routes/verificationV2.ts",
           D + "docs/openapi/secuura-api.yaml",
           D + "scripts/generate-openapi.ts",
           D + "scripts/spec-examples/",
           D + "packages/shared/src/openapi/",
           D + "packages/shared/src/__tests__/ks860-test-listeners-bind-loopback.test.ts",
           D + "package-lock.json"]
# STYLE NOTE (912r2 launcher, measured): bash scans quote/paren state THROUGH this heredoc because it sits inside a
# command substitution — keep apostrophes and parentheses EVEN (this block uses none of the former), or the outer $( ) breaks.
# CONTENT-JUDGED allowlist: a hit under a GUARDED path clears ONLY if the per-file blob sha in the compare is EXACTLY the one
# pinned here (read 17:38 AEST from the #919 head 4736e2277 — its squash on an unmoved M38 yields these blobs). Any other
# blob at that path (a regeneration, a further edit, an L4 #805/#922 squash) is NOT cleared and falls through to GUARDED.
DEV_CONTENT_ALLOWED = {
    D + "services/originate/src/originate.openapi.ts": "509f13abb2910ea51fe1d0093d6268caf579f750",
    D + "docs/openapi/secuura-api.yaml": "8c3df719459a21ecd119aea8ca125130289f7e92",
}
hits = sorted({x["filename"] for x in files for g in GUARDED if x["filename"] == g or (g.endswith("/") and x["filename"].startswith(g))})
by_name = {x["filename"]: x for x in files}
cleared = sorted(h for h in hits if h in DEV_CONTENT_ALLOWED and by_name.get(h, {}).get("sha") == DEV_CONTENT_ALLOWED[h])
remaining = sorted(h for h in hits if h not in cleared)
if remaining:
    print("GUARDED " + " ".join(remaining)); sys.exit(0)
tail = "the gate merges the then-current develop onto 7b6fb960d in its own clone, runs check:openapi on the MERGED tree first (a CHECK FAIL after a clean merge = anchor renumbering = a regenerate-after-squash Record), names the delta and re-derives every count (brief TARGET)"
if cleared:
    print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d, cleared BY BLOB under guarded paths: %s (#919 / KS-739 landed) — %s" % (pinned, cur, c["ahead_by"], len(files), ",".join(x.split("/")[-1] for x in cleared), tail)); sys.exit(0)
print("OK " + state + " | origin develop MOVED %s -> %s: commits=%d files=%d — disjoint from the GUARDED list (services/api-gateway/, originate.openapi.ts, the two verification routes, the yaml, the generator, spec-examples, shared openapi/, the ks860 guard, the lockfile); %s" % (pinned, cur, c["ahead_by"], len(files), tail)); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } (develop $CUR_DEV) — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop is at $CUR_DEV (pinned $DEVELOP_SHA) and the move is not provably disjoint: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher DEVELOP_SHA / JUDGED blobs / DEV_CONTENT_ALLOWED + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 1' "$BRIEF" && grep -q 'TIER 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #813 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#813 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 1 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA813_BRIEF:-}${QA813_PROMPT:-}${QA813_HEAD:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
