#!/bin/bash
# launch_qa_secuura_ks1211_1030.sh — cross-project QA agent, ONE TIER 2 ROUND 1 gate over Secuura/Blockchain PR #1030
# (KS-1211, Seat B, PR-3b: GHSA-82fw-gwwq-j7x9, vitest / @vitest/mocker < 4.1.11, moderate) @ e43af493418a1f13cfb60c994380fb74d79ad07e —
# THREE commits: 17cbb1091 (26 standalone locks + 15 manifests, on 19f1e5475), 566107f01 (a merge of develop 20ab16f9a = #1018 + #1027) and
# e43af4934 (the Blockchain/Dev root lock + the audit-baseline row removed, 32 -> 31). 43 files vs develop: 27 package-lock.json (frontend/issuer,
# the Dev root, 23 services/*, systemTest/api-explorer, systemTest/performance), 15 services/*/package.json, scripts/audit/audit-baseline.json.
#
# THE SHAPE, as read 21:06-21:14 AEST 2026-09-17 (git ls-remote + the PR and compare APIs): head parent 566107f01; merge parents 17cbb1091 +
# 20ab16f9a; origin develop 75ad0e55c (#1026, services/auth oauth.ts + one test — 0 of the 43). compare develop...head = merge_base 20ab16f9a,
# status diverged, ahead 3, behind 1, files 43. Asserted: merge_base + ahead + files (exit 10); behind is NOT asserted.
#
# THE DEVELOP ARM IS JUDGED BY PATH BLOBS, NEVER BY DEVELOP'S SHA (develop moves often). GUARDED PATHS, each read from its parent directory's
# GitHub contents listing at the CURRENT develop (28 listings):
#   (a) the 42 non-audit PR paths: frontend/issuer/package-lock.json; Blockchain/Dev/package-lock.json; services/{analytics, anchoring,
#       api-gateway, auth, billing, demo-service, guardian, kyc, m365-integration, mcp-server, nft-certificate, prism, queue, referral, security,
#       shared, staking, tenant-provisioning, timestamping, tokenisation, transfer, vc-issuer, wallet-connector}/package-lock.json;
#       services/{analytics, guardian, kyc, m365-integration, mcp-server, nft-certificate, prism, queue, referral, security, tenant-provisioning,
#       timestamping, tokenisation, vc-issuer, wallet-connector}/package.json; systemTest/{api-explorer, performance}/package-lock.json;
#   (b) EVERY file of Blockchain/Dev/scripts/audit/ (13 at draft, incl. audit-baseline.json, audit-gate.mjs, audit-locks.mjs, lock-discovery.mjs,
#       baseline-contract.mjs, package.json, package-lock.json); the listing must name exactly these 13.
# Every path at its merge-base blob -> OK (develop's SHA is printed, not judged). ALL 43 PR paths at their #1030 blobs -> exit 19 LANDED.
# Any path at a blob nobody pinned, a file absent, a scripts/audit/ file added or removed, or a PARTIAL landing -> exit 18 GUARDED.
# TEN open Dependabot PRs (#949 #948 #947 #946 #945 #649 #639 #635 #575 #572) touch the root lock (#948, #649, #575 also service manifests):
# one of them landing first REFUSES here by design — re-pin deliberately.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit pane, never inside a
# Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY.
# exit 23: brief AND prompt must carry the exact #1030 verdict subject; the prompt must name coagent@ as sender and wednesday-agent@ as recipient.
# exit 24: brief AND prompt must name the REPORT DIRECTORY; the prompt must name NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM.
# exit 26: the prompt must say Docker is NOT available and require the host load average beside every timed run.
# exit 27: brief AND prompt must carry the TIER 1 TRIGGERED rule (a moved runtime byte is stated, the gate does not silently continue as tier 2).
# QA1030_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED arms and an older develop can be proven.
# A launch with any QA1030_* override set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1030/gen_launcher_1030.py from launch_qa_secuura_ks1211_1027.sh (asserted substitutions + segment
# replacement + pins re-read from the repo + residual guard + output controls + bash -n). Exit codes 2..27 (19 = LANDED).
# Written by the generator because it contains a legitimate directory change.
#
# Usage: launch_qa_secuura_ks1211_1030.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..27 a guard refused
set -u

QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
WED='/Volumes/DevMASTER/WEDNESDAY'
BRIEF="${QA1030_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1030-ks1211-vitest-tier2.md}"
PROMPT_FILE="${QA1030_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1030-ks1211-vitest-tier2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
BRANCH='refs/heads/feature/ks-1211-bump-vitest'
HEAD_SHA="${QA1030_HEAD:-e43af493418a1f13cfb60c994380fb74d79ad07e}"
MERGE_BASE='20ab16f9a80c5c3c75e613d8c670efefd8f5cafb'   # the merge-base of the head with develop = the develop 566107f01 merged in (#1027 squash, on #1018)
DEVELOP_SHA='75ad0e55c6335a5f34f6d0b74dfe00b334b2eb2e'   # develop at draft = #1026 squash (ls-remote 21:06:26 and 21:08:32 AEST) — PRINTED, never a guard
REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1211-1030-e43af4934-tier2-r1/'
SUBJECT='[QA -> Wednesday] TIER 2 GATE #1030 (KS-1211) e43af4934 — '
REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1030-ks1211-vitest-tier2.md"

[ -d "$QA_DIR" ]         || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]          || { echo "brief missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ]    || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]           || { echo "repo under test missing: $REPO" >&2; exit 5; }

# The head, pinned at its branch on origin (one ls-remote at run time).
LSR="$(git -C "$REPO" ls-remote origin "$BRANCH")"
if ! printf '%s\n' "$LSR" | grep -q "^${HEAD_SHA}[[:space:]]${BRANCH}\$"; then
  echo "REFUSING: #1030 — $HEAD_SHA is not at $BRANCH on origin — the head moved; the brief is about a different SHA" >&2
  printf '%s\n' "$LSR" >&2
  exit 6
fi

# The compare (GitHub compare API), asserted whole (merge_base + ahead + files; NOT behind — see the header):
# develop...#1030 = 20ab16f9a ahead 3 files 43 (behind 1 at draft time: #1026 — deliberately not asserted).
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  HEAD_SHA="$HEAD_SHA" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
r = urllib.request.urlopen(urllib.request.Request(api + "develop..." + os.environ["HEAD_SHA"], headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60)
c = json.load(r)
print("%s ahead=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], len(c.get("files") or [])))
PY
)"
[ -n "$COMPARE" ] || { echo "REFUSING: could not read the compare develop...head from the GitHub compare API" >&2; exit 13; }
[ "$COMPARE" = "$MERGE_BASE ahead=3 files=43" ] || { echo "REFUSING: #1030 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=3 files=43'" >&2; exit 10; }

# The develop arm, judged by PATH BLOBS (see the header) — never by develop's SHA, never by a pinned...develop compare.
CUR_DEV="${QA1030_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ -n "$CUR_DEV" ] || { echo "REFUSING: could not read origin develop (git ls-remote)" >&2; exit 18; }
DEV_JUDGEMENT="$(
  set -a; . "$SECUURA_ENV"; set +a
  DEVELOP_SHA="$DEVELOP_SHA" CUR_DEV="$CUR_DEV" python3 - <<'PYJ'
import json, os, sys, urllib.request
t = os.environ.get("GH_TOKEN", "")
api = "https://api.github.com/repos/Secuura/Distributed_Secuura"
def get(p):
    return json.load(urllib.request.urlopen(urllib.request.Request(api + p, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
cur = os.environ["CUR_DEV"]; pinned = os.environ["DEVELOP_SHA"]
D = "Blockchain/Dev/"
# path -> [merge-base blob = develop-OK, the #1030 blob = LANDED]; read by generator from the Secuura checkout with git rev-parse
JUDGED = {
  "Blockchain/Dev/frontend/issuer/package-lock.json": ["b0c47af7144f9228450dc5a82225f742db50b662", "d51db26d56e17dc147e0672c86e1301934503110"],
  "Blockchain/Dev/package-lock.json": ["4831bf2074779139926fbfda3f872c404eba177f", "5bd5680f8ce9853b2fa26778a2609b3d00913b8d"],
  "Blockchain/Dev/services/analytics/package-lock.json": ["9f80f8360e28cea5c77a32bd3da63db7478694ae", "687607af6f23a8d4df98f709c0f99c5356b74878"],
  "Blockchain/Dev/services/analytics/package.json": ["021d2db716b31aa793a6d563fdf139fbc1097170", "50015a885cb4bcfaefa08c770d3bf830642faf07"],
  "Blockchain/Dev/services/anchoring/package-lock.json": ["d97f9d4a3901af861b6f0f628b04e8fbcca03025", "7ef3f65a35b48bec2591df4b2859bab9aa237334"],
  "Blockchain/Dev/services/api-gateway/package-lock.json": ["e0539f24807e0a0ea3cec0f1f6ab6b1689ed0d9a", "5ec55d86d83f93e70dc03676293331fd3bc250e5"],
  "Blockchain/Dev/services/auth/package-lock.json": ["fea21ba1129410dd142992c72760d04c513650a3", "2d91a356aa8426304dc291e0090dbd6893d53c00"],
  "Blockchain/Dev/services/billing/package-lock.json": ["b5c931b3b1c629b1323d90f7efacf5686b9607ca", "4467d01413d80dec5f5fa00afe9080ed7d0f1983"],
  "Blockchain/Dev/services/demo-service/package-lock.json": ["c043455f53353117f49ee5aeaf3dfc4360e436d8", "64b0c9374dbb42054260790f2dfb0df692fdf040"],
  "Blockchain/Dev/services/guardian/package-lock.json": ["12e2f05ffbe669d22bb182d8dd8c3218c8f7e106", "d1cefe1a226b35b74e64ba021ddf793e571d8aa0"],
  "Blockchain/Dev/services/guardian/package.json": ["4a183e0805d017283dae9ffc7df2dca006e144f8", "232c3db77c4e0c65b309965fd2916e32463a3b8c"],
  "Blockchain/Dev/services/kyc/package-lock.json": ["5a94e5b86f59e30f175540bd86243724ab8d8b24", "b96b7a75b81303f10dfb77b863919aa746181a84"],
  "Blockchain/Dev/services/kyc/package.json": ["1d527bede721bee11a6c070d359685439450e3c3", "478b341cecada6850a806562c4ad0f58018b0da7"],
  "Blockchain/Dev/services/m365-integration/package-lock.json": ["48790b38abb619c944dedfbf88df23c568d10c5f", "803ca79bda38706715ee9637adc52bf649345f1e"],
  "Blockchain/Dev/services/m365-integration/package.json": ["6c5d5eacbd5ceaa218e60cf8a1467a620a87e15d", "e21d4cfb525dbe7c994aace244d049c8ffc050da"],
  "Blockchain/Dev/services/mcp-server/package-lock.json": ["f942d659b90b2314ccb5737cb41ecc3c0a70a306", "780b4cbcb86ad9edc285f2efc66cf708a97f092d"],
  "Blockchain/Dev/services/mcp-server/package.json": ["a97eaaab5b029ea2edfeba4bb9db5c83ef20e728", "940a2e70b03e2aa10ef69beafc98c1170366db26"],
  "Blockchain/Dev/services/nft-certificate/package-lock.json": ["8aecebe47450422a9811c883a35c64d0bb8260ad", "c831aee6f5e1ec085bbe5c45bf6c10c2a93528a1"],
  "Blockchain/Dev/services/nft-certificate/package.json": ["713f49bfcf6340bc99904dab9962fa6dba0b950c", "4a3518c211dbcbc82800c551490e002ecfb94d96"],
  "Blockchain/Dev/services/prism/package-lock.json": ["f36bd6d78b689a3ae6ee96139d7cf3d074d78aa3", "0f982cc4464e674c04f7ddbe5da79c2bc4d9a804"],
  "Blockchain/Dev/services/prism/package.json": ["ee3882c83cd967d90bed79434309d49a66a39b3b", "cb7eb842797932bbeb578ca5368c01d939b04583"],
  "Blockchain/Dev/services/queue/package-lock.json": ["01b9cae23c6d39d7895c636859df7f03436ea181", "922cd071d80aa4289eb00ef42a7db35bc282f1a4"],
  "Blockchain/Dev/services/queue/package.json": ["eae15917838d902ddfcab1d0b47b545e6d212c15", "d5652ee9d0b1b3b3c3de1dba2542e72fe41026cd"],
  "Blockchain/Dev/services/referral/package-lock.json": ["725d5d2c21f00e574b2f3986383ca398e322b2aa", "c7bd745800eae211d7fe21d978cd8b316b9f6ba5"],
  "Blockchain/Dev/services/referral/package.json": ["6482d21714eaa92df7a5fc7e8347912eb446c214", "1bc18b51f0ee6100b70ea65ee2610b9bf0220d7f"],
  "Blockchain/Dev/services/security/package-lock.json": ["28622e6f4497e6bde9b023739f9ce23125b51962", "2675691235597a521c8952a5058df29203b4eb8c"],
  "Blockchain/Dev/services/security/package.json": ["467928a30ec608b9e17d4278ec870bfb6217b28a", "a2f2e03ff75b5aba19a9aac97a827cb7a6c50aba"],
  "Blockchain/Dev/services/shared/package-lock.json": ["4de639861560d1a3ff8564e3c76fb1ddaee071e6", "13d6191f30ca150d31b57b3dace52e10f176df40"],
  "Blockchain/Dev/services/staking/package-lock.json": ["cd6450ead247d28236767c2dcf21f63269a87692", "ad74908c566d552972eef88f204e303086f64e18"],
  "Blockchain/Dev/services/tenant-provisioning/package-lock.json": ["c80cd75e7e31764520aac5450775700d93b5df0d", "ec65822f50dc09c844a08726ee96818acadb3a9b"],
  "Blockchain/Dev/services/tenant-provisioning/package.json": ["99cc94a15df9cbabfa53a0eb8bd916afd5ad5cd9", "c5b24fba535b295e16f840dd775a832f8fd03af6"],
  "Blockchain/Dev/services/timestamping/package-lock.json": ["d94f7ab1cc70451a1af43043d85a923f12263dde", "c2f5b451133aef7cb8f00d5e19aba929075d7113"],
  "Blockchain/Dev/services/timestamping/package.json": ["e56992b24e0a924b375b0c8f9bce19fa2099277c", "450cb6dc189a8552eb0923a44a4a7b29d4b1eb69"],
  "Blockchain/Dev/services/tokenisation/package-lock.json": ["ff24651119f0e26c9e7e0af104267cbec830a0f9", "ecb12e1da93ad2d8342096bf5a21dafae9433ddd"],
  "Blockchain/Dev/services/tokenisation/package.json": ["618e68c5f0c77a202dc00479b483574ff8351fe9", "647077b07acceefb8b112b639648cffa1302202a"],
  "Blockchain/Dev/services/transfer/package-lock.json": ["8b364e6a9bb3cd3c259a43130b810be7dacdeaff", "cfaed9c882bcd146cfbb41a1ee7a08d0314dca4f"],
  "Blockchain/Dev/services/vc-issuer/package-lock.json": ["05dff4ebb509fdf2c5605f0e4caa2e16a15bb0b5", "b0b66b5018e556731056875d4c1720945e3478e7"],
  "Blockchain/Dev/services/vc-issuer/package.json": ["98b44b6c9bc95409a834339dda8b14c0f1e51c77", "27888b6eeb6c20b44af947d14eddb3bccf6293cf"],
  "Blockchain/Dev/services/wallet-connector/package-lock.json": ["775df4f92353d8cbc4e219a006a79e1af3597e78", "c7d33bd92a63acf97df48313a502ec9e1a21c136"],
  "Blockchain/Dev/services/wallet-connector/package.json": ["90663e4ffc8722a673e86079c004a83d15847a57", "4f6ef932488fe7719097d46ea78983d4fcca1f21"],
  "systemTest/api-explorer/package-lock.json": ["78589de7e1165c64ef74707fdc75e1515fd6eae5", "544d4fe237b27466e754670dbc45c10d84103f1c"],
  "systemTest/performance/package-lock.json": ["4694ee0a7a8cbc06e9e17c2441f9c535ae8d224c", "91563c0d8df3e13f5cc2cd168425307dfba31107"],
}
# EVERY file of Blockchain/Dev/scripts/audit/ -> [merge-base blob, #1030 blob or empty]; the listing must name exactly these
AUDIT_DIR = "Blockchain/Dev/scripts/audit"
AUDIT = {
  "advisory-fetch-stub.mjs": ["29c9fc48f32857d4f24ef944b9868639e0171435", ""],
  "audit-baseline.json": ["017f52bb5a358e8cae1d25a729c8642d3ed45bc5", "b647dd66e6772720a5252af9370655ceeda2b2b9"],
  "audit-gate.mjs": ["8e236ee70ce1a4634552596fb86fcffce234f221", ""],
  "audit-locks.mjs": ["aff23b0420ced863884787443a35f28cf727bd09", ""],
  "baseline-contract.mjs": ["2504d9a28dc017fcaabfc88248bf1c64431eb38a", ""],
  "baseline-contract.test.mjs": ["2379c0aeee6e3e3f0c4ef3a2512e3a590ad47d29", ""],
  "could-not-check.mjs": ["92eea6087a6c442f1a14e735ba9fcca74493bd0a", ""],
  "expected-case-count": ["04f9fe46068b397a6fc24d647b7e3ec4315c15e7", ""],
  "gate-exit-codes.test.mjs": ["40079f6fb41e146a34a66463e352b9c0a49f91e8", ""],
  "lock-discovery.mjs": ["3dd903b527f26c758cc1da84b10cc0a0db3b1d46", ""],
  "lock-discovery.test.mjs": ["f102d9d4c4523091fe4e3119d6c539fb29bfd904", ""],
  "package-lock.json": ["ffb2b110a2d69c2c9a10e6caf5666c5fa08ec62c", ""],
  "package.json": ["d5977b6a13638558ef57e8c294809d7ada8be6cd", ""],
}
for n, v in AUDIT.items():
    JUDGED[AUDIT_DIR + "/" + n] = v
dirs = sorted({p.rsplit("/", 1)[0] for p in JUDGED})
seen = {}
for d in dirs:
    try:
        listing = get("/contents/" + d + "?ref=" + cur)
    except Exception as e:
        print("UNJUDGEABLE contents listing unreadable for " + d + ": " + type(e).__name__); sys.exit(0)
    for x in listing:
        seen[d + "/" + x["name"]] = x["sha"] if x.get("type") == "file" else "type-" + str(x.get("type"))
    if d == AUDIT_DIR:
        names = sorted(x["name"] for x in listing)
        if names != sorted(AUDIT):
            print("GUARDED develop " + cur[:9] + " scripts/audit/ file set differs from the pin: " + ",".join(sorted(set(names) ^ set(AUDIT)))); sys.exit(0)
landed, unpinned, ok = [], [], 0
for p, (base, own) in JUDGED.items():
    b = seen.get(p, "ABSENT")
    if b == base:
        ok += 1
    elif own and b == own:
        landed.append(p.replace(D, ""))
    else:
        unpinned.append(p.replace(D, "") + " " + b[:9])
owned = sum(1 for v in JUDGED.values() if v[1])
if unpinned or (landed and len(landed) != owned):
    print("GUARDED develop %s: %d guarded path[s] at a blob nobody pinned %s; %d of %d at the #1030 blob" % (cur[:9], len(unpinned), unpinned[:6], len(landed), owned)); sys.exit(0)
if landed:
    print("LANDED develop %s: all %d #1030 blobs present — #1030 has landed; this brief is stale" % (cur[:9], owned)); sys.exit(0)
note = "= the draft pin" if cur == pinned else "MOVED from the draft pin " + pinned[:9] + ", not judged by SHA"
print("OK develop %s %s: %d of %d guarded paths at their merge-base blobs [42 PR paths + all %d files of scripts/audit/], read from %d directory listings" % (cur[:9], note, ok, len(JUDGED), len(AUDIT), len(dirs))); sys.exit(0)
PYJ
)"
case "$DEV_JUDGEMENT" in
  OK*) DEV_NOTE="${DEV_JUDGEMENT#OK }" ;;
  LANDED*) echo "REFUSING: ${DEV_JUDGEMENT#LANDED } — re-pin deliberately: a different brief" >&2; exit 19 ;;
  *) echo "REFUSING: origin develop $CUR_DEV is not provably clean on the guarded paths: ${DEV_JUDGEMENT:-no judgement} — confirm the delta, then re-pin deliberately (launcher JUDGED/AUDIT blobs + brief TARGET + prompt)" >&2
     exit 18 ;;
esac
grep -q 'TIER 2' "$BRIEF" && grep -q 'TIER 2' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the tier" >&2; exit 7; }
grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }
head -1 "$PROMPT_FILE" | grep -q 'ultrathink' || { echo "REFUSING: prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$REAL_BRIEF" "$PROMPT_FILE" || { echo "REFUSING: prompt does not name the brief path" >&2; exit 9; }
grep -qF "$HEAD_SHA" "$PROMPT_FILE" && grep -qF "$HEAD_SHA" "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not name the head SHA $HEAD_SHA — a gate about another SHA is another gate" >&2; exit 20; }
grep -qi 'MAIL YOUR VERDICT' "$PROMPT_FILE" || { echo "REFUSING: prompt does not tell the agent to MAIL its verdict" >&2; exit 12; }
grep -qi 'NEVER run a push, the real pre-push hook, or preflight.sh inside the Secuura checkout' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid pushing / running the hook in the real checkout" >&2; exit 11; }
grep -qi 'no memory maintenance' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid memory maintenance inside the gate session" >&2; exit 14; }
grep -qi 'NEVER print a credential value' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not forbid printing a credential value" >&2; exit 17; }
grep -qi 'farmed per ENTRY' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not require node_modules farmed per ENTRY" >&2; exit 22; }
grep -qF "$SUBJECT" "$PROMPT_FILE" && grep -qF "$SUBJECT" "$BRIEF" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not carry the exact #1030 verdict subject, or the prompt does not name the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" \
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR, or the prompt does not name NOT-TESTED.written-first.md" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM" >&2; exit 25; }
grep -qi 'Docker is NOT available' "$PROMPT_FILE" && grep -qi 'load average' "$PROMPT_FILE" \
  || { echo "REFUSING: prompt does not say Docker is NOT available or does not require the host load average beside timed runs" >&2; exit 26; }
grep -qF 'TIER 1 TRIGGERED' "$PROMPT_FILE" && grep -qF 'TIER 1 TRIGGERED' "$BRIEF" \
  || { echo "REFUSING: brief or prompt does not carry the TIER 1 TRIGGERED rule" >&2; exit 27; }

if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  head on origin: #1030 $HEAD_SHA at $BRANCH"
  echo "  compare (GitHub API): develop...#1030 = $COMPARE"
  echo "  $DEV_NOTE"
  echo "  brief, prompt, QA project and repo all present"
  echo "  brief and prompt agree on TIER 2 and ROUND 1"
  echo "  prompt opens with the thinking directive and names the brief"
  echo "  brief and prompt both name the head SHA"
  echo "  prompt tells the agent to MAIL its verdict"
  echo "  prompt forbids pushing / the real hook / preflight in the Secuura checkout"
  echo "  prompt forbids memory maintenance inside the gate session"
  echo "  prompt forbids printing a credential value"
  echo "  prompt requires node_modules farmed per ENTRY; says Docker is NOT available; requires the host load average beside timed runs"
  echo "  brief and prompt carry the exact verdict subject ($SUBJECT...); prompt names coagent@ -> wednesday-agent@"
  echo "  brief and prompt name the report directory; prompt names NOT-TESTED.written-first.md"
  echo "  brief and prompt carry the MERGE ADDENDUM and the TIER 1 TRIGGERED rule"
  echo "  guarded paths (blobs at the current develop): the 42 non-audit PR paths + every file of Blockchain/Dev/scripts/audit/ (13, incl. audit-baseline.json)"
  [ -n "${QA1030_CUR_DEV:-}" ] && echo "  (develop read from the QA1030_CUR_DEV test override, not ls-remote)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi

[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — this launcher execs an interactive agent; run it in a cockpit pane, never inside a Bash tool (a headless gate is invisible and dies with the caller's shell)" >&2; exit 21; }
[ -z "${QA1030_BRIEF:-}${QA1030_PROMPT:-}${QA1030_HEAD:-}${QA1030_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$DEV_NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions --model opus "$(cat "$PROMPT_FILE")"
