#!/bin/bash
# launch_qa_secuura_batch1338.sh — cross-project QA agent, ONE BATCH gate (gate40, T1) over 1 Secuura/Blockchain PR(s) of round 40, FROZEN at one:
# #1338 KS-1370 (B 42nd (ITEM 1, seat-written, per Kam's rulings (a) on secuura-ks1370-revoke-undone-by-stale-process and (a) on secuura-ks1370-validate-when-the-revoke-check-cannot-read: half (i) validate's usage write is a usage-only UPDATE (dbRecordApiKeyUsage); half (ii) on a cache HIT validate re-reads the stored row through security_find_api_key_by_hash and decides on it — revoke sticky both ways, a vanished row answers Key not found and is evicted, a failed read with a database configured answers 503 'Unable to verify key', memory-only mode answers from memory; #1334's KS 888 validate cells re-pinned), T1)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate40.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-28T23:00:58Z, never adopted
# from a mail. develop at generation 0de108577e6199de3c9402c0643a2944d86aee97; the PRs' merge-bases: 0de108577e6199de3c9402c0643a2944d86aee97 for #1338; END_TREE 4d2c269e338113956b73954bf2164e1140b1fb21.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate40: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate40.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  one rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate40.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at one.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: requirement 1: the real-Postgres drill, RED at base / GREEN at head, controls both ways. exit 41: requirement 2: the stored read as a non-superuser application role. exit 42: requirement 3: both design calls, each with a discriminating arm. exit 43: requirement 4: Kam's split for a failed stored read. exit 44: requirement 5: Kam's KS-888 ruling kept. exit 46: requirement 6: #1334's re-pin read line by line. exit 47: requirement 7: the cross-package guards. exit 48: requirement 8: the gateway's 30 s refusal cache, end to end. exit 49: requirement 9: Tier 1 and the two-NO-GO cap, round 1. exit 50: requirement 10: the GO string, the subject rule, the key scanner. exit 51: the MG-3 key scan. exit 52: the addendum one-line-per-PR shape. exit 53: the Linear link kinds. exit 54: the no-op vs overlap keys. exit 55: the full-disk rule: Data volume, STOP on ENOSPC. exit 35: no Docker / no stack / no TCP port.
# QAB40_CUR_DEV / QAB40_HEAD_<n> / QAB40_PATHS_<n> / QAB40_BRIEF / QAB40_PROMPT: test overrides (--check only); a launch with any QAB40_* set refuses (16).
# Generated by fill_gate40.py at 2026-09-28T23:05:08Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1338.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-29_gate40'
BRIEF="${QAB40_BRIEF:-$GS/mail_gate40_ready.md}"
PROMPT_FILE="${QAB40_PROMPT:-$GS/2026-09-29_secuura-batch1338.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1338|KS-1370|refs/heads/feature/ks-1370-validate-reads-stored-revoke-b42-1|42f8a5abc65ef9a6bc20c07797786089f2b9cd93|3|1|0de108577e6199de3c9402c0643a2944d86aee97|0|Blockchain/Dev/services/security/src/__tests__/ks1370-validate-reads-stored-revoke.test.ts,Blockchain/Dev/services/security/src/__tests__/ks888-failed-mint-save-issues-no-key.test.ts,Blockchain/Dev/services/security/src/index.ts|T1"
)
DEVELOP_SHA='0de108577e6199de3c9402c0643a2944d86aee97'
END_TREE='4d2c269e338113956b73954bf2164e1140b1fb21'
STACKS=''
_ovr() { local v="QAB40_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate40.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 1 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 1 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate40_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB40_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate40.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at one' && has 'T1 ROWS ARE GRADED THROUGH CODE AND AT RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at one" >&2; exit 7; }
for _w in \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.' \
  'Two module instances with separate CJS caches were driven, NOT two OS processes.' \
  'The drill runs as `postgres` (`rolsuper=t`, `rolbypassrls=t`)' \
  'Cell R2 of the KS 888 file is what caught this, and it now passes unchanged' \
  'This is a defensive path, not a live one' \
  'my FIRST green was vacuous' \
  'V2'\''s no-key/no-hash and one-error-line pins are unchanged' \
  '5 declarations = 7 executed cases' \
  'No pin was weakened.' \
  'So half (ii)'\''s extra stored read fires' \
  'at most once per key per 30 s, not once per request.' \
  'Only 5 of the 9 new cells are red-first' \
  'at the base tip (W1 V1 V2 D1 F1)' \
  '26 files / 275 tests, 0 failed' \
  '`tsc -p services/security` — rc 0' \
  'product file restored byte-identical' \
  'The four platform suites were not run: service-internal change, no OpenAPI surface change.' \
  '`usage_count` written from a stale copy is a lost update.' \
  'The log reports the ratio but does not name which three skipped.' \
  'The ticket moved Backlog -> In Progress on its own' \
  'narrowing validate'\''s own call site is the change that leaves revoke intact'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'REAL-POSTGRES-DRILL' \
  'RED-AT-BASE' \
  'GREEN-AT-HEAD' \
  'NON-SUPERUSER-ROLE' \
  'CARVE-OUT-UNDER-FORCE-RLS' \
  'SUPERUSER-IS-BLIND' \
  'STICKY-BOTH-WAYS' \
  'KS888-R2-UNCHANGED' \
  'VANISHED-ROW-EVICTED' \
  'VANISHED-ROW-RESURRECTED-AT-BASE' \
  'EACH-HALF-LOAD-BEARING' \
  'FAILED-READ-503' \
  'MEMORY-ONLY-FROM-MEMORY' \
  'USAGE-WRITE-LOG-ONLY' \
  'NO-KEY-NO-HASH-IN-LOGS' \
  'V2-PINS-UNTOUCHED' \
  'USAGE-UPDATE-UNDER-RLS' \
  'SILENT-ZERO-ROW-UPDATE' \
  'EXECUTE-GRANT-SOURCE' \
  'TWO-PROCESSES' \
  'THE-POSTGRES' \
  'REPIN-LINE-BY-LINE' \
  'WEAKENED-PIN-BLOCKER' \
  'CROSS-PACKAGE-GUARDS' \
  'KS764-GUARD-CALL-SITE' \
  'GATEWAY-REFUSAL-CACHE' \
  'SECURITY-DB-FAULT-END-TO-END' \
  'LOST-UPDATE-CANDIDATE' \
  'SUBJECT-LANDS-AT' \
  'TITLE-LANDS-93' \
  'NOOP-VS-OVERLAP' \
  'NO-FOREIGN-KEY' \
  'ADDENDUM-ONE-LINE-PER-PR' \
  'SECURITY-COUNTS' \
  'SHARED-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'DISK-ENOSPC' \
  'TIER1-CAP-ROUND-1' \
  'TIERING'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'THE REAL-POSTGRES DRILL (#1338; requirement 1' && has 'on a REAL PostgreSQL over a unix socket (no TCP listener, not Docker), RED at the base and GREEN at the head, with controls both ways' && has 'The gate re-derives, it does not trust' || { echo "REFUSING: requirement 1: the real-Postgres drill, RED at base / GREEN at head, controls both ways" >&2; exit 40; }
has 'THE STORED READ AS A NON-SUPERUSER APPLICATION ROLE (requirement 2' && has 'a NOSUPERUSER NOBYPASSRLS application role' && has 'A gate that repeats the superuser drill has not tested the premise' || { echo "REFUSING: requirement 2: the stored read as a non-superuser application role" >&2; exit 41; }
has 'THE TWO DESIGN CALLS, each with a DISCRIMINATING ARM (requirement 3' && has 'revoked if EITHER the in-memory copy or the stored row says revoked' && has 'KS-888 cell R2 must pass unchanged' && has 'a vanished row answers `Key not found` and evicts the cache entry' || { echo "REFUSING: requirement 3: both design calls, each with a discriminating arm" >&2; exit 42; }
has 'KAM'\''S SPLIT FOR A FAILED STORED READ (requirement 4' && has 'a configured database whose read fails -> 503 '\''Unable to verify key'\''' && has 'memory-only mode (isDbAvailable false) answers from memory and still refuses an in-memory revoke' || { echo "REFUSING: requirement 4: Kam's split for a failed stored read" >&2; exit 43; }
has 'KAM'\''S KS-888 RULING KEPT (requirement 5' && has 'a failed usage write is logged once, never refused, no key or hash in any log' && has '(#1334'\''s V2 pins untouched)' || { echo "REFUSING: requirement 5: Kam's KS-888 ruling kept" >&2; exit 44; }
has '#1334'\''s RE-PIN (requirement 6' && has 'the 5 declarations / 7 cases that changed are read LINE BY LINE and judged' && has 'Name any weakened pin as a BLOCKER' || { echo "REFUSING: requirement 6: #1334's re-pin read line by line" >&2; exit 46; }
has 'CROSS-PACKAGE GUARDS (requirement 7' && has '`git grep -l '\''<changed path>'\'' -- '\''*.test.ts'\''`' && has 'plus the packages/shared KS 764 revoke call-site guard, run in the gate' || { echo "REFUSING: requirement 7: the cross-package guards" >&2; exit 47; }
has 'THE GATEWAY'\''S 30 s REFUSAL CACHE (requirement 8' && has 'State what a security-DB fault now does END TO END' || { echo "REFUSING: requirement 8: the gateway's 30 s refusal cache, end to end" >&2; exit 48; }
has 'TIER 1 AND THE TWO-NO-GO CAP (requirement 9' && has 'this is ROUND 1 for this class' || { echo "REFUSING: requirement 9: Tier 1 and the two-NO-GO cap, round 1" >&2; exit 49; }
has 'THE GO STRING AND THE SUBJECT (requirement 10' && has 'the squash subject is declared WITHOUT `(#n)` and checked as declared + " (#1338)" <= 92 chars' && has 'the key scanner over any mandated body' || { echo "REFUSING: requirement 10: the GO string, the subject rule, the key scanner" >&2; exit 50; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'the key scanner over every mandated body' && has 'index.ts carries foreign hyphenated keys as CONTENT' || { echo "REFUSING: the MG-3 key scan" >&2; exit 51; }
has 'THE ADDENDUM IS ONE LINE PER PR in exactly this shape' && has '- #NNNN · head <sha12> · subject: `<subject>`' && has 'NO sub-bullets' || { echo "REFUSING: the addendum one-line-per-PR shape" >&2; exit 52; }
has 'every PR links its ticket as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 53; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 54; }
has 'DISK: /Volumes/DevMASTER is FULL' && has 'STOP on any ENOSPC' && has 'goes on the Data volume' || { echo "REFUSING: the full-disk rule: Data volume, STOP on ENOSPC" >&2; exit 55; }
has 'NO DOCKER, NO STACK, NO TCP PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no TCP port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO (Seat B 42nd): merge 1338 on gate40`' && has 'it is squashed by the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (3 over 3 paths) for #1338' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE40 batch #1338 (Seat B42, round 40; T1: KS-1370 validate reads the stored revoke, both halves)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB40_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 1 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 21 seat items; the prompt carries 39 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / requirement 1: the real-Postgres drill, RED at base / GREEN at head, controls both ways / requirement 2: the stored read as a non-superuser application role / requirement 3: both design calls, each with a discriminating arm / requirement 4: Kam's split for a failed stored read / requirement 5: Kam's KS-888 ruling kept / requirement 6: #1334's re-pin read line by line / requirement 7: the cross-package guards / requirement 8: the gateway's 30 s refusal cache, end to end / requirement 9: Tier 1 and the two-NO-GO cap, round 1 / requirement 10: the GO string, the subject rule, the key scanner / the MG-3 key scan / the addendum one-line-per-PR shape / the Linear link kinds / the no-op vs overlap keys / the full-disk rule: Data volume, STOP on ENOSPC / no Docker / no stack / no TCP port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB40_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
