lineis anchor 124 " * No-ops when the anchor is already \`confirmed\` — never downgrade a recorded"
lineis anchor 142 " * KS-1058: the write REPLACES the blockchain blob (updateDocument spreads"
lineis anchor 146 "export async function markDocumentAnchorFailed("
lineis anchor 152 "  const doc = await getDocument(documentId, tenantId);"
lineis anchor 153 "  if (!doc) return;"
lineis anchor 154 "  if (doc.blockchain?.status === 'confirmed') return;"
lineis anchor 155 "  const prior = doc.blockchain as (typeof doc.blockchain & { threadToken?: unknown }) | undefined;"
lineis anchor 156 "  const revertStatus: DocumentRecord['status'] = doc.signatures?.length ? 'signed' : 'draft';"
lineis anchor 157 "  await updateDocument(documentId, tenantId, {"
lineis anchor 160 "      status: 'anchor_failed',"
lineis anchor 164 "      txHash: prior?.txHash ?? null,"
lineis anchor 165 "      blockHeight: prior?.blockHeight ?? 0,"
lineis anchor 166 "      ...(prior?.network ? { network: prior.network } : {}),"
lineis anchor 170 "      ...(prior?.txHash && prior?.anchoredAt ? { anchoredAt: prior.anchoredAt } : {}),"
lineis anchor 171 "      ...(anchorId ? { anchorId } : {}),"
lineis anchor 182 "      ...(prior?.threadToken ? { threadToken: prior.threadToken } : {}),"
lineis anchor 183 "      error: errorMessage || 'anchor failed on chain',"
lineis anchor 184 "      failedAt: new Date().toISOString(),"
lineis anchor 186 "  }, undefined, { preserveTerminalStatuses: true });"
lineis anchor 314 "export async function reconcileDocumentAnchorState("
lineis anchor 319 "  const bc = document.blockchain;"
lineis anchor 320 "  if (!bc?.anchorId) return document;"
lineis anchor 321 "  if (bc.simulated) return document;"
lineis anchor 329 "  const inFlight = bc.status !== 'anchor_failed' && bc.status !== 'confirmed';"
lineis anchor 330 "  const failed = bc.status === 'anchor_failed';"
lineis anchor 331 "  if (!inFlight && !failed) return document;"
lineis anchor 342 "  if (confirmed && txHash) {"
lineis anchor 358 "  if (inFlight && anchor.status === 'failed') {"
lineis anchor 359 "    await markDocumentAnchorFailed(document.id, tenantId, bc.anchorId, anchor.errorMessage);"
lineis anchor 377 "  const simFields = simulatedFieldsFromAnchor(anchor);"
lineis anchor 378 "  if (inFlight && !bc.txHash && simFields.simulated) {"
lineis anchor 381 "        txHash: null,"
lineis anchor_merge 150 "  errorMessage?: string | null,"
lineis anchor_merge 151 "): Promise<void> {"
lineis anchor_merge 152 "  const doc = await getDocument(documentId, tenantId);"
lineis anchor_merge 153 "  if (!doc) return;"
lineis anchor_merge 154 "  if (doc.blockchain?.status === 'confirmed') return;"
lineis anchor_merge 163 "      // reproduce the previous values exactly for the no-hash case."
lineis anchor_merge 164 "      txHash: prior?.txHash ?? null,"
lineis anchor_merge 165 "      blockHeight: prior?.blockHeight ?? 0,"
lineis anchor_merge 167 "      ...(prior?.anchoredAt ? { anchoredAt: prior.anchoredAt } : {}),"
lineis anchor_merge 168 "      ...(anchorId ? { anchorId } : {}),"
lineis anchor_merge 179 "      ...(prior?.threadToken ? { threadToken: prior.threadToken } : {}),"
lineis anchor_r1 150 "  if (doc.blockchain?.status === 'confirmed') return;"
lineis anchor_r1 151 "  const prior = doc.blockchain;"
lineis anchor_r1 163 "      ...(prior?.anchoredAt ? { anchoredAt: prior.anchoredAt } : {}),"
lineis anchor_r1 164 "      ...(anchorId ? { anchorId } : {}),"
lineis anchor_dev 140 "  if (doc.blockchain?.txHash || doc.blockchain?.status === 'confirmed') return;"
lineis anchor_dev 142 "  const prior = doc.blockchain as (typeof doc.blockchain & { threadToken?: unknown }) | undefined;"
lineis anchor_dev 147 "      txHash: null,"
lineis anchor_dev 148 "      blockHeight: 0,"
lineis anchor_dev 160 "      ...(prior?.threadToken ? { threadToken: prior.threadToken } : {}),"
lineis anchor_dev 300 "  const inFlight = !bc.txHash && bc.status !== 'anchor_failed' && bc.status !== 'confirmed';"
lineis anchor_dev 341 "  if (inFlight && simFields.simulated) {"
lineis ks1004 54 "    blockchain: { txHash: null, blockHeight: 0, status: 'pending', anchorId: 'anchor_1' },"
lineis ks1004 66 "    blockchain: { txHash: REAL_TX, blockHeight: 0, status: 'submitted', anchorId: 'anchor_1' },"
lineis ks1004 89 "  it('REPRO: records the failure on a submitted document carrying a txHash (was: inert)', async () => {"
lineis ks1004 102 "  it('the txHash is CARRIED FORWARD, not nulled — the failed tx keeps its forensic trail', async () => {"
lineis ks1004 114 "    expect(updates.blockchain.txHash).toBe(REAL_TX);"
lineis ks1004 115 "    expect(updates.blockchain.blockHeight).toBe(4242);"
lineis ks1004 116 "    expect(updates.blockchain.network).toBe('preview');"
lineis ks1004 117 "    expect(updates.blockchain.anchoredAt).toBe('2026-02-02T00:00:00.000Z');"
lineis ks1004 120 "  it('CONTROL: a confirmed anchor is still refused — the guard kept its real job', async () => {"
lineis ks1004 125 "    expect(mockUpdateDocument).not.toHaveBeenCalled();"
lineis ks1004 128 "  it('CONTROL: a document with NO txHash still writes null/0, exactly as before', async () => {"
lineis ks1004 136 "  it('CONTRACT: a NO-txHash prior carrying anchoredAt does NOT keep it — an anchor time is retained only alongside a hash', async () => {"
lineis ks1004 151 "    expect('anchoredAt' in updates.blockchain).toBe(false);"
lineis ks1004 153 "    expect(updates.blockchain.status).toBe('anchor_failed');"
lineis ks1004 154 "    expect(updates.blockchain.txHash).toBeNull();"
lineis ks1004 159 "  it('REPRO: a stale submitted-with-hash document whose anchor failed is healed to anchor_failed', async () => {"
lineis ks1004 170 "    expect(updates.blockchain.txHash).toBe(REAL_TX);"
lineis ks1004 182 "  it('REPRO 2: a hashed document could not heal FORWARD either — confirmed now lands', async () => {"
lineis ks1004 192 "    expect(updates.blockchain.status).toBe('confirmed');"
lineis ks1004 197 "  it('CONTROL: an already anchor_failed document is not re-written by the failure branch', async () => {"
lineis ks1004 208 "    expect(mockUpdateDocument).not.toHaveBeenCalled();"
lineis ks1004 211 "  it('CONTROL: the KS-587 simulated-heal leg still requires NO txHash', async () => {"
lineis ks1004 223 "    expect(mockUpdateDocument).not.toHaveBeenCalled();"
lineis ks1058 110 "async function writtenBlobFor(prior: Record<string, unknown>): Promise<Record<string, any>> {"
lineis ks1058 114 "  expect(mockUpdateDocument).toHaveBeenCalledTimes(1);"
lineis ks1058 124 "  it('DEFECT: a prior threadToken survives the anchor_failed write', async () => {"
lineis ks1058 129 "    expect(blob.threadToken).toEqual(THREAD_TOKEN);"
lineis ks1058 136 "  it('CONTRACT: anchoredAt is NOT carried forward — the blob type says it is absent here', async () => {"
lineis ks1058 144 "    expect(blob.anchoredAt).toBeUndefined();"
lineis ks1058 147 "  it('DELIBERATE: confidence is NOT carried forward — it would report a terminal failure as pending', async () => {"
lineis ks1058 157 "    expect(blob.confidence).toBeUndefined();"
lineis ks1058 160 "  it('CONTROL: with no threadToken in the prior blob the written shape is unchanged', async () => {"
lineis ks1058 164 "    expect(Object.keys(blob).sort()).toEqual("
lineis ks1058 165 "      ['anchorId', 'blockHeight', 'error', 'failedAt', 'status', 'txHash'].sort(),"
lineis ks1058 166 "    );"
lineis ks1058 170 "  it('CONTROL (non-zero): the writer still records the failure it is for', async () => {"
lineis ks1058 183 "  it('UNION with KS-1004: a hashed prior IS written — status anchor_failed, txHash and blockHeight carried, threadToken preserved', async () => {"
lineis ks1058 190 "    const blob = await writtenBlobFor({"
lineis ks1058 191 "      txHash: 'd'.repeat(64), blockHeight: 42, status: 'submitted', threadToken: THREAD_TOKEN,"
lineis ks1058 193 "    expect(blob.status).toBe('anchor_failed');"
lineis ks1058 194 "    expect(blob.txHash).toBe('d'.repeat(64));"
lineis ks1058 195 "    expect(blob.blockHeight).toBe(42);"
lineis ks1058 196 "    expect(blob.threadToken).toEqual(THREAD_TOKEN);"
lineis ks535 163 "describe('markDocumentAnchorFailed — never downgrades recorded chain facts', () => {"
lineis ks535 169 "  it('no-ops when the anchor is confirmed — WITHOUT a txHash, so this isolates the confirmed arm', async () => {"
lineis ks535 177 "  it('no-ops on a confirmed anchor even when it also carries a txHash (the original fixture)', async () => {"
lineis ks535 185 "  it('no-ops when the document no longer exists', async () => {"
lineis ks1059 6 " *     if (inFlight && simFields.simulated) {   // anchorStateSync.ts:325 on develop"
lineis ks1059 82 "function terminallyFailedDoc(): DocumentRecord {"
lineis ks1059 95 "      txHash: null,"
lineis ks1059 96 "      blockHeight: 0,"
lineis ks1059 97 "      status: 'anchor_failed',"
lineis ks1059 119 "  it('DEFECT CELL: an anchor_failed document is NOT rewritten to anchored by a simulated anchor', async () => {"
lineis ks1059 133 "    expect(mockUpdateDocument).not.toHaveBeenCalled();"
lineis ks1059 135 "    expect(out.status).toBe('draft');"
lineis ks1059 136 "    expect((out.blockchain as any).status).toBe('anchor_failed');"
lineis ks1059 139 "  it('CONTROL (non-zero): a genuinely in-flight blob with the same simulated anchor IS healed', async () => {"
lineis ks1059 151 "    (doc.blockchain as any).status = 'pending';   // in flight, not terminal"
lineis ks1059 157 "    expect(mockUpdateDocument).toHaveBeenCalledTimes(1);"
lineis ks1059 159 "    expect(updates.status).toBe('anchored');"
lineis ks1059 160 "    expect(updates.blockchain.simulated).toBe(true);"
lineis ks1059 163 "  it('CONTROL: the terminal document is let THROUGH the early returns — it is the sim leg that stops it', async () => {"
lineis ks1059 176 "    expect(mockFetch).toHaveBeenCalledTimes(1);"
lineis ks1059 177 "    expect(String(mockFetch.mock.calls[0][0])).toContain('/api/anchors/anchor_1');"
lineis ks1059 180 "  it('CONTROL: a terminal document whose anchor genuinely confirmed IS still healed forward', async () => {"
lineis ks1059 194 "    expect(mockUpdateDocument).toHaveBeenCalledTimes(1);"
lineis ks1059 196 "    expect(updates.blockchain.status).toBe('confirmed');"
lineis ks1059 197 "    expect(updates.blockchain.txHash).toBe('e'.repeat(64));"
lineis gw 247 "export function confidenceForAnchorStatus("
lineis gw 251 "    case 'confirmed':"
lineis gw 252 "      return 'on-chain';"
lineis gw 256 "    case 'failed':"
lineis gw 257 "      return 'off-chain-only';"
lineis gw 260 "      return 'off-chain-only';"
lineis gw 630 "    const txHash = liveTxHash || persistedTxHash;"
lineis gw 631 "    const blockHeight = liveBlockHeight || persistedBlockHeight;"
lineis gw 633 "    // KS-1057: \`confidence\` used to be keyed on PRESENCE alone — \`txHash &&"
lineis gw 645 "    const liveAnchored = Boolean(liveTxHash && liveBlockHeight);"
lineis gw 681 "    const persistedAnchored = Boolean("
lineis gw 682 "      persistedTxHashIsReal &&           // KS-1069: was \`persistedTxHash &&\`"
lineis gw 683 "      persistedBlockHeightIsHeight &&    // KS-1069: was \`persistedBlockHeight &&\`"
lineis gw 684 "      !persistedDeclaredSimulated &&     // KS-1069: was \`persistedSimulated !== true\`"
lineis gw 685 "      (persistedStatus === 'confirmed' || persistedStatus == null),"
lineis gw 704 "    const confidence: 'on-chain' | 'pending-onchain' | 'off-chain-only' ="
lineis gw 705 "      liveAnchored || persistedAnchored"
lineis gw 706 "        ? 'on-chain'"
lineis gw 707 "        : confidenceForAnchorStatus(persistedStatus) === 'pending-onchain'"
lineis gw 711 "        : 'off-chain-only';"
lineis gw 712 "    const blockchainAnchored = confidence === 'on-chain';"
lineis gw 715 "      verified: !isRevoked && hashValid && blockchainAnchored,"
lineis gw 731 "      blockchain: {"
lineis gw 732 "        anchored: blockchainAnchored,"
lineis gw 733 "        txHash,"
lineis gw 734 "        blockHeight,"
lineis gw 735 "        confidence,"
lineis gw 737 "        source: liveTxHash ? 'cardano-live' : (persistedTxHash ? 'persisted' : 'none'),"
lineis gw_base 513 "    const txHash = liveTxHash || persistedTxHash;"
lineis gw_base 514 "    const blockHeight = liveBlockHeight || persistedBlockHeight;"
lineis gw_base 515 "    const confidence: 'on-chain' | 'pending-onchain' | 'off-chain-only' ="
lineis gw_base 516 "      txHash && blockHeight"
lineis gw_base 517 "        ? 'on-chain'"
lineis gw_base 520 "        : 'off-chain-only';"
lineis gw_base 521 "    const blockchainAnchored = confidence === 'on-chain';"
lineis docrepo 58 "  blockchain?: {"
lineis docrepo 59 "    txHash: string | null;"
lineis docrepo 60 "    blockHeight: number;"
lineis docrepo 61 "    // Absent in the KS-520 fail-closed state — nothing was anchored, so"
lineis docrepo 62 "    // there is no anchor time to record."
lineis docrepo 63 "    anchoredAt?: string;"
lineis docrepo 64 "    network?: string;"
lineis docrepo 65 "    status?: string;"
lineis docrepo 66 "    anchorId?: string;"
lineis ks1057 123 "  originate.listen(0, '127.0.0.1');"
lineis ks1057 136 "  const { createVerificationRoutes } = await import('../routes/verification');"
lineis ks1057 141 "    createVerificationRoutes({"
lineis ks1057 177 "  gateway = app.listen(0, '127.0.0.1');"
lineis ks1057 197 "  const r = await realFetch(\`http://127.0.0.1:\${gatewayPort}/api/documents/\${DOC_ID}/verify\`, {"
lineis ks1057 207 "  it('DEFECT: an anchor_failed blob carrying a hash AND a height must not report on-chain', async () => {"
lineis ks1057 247 "  it('CONTROL (pre-#912 shape): anchor_failed with no hash and zero height stays off-chain', async () => {"
lineis ks1057 258 "  it('CONTROL (non-zero): a confirmed blob still reports on-chain and verified', async () => {"
lineis ks1057 316 "  it('F1 DEFECT: a FAILED anchor reached via tier 2 must not report on-chain', async () => {"
lineis ks1057 357 "  it('REGRESSION: live chain evidence still heals a blob that says anchor_failed', async () => {"
