#!/bin/bash
# launch_qa_secuura_batch1304.sh — cross-project QA agent, ONE BATCH gate (gate32, T2 x6) over 6 Secuura/Blockchain PRs of round 32, FROZEN at six:
# #1304 KS-1227 (B 34th (local-model patch, TEST-ONLY: ks1072 cells edited in place), T2) · #1305 KS-1090 (B 34th (local-model patch, TEST-ONLY: a NEW api-gateway cell, renamed at raise; R2-3, Refs not Closes), T2) · #1306 KS-1205 (B 34th (local-model patch, TEST-ONLY on an AUTH surface: a NEW api-gateway cell; F3), T2) · #1307 KS-1212 (B 34th (local-model patch, TEST-ONLY: a NEW api-gateway cell, renamed at raise), T2) · #1308 KS-1108 (B 34th (local-model patch, TOOLING: systemTest/akto secrets.ts + a NEW akto unit cell carrying a RULED, disclosed 16-line lint departure), T2) · #1309 KS-1196 (B 34th (local-model patch, PRODUCT: api-gateway routes/admin.ts document-type ids to crypto.randomUUID + a NEW cell; the diff REGENERATED by Wednesday), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate32.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-27T11:35:34Z, never adopted
# from a mail. develop at generation a24db57e65c9d0b96e8560ea7feaa0c764dee564; the PRs' merge-bases: 94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812 for #1304, #1305, #1306, #1307, #1308, #1309; END_TREE 977c6a48635341fe9d29f48a0c7e83c843dd9895.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate32: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate32.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  six rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate32.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at six.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the four test-only tamper arms. exit 41: the #1306 auth-bytes rule. exit 42: the #1308 akto row. exit 43: the #1309 product row. exit 44: the READY identity. exit 46: the Linear link kinds. exit 47: the MG-3 key scan. exit 48: the squash-subject rule. exit 49: the no-op vs overlap keys. exit 50: the older-base rule. exit 51: the title-vs-diff rule. exit 35: no Docker / no stack / no port.
# QAB32_CUR_DEV / QAB32_HEAD_<n> / QAB32_PATHS_<n> / QAB32_BRIEF / QAB32_PROMPT: test overrides (--check only); a launch with any QAB32_* set refuses (16).
# Generated by fill_gate32.py at 2026-09-27T11:47:43Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1304.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-27_gate32'
BRIEF="${QAB32_BRIEF:-$GS/mail_gate32_ready.md}"
PROMPT_FILE="${QAB32_PROMPT:-$GS/2026-09-27_secuura-batch1304.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1304|KS-1227|refs/heads/feature/ks-1227-ks1072-witness-hit-only-cell-b34-1|c8233156f0912ec63773e6261cd6926dbce9de7f|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|Blockchain/Dev/services/api-gateway/src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts|T2"
  "1305|KS-1090|refs/heads/feature/ks-1090-r2-3-tsc-wiring-test-b34-2|7aab743e13f45d10a43650e07f25abffccb6441e|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|Blockchain/Dev/services/api-gateway/src/__tests__/ks1090-vouch-reaches-only-originate.test.ts|T2"
  "1306|KS-1205|refs/heads/feature/ks-1205-f3-claim-named-limiter-bucket-b34-3|00180ad72bffdcf917d618b54557a4df90f510c8|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|Blockchain/Dev/services/api-gateway/src/__tests__/ks1205-api-gateway-per-key-limiter-follow.test.ts|T2"
  "1307|KS-1212|refs/heads/feature/ks-1212-erasure-door-casesensitive-cell-b34-4|64d8e398599687b53520bc3710cae6869bdc6b8f|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|Blockchain/Dev/services/api-gateway/src/__tests__/ks1212-erasure-door-reads-its-own-router-case-option.test.ts|T2"
  "1308|KS-1108|refs/heads/feature/ks-1108-akto-secrets-parse-failure-b34-5|f9348a9d10b7512d22a33a0a471f9042ad622831|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|systemTest/akto/src/config/secrets.ts,systemTest/akto/tests/unit/config/ks1108-secrets-parse-failure-prints-no-content.test.ts|T2"
  "1309|KS-1196|refs/heads/feature/ks-1196-admin-doctype-random-uuid-b34-6|f615d12d58d95b01b98816644334cfd06832252d|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|3|Blockchain/Dev/services/api-gateway/src/__tests__/ks1196-admin-post-api-admin-document-types.test.ts,Blockchain/Dev/services/api-gateway/src/routes/admin.ts|T2"
)
DEVELOP_SHA='a24db57e65c9d0b96e8560ea7feaa0c764dee564'
END_TREE='977c6a48635341fe9d29f48a0c7e83c843dd9895'
STACKS=''
_ovr() { local v="QAB32_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate32.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 6 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 6 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate32_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB32_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate32.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at six' && has 'ONE TIER, SIX SHAPES, EACH PR GRADED ON ITS OWN SHAPE' || { echo "REFUSING: the tier definition / FROZEN at six" >&2; exit 7; }
for _w in \
  '1 failed / 7 passed of 8' \
  'the keep-vs-filter decision stays open on the ticket' \
  '2 failed / 2 passed of 4' \
  'the tsconfig half (R2-2) and the record (R2-4) stay open on the ticket' \
  '1 failed / 2 passed of 3' \
  'a tamper inside `rateLimitEnforce.ts` would not red them' \
  'and `erasureDoorCaseSensitive` appears in that file exactly twice' \
  '1 failed / 1 passed of 2' \
  '12 JSDoc, 4 prettier-wrap, 0 other' \
  '`eslint --fix` could not fix it, and made it worse: 5 errors became 6.' \
  'a time-ordered id is no longer monotonic' \
  'a body-supplied `id` would diverge from its catalogue key' \
  '754 passed (754)' \
  '1238 passed (1238)' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'TAMPER-ARMS-4' \
  'ANCHOR-RELOCATED' \
  'KS1205-TAMPER-313' \
  'KS1212-TAMPER-814' \
  'READY-IDENTITY' \
  'GLUED-FENCE' \
  'RENAMED-AT-RAISE' \
  'AUTH-BYTES-UNCHANGED' \
  'AKTO-LINT-RC0' \
  'RULED-DEPARTURE-16' \
  'PRODUCT-HUNK-EXACT' \
  'GIT-APPLY-NOT-PATCH' \
  'REGENERATED-EXACT' \
  'SORT-BY-ID' \
  'CRYPTO-IN-SCOPE' \
  'BODY-ID-DIVERGES' \
  'OLDER-BASE-94C9' \
  'TITLE-VS-DIFF' \
  'SUBJECT-LANDS-AT' \
  'NOOP-VS-OVERLAP' \
  'API-GATEWAY-COUNTS' \
  'AKTO-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'LINT-36-WARNINGS' \
  'BASE-FIGURES-PER-PR' \
  'LOCAL-MODEL-PROVENANCE'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'THE TAMPER ARMS FOR THE FOUR TEST-ONLY CELLS' && has 'A tamper that does not red its declared cell is a FAIL of the arm' && has 'plant a TEST-SIDE tamper of your own' || { echo "REFUSING: the four test-only tamper arms" >&2; exit 40; }
has 'NO AUTH PRODUCT BYTE (#1306; AUTH-BYTES-UNCHANGED)' && has 'middleware/auth.ts blob equal at merge-base, head and END_TREE' || { echo "REFUSING: the #1306 auth-bytes rule" >&2; exit 41; }
has 'THE AKTO ROW (#1308;' && has 'The product hunk must be byte-identical to the golden' && has 'ONLY JSDoc and formatting' || { echo "REFUSING: the #1308 akto row" >&2; exit 42; }
has 'THE PRODUCT ROW (#1309;' && has 'crypto IN SCOPE:' && has 'SORT-BY-ID (Wednesday: the READY left it unmeasured)' || { echo "REFUSING: the #1309 product row" >&2; exit 43; }
has 'READY-IDENTITY: the drafter compared' && has 'carry a glued closing fence' || { echo "REFUSING: the READY identity" >&2; exit 44; }
has 'all six PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'SQUASH SUBJECTS ARE DECLARED WITHOUT THE (#n) SUFFIX' && has 'len(declared) + len(" (#n)") <= 92' && has 'the merge tool refuses a declared subject matching' || { echo "REFUSING: the squash-subject rule" >&2; exit 48; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 49; }
has 'THE OLDER BASE (OLDER-BASE-94C9)' && has 'merge-tree with each PR'\''s own merge-base' || { echo "REFUSING: the older-base rule" >&2; exit 50; }
has 'TITLE-VS-DIFF. Two titles do not describe their diffs' && has 'the gate RULES whether each title describes its diff' || { echo "REFUSING: the title-vs-diff rule" >&2; exit 51; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1304, #1305, #1306, #1307, #1308, #1309 batch`' && has 'so all six are squashed by Seat B 34th, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (8 over 8 paths) for #1304, #1305, #1306, #1307, #1308 and #1309' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE32 batch #1304 #1305 #1306 #1307 #1308 #1309 (Seat B34, round 32; T2 x6: KS-1227, KS-1090, KS-1205, KS-1212, KS-1108, KS-1196)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB32_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 6 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 15 seat items; the prompt carries 26 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the four test-only tamper arms / the #1306 auth-bytes rule / the #1308 akto row / the #1309 product row / the READY identity / the Linear link kinds / the MG-3 key scan / the squash-subject rule / the no-op vs overlap keys / the older-base rule / the title-vs-diff rule / no Docker / no stack / no port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB32_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
