#!/bin/bash
# launch_qa_secuura_batch1245r2-t2.sh — cross-project QA agent, ONE TIER-2 BATCH gate over SEVEN Secuura/Blockchain PRs of round 24 (Seats L6, L5,
# B 28th), FROZEN at seven: #1245 KS-1313 ROUND 2 OF 2 (THE CAP ROUND; LIVE-SHAPE + the must-change list), #1256 KS-1159, #1257 KS-1201, #1258 KS-1296,
# #1259 KS-906, #1260 KS-1139 (sync-secrets.sh NEVER executed, NEVER az), #1261 KS-1293 (THE READER RULE; NODNS-EGRESS measured first).
# Pairwise path-disjoint; NO declared overlap; disjoint from the RUNNING sibling batch gate24T2b. No Docker, no DB, no az.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate24T2c.py, a --no-local scratch clone fetched from origin) at 2026-09-25T18:22:58Z, never adopted
# from a mail. BASE 6e2a00bfed577528de1ee02b41cb5a0e99172b35; develop at generation 4db87c3e4b98b8e366c3dd60d5f399917bad5086 (10 ahead of BASE); END_TREE dfd7f306de8a6d9067b1ee591156eab9b500f0ce;
# END_TREE_NO1245 54cdda7f4bce2ae72779a3f01065c2ffdac33b8e. The compare check is three-dot (develop...head): merge_base, ahead, behind AND the file NAMES, per PR.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate24T2c.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  seven rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate24T2c.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 23: verdict subject / sender.  exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.
# exit 7:  tier lines + FROZEN at seven.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: BASE / develop / END trees in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 34: BASE-INVARIANT + PAIRWISE + NO declared overlap + sibling batch.
# exit 35: NO DOCKER / NO DATABASE.  exit 36: the RED-PROOF rule.  exit 37: the fleet STOP count.  exit 38: LOAD + the anchoring wording.  exit 39: HOLDS.
# exit 40: THE RULE for #1245 (the cap).  exit 41: THE READER RULE.  exit 42: the round-1 MUST-CHANGE list.  exit 43: the REAPER.  exit 44: the declared
# scope.  exit 45: legs 3/4/8 NOT run, owed by none.  exit 46: #1260 never executed, never az.  exit 47: #1261 NODNS-EGRESS measured first.
# QAB24C_CUR_DEV / QAB24C_HEAD_<n> / QAB24C_PATHS_<n> / QAB24C_BRIEF / QAB24C_PROMPT: test overrides (--check only); a launch with any QAB24C_* set refuses (16).
# Generated by fill_gate24T2c.py at 2026-09-25T18:23:29Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1245r2-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-26_gate24T2c'
BRIEF="${QAB24C_BRIEF:-$GS/mail_gate24T2c_ready.md}"
PROMPT_FILE="${QAB24C_PROMPT:-$GS/2026-09-26_secuura-batch1245r2-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)
PRS=(
  "1245|KS-1313|refs/heads/feature/ks-1313-readsuitecounts-label-set-l6-r24-1|65eb964271b0d6895e90fe8f5ffcbbbb9a484050|2|2|6e2a00bfed577528de1ee02b41cb5a0e99172b35|10|systemTest/performance/tests/unit/support/capturedChildOutput.ts,systemTest/performance/tests/unit/utils/unitSuiteSlotIndependence.test.ts"
  "1256|KS-1159|refs/heads/feature/ks-1159-ks1061-guard-blind-spots-r24-d-1|5a41ed7fea96ab77ed1dc263ae0c7d25c9846440|1|1|77c6426b96d9e48a758e68fa56e9138dc8509aa8|8|Blockchain/Dev/services/originate/src/__tests__/ks1061-shared-mock-completeness.test.ts"
  "1257|KS-1201|refs/heads/feature/ks-1201-login-stub-parent-shell-l5-1|d1db0d41ac52359c231cd22abf11124204645d97|1|1|6e2a00bfed577528de1ee02b41cb5a0e99172b35|10|systemTest/__tests__/bootstrap_login_diagnosis.test.sh"
  "1258|KS-1296|refs/heads/feature/ks-1296-pg-isready-missing-binary-l5-1|ff90fbf9d7e351104404e3eaad505a673e656c1e|2|1|6e2a00bfed577528de1ee02b41cb5a0e99172b35|10|Blockchain/Dev/scripts/__tests__/run_migrations_failure_exit_code.test.sh,Blockchain/Dev/scripts/run-migrations.sh"
  "1259|KS-906|refs/heads/feature/ks-906-case6-inert-cd-l5-1|8a2a28f50eb3453db7284da0f098f6a819d40145|1|1|6e2a00bfed577528de1ee02b41cb5a0e99172b35|10|Blockchain/Dev/scripts/__tests__/no_tracked_credentials_root.test.sh"
  "1260|KS-1139|refs/heads/feature/ks-1139-sync-secrets-arith-errexit-l5-1|62e69d23b2507780316f1930123c7d57ebba3ae2|1|1|6e2a00bfed577528de1ee02b41cb5a0e99172b35|10|Blockchain/Dev/deployment/azure/sync-secrets.sh"
  "1261|KS-1293|refs/heads/feature/ks-1293-pin-originate-suite-hermeticity-r24-e-1|eab8d7031b1b19071a66715ca0aabd9c5cb29c6d|1|1|fa25c9b10fb44da6c848a6975d86ebfa523e8602|5|Blockchain/Dev/services/originate/src/__tests__/ks1293-originate-suite-is-hermetic.test.ts"
)
BASE_SHA='6e2a00bfed577528de1ee02b41cb5a0e99172b35'
DEVELOP_SHA='4db87c3e4b98b8e366c3dd60d5f399917bad5086'
DEV_BEHIND='10'
END_TREE='dfd7f306de8a6d9067b1ee591156eab9b500f0ce'
END_TREE_NO1245='54cdda7f4bce2ae72779a3f01065c2ffdac33b8e'
_ovr() { local v="QAB24C_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate24T2c.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 7 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is SEVEN PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate24T2c_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB24C_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate24T2c.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n T2" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n T2'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'TIER 2: THROUGH-CODE' && has 'The batch is FROZEN at seven' || { echo "REFUSING: TIER 2 / FROZEN at seven" >&2; exit 7; }
for _w in \
  '65eb964271b0d6895e90fe8f5ffcbbbb9a484050' \
  '7f3989cd-8428-4868-addb-1f3c465699dc' \
  'S19: a test that logs BOTH a ` Test Files ` line AND a `Tests` line to STDOUT.' \
  'load 5.79 (base at develop `6e2a00bfe`: 63 / 1089 / 0)' \
  'My first E1 applied cleanly and tampered NOTHING' \
  'anchor on the FIRST ` Test Files ` -> ' \
  'cannot see an inline regex creeping back. Neither alone covers the other.' \
  'alternative in your fix list' \
  'but it would be round 3, which the cap forbids' \
  'A TTY child (ANSI is stripped unconditionally, so it cannot reach the parse)' \
  'the 15-leg preflight did NOT run; 12 s, format gate only;' \
  '5a41ed7fea96ab77ed1dc263ae0c7d25c9846440' \
  '6ad49b00-c50d-464e-bcfd-6675011b57a7' \
  'T6b double-quoted   -> NEW guard red · OLD guard blind' \
  'real pre-edit file' \
  'it reported ITSELF' \
  '869/869, 74/74 suites' \
  'The guard still scans THIS service'"'"'s `__tests__` only.' \
  'd1db0d41ac52359c231cd22abf11124204645d97' \
  'ff90fbf9d7e351104404e3eaad505a673e656c1e' \
  '8a2a28f50eb3453db7284da0f098f6a819d40145' \
  '62e69d23b2507780316f1930123c7d57ebba3ae2' \
  '8828f8b1-ab10-4a87-b82c-8b72b2a32571' \
  'a60c002f-f2eb-4055-ae48-145add61769b' \
  '95590d10-4f54-450a-b55e-3b4dbd1c6227' \
  '9698865f-574b-4bf1-848f-23d3cc361977' \
  '#1257 ran 0 of 15 legs, by design' \
  '18/0 green, 16/0 + 4 leaked on the base, 14/4 red' \
  'the errexit DEATH is UNREPRODUCED-ON-THIS-HOST' \
  '#1258: no real PostgreSQL anywhere.' \
  '#1259: CASE 6b compares two cwds, not all of them.' \
  '#1257: the cell counts LISTENERS, not processes' \
  '#1258 is tier 2' \
  'HEAD `3bad652d17cf`' \
  'the log is EMPTY' \
  'RED on the base: 6 passed, 1 failed' \
  'Base suite run in place LEAKS EXACTLY 4' \
  'RED, one call site put back inside `$( )`: 14 passed, 4 failed' \
  'BASE returns non-zero at 8 of 8, HEAD at 0 of 8' \
  'My first CASE 6b could not fail.' \
  'the fleet STOP count does not move' \
  'eab8d7031b1b19071a66715ca0aabd9c5cb29c6d' \
  'c4688275-dab8-47ed-839d-7213ea3acd0d' \
  'A DNS spy cannot distinguish `:1` from `:2`' \
  'the static cell refuses a scan finding fewer than 8' \
  'The two N arms necessarily redden both cells' \
  '871/871, 75' \
  '`*.integration.test.ts` is NOT scanned' \
  '`import * as dns` yields a namespace whose `lookup` is'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'THE CAP ROUND' \
  'SHIPS NOTHING' \
  'DO NOT grade it' \
  'END_TREE_NO1245' \
  'THERE IS NO DECLARED OVERLAP' \
  'THE RUNNING SIBLING BATCH gate24T2b' \
  'LIVE-SHAPE' \
  'KILLED-AFTER-LOOKALIKE' \
  'JOINED' \
  'CALLSITE-STILL-TEXT' \
  'MUST-CHANGE' \
  'T-CALL (i)' \
  'T-CALL (iii)' \
  'T-CALL (iv)' \
  '(E6)' \
  '(H1)' \
  '(H8b)' \
  '(L4)' \
  '(T-210)' \
  '(T-INCLUDES)' \
  'THE READER RULE' \
  'REVERT-SKIPS' \
  'NODNS-EGRESS' \
  'SELF-SCAN' \
  'BACKTICK' \
  'NAMED-FACTORY' \
  'LISTENER-COUNT' \
  'CASE6B-TWO-CWDS' \
  'KS1139-CLOSES?' \
  'STOP-RECORD-OVERWRITTEN' \
  'UNREPRODUCED-ON-THIS-HOST' \
  '(K0)' \
  '(K2)' \
  '(M0)' \
  '(W0)' \
  '(A0)' \
  '(A1)' \
  'arms1293.py' \
  'arms1159.py' \
  'tamper1313r2.sh' \
  '--no-file-parallelism' \
  '--runInBand' \
  '--json' \
  'shellcheck' \
  'NOT INSTALLED' \
  'KNIP-DELTA' \
  'TYPECHECK AND LINT DELTA' \
  'TS2322' \
  'prettier --check' \
  'PACKAGE SUITES, BEFORE / AFTER' \
  'exits 127' \
  'the one allowed standalone run' \
  'NOT-FOUND control' \
  'NO DOCKER, NO DATABASE' \
  'LOAD (standing' \
  'KS-1155' \
  'LOGIN_STUB REAPER — YOUR OWN ONLY' \
  'LEADS for you to grade' \
  'BY-NAME ITEMS' \
  'CENSUS v2' \
  'LINEAR LINK HYGIENE' \
  'MERGE ADDENDUM' \
  'MG-1' \
  'MG-3' \
  'MG-11' \
  'STAYS In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'CARRY-FORWARD' \
  'READ THE WHOLE TEST FILES' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'NEVER a fetch into it' \
  'Never enter any seat worktree' \
  '.push-lock-24' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'never print a credential value' \
  'No memory maintenance' \
  'Datasec files and mail are out of scope entirely' \
  'EVIDENCE CLASS' \
  'NOT-TESTED.written-first.md' \
  'THE CONTEXT RULE' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '2026-09-26-batch1245r2-t2c' \
  'the merging seat re-predicts' \
  'HOLDS (standing)' \
  'mail_gate24T2c_ready.md' \
  'COMMISSION.md' \
  'liveshape_2.out' \
  'predict_5/6/7.out' \
  '2026-09-26-batch1243-t2a' \
  'KS-1201' \
  'STREAM-SEPARATED' \
  'PRESUITE-URLPATH' \
  'COLD CACHE' \
  'INERT TAMPER' \
  'GO WITH FINDINGS' \
  'no `timeout` binary' \
  'absolute paths only' \
  'no PIPESTATUS' \
  '${A[@]+"${A[@]}"}'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'a sibling batch merging is not a difference' && has 'THERE IS NO DECLARED OVERLAP in this batch' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' && has 'THE RUNNING SIBLING BATCH gate24T2b' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE / no-declared-overlap / sibling-batch rule" >&2; exit 34; }
has 'NO DOCKER, NO DATABASE — none is needed' && has 'NEVER connect to it' && has 'NO Docker action of any kind' || { echo "REFUSING: the NO DOCKER / NO DATABASE rule" >&2; exit 35; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' && has 'an INERT TAMPER' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has 'THE FLEET STOP COUNT: CLAIMABLE BY READ FOR FIVE, NOT FOR #1245 OR #1257' && has 'was OVERWRITTEN by the seat' && has 'THE FLEET STOP after this merge is READ FROM THE DEVELOP IT LANDS ON' && has 'NO STANDALONE RUN of' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'A WRONG READING ON ANY REAL SHAPE = NO GO for #1245 (blocking)' && has 'AT THE CAP A NO GO SHIPS NOTHING and the residue is ticketed by Wednesday' && has 'THROUGH THE REAL CODE PATH — never a lifted regex, never a re-implementation, never a Python port — with the two streams SEPARATE' && has 'do not soften the rule yourself' || { echo "REFUSING: THE RULE for #1245" >&2; exit 40; }
has 'THE READER RULE (the gate'"'"'s, for every other PR' && has 'the PR'"'"'s own commit / cell text NAMES it as a shape the check catches' && has 'A WRONG READING ON ANY REAL SHAPE = NO GO for that PR (blocking)' || { echo "REFUSING: THE READER RULE" >&2; exit 41; }
has 'THE ROUND-1 MUST-CHANGE LIST' && has 'T-CALL (iii) SHOULD NOW RED (graded MINOR, NON-BLOCKING' && has 'the {3,2} row present' || { echo "REFUSING: the round-1 MUST-CHANGE list" >&2; exit 42; }
has 'never by name, never pid 1' && has 'report the count before / after' || { echo "REFUSING: the LOGIN_STUB REAPER rule" >&2; exit 43; }
has 'DECLARED SCOPE (grade as disclosed scope, never as a defect of the PR)' || { echo "REFUSING: the declared scope" >&2; exit 44; }
has 'Legs 3/4/8 are NOT RUN in this gate and OWED BY NONE' || { echo "REFUSING: legs 3/4/8 NOT run, owed by none" >&2; exit 45; }
has 'NEVER EXECUTE sync-secrets.sh AND NEVER RUN `az`' && has 'an `az` shim FIRST on PATH that logs every call' && has 'the log MUST stay EMPTY' || { echo "REFUSING: #1260 never executed / never az" >&2; exit 46; }
has 'NODNS-EGRESS (#1261; MEASURE before you run #1261'"'"'s cells)' && has 'READ /etc/hosts' || { echo "REFUSING: #1261 NODNS-EGRESS measured first" >&2; exit 47; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1245, #1256, #1257, #1258, #1259, #1260, #1261 batch`' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (2 over 2 paths) for #1245 and #1258, (1 over 1 path) for #1256, #1257, #1259, #1260 and #1261' && has 'KEY-FREE' && has 'subject <= 92 chars' && has 'FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 GATE batch #1245r2 #1256 #1257 #1258 #1259 #1260 #1261 (Seats L6 L5 B28, round 24)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$BASE_SHA" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" && grep -qF -- "$END_TREE_NO1245" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the END trees not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of BASE $BASE_SHA); heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE"
_ANY_OVR="$(env | grep -c '^QAB24C_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; seven rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 49 seat items; the prompt carries 105 by-name keywords and the base-invariant+pairwise+sibling / no-docker / red-proof / fleet-STOP / load+anchoring / holds / THE RULE (cap) / READER RULE / MUST-CHANGE / reaper / scope / legs-3/4/8 / never-az / NODNS-EGRESS rules, the GO string, the addendum rules, the verdict subject, BASE / develop / both END trees in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB24C_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
