#!/bin/bash
# launch_qa_secuura_batch1349.sh — cross-project QA agent, ONE BATCH gate (gate47, round 47) over TWO Secuura/Blockchain PRs, FROZEN at TWO:
# #1349 KS-1374 (T2, systemTest-only; the hook skipped its preflight) · #1350 KS-1054 (T1, a deploy-path RUNTIME change). Merge order 1349 1350.
# Author and merger: Seat B 46th. Each PR is ROUND 1 of its own PR.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate47.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-29T14:11:18Z.
# develop a72149a1a803d802430568254e7fa9afa7029321; END_TREE 6930599560c93f3a6cd929cc634b537a2eeb2eaf (the two squashes chained in order; the reverse order gives the same tree). Shape copied from the
# gate47 launcher, re-keyed for gate47 (two rows, as gate44 / gate45).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  a head is not at its branch AND refs/pull/<n>/head on origin.   exit 8: thinking directive / capture + commission + Linear read + drafted texts + gate47 report named / an unfilled token / row count.
# exit 10: a GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name every head in full.   exit 7: the tier lines + FROZEN at TWO + ROUND 1 + the tiering rule.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state the tickets.   exit 33: the by-name keyword ladder (each keyword AS A TOKEN).   exit 39: the HOLDS.
# exit 26: merge authority + the GO string.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST (nothing into report.md after the mail).   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G47_* test override set.
# G47_CUR_DEV / G47_HEAD_<n> / G47_PATHS_<n> / G47_BRIEF / G47_PROMPT: test overrides (--check only).
# Generated by fill_gate47.py at 2026-09-29T14:50:26Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1349.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-30_gate47'
BRIEF="${G47_BRIEF:-$GS/mail_gate47_ready.md}"
PROMPT_FILE="${G47_PROMPT:-$GS/2026-09-30_secuura-batch1349.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1349|KS-1374|refs/heads/feature/ks-1374-pace-by-scanned-target-b46-1|daab8ff3bff564ee89d4e03cb36a9af04d9b4c9e|2|1|8c810023f9c9ac060a7aff24f0933ae3b8734479|1|systemTest/akto/src/setup/aktoRateLimit.ts,systemTest/akto/tests/unit/setup/ks1374-n1347-11-scan-target-override.test.ts|T2"
  "1350|KS-1054|refs/heads/feature/ks-1054-skipped-check-stops-reading-as-a-pass-b46-2|8f4f0ef1496304cc853532b686e92bb886fa027d|4|1|a72149a1a803d802430568254e7fa9afa7029321|0|Blockchain/Dev/deployment/azure/check-startup-migrations.sh,Blockchain/Dev/deployment/azure/deploy-all.sh,Blockchain/Dev/deployment/azure/deploy.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_scripts_read_startup_migrations.test.sh|T1"
)
DEVELOP_SHA='a72149a1a803d802430568254e7fa9afa7029321'
END_TREE='6930599560c93f3a6cd929cc634b537a2eeb2eaf'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate47.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is TWO PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate47_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" && grep -qF "$GS/linear_gate47.md" "$PROMPT_FILE" && grep -qF "$GS/drafted_texts_gate47.md" "$PROMPT_FILE" && grep -qF "2026-09-29-batch1348r2-g46/report.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture, the Linear read, the commission, the drafted texts at $GS and the previous round report" >&2; exit 8; }
[ -s "$GS/linear_gate47.md" ] && grep -qF "b82bebb3" "$GS/linear_gate47.md" && grep -qF "dc9212b5" "$GS/linear_gate47.md" && grep -qF -- "- [ ] **N-1347-11" "$GS/linear_gate47.md" || { echo "REFUSING: the Linear read $GS/linear_gate47.md is missing, empty, or lacks the raise comment b82bebb3 / dc9212b5 / the UNTICKED N-1347-11 checklist line" >&2; exit 8; }
[ -s "$GS/overlap_probe_1.out" ] && grep -qF "$GS/overlap_probe_1.out" "$PROMPT_FILE" || { echo "REFUSING: the out-of-kit overlap probe $GS/overlap_probe_1.out is missing or not named in the prompt" >&2; exit 8; }
[ -s "$GS/drafted_texts_gate47.md" ] && grep -qF "N-1347-11 — the residue of the target-keyed pacing" "$GS/drafted_texts_gate47.md" && grep -qF "live sweep owed" "$GS/drafted_texts_gate47.md" || { echo "REFUSING: the drafted texts $GS/drafted_texts_gate47.md are missing or lack one of the two texts" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + every branch + every pull/head
CUR_DEV="${G47_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate47.sh (it re-pins and re-fills in one action)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G47_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G47_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
for _kt in 'PR #1349 is KS-1374' 'PR #1350 is KS-1054'; do
  has "$_kt" && grep -qF -- "${_kt#PR }" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state '$_kt'" >&2; exit 32; }
done
has '#1349 T2' && has '#1350 T1' && has 'The batch is FROZEN at TWO PRs' && has 'TIER 1 = FULL WEIGHT' && has 'TIER 2 = THROUGH-CODE ONLY' && has 'a DEPLOY-PATH RUNTIME change' && has 'ROUND 1 of its own PR' && has 'a round-1 NO GO goes back to the author for round 2' && has 'ship the closed instances, ticket the residue' || { echo "REFUSING: the tier lines / FROZEN at TWO / ROUND 1 / the tiering rule" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control" >&2; exit 33; }
for _w in HOOK-SKIPPED-LEGS-1349 FORMAT-GATE-1349 AUDIT-LEGS-1349 AUDIT-BASELINE-CLEANUP-NOTE SUITE-1349 RED-FIRST-1349 TAMPER-1349 NUMBERS-FROM-CODE-1349 NOT-COVERED-1349 SUITE-1350-MACOS SUITE-1350-GNU RED-FIRST-1350 RED-AT-BASE GREEN-AT-HEAD CALLER-CELLS-1350 ABSENT-STILL-PASSES-1350 N-1348-6-BOTH-WAYS R8-EXECUTES PYTHON3-ABSENT-FAILS-CLOSED N-1348-7-COMMENT-FIXED OTHER-CALLERS-1350 TAMPER-ARMS-1350 TAMPER-UNIQUE-ANCHOR TAMPER-RIGHT-REASON RESTORE-SHA256 DEPLOY-PATH-TABLE-1350 EMPTY-NONJSON-DIVERGENCE N-1346-9-OUT-OF-SCOPE CLEAN-MERGE END-TREE OVERLAP-MEASURED MODES OUT-OF-KIT-1351 DRAFTED-COMMENTS-CHECKED DRAFT-POST-TIMING CENSUS-TESTS-RUN CENSUS-LISTED SUBJECT-KEY-SCAN SUBJECT-LANDS-AT SUBJECT-TRUE-OF-DIFF REFS-OWN-KEY NO-CLOSING-KEYWORD PR-BODY-CLAIMS HOOK-LINE-CITE WHOLE-SUITE-BEFORE-AFTER NO-NEW-RED SUITES-AT-END CLASS-ROUND-1349 TIERING DISK-ENOSPC REPORT-HASH-LAST; do   # AS A TOKEN: bounded by a non-[A-Za-z0-9-] character (MODES is not satisfied by MODES-X)
  printf '%s' "$PROMPT_JOINED" | grep -qE -- "(^|[^A-Za-z0-9-])$_w([^A-Za-z0-9-]|\$)" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' && has 'Never read or write a real `.env`' && has 'Docker runs are `--rm --network none` with the source mounted READ-ONLY' && has 'NO checklist tick' && has 'no Akto scan against any stack' && has 'No audit-baseline row edited' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the heads" && has 'GO (Seat B 46th): merge 1349 1350 on gate47' && has 'The merge seat is Seat B 46th' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after these merges' && has 'MG-1 6 over 6 paths' && has 'MODE deploy.sh 100755 check-startup-migrations.sh 100755 deploy-all.sh 100755' && has 'drafted texts: KS-1374' && has 'TRUE of its diff' && has 'EVERY SUBJECT YOU PROPOSE MUST BE TRUE OF THE DIFF' && has 'is the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE47 #1349 #1350 (Seat B46 author and merger, round 47; T2: KS-1374 pace keyed on the scan target; T1: KS-1054 a skipped migration check stops reading as a pass)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-09-30-batch1349-g47/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G47_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-400
  echo "  capture, Linear read, drafted texts, prompt, QA project and repo present; kit at its filled home; TWO rows; thinking directive; capture + Linear read (b82bebb3, dc9212b5, N-1347-11 unticked) + drafted texts + commission + gate46 report named; no unfilled token"
  echo "  2 of 2 heads at branch AND pull/head (whole-field); 2 of 2 GitHub compares == the pins; capture and prompt BOTH carry every head in full and both tickets"
  echo "  the prompt carries 51 by-name keywords (as tokens), the tier lines, the holds, the GO string, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G47_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
