#!/bin/bash
# launch_qa_secuura_batch1348.sh — cross-project QA agent, ONE BATCH gate (gate45, round 45) over TWO Secuura/Blockchain PRs, FROZEN at TWO:
# #1348 KS-1054 (T1, a deploy-path change) · #1347 KS-1374 (T2, ROUND 2 OF 2). Merge order 1348 1347. Author and merger: Seat B 45th.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate45.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-29T11:07:11Z.
# develop 8ba2da02d980e7e8065e8ce614b034adc2b7c2eb; END_TREE 9222b67ef2039327a9debfb25a652c1bbf7e8fc8 (the two squashes chained in order). Shape copied from the gate44 launcher (two rows), re-keyed for gate45.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  a head is not at its branch AND refs/pull/<n>/head on origin.   exit 8: thinking directive / capture + commission named / an unfilled token / row count.
# exit 10: a GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name every head in full.   exit 7: the tier lines + FROZEN at TWO.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state the tickets.   exit 33: the by-name keyword ladder.   exit 39: the HOLDS.
# exit 26: merge authority + the GO string.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST (nothing into report.md after the mail).   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G45_* test override set.
# G45_CUR_DEV / G45_HEAD_<n> / G45_PATHS_<n> / G45_BRIEF / G45_PROMPT: test overrides (--check only).
# Generated by fill_gate45.py at 2026-09-29T11:13:48Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1348.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-29_gate45'
BRIEF="${G45_BRIEF:-$GS/mail_gate45_ready.md}"
PROMPT_FILE="${G45_PROMPT:-$GS/2026-09-29_secuura-batch1348.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1348|KS-1054|refs/heads/feature/ks-1054-deploy-sh-exits-non-zero-on-failed-migrations-b45-2|1bb58b4ebb97d2fa9f04bddd961ad499b6106e09|2|1|8ba2da02d980e7e8065e8ce614b034adc2b7c2eb|0|Blockchain/Dev/deployment/azure/deploy.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_scripts_read_startup_migrations.test.sh|T1"
  "1347|KS-1374|refs/heads/feature/ks-1374-local-templates-10000-and-akto-reads-platform-b45-1|18bc5123ce90b4c2cf2a9b22f141e1c2b81083c0|6|2|bd740147c3d88fbf45af109fd68fd35f602c2914|1|Blockchain/Dev/.env.example,Blockchain/Dev/docker-compose.yml,Blockchain/Dev/env.example,Blockchain/Dev/services/api-gateway/src/__tests__/ks1374-global-limiter-at-demo-limit.test.ts,systemTest/akto/src/setup/aktoRateLimit.ts,systemTest/akto/tests/unit/setup/ks1374-platform-limit-from-env.test.ts|T2"
)
DEVELOP_SHA='8ba2da02d980e7e8065e8ce614b034adc2b7c2eb'
END_TREE='9222b67ef2039327a9debfb25a652c1bbf7e8fc8'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate45.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is TWO PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate45_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" && grep -qF "$GS/linear_gate45.md" "$PROMPT_FILE" && grep -qF "$GS/drafter_return_probe.out" "$PROMPT_FILE" && grep -qF "2026-09-29-batch1346-g44/report.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture, the Linear read, the commission, the drafter probe at $GS and the previous round report" >&2; exit 8; }
[ -s "$GS/linear_gate45.md" ] && grep -qF "dc9212b5" "$GS/linear_gate45.md" || { echo "REFUSING: the Linear read $GS/linear_gate45.md is missing, empty or lacks the second correction dc9212b5" >&2; exit 8; }
[ -s "$GS/drafter_return_probe.out" ] || { echo "REFUSING: the drafter probe $GS/drafter_return_probe.out is missing" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + every branch + every pull/head
CUR_DEV="${G45_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate45.sh (it re-pins and re-fills in one action)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G45_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G45_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
for _kt in 'PR #1348 is KS-1054' 'PR #1347 is KS-1374'; do
  has "$_kt" && grep -qF -- "${_kt#PR }" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state '$_kt'" >&2; exit 32; }
done
has '#1348 T1' && has '#1347 T2' && has 'The batch is FROZEN at TWO PRs' && has 'TIER 1 = FULL WEIGHT' && has 'TIER 2 = THROUGH-CODE ONLY' && has 'a DEPLOY-PATH change' && has 'KS-1374 ROUND 2 OF 2' && has 'a NO GO on #1347 ships NOTHING' || { echo "REFUSING: the tier lines / FROZEN at TWO / the round-2-of-2 cap" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control" >&2; exit 33; }
for _w in RED-AT-BASE GREEN-AT-HEAD TAMPER-RIGHT-REASON TAMPER-UNIQUE-ANCHOR RESTORE-SHA256 WHOLE-SUITE-BEFORE-AFTER NO-NEW-RED TSC-BEFORE-AFTER SUITES-AT-END CENSUS-TESTS-RUN CENSUS-LISTED SUBJECT-KEY-SCAN SUBJECT-LANDS-AT SUBJECT-TRUE-OF-DIFF REFS-OWN-KEY NO-CLOSING-KEYWORD END-TREE MERGE-ORDER-T1-FIRST OVERLAP-MEASURED CLEAN-MERGE-1347-OVER-8BA2 MODE-100755-RECORDED-1348 E1-RED-AT-BASE-1348 E2-CLEAN-DEPLOY-RETURNS-0-1348 TAMPER-UNCONDITIONAL-RETURN-1348 TAMPER-RETURN-0-1348 E-DRIVER-TOPLEVEL-RETURN-1348 MKTEMP-GNU-1348 DEPLOY-SH-VERIFY-DRIVEN-1348 DEPLOY-SERVICES-TAIL-1348 SET-E-CALL-SITES-1348 ERR-TRAP-LINE-1348 BEHAVIOUR-WIDER-THAN-MIGRATIONS-1348 RULING-A-BOTH-SCRIPTS-1348 NAMED-NOT-FIXED-1348 GATE44-FINDINGS-ROWS-1347 RED-FIRST-ROUND1-N-1347-1 RED-FIRST-ROUND1-N-1347-3 NONLOCAL-RAISED-ENV-LE-1500-1347 LOCAL-7500-1347 LOCAL-HOST-FORMS-1347 OVERRIDE-APP-URL-1347 DOTENV-ORDER-TARGET-1347 OVERRIDE-NAME-ABSENT-1347 CI-TEST-ASSUMES-2000-1347 COMPOSE-COMMENT-1347 ENV-EXAMPLE-2000-1347 SECOND-CORRECTION-LINES-1347 PR-BODY-STALE-1347 AKTO-OWN-NPM-CI-1347 ROUND-2-OF-2-CAP-1347 DISK-ENOSPC TIERING REPORT-HASH-LAST; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' && has 'Never read or write a real `.env`' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the heads" && has 'GO (Seat B 45th): merge 1348 1347 on gate45' && has 'The merge seat is Seat B 45th' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after these merges' && has 'MG-1 8 over 8 paths' && has 'MODE deploy.sh 100755' && has 'TRUE of its diff' && has 'EVERY SUBJECT YOU PROPOSE MUST BE TRUE OF THE DIFF' && has 'is the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE45 batch #1348 #1347 (Seat B45, round 45; T1: KS-1054 deploy.sh exits non-zero on verify issues; T2: KS-1374 round 2 of 2)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-09-29-batch1348-g45/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G45_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-400
  echo "  capture, Linear read, prompt, QA project and repo present; kit at its filled home; TWO rows; thinking directive; capture + Linear read (with dc9212b5) + commission + drafter probe + previous round report named; no unfilled token"
  echo "  2 of 2 heads at branch AND pull/head (whole-field); 2 of 2 GitHub compares == the pins; capture and prompt BOTH carry every head in full and the tickets"
  echo "  the prompt carries 53 by-name keywords, the tier lines, the holds, the GO string, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G45_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
