#!/usr/bin/env python3
"""make_readme_gate42.py <scratchpad> — writes README.md for gate42 (the directory this script lives in). Every figure is READ from the kit's own output
files at the moment it runs (pins_gate42.json, predict_1.out, predict_sim_*.out(.rc), installprobe_gate42.json, fill_1.out, keyscan_1.out, rekey_1.out,
launcher_check_1.out, repin_dryrun_N.out, controls_1.out / controls_2.out (+ .rc), controls_sha.txt, final_lsremote_1.out), each named beside it; the
prose (doubts, fixes) is the drafter's. Shape copied from gate41's make_readme (gate40 -> gate39 lineage), re-keyed to gate42 (#1339 ROUND 2 OF 2). The
README ENDS with §8, the ONE launch command; its argument 2 is the EXISTING scratchpad passed here."""
import json, os, re, glob, hashlib, datetime, sys
D = os.path.dirname(os.path.abspath(__file__)); K = json.load(open(D + '/kit.json')); kit = K['kit']
SP = sys.argv[1] if len(sys.argv) > 1 else ''
if not (SP.startswith('/private/tmp/claude-501/') and '/scratchpad' in SP and os.path.isdir(SP)): sys.exit('usage: make_readme_gate42.py <an EXISTING scratchpad dir under /private/tmp/claude-501/*/scratchpad*> (argument 2 of the launch command)')
P = json.load(open('%s/pins_%s.json' % (D, kit))); IP = json.load(open('%s/installprobe_%s.json' % (D, kit)))
def rd(f): return open(os.path.join(D, f), encoding='utf-8').read() if os.path.exists(os.path.join(D, f)) else ''
def last(f, rx):
    m = [l for l in rd(f).splitlines() if re.search(rx, l)]; return m[-1].strip() if m else 'ABSENT'
def rc(f): return rd(f).strip() or '?'
def strip(s): return re.sub(r'^(PASS )?#1339 ', '', s)
def j(x): return json.dumps(x, ensure_ascii=False, default=str)
DRY = sorted(glob.glob(D + '/repin_dryrun_[0-9]*.out'), key=lambda f: int(re.search(r'_(\d+)\.out$', f).group(1)))
DRYF = os.path.basename(DRY[-1]) if DRY else 'repin_dryrun_1.out'
fill = rd('fill_1.out'); now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
L = os.path.join(D, K['launcher']); PR = os.path.join(D, K['prompt']); CAP = os.path.join(D, 'mail_%s_ready.md' % kit)
def sz(p): b = open(p, 'rb').read(); return '`%s` %d bytes sha256 `%s`' % (os.path.basename(p), len(b), hashlib.sha256(b).hexdigest())
SU = IP['_summary']
sims = {os.path.basename(f)[len('predict_sim_'):-len('.out')]: (rc(os.path.basename(f) + '.rc'), last(os.path.basename(f), r'^(PASS|REFUSED):')[:60]) for f in sorted(glob.glob(D + '/predict_sim_*.out'))}
fl = rd('final_lsremote_1.out').strip().replace('\n', ' | ')
n = '1339'; pr = P['prs'][n]; R1 = K['round1_head']
cur = pr['head'] in fl and P['develop'] in fl
CH, CD = 'fa93ff88f47e', '8af6ab821600'   # the prefixes Wednesday's gate42 commission named ("re-read it by `git ls-remote` before you trust it")
launch = '%s/repin_and_launch_%s.sh %s %s' % (D, kit, L, SP)
m = re.search(r'#%s (\d+)->(\d+)' % n, fill)
subj = 'declared %s, lands at %s' % (m.group(1), m.group(2)) if m else '?'
CZ = P['measured'][n]['census']
ntests = len({x for v in CZ['exact'].values() for x in v} | set(CZ['broad']) | set(CZ['email_importers']['services/auth']) | set(CZ['email_importers']['services/originate']))
out = ['# Gateset 2026-09-29_gate42 — README for Wednesday', '',
 'Written %s by the drafter (make_readme_gate42.py; every figure below is read from the kit\'s own output files at that moment, each named beside it).' % now,
 'The drafter launched nothing, sent no mail, tapped no pane, merged nothing, committed nothing, pushed nothing, posted nothing, changed no ticket or PR and deleted nothing. It wrote this kit directory (TEXT files only) and scratch on the DATA volume under its own session scratchpad (`g42_sp/clone.git` — `git clone --bare --shared --no-checkout` of the checkout, fetched FROM ORIGIN with the checkout\'s repo-local key, a read of the checkout\'s objects only; the standalone installs and builds under `g42/ip/` — earlier drafting runs MOVED aside as `*.prevN`, never removed — and their npm cache `g42/npmcache`; the control workdirs `g42_controls_*`; drafting patch scripts under `g42_sp/patches/`). Superseded fill outputs (`*.pre-HHMMSS`) were MOVED to `_quarantine_2026-09-29/` in this kit, not deleted. It did NOT write the routing line (§4).',
 'The Secuura checkout was touched only by read verbs (ls-remote, `config --get`, and `clone --shared` as a source). Seat B 44th\'s record folder and session scratchpad and Seat B 43rd\'s handover were READ. GitHub: REST GET only. Linear: queries only (linear_reads_1.out, before this drafter; not re-run). npm: the registry, for `npm ci --ignore-scripts` of committed locks (no advisory call). AgentMail: ONE read-only listing of wednesday-agent@ (`_mail_list_gate42.py` -> `_mail_list_1.out`; touches no seen-state) and four by-id reads (`inbox_digest.sh full`); nothing sent.', '',
 '**gate42 = ONE PR (T1), #1339 ROUND 2 OF 2 under the Tier-1 two-NO-GO cap — THE LAST ROUND (a NO GO ships nothing and goes to Kam); one kit, no sibling, NO stack, ONE merge-base (develop itself); eleven OPEN PRs DECLARED as overlapping (manifests / locks, unchanged from round 1).**', '',
 '| PR | tickets | tier | head (API == ls-remote pull/head == branch == fetched) | commits on merge-base | files | subject declared -> lands |', '|---|---|---|---|---|---|---|',
 '| #%s | KS-1378 + KS-729 | T1 | `%s` | %d on `%s` (round 1 `%s` graded NO GO by gate41; round 2 `%s`) | %d (28 manifests / locks + 2 email.ts) | %s |' % (
     n, pr['head'], len(pr['commits']), pr['merge_base'][:12], pr['commits'][0][:12], pr['commits'][-1][:12], len(pr['paths']), subj), '',
 'Routing `%s` (**NOT added by the drafter** — §4). The GO string, as the GO mail\'s SUBJECT: `GO (Seat B 44th): merge 1339 on gate42` — Seat B 44th pushed round 2 and holds the merge tools (kit rule 46 carries requirement 6; launcher exit 26). Merge order: #1339 ALONE and FIRST — before Seat B 44th\'s six held branches and before its separate audit-baseline re-date PR (not in this kit). The squash subject is the PR title verbatim, declared explicitly (fill_gate42.py SHORT), %s; body `Refs KS-1378` + `Refs KS-729`.' % (K['pane'], subj), '',
 '## 1. BLUF',
 '- **Kit: READY to launch once the routing line is added** — launcher `--check` (launcher_check_1.out: `%s`); repin `--dry-run` (%s: %s).' % (last('launcher_check_1.out', r'all guards pass'), DRYF, last(DRYF, r'DRY RUN COMPLETE')[:170]),
 '- **Heads read at pin vs the commission:** #1339 head `%s` (commission `%s…`: **%s**); develop `%s` (commission `%s…`: **%s**). Re-read by `ls-remote` AND the PULLS API AND the fetch (predict_1.out), again by the dry run (%s) and a final `ls-remote` (final_lsremote_1.out): %s — every pin still current: **%s**.' % (
     pr['head'], CH, 'EQUAL' if pr['head'].startswith(CH) else 'DIFFERENT', P['develop'], CD, 'EQUAL' if P['develop'].startswith(CD) else 'DIFFERENT', DRYF, fl, cur),
 '  - Develop tree `%s`; merge-base `%s` (develop itself, move EMPTY); **END_TREE `%s`** (%s); diff(develop, END) == the %d own paths, every END blob == the head blob (MG-1).' % (P['develop_tree'], pr['merge_base'][:12], P['end_tree'], P['end_shortstat'], len(pr['paths'])),
 '  - Round-2 shape (predict (b), READ): %s | %s | %s.' % (strip(last('predict_1.out', r'ROUND 2 SHAPE'))[:200], strip(last('predict_1.out', r'ROUND 2 SCOPE'))[:160], strip(last('predict_1.out', r'ROUND 2 MOVED NO LOCK'))[:170]),
 '- **Controls, both ways (controls_gate42.sh, one unedited script — controls_sha.txt):**',
 '  - normal (controls_1.out, rc %s): `%s`' % (rc('controls_1.rc'), last('controls_1.out', r'^SUMMARY')),
 '  - `--invert` (controls_2.out, rc %s): `%s`' % (rc('controls_2.rc'), last('controls_2.out', r'^SUMMARY')),
 '- **Simulations (predict):** %s | (`moved` must PASS; `foreign<n>` must REFUSE).' % '; '.join('%s -> rc %s %s' % (k, v[0], v[1]) for k, v in sims.items()),
 '- **Pinned predict** (predict_1.out, rc %s): `%s`.' % (rc('predict_1.out.rc'), last('predict_1.out', r'^(PASS|REFUSED):')),
 '- **Requirement 1 — the Dockerfile build path (MEASURED by the drafter, installprobe_1.out, rc %s; npm %s, node %s; controls %d/%d PASS):** `npm run build` (tsc 5.9.3) on a host mirror of the shared-builder + builder stages: %s. **CT8 — the control that can fail, on REAL code — round 1 reds with exactly the TS2503 pair per service**: auth %s; originate %s. Resolved nodemailer (standalone): %s. The ROOT install and both suites are NOT measured — the gate owes them (the seat\'s "77 / 836" and "89 / 1058" on 10.0.12 are claims).' % (
     rc('installprobe_1.rc'), IP['npm'], IP['node'], sum(IP['controls'].values()), len(IP['controls']), j({k: 'rc %s / %s err' % (v['build_rc'], v['n_errors']) for k, v in SU['tsc'].items()}),
     IP['tsc']['r1_auth']['errors'], IP['tsc']['r1_originate']['errors'], j({k: v['nodemailer'] for k, v in SU['nodemailer_probe'].items()})),
 '- **Requirement 2 — what held in gate41 (READ + MEASURED):** %s; the 28 manifest / lock blobs at the head == round 1\'s; morgan planted quote base escaped %s -> head escaped %s (MEASURED); %s. Legs 6 / 7 NOT run by the drafter (npm advisory API).' % (
     strip(last('predict_1.out', r'AUDIT BASELINE'))[:200], SU['nodemailer_probe']['base_auth']['morgan_planted_quote_escaped'], SU['nodemailer_probe']['head_auth']['morgan_planted_quote_escaped'], strip(last('predict_1.out', r'IP-ADDRESS: a 9.x'))[:140]),
 '- **Requirement 3 — the runtime-moved services (MEASURED, standalone `npm ci`):** queue msgpackr %s -> %s; m365 identity-nested msal-node %s -> %s; shared msal-node %s -> %s; load smokes ALL ok (CT13); own suites %s. **packages/shared\'s suite did NOT start standalone** (§2 item 1).' % (
     [v for p_, v in SU['runtime_copies']['base_queue'] if p_.endswith('/msgpackr')], [v for p_, v in SU['runtime_copies']['head_queue'] if p_.endswith('/msgpackr')],
     [v for p_, v in SU['runtime_copies']['base_m365-integration'] if p_.endswith('identity/node_modules/@azure/msal-node')], [v for p_, v in SU['runtime_copies']['head_m365-integration'] if p_.endswith('identity/node_modules/@azure/msal-node')],
     [v for p_, v in SU['runtime_copies']['base_shared'] if p_.endswith('/@azure/msal-node')], [v for p_, v in SU['runtime_copies']['head_shared'] if p_.endswith('/@azure/msal-node')],
     j({k: v['summary'] for k, v in SU['standalone_suites'].items()})),
 '- **Requirement 4 — the round-2 diff (READ line by line, predict (e)):** %s' % strip(last('predict_1.out', r'services/auth email.ts ROUND-2 DIFF'))[:620],
 '- **Requirement 5 — test files that reference a changed path:** %d distinct files (the list is in COMMISSION.md requirement 5 and in the prompt), incl. %d auth + %d originate tests importing email.ts by `services/email`.' % (ntests, len(CZ['email_importers']['services/auth']), len(CZ['email_importers']['services/originate'])),
 '- **Requirement 6 — the re-date PR:** NOT open at the pin (the PULLS API census, predict (a)); kit.json `widen_disjoint_rule` classes a baseline-only WIDEN PR DISJOINT-OUT-OF-KIT when it opens (controls RWD / RWD-twin).',
 '- **Linear (linear_reads_1.out, READ by the previous drafter at 04:16Z):** %s. **Key scan (keyscan_1.out):** %s.' % (last('linear_reads_1.out', r'^#1339 attachmentsForURL')[:200], last('keyscan_1.out', r'MANDATED squash text')[:200]),
 '- **Re-key / namespace (rekey_1.out, gate41\'s AND gate40\'s namespaces):** %s' % last('rekey_1.out', r'^RESULT'),
 '- **Sizes / sha256:** %s; %s; %s.' % (sz(PR), sz(L), sz(CAP)), '',
 '## 2. Doubts and contradictions the drafter found (each READ or MEASURED as stated)',
 '1. **packages/shared\'s own suite cannot run in its standalone install (MEASURED):** its standalone lock carries NO vitest (vitest is only in the root lock), its vitest.config.ts imports `vitest/config`, and its KS-727 guard imports service source from outside the package — run with the same side\'s m365 vitest it prints `Error: Cannot find module \'vitest/config\'` at base AND head (recorded as DID NOT START, never as red or green). So Wednesday\'s condition ("a clean standalone `npm ci` plus that service\'s own suite") is met for queue and m365-integration (MEASURED green both sides) but NOT for packages/shared by the drafter; the prompt tells the gate to close it or say what exercises shared\'s msal-node 6 (m365\'s standalone suite links the standalone-built shared).',
 '2. **gate41\'s N-1339-7 ("@types/nodemailer unused by tsc under 10") is not what the drafter measured at round 1 or the head:** `tsc --listFilesOnly` reads BOTH the bundled `dist/cjs` declarations (20 files, the entry `nodemailer.d.ts` among them) AND 14 `@types/nodemailer` files (%s) — @types is still in the program (automatic @types inclusion); whether it is load-bearing is unmeasured.' % j(SU['tsc_reads'].get('head_auth')),
 '3. **The seat\'s fix shape differs from gate41\'s fix-shape (READ):** a separate `import type { Transporter } from \'nodemailer\';` line vs gate41\'s inline `import nodemailer, { type Transporter }`. Under these tsconfigs (`module: commonjs`, `esModuleInterop`, no `verbatimModuleSyntax` / `isolatedModules`, READ) both are erased; the drafter MEASURED tsc rc 0 on 10.0.12 only — it did NOT type-check the round-2 source against 9.1.1 or read the emitted email.js. The gate owes both (requirement 4).',
 '4. **The fuse (READ):** gate41 (round 1) PROBED that after 2026-09-30T00:00Z leg 6 reds at this head on the GHSA-frvp-7c67-39w9 lapse. Kam\'s signed re-date mail arrived (2026-09-29T04:14:47Z) and Seat B 44th builds it as a SEPARATE PR that merges AFTER #1339 — so a gate that runs its legs after 00:00Z sees a leg-6 red that is the lapse, not the bump. Seat B 44th\'s CORRECTION (04:22Z) retracted its "three rows" finding: at develop only frvp (KS 530) and mwp4 (KS 729) expire 09-30, both named by Kam. The prompt makes the gate time-stamp its leg runs and prove the cause.',
 '5. **The re-date PR would trip the WIDEN branch census** (its branch will carry `-b44-<n>`, which kit.json `widen_branch_rx` matches): the prior round\'s (gate41) shape would refuse the launch rc 15. The drafter added ONE measured exception (kit.json `widen_disjoint_rule`: an out-of-kit WIDEN PR whose ENTIRE file list is `Blockchain/Dev/scripts/audit/audit-baseline.json`), in predict (a) and the launch action\'s step 2b, proved both ways on a real one-file PR (RWD / RWD-twin). It is dormant at drafting (no such PR open); if the re-date PR touches ANY other file the launch still refuses rc 15 — a re-draft decides.',
 '6. **The shared checkout is 176+ commits behind origin develop** (Seat B 44th\'s CORRECTION, READ): the prompt forbids reading file CONTENT from its working tree. Every drafter read was `git show <sha>:<path>` from the scratch clone.',
 '7. **Seat B 44th disclosed `--no-verify` on `git commit`** (round-2 READY): no commit hook exists (its measurement). The push itself ran the pre-push preflight (push.out: 12/15 legs, INCOMPLETE, 3 SKIPPED — legs 3 4 8, nothing failed). The gate grades the disclosure (N-1339-6).',
 '8. **The drafter did NOT run** the root workspace install, the auth vitest or originate jest suites, the census-named tests, eslint, the audit legs, the SMTP sink, or any of the seat\'s arms (§6).',
 '9. **The PR BODY was NOT updated for round 2 (READ, gh_body_1339.md re-read by gh_read_gate42.py at the pin):** byte-identical to round 1\'s apart from the head line — it still says "Zero vulnerable copies" with no "in scope" (N-1339-3), and names neither round 2, N-1339-1, tsc nor KS 1379; the corrected wording lives only in the round-2 commit message and the READY. The merger composes the squash body; the prompt asks the gate to rule on what it must carry.',
 '10. **GitHub mergeable_state `unstable`** (gh_read_1.out) — mergeable True; not measured further (CI jobs never start: gate41\'s "recent account payments have failed").',
 '11. **Defects found in the partial kit and fixed by this drafter (READ):** (a) the prompt template\'s report directory still named gate41\'s report dir (`…batch1339-g41/`) — the gate would have written INTO the round-1 report; now `{{REPORT}}` filled from kit.json (%s); (b) make_commission\'s routing token was gate41\'s pane (the re-key check caught it); (c) predict\'s class (`dependency-bump-r2`) had no DECL entry (KeyError) and still asserted email.ts BYTE-IDENTICAL base -> head and "ZERO source files" — replaced by the round-2 shape / scope / line-by-line checks; (d) the fill CFG, prompt, capture and controls were gate41\'s round-1 content (seat items, keywords, rules, subject "GATE41 …", the Seat B 43rd READY id and push log); (e) the re-key map guarded gate40/gate39, not gate41/gate40; (f) the launcher template header said round 41; (g) installprobe measured no tsc (the prediction that missed N-1339-1) and nothing for the runtime-moved services; (h) the SJ1-SJ4 subject controls could not fail for their stated reason: the doctor anchored on the indented `  SHORT=` line, and its whitespace-joined regex ate the previous newline, gluing SHORT onto a comment — every plant refused for "NO declared subject" whatever it planted (the same shape is in the prior round\'s (gate41) controls, whose SJ passes were therefore not evidence of the subject rule). Found by a new SJ3/why check on the first controls run (170 controls, 1 MISMATCH); fixed (anchor without indent) and every SJ now carries a /why check that its REFUSING line names ITS defect; both runs in §1 are of the fixed script.' % K['report'], '',
 '## 3. Pins and what the gate owes',
 '- Prompt `%s` — Wednesday\'s SEVEN gate42 requirements BY NAME as kit rules 40-44 / 46-47, plus 48 (every finding of the prior round, gate41, re-checked), 49 (every lock-touched suite), 50 (the call sites driven through the emitted JS); the launcher refuses a prompt missing any; the R<exit> controls split each. `## MERGE ADDENDUM` last, ONE LINE (rule 52), 30 over 30 paths.' % K['prompt'],
 '- Report dir `/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/%s/` (TEXT only); mail FROM coagent@ TO wednesday-agent@, subject `%s`.' % (K['report'], re.search(r"grep -qF -- '(\[QA -> Wednesday\][^']*)'", open(L, encoding='utf-8').read()).group(1)), '',
 '## 4. Routing line — NOT added',
 'Add this ONE line to `/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/inbox_routing.conf` (beside the other QA/Secuura batch lines) — backup first:',
 '```', '%s|coagent@agentmail.to|yes' % K['pane'], '```',
 'Until it is present the launch action\'s step 0 refuses rc 1 (%s reports it: `%s`; control RB measures the real refusal rc 1). The dry run found NO other refusal.' % (DRYF, last(DRYF, r'line present:')[:200]), '',
 '## 5. Controls: `controls_gate42.sh <scratchpad> [--invert]`',
 '- gate41\'s arms re-cut for round 2: wrong heads (C2 = the develop sha as the head; **C4 = the ROUND-1 head gate41 graded, real and fetched — must refuse rc 6**), a moved develop (predev = the #1332 squash, MERGED), a path rename, capture / prompt doctoring, every kit rule 35 / 40-44 / 46-55 SPLIT (the seven requirements among them), the GO string and merge authority, the addendum, the verdict subject, a wrong END_TREE, a moved launcher, the non-TTY launch path, repin argv / routing / WIDEN by title and by branch / **RWD + twin (NEW: the baseline-only widen_disjoint_rule both ways on a real one-file open PR)** / a false (self-)STACK / the REAL re-pin across a move in a copy / RE-RN-RO-RDO plants, predict `--simulate foreign1339` and `moved`, fill from SIM / failed pins, SJ1-SJ4 subject plants (SJ3\'s foreign key is KS-1379, the ticket #1339 does NOT close), and NS[<spelling>] over gate41\'s AND gate40\'s namespaces.',
 '- Inside predict (each `CONTROL` line in predict_1.out): the unfetched-object guard, the vulnerable-range predicate, the +/- comparator, **the round-2 line judge** (the real shape reads RIGHT; a planted extra value line and a dropped annotation pair each read WRONG) and **the census grep** (it finds email importers in both services). Inside installprobe: CT1-CT13, CT8 being real round-1 code that must red.',
 '- Not controlled: exit 16 (needs a TTY), repin steps 4-6 (usage gate, cockpit add), a `mergeable=False` refusal.', '',
 '## 6. Could not measure (the drafter\'s NOT-MEASURED list)',
 '- The ROOT workspace `npm ci` and require.resolve from each service dir; the auth (vitest) and originate (jest) suites on 10.0.12; the other lock-touched suites and frontend/issuer; every census-named test; packages/shared\'s suite on its standalone install (did not start); eslint on the two email.ts; audit legs 6 / 7 and the audit contract (npm advisory API — no advisory call made); the SMTP sink through the tsc-emitted JS; the round-2 source type-checked against 9.1.1; the emitted email.js read; the seat\'s A0 / A1 / A2 arms; a real Redis / Azure call for the runtime-moved packages (constructed only). Every suite figure in the READY is a seat claim.', '',
 '## 7. Files',
 '- Kit: kit.json · COMMISSION.md (make_commission_gate42.py) · README.md (make_readme_gate42.py) · rekey_check_gate42.py -> rekey_1.out',
 '- Pins: predict_gate42.py -> predict_1.out(.rc), predict_sim_*.out(.rc), pins_gate42.json (+ .SIM-*.json) · keyscan_gate42.py -> keyscan_1.out · final_lsremote_1.out',
 '- Measurements: installprobe_gate42.py + installprobe_gate42.cjs + installprobe_rt_gate42.cjs -> installprobe_1.out (+ .rc), installprobe_gate42.json',
 '- Reads: gh_read_gate42.py -> gh_read_1.out, gh_body_1339.md, gh_comments_1339.md · linear_reads_gate42.py -> linear_reads_1.out, linear_KS-1378.md, linear_KS-729.md, linear_KS-1379.md · _mail_list_gate42.py -> _mail_list_1.out · capture_mail_gate42.py -> capture_1.out, mail_gate42_ready.md, stopcounts_gate42.json · _api_peek_gate42.py -> _api_peek_1.out',
 '- Prompt/launcher: prompt_gate42.TEMPLATE.txt, launcher_gate42.TEMPLATE.sh.txt, fill_gate42.py -> %s + %s (fill_1.out), launcher_check_1.out · repin_and_launch_gate42.sh -> %s · controls_gate42.sh -> controls_1.out / controls_2.out (+ .rc) — both complete runs of ONE unedited script (its sha256 before the first run and after the second: controls_sha.txt). `_quarantine_2026-09-29/`: superseded fill outputs, moved not deleted.' % (K['prompt'], K['launcher'], DRYF), '',
 '## 8. The ONE launch command (after the routing line, §4)',
 '```', launch, '```',
 '- Dry run: append `--dry-run` (%s is one, rc %s). Argument 2 may be ANY existing Claude session scratchpad dir (`/private/tmp/claude-501/*/scratchpad*`, the Data volume); if `g42_sp/clone.git` is absent there, predict rebuilds it on a re-pin (installprobe is NOT re-run by a re-pin). A develop move re-pins in the same action (step 3b); an own-path move (e.g. a declared dependabot PR merging first), an undeclared open-PR overlap or an END-tree disagreement refuses rc 10; a moved #1339 head refuses rc 11; a further `-b43-<n>` / `-b44-<n>` PR (one of the six held branches) or a KS-1378 / KS-1379-titled PR refuses rc 15 — EXCEPT the baseline-only re-date PR (widen_disjoint_rule), which passes as DISJOINT-OUT-OF-KIT.' % (DRYF, rc(DRYF.replace('.out', '.rc')) if os.path.exists(os.path.join(D, DRYF.replace('.out', '.rc'))) else '?')]
open(D + '/README.md', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('wrote', D + '/README.md', len(out), 'lines')
