#!/bin/bash
# launch_qa_secuura_batch1286.sh — cross-project QA agent, ONE BATCH gate (gate28, tiers 1, 2 and 3) over 3 Secuura/Blockchain PRs of round 28, FROZEN at three:
# #1286 KS-1336 (B 30th (round 1 + fix round 1, fast-forward), T3) · #1288 KS-1341 (B 31st (local-model patch, Spark spark-dsv4flash under a Wednesday brief, re-verified by the seat), T1) · #1289 KS-1318 (B 31st (hunk 3 of #1268's ks781 diff, raised alone), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate28.py, a --no-local scratch clone fetched from origin) at 2026-09-26T06:49:31Z, never adopted
# from a mail. develop at generation e080174c86c671349c508560744644fc0ef33388; the PRs' merge-bases: 00de57baeb405d0081fe8b6f192bd40d35acef61 for #1286; e080174c86c671349c508560744644fc0ef33388 for #1288, #1289; END_TREE 80a3d6968f67c1bdf70af6fc1da6cf2ad3a5ee54.
# The compare check is three-dot (develop...head): merge_base, ahead, behind AND the file NAMES, per PR.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate28.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  three rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate28.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at three.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the #1288 T1 runtime probe. exit 41: the #1286 round-2 cap rule. exit 42: the #1288 declared five. exit 49: the #1288 helper placement. exit 43: the #1286 TIER-3 doc-claim rule. exit 44: the #1289 red design. exit 48: the declared dead-open #1268 overlap. exit 35: no Docker / no stack / no port. exit 47: the MG-3 key scan. exit 46: the Linear link kinds.
# QAB28_CUR_DEV / QAB28_HEAD_<n> / QAB28_PATHS_<n> / QAB28_BRIEF / QAB28_PROMPT: test overrides (--check only); a launch with any QAB28_* set refuses (16).
# Generated by fill_gate28.py at 2026-09-26T06:56:04Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1286.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/private/tmp/claude-501/-Volumes-DevMASTER-WEDNESDAY/6a51240d-d642-471f-b7c2-1011f35eb0ce/scratchpad/gate28'
BRIEF="${QAB28_BRIEF:-$GS/mail_gate28_ready.md}"
PROMPT_FILE="${QAB28_PROMPT:-$GS/2026-09-26_secuura-batch1286.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1286|KS-1336|refs/heads/feature/ks-1336-multi-tenancy-docs-shared-db-b30-2|da5f3dd837dd5b6c706e7816bd4028070029d5e1|2|2|00de57baeb405d0081fe8b6f192bd40d35acef61|13|Blockchain/Dev/docs/MULTI-TENANCY.md,Blockchain/Dev/docs/RLS-FAIL-CLOSED-PLAN.md|T3"
  "1288|KS-1341|refs/heads/feature/ks-1341-webhooks-500-part-a-b31-1|cb58d3a59c8921a3a1caede3c6acfb4b599bf959|2|1|e080174c86c671349c508560744644fc0ef33388|0|Blockchain/Dev/services/originate/src/__tests__/ks1341a-webhooks-500-never-answers-err-message.test.ts,Blockchain/Dev/services/originate/src/routes/webhooks.ts|T1"
  "1289|KS-1318|refs/heads/feature/ks-1318-ks781-j2-tag-set-alone-b31-2|1e24633b9c196c5d3dd5bb83519bce860ca79758|1|1|e080174c86c671349c508560744644fc0ef33388|0|Blockchain/Dev/packages/shared/src/__tests__/ks781-p3-3-body-parser-order.test.ts|T2"
)
DEVELOP_SHA='e080174c86c671349c508560744644fc0ef33388'
END_TREE='80a3d6968f67c1bdf70af6fc1da6cf2ad3a5ee54'
_ovr() { local v="QAB28_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate28.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 3 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 3 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate28_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB28_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate28.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at three' && has 'TIER 1: THROUGH-CODE PLUS RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at three" >&2; exit 7; }
for _w in \
  'the only place in this router that turns a caught error into a 500' \
  'bare 943 / patched 951' \
  'Declared at the END of the file' \
  '22 problems (0 errors, 22 warnings)' \
  'no catch block in this file tests error text at all' \
  'the patch was produced by the local model' \
  'This PR'\''s diff carries **1 hunk**; the develop→#1268 diff carries 3.' \
  'PREDICTED 1 red, GOT 1 — set matches EXACTLY' \
  '36 problems (1 error, 35 warnings)' \
  'N-1286-1 TWO-FLAGS-FALSE' \
  'the INSERT at :271' \
  'Nothing else is changed.' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'TWO-FLAGS-FIXED' \
  'NOTHING-ELSE-CHANGED' \
  'INSERT-LINE-271' \
  'BICEP-SCOPE' \
  'FLAG-ROLES' \
  'N1286-3-TO-6-CARRY' \
  'PR-BODY-STALE' \
  'SENTENCE-BY-SENTENCE' \
  'NO-PLAN-ADDED' \
  'TIER-3-DOCS' \
  'FAIL500-RUNTIME-NODE-ENV' \
  'CATCH-REACHED' \
  'LEAK-FIXTURE-BENIGN-TRAP' \
  'GET-SLASH-SYNC-THROW' \
  'UNCONVERTED-FIVE' \
  'PART-A-SCOPE-ORDER' \
  'HELPER-HOISTING' \
  'DOCBLOCK-FALSE-AT-A' \
  'KS730-HELPER-PARITY' \
  'GOLDEN-BLOB-IDENTITY' \
  'LOCAL-MODEL-PROVENANCE' \
  'ORIGINATE-943-951' \
  'TSC-EXCLUDES-TESTS' \
  'LINT-22-WARNINGS' \
  'ARM-A-REVERSE' \
  'ARM-B-RELABEL' \
  'HUNK3-ALONE' \
  'KS1316-FREE' \
  'DEAD-OPEN-1268-HUNK-SUBSET' \
  'LINT-PREEXISTING-KS703' \
  'KS1318-DOD-CLOSES' \
  'BASE-FIGURES-PER-PR'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'RUNTIME PROBE FOR #1288 — THROUGH THE REAL ROUTER' && has 'a LEAK that does NOT contain '\''does not exist'\''' && has 'under NODE_ENV production, development, test and UNSET' && has 'the body NEVER contains it, the logger RECEIVED it, the catch was REACHED' && has 'it MUST leak on both routes in all four environments' || { echo "REFUSING: the #1288 T1 runtime probe" >&2; exit 40; }
has 'ROUND 2 OF 2 FOR #1286 — THE CAP' && has 'AT THE CAP A NO GO SHIPS NOTHING' && has 'grade it against gate27'\''s NO GO' || { echo "REFUSING: the #1286 round-2 cap rule" >&2; exit 41; }
has 'THE FIVE UNCONVERTED SITES ARE DECLARED SCOPE, NOT A NO GO' && has 'byte-identical to their develop lines' || { echo "REFUSING: the #1288 declared five" >&2; exit 42; }
has 'HELPER PLACEMENT (#1288): the helper is declared at the END of the file' && has 'prove the hoisting at runtime' || { echo "REFUSING: the #1288 helper placement" >&2; exit 49; }
has 'TIER 3: DOC-CLAIM (#1286' && has 'Check each corrected sentence against the code at the launch develop' && has 'the docs must add NO plan and NO recommendation' || { echo "REFUSING: the #1286 TIER-3 doc-claim rule" >&2; exit 43; }
has 'RED DESIGN FOR #1289' && has '`return shapes;` -> `return shapes.reverse();` must red J2 ALONE at head and red NOTHING at develop' || { echo "REFUSING: the #1289 red design" >&2; exit 44; }
has 'ONE overlap is DECLARED, not found: the dead-open #1268 carries #1289'\''s path at a DIFFERENT blob' && has 'RECOMMEND to Wednesday, READ ONLY: #1268 closes unmerged' || { echo "REFUSING: the declared dead-open #1268 overlap" >&2; exit 48; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'all three PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1286, #1288, #1289 batch`' && has 'so all three are squashed by a MERGE SEAT Wednesday names, never by an author' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (2 over 2 paths) for #1286 and #1288, (1 over 1 path) for #1289' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE28 batch #1286 #1288 #1289 (Seats B30/B31, round 28; #1286 round 2 of 2 at the cap)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE"
_ANY_OVR="$(env | grep -c '^QAB28_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 3 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 13 seat items; the prompt carries 32 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the #1288 T1 runtime probe / the #1286 round-2 cap rule / the #1288 declared five / the #1288 helper placement / the #1286 TIER-3 doc-claim rule / the #1289 red design / the declared dead-open #1268 overlap / no Docker / no stack / no port / the MG-3 key scan / the Linear link kinds rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB28_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
