#!/bin/bash
# launch_qa_secuura_1210-t1r2.sh — cross-project QA agent, ONE TIER-1 RE-GATE (round 2 of 2) over ONE Secuura/Blockchain PR: #1210 KS-1239 RAWAUTHDEAD,
# head 6b572240fc31e564a6d0c516fdff66814bb856c6 (parent = the round-1 head 231ab8b5c898, parent BASE). The round-1 NO GO was on LEGD-LINEPIN only.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_r2.py, a scratch clone FROM ORIGIN) at 2026-09-23T10:26:52Z, never adopted from a mail.
# Develop read at generation: dd8f99cc75b9b753172a40379eaab2b6c1026180 (10 ahead of BASE); merged tree over it 0c834769ecf99f9563105f0b1a48a6c7371955b2.
# exit 2-5: QA project / capture / prompt / repo missing.
# exit 6:  the head is not at its branch AND refs/pull/1210/head on origin — a STALE HEAD REFUSES.
# exit 8:  the prompt must open with the thinking directive and name the capture + the commission.
# exit 10: the GitHub compare develop...head: merge_base == BASE, ahead 2, behind == 10, files 3.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_r2.sh (it re-reads, re-measures and regenerates in ONE action).
# exit 20: the capture AND the prompt must name the head in full.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` runs headless; it launches nothing).
# exit 23: the prompt must carry the exact verdict subject prefix, coagent@ as sender, wednesday-agent@ as recipient.
# exit 25: the MERGE ADDENDUM rules.  exit 26: WEDNESDAY'S signed GO as merge authority + the GO string.
# exit 30: the capture AND the prompt must BOTH carry the seat items.  exit 31: BASE / the launch develop / the merged tree in full.
# exit 33: the by-name keyword ladder.  exit 16: a launch with any QA1210_* override set.
# QA1210_CUR_DEV / QA1210_HEAD / QA1210_BRIEF / QA1210_PROMPT: test overrides (--check only).
# Generated by gatesets/2026-09-23_gate20T1r2_1210/fill_r2.py at 2026-09-23T10:29:30Z.
# Usage: launch_qa_secuura_1210-t1r2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-23_gate20T1r2_1210'
BRIEF="${QA1210_BRIEF:-$GS/mail_r2_ready.md}"
PROMPT_FILE="${QA1210_PROMPT:-$GS/2026-09-23_secuura-1210-t1r2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
PR_N='1210'
PR_BR='refs/heads/feature/ks-1239-r-1-the-indexts347-rawauthorization-capture-is-dead-code-0-r16b-rawauthdead-1'
HEAD_SHA='6b572240fc31e564a6d0c516fdff66814bb856c6'
BASE_SHA='2bc5ccf63b8c40911afb568b03cace066238ffcf'
DEVELOP_SHA='dd8f99cc75b9b753172a40379eaab2b6c1026180'
DEV_BEHIND='10'
MERGED_TREE='0c834769ecf99f9563105f0b1a48a6c7371955b2'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF 'mail_r2_ready.md' "$PROMPT_FILE" && grep -qF '2026-09-23_gate20T1r2_1210/COMMISSION.md' "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission" >&2; exit 8; }
grep -qF '{{' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled {{ token" >&2; exit 8; }
_h="${QA1210_HEAD:-$HEAD_SHA}"
_lsr="$(git -C "$REPO" ls-remote origin "$PR_BR" "refs/pull/$PR_N/head")"
if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${PR_BR}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${PR_N}/head\$"; then
  echo "REFUSING: #$PR_N — $_h is not at the branch AND refs/pull/$PR_N/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
  printf '%s\n' "$_lsr" >&2
  exit 6
fi
CUR_DEV="${QA1210_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the merged tree $MERGED_TREE is unverified there: run repin_and_launch_r2.sh (it re-reads, re-measures and regenerates in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  CUR_DEV="$CUR_DEV" H="$_h" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
u = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/" + os.environ["CUR_DEV"] + "..." + os.environ["H"]
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    print("%s ahead=%d behind=%d files=%d" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(c.get("files") or [])))
except Exception as e: print("ERROR %s" % e)
PY
)"
[ "$COMPARE" = "$BASE_SHA ahead=2 behind=$DEV_BEHIND files=3" ] || { echo "REFUSING: the compare is not merge_base $BASE_SHA / ahead 2 / behind $DEV_BEHIND / files 3: $COMPARE" >&2; exit 10; }
grep -qF "$HEAD_SHA" "$BRIEF" && grep -qF "$HEAD_SHA" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name the head $HEAD_SHA in full" >&2; exit 20; }
grep -qF 'PR #1210 is KS-1239.' "$PROMPT_FILE" && grep -qF '#1210 KS-1239' "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #1210 is KS-1239" >&2; exit 30; }
for _w in \
  '231ab8b5c898' \
  '0c834769ecf99f9563105f0b1a48a6c7371955b2' \
  'dd8f99cc75b9b753172a40379eaab2b6c1026180' \
  '917/917' \
  '918/918' \
  '746/746' \
  '750/750' \
  '915/917' \
  'LEGD-LINEPIN' \
  '827' '840' '873' \
  '2327' '2550' \
  'STACK_TRACE_ERROR' \
  '--no-file-parallelism' \
  's-b22-merged1210' \
  '3bad652d1' \
  '205 files' \
  'CROSSLANE-READERS' \
  'RAWAUTHDEAD-COMMENTS'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
for _w in \
  'TIER-1 RE-GATE, ROUND 2 of 2' \
  'TWO-NO-GO CAP' \
  'CLOSED-PARTS' \
  'MEASURE, not conclude' \
  'RULE WHETHER IT BLOCKS' \
  'THE FIRST JOB' \
  'THE SECOND JOB' \
  'THE THIRD JOB' \
  'RED-FIRST FOR THE FIX' \
  'THE PINS ARE LIVE, NOT VACUOUS' \
  'A CONTROL THAT FIRES' \
  'FOR SCOPE' \
  'THE BASE MOVED' \
  'RE-READ develop at your start' \
  '0 bytes under `services/auth/`' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'never print a credential value' \
  'No memory maintenance' \
  'Datasec files and mail are out of scope entirely' \
  'NOT-TESTED.written-first.md' \
  'WRITE report.md BEFORE THE MAIL' \
  'THE CONTEXT RULE' \
  'NOT-PINNED' \
  'CARRY-FORWARD' \
  'KEY-FREE' \
  'stays In Progress' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '2026-09-23-batch1204-t1-r2-1210' \
  '2026-09-23-batch1204-t1-r1/report.md'; do
  printf '%s' "$PROMPT_JOINED" | grep -qF -- "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
grep -qF -- "WEDNESDAY'S signed GO naming the head" "$PROMPT_FILE" && grep -qF -- '`GO: merge #1210 batch`' "$PROMPT_FILE" || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
grep -qF -- '## MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF -- 'ONE equality target PER PR FILE' "$PROMPT_FILE" && grep -qF -- 'KEY-FREE' "$PROMPT_FILE" || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-1 RE-GATE #1210 KS-1239 round 2 of 2' "$PROMPT_FILE" && grep -qF -- 'FROM coagent@agentmail.to' "$PROMPT_FILE" || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$BASE_SHA" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$MERGED_TREE" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the merged tree not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of BASE); compare $COMPARE; head $_h at branch AND pull/$PR_N/head; merged tree $MERGED_TREE"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  capture, prompt, QA project and repo present; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry the head in full, the ticket and 21 seat items; the prompt carries 33 by-name keywords, the merge authority + GO string, the MERGE ADDENDUM rules, the verdict subject / sender, BASE / develop / merged tree in full"
  [ -n "${QA1210_CUR_DEV:-}${QA1210_HEAD:-}${QA1210_BRIEF:-}${QA1210_PROMPT:-}" ] && echo "  (a QA1210_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QA1210_BRIEF:-}${QA1210_PROMPT:-}${QA1210_HEAD:-}${QA1210_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
