#!/usr/bin/env python3
"""make_task.py <out task.md> — the bash_patch2 task text, DERIVED from tasks/bash_patch/task.md at run time (2026-10-07).

bash_patch2 is bash_patch with a declared multi-file touched set, so the model's contract is bash_patch's task.md with
exactly the clauses that say "ONE script / ONE new test / two files" replaced (never a second hand-maintained copy that
drifts from the first), plus one rule for the RED / SUPPORT roles. Each replaced clause is located by its exact text;
if any anchor is missing (bash_patch's task.md was rewritten) this REFUSES (rc 2) rather than emit a task that says two
contradictory things. rc 0 ok · 2 anchor missing · 64 usage. Same discipline as tasks/code_patch2/make_task.py.
"""
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
SRC = os.path.join(os.path.dirname(HERE), "bash_patch", "task.md")

REPL = [
    ("fix ONE bash script exactly as the brief says, and add ONE shell test suite that proves it",
     "fix the DECLARED bash script(s) exactly as the brief says, and edit / add the DECLARED shell test suites that prove it"),
    ("- `product_file` — the ONE script you may change (path from the repo root).",
     "- `product_files` — the script(s) you change (1-3; `product_file` is the FIRST of them). Every one's FULL current content"
     " is in `files[<its path>]`.\n- `product_file` — the first script (path from the repo root)."),
    ("- `suggested_test_file` — the path of the NEW test file you create (under `test_dir`, beside the reference).",
     "- `test_files` — the test suites you touch (1-4), each `{path, status, role}`: `status: new` is a NEW file you create"
     " (`--- /dev/null`), `status: modified` an EXISTING suite you modify in place (its FULL content is in"
     " `files[<its path>]`). `suggested_test_file` names the first RED one only."),
    ("from `files[product_file]`. A blank context line", "from `files[<that file's path>]`. A blank context line"),
    ("3. The diff touches EXACTLY two files: `product_file` and the new test at `suggested_test_file`. Nothing else.",
     "3. BASH_PATCH2 (multi-file): the diff touches EXACTLY the files the input DECLARES — every path in `product_files`"
     " and every path in `test_files` — one file section per declared file, in the order the brief's `## The mode` gives."
     " Not one file more, not one fewer: an undeclared file, or a declared file left untouched, fails the checker before"
     " any test runs. Never touch the reference test unless it is declared."),
]
ADD = ("\n6. Roles. Every `role: red` suite FAILS at the untouched tip with your test edits alone and PASSES after your"
       " script edits. Every `role: support` suite is an existing suite whose edit (e.g. a stub brought to the new"
       " contract) must PASS both with your test edits alone and after your script edits. The checker applies ALL your"
       " test sections first (no script section), then ALL your script sections on top. Every `+` line of every file is"
       " the brief's, byte for byte, in the brief's order.\n")


def main():
    if len(sys.argv) != 2:
        print("usage: make_task.py <out task.md>", file=sys.stderr)
        return 64
    t = open(SRC, encoding="utf-8").read()
    missing = [a for a, _ in REPL if t.count(a) != 1]
    if missing:
        print(f"make_task: REFUSED — anchor(s) not found exactly once in {SRC}: {[m[:60] for m in missing]} (bash_patch's "
              f"task.md changed; update this derivation, do not run with a contradictory task)", file=sys.stderr)
        return 2
    for a, b in REPL:
        t = t.replace(a, b, 1)
    t = ("<!-- GENERATED by tasks/bash_patch2/make_task.py from tasks/bash_patch/task.md; the one-script / two-file clauses"
         " replaced, rule 6 added -->\n" + t.rstrip("\n") + "\n" + ADD)
    open(sys.argv[1], "w", encoding="utf-8").write(t)
    print(f"make_task: wrote {sys.argv[1]} ({len(t)} B) from {SRC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
