# Expiring grants — anything Kam time-scoped, with the date it DIES

**Why this file exists:** a time-scoped instruction with no mechanism to expire it becomes a
permanent change nobody decided to make. Every seat reads this at boot; an entry past its date is
**dead** and must be re-asked, not assumed.

| grant | given | EXPIRES | scope, exactly |
|---|---|---|---|
| **SPEND PAST THE 90% STOP TONIGHT (Wednesday seat, Secuura)** | Kam, live board 2026-09-26 21:03:00 view=wednesday, verbatim: *"The account, keep going. The accounts renew in the morning. So even if we run out, I'll switch in the morning."* (answering card `secuura-allowance-89-before-the-0930-freeze`) + 21:03:56 *"Focus as much work on the spark, so use the remaining credits between you and anything you need to do to coordinate the spark until tomorrow morning."* | **NO DATE — ends when he switches accounts (he said: in the morning, 2026-09-27) or says stop. Re-ask before relying on it after that.** Wednesday's reading receipted on the panel 21:0x. | Lifts the 90% launch stop for THIS seat's Secuura work tonight: the KS-1341 part C + KS-1344 raise seat, its QA gate, the merges. Launches pass `WED_USAGE_STOP=100` with this row as the authority. **Unchanged:** no deploys (kintsugi/demo), no production, no external comms, the QA gate before every merge, the signature classes, the audit fuse card. A spend ceiling, not a boundary. |
| **NexusAI: work through the tickets and MERGE ONCE TESTED (new Claude account)** | Kam, typed into Tuesday's terminal right after `/login` (Login successful), 2026-09-25 ~22:0x AEST, verbatim: *"New account logged in, so you should have plenty of Azure credits. Please work your way through the tickets and merge once tested."* | **NO DATE. Tied to this account's allowance and to his standing oversight; re-read if he switches accounts again or says stop.** | Agent seats work NexusAI tickets in code-disjoint lanes. A change merges to NexusAI main on Tuesday's GO ONLY after a QA gate verdict at its head + full verify; one merge at a time; main re-read after each. **NOT covered:** production, demo redeploys (a merge must not deploy — check deploy-demo.yml each time), Partner Center, money beyond the test environment's A$60 alert, external comms, anything irreversible. The previous row (keep going past 95%) is superseded by the new account. |
| **KEEP GOING PAST THE 95% STOP (Tuesday seat) — he signs in near 100%** | Kam, live board 2026-09-25 20:29:16 view=tuesday, verbatim: *"94% keep going for now and I will sign in closer to 100"* (answering Tuesday's 20:28 usage report: 94%, renews in ~1d 7h) | **NO DATE. Ends when he signs into a new account. RE-ASK if the gauge reaches ~99% and no new account has appeared** — the premise (he is there to switch) is then gone. | **Lifts this seat's 95% launch stop only**, for the NexusAI 2.2.1 live check + full client deploy test + data link (his 20:27:18 instruction). Launches pass `WED_USAGE_STOP=100` with this row as the recorded authority. **Unchanged:** the v1.3 signature classes, the QA gate before every score, the A$60 Azure bound (C-154). A spend ceiling, not a boundary. |
| ⚠ **END EVENT REACHED 2026-09-25 13:06 AEST — the gated 2.2.0 resubmission zip was EMAILED to Kam (msg 010001a0d6862e9e…); treat this grant as SPENT and re-ask before any further NexusAI main merge or demo redeploy.** ~~NexusAI: merge to main + redeploy DEMO on Tuesday's word, until a STABLE, fully-ready version exists (keeps demo and the resubmission in sync)** | Kam, LIVE board 2026-09-21 18:18:12 view=tuesday, verbatim: *"Until we have a stable version, feel free to redeploy, merge, or do anything else to get us to a point where everything is fully ready. That way, the demo version and the version resubmitted will be in sync. Yes, but I'll communicate through the board if necessary."* | **EVENT, not date: ends when NexusAI has a stable, fully-ready version (the gated resubmission zip emailed to Kam is the natural marker).** Tuesday's reading, receipted on the live board 18:2x (HTTP 201). | Merges to NexusAI main and the demo redeploys they trigger, on Tuesday's GO **after a QA gate verdict at the head** (C-32 conditions, main stays green, RELEASE mail names this row). **This answers the "Kam's terminal word" requirement for RELEASE while he travels — his board word IS the authority; quote it in the RELEASE.** **NOT covered (receipted to him):** production, Partner Center / Marketplace upload, money, external comms to humans, anything irreversible. "Yes" in the same message confirmed the week-instruction reading (valid_until 2026-09-27). |
| **SPEND PAST THE 95% STOP TONIGHT — do not hold work back to preserve the allowance** | Kam, panel 2026-09-20 ~21:2x *"Don't hold depending on the count, just keep going. If the credits run out, I'll sign in to a new account in the morning."* (with, in the same exchange, *"No problem if it's not ready in the morning. I would much rather it done properly than quickly."*) | **NO DATE STATED — it ends when he signs into the new account, which he said would be "in the morning" (Monday 2026-09-21).** Read as covering tonight's run only; **re-ask before assuming it on Monday.** Stated to him as that reading on the panel. | Launch what the work needs and let the gauge run down rather than holding items back. **Everything else is UNCHANGED and was said back to him:** the v1.3 signature classes still pause (production, money, external comms, anything irreversible), the QA gate still precedes every score, and spend is still REPORTED. This lifts a spend ceiling, not a boundary. Gauge was 90% when he ruled it and 91% at the second launch. |
| **DO NOT HOLD FOR THE USAGE GATE — he switches accounts near 100%** | Kam, panel 2026-09-21 ~08:3x *"Don't worry about the usage gate. I will log in as a new account as we get close to 100%. Please do everything you can to get Nexus AI ready for resubmission."* | **NO DATE. Tied to the ALLOWANCE, not the clock: it holds while he is willing to re-auth, i.e. through this resubmission push. RE-ASK if he goes quiet AND the gauge crosses ~99% without a new account appearing** — at that point the premise (he is there to switch) has gone. | **Lifts the 95% STOP only.** Launches this session pass `WED_USAGE_STOP=100` **with his quote as the recorded authority**, so the override is visible and attributable rather than silent. **Everything else is UNCHANGED and was not granted:** the v1.3 signature classes still pause (production, money, external comms, anything irreversible), the QA gate still precedes every score, no merge without a gate verdict at the head, and the RD-516 merge still waits on its own §5 acceptance clause (the 28 on main). **This lifts a spend ceiling, not a boundary.** Priority he named: **NexusAI ready for RESUBMISSION** — minimum set RD-516 · RD-518. |
| **We approve and merge our own TESTED Platform K work** | Kam, panel 2026-09-11 16:56:00 *"For the time being, I / you will approve our own elements"* + 16:56:44 *"based on this.  FIx and merge all tickets after they are tested"* (on Stuart's forwarded proposal) | **OPEN-ENDED — "for the time being"; stands until Kam withdraws it** | Approval = Kam or Wednesday's GO after the QA gate at head + Test Evidence; squash, author merges; kintsugi gets merged work; **demo = UAT, waits for Peter's formal test and nod (narrows the week deploy grant's demo half — told to Kam)**; raise-to-1 stays unapplied. Platform K only. `learnings/2026-09-11_secuura-we-approve-and-merge-our-own-tested-work.md` |

⚠ **ASSUMPTION ON THE DATE, FLAGGED TO KAM 2026-09-10 15:2x AND NOT YET CORRECTED:** "end of the
week" read as **end of Sunday 13 September** (Sunday IS the 13th; 2026-09-14 is a Monday — this file said "Sunday 14 Sep" until 15:4x on 09-10, granting a day nobody gave). If he meant Friday 11th or 12th, this grant died earlier than
this file says. **Ask before relying on it on the 12th or 13th.**


## When a grant expires

1. **Stop.** The permission is gone; the previous rule returns — for demo that is *"demo-affecting
   changes always pause for Kam"*.
2. **Do not renew it by inference.** A grant that was given once is evidence about that week, not
   about this one.
3. **Delete the row or move it below a `## Expired` heading with the date it lapsed** — never leave
   a dead grant looking live.

## Expired

### Lapsed 2026-09-23 ~23:47 AEST — its EVENT happened (moved here by the 17:0x Wednesday seat, per rule 3)
Round 20 is merged (11/11, #1202-#1212, verified at source) AND deployed to kintsugi (develop 6ab9d5021e96, verified on the running box by Seat B 23rd's V1-V13, KS-535 holding). The 90% cut applies again to every launch. Not renewed by inference.

| grant | given | EXPIRED | scope, exactly |
|---|---|---|---|
| **90% USAGE CUT LIFTED FOR ONE LANE: the round-20 Secuura raise seat (held Ornith passes → PRs → gate → merge → kintsugi)** | Kam, live board 2026-09-23 14:24:05 view=wednesday *"I sign those to the Claude agent then, and after you do merge, push, and deploy what you can."*; Wednesday's reading (incl. the usage lift, "same account, spends into the last 10%") said back 14:2x; Kam 14:25:35 *"Fantastic, thank you."* | **EVENT: ends when that lane's work is merged and deployed to kintsugi, or when he switches accounts / says stop.** Not renewed by inference. | ONE Secuura raise seat + its QA gates + the drafter already commissioned for its brief, launched with `WED_USAGE_STOP=100` and this row as the authority. **NOT covered:** any other lane or seat at the cut; demo (Peter's nod); KS-1250; production; money; external comms beyond rule-7. Deploy = KINTSUGI ONLY, his "deploy what you can". |

### Lapsed end of SUNDAY 2026-09-20 — moved here by the 19:5x Tuesday seat, per rule 3 above

**Both rows reached their stated date tonight (weekday and date checked against each other with
`date -j`: 2026-09-20 IS a Sunday).** The first one's PREMISE had already ended ahead of its date —
it was granted *because he would be away*, and he came back early, ruling cards on the panel from
~15:25 and again at 19:39–19:41 today. **Neither is renewed by inference.** Both are largely
Wednesday/Secuura-scoped (Ornith, KS tickets, kintsugi) rather than Datasec, and **nothing in this
seat's queue depended on either**: RD-516 / RD-518 / RD-464 r3 all run on the open-ended TESTED
grant, which is unaffected. If work wants either of these back, ASK.

| grant | given | EXPIRED | scope, exactly |
|---|---|---|---|
| **AWAY 2 DAYS: keep going; push, merge and deploy whatever is ready** | Kam, panel 2026-09-18 14:14:27 *"I'm going to be away for the next two days, so please keep going with tickets and activity while I'm away. Push merge and deploy whatever is ready. Whenever it's ready."* | **end of SUNDAY 2026-09-20** (derived with `date -j`: Fri 18 → Sat 19, Sun 20; back Mon 21) | Tickets and activity continue; merges on Wednesday's signed GO after a gate (the TESTED grant); **deploy = KINTSUGI only** (the weekend suits the rebuild); **NOT demo** (Kam 10:27, only proven + Peter's nod); the signature classes still pause (irreversible: KS-1250, KS-1175; money; external comms beyond rule-7). Full reading: `tasks/WEEK-INSTRUCTION.md`. |
| **Ornith q4 ONLY; volume across the whole KS Backlog/Todo** — ⚠ the "QA Sunday night, merge all at once" HALF was already SUPERSEDED by Kam 2026-09-18 09:15:10: *"Okay, don't wait until Sunday. Merge, push, and deploy everything that's ready and archive all the items that have been done."* The q4-only and volume halves stood until tonight. | Kam, panel 2026-09-15 16:36:04 *"lets use the smaller model for the rest of the week. complete as many tickets as possible. work with the local LLM. we will do QA on these Sunday night and merge / commit all at once"* | **end of SUNDAY 2026-09-20** (derived: 2026-09-20 is a Sunday) | held diffs only until Sunday's QA; auth/MFA/OAuth product edits stay out until he names them (Wednesday's reading 16:37). Lesson: `learnings/2026-09-15_ornith-q4-only-volume-week-qa-sunday-merge-once.md` |

**LIFTED AFTER 2 h 39 min — Kam, panel 2026-09-18 09:16:16, verbatim:** *"The credits have reset, so please start up all agents and continue the work."* The 06:37 no-Claude-agents restriction is **DEAD**; it never reached its Sunday expiry. `usage_gate.sh` re-checked at 09:17: **OK — weekly usage 5% < 90%, gauge age 3 min** (the reset landed and the gauge is publishing again). The four parked launches (#1034 gate · #1037 KS-1101 drafter · seat A 9th successor · #1036 + Seat B) are UNPARKED.

**The lifted row, kept for the record:**

| grant | given | EXPIRES | scope, exactly |
|---|---|---|---|
| **RESTRICTION (not a grant): NO Claude agents at all — local LLM ONLY** | Kam, panel 2026-09-18 06:37:13 *"we are at 92% can you move to no more claude agents and only using the local LLM until sunday"* | **end of SUNDAY 2026-09-20** (derived: `date -j` says 2026-09-20 is a Sunday; today is Friday 2026-09-18 — the weekday and the date were checked against each other, not assumed) | **No seats, no QA gates, no drafters, no successors.** This SUPERSEDES the 90% usage cut (`2026-09-14_at-90pct-weekly-usage-no-new-agents…`) in the strict direction: under that rule the ~08:00 allowance renewal would have reopened launching; under THIS one it does not — the renewal unparks nothing. **CANCELLED by it:** the 02:18 renewal sequence (#1034 gate · #1037 KS-1101 drafter · seat A 9th successor · #1036 + Seat B) — all four are Claude launches and are parked until Sunday, NOT until 08:00. Wednesday + Ornith continue. **OPEN QUESTION put to Kam 06:38, unanswered:** whether in-session research sub-agents (the Agent tool, used to search the board and size Ornith's next ticket) are included. **Until he answers, treat them as INCLUDED** — the safest reading of "no more claude agents", and the cost is a thinner hand-picked Ornith queue, not a wrong action. Lesson: `learnings/2026-09-18_no-claude-agents-local-model-only-until-sunday.md`. **⚠ SCOPE UNRESOLVED, ASKED 06:5x, UNANSWERED:** a Tuesday commit SUBJECT at 06:52 — fifteen minutes AFTER this instruction — reads *"Kam released the pause, RD-521 dropped, S66 launched"*, i.e. a Claude seat started on DATASEC. Read as a subject only (Datasec is Tuesday's). So either this instruction is WEDNESDAY/SECUURA-scoped and Datasec runs to its own rules, or Kam has moved and Tuesday holds the newer version. **KEEP HOLDING until he answers** — guessing loose spends the allowance he is protecting; guessing tight costs an idle weekend, and only one of those is recoverable. Do NOT infer a release from another seat's commit subject. |


**Lapsed at midnight 13→14 Sep 2026 AEST (moved here at the first Monday boot, 2026-09-14 06:52, per rule 3 above).** The v1.3 baseline returns: demo-affecting changes pause for Kam (demo = UAT, Peter's nod); no deploys without Kam's word; production is his signature class again (the 09-07 week grants — merge-for-the-week, deploy, production-ban-lifted — lapsed the same midnight per their `doctor.sh` expiry checks). The open-ended TESTED grant above still stands.

| grant | given | EXPIRED | scope, exactly |
|---|---|---|---|
| **Deploy freely to kintsugi AND demo** | Kam, email 2026-09-10 15:24 — *"Please deploy everything possible to kintsugi. Also deploy everything possible to demo. This rule stands until the end of the week."* | **END OF SUNDAY 2026-09-13 AEST** | Deploy MERGED work to both boxes. **"Everything possible" = what has merged to develop** — it does NOT authorise merging the 66 unapproved PRs, bypassing a gate, or `--no-verify`. Kintsugi first (his 13:22 rule). Production is untouched and does not exist. |
| **Both boxes end the week at PARITY** | Kam, panel 2026-09-10 17:10 — *"make sure that everything that we do this week is replicated and fixed on both servers."* | **END OF SUNDAY 2026-09-13 AEST** (same week as the deploy grant above) | Anything deployed/fixed on kintsugi this week lands on demo too, and vice versa. **This is a PARITY duty, not a new permission** — it does not widen what may be deployed ("everything possible" still = what has MERGED). If something lands on one box and cannot land on the other, that is a REPORT to Wednesday, never a silent asymmetry. |
