---
date: 2026-09-15
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 06:58 on 2026-09-15 by the seat booted 05:3x (the 50% checkpoint). Previous copy beside this file: .pre-0700-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **KAM'S LINE FOR THE WEEK (his words 2026-09-14 22:12 + 2026-09-15 06:51): "predominantly the local agent" · "keep working with the local model to close as many backlog and to-do tickets as possible" · batch Ornith's tickets and CHECK THEM ALL IN ONE PASS · the 90% weekly-usage cut (gauge 89% at 06:5x; `usage_gate.sh --check` before ANY launch; at/over 90 nothing new starts, in-flight finishes, then Wednesday + Ornith only) · no clock this week ("rotate and implement whenever ready").** Target line: KS active ≤ 60 by today (72 at 05:4x by `board_count.sh`; 12 to go — honest forecast 1–3 today under the cut).

> Narrative: `0_Brain/daily/2026-09-15.md` (the 05:59 boot block → onward). Yesterday: `2026-09-14.md` (18:58 block + the 05:3x retro).

## 🔴 STATE at 09:36 — read this first (the 65% checkpoint refresh)
- **Floor:** `%0` Wednesday · `%29` monitor ONLY — s233 wrapped 22:40Z (scored 1.00; `%61` closed). **The 90% cut is IN FORCE** (gauge read 90 at 08:2x): no new Claude seat or gate until the renewal (`renews:` on the statusline, ~Sat morning). Watcher runner patched (own-stuck-tap + read-back; idle-hash excludes the statusline). panel_sync live. Ollama live. Ornith loop job armed (900 s) + the 23:30 job; a mkdir run lock in `night/log/.night_run.lock`.
- **Product today:** #805 → **M55 `48e65c435`** (KS-726 Done + archived; KS-1171 filed for the residue). #995 (KS-741) READY tier 1 @ `b8155636e`, In Progress — **its gate is HELD for the renewal** (SET B of `briefs_staged/COMMISSION_2026-09-15_gates805r3-995-drafter.md` un-drafted); #922 T2 / #989 T1-delta / #927 gates likewise. **Board 71 active** (from 72 at boot; Kam's line ≤ 60).
- **Kam's rulings today (all receipted; verbatim via `kam_rulings_today.sh`):** 06:51 keep the local model closing backlog/to-do, batch + ONE-PASS check · 06:53 "fix this through process or management" (→ Ornith, per his 09:14) · 09:24 "How is it performing after the fix?" (answered measured) · **09:28 the STANDING RULE: every Ornith issue → a tooling or instruction fix (lesson `2026-09-15_ornith-every-issue-gets-a-tooling-or-instruction-fix.md`, W; ledger `2_Project_Files/local-model/IMPROVEMENTS.md`, 7 rows)** · **09:30 Wednesday writes the model's prompt from the ticket (`night/briefs/<TICKET>.md` replaces the description in the input)** · 09:32 "put this into effect and keep going".
- **ORNITH at 10:47 (the 70% checkpoint): six rounds today, every failure a ledger row — `2_Project_Files/local-model/IMPROVEMENTS.md` (15 rows).** Working combination: **a Wednesday-written brief (`night/briefs/<TICKET>.md`, now with its own `## Where` list of the exact lines to remove) + think=0** (think=1 + a brief over-thinks into the context wall; think=1 alone placed the fix right but partial). Harness built + red-proofed this seat: sampler (repeat_penalty 1.15 / repeat_last_n 512 / num_predict 32768); `--directory` for service-relative paths; FUZZY `-C1`; trailing-empty-line strip; **A3b** (must_change sites from the brief, refuses a hunk that leaves one); **A4 twin** (a red counts only with the CONTROL cells green and assertion reds — a `ReferenceError` in the test is refused as "not a real red"); 6a identifier self-check + test-path rule; 60 s settle + load bar 12 between tickets. **Best results so far:** KS-1087 round 3 produced the CORRECT product fix (test bug sank it); KS-1072 round 5 reached a genuine red-first (then left one old line → redeclare). **Round 6 running (`night/log/manual_2026-09-15_1045_round6.out`, wake armed in this seat) — read `night/done.md` + each run's `checker.out` in one pass; a PASS → Wednesday reads the diff → a Secuura seat raises the PR when the allowance allows; a FAIL → classify (model / harness / prompt) → fix where it lives → IMPROVEMENTS row.** **Kam 10:46: "what quant are you running. the 35b-a3q at q8_0 could work well and fit"** — measured: `ornith:35b` = Q4_K_M, 21.2 GB (qwen35moe 34.7B, 256 experts); registry tags read 10:5x: `ornith:35b-q8_0` exists (36 GB) — **PULL STARTED 10:5x** (`local-model/logs/pull_ornith35b-q8_0.log`, ~5 min at 117 MB/s; drive has 1.4 TB free). **Next after the pull: run the same three briefs on `ornith:35b-q8_0` (`NIGHT_MODEL=ornith:35b-q8_0`; the runner's G5 checks the tag; memory gate 30 GB — the q8 needs ~38 GB, so the headroom check may need `NIGHT_MIN_FREE_GB` raised or the other models unloaded) and compare per assertion rung against the Q4 rounds; keep the one that passes more; tell Kam measured.** Successor: `pgrep -f "ollama pull"` / the log tells whether the pull finished; `curl /api/tags` lists it when done.
- **Owed / candidates:** the no-rm hook is blind to `rm` inside a brace group after `||`; the idle-ack should key on the seat's transcript mtime (a pane hash drifts); `send_brief.sh` ADDENDUM blob-list refusal; the zsh-list ADVISORY hook; `panel_sync` scoreboard union-merge; WED-141; Dependabot close-and-rescope (board seat); the #995 gate at the renewal.
- **For Kam's read (no clock):** docker daemon DOWN on the Studio; node 24.7.0 < engines 24.11.0; Peter's #811 caution; #887 his; PS #759/#760 unmeasured; Peter merged #992–#994 + filed KS-1170.
- **Rotation:** band 80–90 at a safe boundary (agents live is fine — none are). Successor's first reads: this block → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check` → `night/done.md` + `IMPROVEMENTS.md`.

## ⚠ TRAPS
- zsh: `for x in $LIST` / `set -- $VAR` / `kill $PIDS` do NOT word-split — `while IFS= read -r` or literal args. The no-rm hook is LIVE (quarantine by `mv`) and blind inside brace groups — do not rely on it. The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. `cockpit.sh say` takes the pane NAME; `pane_close.sh` the `%id`. The no-cd hook refuses `git -C $VAR` and `git -C <other tree> fetch` — literal paths, read verbs only outside WEDNESDAY. Unquoted heredocs blank backtick phrases — `<<'EOF'` always. `panel_sync` SKIPs while untracked files sit in the tree — `git add` run dirs and logs before expecting a push; my `git push` is rejected while panel_sync is pushing — it rebases and pushes my commits within a cycle; verify by `merge-base --is-ancestor HEAD origin/main`. A wrapped seat's pane is closed in the SAME action as its wrap is read. Never run `wed_claim.sh` while panel_sync is live. Ornith's runner writes `done.md` rows; a FAIL at A1 with `done_reason: length` is a sampler loop, not a verdict.
