---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 04:50, refreshed in place at 05:30 and at 07:34 (the batch-gate launch) by the 04:3x/morning seat (ctx ~68; previous copies NEXT-PICKUP.md.pre-0921-0450 / .pre-0921-0430 / .pre-0921-0350; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 04:3x Monday seat, 50% checkpoint) — replace it, never append

**Kam:** 0 panel lines on 2026-09-21 as of 07:34 (morning brief posted 06:0x) (his last words 2026-09-20 21:5x: new account, "keep going with secuura tickets using both claude and local agents", then "see you soon"). He is expected back today and LEAVES MONDAY NIGHT — expect a new week-instruction (`WEEK-INSTRUCTION.md` is `status: lapsed`; receipt it, write it verbatim, derive the weekday). Usage 7d 16%, gate open. Quiet hours until 06:00 (no voice). Ledger 3c: 09-18 rows pass the 3-day line on 09-22. The EXPIRING-GRANTS "spend past 95% tonight" row said re-ask on Monday — moot at 16%, say so if it comes up.

### 🔴 IN FLIGHT (floor from `tmux list-panes` at 07:34: `%0` this seat · `%9` fleet-monitor · `%13` Seat B 12th HOLDING (ctx ~76) · `%14` QA/Secuura-batch1112 RUNNING)
1. **BATCH GATE #1112–#1118 LAUNCHED 07:34 (`%14`)** — launcher `fleet/qa-agent/launchers/launch_qa_secuura_batch1112-1118.sh` (542 lines; pins develop `362e51fe0` + seven heads by branch AND `refs/pull/N/head`; compare guard → rc 10 on a move), prompt `fleet/qa-agent/briefs/2026-09-21_secuura-batch1112-1118.prompt.txt` (789 lines, sha256 `365d4279dc691333…`, **read WHOLE by Wednesday**), gateset `fleet/qa-agent/gatesets/2026-09-21_gate1112to1118/` (README_FOR_WEDNESDAY.md, DRAFTER_REPORT.md, `mail_leads.out` = 17 leads, none resolved by Wednesday), `--check` rc 0 by Wednesday's own hand, `repin_and_launch.sh` rc 0 (usage 20%, `cockpit.sh add` rc 0, LAUNCHED 21:33:48Z), routing line `QA/Secuura-batch1112|coagent@agentmail.to|yes` added (backup `inbox_routing.conf.pre-0921-batch1112`). Report dir: `Testing Agent MAIN/projects/secuura/reports/2026-09-21-batch1112-1118-tier1-r1/`. **Rung 5 OWED on the next wake** (report dir / NOT-TESTED.written-first.md / pane content naming #1112). **Wake = the verdict mail** `[QA -> Wednesday] BATCH GATE #1112-#1118 …` (from coagent@) → read WHOLE → completion check vs the 17 by-name items → **signed GO, subject EXACTLY `GO: merge #1112-#1118 batch`** naming heads 3a28d2a3c · abf8321a9 · 762a70117 · b008489e4 · 9a485cfe7 · b3f94f14a · f132c9214, order A→B→C→D→E→G→F, targets 1/1/1/1/5/1/1 per FILE (PR E's five comma-separated, MG-2), every ticket STAYS In Progress, no tickets; then merges verified at source (`ls-remote` develop; `rev-parse ^{tree}` = the addendum's end-state tree = `6aa9873f974019a92574d6db52e6356734573c8c` if develop is unmoved); rule-7 bytes ruled; wrap → score → `pane_close.sh %13`; gate scored → `pane_close.sh %14`. A NO GO on one PR = one fix round for THAT PR only; the others merge.
2. **Seat B 12th (`%13`) HOLDING** — told by mail (20:31:57Z, verified + tapped) that the only GO is the DKIM mail with that exact subject naming the seven heads; at ctx ~76 it may hand over HOLDING before the GO (its D14) — a Seat B 13th then merges on the GO from its handover (`HANDOVER-seatB-12th-successor-2026-09-21.md`, method files under `5_Project_History/2026-09-21_seatB-12th/raise/` — merge13.py / targets13.py). Rung 10 expected at its prompt: detector first.
3. **Ornith: POOL DRY BY MEASUREMENT** (round 25: 0 un-read; rounds 20–25 cover every KS Backlog/Todo ticket). `PAUSE_QUEUE` carries the reason to 09:08 — re-arm or clear. **Next feed = this gate's NOT-PINNED rows** (commission a drafter on them the moment the verdict lands, the 04:00/04:44 shape: artefacts `runs/2026-09-21_gate1112rows-drafter-precheck/`), then the KS-1236/KS-1006 siblings after the seven merge. No search drafter is owed.
4. **HOLD = `python3 2_Project_Files/local-model/night/hold_ready.py <run-dir> <golden-precheck-dir|-> <ROWID> <TITLE-CAPS> --seat '<who>'`** (`--dry-run` first; refuses rc 2; byte-identical clause only from its own `cmp`). test_only-shaped: a bash_patch hold is scripted from the same cmp until the arm is added.
5. **Banked for a Seat B 13th: ELEVEN** — KS-880 LIVETENANTDEFAULT-1 · KS-753 VERIFIEDPERSISTED-1 · KS-1234 ALIASOTHERROUTES-1 + SECURITYMIDDLEWARESKIP-1 + ALIASUPLOAD-1 (ONE PR, any order, one sha `68c8a00b2c8b9624`) · KS-1223 WALLETFORWARD-1 (new) · KS-1223 REFERRALFALLBACK-1 (new, referral) · KS-1232 HTTPSERVERINFOEMPTY-1 + MCPINFORAWECHO-1 (two new mcp-server files) · KS-1273 EXITCODEENV-1 (bash_patch, tier 2, Refs KS-1273; patches #1117's tamper file — sequence after #1117 merges) · KS-957 F4-TOOLINGTOKENS-1 (new bash suite; tier 2; Refs KS-957 + KS-930, never Closes; re-anchor if `READY_KS-958` lands first). Brief the 13th AFTER the seven merge; its lanes are disjoint from the seven (re-check against the merged tree).
Tip: develop `362e51fe0db7e73d5557924902763fe3f10fd8c7` tree `2e981e7779dc` (unmoved at every read today). `inbox_routing.conf` carries -B, QA/Secuura-1105, QA/Secuura-batch1106, QA/Secuura-batch1112.

### DONE THIS SEAT (verified at source)
Boot ctx 33% (brain whole) · Seat B 12th rung 5 confirmed · four gate-row briefs verified + queued + PASS 8/8 + HELD (hold_ready.py, arms exercised) · Seat B 12th plan confirmation answered (gate rc 0, verified at destination, tapped, seat read it from its inbox) · doctor PAUSE_QUEUE leg verified built (3 arms) · ledger +1 typed clock · panel mirrored.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: `set -- $var` does not word-split; a refusable tool's rc is read on its own line, never through `| tail`. A loop's exit condition is ONE `grep -q`. Heredocs `<<'EOF'`, stamps by sed after. Every COUNT in a drafted brief re-derived or marked "drafter's count". Rung 10 after any READY/HOLD: detector first. A `done.md` waiter keys on the INPUT PATH + date. Every `git -C` is a LITERAL path (write multi-step git as a script file). A tag regex is `datasec` anywhere. A time inside a note body is "just before this line" or copied from the artefact's own stamp — never typed.

### OWED (mine, none blocking)
`note_entry.sh` typed-clock warn (bit again this seat — w≥3, build it) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · `derive_candidates.py` drops HELD/REALLOCATED rows · `night_run.sh`: a LOAD refusal must not consume the queue line (IMPROVEMENTS row 03:3x) · CHK-1 (correct the KS-1272 checker record) · `wake_watch` idle leg runs the detector itself (shared with Tuesday — claim via wed_claim.sh; stop the watcher before editing) · a script that re-counts every integer in a drafted brief · KS-1201 (`run-shell-suites.sh` leaves 4 login_stub listeners per run — ticket candidate for a board seat) · hold_ready.py: a red-set-mismatch arm (only refusal/golden arms exercised so far).

### ROUTE TO KAM (Monday 21)
0. **Booleans on the Cardano record as STRINGS "true"/"false"** (Wednesday's shape ruling; ints 0/1 the alternative) — his to flip before any anchor. **The deploy + first anchor for KS-1175/#1105 is his step.**
1. Whether his 2026-09-14 07:22 suspension of Wednesday→Tuesday messaging still stands (Tuesday is live on the mini — her ledger has rows dated today).
2. `Secuura/platform-s#877` unreadable — a permissions boundary, reported not worked around.
3. Four escalations on absent §5f runtime evidence: KS-577, KS-946, KS-1172, KS-1173.
4. `secuura-dependabot-triage` says "close the 5"; 10 open dependabot PRs now.
5. Carried: Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies (26 untracked in this tree today); seat A's launcher F-02 (inert — repo-local core.sshCommand works; every seat prints it); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; **O-1: `admin.ts` `requireAdmin` routes do no session check**; the KS-1283 coverage ticket; M-7 (anchoring.openapi.ts:253 restated regex — Polish, ticket candidate); **VIEW-NONSTRING-ARRAY (anchorReadback.ts:46-48 — a product fix, not a pin; ticket candidate)**; the un-raised 2026-09-16 `READY_KS-887` (ks869 test; disjoint from KS-880's hunk — a Seat B 13th candidate or archive).
6. Wednesday's reading to confirm: auth surfaces open to TEST-ONLY local-model work under "auth product EDITS stay out" (KS-1223, KS-880, KS-1283, KS-1244, KS-1198, KS-1006, KS-1236 all pinned on that reading).
