---
date: 2026-09-15
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 22:40 on 2026-09-15 by the seat booted 22:1x (the 21:0x seat's successor). Previous copy beside this file: .pre-2240-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words (all receipted): 18:19 NEVER IDLE — "extend the checker… action all backlog and to do from easy to hard. you act as a gate keeper" · 16:36 q4 ONLY, held diffs only, QA Sunday night + merge all at once (expires end of Sunday 09-20) · 19:44 KS-1172 deferred to Sunday, Stuart told on the ticket · 21:05 "Keep working with the local model, looks like promising progress especially when guided by you" · 18:23 he leaves MONDAY NIGHT 09-21 — the unattended loop must be BUILT and PILOTED by Monday morning. Speak in the FIRST person on the panel.** A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.

## 🔴 STATE at 22:40 — read this first
- **Floor:** `%0` Wednesday · `%29` monitor ONLY (+ a scratch `rtest` tmux session — harmless). Usage gate CLOSED (7d 96%, renews Sat ~11:xx AEST): no Claude seat, gate or drafter; Ornith (q4) is the only worker. Origin contains HEAD at the last push (commit the launcher-regenerated digests at boot, then push — see TRAPS).
- **RUNNING at 22:40: KS-1074 Part C** (the poller's SIMULATED writer, `briefs/split_1074C`, queue file in the 22:1x seat's scratchpad — if that scratchpad is gone, re-queue from the brief: `NIGHT_BRIEFS_DIR=night/briefs/split_1074C` + a one-line queue `KS-1074 product=Blockchain/Dev/services/originate/src/services/anchorStateSync.ts ref=Blockchain/Dev/services/originate/src/__tests__/ks587-document-blob-simulated.test.ts line=270 ctx=49152`). Read its verdict in `night/done.md` (the last KS-1074 line) → READY (Parts A+B already READY; A+B+C = ONE PR) or fix-where-it-lives.
- **THE POOL IS NOT DRY — the derivation was.** `derive_candidates.py` EXCLUDED 152 tickets as "names no product file" (its predicate wants a `services/…` path in the description); a title read of all 152 at 22:2x (Linear, paged, real count) found code-shaped tickets it had hidden — including KS-1097 (done tonight) and KS-794 (done tonight). **Widening owed for the Monday loop:** resolve a route (`POST /api/…`), a symbol or a filename mentioned in the description to a file at the tip (`git grep` in the source checkout, read-only) before excluding. Until then: **read the 152's titles** (query `number:{in:[…]}` over the ids in `candidates.md`'s EXCLUDED section) and pick by hand.
- **NEXT BRIEFS, easy → hard (per 18:19; each read at the tip before briefing):** (1) **KS-999 item 1** — `return await fromRow(result.rows[0])` in `getUserById` (`services/auth/src/repositories/userRepo.ts`, one word) + a cell pinning D1 → `ServiceUnavailable` on a `fromRow`-side rejection (reference `ks949-platform-admin-seed-identity.test.ts`, whose "UNAWAITED fromRow" cell asserts only `resolves.toBeTruthy()` — item 3 renames it). **auth SERVICE but not auth LOGIC** — Wednesday's reading of Kam's 16:40 "no auth ones": held to LAST; brief it only when the non-auth pool is dry, and say so in the header. (2) **KS-1028** — the originate erasure step-12 throw skips the USER_ERASED fan-out after the crypto-shred: option (b) "wrap step 12 so the fan-out still fires and the DSR failure is raised separately" is the smaller of the ticket's two; read the erasure function first (likely a large function with DB mocks — may be a Claude-seat item). (3) **KS-934** — m365 `/api/teams/notify` serial loop with no aggregate bound: the ticket offers three shapes (LIMIT+paging / aggregate deadline / off the request path) — DECISION-class → card with a default (aggregate deadline, the smallest), then brief. (4) **KS-1102** — three unauthenticated system-status routes publish internal URLs/ports/versions/key state: gate behind admin auth OR serve a stripped public variant (the `/status/` page reads `/system/status`) — DECISION-class → card. (5) T5 split vein from `candidates.md`: KS-1055 (needs the KS-1125-shaped pg fake — check first), KS-580 (two files + design), KS-953 (decision-class: three shapes). SET ASIDE with reasons (do not re-propose): KS-753 (no in-process seam — `index.ts:838` unconditional `app.listen`; first Claude-seat item after Sunday), KS-1125 (`Module._resolveFilename` harness), KS-1111 (unruled masking shape), KS-755 (diagnosis-first), KS-981 (frozen #892 branch), KS-1076 (item 1 CONFIRMED fixed on develop), KS-1114/1129/757/979/980/1159, KS-777 (record defect → Done close Sunday), KS-807 (decision-class, rec A recorded), KS-683 (done bar Layer 4), KS-759 (type-only: no cell can red it under ts-jest's non-typecheck of the product), KS-746 (multi-file + migration), KS-692 (cross-tenant revoke — authorization surface, LAST), KS-1121/629/975 (carded). Auth/MFA/OAuth LAST.
- **Held (READY_*): 51 files = 49 DISTINCT PINS across 31 ticket ids (32 with KS-1173)** — counted from the filenames' ticket/pin tokens (KS-1120-F2 and KS-1171-8j carry a q4 AND a q8 copy — count pins, never files). This seat added: **KS-794** (option 1 — `fileSize` optional int on the two BASE schemas; PR NOTES: amend the two NOTE descriptions at `originate.openapi.ts:2067/:2116`, regenerate the yaml + `check:openapi`), **KS-1074-B** (reconcile writers) + **KS-1074-A** (poller confirm writer, per-write `getDocument` read — Wednesday's decision recorded in the READY). **The raising seat's brief is STAGED (not sent): `2_Project_Files/fleet/briefs_staged/secuura_raise_ornith_ready_diffs.md`** — bundles 1–26 current to 22:1x; **ADD bundles 27 (KS-794) and 28 (KS-1074 A+B[+C] → one PR)** before Sunday; re-derive the ⟲ facts at send time.
- **HARNESS THIS SEAT:** nothing changed in the checker; one brief rule learned (IMPROVEMENTS row 87): a 🔴 cell on a field the tip does NOT declare reaches it with optional chaining (`shape.fileSize?.isOptional?.()`) so the tip reds by ASSERTION — A4 refuses a TypeError red. RETRY-ONCE carried Parts A and B (an A2b placeholder; a load error at the tip) — both PASSed on the retry, so the retry feedback is doing real work: count it at the consolidation.
- **DOC BRIEF RULES (unchanged from the 21:0x seat — put every one in the next doc brief):** an edit inside a hard-wrapped run is a WHOLE-RUN `-`/`+` replacement, every physical line named; the hunk's context is PINNED away from dense-markup lines and any template/repeating block; a bullet line begins `- ` so its diff lines read `-- …`/`+- …`; a `## Required` token must not contain a comma; sections are `## ` to the next `## ` measured on the TIP file.
- **UNATTENDED LOOP (Monday deadline):** `night/derive_candidates.py` exists but under-derives (above); the 15-min loop job takes `night/queue.md` lines; `night/daily_receipt.sh [--post]` exists (not scheduled — a launchd job + doctor/PORTABILITY items when wired); MISSING: the resolver widening, the briefs-a-day-ahead batch (the only human-shaped step), the receipt scheduler.
- **For Kam's read (no clock):** KS-1172/1173 activation waits for Sunday (his 19:44); `iogpu.wired_limit_mb` persistence; docker daemon DOWN on the Studio; node 24.7.0 < engines 24.11.0.
- **Rotation:** band 80–90 at a safe boundary, Ornith running through it. Successor's first reads: this block → `night/done.md` tail → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check`.

## ⚠ TRAPS
- **COMMIT THE TWO REGENERATED DIGESTS AT BOOT** (`0_Brain/learnings/_boot_digest*.md` — the launcher rewrites them): `panel_sync` SKIPS its rebase+push while any tracked file is dirty. Then `git -C /Volumes/DevMASTER/WEDNESDAY push origin main` yourself and confirm `merge-base --is-ancestor HEAD origin/main`.
- **A launch while the previous runner is in its 60 s post-ticket SETTLE exits 0 on the LOCK and consumes nothing** — poll `night/log/.night_run.lock/pid` with `kill -0` until it clears, THEN launch. A queue line is MOVED to `done.md` when its run ends — a re-run needs a fresh queue line.
- **`python3` read-then-write: `open(p,'w').write(open(p).read()…)` TRUNCATES before it reads** — read into a variable first (bit this seat once: a brief written 0 bytes, rewritten).
- **NEVER edit `night/*.sh` or `tasks/*/checker.sh` while a runner is live**: write `<file>.new` and `mv` it over. `git -C $VAR <write verb>` is REFUSED by the hook — literal paths; `rm $VAR` refused — `mv` to the scratchpad. macOS has no `setsid` (use `nohup … </dev/null &`) and no `timeout`. zsh: `for x in $LIST` / `kill $PIDS` do NOT word-split. The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. The chat-store hook refuses ad-hoc `chat_log.json` reads — `kam_msgs.sh` / `kam_rulings_today.sh`. `<<'EOF'` always; **any clock in a row/brief/panel line is `$(date +%H:%M)` substituted by the shell**. Waiters on the runner poll the LOCK PID (`kill -0`), never `pgrep -f night_run`. Split briefs share a ticket id → separate `briefs/split_<id><X>/` dirs + `NIGHT_BRIEFS_DIR=` + an OWN `NIGHT_QUEUE=` file; `NIGHT_DONE=night/done.md` explicitly. Ornith: `done.md` rows are verdicts; a re-check runs from a scratch copy; every FAIL gets an IMPROVEMENTS row + a fix where it lives, same session.
