---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 20:04 by the 16:4x Monday seat at its ROTATION HANDOVER (ctx ~81, band 80-90; previous copies NEXT-PICKUP.md.pre-0921-*; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 16:4x Monday seat, rotation handover) — replace it, never append

**Kam:** LEAVES TONIGHT; his last lines on this tab 15:43 (live board), then TERMINAL lines 18:4x–18:5x (the portable drive: "keep going", then "copy the whole thing and do the same on Wednesday after both NAS syncs"). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27 = Wednesday's reading; return day unanswered). He types on the LIVE board (view tags; `kam_msgs.sh` defaults `--source live`; on a poller wake read `kam_msgs.sh N` with N = the tapped-rows count in `fleet/cockpit/logs/live_chat_poll.log`). Usage 7d 36%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at the next checkpoint (rows(ledger)+rows(archive) conserved).**

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at 20:04: `%0` this seat · `%9` monitor · `%18` Seat B 14th HOLDING · `%20` batch gate `QA/Secuura-batch1130`)
1. **BATCH GATE #1130–#1135 LAUNCHED 20:04 (`%20`, `repin_and_launch_1130.sh` rc 0: develop `9f0265eb0` unmoved, six heads == pins and OPEN by the PULLS API, usage 36%, launcher `--check` rc 0 by Wednesday's own hand at 20:2x, prompt 931 lines / 125,767 B read WHOLE by Wednesday, `cockpit.sh add` rc 0).** Gateset `fleet/qa-agent/gatesets/2026-09-21_gate1130to1135/` (README, DRAFTER_REPORT, the six READYs captured by id). **Rung 5 OWED on the successor's first wake** (the pane was on its alternate screen at launch — an empty capture is the screen, not an absence; grep the pane for `#1130` / `report.md` / the six heads). Report dir: `Testing Agent MAIN/projects/secuura/reports/2026-09-21-batch1130-1135-tier1-r1/`. **Wake = the verdict mail `[QA -> Wednesday] BATCH GATE #1130-#1135 …` (~2–3 h; time-box 180 min).** THEN: read it WHOLE from the mail; assert `report.md` on disk BEFORE the mail (sha256 + bytes quoted in the mail) with its `## MERGE ADDENDUM` (six lines `- #<n> …`; targets 1/1/2/1/1/1 per FILE, #1132's two comma-separated); completion check vs the SEVENTEEN by-name items; re-read develop + the six heads at origin by own `ls-remote` in the GO's action; **signed GO** (`briefs_staged/2026-09-21_seatB14_go_1130-1135.md`, subject EXACTLY `GO: merge #1130-#1135 batch`, every head in the body, `BASE_GO` = develop, merge order = the gate's (default 1→2→6→3→5→4; PR 3 before PR 5 on their shared file), all seven tickets STAY In Progress, NO deploy) → `send_brief.sh --kind answer` → verified at secuura-blockchain@ → `cockpit.sh say Secuura/Blockchain-B '<pointer>' --mail 'GO: merge #1130-#1135 batch'` (by NAME) → gate pane `%20` closed via `pane_close.sh` (detector first: a rung-2 ghost is expected) + gate scored → the seat's STATUS "merged" → **verify at source** (`ls-remote` develop; `rev-parse ^{tree}` == the all-six tree `60bd96e7078c41bbd71b3e0d7e15f815f70b0b1b` if develop is still the GO's base; `rev-list --count 9f0265eb0..<new>` = 6; read verbs only) → rule-7 bytes to Wednesday first (KS-485 @peter, KS-772 @stuart.jamieson, facts-only test blocks) → its wrap → **score + `pane_close.sh %18` in ONE action**. A NO GO on any PR = a fix round for THAT PR only (round 2 of 2 under the cap). Rung 10 at the holding seat after any mail: detector first.
2. **Seat B 14th (`%18`) HOLDING since 09:34Z at ctx ~80** (handover `HANDOVER-seatB-14th-successor-2026-09-21.md` on disk, 10,564 B; its GO watcher polls its inbox on the pane tag every 60 s). If it dies at 100% before the GO: retire by hand (`tmux kill-pane` after the on-disk check — never `cockpit.sh rotate` on a wrapped/holding seat), and brief a **Seat B 15th** from that handover to merge on the same GO (the 13th→14th brief shape; the six heads; targets15/dry15/merge15 already re-keyed in `5_Project_History/2026-09-21_seatB-14th/raise/`).
3. **Ornith:** pool DRY by measurement (round 25 read every Backlog/Todo description; 0 KS tickets created since 09-20 20:36Z, re-checked 19:5x); `PAUSE_QUEUE` to 21:44 with the reason — re-arm at each checkpoint until the gate's NOT-PINNED rows land (the next feed; a brief-writer drafter per row, `hold_ready.py` holds each PASS). **The 14th drafter's census: 68 content-absent UNAPPLIED older READYs** (`…successor14.DRAFTER_REPORT.md` §7, per-row recommendations) = the Seat B 15th/16th raise pool, each row verified (strict apply at the tip, task type, product bytes) before it is briefed — a later brief, drafted by a subagent, every count re-derived.
4. **Live-board poller** `live_chat_poll.sh --seat wednesday` pid 14963 (health `fleet/cockpit/state/live_chat_poll.health`): verify `pgrep -f cockpit/live_chat_poll.sh` + a fresh OK line at boot.
5. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). `reconcile_rulings.py` at every checkpoint.

### DONE THIS SEAT (verified at source)
Boot ctx 32 (brain whole) · board swept before briefing · the "19 banked" corrected by measurement (5 + 2 candidates) · `hold_ready.py` T3 fix (4 arms, 8031f57b3) · Seat B 14th brief (drafter; every count re-derived; three week-instruction lines corrected) sent + launched `%18`; plan confirmed (KS-887 separate PR 5, KS-958 PR 6 T1 — SIX PRs); PR 1 leg-14 refusal ruled (harness fault resumes the round); six READYs #1130–#1135 read with heads re-read at origin each; hold mail with the channel discriminator; the batch gate drafted (subagent) → prompt read WHOLE → `--check` → launched `%20` · Kam's live-board Tuesday-tab refusal FIXED (client self-heal on the addressed-seat-key 400; 4 arms + red on pre-fix; zip-deployed via the new `04c_zip_deploy_only.sh` because `04_deploy.sh`'s `az webapp update` hits a `NoRegisteredProviderFound` api-version 2026-08-01 refusal — OWED; live probes 70/70 after fixing H6's stale synthetic-row predicate; Tuesday's seat proved Kam's 18:02 reply end to end) · portable drive: blind copy DONE 19:13 (1,422,960 files, 1.43 TB, rc 23 = 12 tool-bundle symlinks only) + TUESDAY/WEDNESDAY priority copy (counts verified); Kam told · Kam's 09-23 re-copy instruction recorded (OWED 0) · 2 ledger rows (rung 10 ×1; the poller/T3 rows earlier) · panel receipts within the minute; ~12 pushes HEAD == origin.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad (literal paths); no `sleep N; cmd` chains (Monitor/run_in_background); `set -- $var` does not word-split; a refusable tool's rc on its own line; never `echo =====X`; `!SYNC` single-quoted. `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only); a subject with `hold`/`STOP` mid-string is refused by the token gate — reword. `cockpit.sh launch Secuura/Blockchain-B` works (registered); pane ids from `tmux list-panes`, never `launched:`. Taps by pane NAME (`%id` refuses silently). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. `hold_ready.py` copies the checker's T3 line and refuses 'strict' on a non-empty `apply_strict.out`. The live-dashboard deploy path is `dashboard-cloud/scripts/04c_zip_deploy_only.sh` until `04_deploy.sh`'s api-version refusal is understood. Every count in a drafted brief re-derived or marked "drafter's count".

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. `04_deploy.sh`: `az webapp update`/`config set` fail with `NoRegisteredProviderFound … api-version 2026-08-01` (azure-cli 2.81.0 vs australiaeast) — diagnose (pin the api-version or upgrade/downgrade the CLI); 04c is the interim · `wake_watch.sh` idle leg runs `pane_prompt_check.sh` and puts the verdict in the wake text (rung 10 ×4 today; shared: claim, stop, edit, `--once`, re-arm) · doctor.sh: live-poll health + the dashboard venv item · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · MANIFESTQUARANTINESTDERR + SYSTEMTESTPUSHUNGATED ticket candidates (the gate's leads) · NAS tomorrow-check (`scheduler/state/nas_sync_last_wednesday.txt`) · `derive_candidates.py` misses `Blockchain/Testing/` · Tuesday's line for Kam (the vault note overwrite; "pull before every vault commit") · Ledger 3c on 09-22.

### ROUTE TO KAM (sent 14:0x + 16:49 + 17:38 + 17:40 + 17:5x + 18:5x + 19:13/19:14; add only what is NEW — one message when he engages)
NEW since: nothing. Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (a pool, not a question).
