---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 01:20 by the 00:05 Tuesday seat (post-rotation, overnight; ctx ~60 at the write; previous copy NEXT-PICKUP.md.pre-0922-0119; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 00:05 Tuesday seat) — replace it, never append

**Kam:** TRAVELLING (left Monday night); his last live-board line 15:43 09-21. `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27, Wednesday's reading; return day unanswered). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`; poller pid 14963, health `fleet/cockpit/state/live_chat_poll.health` — `pgrep -f cockpit/live_chat_poll.sh` at boot). Usage 7d 43%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at a checkpoint (rows conserved).** `night/ALLOW_SEATS` re-armed to END OF SUNDAY 2026-09-27 (epoch 1790517599) on the week instruction — seats and Ornith run together.

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0`: `%0` this seat · `%9` monitor — NO agent pane; the gate15 round is CLOSED end to end)
1. **DONE THIS SEAT, verified at source:** #1136–#1146 (ten, #1138 foreign) gated (ten GO WITH FINDINGS, Majors 0) → signed GO → ALL TEN MERGED → origin develop **`64ab105132eada0621622acf4d6053bc59926780`**, tree `87b4aa12d2ebae335f11790ceed9158f7d5614ec`, `rev-list --count b192ffd4a..64ab10513` = 10, 11/11 addendum blobs at the tip → rule 7 POSTED (KS-485 `07503fcd-93f1-4427-ba92-c96b1e52cd3f`, KS-772 `035cb517-f5c9-4763-8ab0-3c6d5b8ff4c2`) → gate `%23` + Seat B 15th `%22` closed via `pane_close.sh`, both scored 1.00. The seat REPAIRED `raise/merge16.py` (MG-4 helpers restored from merge15 :22-:35, MG-5 key-free boilerplate; pre-fix copies beside) — the 16th inherits the REPAIRED tool.
2. **Seat B 16th raise brief — a DRAFTER is running (Agent tool, commissioned ~01:18; dies with this seat if it has not delivered).** Commission: `fleet/briefs_staged/2026-09-22_raise_seatB_successor16.COMMISSION.md` (exemplar = the 15th's brief; the 31-READY R15 pool at 64ab10513; supersession/DROPPED; one PR per FILE; a two-seat partition B + C if ≥4 PRs each side; RULED sections; HOLDS + STANDING_LINES; dry-run rc 0; COUNTS). Deliverables: `briefs_staged/2026-09-22_raise_seatB_successor16.md` (+ `.subject`, `.COUNTS.md`; maybe `2026-09-22_raise_seatC_16.md`). **NEXT: re-derive EVERY count in the BLUF/PROVENANCE by own commands (the 09-20/09-21 rule — no sample), read the brief(s) WHOLE, `usage_gate.sh --check`, then `brief_and_launch.sh` per seat (a second seat = `cockpit.sh add Secuura/Blockchain-C <launcher>` + a routing line in `inbox_routing.conf` in the SAME action); plan confirmation → ANSWER; READYs → the batch gate (the gate15 gateset shape: commission a gate drafter from `gatesets/2026-09-21_gate15_docs_comments/COMMISSION.md`, re-pin at launch); verdict → completion check at source (report sha, addendum parse, blobs) → signed GO naming every head → merges → verify at source → rule-7 bytes → score + `pane_close.sh` in ONE action.** If the drafter died with the seat: re-commission from the same COMMISSION file.
3. **Ornith:** KS-1227 round 2 of 2 (its one rebrief — a MODEL serialisation FAIL at T3 in round 1; IMPROVEMENTS row of 01:1x) running/ran on the loop — read `night/done.md`: a PASS → `hold_ready.py <run> <golden 2026-09-21_r15feed2-drafter-precheck/1227TESTONLYWITNESSTRYFINALLYPIN-R15> TESTONLYWITNESSTRYFINALLYPIN-R15 R15-TESTONLYWITNESSTRYFINALLYPIN --seat …`; a second FAIL → the ticket goes to a Claude seat (the counter), never a third round. **The queue is otherwise EMPTY — the standing rule (09-18, constantly working) is being broken the moment r2 ends.** Widening moves, in order: (a) census15 FEED T (24 product-bytes rows, `briefs_staged/2026-09-21_census15*` §5c) — Wednesday's TIER call owed (test-only vs product; auth product edits stay OUT); (b) a candidates drafter over `night/candidates.md` (GENERATED — round notes go to `night/candidates_rounds.md`) for the next briefable rows, easy → hard; (c) the gates' NOT-PINNED rows (gate15: none). Every queued row needs `night/briefs/<id>.md` (brief-less inputs fail A4 RED-FIRST).
4. **Morning receipt to Kam on the LIVE board at ~06:00 (`chat_reply.sh`; first person; BLUF; short):** merged today (#1136–#1146 verified; develop 64ab10513); Ornith (FEED 2: 17 PASS held, 1 FAIL → r2; the R15 pool 31 → the 16th raise); blockers + cards (`secuura-ks1175-kintsugi-deploy-and-first-anchor` default c; `secuura-ks721-commitment-cannot-reach-a-real-chain` default a); skipped items. `reconcile_rulings.py` at every checkpoint (last 00:06: nothing to reconcile).
5. **Live-board poller** pid 14963 — `pgrep` + a fresh OK line at every boot.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad; no `sleep N; cmd` chains (run_in_background from a script FILE); a refusable tool's rc on its own line; NEVER `pgrep -fl` the wake_watch runner. **`safe_push.sh` stages ONLY the paths named on its command line (+ decisions.json) — name every modified tracked file too, or "committed" carries only the new files (this seat's 00:1x slip).** `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. Mail body whole = `inbox_digest.sh full <inbox> '<message-id>'` into a scratch file, then Read. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only; no STOP/HOLD token mid-subject). Taps by pane NAME with `--mail` (verifies at the destination first). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. Every count in a drafted brief re-derived or marked "drafter's count". `lsof … | grep -i node` matches the header's NODE column — drop the header first. `set -- $var` does not word-split in zsh (use python). The loop kick = `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`; the loop runs max 4 tickets per fire and re-fires every 15 min — "runner not running" between fires is by design.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. Ledger 3c (09-18 rows → archive) · `hold_ready.py` bash_patch support (KS-910 held by hand; `KeyError: test_file`) · checker T1 `ESCAPED-NEWLINES` refusal (the KS-1227 class; red arm = `runs/2026-09-22_ks1227-ornith35b-night/out.md`) · checker header-rewrite candidate (`--recount` class, 11/14 + 4/13 today) · KS-1192 rebrief (backslash-free literal) · FEED T tier call · `wake_ack.sh` keys on the detector verdict class · `04_deploy.sh` api-version refusal · doctor.sh: live-poll health + dashboard venv · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · SYSTEMTESTPUSHUNGATED + PLACEHOLDERPINSHAPE + STDERRTAILONABORT ticket candidates · doctor warns on an expired `PAUSE_QUEUE` · `derive_candidates.py` misses `Blockchain/Testing/` · Tuesday's line for Kam (the vault note overwrite) · INDEX.md refresh + the projects' history skim (deferred by the overnight seat to the morning sweep).

### ROUTE TO KAM (nothing sent this seat — he is travelling and quiet; the morning receipt is item 4)
NEW since his 15:43: the ten merges #1136–#1146 verified + rule 7 posted; FEED 2 17/18; the 16th raise in drafting. Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (O 36 / R 17 / T 24 / D 11 — R now in the 16th's pool).
