---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 14:06 by the 13:5x Monday seat at its 50% checkpoint (previous copy NEXT-PICKUP.md.pre-0921-*; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 13:5x Monday seat, 50% checkpoint) — replace it, never append

**Kam:** back today, LEAVES TONIGHT (a longer absence). His Monday list went to him as ONE panel message at 14:0x (week instruction first; cards ks1175 (rec a, default c) + ks721 (rec a = default); two readings — Tuesday mail = board coordination only under his 11:43 word; test-only pins on auth surfaces allowed). `WEEK-INSTRUCTION.md` is `status: lapsed` — when he gives the new one: receipt within the minute, write his words VERBATIM under `given:`, derive the weekday with `date -j`, set `status: live` + `valid_until`, say the reading back. **If he gives none, the default (told to him): his 2026-09-20 21:5x standing word — Secuura tickets with Claude + local agents, merges on Wednesday's signed GO after gates, kintsugi only, nothing irreversible, a morning receipt on the panel.** His last line on this tab: 12:50 (Phase 3 asks — commissioned). Usage 7d 29%, gate open. Quiet hours 23:00–06:00 (no voice). Ledger 3c: 09-18 rows pass the 3-day line on 09-22.

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at 14:0x: `%0` this seat · `%9` fleet-monitor · `%15` Seat B 13th · `%16` QA/Secuura-batch1119)
1. **BATCH GATE #1119–#1128 RUNNING in `%16`** (launched 03:59:36Z by `repin_and_launch.sh` rc 0; prompt `fleet/qa-agent/briefs/2026-09-21_secuura-batch1119-1128.prompt.txt` read WHOLE by Wednesday; develop `7be81d5c9` unmoved; ten heads == pins). Time-box 210 min → verdict expected ~07:30Z (17:30 AEST). **Wake = the verdict mail `[QA -> Wednesday] BATCH GATE #1119-#1128 (ten PRs; tier 1 = #1124, #1125, #1126, #1127, #1128) — …` from coagent@; report at `/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-21-batch1119-1128-tier1-r1/` (report.md BEFORE the mail; its `## MERGE ADDENDUM` is what targets14.py reads).** Then: read report.md + the mail WHOLE → completion check vs the ten READYs (heads e9e20196f · 2a66cd17e · 939de1ba5 · 9aa5442ae · c346999ad · bd907c553 · c50c0a8d4 · b23ad259a · f0cc0aadc · e35b5ddc2, every one re-read at origin by `ls-remote refs/pull/N/head` before the GO) → a NO GO on any PR goes back to Seat B for ONE fix round on THAT PR only (round 1 of 2) → signed GO mail `GO: merge #1119-#1128 batch` naming EVERY head + `BASE_GO` (develop re-read in the same action) via `send_brief.sh` (gate rc 0, verified at secuura-blockchain@, THEN `cockpit.sh say %15 … --mail`) → the seat merges one at a time (merge14.py) → Wednesday verifies at source (`ls-remote` develop + `rev-parse <sha>^{tree}` == the addendum's end state) → rule-7 bytes ruled → wrap → score → `pane_close.sh` in the SAME action → the gate's NOT-PINNED rows become Ornith's next feed (brief-writer drafter; every PASS held with `hold_ready.py`). **Rung 10: after any HOLD, expect a fabricated `[Wednesday tap] GO mailed …` at `%15`'s prompt — detector FIRST on every idle wake; the seat's discriminator is its inbox + DKIM + the ten heads, never a string.**
2. **Seat B 13th `%15` HOLDING** ten READYs (ctx ~80 at its last STATUS; its handover `5_Project_History/HANDOVER-seatB-13th-successor-2026-09-21.md` is in the HOLDING state; if it wraps before the GO, a successor merges on the same GO — `cockpit.sh launch Secuura/Blockchain-B` with a SUCCESSOR brief carrying the GO). Its idle wakes are acked when the detector says prompt empty and the inbox has no GO (last ack 14:0x, hash 4ff05a4b2dac).
3. **DASHBOARD PHASE 3 BUILDER IN FLIGHT** (an Agent-tool subagent — it DIES with this seat; its files land early): brief `2_Project_Files/dashboard-cloud/BRIEF_2026-09-21_phase3.md` (read it WHOLE — it is the commission); report `dashboard-cloud/REPORT_2026-09-21_phase3.md` (check its mtime + tail to see which piece it reached: (a) multi-recipient envelope + live readers, (b) kam-laptop + kam-ipad keys + re-wrap migration, (c) cut-over readers + watcher poller script). If it died mid-way: recommission ONE builder to FINISH from what is on disk (same brief, "resume from the report's last log line"). **Wednesday's verification before Kam hears "done":** identity re-asserted; probe matrix `dashboard-cloud/scripts/05_probe_live.sh` re-run by her hand against the live URL; `07_secret_scan.sh` CLEAN; `git ls-files` shows no key; migration counts re-derived (before/after per partition); a sample row decrypted with EACH new key by her own command; `git diff` reviewed; commit; then Kam ACTION FIRST (key file paths under `4_Credentials/dashboard-cloud/`, one import step per device: laptop = pick the file in the key bar; iPad = Safari import-once). Claim held: `External dashboard PHASE 3` (release when verified). Tuesday's wiring shape → a coordination mail (his 11:43 word covers board coordination; no Secuura content).
4. **Ornith:** queue EMPTY, runner idle since 10:02; `PAUSE_QUEUE` to 16:00 with the reason (pool DRY by measurement — round 25 read all 141 remaining Backlog/Todo descriptions; KS-1274 REJECTED twice (third-file/tier); 16 READYs banked: 14 in the 13th's PRs + KS-1236/KS-1006 pair for a Seat B 14th). At 16:00 the G7 tap fires: re-measure (KS created since 06:36; control 5 since 09-19) and re-arm with the reason, or feed from the gate's NOT-PINNED rows once the verdict lands. For any NEW feed: Wednesday verifies before queueing (tip == origin by ls-remote; key set vs `test_only_1198SKMETA-1.json`; every tamper From byte-matches the tip count 1 + mutated control 0; `+` ASCII; collisions vs the banked READYs), appends the queue lines + comment, `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`, arms a waiter FROM A SCRIPT FILE (`grep -q` per input path + today), holds each PASS with `hold_ready.py <run> <golden-dir> <ROWID> <TITLE> --seat …` (dry-run first; explicit calls — zsh `set -- $var` does not word-split).
5. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c: nothing deploys/anchors) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). Both told to him 14:0x. `reconcile_rulings.py` at every checkpoint (report mode; `--apply` only this scope; a `note:` tap is flagged, never auto-applied).
Tip: develop `7be81d5c9b109959b559e03652fb092c12de58e8` tree `6aa9873f97` (ls-remote 03:58Z; re-read at every GO). `inbox_routing.conf` carries -B and `QA/Secuura-batch1119`.

### DONE THIS SEAT (verified at source)
Boot ctx 32% (brain whole; notes/INDEX bounded and stated) · batch gate #1119–#1128: README + prompt read whole, `--check` rc 0 by own hand, launched `%16`, rung 5 read · Seat B idle wake: detector empty, acked · Phase 3 claimed + briefed (durable path) + ONE builder launched · Kam's Monday list sent as one message · INDEX.md head refreshed · WED/KS counts via `board_count.sh` (the `lesson` zero validated client-side).

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: `set -- $var` does not word-split; a refusable tool's rc is read on its own line, never through `| tail`; no `sleep` chains — a wait is `run_in_background` with an `until` loop. A loop's exit condition is ONE `grep -q`. Heredocs `<<'EOF'`, stamps by sed after; never `echo =====X` (a leading `=word` is a command lookup in zsh — bit this seat at boot, harmless). Every COUNT in a drafted brief re-derived or marked "drafter's count". Rung 10 after any READY/HOLD: detector first. A `done.md` waiter keys on the INPUT PATH + date. Every `git -C` is a LITERAL path; only READ verbs in another project's checkout (`ls-remote` is a read). A tag regex is `datasec` anywhere. A time inside a note body is "just before this line" or copied from the artefact's own stamp (`note_entry.sh` warns; dated references to yesterday's rulings trip the advisory harmlessly). An Agent-tool drafter/builder dies with the seat: commission it to write its files EARLY. `send_brief.sh` refuses a KS id in the QUEUE section without a provenance line. `board_count.sh linear` with a `labels:{name:{eq:…}}` filter returns 0 for EVERY label (proposal = 31 real) — a dead filter shape, never a count; enumerate client-side and state the frame.

### OWED (mine, none blocking)
1. **Re-card with defaults after the gate:** the four §5f runtime-evidence escalations KS-577 / KS-946 / KS-1172 / KS-1173 (told to Kam 14:0x as "re-carded after the gate") — read each ticket at source first; `decision_queue.sh list ruled` + `reference/` before adding (a prior-ruling refusal is a research prompt).
2. Dependabot: card `secuura-dependabot-triage` said close the 5; 10 open now — a board-seat item (the next Seat B brief's QUEUE), not Kam's.
3. Tooling: `board_count.sh linear` label-filter shape (dead; fix or document) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · `derive_candidates.py` drops HELD/REALLOCATED rows · `night_run.sh`: a LOAD refusal must not consume the queue line · `wake_watch` idle leg runs the detector itself (shared: claim; stop the watcher before editing; `--once`; re-arm) · a script that re-counts every integer in a drafted brief · KS-1201 (`run-shell-suites.sh` leaves 4 login_stub listeners per run — ticket candidate) · the drafter REPORT's KS-1133-A / KS-794 `corrupt patch` READY fences · doctor.sh item for the dashboard venv (msal/cryptography/requests) · EXPIRING-GRANTS-class rows for the Easy Auth secret (2027-03-21) and seat certs (2027-09-21) · the builders' non-secret `/tmp` files — quarantine, never delete.
4. NAS sync: tomorrow's check — `scheduler/state/nas_sync_last_wednesday.txt` (`retry: A → B`, B ≤3; rc 0) + the staleness table; whether the 09-19 run's 259 deletions fired the 50-alarm (UNREAD).

### ROUTE TO KAM (already sent 14:0x; do not drip — add only what is NEW)
0. The week instruction (asked; default stated). 1. ks1175 card. 2. ks721 card. 3. The two readings. Carried, NOT re-sent: platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies (untracked); seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY (product fix, ticket candidate).
