---
date: 2026-09-16
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 07:25 by the 07:00 seat at its 50% checkpoint (statusline 52%). Previous copy beside this file: .pre-0725-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words (all receipted): TODAY 06:39 "thanks for fixing it. I am glad you are onto it. please keep going through the day with the local agent" · 07:01 THREE CARDS RULED BY TAP (below) · 09-15 18:19 NEVER IDLE — "extend the checker… action all backlog and to do from easy to hard. you act as a gate keeper" · 16:36 q4 ONLY, held diffs only, QA Sunday night + merge all at once (expires end of Sunday 09-20) · 19:44 KS-1172 deferred to Sunday, Stuart told on the ticket · 18:23 he leaves MONDAY NIGHT 09-21 — the unattended loop must be BUILT and PILOTED by Monday morning. Speak in the FIRST person on the panel.** A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.

## 🔴 STATE at 07:25 (the 07:00 seat's 50% checkpoint) — read this first
- **Floor:** `%0` Wednesday · `%29` monitor ONLY. Usage gate CLOSED (7d 99%, renews Sat ~11:xx AEST): no Claude seat, gate or drafter; Ornith (q4) is the only worker. Origin contains HEAD at every push this seat. Kam is AWAKE (07:01 taps); every line of his receipted within the minute.
- **KAM'S 07:01 RULINGS (reconciled `--apply`, all three cards RULED; one marked delivered):** (1) `secuura-ks953-shared-pins-anchor-by-marker` → **a** (anchor the three shared-pin sites by a stable marker + occurrence index; the cell drops the count-arrives-with-the-site promise) — **NOT YET BRIEFED, not delivered**: a test-side change in `packages/shared`'s ks781 body-parser-order test (the KS-1126 shape) — read the test at the tip first; a `test_file=` modify-in-place brief. (2) `secuura-ks1102-public-status-what-may-show` → **b** (strip url/port/version/env/expectedVersions/troubleshooting from `GET /system/status`, `/api/system/status`, `/api/system/health/dashboard` but KEEP `dependencies[].{name,type,required,status}`; full detail behind admin auth) — **NOT YET BRIEFED, not delivered**: `routes/system-status.ts :396-480` (mounted index.ts :791/:798) — a product change with a route-level red; likely a Claude-seat item on Sunday unless it fits one function. (3) `secuura-ornith-decision-class-tickets-1121-629-975` → **a** — **KS-1121 HELD** (delivered mark names its READY); **KS-975 item 1 RUNNING** (test-only + tamper, see below); **KS-629 OWED**: remove `livenessVideo` from `services/kyc/src/index.ts:534` (one line) and `kyc.openapi.ts:195-200` (six lines) + its comment :183-185, then `docs/openapi/secuura-api.yaml` is GENERATED ("never edit this YAML" — the raising seat regenerates); no exported schema to test against (both schemas are module-private consts) — brief as a split (A index.ts / B openapi.ts) with text-pin cells, or leave for a Claude seat; state which.
- **RUNNING at the handover (07:23): KS-975 item 1 on q4** (`night/log/manual_2026-09-16_0723_q4_975_vitest.out`; TEST-ONLY MODE with a `## Tamper` on `rateLimitScope.ts:118`; brief `night/briefs/KS-975.md`; queue line `product=… ref=ks952-rate-limit-scope.test.ts line=118`). **Its verdict is the successor's first read** (`runs/2026-09-16_ks975-*/checker.out`; the new test file read whole; under the tamper 2 red / at the tip 4 green) → READY bundle 47 or fix-where-it-lives. KS-975 item 2 (`explicitScope` treats JSON `null` as ABSENT — :86 in `claim` vs :232 the second line) is a SEPARATE product task: one guard line in `explicitScope` (:226-236) + a cell `explicitScope({ tenantId: null }, caller)` → null (red at the tip: falls through to `principalScope(caller)`).
- **THIS SEAT (07:00 → 07:2x): KS-1047, KS-1093 (P0) and KS-1121 HELD** (bundles 44–46; **READY 73 files = 71 distinct pins across 49 ticket ids** — counted from the filenames' ticket/pin tokens; KS-1171-8j and KS-1120-F2 carry a q4 AND a q8 copy — count pins, never files). Every product line byte-for-byte on the held pins; KS-1093's `after.sh` `cmp`-identical to Wednesday's hand fix; KS-1121's `+` side the brief's block. **The raising seat's brief is STAGED (not sent): `2_Project_Files/fleet/briefs_staged/secuura_raise_ornith_ready_diffs.md` — bundles 1–43 in it; 44–46 (and 47 if KS-975 holds) must be appended;** re-derive the ⟲ facts at send time.
- **HARNESS THIS SEAT (red-proofed on REAL artefacts before install; backups `.pre-0916-*`; IMPROVEMENTS rows 07:14 ×3):** `bash_patch/checker.sh` **B3c** — the model's INSERT-AFTER dialect REPLACES its anchor line (stable, 3/3 on KS-1093); a `(correct) … stays` site appearing as a `-` line is RESTORED as context (`section_1.diff.pre-b3c` beside it, `--recount` on apply) and named as an accommodation; unrepairable → FAIL by name. Arms `local-model/tests/b3c_stays_removed_arms.sh` 4/4 (the real r1 → REMOVED; KS-1047/KS-1127 → nothing; the OLD checker as the negative). Fired in the path on r2, repaired on r3. **The vitest tier has NO B3c twin** — KS-1121's rewrite happened to keep its anchors; if a vitest run deletes a stays-line, that is the next mechanism (the code_patch checker's A3d/a3c_plus.py is where it goes).
- **BRIEF RULES learned this seat:** (a) nothing a cell READS may live in prose — every declaration is the FIRST line of the fenced block (KS-1093 r1 `RES: unbound variable`); (b) a text cell's grep pattern ends at ONE unambiguous character, never a quote+space pair the model can transpose (KS-1093 r2 `slot}" ` → `slot} "`); (c) THREE separate edits in one TS file drift (KS-1121 r1: a deletion landed on the wrong lines each sample; the `if (result…)` line exists twice) — write ONE replacement hunk over the whole function with the `+` block given verbatim (KS-1121 r2: right first sample); (d) a `try { … } finally { … }` at the END of a replacement loses its closing brace (KS-1121 r2 first sample) — RETRY-ONCE fixed it, but prefer flat cells; (e) a comment line inside a backslash-continued bash list breaks the list — put it above the list; (f) `RateLimitPrincipal` fields are `unknown` — no casts needed in cells.
- **NEXT BRIEFS, in order (Kam's 07:01 rulings first, then the T2b bash tier):** KS-975 item 2 (above) → KS-953 (ruled a; read `packages/shared`'s ks781 test at the tip) → KS-629 (split or Claude — state which) → KS-1102 (ruled b — read `routes/system-status.ts :396-480` whole; if the strip is one function + one route test, brief it; else Sunday) → then the bash tier from `night/candidates.md` (14 rows, 06:5x): KS-998 (pre-push formatting gate fails OPEN on missing deps), KS-1011 (start-secuura.sh stack marker "unknown"), KS-1081 (bootstrap-env.sh template drift), KS-1148, KS-1031, KS-1033, KS-1162; KS-813 / KS-1163 are BIGGER (200+ line scripts — read whole, fresh window). Set aside with reasons (in `derive_candidates.py` SET_ASIDE — do not re-propose): KS-1088, KS-1135, KS-1034, KS-808, KS-897/906, KS-1063. Brief shape that held: `night/briefs/KS-<n>.md` per KS-1047 / KS-1093 (bash) or KS-1121 (vitest one-hunk) / KS-975 (test-only + tamper); pre-measure on a hand-fixed copy in the scratchpad (`scratchpad/ks1093/` is the template: reproduce the defect, fix by hand, run the golden suite from the brief's own block at tip and fixed, restore the clone with `cmp`); launch through a lock-gated script (`scratchpad/launch_975.sh` shape); READ the verdict from `checker.out` + the applied artefacts.
- **For Kam's read (no clock):** KS-1172/1173 activation waits for Sunday (his 19:44); the KS-953 / KS-1102 rulings are now in hand (briefs owed); `iogpu.wired_limit_mb` persistence; docker daemon DOWN on the Studio (doctor ⚠ every boot); node 24.7.0 < engines 24.11.0.
- **Rotation:** band 80–90 at a safe boundary, Ornith running through it. Successor's first reads: this block → `night/done.md` tail → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check` → the rotate log's last line (was the predecessor's rotation real?). **Rotating seat: `nohup … --self &`, `sleep 8`, `tail -1 fleet/cockpit/logs/rotate_wednesday.log` — in ONE action; never end a turn on "launched".**

## ⚠ TRAPS
- **COMMIT THE TWO REGENERATED DIGESTS AT BOOT** (`0_Brain/learnings/_boot_digest*.md` — the launcher rewrites them): `panel_sync` SKIPS its rebase+push while any tracked file is dirty. Then `git -C /Volumes/DevMASTER/WEDNESDAY push origin main` yourself (LITERAL path — `git -C $W …` is REFUSED by the hook) and confirm `merge-base --is-ancestor HEAD origin/main`.
- **A launch while the previous runner is in its 60 s post-ticket SETTLE exits 0 on the LOCK and consumes nothing** — the lock check must GATE the launch (`kill -0 $P && exit 3`), never print-and-continue (the `scratchpad/launch_*.sh` shape does this). A queue line is MOVED to `done.md` when its run ends — a re-run needs a fresh queue line (the launch script re-appends when absent).
- **zsh: `$T:systemTest/...` is a BAD SUBSTITUTION** — write `"${T}:path"`. `for x in $LIST` / `kill $PIDS` do NOT word-split; **an rc read through a pipe is the LAST command's** (`> out; rc=$?`). **`sleep N; cmd` is BLOCKED in the tool — waiting is a background `until` loop on `done.md`'s last line** (this seat's shape: `until tail -1 done.md | grep -q '^KS-NNN '; do sleep 5; done` with `run_in_background`).
- **Write verbs on the SCRATCH CLONE run inside a SCRIPT FILE**; `git -C $SP checkout/apply` from the tool line is refused. **A heredoc whose CONTENT carries `cd` or `rm` is refused** — write briefs/arms through the Write tool. **`rm $VAR` is refused; a diff context line containing `rm \` inside a grep pattern is refused too** (this seat, once) — grep for another token.
- **`python3` read-then-write: `open(p,'w').write(open(p).read()…)` TRUNCATES before it reads** — read into a variable first. **NEVER edit `night/*.sh` or `tasks/*/checker.sh` while a runner is live**: write `<file>.new` and `mv` it over (this seat did so for B3c mid-run — the old inode kept running). `cd` at the head of a call is refused. macOS has no `setsid`/`timeout`; `cat -A` does not exist (`sed -n l`). The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. The chat-store hook refuses ad-hoc `chat_log.json` reads — `kam_msgs.sh` / `kam_rulings_today.sh`. `<<'EOF'` always; **any clock in a row/brief/panel line is `$(date +%H:%M)` substituted by the shell** (`@NOW@` + `sed`). Waiters on the runner poll the LOCK PID (`kill -0`), never `pgrep -f night_run`. `NIGHT_DONE=night/done.md` explicitly for split queues. Ornith: `done.md` rows are verdicts; a re-check runs from the run's `recheck/` dir against the ticket's clone (`checker.sh <input.json> <recheck/out.md> /private/tmp/claude-501/night/clone_ks<n>`); **read after.sh / the `+` side of the reanchored section before a READY — a PASS is a claim**; every FAIL gets an IMPROVEMENTS row (5 columns: Date | Symptom | Cause | Fix (where) | Proof) + a fix where it lives, same session. **`git apply --recount` on a WHOLE multi-file patch mis-parses — apply per section.** `note_entry.sh` takes `--stdin` (a quoted heredoc) or `--h3 --stdin`; the bare-argument form is refused.
