---
date: 2026-09-16
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 06:36 by the 06:00 morning seat at its 50% checkpoint; STATE + THIS SEAT + HARNESS lines refreshed in place at 06:52 at its rotation. Previous copy beside this file: .pre-0640-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words (all receipted; nothing new today — 0 panel lines by 06:3x): 09-15 18:19 NEVER IDLE — "extend the checker… action all backlog and to do from easy to hard. you act as a gate keeper" · 16:36 q4 ONLY, held diffs only, QA Sunday night + merge all at once (expires end of Sunday 09-20) · 19:44 KS-1172 deferred to Sunday, Stuart told on the ticket · 21:05 "Keep working with the local model, looks like promising progress especially when guided by you" · 18:23 he leaves MONDAY NIGHT 09-21 — the unattended loop must be BUILT and PILOTED by Monday morning. Speak in the FIRST person on the panel.** A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.

## 🔴 STATE at 06:36 (the 06:00 seat's 50% checkpoint) — read this first
- **Floor:** `%0` Wednesday · `%29` monitor ONLY (+ the scratch `rtest` tmux session, used by the rotation arms — harmless). Usage gate CLOSED (7d 98%, renews Sat ~11:xx AEST): no Claude seat, gate or drafter; Ornith (q4) is the only worker. Origin contains HEAD at every push this seat (commit the launcher-regenerated digests at boot, then push — see TRAPS). Kam's last line 09-15 21:05; the 06:45 `com.wednesday.ornith-receipt` job posts his morning line from the records (check it fired: `night/log/` + the panel).
- **RUNNING at the handover (06:55): KS-1047 (the pre-push :268 comment → a KS-1046 verdict pointer; one `-`/`+` line + a four-cell suite from the KS-972 template) on q4** (`night/log/manual_2026-09-16_06*_q4_1047_bash.out`; lock-gated launch via `scratchpad/launch_1047.sh`). **Its verdict is the successor's first read** — `checker.out` + the applied hook (`grep -n KS-691` on after.sh, :269 untouched) → READY bundle 44 or fix-where-it-lives. Then the FIRST ACT for the successor (Kam 06:39 "keep going through the day with the local agent"): brief from the NEW **T2b bash tier** in `night/candidates.md` (14 rows, derived 06:5x — `derive_candidates.py` now resolves `.sh` products): read at the tip in this order — **KS-1093 (P0, `scripts/check-stack-safety.sh` 6f false red once a real Playwright run exists — read first; if its fix is one site with a bash-provable red cell, brief it; else set aside with the reason)**, **KS-1047 (P3, `.githooks/pre-push:230` names legs (3,4,7) where the measured set differs — likely a one-line comment/message fix + a grep cell)**, KS-998 (pre-push formatting gate fails OPEN on missing deps), KS-1011 (start-secuura.sh stack marker "unknown"), KS-1081 (bootstrap-env.sh template drift), KS-1148, KS-1031, KS-1033, KS-1162; **KS-813 / KS-1163 are BIGGER** (a 200+ line script each — read whole before briefing, budget a fresh window). Brief shape that held four times today: `night/briefs/KS-<n>.md` per the KS-958 / KS-1089 / KS-1127 files (helpers by line range + "verbatim"; cells as ONE fenced block of literal calls; `+` lines = only lines absent at the tip; a CONTROL cell beside every red; no backslash-dollar; `<<< "$out"` not a pipe under pipefail), pre-measure on a hand-fixed copy in the scratchpad (`scratchpad/ks1089/premeasure.sh` is the template), `build_bash_input.sh … > out 2>&1; rc=$?`, launch through a lock-gated script (`scratchpad/launch_958.sh` shape), READ the verdict from `checker.out` + the applied artefacts. Set aside this seat with reasons (in `derive_candidates.py`'s SET_ASIDE — do not re-propose): KS-1088 (decision), KS-1135 (diagnosis-first), KS-1034, KS-808, KS-897/906, KS-1063.
- **THIS SEAT (06:00 → 07:0x): KS-958, KS-884, KS-1089 and KS-1127 HELD** (bundles 40–43; **READY 70 files = 68 distinct pins across 46 ticket ids (47 with KS-1173)** — counted from the filenames' ticket/pin tokens; two pins carry a q4 AND a q8 copy — count pins, never files). Every product line in both is the brief's byte-for-byte; both applied artefacts read (KS-958's guard `cmp`-identical to a sed golden; KS-884's indents 4/4/7/7/7/8/8/8/8 == the tip's). **The raising seat's brief is STAGED (not sent): `2_Project_Files/fleet/briefs_staged/secuura_raise_ornith_ready_diffs.md` — bundles 1–43 current; QUEUE says ITEMS 1–43;** re-derive the ⟲ facts at send time.
- **HARNESS THIS SEAT (every one red-proofed on REAL artefacts before install; backups `.pre-0916-*` beside each; IMPROVEMENTS rows 06:17 ×3, 06:26, 06:31):** (1) `reanchor.py` **`rebuild_from_minus`** — a replacement hunk whose `-` lines are byte-exact but whose LEADING context is a truncated tip line anchors on the `-` LINES (chained, unique, the file's context re-emitted); refuses inserts / 0× / non-unique by name; (2) the same function's **INDENT-SHIFT** — `-` lines matched with leading whitespace ignored at ONE constant delta, the shift applied to the `+` lines (the model's stable +4 on `.githooks/pre-push`); `tests/reanchor_minuschain_arms.sh` 7/7 (both real outputs + the OLD script as the control + refusals); (3) `build_doc_input.sh` gained **G6** (the docs tier had refused every build since origin moved at 00:2x — found by the doc arms failing at their BUILD step); (4) `bash_patch/checker.sh` **new-file header RECOUNT** — a `/dev/null` section's header count is always recounted from its `+` body and a wrong declared count named (`git apply` had applied 75 of 84 lines and dropped the exit tail silently → a test exiting 0 with four FAIL lines read as "not red"); (5) `bash_patch_arms.sh` ARM9's run selector pinned to the A run (`ls … | tail -1` had drifted); (6) the minuschain arms take the model's hunk from the IMMUTABLE `out.md` — the checker OVERWRITES `section_N.diff` with its reanchored result at every run (`.as-written` beside it): **never read a run's `section_N.diff` as the model's text after a re-check.** (7) SPLIT-GROUPS (old-side rebuild first when a hunk's -/+ are not one run) + bare-context restoration (`.pre-0916-splitgroups`) — a hunk with `+` lines inside an if/else was being collapsed onto the `-`; (8) the EOF clamp (`_n_file`, `.pre-0916-eofclamp`) on both older reanchor paths — a whole-tail rewrite carried a phantom blank past EOF; (9) A3d narrowed to tip lines the hunk does not ALSO remove (`a3c_plus.py.pre-0916-rewrite`) — a whole-block rewrite is not duplication; (10) `derive_candidates.py` T2b bash tier + 7 set-asides (`.pre-0916-bashtier`). Arms: `reanchor_minuschain_arms.sh` **11/11** (both real KS-958/884/1089/1127 outputs + the OLD scripts as controls), regression `reanchor_gap` ✓ `doc_d8d9` ✓ `a3d` 5/5 ✓ `a3c_testonly` ✓ `bash_patch_arms` 9/9.
- **ROTATION MECHANISM (the 05:32 owed item, BUILT):** `wednesday_rotate.sh --self` (`.pre-0916-refusetap`) taps THIS pane through `cockpit.sh say` on every refusal and pushes the seat's OWN repo once before refusing on containment; `fleet/tests/rotate_refuse_arms.sh` 4/4 (scratch bare origins + the `rtest` session); the launcher's rotation line now says READ the rotate log's last line in the same action ('respawned OK' vs 'REFUSED — this seat is still here'). **Rule for the rotating seat: `nohup … --self &`, `sleep 8`, `tail -1 fleet/cockpit/logs/rotate_wednesday.log` — in ONE action; never end a turn on "launched".**
- **BRIEF RULES learned this seat (bash tier):** every CELL is written as the LITERAL call in one fenced block (the model pasted six prose cell descriptions into KS-958's test verbatim); a git shim in a test is a single-quoted `printf`, never a heredoc with `\$` (the model doubles the backslash); the reference's helpers by LINE RANGE + "verbatim" copy cleanly (84 lines on KS-958, first sample); cells that grep the runner's OUTPUT for a phrase carry a CONTROL cell for the phrase that must survive.
- **For Kam's read (no clock):** KS-1172/1173 activation waits for Sunday (his 19:44); the KS-953 and KS-1102 cards; `iogpu.wired_limit_mb` persistence; docker daemon DOWN on the Studio (doctor ⚠ every boot); node 24.7.0 < engines 24.11.0.
- **Rotation:** band 80–90 at a safe boundary, Ornith running through it. Successor's first reads: this block → `night/done.md` tail → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check` → the rotate log's last line (was the predecessor's rotation real?).

## ⚠ TRAPS
- **COMMIT THE TWO REGENERATED DIGESTS AT BOOT** (`0_Brain/learnings/_boot_digest*.md` — the launcher rewrites them): `panel_sync` SKIPS its rebase+push while any tracked file is dirty. Then `git -C /Volumes/DevMASTER/WEDNESDAY push origin main` yourself (LITERAL path — `git -C $W commit` is REFUSED by the hook, twice this seat) and confirm `merge-base --is-ancestor HEAD origin/main`.
- **A launch while the previous runner is in its 60 s post-ticket SETTLE exits 0 on the LOCK and consumes nothing** — the lock check must GATE the launch (`P=$(cat night/log/.night_run.lock/pid); kill -0 $P && exit`), never print-and-continue. A queue line is MOVED to `done.md` when its run ends — a re-run needs a fresh queue line.
- **zsh: `$T:systemTest/...` is a BAD SUBSTITUTION** (a modifier) — write `"${T}:path"`. `for x in $LIST` / `kill $PIDS` do NOT word-split; **an rc read through a pipe is the LAST command's** (`bash arms.sh | tail; echo $?` printed 0 over a failed arm this seat — `> out; rc=$?`).
- **Write verbs on the SCRATCH CLONE run inside a SCRIPT FILE** (`mk_clone.sh`, a `cg.sh` wrapper) — `git -C $SP checkout/apply` from the tool line is refused by the hook (twice this seat). **A heredoc whose CONTENT carries `cd` (a diff context line) is refused too** — write such files through the Write tool.
- **`python3` read-then-write: `open(p,'w').write(open(p).read()…)` TRUNCATES before it reads** — read into a variable first. **NEVER edit `night/*.sh` or `tasks/*/checker.sh` while a runner is live**: write `<file>.new` and `mv` it over. `cd` at the head of a call is refused. `rm $VAR` refused — `mv` to the scratchpad. macOS has no `setsid` and no `timeout`; `cat -A` does not exist (`sed -n l`). The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. The chat-store hook refuses ad-hoc `chat_log.json` reads — `kam_msgs.sh` / `kam_rulings_today.sh`. `<<'EOF'` always; **any clock in a row/brief/panel line is `$(date +%H:%M)` substituted by the shell**. Waiters on the runner poll the LOCK PID (`kill -0`), never `pgrep -f night_run`. Split briefs share a ticket id → separate `briefs/split_<id><X>/` dirs + `NIGHT_BRIEFS_DIR=` + an OWN `NIGHT_QUEUE=` file (bash_patch takes `input=` + `task=` pins instead); `NIGHT_DONE=night/done.md` explicitly. Ornith: `done.md` rows are verdicts; a re-check runs from a scratch copy (a bash re-check uses the checker's own quarantine/reset on the clone); **read after.md / after.sh / the product hunk before a READY — a PASS is a claim (three false greens this week were found only by reading)**; every FAIL gets an IMPROVEMENTS row + a fix where it lives, same session. **`git apply --recount` on a WHOLE multi-file patch mis-parses when a later new-file hunk's count is wrong and blames the previous file — apply per section.**
