---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 16:43 by the 13:5x Monday seat at its ROTATION HANDOVER (ctx 79, band 80-90; previous copies NEXT-PICKUP.md.pre-0921-*; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 13:5x Monday seat, rotation handover) — replace it, never append

**Kam:** back today, LEAVES TONIGHT (a longer absence; return day ASKED 14:0x, unanswered — `WEEK-INSTRUCTION.md` is LIVE with `valid_until 2026-09-27` as Wednesday's reading; his answer moves it). His week instruction (14:05:04, verbatim in the file): the week = Secuura tickets by Claude seats + Ornith; TODAY = the live board fully functioning + tested — DONE on the mechanism (Phase 3 verified + delivered 14:4x; root fixes 15:0x/15:0x/e8ae8258b; Tuesday confirmed on the mini; **both seats' live pollers ARMED** — mine pid 14963 since 15:42, hers since 15:04; his laptop test 15:37 reached me, his 15:43 pair came by the poller's own taps). **His device-key imports (laptop + iPad; paths + one step each told 14:4x) and his first real reply on Tuesday's tab are the two remaining end-to-end proofs** — not yet confirmed by him. He types on the LIVE board now (view tags matter; `kam_msgs.sh` defaults `--source live`; on a poller wake read `kam_msgs.sh N` with N = the tapped-rows count in `fleet/cockpit/logs/live_chat_poll.log`, never 1). Usage 7d 31%, gate open. Quiet hours 23:00–06:00 (no voice). Ledger 3c: 09-18 rows pass the 3-day line on 09-22 (run the archive move at the next checkpoint: rows(ledger)+rows(archive) conserved).

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at the handover: `%0` this seat · `%9` fleet-monitor — NO agent live)
1. **PORTABLE DRIVE — Kam's 14:49 instruction, his 16:2x "copy everything blindly":** a plain ADDITIVE `rsync -a` DevMASTER → `/Volumes/KK_DEV_Local` runs in tmux session **`sync:0`** (NOT fleet:0 — the Ornith G2 census must not see it) from `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (started 16:30:35; log beside it; excludes node_modules (his 15:48 word), the two `local-model/models` dirs (his profile; he was told — one word adds them), macOS volume junk; NO --delete; `.git` + worktrees INCLUDED). At 16:36: 2.9 GiB on the drive, ~4 MB/s on small files (1.2 TiB source — it will run for HOURS; large files go faster). **SUCCESSOR: arm a waiter FROM A SCRIPT FILE on the log's `=== blind copy done … rc=` line (this seat's background waiter dies with it), then tell Kam on the panel the size that went across (`Total transferred file size` in the log's stats2) and the rc; if rc ≠ 0, read the log's last errors — an rsync partial is resumable by re-running the same script (additive).** His engine's unison runs (two) were stopped; their logs `2026-09-21_portable_sync_KK_DEV_Local*.log` are the record; his `devnas.prf` untouched; the engine's first-sync screen prints `$NAS_MOUNT` as the destination (a display slip in HIS file — told to him, not edited).
2. **Ornith:** pool DRY by measurement; 19 READYs BANKED under `night/` (16 from the #1106–#1118 waves + KS-1236/KS-1006 pair + today's three gate rows KS-880-OTHERMAPPERDEFAULT-1 / KS-1273-TRIVYYAMLEXITCODE-1 / KS-1135-MANIFESTQUARANTINESTDERR-1 (its patch needs `--recount`: a miscounted hunk header, every line byte-exact — stated in its READY, corrected by hand from checker.out)). `PAUSE_QUEUE` to 18:14 with the reason. **The Claude-side next act = a Seat B 14th raise brief** (the 13th's brief `fleet/briefs_staged/2026-09-21_raise_seatB_successor13.md` + its DRAFTER_REPORT are the exemplar; a drafter writes it, Wednesday re-derives EVERY count): the KS-1236/KS-1006 pair (one PR, tier 1) + the three gate rows (KS-880 tier 1 — its file also carries HELD KS-887, both orders one sha, re-anchor if 887 lands first; KS-1273 tier 2; KS-1135 tier 2 — no ticket names the row; briefed under KS-1135 as the nearest live; a ticket candidate is Wednesday's) + whichever of the older 14 banked are not yet raised (KS-887/KS-958 ruled OUT on Q6 — separate later PRs; KS-794/KS-1133-A fences `corrupt patch`). Tip at handover: develop `9f0265eb06ecf24d4de18149ce862ad2330a61ee` tree `23d60cace7c37bc329ccc425e58659e950089a4d` (ls-remote 15:1x; re-read before any brief). Under Kam's usage-gate rule (31% now) and his 09-13 standing rule; a batch gate after the raise; merges on Wednesday's signed GO (TESTED grant, open-ended); kintsugi waits on his card.
3. **Live-board poller (this seat):** `fleet/cockpit/live_chat_poll.sh --seat wednesday` pid 14963 (nohup; health `fleet/cockpit/state/live_chat_poll.health`; watermark `state/live_chat_polled_through`). **It survives this seat's rotation (detached), but the SUCCESSOR verifies `pgrep -f cockpit/live_chat_poll.sh` + a fresh `OK` health line at boot** — an unarmed poller and an armed quiet one look identical (ledger row today). OWED: doctor.sh reads the health file (warn on FAILING / stale); wire the poller into `arm_wake_watch.sh` (shared; claim first; the one-liner is in `dashboard-cloud/REPORT_2026-09-21_phase3.md` piece (c)).
4. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c: nothing deploys/anchors) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). Told 14:0x. `reconcile_rulings.py` (default source both) at every checkpoint.

### DONE THIS SEAT (verified at source)
Boot ctx 32 (brain whole) · #1119–#1128 batch gate launched (prompt read whole, --check by own hand) → GO WITH FINDINGS ×10 → signed GO → ALL TEN MERGED (develop 9f0265eb0, tree = the gate's; ls-remote + rev-parse + rev-list 10) → rule 7 posted (KS-485 48c371bf, KS-772 e136b05a) → seat + gate scored 1.00, panes closed (29 merged on Wednesday's GOs since Kam's 09-20 15:25 word: #1100–#1128) · Kam's week instruction receipted + `WEEK-INSTRUCTION.md` live · Phase 3 dashboard: briefed, built (one builder), VERIFIED by own hand (probes 70/0, scan CLEAN, migration 0 left, five-key decrypt), committed 455519fa0 + fixes b7c9abb1e / e8ae8258b (two builder defects found by reading the diff; two more found by Tuesday's second-machine run; all fixed) → Kam told action-first; Tuesday confirmed on the mini · both live pollers armed · NAS template root fix (WED_AGENT per seat, e867ecdac) · Ornith: 3 gate rows briefed (drafter) → verified → queued → PASS 8/8 ×3 → HELD (19 banked) · Kam's Monday list sent as one message · 5 ledger rows (poller unarmed — Kam-caught; the constant-not-the-caller check — Tuesday-caught; the fired-tap misread; hold_ready's templated T3; + 1 praise row) · ~14 pushes, HEAD == origin each.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: `set -- $var` does not word-split; a refusable tool's rc on its own line, never through `| tail`; no `sleep` chains — a wait is `run_in_background` with an `until` loop or a Monitor (≤30 min, re-arm); never `echo =====X`; `!SYNC` in double quotes is history expansion — single-quote that path. Heredocs `<<'EOF'`; stamps by sed after. Every `git -C` is a LITERAL path (a `$VAR` is refused by the hook); only READ verbs in another project's checkout (`fetch --dry-run` is a write). A scratch clone for write verbs goes in the scratchpad from a SCRIPT FILE with literal paths. Every COUNT in a drafted brief re-derived or marked "drafter's count". Rung 10 after any READY/HOLD: detector first; `pane_close.sh` closes a ghost-bearing pane, never clears it. A `done.md` waiter keys on the INPUT PATH + date. `hold_ready.py` takes ROWID WITHOUT the key and a title WITHOUT `TESTONLY-` (it prefixes both) and TEMPLATES its T3 sentence — read checker.out's `PASS T3 …` line and correct the READY when `--recount` was the accommodation (tool fix OWED). A "root fix" is complete over the CALLERS of the constant — enumerate them (`grep -n DevMASTER seat/*.py`) and arm the caller that failed, never the constant. A mechanism that watches Kam's channel is ARMED on THIS seat in the same action its arms pass. A `send_brief` body may not carry a literal `@SEAT@`-style placeholder token. Tuesday-tab rows about MY work: answer on my tab, name the tab. Agent-tool drafters/builders die with the seat: files EARLY.

### OWED (mine, none blocking)
1. `hold_ready.py`: copy checker.out's T3 line verbatim; refuse 'strict' when `apply_recount.out` exists · doctor.sh: live-poll health + the dashboard venv item · wire the poller into `arm_wake_watch.sh` (shared, claim) · `nas_sync.sh` refuses an unset WED_AGENT (a guessed seat) · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS (told to Kam 14:0x) · dependabot 10 open (a board-seat QUEUE item) · `board_count.sh linear` label-filter shape (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · MANIFESTQUARANTINESTDERR ticket candidate (Polish; Wednesday's to file or not) · the 4 §5f + NAS tomorrow-check (`scheduler/state/nas_sync_last_wednesday.txt`: `retry: A → B`, B ≤3; and whether the 09-19 259-deletion alarm fired) · Tuesday's line for Kam: the shared vault daily note was overwritten from a stale copy by a NexusAI session today and restored additively — rule candidate "pull before every vault commit on every machine" (routed, not mine to fix).
2. Ledger 3c on 09-22: move the 09-18 rows to `_ledger_archive.md` (conservation asserted).

### ROUTE TO KAM (already sent 14:0x; add only what is NEW — one message when he engages)
NEW since: the copy's finish + size (item 1) · Tuesday's vault-note line (above) · nothing else. Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY.
