---
date: 2026-09-16
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's — but Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"), and on 2026-09-16 14:00 he commissioned Wednesday to ANALYSE Tuesday's structure and fix it. He added 14:02: "Feel free to read the Datasec content. There is no secrets from you." So Datasec content is readable for THAT task; Datasec client WORK is still not Wednesday's to do.
source: replaced WHOLESALE at 14:10 by the 13:2x seat at its 50% checkpoint. Previous copy beside this file: .pre-1410-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words today, all receipted:** 06:39 "keep going through the day with the local agent" · 09:53 "If something's blocking, move on to the next. This is especially important for next week" · **13:32 THE ALLOWANCE RAN OUT ~12:00 — he signed in on a DATASEC account; "minimal or limited Secuura work on this account… until Sunday when we'll switch over to my account and we can do more robust action"** · 13:35 "analyzing what's working properly and address anything and fix anything before we go on… continue working with the local LLM on backlog and to-do tickets" · 13:40 storage onto DevMASTER · 14:00 the Tuesday commission (below) · 18:23 (09-15) **he leaves MONDAY NIGHT 2026-09-21** — the unattended loop must be BUILT and PILOTED by Monday morning. Speak in the FIRST person on the panel. A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.

## 🔴 REFRESHED at 14:55 — read this first
- **KAM (14:50): "you said that twice in 2 minutes.  can this be fixed?"** — Wednesday was tailing every panel message with a STANDING STATUS line, so an unchanged fact arrived twice in two minutes. Same shape as his 2026-08-27 correction → **w=2**. ✅ **Fixed in the path:** `chat_reply.sh` REFUSES (rc 3) a message repeating a ≥8-word sentence from this seat's last four; `CHAT_ALLOW_REPEAT=1` overrides. **Honest limit: verbatim only, not paraphrase.** ⚠ **Arming it sent THREE test messages to his live panel** — the exact noise he had just asked me to stop. `CHAT_DRY=1` now runs every check and writes nothing; **use it for every future arm.** 4 arms through the dry seam. **RULE FROM HERE: report a status only when it CHANGES, never as a sign-off.**
- **KS-1031 HELD 7/7** (r2). 🔴 **NEW MODEL DIALECT, and it is the important one: there is a TRANSCRIPTION CEILING.** r1's whole test section was ONE placeholder comment ("due to length constraints, only the first line is shown here") — 179-line body refused; KS-1081's ~90-line body passed first time. **Keep test bodies under ~110 lines AND carry the completeness arm** (a final cell asserting cells-run == `EXPECTED_CELLS`, proven to fire). Both are now in BRIEF RULES below and in every commissioning prompt.
- **KS-953 REFUSED by its agent, correctly** — no single product file (option (a) as ruled touches `index.ts` not at all), a 5,406-line test file, and the three pinned sites need TWO marker grammars because `:892` is a `mockBodyParser` property inside `createVerificationRoutes({…})`, not a route. **Carded** `secuura-ks953-anchor-grammar-for-the-non-route-site` (rec a: uniform `callee#n`; default = the Sunday seat takes (a) and says so). The gate refused it first on his 07:01 ruling; the refusal was READ and its words are in the BLUF.
- **`autostart_on_brief.sh` gained `--tier bash|vitest`** — it hardcoded the bash builder and would have built a bash input for a TypeScript ticket. Caught by reading the tool before arming it. Input names now carry the tier (`code_683.json`). 3 arms.
- **IN FLIGHT:** the KS-683 brief agent (vitest tier), with the autostart armed on it — **that armed run is also the end-to-end unattended cycle the design says this script owes before Monday**; and the DevMASTER↔T9 sync, still scanning at 30+ min, **0 deletions**, instrument controlled (20,827 control hits).
- ctx 72% at 14:55. Band 80–90.

## 🔴 REFRESHED at 14:47 — read this first
- **R4 IS DONE AND BETTER THAN THE REPORT ASKED.** `install_scheduler.command` armed **3 of 9** jobs (not 8 of 9); six had NO plist on the drive and hardcoded `/Volumes/DevMASTER/WEDNESDAY`, so on Tuesday's machine launchd would load them and they would fail EX_CONFIG forever, silently. Now `scheduler/jobs/*.plist.template` (tracked, `@PROJECT_DIR@`/`@SEAT@`) + `scheduler/install_all_jobs.sh`; all nine render byte-identical to the live plists. **Kam's "30 min at the mini" is now one command run from her own tree.** doctor reports the count.
- ⚠ **THE ARM THAT FAILED, AND WHY THE FIX MATTERS:** the control tree did NOT refuse — `WED_AGENT` is exported into every shell, so an INHERITED value decided the seat and the script installed `com.wednesday.*` jobs pointing at a scratch dir, **overwriting the real ones**. Recovered in one command (it backs up before overwriting; templates are tracked). Seat resolution now takes the FOLDER NAME and **refuses on a disagreement** between tree and env. 4 arms, 2 controls.
- **A FOURTH CAUSE the report missed, and it would have undone every other fix:** the launcher's boot `git pull` runs only on a CLEAN tree, and a coordinator's tree is never clean (the dashboard writes every minute) — so it was structurally unreachable at every boot and said nothing. That is the real reason Tuesday was 382 behind. It now FETCHES and prints the behind-count loudly. 4 arms (an empty measurement must not read as up-to-date).
- **R9(e) IS ALREADY BUILT — do NOT rebuild it.** `night/daily_receipt.sh` already counts DISTINCT pins/tickets from filenames, skips DRY-RUN rows, names unresolved tickets and says whether the model runs. Dry-run 14:4x: *35 rounds, 13 passes, 2 unresolved (KS-1031 KS-1163), 19 new pins today, 77 pins / 53 tickets held, model idle, allowance 2%.* Residual: it does not name Kam-HELD cards and cannot tell idle-by-design from stalled. **Both corrections are appended to the report itself**, not left in chat.
- **Lesson filed + 3 ledger rows + BOTH digests regenerated** (`--check` clean, 172 files). New W lesson: `2026-09-16_what-keeps-a-seat-correct-is-not-all-in-git.md`.
- **IN FLIGHT:** the DevMASTER↔T9 sync (tmux `syncleg`, still SCANNING, **0 deletions**, control proves the instrument sees the file — read it with `tr '\r' '\n'` FIRST, it is 148 KB in six "lines"); and the KS-1031 agent rewriting its brief after the model's suite ran **zero cells** at the tip (rc=0, 0 pass, 0 fail — a check that cannot fail; B2/B3/B3b all passed, so the em-dash risk did not bite).
- ⚠ **`autostart_on_brief.sh` failed at its first real use** — `case` inside `$( )`, which `bash -n` PASSES. It built the input and died before queuing. Fixed and armed by RUNNING the line, not parsing it.
- ctx 66% at 14:47. Band 80–90.

## 🔴 REFRESHED at 14:32 — what changed since the 14:10 block below
- **Kam gave the GO on the Tuesday work** (14:23: *"Please go ahead and, if there's anything else that you can do to improve things for both yourself and Tuesday, do that too."*). **R1, R2, R3 and R5 are DONE and pushed** (`2d2f39082`): hooks + permissions now live in a TRACKED `.claude/settings.template.json` rendered by `tools/render_claude_settings.py` at every boot (6 arms, both controls); boot step 4 now READS the seat's own pickup + EXPIRING-GRANTS (no step named a pickup for either seat before — that is why an ongoing task died on her seat and survived on mine); `WEEK-INSTRUCTION-TUESDAY.md` created so a Secuura week cannot become her Datasec orders; doctor FAILS HARD on fewer than 6 hooks (proven rc 1 stripped / rc 0 restored).
- **STILL OWED for Monday:** R4 — arm the launchd set on the MINI (`WED_AGENT=tuesday`, and add `chatsync` to `install_scheduler.command`; it is the one job no installer arms). **Needs hands at that machine — Kam's, or a session there.** R6 — pull Tuesday's tree forward 382 commits AFTER R1–R3/R5 reach it. R9 — the unattended-week pieces (b) and (e). Full report: `1_Project_Definition/Architecture/2026-09-16_tuesday-vs-wednesday-structure.md`.
- **Kam asked (14:24) whether Tuesday needs a git repo — answer: NO.** She has one, same remote, a clean ancestor 382 commits behind. The repo was never the problem; the gitignored settings file was.
- **KS-1081 PASS 7/7 on its FIRST sample; READY written** (79 READY files). ⚠ Its READY carries THREE ticket errors found at the tip, one material: the ticket's two variable lists are INVERTED, so Kam's ruling drops ~30 vars a fresh clone used to get. **His ruling stands; the reconciliation is a separate ticket and must be filed before `.env.example` is deleted.**
- **A DevMASTER↔T9 sync is RUNNING** in tmux session `syncleg`, log `/private/tmp/sync_t9b.out` (Kam 14:19; ollama stores excluded per his 14:20). **First attempt failed instantly and did nothing** — `devnas-sync.sh` wraps unison in `script -q /dev/null` for a pty and dies with `tcgetattr/ioctl` when launched detached. **Run it from a tmux session, never `nohup`.** A background watcher greps it for `Deleting` and `conflict`; if it proposes deleting inside a working folder, STOP and show Kam the list.
- **A subagent is writing the KS-1031 brief** (`night/briefs/KS-1031.md`), told to STOP and say so rather than force a brief if the ticket needs a Kam decision. Ornith idle until it lands; `night/autostart_on_brief.sh` exists now and will build+queue+launch on a brief's appearance (its give-up path is armed).
- ctx 61% at 14:32. Band 80–90.

## 🔴 STATE at 14:10
- **Floor:** `%0` Wednesday only — the fleet session died with the allowance ~12:00 and was not rebuilt. Usage gate OPEN (7d **0%**, renews in ~1d 18h on this Datasec sign-in). Origin contains HEAD.
- **Two subagents live** (launched 14:0x, results not yet in): (1) the **Tuesday-vs-Wednesday structural comparison** → writes `1_Project_Definition/Architecture/2026-09-16_tuesday-vs-wednesday-structure.md`; (2) the **KS-1081 brief** → writes `2_Project_Files/local-model/night/briefs/KS-1081.md` (Kam ruled option a: env.example is canonical). Neither builds an input or queues anything — that is the seat's job.
- **ORNITH: idle with an empty queue at 14:10.** Server UP (drive-local, `start_ollama.sh`). The moment KS-1081's brief lands: `build_bash_input.sh` → queue line → `night_run.sh`.
- **A background hash check is still running** on the three largest ollama blobs (61 + 48 + 17 GB, both ends — ~252 GB of reads). Read `/private/tmp/claude-501/.../bmkbf51v2.output` or just re-run `move_ollama_store.sh --verify`. **Until it is clean, do NOT reclaim `~/.ollama`** — and reclaiming it needs Kam's word anyway.

## ✅ WHAT THIS SEAT DID (13:2x → 14:10)
- **Ornith was idle 09:58 → 13:32 and only half of that was the token cap.** The ollama server died before 12:24 (Kam 13:43: a system update — diagnosis closed) and G5 refused six cycles into a log nobody reads. Fixed in the path: `start_ollama.sh` (new) · **G5 self-heals** by calling it · **G8** escalates any gate refusing ≥30 min to Kam's panel, rate-limited, markers moved to `log/_quarantine_g8/`. Arms `tests/g5_selfheal_g8_alert_arms.sh` **6/6** including the control that the same condition refuses under `NIGHT_G5_SELFHEAL=0`.
- **KS-1011 PASS 7/7, held, READY written** (78 READY files now). Kam's option b.
- **Three harness defects fixed:** `build_bash_input.sh` `show(tf)` → `try_show()` (the NEW-test mode had become unreachable; proven by a discriminating PAIR); RETRY-ONCE gained `B3b`/`B3c` (the bash tier had NO retry) and its `&&/||` precedence was grouped so the disable flag disables; `OLLAMA_MODELS` PINNED in night_run.sh.
- **Storage** (see the daily note for the numbers): ollama's 141 GB moved + pointers set on all three surfaces; Docker's move lost his images and he ruled it an acceptable loss.

## 🎯 THE NEXT SEAT'S FIRST ACTS, in order
1. `kam_rulings_today.sh` — read EVERY line before any card or brief.
2. **Feed Ornith.** If `night/briefs/KS-1081.md` exists: build the input, queue it, launch. If not, the next candidates from `night/candidates.md` that are NOT under `systemTest/` — KS-1168 (Kam ruled a, EXACT-only search), KS-1031, KS-953, KS-692. **Do not brief a `systemTest/` ticket** (see BLOCKED).
3. **Read the Tuesday comparison** the moment it lands and take it to Kam with a recommendation, not a summary. This is the highest-value thing on the desk: it is the same problem as his unattended week, and he leaves Monday night.
4. Ask Kam for the one word on reclaiming `~/.ollama` once the hash check is clean.

## ⏳ BLOCKED — stated, not worked around
- **Every `systemTest/` ticket** (KS-998, KS-910, KS-1148, KS-1162 and most of Kam's 09:53 rulings): Peter's #997 merged 36 files, ALL under `systemTest/`, and `0b25f823f` is not in the local object store. `tip_override.txt` is verified only for `Blockchain/Dev`. Briefing one means briefing against a stale copy of exactly the files that moved. Fetching is a Secuura seat's job, and that spends the account Kam wants kept light.
- **KS-1163** needs ONE change across `Start_Up/start-secuura.sh` and TWO suites (`start_secuura_expected_services` + `start_secuura_slot_names`). `bash_patch` expresses product + ONE test file. Part A passes B2/B3/B3b/B4-red/B5-green and stops at B6 (the sibling goes 0→8); Part B's model hunk landed on the `prefix_of` definition at :45. The harness extension is Wednesday's and is NOT started.

## 📋 BRIEF RULES — every one of these cost a model round. Break them and you pay again.
- 🔴 **KEEP A TEST BODY UNDER ~110 LINES.** Above that the model does not transcribe it — it writes a PLACEHOLDER COMMENT saying the content is too long and emits a one-line file, which runs, asserts nothing and exits 0 (KS-1031 r1: a 179-line body; KS-1081, first-sample pass, was ~90). **And carry the arm that makes it detectable: a final cell asserting `PASS+FAIL == EXPECTED_CELLS`** — without it a suite that skipped everything reports success.
- **Nothing a cell READS lives in prose** — every declaration is the FIRST line of the fenced block.
- **NEVER show a CONTEXT line inside the `## The exact change` fence.** Name context lines in prose above it. Every line in the fence carries `+` or `-` and is a change. (KS-1011 r1.)
- **No backslash continuations in a `+` block** — the model drops them. One long line instead. (KS-1011 r2.)
- **Test cells are LITERAL SHELL, written out in full.** Describe them and the model invents a helper whose assertion is a mutation, and every cell reports FAIL while the product hunk is correct. (KS-1011 r3.)
- Every 🔴 cell fails at the tip BY ASSERTION, never by a throw or an unbound variable. Include one 🟢 CONTROL green at the tip AND after.
- A text pattern ends at ONE unambiguous character, never a quote+space pair. No `\$`/`\u` in a `+` line. One replacement hunk per function when a line repeats.
- Every `-` line must exist byte-for-byte at the tip — copy from `git show`, never retype.

## ⚠ TRAPS
- **`git -C $VAR <write verb>` is REFUSED by the hook** — write the LITERAL path. This has now failed at six consecutive seats; only the hook has ever held.
- **`rm` outside the session scratchpad is REFUSED**, including through a variable. Quarantine by `mv` — and that applies to code you WRITE too: G7 moves its markers, so G8 does as well.
- **NEVER edit `night/*.sh` or a `tasks/*/checker.sh` while a runner is live.** Check the lock (`night/log/.night_run.lock/pid`, `kill -0`), and if live write `<file>.new` and `mv` it over — bash reads a script incrementally and the old inode keeps running. The Edit tool rewrites in place, so it is the WRONG tool for a live script.
- **`sleep N; cmd` is blocked in the tool.** Wait with a background `until` loop (`run_in_background: true`).
- An rc read through a pipe is the LAST command's (`> out; rc=$?`). zsh: `for x in $LIST` and `kill $PIDS` do not word-split.
- **`pgrep -fl` on a `bash -c` body prints the WHOLE script** — thousands of lines into your context. Use `pgrep -f <pat> | while read p; do ps -o pid,ppid,lstart -p $p; done`.
- **`ls -1` does not show dotfiles.** A quarantine dir of `.marker.<ts>` files reads as empty — that is a false absence from your own instrument.
- The statusline was readable at boot (ctx:33% at 13:31) and `tmux capture-pane` has not found it since. If you cannot read it, say "unread", never guess a number.
- `note_entry.sh --stdin` with a quoted heredoc; any clock in a row, brief or panel line is `$(date +%H:%M)` substituted by the shell, never typed.

## 🔭 THE BIG ONE — Kam's 14:00 commission, verbatim in the daily note
Tuesday works poorly (not responding, not following instructions, not coordinating agents) and Kam wants her brought up to "almost like you", autonomously if that is what it takes — plus whatever else is needed so that **an ongoing task given once LIVES ON and is performed properly** while he is away. The comparison agent's report is the input; the deliverable is a recommendation split into INSTRUCTION / SKILL / CODE with what must land before **Monday 2026-09-21**.
