---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 01:59 2026-09-21 by the 01:3x seat at its 50% checkpoint (previous copy NEXT-PICKUP.md.pre-0921-0200; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 01:3x Monday seat, written at ctx 50% — a checkpoint, not a rotation) — replace it, never append

**Kam:** 0 panel lines on 2026-09-21 as of 01:59 (his last words 2026-09-20 21:5x: new account, "keep going with secuura tickets using both claude and local agents", then "see you soon"). He is expected back today and LEAVES MONDAY NIGHT — expect a new week-instruction (`WEEK-INSTRUCTION.md` is `status: lapsed`; receipt it, write it verbatim, derive the weekday). Usage 7d 11%, gate open. Quiet hours until 06:00 (no voice). Ledger 3c: 09-17 done at 00:50; 09-18 rows pass the line on 09-22.

### 🔴 IN FLIGHT (floor from `tmux list-panes` at 01:59: `%0` this seat · `%9` fleet-monitor · `%11` Seat B 11th)
1. **Seat B 11th (`%11`, ctx ~62%) — raising SIX PRs on develop 778e6cfe2 in order; develop is `cbae988db` (#1105 on top; a measured non-event for its twelve paths).** READYs in: **1/6 #1106 KS-1232 `2abc82d1` · 2/6 #1107 KS-753 `7e7da2f8` · 3/6 #1108 KS-1234 `4904c081c` (TIER 1: the `/api/v1/` alias middleware-skip widening; index.ts 1/1 + a new test file) · 4/6 #1109 KS-1279 `f592268a` (bash pair).** Pending: 5/6 KS-880 (tier 1) and 6/6 KS-1223 (tier 1, LAST). Its idle-at-prompt wakes are rung-1 ghosts over a live push driver (`5_Project_History/2026-09-21_seatB-11th/raise/series.out` advancing) — detector first, ack, never tap. **Wake = READYs 5 and 6 → ONE batch gate** (file-disjoint, four lanes, tier-1 floor; draft via a gate drafter from the `2026-09-20_gate1102to1104` gateset shape; re-pin at launch; grade on the then-current develop; leads to carry: each push's pre-push preflight ran 12/15 legs with 3 SKIPPED — "skips are not a pass"; INT-1 the batch bash pass load-flake re-run clean 3×; LINT-1 one eslint warning in PR 3's test; the linear[bot] walks tickets Backlog→In Progress on PR open — ruled STAY Backlog, the GO names it) → completion check → signed GO (equality targets per FILE, comma-separated on the two-file lines — MG-2) → merges one at a time → score → `pane_close.sh %11` in the same action as its wrap. Brief: `fleet/briefs_staged/2026-09-21_raise_seatB_successor11.md`; its plan ANSWER `…_seatB11_answer_plan.md`; STATUS 15:28Z has the six commit SHAs + trees.
2. **Ornith — THREE #1105-gate NOT-PINNED rows RUNNING (queued 01:59, runner pid live): KS-1284 CHUNKED-DOCUMENTID-ROUNDTRIP-1 → KS-1175 EXPLORERBASE-PER-NETWORK-1 → KS-1175 IDENTITY-EMPTY-OBJECT-1** (tip cbae988db; briefs `night/briefs/KS-1284-CHUNKED-…-1.md`, `KS-1175-EXPLORERBASE-…-1.md`, `KS-1175-IDENTITY-EMPTY-OBJECT-1.md`; drafter precheck `runs/2026-09-21_ks1105rows-drafter-precheck/`, golden 8/8 each; the two on `ks1175-anchor-readback.test.ts` apply in both orders → sha 431b51cb). **Wake = a background waiter on `done.md` (all three input paths + today) → source-read each PASS → READY per the KS-1198 template → bank.** Row VIEW-NONSTRING-ARRAY is NOT a pin (the gate's cell is RED at the tip — a product change; `…/VIEW-NONSTRING-ARRAY/NOT_BRIEFABLE.txt`) — a code_patch candidate for a Claude seat, or a KS ticket. T11/T12/T13 need NEW files (fs-extraction guards; a CSL wallet for T13) — the next drafter wave after these three.
3. **BANKED for the NEXT raise seat (Seat B 12th, after the 11th wraps): FIVE — `READY_KS-1203-NESTEDTYPE-1_*` + `READY_KS-1203-WSTRIM-1_*` (same file, NESTEDTYPE first, one PR), `READY_KS-1283-PROVADMIN-1_*`, `READY_KS-1244-JOINEDKEY-1_*` + `READY_KS-1198-SKMETA-1_*` (same file `auth.test.ts`, one PR, KS-1244's hunk first; auth → tier 1, LAST).** Plus whatever the three anchoring runs bank.
Tip: develop `cbae988dbe90ebe556459ada2cb437eaf80e2402` tree `1f2bc512a` (#1105 on 778e6cfe2). `inbox_routing.conf` carries -B and QA/Secuura-1105.

### DONE THIS SEAT (verified at source)
KS-1198 SKMETA-1 PASS 8/8 held (patch byte-identical to its golden hunk) · `inbox_digest.sh` preview-leak fix (both seats' regexes; 48/48 withheld, 21 Secuura previews intact; ledger w=3 → enforced) · `reconcile_rulings.py` recognises `note:` rulings (flag loudly, never guess; arms 23/23; the 09-20 OWED closed) · INDEX refreshed · panel mirrored.

### STANDING RULES LEARNED (carry, do not re-learn)
A loop's exit condition is ONE `grep -q`, never a pipeline. A heredoc is `<<'EOF'`; stamps by sed after — and an EMBEDDED python heredoc in a bash script is unquoted: no backticks in its comments (executed twice this seat lineage). Every COUNT in a drafted brief is re-derived by Wednesday's own command or marked "drafter's count". Rung 10 (`[Wednesday tap] GO mailed …` ghost) after any READY/HOLD: detector first on every idle wake. A `done.md` waiter keys on the INPUT PATH + date. The checker's clone is DIRTY after a run — drafters use a fresh clone per measurement. Every `git -C` is a LITERAL path (the hook fails closed on variables) — write multi-step git checks as a script file with literal paths. A tag regex is `datasec` anywhere, never a path-shaped literal.

### OWED (mine, none blocking)
`cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · `note_entry.sh` typed-clock warn (and its `--h3` form refuses: "bare-argument form retired" — the heading path is broken, only `--stdin` works) · `derive_candidates.py` drops HELD/REALLOCATED rows · CHK-1 (correct the KS-1272 checker record) · `wake_watch` idle leg runs the detector itself · a script that re-counts every integer in a drafted brief · KS-1201 (`run-shell-suites.sh` leaves 4 login_stub listeners per run — a ticket candidate for a board seat) · doctor: warn on an expired `PAUSE_QUEUE` (the 09-20 guard-inside-the-guarded row) — check whether the 23:4x seat's "doctor now warns" line means it is BUILT (the pickup said so; verify with a clock-moved arm before trusting it).

### ROUTE TO KAM (Monday 21)
0. **Booleans on the Cardano record as STRINGS "true"/"false"** (Wednesday's shape ruling; ints 0/1 the alternative) — his to flip before any anchor. **The deploy + first anchor for KS-1175/#1105 is his step.**
1. Whether his 2026-09-14 07:22 suspension of Wednesday→Tuesday messaging still stands (Tuesday is live on the mini).
2. `Secuura/platform-s#877` unreadable — a permissions boundary, reported not worked around.
3. Four escalations on absent §5f runtime evidence: KS-577, KS-946, KS-1172, KS-1173.
4. `secuura-dependabot-triage` says "close the 5"; 10 open dependabot PRs now.
5. Carried: Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies (17 mechanism scripts); seat A's launcher F-02; O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; **O-1: `admin.ts` `requireAdmin` routes do no session check**; the KS-1283 coverage ticket (one cell now held); M-7 (anchoring.openapi.ts:253 restated regex — Polish, a ticket candidate); **VIEW-NONSTRING-ARRAY (anchorReadback.ts:46-48 passes a non-scalar through to S under a `type: string` field — a product fix, not a pin; ticket candidate)**.
6. Wednesday's reading to confirm: auth surfaces open to TEST-ONLY local-model work under "auth product EDITS stay out" (KS-1223, KS-880, KS-1283, KS-1244, KS-1198 all pinned on that reading).
