---
date: 2026-09-15
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 11:09 on 2026-09-15 by the seat booted 05:3x (rotating at ~75% with the floor clear). Previous copy beside this file: .pre-1110-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **FIRST JOB (Kam 11:06 + 11:07, verbatim: "test both on different tickets - 5 each" · "yes 10 tix in total"): TEN tickets in total — FIVE run on `ornith:35b` (Q4_K_M) and a DIFFERENT FIVE on `ornith:35b-q8_0` — each with a Wednesday-written brief, one model in memory at a time (Kam 10:53: "dont run them side by side"), the same checker; results per rung into the table in `2_Project_Files/local-model/IMPROVEMENTS.md`.** The usage cut is IN FORCE (gauge 91% at 11:0x; no Claude seat, gate or drafter until the renewal ~Sat morning) — the briefs are written by WEDNESDAY'S HAND from the ticket + the code at the tip (no drafter; a brief costs no allowance).

> Narrative: `0_Brain/daily/2026-09-15.md` (05:59 boot → the wrap). The Ornith record of the day: `2_Project_Files/local-model/IMPROVEMENTS.md` (24 rows + the q4/q8 table) — READ IT WHOLE before writing a brief.

## 🔴 STATE at 11:09 — read this first
- **Floor:** `%0` Wednesday · `%29` monitor ONLY. No agent live. Watcher runner patched (own-stuck-tap discriminator + tap read-back; idle-hash excludes the statusline). panel_sync live. Ollama live (`tools/ollama`, `OLLAMA_MODELS=local-model/models`; tags: `ornith:35b` 21 GB · `ornith:35b-q8_0` 37 GB · gpt-oss 20b/120b). Ornith loop job `com.wednesday.ornith-loop` (900 s) + the 23:30 job; a mkdir run lock; G1 clock informational; G2 pane census is the gate. `iogpu.wired_limit_mb` = 88064 (Kam ran it 10:52; NOT reboot-persistent — his choice owed: launchd job or sudoers line).
- **Product today:** #805 → **M55 `48e65c435`** (KS-726 Done + archived; KS-1171 filed). **Two Ornith patches PASS 7/7 and are HELD for a Secuura seat** (Wednesday read both at source; a seat is a launch → after the renewal, or on Kam's word for one short seat): `night/READY_KS-1072_ornith35b-q4_PASS-7of7_2026-09-15.diff.md` · `night/READY_KS-1087_ornith35b-q4_PASS-7of7_2026-09-15.diff.md`. #995 (KS-741) READY tier 1 @ `b8155636e` (gate HELD); #922 / #989 / #927 gates HELD. **Board 71 active** (Kam's line ≤ 60).
- **HOW TO WRITE A BRIEF (the rules learned today, each from a failure — the ledger has the case):** `night/briefs/<TICKET>.md`; sections: *What is wrong* (one paragraph) · *The exact change* — **every edit ≤ ~8 lines, anchored by line number + the line's text at the tip, several small edits never one rewrite** (KS-1087 failed 4× on a 30-line hunk and passed on three edits) · *What must NOT change* · *The test* (file path `<test_dir>/<name>.test.ts` repo-relative; the reference file to copy the mocking shape from; cells: 🔴, 🔴, CONTROL — name the exact assertions) · **`## Where`** with `* \`:NNN\` — **must change**: \`<line text>\`` bullets (parsed into A3b; the model must remove every one) · *Output* (one fenced diff, repo-relative paths, correct counts). Run with think=0 (`NIGHT_THINK` default) — think=1 + a brief over-thinks into the context wall. Queue lines: `KS-<n> ctx=49152` (+ `ref=` / `line=` pins as `build_input.sh` needs; a `ref=` when the reference test does not import the product file). Run: `NIGHT_MODEL=<tag> NIGHT_MIN_FREE_GB=45 NIGHT_MAX_TICKETS=5 nohup bash night/night_run.sh > night/log/manual_<stamp>.out 2>&1 &` then a background `until ! pgrep -f night/night_run.sh` wait (the runner has no wake of its own). Read `night/done.md` + each run's `checker.out` in ONE pass; a PASS → read the diff at source → hold it as `night/READY_<ticket>_…diff.md`; a FAIL → classify (model / harness / prompt) → fix where it lives → IMPROVEMENTS row (Kam's standing rule, lesson `2026-09-15_ornith-every-issue-gets-a-tooling-or-instruction-fix.md`).
- **PICKING THE TEN:** the 09-14 sweep in `night/queue.md`'s comment block lists the fits and every rejection with its reason — with a Wednesday brief, single-file tickets rejected as "decision" become feasible ONLY where the brief can state the decision from the ticket's own words (else it is Kam's); "coverage-only" tickets still cannot pass RED-FIRST; multi-file stays out. Re-read the board at source (Backlog/Todo, ours, no open PR, not in a live lane, vitest services only: api-gateway, anchoring — originate/governance are jest). Candidates to read first: KS-1050 (users.ts:933 0-row update — if the ticket's own text fixes the status, brief it), KS-954 (leading-`//` — reproduce in the brief's test), KS-1132 (getPlatformAdmin swallows infra failure), KS-864 (system-status literals — only if the values are in the ticket), KS-849 (kyc timer — option (a) only if the ticket says so). Five per quant, different tickets; q8 needs `NIGHT_MIN_FREE_GB=45`.
- **Kam's rulings today (all receipted; `kam_rulings_today.sh`):** 06:51 local model on the backlog, batch + one-pass check · 06:53 fix it through process or management · 09:28 **the standing improvement rule** · 09:30 **Wednesday writes the model's prompt from the ticket** · 09:32 "put this into effect and keep going" · 10:31 keep pushing, improve local performance · 10:46/10:47 pull `ornith:35b-q8_0` (DONE) · 10:51 the wired-limit sysctl (he ran it) · 10:53 never side by side · 10:54 same tooling and approach · 11:06/11:07 **ten tickets, five per quant**.
- **Owed / candidates:** the wired-limit persistence choice (Kam's); the no-rm hook is blind to `rm` inside a `{ … }` group after `||`; the idle-ack keyed on a transcript mtime (a pane hash drifts); `send_brief.sh` ADDENDUM blob-list refusal; the zsh-list ADVISORY hook; `panel_sync` scoreboard union-merge; WED-141; Dependabot close-and-rescope (board seat); Ornith open rows (task.md `-U1` context; the test-only emission class); the q8 re-test of KS-1087 on the split brief.
- **For Kam's read (no clock):** docker daemon DOWN on the Studio; node 24.7.0 < engines 24.11.0; Peter's #811 caution; #887 his; PS #759/#760 unmeasured; Peter merged #992–#994 + filed KS-1170.
- **Rotation:** band 80–90 at a safe boundary (agents live is fine). Successor's first reads: this block → `IMPROVEMENTS.md` whole → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check` → `night/done.md`.

## ⚠ TRAPS
- zsh: `for x in $LIST` / `set -- $VAR` / `kill $PIDS` / `git apply $OPTS` do NOT word-split — `while IFS= read -r`, literal args, or a script FILE under bash. The no-rm hook is LIVE (quarantine by `mv`) and blind inside brace groups. The no-cd hook refuses `git -C $VAR …` and any write verb (`checkout`, `apply`, `clean`) pointed outside WEDNESDAY even in the scratchpad — put the command in a script file and run it with bash, or use literal paths. The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. `cockpit.sh say` takes the pane NAME; `pane_close.sh` the `%id`. Unquoted heredocs blank backtick phrases — `<<'EOF'` always; a python f-string with `{ … }` in prose breaks — build blocks from a file. `panel_sync` SKIPs while untracked files sit in the tree; my `git push` is rejected while it is pushing — it rebases and pushes within a cycle; verify by `merge-base --is-ancestor HEAD origin/main`. A wrapped seat's pane is closed in the SAME action as its wrap is read. Never run `wed_claim.sh` while panel_sync is live. Ornith: `done.md` rows are verdicts, `SKIP_MEMORY` no longer is (it stays in the queue); the memory gate reads `memory_pressure`; a `done_reason: length` is the context wall, not a verdict; `IMPROVEMENTS.md` before any brief.
