---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 12:27 by the 11:0x Wednesday seat at its 50% CHECKPOINT (band 80-90; previous copy NEXT-PICKUP.md.pre-0922-1227 beside; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 11:0x seat, 50% checkpoint) — replace it, never append

**Kam:** AT HIS COMPUTER TODAY and reachable on the LIVE board (his 08:59: "if you need me, just let me know through the live page"); nothing pending for him; his 10:15 "thank you" closed the usage-chip exchange; NO board message sent this seat (nothing needed him). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27, Wednesday's reading; return day unanswered). `kam_msgs.sh` defaults `--source live`; poller pid 14963, usage publisher pid 9380 (`pgrep` at boot). Usage 7d 68% (12:2x), gate open. The 06:00 receipt for 09-23 is the successor's (arm a 05:58 wake from a script file at boot). Ledger 3c: the 09-20 rows pass the ~3-day line on 09-23.

### 🔴 IN FLIGHT (floor at the checkpoint: `%0` this seat · `%31` Seat B 18th HOLDING · `%32` Seat C 18th HOLDING · `%33` gate18C `QA/Secuura-batch1167` (launched 02:15:33Z) · `%34` gate18B `QA/Secuura-batch1170` (launched 02:23:27Z) · `%9` monitor; one subagent (FEED 11 drafter) in this seat, dies with it)
1. **TWO BATCH GATES RUNNING, both on develop `8c2f7b3fd4fde915b2a24542bc32259b24e092a0` (own `ls-remote` at each launch).** Wake = the verdict mails `[QA/Secuura-batch1167 -> Wednesday]` and `[QA/Secuura-batch1170 -> Wednesday]`. On each: completion check at source (report sha; NOT-TESTED first; the addendum lines through the SEAT'S own targets18.py on a scratch copy via `cat` per file; blobs at heads by own `ls-remote`/`cat-file`) → signed GO to that seat (subject EXACTLY as its HOLD names it; BASE_GO re-read in the send action; **the FIRST GO's merges MOVE develop for the second seat — say so in the second GO and let its merge18 re-predict; if the second gate's pin refuses (rc 10/18/19) that is a re-pin per its README §0, not a defect**) → merges → verify at source (`ls-remote`; `rev-parse ^{tree}`; `rev-list --count --first-parent`) → rule-7 drafts read whole → RULE → wrap → score + `pane_close.sh` in ONE action. **Seat C 18th** (%32, ctx 72): six up (#1167 #1168 #1169 #1171 #1173 #1175), GO subject `GO: merge #1167, #1168, #1169, #1171, #1173, #1175 batch`, all-6 tree over 8c2f7b3fd `52853c8bf6c4ff43585cdade61c637ff8cbaa5d0` (drafter = seat), `--pair-blob …health.ts=ae6017a84cf7…` on #1173 after #1171. **Seat B 18th** (%31, past its band at 80+): seven up (#1170 #1172 #1174 #1176 #1177 #1178 #1179) on parent `3916eacd1`, GO subject `GO: merge #1170, #1172, #1174, #1176, #1177, #1178, #1179 batch`, all-7 over the parent `a36532029483…`, **END_TREE over develop `76a88d9ddfa4f50098aa639a1056c5c9387aeb18`** (gate18B README §0) — the GO carries BASE_GO + END_TREE. A seat at its band while HOLDING = it hands over HOLDING and wraps → retire by hand on the wrap (records on disk verified; `cockpit.sh rotate` is for an UNWRAPPED seat) → launch its 19th on the SAME GROUPING from `briefs_staged/2026-09-22_raise_seatB_successor19.md` / `…seatC_successor19.md` + `.subject` (dry-run rc 0 ×2 at 10:50; **the B brief's "push the 2 un-pushed" premise is STALE — all seven are up; the B 19th = MERGE-on-the-GO + the ONE new Claude-written KS-1179 F2F3 row + now KS-1097 PRPROCESS (a CONTRIBUTING.md doc edit, Ornith's counter spent twice on one byte) — re-derive by own `ls-remote`, amend BLUF/ITEM 0/subject before any send**). Gate drafter reports: `gatesets/2026-09-22_gate18C_seatC/DRAFTER_REPORT.md` (S6: `--shared` freshens loose-object mtimes, content byte-identical — ledger row) and `…gate18B_seatB/DRAFTER_REPORT.md` (S1–S7). Lead for 18B: #1178's F1c/F1d = the 16C gate's NOT-PINNED MFASIBLINGSITES rows → CLOSED candidates.
2. **Ornith: FEED 10 DRAINED 5/5 PASS, all HELD; queue EMPTY; the FEED 11 drafter is RUNNING in this seat** (`briefs_staged/2026-09-22_ornith_feed11.COMMISSION.md` → proposal `…feed11_queue_proposal.md`; its §0 fixes the FEED 10 build defect: `suggested_test_file` must == the brief's `File:` line, asserted per row). On its report: Wednesday's checks (tip == own `ls-remote` + every input's tip; key sets vs `code_1257THREEHUNKS-R16` / `doc_1276` both deltas ∅; **AND per row `suggested_test_file`/`product_file` == the brief's lines BY VALUE**; `+` lines dq/bs/non-ASCII 0; `cmp` after copy) → append the queue lines under a generated stamp → `launchctl kickstart -k gui/$(id -u)/com.wednesday.ornith-loop` → read `done.md` by input path; PASS → `hold_ready.py <run> <golden> <TAG>-R16B <title> --title-from-brief night/briefs/<brief>.md` (the title passed positionally must equal the derived one — run once with `X` to read the derivation, then pass it); FAIL → classify from the artefacts (model/harness/brief) + IMPROVEMENTS row + ONE rebrief (Kam's counter), a second FAIL → a Claude seat. If the seat rotated first: check for the proposal file; re-commission from the COMMISSION file if absent. **Held pool: 18 R16B today + 12 R16 = 30 READYs** (`ls night/READY_*R16B*`) for the round-19/20 raise; FEED 12's pool = whatever FEED 11 §2 leaves + the FEED 10 §3 rows.
3. **#1036 (KS-763) MERGED + verified** (develop `8c2f7b3fd`); KS-763's CLOSE = a later pass once a pushed PR's audit gate is green at the new tip — commission it in a Secuura seat's brief, never by hand. Baseline expiries 2026-09-30 (KS-530, KS-528, KS-729) and 2026-10-02 (KS-528 ×2) — the 09-29 sweep's item.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH — an unquoted `$var` does NOT word-split (a loop over "a b c" specs gets ONE arg; use explicit args or `${(s: :)var}`); `cd` REFUSED by the hook; `rm` outside a LITERAL scratchpad path REFUSED (quarantine, or write the /private/tmp path out); `sleep N; cmd` chains are BLOCKED (use Monitor/run_in_background); `git -C <other tree> <write verb>` REFUSED — write `/Volumes/DevMASTER/WEDNESDAY` out in full; `note_entry.sh --h3 --stdin <<'EOF'` for a heading (the bare `--h3 "text"` is refused — this seat had to insert its boot heading by python from the lines' own stamp); `safe_push.sh` takes each path as its own argument and refuses ignored ones (`_ledger.md.pre-*` backups are ignored — do not name them); a concurrent panel_sync push makes safe_push return rc 3 with the commit made locally — re-run it with no paths; `cockpit.sh say` keys its `--mail` route on the cockpit NAME; `hold_ready.py` modes: test_only / code_patch / bash_patch / doc_patch; a READY's apply-mode/byte-count sentence from an apply output, never typed; every count in a drafted brief re-derived AND every branch/subject name through the hyphenated-key scanner before the send; a receipt to Kam is ONE message per event on the LIVE board, first person, BLUF first.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. Tooling: `hold_ready.py` code_patch path measures CONTEXT-ONLY vs the golden (bash/doc do; today four READYs print "bytes differ; applied result not compared" with identical bodies) · `build_input.sh` derives `suggested_test_file`/`product_file` from the brief's lines when a brief exists · `hold_ready.py` derives the title from the brief and prints WHY on a relative path · `absence_claim_check.sh` adds 'only'/'nothing else' · `send_brief.sh --kind brief` refuses a `feature/…` name carrying a foreign `ks-\d+` · the 09-06 lesson file gains the measured scope of `git clone --shared` (content read-only; loose-object mtimes freshened) — one line, regenerate BOTH digests · `pane_close.sh` prints the listener DIFF · the gate prompt template's ctx rule + "read the WHOLE test file" line · the pretooluse hook: expand a `$VAR` assigned in the same command or say "unresolved variable" · `board_count.sh linear` label filter · `cockpit.sh say` prints WHY it refuses · doctor: expired `PAUSE_QUEUE`, live-poll health · EXPIRING-GRANTS-class rows (Easy Auth secret 2027-03-21, seat certs 2027-09-21; audit-baseline 09-30 / 10-02) · the four §5f escalations re-carded WITH DEFAULTS · dependabot 19 open (ten share #1036's paths) · the 12 FEED-5 card-shaped rows with defaults (Kam reachable today — card the three Kam-class ones: KS-1274, KS-1048, KS-755).

### ROUTE TO KAM (he is on the live page today)
Sent this seat: nothing (nothing needed him). Carried, NOT re-sent: the two cards (`secuura-ks1175-kintsugi-deploy-and-first-anchor` default c; `secuura-ks721-commitment-cannot-reach-a-real-chain` default a); platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi's connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the older READY pool.
