---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 02:14 by the 00:05 Tuesday seat at its 70% CHECKPOINT (ctx ~71; previous copy NEXT-PICKUP.md.pre-0922-0214; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 00:05 Tuesday seat, 70% checkpoint) — replace it, never append

**Kam:** TRAVELLING (left Monday night); his last live-board line 15:43 09-21. `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27, Wednesday's reading; return day unanswered). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`; poller pid 14963, health `fleet/cockpit/state/live_chat_poll.health` — `pgrep -f cockpit/live_chat_poll.sh` at boot). Usage 7d 43%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at a checkpoint (rows conserved).** `night/ALLOW_SEATS` re-armed to END OF SUNDAY 2026-09-27 (epoch 1790517599) on the week instruction — seats and Ornith run together.

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0`: `%0` this seat · `%24` Seat B 16th · `%25` Seat C 16th · `%9` monitor)
1. **TWO RAISE SEATS LIVE on the 30-READY R15 pool at develop `64ab10513`, both plans CONFIRMED by Wednesday's ANSWERs (C 16:0xZ = 02:0x AEST; B ~02:12 AEST — B's pointer tap is QUEUED at its prompt and delivers at its turn end; the ANSWER is in its inbox regardless):** Seat B 16th = 9 PRs / 14 READYs (originate ×5, shared ×2, anchoring, security — KS-928, 1118, 1133, 1158, 1229 (five READYs one file), 1179, 1181, 1171 (two files), 975), all-14 tree `649ccf34c6d1…`; Seat C 16th = 13 PRs / 16 READYs (api-gateway ×6, auth ×6 — SIX auth-surface test-only pins, scripts — KS-864, 1123 F3b, 1180, 1185, 1199, 1237, 855, 944, 1156, 1188 (three files), 1193 (two files), 1217, 910 bash), all-16 tree `48528fa3c355…`; all-30 `0e1f2c465752…`; partition by DIRECTORY, overlap 0; `--recount` MANDATED on every apply (seven READYs are silently TRUNCATED by strict apply). Briefs: `briefs_staged/2026-09-22_raise_seatB_successor16.md` + `…_raise_seatC_16.md` (+ `.COUNTS.md`); answers `…_seatB16_answer_plan.md`, `…_seatC16_answer_plan.md`. **Each seat: READY mails per PR (`[Secuura/Blockchain-B|-C -> Wednesday] READY FOR QA (Seat X 16th): PR <n> …`) → HOLD after its last READY naming its GO subject → ONE batch gate per seat** (commission a gate drafter per seat from the gate15 shape: `gatesets/2026-09-21_gate15_docs_comments/COMMISSION.md` + README; tier-2 floor with the auth pins expected at tier 1 on C; re-pin at launch; routing line `QA/Secuura-batch<first>|coagent@agentmail.to|yes` FIRST) → verdict → completion check at source (report sha; addendum parse; blobs) → signed GO per seat naming every head, BASE_GO = the then-current develop (the OTHER seat's merges move it — re-read before each GO; the two GOs merge in either order, measured) → merges → verify at source → rule-7 bytes → score + `pane_close.sh` in ONE action. Seat C's Q-910: `Refs KS-910` only; the KS-910 CLOSE (Kam 2026-09-16 09:53) is Wednesday's closing pass after its merge.
2. **Ornith: FEED 3 running (KS-947 test_only taken 02:12; KS-1265 code_patch queued).** PASS → source-read + `hold_ready.py <run> <golden runs/2026-09-22_feed3-drafter-precheck/<row>> <ROWID> <TITLE>`; FAIL → classify (model/harness/brief) + IMPROVEMENTS row + the ONE rebrief. **The candidate pool is THIN at the easy tiers** (the FEED 3 drafter read every T1–T4 row + 3 T5: 2 briefable, 36 skipped — 14 decision-class, 10 feature/design, 7 multi-file; report `briefs_staged/2026-09-22_ornith_feed3.REPORT.md` §0.1 = the round note, to be carried into `night/candidates_rounds.md`). After FEED 3 drains the queue is EMPTY again → widen: (a) the next `derive_candidates.py` run (nightly on the loop) over the board as it moves; (b) T5 multi-file rows briefed as SPLIT single-file briefs where a cell reaches the file directly; (c) the 14 FEED T product-code READYs (census15 §5; auth-product rows OUT) — a RAISE pool for a Claude seat, not model feed; (d) say so to Kam in the receipt rather than idling quietly. **KS-1227: two Ornith rounds FAILED (a `\n`-serialisation defect both times) → REALLOCATED to a Claude seat under Kam's counter — fold into the next api-gateway raise/fix seat (its file is Seat C's directory).**
3. **Live-board poller** pid 14963 — `pgrep` + a fresh OK line at every boot. **`reconcile_rulings.py` at every checkpoint (last 02:13: nothing to reconcile; Kam quiet since 15:43 09-21).**
4. **Morning receipt to Kam on the LIVE board at ~06:00 (`chat_reply.sh`; first person; BLUF; short):** merged (#1136–#1146, develop 64ab10513, rule 7 posted); the 16th round (22 PRs in flight on two seats); Ornith (FEED 2 17/18 PASS held; FEED 3 running; the thin pool — the honest line); blockers + cards (`secuura-ks1175-kintsugi-deploy-and-first-anchor` default c; `secuura-ks721-commitment-cannot-reach-a-real-chain` default a); skipped items (KS-1227 → Claude; KS-1239 trap).
5. **DONE THIS SEAT, verified at source:** gate15 (ten GO WITH FINDINGS) → GO → ALL TEN MERGED (develop `64ab10513`, tree `87b4aa12d2eb`, 10 commits, 11/11 blobs) → rule 7 posted (KS-485 `07503fcd…`, KS-772 `035cb517…`) → gate `%23` + Seat B 15th `%22` closed, both scored 1.00; ALLOW_SEATS re-armed to Sunday 27th; FEED 2 sat (13 held → 31 READYs; KS-1227 classified); the 16th briefs drafted (364K-token drafter), counts re-derived, both seats launched + confirmed; FEED 3 drafted (309K) + queued. Ledger +4 this seat (a typed clock in ALLOW_SEATS; a push receipt read wider than it staged; the KS-910 READY's unmeasured apply mode + chars-as-bytes; the fleet vault-note overwrite).

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad; no `sleep N; cmd` chains (run_in_background from a script FILE); a refusable tool's rc on its own line; NEVER `pgrep -fl` the wake_watch runner. **`safe_push.sh` stages ONLY the paths named on its command line (+ decisions.json) — name every modified tracked file too, or "committed" carries only the new files (this seat's 00:1x slip).** `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. Mail body whole = `inbox_digest.sh full <inbox> '<message-id>'` into a scratch file, then Read. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only; no STOP/HOLD token mid-subject). Taps by pane NAME with `--mail` (verifies at the destination first). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. Every count in a drafted brief re-derived or marked "drafter's count". `lsof … | grep -i node` matches the header's NODE column — drop the header first. `set -- $var` does not word-split in zsh (use python). The loop kick = `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`; the loop runs max 4 tickets per fire and re-fires every 15 min — "runner not running" between fires is by design.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. Ledger 3c (09-18 rows → archive) · `hold_ready.py` bash_patch support (KS-910 held by hand; `KeyError: test_file`) · checker T1 `ESCAPED-NEWLINES` refusal (the KS-1227 class; red arm = `runs/2026-09-22_ks1227-ornith35b-night/out.md`) · checker header-rewrite candidate (`--recount` class, 11/14 + 4/13 today) · KS-1192 rebrief (backslash-free literal) · FEED T tier call · `wake_ack.sh` keys on the detector verdict class · `04_deploy.sh` api-version refusal · doctor.sh: live-poll health + dashboard venv · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · SYSTEMTESTPUSHUNGATED + PLACEHOLDERPINSHAPE + STDERRTAILONABORT ticket candidates · doctor warns on an expired `PAUSE_QUEUE` · `derive_candidates.py` misses `Blockchain/Testing/` · Tuesday's line for Kam (the vault note overwrite) · INDEX.md refresh + the projects' history skim (deferred by the overnight seat to the morning sweep).

### ROUTE TO KAM (nothing sent this seat — he is travelling and quiet; the morning receipt is item 4)
NEW since his 15:43: the ten merges #1136–#1146 verified + rule 7 posted; FEED 2 17/18; the 16th raise in drafting. Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (O 36 / R 17 / T 24 / D 11 — R now in the 16th's pool).
