---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 15:14 by the 11:0x Wednesday seat at its ROTATION HANDOVER, ctx 80 (band 80-90; previous copy NEXT-PICKUP.md.pre-0922-1514 beside; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 11:0x seat, rotation handover) — replace it, never append

**Kam:** AT HIS COMPUTER and on the LIVE board (his 08:59); reachable, answering within minutes. **ONE OPEN QUESTION with a DEFAULT on the board (14:4x):** whether to delete his PERSONAL Ollama store `/Volumes/DevMASTER/SYSTEM/ollama` (269 G, twelve models + the fleet's 09-16 ornith/gpt-oss copies) — his instruction 14:35 "delete all the other models" was executed on WEDNESDAY's store (gpt-oss ×2 removed, 74 GB freed, Ornith proved live with the FLEET binary `tools/ollama/ollama`; Homebrew's binary answers `unknown renderer "ornith"` — an instrument, not the model); the personal store is HIS → default LEAVE until his word ('all of it' = remove everything there except the Ornith copy, with `tools/ollama/ollama serve` on that store + `ollama rm`, then a generate control on the remaining Ornith). Closed today on the board: the travel-drive question (2 TB, folder walk: !CODING 828 G · SYSTEM 269 G · WEDNESDAY 73 G) — he bought a 2 TB; the Studio cross-config check (clean, controls stated; praise 14:30); the six Ornith rows HIDDEN on the LIVE Datasec tab (a reversible hide built + deployed, 112/112 probes; told 15:1x). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27). Poller pid 14963 + usage publisher pid 9380 (`pgrep` at boot). Usage 7d ~74%, gate open. The 06:00 receipt for 09-23 is the successor's. 🔴 **`git stash list` = 23 autostash entries (the day's record of the safe_push defect below) — READ IT AT BOOT, never drop; the tree holds everything (17/17 real files == stash@{0}; done.md/queue.md newer in the tree).**

### 🔴 IN FLIGHT (floor at the handover: `%0` this seat · `%35` Seat B 19th (ctx ~70, raising 9 PRs) · `%36` Seat C 19th (ctx ~70, 12/12 raised, pushing) · `%9` monitor; no subagent running)
1. **ROUND 19 (both seats plan-confirmed + GO'd; base 3bad652d1 = the 13-PR tree):** Seat B 19th — 11 READYs → 9 PRs (KS-730, KS-1028, KS-1160, KS-1229, KS-629-A, KS-974, KS-976 (`--pair-blob`, second of the security/index.ts pair), KS-1164 (RULED (b): a DECLARED whitespace-only prettier rewrap of the model's new test file, `git diff -w` empty as the proof, new blob stated; product untouched), KS-1179 (Claude-written)); tier 1 ×8; Q-629 Part B DEFERRED (Wednesday's rebrief). Seat C 19th — 14 READYs → 12 PRs (ten bash + KS-1097 ×3 by file; KS-1034+KS-1093 one PR; KS-972 before KS-1011 (`--pair-blob`)); tier 1 ×9; MG-11 bound; its GO subject = ITS twelve only; Q-1047 IN (the pre-push hook comment PR proves the modified hook with the hook's own leg summary). **Wakes:** each READY → own `ls-remote refs/pull/<n>/head`, develop unmoved-or-attributed, one note line; each HOLD → its batch-gate drafter from `fleet/qa-agent/gatesets/2026-09-22_gate18{B,C}_seat{B,C}/COMMISSION.md` re-keyed 19 (base 3bad652d1; pair blobs; MG-11; `.push-lock-19/`; the KS-1164 amendment as a finding to grade) → routing line → prompt read → `--check` by own hand → repin + launch → verdict → completion check at source (report sha; DKIM from the API; NOT-TESTED first; the SEAT'S OWN targets19.py on a scratch copy of its raise/+gate/ records; blobs at heads by `ls-tree`) → signed GO (subject exactly as the HOLD; BASE_GO re-read in the send action; the first GO's merges move develop for the second — say so) → merges → verify at source → rule-7 drafts read whole → RULE → wrap → score + `pane_close.sh` in ONE action. A seat at its band while HOLDING hands over HOLDING; retire on its wrap, launch its successor on the same GO. **Seat B 19th's S1 (a boot-prompt `pull` of the shared checkout, ruled LEAVE; develop there = 3bad652d1 = origin)** — the no-pull line goes at the TOP of every Secuura successor brief until the launcher-vs-brief card is ruled.
2. **Ornith: FEED 13 RUNNING** — queue at the handover: the DUPLICATE `code_1121EXACTID-R16B` run (a stale line `move_done` never removed — NOT a counter round; IMPROVEMENTS row written) then `code_1121EXACTID2-R16B` (Kam's ONE rebrief for KS-1121 — a second FAIL → Claude) then `code_1239RAWAUTHDEAD-R16B` (a fresh-derivation row; the held KS-1234 READY on the same file is STALE and disjoint — sequenced at the raise). Read `done.md` by input path; PASS → `hold_ready.py <run> <golden> <TAG>-R16B <title> --title-from-brief <brief>` (goldens in `runs/2026-09-22_feed13-drafter-precheck/<EXACTID2|RAWAUTHDEAD>/`; derive the title with `X` first, then pass it); FAIL → classify + IMPROVEMENTS + (KS-1239 only) ONE rebrief. **The pool at this tip is thin** (FEED 13 census: 41 rows tabled with reasons in its proposal §2; two best-next needing measurement: KS-1287, KS-1145) — the next feed waits for the round-19 seats' NOT-PINNED rows from their gates (the gates' feed), not another sweep; say so in `QUEUE_EMPTY_WHY.md` when it empties. **Held pool: 23 R16B** (`ls night/READY_*R16B*`) — the round-19 raise consumes them; new holds after the 19th sends are round 20's.
3. **#1036 (KS-763) MERGED + verified;** KS-763's CLOSE = a later pass once a pushed PR's audit gate is green at the new tip — a round-19 seat's wrap may carry it; never by hand. Baseline expiries 2026-09-30 / 2026-10-02 — the 09-29 sweep's item.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH — an unquoted `$var` does NOT word-split (a loop over "a b c" specs gets ONE arg; use explicit args or `${(s: :)var}`); `cd` REFUSED by the hook; `rm` outside a LITERAL scratchpad path REFUSED (quarantine, or write the /private/tmp path out); `sleep N; cmd` chains are BLOCKED (use Monitor/run_in_background); `git -C <other tree> <write verb>` REFUSED — write `/Volumes/DevMASTER/WEDNESDAY` out in full; `note_entry.sh --h3 --stdin <<'EOF'` for a heading (the bare `--h3 "text"` is refused — this seat had to insert its boot heading by python from the lines' own stamp); `safe_push.sh` takes each path as its own argument and refuses ignored ones (`_ledger.md.pre-*` backups are ignored — do not name them); a concurrent panel_sync push makes safe_push return rc 3 with the commit made locally — re-run it with no paths; `cockpit.sh say` keys its `--mail` route on the cockpit NAME; `hold_ready.py` modes: test_only / code_patch / bash_patch / doc_patch; a READY's apply-mode/byte-count sentence from an apply output, never typed; every count in a drafted brief re-derived AND every branch/subject name through the hyphenated-key scanner before the send; a receipt to Kam is ONE message per event on the LIVE board, first person, BLUF first.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. `safe_push.sh` now REFUSES rc 6 when the pull strands an autostash (built + armed this seat) — the successor reads `git stash list` at boot and restores by hand if a new entry appears (`git show 'stash@{0}:<path>'`, backup beside; never drop). · **Launch_Tuesday.command week-instruction line: make it SEAT-AWARE so the Tuesday seat is never told to keep Ornith running (Kam 2026-09-22 10:32; Tuesday handed it to Wednesday 04:32Z) — a launcher edit, backup beside, both branches read (the wednesday line unchanged; the tuesday line without Ornith); claim it in the note, then mail Tuesday one line.** · **Card for Kam: the Secuura launcher's first action ("pull latest if safe") contradicts the fleet brief's ITEM 0 ("LEAVE IT") on the shared checkout — his shared file; Seat B 19th's S1 was the instance (ruled LEAVE); the no-pull line goes at the TOP of every Secuura successor brief until he rules.** · **The 6 Ornith rows on the LIVE Datasec tab: a builder is adding a reversible HIDE (routes on the seat-key path, own-tab rows only, audit line, arms, zip-deploy with the tenant guard) and hiding the six by id — on its report: re-probe by own hand, read the tab list (six absent, count before/after), mail Tuesday one line, tell Kam on the live page in one line; the LOCAL `chat_tuesday.json` rows are left alone (chat_sync unions from origin — a local quarantine would be undone).** · Tooling: `hold_ready.py` code_patch path measures CONTEXT-ONLY vs the golden (bash/doc do; today four READYs print "bytes differ; applied result not compared" with identical bodies) · `build_input.sh` derives `suggested_test_file`/`product_file` from the brief's lines when a brief exists · `hold_ready.py` derives the title from the brief and prints WHY on a relative path · `absence_claim_check.sh` adds 'only'/'nothing else' · `send_brief.sh --kind brief` refuses a `feature/…` name carrying a foreign `ks-\d+` · the 09-06 lesson file gains the measured scope of `git clone --shared` (content read-only; loose-object mtimes freshened) — one line, regenerate BOTH digests · `pane_close.sh` prints the listener DIFF · the gate prompt template's ctx rule + "read the WHOLE test file" line · the pretooluse hook: expand a `$VAR` assigned in the same command or say "unresolved variable" · `board_count.sh linear` label filter · `cockpit.sh say` prints WHY it refuses · doctor: expired `PAUSE_QUEUE`, live-poll health · EXPIRING-GRANTS-class rows (Easy Auth secret 2027-03-21, seat certs 2027-09-21; audit-baseline 09-30 / 10-02) · the four §5f escalations re-carded WITH DEFAULTS · dependabot 19 open (ten share #1036's paths) · the 12 FEED-5 card-shaped rows with defaults (Kam reachable today — card the three Kam-class ones: KS-1274, KS-1048, KS-755).

### ROUTE TO KAM (he is on the live page today)
Sent this seat: nothing (nothing needed him). Carried, NOT re-sent: the two cards (`secuura-ks1175-kintsugi-deploy-and-first-anchor` default c; `secuura-ks721-commitment-cannot-reach-a-real-chain` default a); platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi's connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the older READY pool.
