---
date: 2026-09-16
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's (live again on the Mac mini since 19:43). Kam 14:02 "Feel free to read the Datasec content" was for fixing her STRUCTURE; Datasec client WORK is still not Wednesday's.
source: replaced WHOLESALE at 20:2x by the 20:0x seat (Studio relaunch after the 19:47 wrong-tree boot). Previous copy: NEXT-PICKUP.md.pre-2024-wholesale.
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words:** 19:34 *"keep working through the night on the backlog and todos using the local agent"* · 20:07 *"let me know if the mail comes in. when it does, work with Tuesday and get the structure working"* · 13:32/13:35 limited Secuura work on this (Datasec) account until SUNDAY, local LLM on backlog · 09:53 *"If something's blocking, move on to the next"* · 07:45/07:57 (email) local model PERMANENT; failed ticket = original + ONE rebrief, then a Claude agent · **he leaves MONDAY NIGHT 2026-09-21.** First person on the panel. **A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.**

## 🔴🔴 FIRST ACT OF THE NEXT SEAT (written 21:3x at rotation)
**Seat A `%2` mailed READY FOR QA: #999 KS-1130 @ `91793e5d4f4d4b70eec93662c45555472e2bb8a6` (11:29Z, spf/dkim/dmarc pass) — test + comment only, 5 files under api-gateway, "Closes KS-1130".** Wednesday ACKed (the gate comes from the next seat; seat A continues A3 KS-960 / A4 KS-1165). **Launch its TIER-2 QA gate** (through-code tier per `learnings/2026-09-05_qa-gate-tiers-and-the-two-nogo-cap.md`; template `fleet/qa-agent/BRIEF_TEMPLATE.md`; `usage_gate.sh --check` first — seat cut 40, now seat-scoped `fleet/USAGE_STOP` vs `USAGE_STOP.tuesday`) → verdict → completion check → `GO: #999 KS-1130 @<head re-read at origin>` to `Secuura/Blockchain` → verify the squash at origin. The seat's mail lists its tamper table + deviations (E7 dead lines removed, E7 tamper constructed, P3 typeof kept) for the gate to review.

## ⚡⚡ KAM 20:40–20:42 — THE NEW STANDING WORD (read before FIRST ACTS)
*"as I have signed you into a new account we have context. you have the approval to spin up other local agents to test, approve, merge and move things forward"* · 20:41 *"yes. claude agents"* · 20:42 *"and see what else needs our attention. highest priority and highest value items first"*. Grant filed: `learnings/2026-09-16_new-account-spin-up-agents-to-test-approve-merge.md` (NOT covered: deploys, demo/UAT, external comms beyond ticket comments, workflows PRs, other authors' PRs; usage gate still applies).
**Two drafting subagents were running at 20:45 (session-local — if this seat is a successor they died with it; their OUTPUT FILES are the durable part):**
1. `fleet/briefs_staged/2026-09-16_raise_PLAN.md` + `2026-09-16_raise_seat_<A|B|C>.md` — the staged Ornith raise brief refreshed against origin develop, partitioned into ≤3 seats by disjoint file family.
2. `fleet/briefs_staged/2026-09-16_attention_RANKED.md` — everything else on Secuura ranked priority × value (stalled PRs at gate/merge, P0/P1, the four Claude-reallocated tickets, undelivered rulings) + a lane partition + NEEDS-KAM with defaults.
**Next when they land:** read both; reconcile lanes so NO two seats share files (Ornith raise lanes vs attention lanes); `usage_gate.sh --check`; launch each seat with `fleet/brief_and_launch.sh` (send → verify at destination → launch); rung-5 check each pane; then run the QA gate per READY FOR QA and GO/merge under the TESTED grant, one at a time. **If the files do not exist, re-commission from this paragraph.** Delegate before the band: launch the seats, THEN rotate with them running (09-13 rule).
**⚠ KAM 21:1x: "dont go overboard. try not to go beyond 40% token allocation"** → `fleet/USAGE_STOP` = 40 (usage_gate reads it; every launch refuses past 40). **STATE AT 21:08:** ONE seat live — **raise seat A `%2` (`Secuura/Blockchain`)**, brief `fleet/briefs_staged/2026-09-16_raise_seat_A.md` (16 PRs, ≤3 open awaiting GO; its FIRST mail is a plan-confirmation QUESTION to wednesday-agent@ — ANSWER it; ITEM 0 waits for it). **Your job as its coordinator:** answer plan confirmation → for each `READY FOR QA: #<n> … @<sha>` run a QA gate (tier per the 09-05 rule; launch through the usage gate) → on GO verdict + your completion check, send `GO: #<n> <ticket> @<sha>` to `Secuura/Blockchain` → verify merge at origin. Seats B and C are STAGED ONLY: their briefs still say GOs arrive in `coagent@` (WRONG — `secuura-blockchain@` per `fleet/inbox_routing.conf`) and have not had Wednesday's end-to-end read; fix + read before any launch, and only with usage headroom (Kam's "dont go overboard"). **Lane briefs STAGED (drafter finished 21:1x), NOT launched by decision:** `fleet/briefs_staged/2026-09-16_lanes_LAUNCH.md` (a one-at-a-time menu: lane B `2026-09-16_lane_B_builder.md` pane key `Secuura/Blockchain-D` — KS-1076 item 2 then KS-998 item 1; lane A `2026-09-16_lane_A_gate995.md` — the #995/KS-741 tier-1 gate re-pinned at head `b8155636e`, needs a drafting subagent before launch; lane C `2026-09-16_lane_C_builder.md` key `-E` — KS-753 only). Both builder briefs pass `send_brief.sh` in DRY RUN. **Before launching ANY of them:** (1) measure seat A's usage burn (7d gauge before/after its first PR) against Kam's 40% cap; (2) STRIKE the line in both builder briefs that lets the seat start without the plan-confirmation ANSWER; (3) do Wednesday's own end-to-end read (the send gate requires the attestation). **Known collisions held out:** KS-801 (api-gateway) and KS-1150 R-2 / KS-806 (auth) sit in raise seat A's partition — not until seat A finishes those files + Kam's auth yes; #922 (regenerates the OpenAPI yaml = raise seat B's file) and #920 (DEV-PROCESS.md = raise seat C's) resolve by merge order only. **Raise seat B/C briefs + raise_PLAN.md still name `coagent@` (wrong) and seats A/B list seat C as owning ALL of `systemTest/**`, contradicting the PLAN table and lane B — fix before any B/C launch.** **Ornith runs WITH seats until 2026-09-17 06:00** (`night/ALLOW_SEATS`; the morning seat re-decides). Kam's auth question (Claude seats on login/token code, KS-1150/KS-806; rec yes) was UNANSWERED at 21:08.
**ORNITH at 21:20 (Kam 21:1x "keep working through easier tickets with the local LLM as well"):** KS-910 r2 HELD · KS-1034 HELD (retry 7/7) · **KS-789 FAIL D7 → ONE REBRIEF OWED** (whole-run `CONTRIBUTING.md:384–:386` replacement; detail on its `night/done.md` row; a second failure → Claude). **QUEUED 21:31 by the search: KS-987 item 1 · KS-890 · KS-1036 item 3 — all DOCS** (next loop ~21:35). **Source-read each PASS before a READY** (docs: read the inserted prose against the file's own standing lines — tonight's premise rule). **The pools are EXHAUSTED at this tip** (test-only vitest + bash; 52 read + 58 title-level, table in `candidates.md` EXCLUDED) **except**: the KS-789 rebrief (owed) · tickets in raise seat A's partition once its PRs merge · a new tier. **When the 3 docs land and the queue empties, the first act is the KS-789 rebrief — never an empty queue.** Every agent-mail turn ends with a queue read.
**Tuesday structure work: DONE on both machines** (her DONE 10:41Z: step 5 `e559f35a7`; FDA granted 20:33, chatsync exit 0; her `install_all_jobs.sh --check` LOADED-DRIFT fix `559090e08`, Studio 9/9 clean). Nothing owed between the seats except her next-boot preflight. Item (a)/(b) below are closed.

## 🔴 FIRST ACTS
1. `kam_rulings_today.sh` (read the `view=` of each; `kam_msgs.sh` shows it) → `reconcile_rulings.py`. Taps in `view=tuesday` on `Datasec/Tuesday` cards are HERS: route verbatim by mail (`send_brief.sh --to "Tuesday" --kind answer`), never rule them — the reconciler SKIPs them by scope, correctly.
2. **Ornith state:** `night/queue.md` pending lines · `night/log/.night_run.lock` · `tail night/log/night_$(date +%F).log`. The loop (`com.wednesday.ornith-loop`, every 15 min, last-exit 4 = queue empty) takes queue lines by itself — append a line, do not launch by hand into its settle.
3. **The 20:07 commission's report:** `…/scratchpad/commission_2007_report.md` of the 20:0x session is SESSION-LOCAL. If this seat is a successor, the durable results are the brief FILES it wrote: `night/briefs/KS-789.md` (JOB 1: premise corrected from measurement — CHECK its `## Premises (measured)` section before queuing) and any NEW `night/briefs/KS-*.md` newer than 20:17 (JOB 3 search). Every brief from it: read its premises against the tip + live system BEFORE queuing (tonight's rule, below).
4. **Tuesday loop (Kam 20:07):** read `wednesday-agent@` for `[Tuesday -> Wednesday]`. OPEN with her: (a) the DAILY-NOTE SPLIT — AGREED after her census (10:23Z) and her RE CLAIM (10:28Z). **Wednesday CLAIMED and a builder subagent is implementing ONE commit:** `tools/note_entry.sh:13` + `voice/speak.sh:39` + `scheduler/close_wednesday.sh` (:158, the hardcoded literal at :241, :256) + `fleet/hooks/session_start_compact.sh:13`, via `fleet/cockpit/seat_resolve.sh` — folder WEDNESDAY → `0_Brain/daily/` (unchanged), TUESDAY → `0_Brain/daily_tuesday/`, ANY OTHER folder → REFUSE (matches `install_all_jobs.sh:55-61`; my first design defaulted it to wednesday — cross-client, Tuesday caught it, SUPERSEDED ~20:31); disagreement WED_AGENT≠tree → refuse; `speak.sh` NEVER fails on resolution (falls back to shared dir, still speaks); cutover recorded in `0_Brain/daily_tuesday/README.md` + the commit message; arms file `fleet/tests/seat_daily_note_arms.sh` incl. the close bell agreeing with the writer on a Tuesday-shaped tree. **LANDED `82af9d579` 20:3x, VERIFIED by Wednesday (arms 18/18 own run; live `note_entry.sh --where` = `0_Brain/daily/…`; WED_AGENT mismatch refuses rc 2; doctor 0 ✗), HASH mailed to Tuesday — boot step 5 is hers now.** Watch: tonight's 23:00 close bell is the FIRST live run of the new bell code — read its log (`fleet/cockpit/logs`) and confirm today's note was found/stamped; (b) FDA re-measure on the mini (Kam's 20:22 "done, please check"); (c) her next-boot preflight verbatim, owed when she rotates.

## ✅ THIS SEAT (20:0x → 20:2x)
- **Ornith:** KS-1033 item 1 PASS 7/7 first sample → HELD (`READY_KS-1033-item1_…`; the guard's fallback base `origin/main` → `origin/develop`; ticket stays OPEN — items 2/3 are not this diff). **KS-866 PASS 8/8 first sample → NOT HELD**: its prose documents `git merge --no-ff` + `push origin HEAD:develop`, which contradicts CONTRIBUTING.md:107 ("Feature PRs into develop stay squash") and :481 ("Never push straight to develop"); develop's last 30 commits show our merges as 1-parent squashes → REALLOCATED to a Claude seat (Sunday), reason on its `done.md` row. **KS-789 PULLED before it ran** (brief said "There is no CI" — Actions API: 23 workflows active, PR/develop runs through 09-15 concluding failure). **KS-910 (Kam ruled a): r1 + retry FAILED B3b 20:28** (the model marked `:50` as `-` instead of `:49` — the wrapped-run dialect; my brief's defect). **r2 = THE ONE REBRIEF** (whole-run `:49-:51` replacement, CONTROL anchor `:47`, pre-measured tip 2 red / fixed 4/4) queued 20:3x for the ~20:39 loop tick. **r2 PASS → source-read + READY; r2 FAIL → KS-910 goes to Claude (Sunday batch), no third round.** Measured premise from the commission worth keeping: Actions run 34961722314 DID execute "All shell test suites" (→ failure), `pr-security-gates.yml:100`.
- 🔑 **RULE FROM TONIGHT (ledger w=2 in one evening): a brief's PROSE PREMISES are claims about the live repo/process and get an instrument before queuing.** The builders gate `-` lines at the tip; nothing gates "no CI", "in force on both seats", "leg 14 runs it". Read the premise against the file's own standing lines and the live system (GitHub API with Secuura's `GH_TOKEN`, read-only).
- ⚠ **"CI runs the suites" in Kam's 09:53 KS-910 tap is WEDNESDAY'S card option text, not his observation** — a tap on my wording is not independent evidence (rung 9). preflight.sh:544-552 says the Actions shell-suite steps are dormant; the Actions API says workflows still RUN on PRs (failing). Whether any run executes the shell suites is UNMEASURED — the commission was told to measure it (jobs/steps API) or refuse KS-789.
- **Tuesday (Kam 14:00/15:06/20:07):** her STATUS 20:08 + ANSWER 20:18 (spf/dkim/dmarc pass). DONE and verified by Wednesday: both boot bugs `56f0a020d` + F1/F2 `316ed56e5` (drain guarded by `[ -t 0 ]`; 5-min boot BOUND posts one panel line, never injects); nine plist templates' hardcoded `/Users/kam_code` logs → a HOME placeholder `8ff4620c5` (Studio `install_all_jobs.sh --check` 9/9 matching); 83 exec bits fixed in the INDEX. **Wednesday DONE:** doctor 126 (TCC/FDA) vs 78 (EX_CONFIG) split in both places, arms `2_Project_Files/fleet/tests/doctor_exithint_arms.sh` 13/13 (two negatives on `doctor.sh.pre-0916-exithint`). **The Studio's fleet-monitor was re-armed on her fixed `monitor.sh`** (it had run pre-fix code since 19:59): `bash -n` → `--once` → `tmux respawn-pane -k -t <fleet-monitor pane> "\"…/monitor.sh\" --interval 60 --stall-min 10; echo; echo '[cockpit] fleet-monitor exited — pane stays for inspection'; exec bash"` — the string goes to the pane's shell DIRECTLY; wrapping it in another `zsh -c` drops the args.
- **Kam's 09-11 FDA grant for the mini: MEASURED NOT APPLIED by Tuesday 20:0x** (chat_sync exit 126 EPERM from launchd). Kam 20:22 on the one-launch card: "done, please check" → Tuesday re-measures. Wednesday's card `tuesday-mac-mini-scheduler-full-disk-access` stays UNDELIVERED until her number says 0.
- **Kam 18:51 "what's the available space"** answered 20:04: internal 615 Gi available, DevMASTER 927 Gi (df). The 128 GB duplicate ollama store at `2_Project_Files/local-model/models` is still there — his to say if "please reclaim" meant it (he ran the Time Machine snapshot deletion himself at 18:52); Wednesday cannot `rm` it (hook) and hands him the command only on his word.

## ⚠ TRAPS (new tonight — read before touching git)
- **Push Wednesday's repo ONLY with `2_Project_Files/tools/safe_push.sh "<msg>" <paths>`.** Tonight two hand-rolled `pull --rebase --autostash` runs displaced three panel entries from the chat stream files (recovered by `python3 2_Project_Files/tools/chat_streams.py --harvest`, then verify it prints the entry total with no orphans). `rebase --continue` refuses on ANY unstaged tracked change and the dashboard writers change `0_Brain/dashboard/data/*` every minute — its message ("You must edit all merge conflicts") misleads. Never `rebase --quit` with an autostash present.
- **panel_sync SKIPs its rebase while ANY path outside `dashboard/data` is dirty — untracked Ornith inputs and `.pre-*` backups included.** Commit artefacts as you make them or your commits never reach origin (the rotation will then refuse).
- **Tuesday's seat writes into `0_Brain/daily/<today>.md` too** (same repo). A rebase conflict there is two appends: keep both, hers first. Never drop either.
- **`/bin/bash` is 3.2: `read -t` takes INTEGERS only** (0.1 is "invalid timeout specification", rc 1). **`send_brief.sh` refuses any `@WORD@` in a body** as an unfilled placeholder — reword literal mentions.
- The older traps still hold: `git -C $VAR <write verb>` refused (literal paths) · `rm` outside the scratchpad refused · never edit `night/*.sh` or a checker while a runner is live (`.new` + `mv`) · **never edit a running bash script in place** (Tuesday's 20:18 lesson: bash reads by byte offset) · macOS has no `timeout`/`setsid` · `chat_reply.sh` refuses a repeated sentence (`CHAT_DRY=1` to test) · the prior-ruling gate: never `--override-prior-rulings` on the first run.

## 📋 COMMISSIONING — the shape that works
One subagent, the BRIEF RULES verbatim (below), "commission the SEARCH, not the ticket", "a measured REFUSAL is a complete answer", **and now: a `## Premises (measured)` section in every brief.** Report to a FILE; the agent never queues. Exemplars: bash `night/briefs/KS-1047.md` (comment fix 7/7), `KS-1081.md`; tamper vitest `KS-960.md`; docs `KS-866.md` (shape good, premise stale).
**BRIEF RULES** — a vitest brief DECLARES its reds (🔴 in each red `it(` title, or `## Red cells`) · no CONTEXT lines inside `## The exact change` fence · every `-` line byte-for-byte and UNIQUE at the tip · no backslash continuations · no `\$`/`\u` in a `+` line · one hunk per function when a line repeats · NEVER re-add unchanged lines as an anchor · `+` lines only lines absent at the tip · cells LITERAL, declarations first, nothing a cell reads in prose · every 🔴 red BY ASSERTION at the tip + one 🟢 control · test body under ~110 lines + the completeness arm · insert-after: name the anchor line's text, mark "(correct) … stays" · mid-statement tamper needs `statement_ok:` · **every premise measured.**

## ⏳ OPEN / BLOCKED
- **Reallocated to Claude (Sunday batch, do NOT re-queue at the local model):** KS-1168, KS-1163, KS-998 (counter), **KS-866** (stale merge-shape premise).
- **Pool:** `night/candidates.md` T1 is exhausted (rejection table in its comment block); T2b mostly held/reallocated/Kam-class; the widening is T5 splittable + tamper-graded coverage tickets. The 20:07 commission's JOB 3 rejection table goes INTO `candidates.md` when it lands.
- **Tuesday's 20:10 retro raised the digest size** (465 KB by-tier; "past 50% before it does anything" on her seat) — a CONSOLIDATION item for Kam. Wednesday's data point: whole digest + whole ledger = ctx 31% on the Studio.
- **Sync:** the KK_DEV_Local chained leg and the unison scans were stopped at 18:5x when Kam's four copies replaced them (verified at the destinations 19:40). Nothing sync-related is running or owed.
