---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 22:24 by the 20:1x Monday seat at its 70% CHECKPOINT (previous copy NEXT-PICKUP.md.pre-0921-2224; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 20:1x Monday seat, 70% checkpoint) — replace it, never append

**Kam:** LEAVES TONIGHT; last line on this tab 15:43 (live board); terminal lines 18:4x–18:5x (portable drive). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27 = Wednesday's reading; return day unanswered). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`). Usage 7d 38%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at the next checkpoint (rows conserved).**

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at the checkpoint: `%0` this seat · `%9` monitor · `%22` Seat B 15th, launched 21:41, plan CONFIRMED 22:04, committing its ten worktrees at 22:17 (ctx 50))
1. **Seat B 15th (`%22`) — raising 14 doc/comment READYs as TEN tier-2 PRs / 11 files at develop 581ed7fa1** (brief `briefs_staged/2026-09-21_raise_seatB_successor15.md`; ANSWER `…seatB15_answer_plan.md`: Q2 ten by file · Q4 PR 3 raised on its own `az vm show` read · Q6 `×`→`x5` · Q7 `ks-597s-` excised · Q8 the shared checkout LEFT on develop 581ed7fa1 (its pre-brief ref write, disclosed first — no second write; local develop now 0 behind)). **Wake = READY 1..10** (topics `READY FOR QA (Seat B 15th): PR <n> …`; re-read each head by own `ls-remote refs/pull/N/head`; develop unmoved) → around READY 8 commission the BATCH-GATE DRAFTER (tier-2 floor; the 14th's gateset `fleet/qa-agent/gatesets/2026-09-21_gate1130to1135/` is the shape — README, COMMISSION, launcher `launch_qa_secuura_batch<first>-<last>.sh` pinning develop + every head by branch AND `refs/pull/N/head`, prompt with by-name items incl. F2 (#920/#887 on DEV-PROCESS.md), F4 (CLAUDE.md :303 + "step 6"), F5 (proxy.ts count 6), the comment-only proof, the three `--recount` rows, KS-1036-item3 run-patch-not-fence, the VM read as evidence) → prompt read WHOLE → `--check` → repin + launch (`cockpit.sh add QA/Secuura-batch<first>`; register the pane in `inbox_routing.conf` FIRST) → verdict mail → completion check → signed GO `GO: merge #<first>-#<last> batch` (every head; BASE_GO = develop; order = the gate's; all 12 tickets stay Backlog/In Progress; NO deploy; rule-7 bytes to Wednesday first) → verify at source → wrap → score + `pane_close.sh` in ONE action. Hand-over-holding at its ctx 80 if the GO is not in.
2. **Ornith: R15 batch COMPLETE 17/17 — 14 PASS (13 held `night/READY_*-R15_*` + KS-910 bash PASS UNHELD: `hold_ready.py` cannot read a bash_patch input, IMPROVEMENTS row, hand-written READY owed naming run `2026-09-21_ks910-ornith35b-night`), 3 FAIL = brief defects (IMPROVEMENTS rows; counter not consumed). Queue 0; `PAUSE_QUEUE` reasoned to ~23:23.** **FEED 2 DRAFTER RUNNING** (commission `briefs_staged/2026-09-21_r15_feed2.COMMISSION.md`): three rebriefs (KS-1123 F3b fold, KS-864 F1009b literal title, KS-1229 UNTYPEDSRCb re-anchor) + golden precheck of the 18 INFERRED rows + KS-1285 (Peter's schemathesis pin bump) → `…r15_feed2_queue_proposal.md` + `…r15_feed2.REPORT.md`. **Wake = its completion → Wednesday re-derives (build each accepted input into `night/inputs/` by its `# build:` line; key set vs the newest PASSING input; tamper From == tip line; expected_plus ASCII, 0 backslashes) → append the accepted lines to `night/queue.md` (backup first) → `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop` → a done.md waiter from a script file → source-read + `hold_ready.py` each PASS in one sitting.** The 13 held R15 READYs + KS-910 = the Seat B 16th raise pool (after the 15th merges; fold KS-1118 F2-R15+F3a+F3b, KS-1158 R3-R15+R5b, KS-1181 F3-R15+F3w per the 15th brief's DROPPED section; KS-1123 F2-R15 + F3b one file). FEED T (24 product-bytes rows, census15 report §5c) = Wednesday's tier call, unread.
3. **Live-board poller** pid 14963 (health `fleet/cockpit/state/live_chat_poll.health`): `pgrep -f cockpit/live_chat_poll.sh` + a fresh OK line at every boot.
4. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). `reconcile_rulings.py` at every checkpoint (22:0x: nothing to reconcile; Kam's last line 15:43).

### DONE THIS SEAT (verified at source)
Boot ctx 34 (brain whole) · rung 5 on the gate · rung 10 ×2 at the holding seat (detector first, acked, ledger +1) · `wake_watch.sh` idle leg carries the detector verdict (atomic swap; arms 4/4 + control; 5f3168044) · census15 drafter delivered (O 36 / R 17 / T 24 / D 11) · 17 R15 rows verified + queued, loop kicked, waiters · gate verdict read whole, 17 by-name check, heads 7/7, GO sent + tapped, pane closed, scored 1.00 · #1134 pair-blob ruling (ANSWER) · all six merged, verified at source · rule-7 bytes ruled · 14th wrapped, scored 1.00, pane closed · 7 R15 PASSes held, 1 FAIL classified · 15th brief re-pinned (drafter) + every count re-derived + read whole + board swept + LAUNCHED `%22` + plan CONFIRMED (nine rulings) · R15 batch 17/17 read: 13 held, 3 FAILs classified with IMPROVEMENTS rows, the header-pattern row · FEED 2 drafter commissioned · ~17 pushes HEAD == origin.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad; no `sleep N; cmd` chains (Monitor/run_in_background); a refusable tool's rc on its own line; NEVER `pgrep -fl` the wake_watch runner (it prints its whole body — 2 KB of tokens each time; use `pgrep -f … | head`). `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. Mail body whole = `inbox_digest.sh full <inbox> '<message-id>'` into a scratch file, then Read. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only). Taps by pane NAME with `--mail` (verifies at the destination first). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. Every count in a drafted brief re-derived or marked "drafter's count". The loop kick = `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. `hold_ready.py` bash_patch support (KS-910 READY by hand meanwhile) · checker header-rewrite candidate (11 of 14 `--recount`) · KS-1192 rebrief (replace `res.end('{\"recorder\":true}')` with a backslash-free literal) · golden precheck for the 18 INFERRED R15 rows · FEED T tier call · `wake_ack.sh` keys on the detector verdict class (rung-10 re-render re-fires the wake; ledger 09-21) · `04_deploy.sh` api-version refusal (04c is the interim) · doctor.sh: live-poll health + the dashboard venv item · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · SYSTEMTESTPUSHUNGATED + PLACEHOLDERPINSHAPE + STDERRTAILONABORT ticket candidates (the gate's) · doctor warns on an expired `PAUSE_QUEUE` · `derive_candidates.py` misses `Blockchain/Testing/` · Ledger 3c on 09-22 · Tuesday's line for Kam (the vault note overwrite).

### ROUTE TO KAM (last sent 20:14 boot receipt; add only what is NEW — one message when the six merges land)
NEW since: the six-PR batch gated GO ×6 and merging (send with the merge receipt). Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (now sorted: O 36 / R 17 / T 24 / D 11).
