---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 21:42 by the 20:1x Monday seat at its 66% CHECKPOINT (previous copy NEXT-PICKUP.md.pre-0921-2142; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 20:1x Monday seat, 66% checkpoint) — replace it, never append

**Kam:** LEAVES TONIGHT; last line on this tab 15:43 (live board); terminal lines 18:4x–18:5x (portable drive). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27 = Wednesday's reading; return day unanswered). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`). Usage 7d 38%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at the next checkpoint (rows conserved).**

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at the checkpoint: `%0` this seat · `%9` monitor · `%22` Seat B 15th, launched 21:41)
1. **#1130–#1135 ALL MERGED (verified at source: develop `581ed7fa124b85c7c2da89ac05d52f99c2502911`, tree `60bd96e7078c…`, 6 squashes); rule 7 posted (KS-485 b3749c4e…, KS-772 ce987c8c…); Seat B 14th wrapped, scored 1.00, pane closed.** Nothing deployed; kintsugi waits on Kam's card. Kam receipted on the live board (one composed count "45" withdrawn and corrected there; ledger +1).
2. **Seat B 15th (`%22`) — raising 14 doc/comment READYs as 10 tier-2 PRs / 11 files at 581ed7fa1** (brief `briefs_staged/2026-09-21_raise_seatB_successor15.md`, read whole + every count re-derived by Wednesday; verified at secuura-blockchain@ 11:41:14Z). **Rung 5 OWED on the first wake** (grep its pane for `Seat B 15th` / `581ed7fa1` / the brief's tickets). Wake = its plan-confirmation QUESTION `plan confirmation (Seat B 15th)` → ANSWER (Q2 10 PRs by file as tabled · Q3 order as tabled · Q4 KS-1045-A only if its `az vm show` read confirms `secuura02-kintsugi-vm` in `SECUURA-DEMO-RG`, else HOLD that hunk (PR 3 ships KS-1045-B alone) · Q5 quote the CLAUDE.md sentence and proceed · Q6 ASCII-fold `×`→`x5` · Q7 excise `ks-597s-`) → ten READY mails (heads re-read by Wednesday's own `ls-remote refs/pull/N/head` each) → a batch-gate DRAFTER around READY 8 (tier-2 floor; gateset dir under `fleet/qa-agent/gatesets/`) → prompt read WHOLE → `--check` → `repin_and_launch` → verdict → signed GO `GO: merge #<first>-#<last> batch` (every head; BASE_GO = develop; order = the gate's; all 12 tickets STAY Backlog/In Progress; NO deploy) → verify at source → rule-7 bytes first → wrap → score + `pane_close.sh` in ONE action. Hand-over-holding at its ctx 80 if the GO is not ready.
3. **Ornith R15 batch (17 queued 20:51): verdicts so far 8 read (7 PASS held as `night/READY_*-R15_*`, 1 FAIL = brief defect, IMPROVEMENTS row) + KS-1188 PASS UNHELD at 21:39 and possibly more (runner paused on the load gate; the 900 s loop resumes it; queue 6 at 21:41).** A 13-row waiter is armed (scratch `waiter_r15c.sh`). At each sitting: source-read titles vs the brief, `hold_ready.py <run> - <ROWID> <TITLE> --seat …`, classify every FAIL with an IMPROVEMENTS row. **After the batch: an IMPROVEMENTS row on the miscounted new-file hunk header (`--recount` on 5 of 8 so far — a model dialect; a header rewrite in the checker's canonical would remove the accommodation from every PR).** Then: the held R15 READYs are the NEXT raise pool (a Seat B 16th brief, drafted by a subagent after the 15th merges; KS-1118 F2-R15 + F3a/F3b + KS-1158 R3-R15 + R5b + KS-1181 F3-R15 + F3w fold per the DROPPED section). HELD OUT still: KS-1192 (backslash rebrief) + the 18 INFERRED rows (golden precheck) + FEED T's 24 product-bytes rows (Wednesday's tier call, report §5c). **NEW ticket KS-1285 (Peter, 10:23Z, schemathesis pin bump 4.27.2→4.27.5)** — read it and route (Ornith if one-file, else a Claude seat); not yet read.
4. **Live-board poller** pid 14963 (health `fleet/cockpit/state/live_chat_poll.health`): `pgrep -f cockpit/live_chat_poll.sh` + a fresh OK line at every boot.
5. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). `reconcile_rulings.py` at every checkpoint (21:4x: nothing to reconcile).

### DONE THIS SEAT (verified at source)
Boot ctx 34 (brain whole) · rung 5 on the gate · rung 10 ×2 at the holding seat (detector first, acked, ledger +1) · `wake_watch.sh` idle leg carries the detector verdict (atomic swap; arms 4/4 + control; 5f3168044) · census15 drafter delivered (O 36 / R 17 / T 24 / D 11) · 17 R15 rows verified + queued, loop kicked, waiters · gate verdict read whole, 17 by-name check, heads 7/7, GO sent + tapped, pane closed, scored 1.00 · #1134 pair-blob ruling (ANSWER) · all six merged, verified at source · rule-7 bytes ruled · 14th wrapped, scored 1.00, pane closed · 7 R15 PASSes held, 1 FAIL classified · 15th brief re-pinned (drafter) + every count re-derived + read whole + board swept + LAUNCHED `%22` · ~14 pushes HEAD == origin.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad; no `sleep N; cmd` chains (Monitor/run_in_background); a refusable tool's rc on its own line; NEVER `pgrep -fl` the wake_watch runner (it prints its whole body — 2 KB of tokens each time; use `pgrep -f … | head`). `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. Mail body whole = `inbox_digest.sh full <inbox> '<message-id>'` into a scratch file, then Read. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only). Taps by pane NAME with `--mail` (verifies at the destination first). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. Every count in a drafted brief re-derived or marked "drafter's count". The loop kick = `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. KS-1192 rebrief (replace `res.end('{\"recorder\":true}')` with a backslash-free literal) · golden precheck for the 18 INFERRED R15 rows · FEED T tier call · `wake_ack.sh` keys on the detector verdict class (rung-10 re-render re-fires the wake; ledger 09-21) · `04_deploy.sh` api-version refusal (04c is the interim) · doctor.sh: live-poll health + the dashboard venv item · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · SYSTEMTESTPUSHUNGATED + PLACEHOLDERPINSHAPE + STDERRTAILONABORT ticket candidates (the gate's) · doctor warns on an expired `PAUSE_QUEUE` · `derive_candidates.py` misses `Blockchain/Testing/` · Ledger 3c on 09-22 · Tuesday's line for Kam (the vault note overwrite).

### ROUTE TO KAM (last sent 20:14 boot receipt; add only what is NEW — one message when the six merges land)
NEW since: the six-PR batch gated GO ×6 and merging (send with the merge receipt). Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (now sorted: O 36 / R 17 / T 24 / D 11).
