---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 23:41 by the 20:1x Monday seat at its ROTATION HANDOVER (ctx ~78, band 80-90; previous copy NEXT-PICKUP.md.pre-0921-2341; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 20:1x Monday seat, rotation handover) — replace it, never append

**Kam:** LEAVES TONIGHT; last line on this tab 15:43 (live board); terminal lines 18:4x–18:5x (portable drive). `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27 = Wednesday's reading; return day unanswered). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`). Usage 7d 38%, gate open. Quiet hours 23:00–06:00 (no voice). **Ledger 3c: the 09-18 rows pass the 3-day line on 09-22 — move them at the next checkpoint (rows conserved).**

### 🔴 IN FLIGHT (floor from `tmux list-panes -t fleet:0` at the handover: `%0` this seat · `%9` monitor · `%22` Seat B 15th HOLDING since 13:38Z)
1. **Seat B 15th (`%22`) HOLDING — TEN PRs READY on develop 581ed7fa1: #1136 6f5c31c45 · #1137 08f931532 · #1139 9b2cf251c · #1140 21c87abe3 · #1141 e4ae24b7f · #1142 51d47ea44 · #1143 7cb87fedb · #1144 5c1f70149 · #1145 6cba33e52 · #1146 abb48650b (every head re-read at origin by Wednesday; #1138 is Peter's KS-1285 and MERGED — origin develop = `b192ffd4a61d1b01bb9485a0f5260ca9fd69cf05` at 13:37Z, the object NOT in the shared store).** Its handover + records are on disk (`5_Project_History/2026-09-21_seatB-15th/`); hold mail sent 13:4xZ with the channel discriminator. **The GO subject it expects, verbatim: `GO: merge #1136, #1137, #1139, #1140, #1141, #1142, #1143, #1144, #1145, #1146 batch`.**
   **NEXT (the successor's first act): LAUNCH THE BATCH GATE — the drafter DELIVERED (23:4x).** Prompt `fleet/qa-agent/briefs/2026-09-21_secuura-batch1136-1146.prompt.txt` (852 lines / 115,117 B, sha256 273a5437…); launcher `fleet/qa-agent/launchers/launch_qa_secuura_batch1136-1146.sh` (485 lines, **`--check` rc 0 ×2 by the drafter** at 13:39Z and 13:42Z — re-run it by OWN hand); gateset `fleet/qa-agent/gatesets/2026-09-21_gate15_docs_comments/` (README = the launch recipe; DRAFTER_REPORT §4 = its five slips — READ §4: its S1 says a by-SHA fetch of the moved develop was refused on the https road and "the checkout's own ssh road fetched it rc 0" — confirm from the report WHERE that fetch ran (the scratch clone is fine; a fetch INTO the shared checkout is a hard-rule-1 write to record); all ten READYs + both STATUS mails + the QUESTION/ANSWER captured by id; `repin_and_launch_gate15.sh <launcher>`; a `_partial` prompt/launcher pair beside it is a RECORD, its `--check` rc 34 by design — do not launch it). **Develop MOVED 12:44:19Z: #1138 (Peter's KS-1285) merged as a MERGE commit — 3 commits, 7 files under `systemTest/` + `Projects Documents/`, ∩ the 11 paths = ∅ (drafter-measured); the prompt/launcher pin the CURRENT develop `b192ffd4a…`, compare per PR = merge_base 581ed7fa1 / ahead 1 / behind 3; the addendum's merged trees are the 3-way trees over b192ffd4a, END STATE `87b4aa12d2eb…` (re-derived in four orders).** Steps: (1) READ the prompt WHOLE (thirteen by-name items; tier-2 floor); (2) re-derive: ten heads by own `ls-remote refs/pull/N/head`, develop by own `ls-remote`, the DRAFTER_REPORT's counts by their commands; (3) `bash <launcher> --check` rc 0 by own hand; (4) ADD `QA/Secuura-batch1136|coagent@agentmail.to|yes` to `fleet/inbox_routing.conf` FIRST (backup `.pre-<HHMM>-gate1136` beside — the README names the exact line); (5) `usage_gate.sh --check`; (6) `repin_and_launch_gate15.sh <launcher>` (or `cockpit.sh add QA/Secuura-batch1136 <launcher>`) → pane id from `tmux list-panes`; rung 5 on the next wake (the pane may be on its alternate screen at launch). Wake = the verdict mail `[QA -> Wednesday] BATCH GATE #1136…` (~45–90 min) → completion check vs the thirteen items → signed GO with the subject EXACTLY `GO: merge #1136, #1137, #1139, #1140, #1141, #1142, #1143, #1144, #1145, #1146 batch` (every head; BASE_GO = b192ffd4a…; order = the gate's; all 12 tickets STAY Backlog/In Progress; NO deploy; rule-7 bytes to Wednesday first) → `send_brief --kind answer` → `cockpit.sh say Secuura/Blockchain-B '<pointer>' --mail 'GO: merge #1136'` → gate pane closed via `pane_close.sh` + scored → the seat's STATUS "merged" → verify at source (`ls-remote` develop; `rev-parse ^{tree}` == the END STATE tree the gate names; `rev-list --count b192ffd4a..<new>` = 10) → rule-7 bytes → its wrap → **score + `pane_close.sh %22` in ONE action**. If the seat dies at ctx 100 before the GO: retire by hand, brief a Seat B 16th to merge on the SAME GO.
2. **Ornith FEED 2 RUNNING (18 rows queued 22:53; runner on the loop; first verdict KS-1156 PASS 22:59, UNHELD).** A 35-row waiter is armed in this seat's scratchpad (dies with the seat — re-arm: a script-file loop on `night/done.md` counting `-R15.json.*done 2026-09-2[12]` rows ≥ 35, or read `ornith_status.py` at every wake). **Sitting: source-read titles vs the brief, `hold_ready.py <run> - <ROWID> <TITLE> --seat …` each PASS (a KS-1123 F3b PASS SUPERSEDES the held `READY_KS-1123-F2-R15_*` — say so in its READY; KS-910's bash PASS still needs a HAND-WRITTEN READY naming run `2026-09-21_ks910-ornith35b-night`), classify every FAIL (model/harness/brief) with an IMPROVEMENTS row.** Held out: two KS-1120 rows (backslash in expected_plus — rebrief) + KS-1192 (same) + the drafter's 1 HOLD (a duplicate). After FEED 2: the R15 READYs (13 held + FEED 2's) = the Seat B 16th raise pool (after the 15th merges; folds per the 15th brief's DROPPED section). FEED T (24 product-bytes rows, census15 report §5c) = Wednesday's tier call, unread.
3. **Live-board poller** pid 14963 (health `fleet/cockpit/state/live_chat_poll.health`): `pgrep -f cockpit/live_chat_poll.sh` + a fresh OK line at every boot.
4. **Cards on Kam's queue:** `secuura-ks1175-kintsugi-deploy-and-first-anchor` (default c) · `secuura-ks721-commitment-cannot-reach-a-real-chain` (default a). `reconcile_rulings.py` at every checkpoint (last: nothing to reconcile; Kam's last line 15:43 — he is travelling; the MORNING RECEIPT on the live board is the successor's: merged today (#1130–#1135 verified; the 15th's ten pending the gate), Ornith's output (R15 17/17: 14 PASS, 3 brief-defect FAILs; FEED 2 in flight), blockers + cards, skipped items).

### DONE THIS SEAT (verified at source)
Boot ctx 34 (brain whole) · rung 5 on the gate · rung 10 ×2 at the holding seat (detector first, acked, ledger +1) · `wake_watch.sh` idle leg carries the detector verdict (atomic swap; arms 4/4 + control; 5f3168044) · census15 drafter delivered (O 36 / R 17 / T 24 / D 11) · 17 R15 rows verified + queued, loop kicked, waiters · gate verdict read whole, 17 by-name check, heads 7/7, GO sent + tapped, pane closed, scored 1.00 · #1134 pair-blob ruling (ANSWER) · all six merged, verified at source · rule-7 bytes ruled · 14th wrapped, scored 1.00, pane closed · 7 R15 PASSes held, 1 FAIL classified · 15th brief re-pinned (drafter) + every count re-derived + read whole + board swept + LAUNCHED `%22` + plan CONFIRMED (nine rulings) · R15 batch 17/17 read: 13 held, 3 FAILs classified with IMPROVEMENTS rows, the header-pattern row · FEED 2 drafter delivered → 18 rows verified + queued, loop kicked · all TEN 15th READYs verified at origin, hold mail sent · gate drafter commissioned · ~24 pushes HEAD == origin.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH: a `cd` in a call is REFUSED by the hook (absolute paths); `rm -rf $VAR` refused even in the scratchpad; no `sleep N; cmd` chains (Monitor/run_in_background); a refusable tool's rc on its own line; NEVER `pgrep -fl` the wake_watch runner (it prints its whole body — 2 KB of tokens each time; use `pgrep -f … | head`). `git add <dir>` on `night/` sweeps `(conflict_on_…)` copies — add by file. Mail body whole = `inbox_digest.sh full <inbox> '<message-id>'` into a scratch file, then Read. `send_brief.sh --subject-file` PREPENDS the routing prefix (`.subject` = the TOPIC only). Taps by pane NAME with `--mail` (verifies at the destination first). A gate pane on its alternate screen captures EMPTY at launch — rung 5 on the next wake. Every count in a drafted brief re-derived or marked "drafter's count". The loop kick = `launchctl kickstart gui/$(id -u)/com.wednesday.ornith-loop`.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. `hold_ready.py` bash_patch support (KS-910 READY by hand meanwhile) · checker header-rewrite candidate (11 of 14 `--recount`) · KS-1192 rebrief (replace `res.end('{\"recorder\":true}')` with a backslash-free literal) · golden precheck for the 18 INFERRED R15 rows · FEED T tier call · `wake_ack.sh` keys on the detector verdict class (rung-10 re-render re-fires the wake; ledger 09-21) · `04_deploy.sh` api-version refusal (04c is the interim) · doctor.sh: live-poll health + the dashboard venv item · wire the poller into `arm_wake_watch.sh` (shared) · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows: Easy Auth secret 2027-03-21, seat certs 2027-09-21 · the four §5f escalations KS-577/946/1172/1173 re-carded WITH DEFAULTS · dependabot 10 open (board-seat) · `board_count.sh linear` label filter (dead) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · SYSTEMTESTPUSHUNGATED + PLACEHOLDERPINSHAPE + STDERRTAILONABORT ticket candidates (the gate's) · doctor warns on an expired `PAUSE_QUEUE` · `derive_candidates.py` misses `Blockchain/Testing/` · Ledger 3c on 09-22 · Tuesday's line for Kam (the vault note overwrite).

### ROUTE TO KAM (last sent 20:14 boot receipt; add only what is NEW — one message when the six merges land)
NEW since: the six-PR batch gated GO ×6 and merging (send with the merge receipt). Carried, NOT re-sent: the two cards; platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs (now sorted: O 36 / R 17 / T 24 / D 11).
