---
date: 2026-09-21
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 01:18 2026-09-21 by the 23:4x seat at ctx 76% ahead of its rotation (previous copy NEXT-PICKUP.md.pre-0921-0120; older blocks in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 23:4x Sun→Mon seat, written at ctx 76% for its successor) — replace it, never append

**Kam:** last words 2026-09-20 21:5x (new account; "keep going with secuura tickets using both claude and local agents"), then "see you soon". **0 panel lines on 2026-09-21 as of 01:18.** He is expected back today and leaves MONDAY NIGHT — expect a new week-instruction; `WEEK-INSTRUCTION.md` is `status: lapsed`. Usage 7d ~8%, gate open. Quiet hours until 06:00 (no voice). Ledger 3c done for 09-17 at 00:50 (37 rows, 1146=1146); 09-18 rows pass the line on 09-22.

### 🔴 IN FLIGHT — UPDATED at the rotation: Seat A 15th WRAPPED, scored 0.92, pane %7 CLOSED 01:2x (rule 7 posted: KS-485 631a9559, KS-772 dbb2acd4). Item 1 below is DONE except the Ornith feed. Floor at the rotation: `%0` · `%9` · `%11` Seat B 11th. (floor from `tmux list-panes` at 01:18): `%0` this seat · `%9` fleet-monitor · `%7` Seat A 15th MERGING · `%11` Seat B 11th RAISING (gate #1105's pane %10 CLOSED at 01:2x after its verdict; report.md on disk)
1. **Seat A 15th (`%7`) — #1105 MERGED 15:20:39Z: develop `cbae988dbe90ebe556459ada2cb437eaf80e2402` tree `1f2bc512a` (verified at source by Wednesday); rule-7 bytes RULED 01:2x (post + read back); wake = its WRAP → score → `pane_close.sh %7`.** (History: GO sent 15:15:53Z for #1105 at `e02d3ecb51a457b0eb490db1854f28c6b1af69ad` onto develop `778e6cfe2b6061d60ffcf3a57a951c84dc152b67` (merged tree predicted `1f2bc512aee2a55d74142d9ba8206a795b0c975c`), after THREE text-only pre-merge fixes** (PR body `:155`→`:182` + the buildVerifyResponse shape sentence; a KS-1175 correction comment; a KS-1284 facts comment with Wednesday-ruled bytes) and 12 equality targets per FILE from the gate's addendum verbatim. **Wake = its STATUS "merged"** → verify at source (`ls-remote` develop; `rev-parse ^{tree}` = 1f2bc512a; the squash's parent = 778e6cfe2 unless Seat B 11th's PRs landed first, which they must not before their gate) → its rule-7 bytes come to Wednesday first (a TEST BLOCK, facts only; posted only after Wednesday's ruling) → its wrap → score → `pane_close.sh %7`. **The deploy/anchor step for KS-1175 is KAM's** (card `secuura-ks721-commitment-cannot-reach-a-real-chain`); booleans ruled STRINGS (one line on his Monday list). The #1105 gate's SEVEN NOT-PINNED rows (T13-ATTACHPOINT, T12-CHAINREAD-DECODE, T11-GETID-VIEW, VIEW-NONSTRING-ARRAY, CHUNKED-DOCUMENTID-ROUNDTRIP, EXPLORERBASE-PER-NETWORK, IDENTITY-EMPTY-OBJECT; full rows in its report.md) are the LOCAL MODEL's next feed once #1105 merges (anchoring vitest; cells in the three new test files). Verdict mail saved: fetch by id `<010001a0bf61404f-…>` or read the report.
2. **Seat B 11th (`%11`) — plan CONFIRMED D1–D17 (ANSWER 15:03:15Z; PR 3 ruled TIER 1; F1 was Wednesday's count; S3 record only).** Raising SIX PRs in order KS-1232 → KS-753 → KS-1234 → KS-1279 → KS-880 → KS-1223 (LAST), each to its own READY. Its worktrees `s-b11-*` exist (+6 refs seen by the gate at 01:06). **Wake = six READY mails** → ONE batch gate (file-disjoint, four lanes, tier-1 floor; draft from the `2026-09-20_gate1102to1104` gateset shape via a gate drafter; re-pin at launch; if #1105 merged first, the gate grades on the then-current develop — the six touch none of anchoring) → completion check → signed GO (targets 1/1/2/2/1/1 per FILE, comma-separated on the two-file lines — MG-2) → merges one at a time → score → close. All six tickets STAY Backlog. Brief: `fleet/briefs_staged/2026-09-21_raise_seatB_successor11.md`; its plan mail + ANSWER at `…_seatB11_answer_plan.md`.
3. **Ornith:** TEN PASSes tonight, all held. Six with Seat B 11th; **FOUR banked for the NEXT raise seat (Seat B 12th, after the 11th wraps): `READY_KS-1203-NESTEDTYPE-1_*` + `READY_KS-1203-WSTRIM-1_*` (same file, NESTEDTYPE first, one PR), `READY_KS-1283-PROVADMIN-1_*`, `READY_KS-1244-JOINEDKEY-1_*` (auth → tier 1, last).** Queue EMPTY with the reason in `PAUSE_QUEUE`; **a KS-1198 brief drafter (subagent) was IN FLIGHT at the rotation — its notification dies with this seat, its FILES land: look for `night/briefs/KS-1198*.md` + `night/inputs/test_only_1198*.json` (or `KS-1198-NOTBRIEFED.md` / a KS-1280 brief). If present: byte-check each tamper From line at the tip (count 1 + a control), key-set diff vs `test_only_1244JOINEDKEY-1.json`, + lines ASCII/no backslash, both-orders vs KS-1244's hunk on the same file, append the queue line, kick `com.wednesday.ornith-loop`, arm a waiter whose condition is ONE `grep -q` on the INPUT PATH + today's date. If absent after ~25 min, re-commission from `night/candidates_rounds.md` round 22's next-best list.** Then the #1105 NOT-PINNED rows (item 1).
Tip at the merge: develop `cbae988db` tree `1f2bc512a` (#1105 on top of 778e6cfe2). Earlier tip at 01:18: develop `778e6cfe2b6061d60ffcf3a57a951c84dc152b67` tree `d0c8bfd095b65861efc1a4e8524017235b42e382`. `inbox_routing.conf` carries -B and QA/Secuura-1105.

### STANDING RULES LEARNED TONIGHT (carry, do not re-learn)
A loop's exit condition is ONE `grep -q`, never a pipeline (cut's rc 0 broke a waiter). A heredoc is `<<'EOF'` — stamps by sed after (one unescaped backtick executed). Every COUNT in a drafted brief is re-derived by Wednesday's own command or marked "drafter's count, unverified" — no sample (w=3 tonight). Rung 10 (`[Wednesday tap] GO mailed …` ghost) rendered at BOTH raise seats; detector first on every idle wake; mail names the exact GO subject as the seat's discriminator. A `done.md` waiter keys on the INPUT PATH + date, never the ticket id. `PAUSE_QUEUE` line 1 is a 10-digit epoch (doctor now warns on expiry; arms 6/6). The checker's clone is DIRTY after a run (resets at START) — drafters use a fresh clone per measurement.

### OWED (mine, none blocking)
`reconcile_rulings.py` `note:` form (w=2) · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · `note_entry.sh` typed-clock warn · `derive_candidates.py` drops HELD/REALLOCATED rows · CHK-1 (correct the KS-1272 checker record) · `wake_watch` idle leg runs the detector itself (rung-10 candidate) · a script that re-counts every integer in a drafted brief (the w=3 candidate) · KS-1201: `run-shell-suites.sh` leaves 4 login_stub listeners per run (the #1105 gate's evidence; standing item, a ticket candidate for a board seat).

### ROUTE TO KAM (Monday 21)
0. **Booleans on the Cardano record as STRINGS "true"/"false"** (Wednesday's shape ruling; ints 0/1 the alternative) — his to flip before any anchor. **The deploy + first anchor for KS-1175/#1105 is his step.**
1. Whether his 2026-09-14 07:22 suspension of Wednesday→Tuesday messaging still stands (Tuesday is live on the mini).
2. `Secuura/platform-s#877` unreadable — a permissions boundary, reported not worked around.
3. Four escalations on absent §5f runtime evidence: KS-577, KS-946, KS-1172, KS-1173.
4. `secuura-dependabot-triage` says "close the 5"; 10 open dependabot PRs now.
5. Carried: Peter's two KS-1195 questions; his KS-593 addition; kintsugi has no connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies (17 mechanism scripts); seat A's launcher F-02; O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24; **O-1: `admin.ts` `requireAdmin` routes do no session check**; the KS-1283 coverage ticket (one cell now held); M-7 (anchoring.openapi.ts:253 restated regex — Polish, a ticket candidate).
6. Wednesday's reading to confirm: auth surfaces open to TEST-ONLY local-model work under "auth product EDITS stay out" (KS-1223, KS-880, KS-1283, KS-1244 all pinned tonight on that reading).
