---
date: 2026-09-23
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block — written at the 05:30 OVERNIGHT WRAP by the 18:3x seat of 2026-09-22 (ctx 65; the previous copy is the `.pre-0923-*` file beside this one, read it by `ls`)

**Kam:** on the LIVE board; last rows 2026-09-22 20:53:05–20:53:49 (four cards ruled in 44 s, all on the defaults — receipted within the minute). Nothing since; nothing owed to him at this boot. **His 15:16 reading is still in force: at ~75%+ weekly usage MORE work to Ornith and NO new Claude build/raise lane** — usage read 85% at the wrap (gauge fresh), so **do not launch a raise seat on this file's authority**: re-read the gauge, and if it has renewed or he says so, the raise lane is the first Claude launch. The file drawer still awaits his first click. Floor at the wrap: `%0` + `%9` monitor only — **no Claude seat live**; Ornith idle with an empty queue; stash list 24 (never drop).

### 🔴 FIRST ACT — HOLD THE FOUR FEED-17 PASSES (deferred here deliberately: the shift change said start nothing new; a hold needs a source read per diff)
All four PASSed round 1 on 2026-09-22 and are UNHELD. For each: read the run's `out.md.checker/patch.diff` against its brief (the product hunk IS the ruling — quote it), then hold:
- **KS-1084 part C** `PASS 7/7` 20:10 — run `2_Project_Files/local-model/runs/2026-09-22_ks1084-ornith35b-night3`, brief `night/briefs/KS-1084-R17-TPVTENANT.md`, golden `runs/2026-09-22_feed17-drafter-precheck/TPVTENANT` (third-party-verifiers `proxy.ts` `@@ -697,7` — region-disjoint from part A's `:674-:680`; **the HELD/GATED clause is Kam's `c` and must stay verbatim in the READY**).
- **KS-1033** `PASS 7/7` 20:12 — run `…_ks1033-ornith35b-night2`, brief `KS-1033-R17-MISSINGBASE.md`, golden `…feed17-drafter-precheck/MISSINGBASE` (the fail-open base; a gate-named design change → HELD/GATED).
- **KS-1139** `PASS 8/8` 20:13 — run `…_ks1139-ornith35b-night2`, brief `KS-1139-R17-ERREXITBEHAVIOUR.md` (test_only; the raiser bumps runtime `TOTAL_CELLS`).
- **KS-1081** `PASS 8/8` 20:15 — run `…_ks1081-ornith35b-night2`, brief `KS-1081-R17-NEITHERTEMPLATE.md` (test_only).
Command shape: `python3 2_Project_Files/local-model/night/hold_ready.py <run-dir> <golden-dir> <ROWID> --title-from-brief <brief.md>` (read its usage first). **Known tool gaps:** it has NO `comment_patch` branch (assemble by hand from the run's artefacts in the 2026-09-20 `READY_KS-1277-N60-1` shape — that is how KS-1019 was held), and its golden compare trips on the `@@` function-context suffix (diff the `+`/`-` lines yourself; KS-1084 part A was byte-identical by that test). Then the queue is empty → FEED 18.

### THE STATE, MEASURED AT THE WRAP
1. **Round 19 is CLOSED OUT.** develop `2bc5ccf63b8c40911afb568b03cace066238ffcf`, tree `b4f2a8beaecdf758d46c719a0f3becc677e421cf` (21 PRs: #1182–#1201 then #1180–#1197; verified from the commit objects). Seats scored + closed: A 16th 0.97 · B 20th 0.98 · C 20th 1.00; gates 19B/19C closed. Kintsugi runs `3bad652d1` with the first KS-1175 anchor confirmed (`anchor_1526505a-…`, tx `0180573229…76fb`, block 4685580). The Secuura checkout's local develop is `3bad652d1` (21 behind origin) — LEAVE IT; its launcher now runs `ls-remote` only (Kam's `c`).
2. **RULED BY KAM, NOT YET IN AN ARTEFACT** (goes in the next Secuura brief's own section, each with its execution):
   - `secuura-ks998-…-prettier` → **a PLUS his note "and install it also"** = hard-fail when a tracked file of the package is in the push **and** install prettier on first run; with the ticket's small items 3–4. **A Claude seat on the hooks lane** (the hook sits outside `Blockchain/Dev`). ⚠ The note is NOT machine-readable — the reconciler flags `note:` and never applies it; carry his words by hand.
   - `secuura-ks1163-…` → **a** wait for all five services (`Start_Up/start-secuura.sh` EXPECTED_SUFFIXES + the count comment + the ks1096 suite's five KNOWN_UNWAITED lines) — **an Ornith bash_patch at FEED 18**.
   - `secuura-ks974-…` → **a** leave both routes as designed; **correct the record on KS-974** (the gate's Minor premise is refuted at the tip: `requestSchemas.ts:82` bounds by code points only on both; the refine lives in `scopeField()` `:65`; `:52-:53` records the design) — one facts comment by the next Secuura seat.
   - `secuura-ks1084-part-b-…` → **a** a Secuura seat files "api-gateway `/api/batch` is unauthenticated-and-therefore-dead"; part B tabled on KS-1084.
   - **Older, undelivered: `decision_queue.sh list ruled --undelivered` returned 75 at this seat's boot and was read as a NUMBER, not a list.** Read it as a LIST this boot — the KS-998 re-ask came out of exactly that (ledger 2026-09-22).
3. **Ornith:** queue EMPTY, runner idle (23:47 and 05:19 fired, found nothing). Held READYs: 31 R16B-class (FEED 16's three + the standing pool) — **not raised**, per the usage reading above. FEED 18 candidates named by the FEED 17 drafter: the gate19C test_only tweaks EXIT3APPLIEDNOTASSERTED · MARKERWARN-RECREATE-BYTES · KS1046COUNTBRITTLE, plus KS-1163 (Kam's `a`). **TABLED with measurements** (do not re-derive): KS-1164 (the code_patch builder REFUSES a ticket In Progress with a merged PR — brief written, no golden; the tooling decision is whether that gate reads live SEATS or needs an explicit ALLOW with a reason) · KS-629 (needs an `export` or `.strict()` — a product edit) · KS-1084 part D (`verification.ts` — 7 edit points, a two-part follow-up) · `platform.ts:252` (not applicable).
4. **Proposals to read, not to redo:** `fleet/briefs_staged/2026-09-22_ornith_feed16_queue_proposal.md` (7 slips) and `…feed17_queue_proposal.md` (10 slips — its §0 carries the harness rules that bind the next drafter).

### STANDING RULES LEARNED (carry, do not re-learn)
`safe_push.sh "<message>" <paths…>` — the FIRST arg is the MESSAGE; **rc 24 = the autostash conflicted on the dashboard-data churn: commit those eight JSONs through safe_push first, never drop the stash**; a path LIST from a command substitution needs `${=VAR}` (zsh does not word-split). The Bash tool is ZSH; `cd` REFUSED; `rm` outside a literal scratchpad path REFUSED; `git -C <other tree> <write verb>` REFUSED **and the hook cannot see through a `$VAR` path — a scratch-clone write verb needs the LITERAL path**; `refs/pull/*/head` are not in the checkout (predict by head SHA — the objects ARE in the shared store). `cockpit.sh say` by pane NAME (the `%id` form refuses silently rc 1). `note_entry.sh --h3 --stdin <<'EOF'`, and **after midnight it writes to TODAY's note — a session that crosses the date writes its retro into the note of the day it started, by hand, with a generated stamp**. `pgrep -fl` prints a runner's whole body (~3K tokens) — pid-only forms. Read every fleet tool's usage line before its first call in a seat. **Before `decision_queue.sh add`: `list ruled | grep -i <ticket-id>` in the same action** — the override flag is not a substitute for looking. A receipt to Kam = ONE message per event on the LIVE board, first person, BLUF first. The extension is not connected (no browser checks — say NOT TESTED).

### OWED (mine, none blocking)
0. 🔴 **DATED — TODAY, Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg (09-22 night) AND Wednesday's 03:30 leg (09-23) have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; preconditions: `scheduler/state/nas_sync_last_wednesday.txt` shows a 09-23 run + Tuesday's leg reported; then tell Kam the total + rc on the panel.**
1. Tooling: `hold_ready.py` — a `comment_patch` branch + a golden compare that ignores the `@@` function-context suffix · `pane_close.sh` prints the listener DIFF (pid, cmd, port), not just counts · `night_run.sh` taps the coordinator on `END rc=0` after a run that attempted ≥1 ticket (the nine-hour gap, ledger 09-22) and refuses an identical-sha re-run · `cockpit.sh say` prints WHY it refuses · `send_brief.sh --kind brief` refuses a foreign `ks-\d+` in a `feature/…` name · `decision_queue.sh add` refuses an `_override_prior` that names no prior card id · `absence_claim_check.sh` is advisory-only by design (done: `only`/`nothing else`/`no other`) · doctor: expired `PAUSE_QUEUE`, live-poll health · the 09-06 lesson gains `git clone --shared`'s measured scope (regenerate BOTH digests after).
2. Records: EXPIRING-GRANTS-class rows (Easy Auth secret 2027-03-21; seat certs 2027-09-21; audit-baseline 09-30 / 10-02) · dependabot 19 open · the 12 FEED-5 card-shaped rows · the two `confirmed,simulated=true` anchor rows on kintsugi · a Datasec-content row sits in this seat's local chat store with `view` None (subject-level only; the store's per-seat split is a consolidation question).

### ROUTE TO KAM
Nothing pending. Carried, NOT re-sent: platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi's connector allow-list; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the master template + 14 other launchers still `git fetch` in their single-session step (other projects' files — outside his launcher ruling's scope).
