---
date: 2026-09-16
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's and Kam STOPPED the Tuesday seat 2026-09-14 07:20 ("until further notice"); nothing to Tuesday. Read Datasec mail by SUBJECT only.
source: replaced WHOLESALE at 00:11 on 2026-09-16 by the seat booted 23:2x on 09-15 (the 22:1x seat's successor), at its rotation. Previous copy beside this file: .pre-0015-wholesale.
status: live
supersede: replace this file wholesale at the next pickup; do not append
---

# NEXT PICKUP — ⚡ **Kam's standing words (all receipted; nothing new since 09-15 21:05): 18:19 NEVER IDLE — "extend the checker… action all backlog and to do from easy to hard. you act as a gate keeper" · 16:36 q4 ONLY, held diffs only, QA Sunday night + merge all at once (expires end of Sunday 09-20) · 19:44 KS-1172 deferred to Sunday, Stuart told on the ticket · 21:05 "Keep working with the local model, looks like promising progress especially when guided by you" · 18:23 he leaves MONDAY NIGHT 09-21 — the unattended loop must be BUILT and PILOTED by Monday morning. Speak in the FIRST person on the panel.** A seat may END ITS TURN only with the model RUNNING or a batch QUEUED.

## 🔴 STATE at 00:11 — read this first
- **Floor:** `%0` Wednesday · `%29` monitor ONLY (+ a scratch `rtest` tmux session — harmless). Usage gate CLOSED (7d 97%, renews Sat ~11:xx AEST): no Claude seat, gate or drafter; Ornith (q4) is the only worker. Origin contains HEAD at the last push (commit the launcher-regenerated digests at boot, then push — see TRAPS). Kam's last line 09-15 21:05; the 06:45 `com.wednesday.ornith-receipt` job posts his morning line from the records.
- **RUNNING / QUEUED: NOTHING — the model is IDLE at this rotation boundary and that is stated, not hidden.** Every ticket this window could read is held (4 pins), carded (KS-953) or set aside below; the next briefs need a FRESH read. **YOUR FIRST ACT: a brief.** Reads in this order, each at the tip first: (1) **`night/candidates.md` T1 hint rows NOT yet read by anyone** — the 23:2x seat read (and set aside, reasons below) KS-986/960/955/837/784/748/1031/678/1049/579/581/627/808/851/915/1145/1162/967/709; **unread: KS-839 (auth — LAST), KS-1121/629/975 (carded), KS-692 (auth surface — LAST)** — so T1's hints are effectively spent; (2) **re-derive**: `python3 night/derive_candidates.py` at the tip after the day's board moves, then read the NEW rows; (3) the T4 docs hints the 23:2x seat did NOT open: ~~KS-866~~ (READ 00:1x and SET ASIDE: its acceptance is a docs paragraph describing the 09-06 `merge --no-ff` + push-by-ref shape — but the flow moved on 09-11 to squash + author-merges + Wednesday's GO, and the merge seats since use a gated squash script; a paragraph must name the CURRENT mechanism and whether the base-race guard survives the squash shape (`PUT … sha=` still pins the head only) — establish authority before reconciling → a Claude seat with the merge script in hand, not Ornith), **KS-1051** (develop RED on originate jest; a CI/process item — probably a Claude seat), **KS-770/709/967/1089/1162** (board/tooling — likely not docs); (4) the T5 split vein needs Claude seats (see set-asides). **KS-1102 is CARDED** (`secuura-ks1102-public-status-what-may-show`, rec b) and **KS-953 is CARDED** (`secuura-ks953-shared-pins-anchor-by-marker`, rec option 1, default = brief it to a Claude seat after Sunday) — do not brief either before his word or the default date.
- **Held (READY_*): 61 files = 59 DISTINCT PINS across 38 ticket ids (39 with KS-1173)** — counted from the filenames' ticket/pin tokens (`sed -E 's/^READY_(KS-[0-9]+)(-[A-Za-z0-9]+)?_.*/\1\2/' | sort -u`; KS-1120-F2 and KS-1171-8j carry a q4 AND a q8 copy — count pins, never files). The 23:2x seat added 4 pins / 3 tickets: **KS-1133 A + B** (Kam-ruled 09-13; A on the r3 RETRY after A3d fired twice; B first sample), **KS-1035 D** (docs; a harness false FAIL retracted; placement rebuilt at the anchor), **KS-1049 A** (docs; a FALSE GREEN retracted → D8/D9 built; the model's lines re-placed by Wednesday at the brief's anchor — stated in the READY). **The raising seat's brief is STAGED (not sent): `2_Project_Files/fleet/briefs_staged/secuura_raise_ornith_ready_diffs.md` — bundles 1–35 current (33–35 added 00:11); QUEUE says ITEMS 1–35;** re-derive the ⟲ facts at send time.
- **HARNESS THIS SEAT (every one red-proofed from REAL artefacts before install; backups `.pre-0915-*` / `.pre-0916-*` beside each; IMPROVEMENTS rows 94–100):** (1) `code_patch/checker.sh`: A3c/A3d run for EVERY brief with expected `+` lines (A3c had sat inside the must_change branch — insert-only briefs were never measured); (2) `a3c_plus.py` **A3d** — a product `+` line (≥ 8 chars) NOT in the brief that already exists at the tip = a CONTEXT LINE MARKED `+` → refused by name (exit 2) before any test; and `\uXXXX` escapes the model echoes from the JSON input are DECODED before comparing; (3) `night_run.sh` RETRY-ONCE fires on `stopped at A3d` and the feedback carries attempt-1's ACCEPTED TEST SECTION verbatim (`accepted_test_section`) — the retry no longer stubs a test that was already right; (4) `code_patch/reanchor.py`: an insert-only hunk keeps the BLANK context lines between the `+` block and its anchor (row 98); (5) `doc_patch/checker.sh` `section()` accepts `### ` sub-headings (row 97); (6) `doc_patch/build_doc_input.sh` + `checker.sh` **D8** (every brief `+` line in AFTER exactly) and **D9** (the first `+` line follows the "Insert AFTER line N" anchor) — arms `tests/a3d_arms.sh` 5/5 · `tests/reanchor_gap_arms.sh` · `tests/doc_d8d9_arms.sh` 3/3.
- **BRIEF RULES learned tonight (put them in every brief):** a 🔴 cell on an undeclared field reaches it with optional chaining (row 87); a split brief's COPY LIST is re-read against ITS OWN cells (row 88); **DOC briefs: NO inline code in a `+` line the model must reproduce** (it drops backticks or pads them — write the path bare; D4's token still matches); **a list-end insert names BOTH neighbours** ("the new bullet is the LAST item: it follows :N and the next line after it is the blank :N+1") — the model placed KS-1049's bullet BELOW the following paragraph three rounds running; D9 now measures it, and if it recurs the builder should FEED the anchor as the hunk's first context line (`must_follow`, candidate). The KS-1133 dialect: on `originate.openapi.ts` the model marks the brief's fenced CONTEXT lines `+` on the first sample every time — A3d + the retry handle it; expect one retry per ticket on that file.
- **DOC BRIEF RULES (unchanged from the 21:0x seat):** an edit inside a hard-wrapped run is a WHOLE-RUN `-`/`+` replacement, every physical line named; the hunk's context is PINNED away from dense-markup lines; a bullet line begins `- ` so its diff lines read `-- …`/`+- …`; a `## Required` token must not contain a comma; sections are `## ` (or `### `, or the `# ` title) to the next heading of the same or higher level, measured on the TIP file.
- **SET ASIDE with reasons (do not re-propose; re-read only if the ticket's updatedAt moved):** **KS-1055 (P2 landmine — DESIGNED for a Claude seat: widen `applyFileMigrations`' `dbName` to `'main' | 'platform' | 'tenant'`, route tenant like main (`(dbName === 'main' || dbName === 'tenant') && m.isPlatform → continue`), call it in the tenant loop BEFORE `migrateDatabase` at `startup-migrations.ts:1184` to mirror main's file-then-core order (:965 → :997; the files are IF NOT EXISTS); the TEST needs the KS-1125 `Module._resolveFilename` harness because `vi.mock('pg')` cannot reach the bare `require('pg')` at :945)**; KS-947 (F3/F4 edit a TEST cell — the subject IS the test → Claude seat); KS-580 (3–5 days, design); KS-986 (docs/config + a demo env question), KS-960 (DO NOT RECONCILE — authority first), KS-955 (test infra), KS-837 (tooling design), KS-784 (an unowned Schemathesis failure — investigation), KS-748 (a SQL constraint — no checker), KS-1031 (a deploy condition), KS-678 (domain ownership), KS-579/581 (design, days), KS-627 (COSE crypto, multi-file), KS-808 (bash — no checker), KS-851 (four minors, multi-file), KS-915 (design), KS-1145 (a bash test), KS-1162/967/709 (workflows/scripts/tooling); plus the 22:1x seat's list: KS-1143, KS-965 (after KS-964), KS-1048, KS-789, KS-1036, KS-758, KS-934, KS-1140/1144/1131/1147, KS-1168, KS-753, KS-1125, KS-1111, KS-755, KS-981, KS-1076, KS-1114/1129/757/979/980/1159, KS-777 (record defect → Done close Sunday), KS-807, KS-683, KS-759, KS-746, KS-692, KS-1121/629/975 (carded). Auth/MFA/OAuth LAST.
- **UNATTENDED LOOP (Monday deadline):** `night/derive_candidates.py` resolves basenames/docs/routes (row 90) — its hints still need a Wednesday read (the human-shaped step); the 15-min loop job takes `night/queue.md` lines; the 06:45 receipt job is ARMED (row 91); D8/D9 now make a doc PASS mean "these lines, at this place" (row 99). **MISSING: the briefs-a-day-ahead batch** (Wednesday writes a day's briefs each morning and queues them) — and the pool for it is thin: after the day's re-derivation, the honest next tiers are the T5 split vein (Claude seats) and the auth tier (LAST, by Kam's 16:40).
- **For Kam's read (no clock):** KS-1172/1173 activation waits for Sunday (his 19:44); the KS-953 and KS-1102 cards; `iogpu.wired_limit_mb` persistence; docker daemon DOWN on the Studio; node 24.7.0 < engines 24.11.0.
- **Rotation:** band 80–90 at a safe boundary, Ornith running through it. Successor's first reads: this block → `night/done.md` tail → `kam_rulings_today.sh` → inbox by SUBJECT → `usage_gate.sh --check`.

## ⚠ TRAPS
- **COMMIT THE TWO REGENERATED DIGESTS AT BOOT** (`0_Brain/learnings/_boot_digest*.md` — the launcher rewrites them): `panel_sync` SKIPS its rebase+push while any tracked file is dirty. Then `git -C /Volumes/DevMASTER/WEDNESDAY push origin main` yourself and confirm `merge-base --is-ancestor HEAD origin/main` (panel_sync may race your push — a second push settles it).
- **A launch while the previous runner is in its 60 s post-ticket SETTLE exits 0 on the LOCK and consumes nothing** — the lock check must GATE the launch (`P=$(cat night/log/.night_run.lock/pid); kill -0 $P && exit`), never print-and-continue (the 23:2x seat printed LOCK and launched anyway, then waited five minutes on a log with no verdict). A queue line is MOVED to `done.md` when its run ends — a re-run needs a fresh queue line.
- **`python3` read-then-write: `open(p,'w').write(open(p).read()…)` TRUNCATES before it reads** — read into a variable first.
- **NEVER edit `night/*.sh` or `tasks/*/checker.sh` while a runner is live**: write `<file>.new` and `mv` it over. `git -C $VAR <write verb>` is REFUSED by the hook — literal paths; a scratch clone under `/private/tmp/claude-501/night/` is OUTSIDE the tree for the hook too (no write verbs there from the tool; the checker's own git runs are fine). `cd` at the head of a call is refused — `git -C /Volumes/DevMASTER/WEDNESDAY …`. `rm $VAR` refused — `mv` to the scratchpad. macOS has no `setsid` and no `timeout`; `cat -A` does not exist (`sed -n l`). zsh: `for x in $LIST` / `kill $PIDS` do NOT word-split; an rc read through a pipe is cut's. The subject-token gate refuses stop/hold/hand over now/checkpoint outside the leading position. The chat-store hook refuses ad-hoc `chat_log.json` reads — `kam_msgs.sh` / `kam_rulings_today.sh`. `<<'EOF'` always; **any clock in a row/brief/panel line is `$(date +%H:%M)` substituted by the shell**. Waiters on the runner poll the LOCK PID (`kill -0`), never `pgrep -f night_run`. Split briefs share a ticket id → separate `briefs/split_<id><X>/` dirs + `NIGHT_BRIEFS_DIR=` + an OWN `NIGHT_QUEUE=` file; `NIGHT_DONE=night/done.md` explicitly. Ornith: `done.md` rows are verdicts; a re-check runs from a scratch copy; **read after.md / the product hunk before a READY — a PASS is a claim (two false greens this week were found only by reading)**; every FAIL gets an IMPROVEMENTS row + a fix where it lives, same session.
