---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at 07:23 by the 03:45 Wednesday seat at its ROTATION HANDOVER (ctx ~79, band 80-90; previous copy NEXT-PICKUP.md.pre-0922-0723; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 03:45 seat, rotation handover) — replace it, never append

**Kam:** TRAVELLING (left Monday night); quiet since 15:43 09-21. `WEEK-INSTRUCTION.md` LIVE (valid_until 2026-09-27, Wednesday's reading; return day unanswered). **The 06:00 receipt for 09-22 is DONE** (live board 06:0x + a one-sentence correction); the next receipt is 09-23 06:00 (arm a 05:58 wake from a script file at boot — nothing else wakes a seat for it). He types on the LIVE board (`kam_msgs.sh` defaults `--source live`; poller pid 14963 — `pgrep -f cockpit/live_chat_poll.sh` + a fresh health line at boot). Usage 7d ~56%, gate open. Quiet hours 23:00–06:00. Ledger 3c: DONE for the 09-19 rows at this handover (15 moved, 1198 == 1198); the 09-20 rows pass the line on 09-23.

### 🔴 IN FLIGHT (floor at the handover: `%0` this seat · `%27` Seat C 17th MERGING on the signed GO · `%9` monitor)
1. **Seat C 17th is merging TWELVE PRs on Wednesday's signed GO** (`briefs_staged/2026-09-22_seatC17_go_1148-1166.md`, sent 21:2xZ, read back at the destination, tap delivered): #1148 #1150 #1152 #1154 #1156 #1158 #1160 #1162 #1163 #1164 #1165 #1166, BASE_GO `a1931d2f3f99b88748d9db49b9eb36e0572b5e5d`, targets 1/1/1/1/1/1/1/1/3/2/1/2 (16 blobs; the addendum in `…/reports/2026-09-22-batch1148-1166-r1/report.md`, sha256 32d8e810…). **Its wakes: (a) STATUS "twelve MERGED" → verify at source (`ls-remote` develop; `rev-parse <new>^{tree}` == the gate's twelve-PR END STATE over a1931d2f3 — the gate names it in its report; `rev-list --count --first-parent a1931d2f3..<new>` = 12; the 16 target blobs at the tip via targets.json in `scratchpad`-equivalent — re-derive: read the seat's `2026-09-22_seatC-16th/raise/` file-by-file with `cat` (`cp`/`tar` are refused by the path guard), run `targets17.py <report.md> batch1148-1166-r1` there) → read the two rule-7 DRAFTS whole (KS-485 @peter, KS-772 @stuart.jamieson: BLUF-first test blocks, facts only, own keys, the two record Minors on #1163/#1166 named, the six auth pins as pins of EXISTING behaviour, KS-910 `Refs` only) → RULE (post both as written unless a fact is wrong; a file-name token carrying an archived key stays — the 15th's S4 reading) via `send_brief.sh --kind answer` + `cockpit.sh say --mail`; (b) its WRAP → verify records on disk (`HANDOVER-seatC-17th-*`, history.md top entry, porcelain 0, rule-7 comment ids in the wrap) → score (the B 17th got 1.00) + `pane_close.sh %27` in ONE action (read the listener diff warning if any).** Then: KS-910's CLOSE is Wednesday's own later pass (Kam 2026-09-16 09:53) — after #1166 merges, close KS-910 on the board via a Secuura seat? NO: Wednesday holds no board identity — commission the close in the NEXT Secuura seat's brief (one comment naming #1166 + Done), never by hand.
2. **The 16th round's B half is CLOSED** (8 merged → develop `a1931d2f3`; rule 7 posted KS-485 `a4c00986…` / KS-772 `d0b57486…`; scored 16th 0.95 / gate 1.00 / 17th 1.00). After C's twelve land: 20 PRs merged this round; develop moves again — **re-derive `night/candidates.md` (`derive_candidates.py`) at the next Ornith sitting** (closed/archived rows fall out).
3. **Ornith: queue EMPTY, reason on disk (`night/QUEUE_EMPTY_WHY.md` — every tier thin by measurement; FEED 3/4/5 + rebrief 3 all drained: 11 R16 READYs HELD this seat — KS-947b, KS-1265, KS-1171 ×2 TSFIX, KS-1123 F3b CAST, KS-1192, KS-1231 A+B, KS-811, KS-1246, KS-1257 THREEHUNKS; three R15 READYs (KS-1171 ×2, KS-1123 F3b) and the 09-17 KS-1192 marked SUPERSEDED with backups beside).** Refills, in order: (1) the two gates' NOT-PINNED rows (gate16B struck its one candidate; gate16C's report — read its NOT-PINNED section) → test_only briefs; (2) the post-merge `derive_candidates.py` re-run; (3) the 12 CARD-shaped rows from FEED 5 (KS-1252/1253 need a HARNESS change — `build_input.sh:191` refuses a product outside services/*|packages/shared — an IMPROVEMENTS item, not a card; KS-1274, KS-1048, KS-755 are Kam-class → cards WITH defaults, not yet filed); (4) a widened search commission if still dry. **The 11 R16 + the un-raised older READYs are the 17th round's RAISE pool** — a Seat B 18th / C 18th successor brief after C 17th wraps (partition by directory as the 16th did; the four cross-seat rulings + the push-window lock FOR MERGES verbatim; STANDING block from the 09-09 lesson's 09-22 extension). Kam's 09-13 rule: as many seats as the code partition allows.
4. **Rung 10 is now routine:** every idle wake on a holding seat carries the detector verdict; four ghosts tonight (`GO mailed`, `READY 4 read; continue`, `ADDENDUM mailed`, `mail: read your inbox`) — ack with `wake_ack.sh`, nothing sent; the seats' own rule (inbox + DKIM) held every time.

### STANDING RULES LEARNED (carry, do not re-learn)
The Bash tool is ZSH; `cd` REFUSED by the hook; `cp <other-tree file> …` and `tar -C <other tree>` are REFUSED as writes to the source — read across with `cat` per file; `git -C <other tree> fetch` REFUSED (hook live since 09-21) — verify merges with `ls-remote` + `cat-file`/`rev-parse`/`rev-list`; `safe_push.sh` stages ONLY named paths (+ decisions.json) and REFUSES a mistyped path — read every backup name from `ls`, never retype a clock; `send_brief.sh` refuses a subject carrying hold/stop/checkpoint tokens anywhere (even "what you hold"); a refusable tool's rc on its own line; `hold_ready.py` needs ABSOLUTE run/golden paths, takes ROWID + TITLE where the TITLE is read from the brief's `head -1` (a typed title was wrong once today), handles code_patch since 03:5x with the checker's own A3 predicate since 04:4x; every count in a drafted brief re-derived (key sets ∅ vs the newest passing input; `"`/`\`/non-ASCII 0 on every `+` line; goldens `RESULT: PASS` from checker.log — the precheck dirs also hold informational dialect ARMS that FAIL by design, read the dir name); a queue append + kick is followed IN THE SAME ACTION by a waiter from a script FILE keyed on the input paths; a gate prompt needs a CONTEXT RULE (write report.md at 80 with NOT TESTED for the rest) — add to the gate template; a chat receipt names client-human comments FROM a per-ticket GraphQL listing, never from `board_sweep`'s 60-row sample.

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. `absence_claim_check.sh` adds 'only'/'nothing else' (w=7 today) · `hold_ready.py` derives the TITLE from the brief's headline and refuses a free-text one; prints WHY on a relative path · `pane_close.sh` prints the listener DIFF (pid, port), not the count · the gate prompt template gains the ctx rule · the builder refuses a mixed hunk whose `+` group precedes its first context line (the KS-1257 r1 shape) · `reanchor.py` insert-only "before" branch (the drafter's named sharp edge) · checker T1 `ESCAPED-NEWLINES` (KS-1227 class) · `wake_ack.sh` keys on the detector verdict class · `build_input.sh:191` product-path allow-list widened (KS-1252/1253) · `board_count.sh linear` label filter · `cockpit.sh say` prints WHY it refuses · `brief_and_launch.sh` skip = rc 1 · doctor: expired `PAUSE_QUEUE`, live-poll health · `nas_sync.sh` refuses an unset WED_AGENT · EXPIRING-GRANTS-class rows (Easy Auth secret 2027-03-21, seat certs 2027-09-21) · the four §5f escalations re-carded WITH DEFAULTS · dependabot 10 open · INDEX.md refresh + the projects' history skim (deferred twice — the successor does it at its boot sweep, bounded) · the 12 FEED-5 card-shaped rows with defaults.

### ROUTE TO KAM (the 06:00 receipt sent; nothing else this seat)
Carried, NOT re-sent: the two cards (`secuura-ks1175-kintsugi-deploy-and-first-anchor` default c; `secuura-ks721-commitment-cannot-reach-a-real-chain` default a); platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi's connector allow-list; kintsugi disk 25 G free; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; seat A's launcher F-02 (inert); O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; audit-baseline.json fuse expires 2026-09-24 (TWO DAYS — card it with a default before it lapses); O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the 68 un-raised older READYs.
