---
date: 2026-09-22
type: pickup
scope: SECUURA + all general/generic work. Datasec is TUESDAY's. Datasec mail by subject only.
source: replaced WHOLESALE at the 50% checkpoint by the 18:3x Wednesday seat (ctx 50; band 80-90; previous copy NEXT-PICKUP.md.pre-0922-1917 beside — read it by ls; older in NEXT-PICKUP-archive.md).
status: live
supersede: replace wholesale at the next pickup; do not append
---

# NEXT PICKUP

## ONE block (the 18:3x seat, 50% checkpoint) — replace it, never append

**Kam:** AT HIS COMPUTER on the LIVE board (his 08:59; newest row 18:11; nothing since). Receipts sent this seat: boot; swap running; kintsugi deployed; first anchor going ahead; **FIRST ANCHOR CONFIRMED (with the cardanoscan link)**. The launcher card is `--delivered` (18:17, previous seat; verified). The file drawer awaits HIS FIRST CLICK (built 16:0x, committed b2405791f). Usage 7d 84%, gate open. Stash list 23 (the record; never drop). No lesson file edited this seat → digests untouched by hand (safe_push regenerated their stamp once).

### 🔴 IN FLIGHT (floor: `%0` this seat · `%37` Seat A 16th · `%38` Seat B 20th · `%39` Seat C 20th HOLDING 12/12 · `%40` gate19C RUNNING · `%41` gate19B DONE (verdict mailed; pane still up — close with the wrap) · `%9` monitor; the FEED 16 drafter subagent has LANDED, its proposal unread at this write)
1. **Seat A 16th — KINTSUGI DEPLOYED + FIRST ANCHOR CONFIRMED.** develop 3bad652d1 on 28 services (STATUS 09:02Z, V1–V7 PASS); anchor `anchor_1526505a-03b9-4062-bc91-501e33be43ac`, preview tx `0180573229ad60a6bd1e369f2dbc28e1bd47f3d1b08cb691b09cea72cd7e76fb`, block 4685580 (STATUS 09:10Z, 15/15 chain-shape checks, control tx has no key). **RULED 09:15:55Z (ANSWER at its inbox, tap clear): POST ×5** — KS-1175 facts with the KS-1284 sentence REPLACED by the measured form (verify hit `source db`; the product's chain-source reader NOT exercised; remaining leg named) + KS-1175 Done only if the ticket's own text is fully met · a NEW KS-1284 evidence comment (no state move) · KS-601 record as written · rule-7 notices Peter KS-485 / Stuart KS-772 as written (the project's deploy-notice rule inside the week instruction's rule-7 carve-out). NEXT: its `STATUS: comments posted` → mark the card `decision_queue.sh --delivered secuura-ks1175-kintsugi-deploy-and-first-anchor "<KS-1175 comment URL>"` → its wrap → **score + `pane_close.sh %37` in ONE action** (check the wrap's handover + history entry on disk first).
2. **Seat B 20th — SIGNED GO SENT 09:14:36Z** (`fleet/briefs_staged/2026-09-22_go19B_seatB20.md`; subject exactly `GO: merge #1182, #1184, #1186, #1194, #1196, #1198, #1199, #1200, #1201 batch`; pair-blob line for #1199 `Blockchain/Dev/services/security/src/index.ts=2ad45cd8e5552d5d52e48749406203d149967073` — predicted by Wednesday in its scratch clone `<scratchpad>/g19b/clone`, tree 64de96836e46 == the gate's; BASE_GO 3bad652d1 re-read in the send action; END_TREE 3df72c02d3). gate19B verdict: 9 GO / GO WITH FINDINGS, 0 NO GO (report sha 00e15fb7… re-hashed; NOT-TESTED 18:35 < report 19:10). NEXT: its `MERGED` STATUS → verify at source (develop's sha + tree by own ls-remote; each PR closed as merged) → its comment bytes (rule-7 HELD → rule) → wrap → score + close `%38` in one action. **Then close gate19B's pane `%41`** (its verdict is delivered; `pane_close.sh` — the tty check first).
3. **Seat C 20th HOLDING 12/12 — gate19C STILL RUNNING on `%40`** (at 18:57 "four lanes remain, ~20 min"; its report.md was on disk at 18:53 but the VERDICT MAIL has not arrived — do not read the disk report as a verdict). On the verdict mail: completion check at source exactly as 19B's (report sha; DKIM; NOT-TESTED first; the twelve heads + develop by own ls-remote; the PAIR blob `Start_Up/start-secuura.sh=58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb` predicted in the scratch clone by `merge-tree --write-tree <head1180> <head1181>`) → signed GO to `Secuura/Blockchain-C` (subject exactly `GO: merge #1180, #1181, #1183, #1185, #1187, #1188, #1190, #1191, #1192, #1193, #1195, #1197 batch`; **the GO MUST CARRY the line `--pair-blob Start_Up/start-secuura.sh=58cdd3dc846b730e9f7eb5b517a6e4108ac05fdb`**; BASE_GO re-read in the send action — **develop WILL have moved if Seat B merged first: say so, the seat re-predicts**; combined end state over 3bad652d1 is `b4f2a8beaecd` either order per gate19B; C ∩ B files = ∅) → merges → close. Briefs: `…seatC_20.md`, answer `…seatC20_answer_plan.md`.
4. **Ornith: FEED 16 LANDED** — proposal `fleet/briefs_staged/2026-09-22_ornith_feed16_queue_proposal.md` (drafter's final line: KS-1245 bash_patch queue-ready · KS-1019 comment_patch at originate.openapi.ts:589 (NOT :601/:615 — slips) queue-ready · KS-1084 part A code_patch queue-ready as a HELD diff, part B TABLED (401 for every caller at the tip; card text in §0 #5); 7 slips in §0). NEXT: read §0 slips FIRST, re-derive every count/path/line by own command, `suggested_test_file` == `File:` by value per input, key set == the newest PASSING input of the type, then append the three queue lines (`task=` explicit; `input=` path) to `night/queue.md` — the runner is NOT running and `PAUSE_QUEUE` expires 19:41 (the pause file may be removed/expired by then: check `night/PAUSE_QUEUE` by `ls`); KS-1145 + KS-1121 → Claude (counter spent). Then the round-19 gates' NOT-PINNED rows = FEED 17.

### STANDING RULES LEARNED (carry, do not re-learn)
`safe_push.sh "<message>" <paths…>` — FIRST arg is the MESSAGE; the Bash tool is ZSH; `cd` REFUSED; `rm` outside a literal scratchpad path REFUSED; `git -C <other tree> <write verb>` REFUSED — and the hook cannot see through a `$VAR` path: a scratch-clone write verb needs the LITERAL scratchpad path; `refs/pull/*/head` are NOT in the checkout — predict by the head SHA (the objects ARE in the shared store); `cockpit.sh say` by pane NAME (the `%id` form refuses silently rc 1 — WHY-print still owed); `note_entry.sh --h3 --stdin <<'EOF'`; `pgrep -fl` prints a runner's WHOLE BODY (~3K tokens) — use pid-only forms; read every fleet tool's usage line before its first call; a receipt to Kam = ONE message per event on the LIVE board, first person, BLUF first; the extension is not connected (no browser checks — say NOT TESTED).

### OWED (mine, none blocking)
0. 🔴 **DATED — Wednesday 2026-09-23 (Kam, terminal 18:5x on 09-21): AFTER Tuesday's 23:00 NAS leg on 09-22 night AND Wednesday's 03:30 leg on 09-23 have both run, re-run `5_Project_History/2026-09-21_portable_blind_copy_KK_DEV_Local.sh` (additive) with `/Volumes/KK_DEV_Local` MOUNTED; precondition reads: `scheduler/state/nas_sync_last_wednesday.txt` (a 09-23 run) + Tuesday's leg reported; then Kam the total + rc on the panel.**
1. DONE this seat: the Tuesday launcher week-instruction line seat-aware (2a0d0be5c) · `absence_claim_check.sh` 'only'/'nothing else'/'no other' (ad46b82cf). STILL OWED: `cockpit.sh say` prints WHY it refuses · `night_run.sh` refuses an identical-sha re-run · `send_brief.sh --kind brief` refuses a foreign `ks-\d+` in a `feature/…` name · `hold_ready.py` derives the title from the brief · the 09-06 lesson gains `git clone --shared`'s measured scope (regenerate BOTH digests) · the test_only checker `:44` header + `prepare_clone.sh` header doc fixes · doctor: expired `PAUSE_QUEUE`, live-poll health · EXPIRING-GRANTS-class rows (Easy Auth secret 2027-03-21; seat certs 2027-09-21; audit-baseline 09-30 / 10-02) · dependabot 19 open · the 12 FEED-5 card-shaped rows · the two `confirmed,simulated=true` anchor rows on kintsugi · a Datasec-content row (18:11, QuickQuote/NexusAI) sits in THIS seat's local chat store with `view` None — subject-level only, not acted; the store's per-seat split is a shared-tooling question for the next consolidation.

### ROUTE TO KAM (he is on the live page today)
Sent this seat: 6 receipts (boot; swap running; deployed; anchor going ahead; anchor confirmed + link; —). Cards: 0 new. Carried, NOT re-sent: platform-s#877 unreadable; Peter's two KS-1195 questions; his KS-593 addition; kintsugi's connector allow-list; KS-1262 severity unowned; the drive sync's `(conflict_on_…)` copies; O-1 CI jobs never start; the NSG's dynamic IP; report-796 F-01/F-03; KS-1269-U/N84-1; ruleset 18499832's flag; O-1 `admin.ts` `requireAdmin` routes do no session check; the KS-1283 coverage ticket; M-7; VIEW-NONSTRING-ARRAY; the older READY pool; the master template + 14 other launchers still `git fetch` in their single-session step (Seat C's note 1 — other projects' files; not in his launcher ruling's scope).
