#!/usr/bin/env python3
"""server.py — Wednesday dashboard Phase 0.1: static site + tiny write API.

Bound to 127.0.0.1 ONLY. Writes go exclusively to Wednesday's own Linear WED
workspace (never any client board). Endpoints:
  GET  /                → site/index.html (regenerated by the collect loop)
  POST /api/add         → {"title": str, "priority": 1..4} → new WED issue (Todo)
  POST /api/prioritise  → {"id": "WED-xx"} → set priority Urgent (1)
  POST /api/start       → {"id": "WED-xx"} → move to In Progress
After any write: linear collector + generator re-run so the page reflects it.
NOTE before any remote exposure (Phase 4/Tailscale): add auth to this API.
"""
import datetime, json, os, pathlib, re, subprocess, urllib.request
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler

# Dedicated Wednesday port — block 47780-47789, registry in ../PORTS.md
# (never common dev/Docker ports; Kam directive 2026-08-05).
PORT = int(os.environ.get("WEDNESDAY_DASHBOARD_PORT", "47787"))

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SITE = HERE / "site"

def env():
    e = {}
    for line in (ROOT / "4_Credentials" / ".env").read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1); e[k.strip()] = v.strip()
    return e

ENV = env()

def gql(query, variables=None):
    req = urllib.request.Request("https://api.linear.app/graphql",
        data=json.dumps({"query": query, "variables": variables or {}}).encode(),
        headers={"Authorization": ENV["LINEAR_API_KEY"], "Content-Type": "application/json"})
    r = json.load(urllib.request.urlopen(req, timeout=20))
    if "errors" in r:
        raise RuntimeError(r["errors"])
    return r

def issue_id(identifier):
    num = int(identifier.split("-")[1])
    r = gql('query($n:Float!){ issues(filter:{team:{key:{eq:"WED"}}, number:{eq:$n}}){ nodes{ id } } }',
            {"n": num})
    return r["data"]["issues"]["nodes"][0]["id"]

def state_id(name):
    r = gql('query($id:String!){ team(id:$id){ states{ nodes{ id name } } } }',
            {"id": ENV["LINEAR_TEAM_ID"]})
    return {s["name"]: s["id"] for s in r["data"]["team"]["states"]["nodes"]}[name]

def refresh_site():
    subprocess.run(["python3", str(HERE / "collect.py"), "linear"], timeout=60)
    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)

# ── parking lot (WED-71 v1): one .md per item in 0_Brain/parkinglot ──────
PARK = ROOT / "0_Brain" / "parkinglot"

def park_path(name):
    """Resolve a client-supplied item name to a file inside PARK, or None.
    Basename only — no traversal; .md only; must already exist."""
    name = pathlib.Path(str(name or "")).name
    if not name.endswith(".md"):
        return None
    p = PARK / name
    return p if p.is_file() else None

def park_parse(path):
    """Frontmatter dict + title + one-liner (same rules as collect.py)."""
    text = path.read_text()
    parts = text.split("---", 2)
    fm = {}
    if text.startswith("---") and len(parts) >= 3:
        for line in parts[1].splitlines():
            m = re.match(r"^(\w+):\s*(.*)$", line)
            if m:
                fm[m.group(1)] = m.group(2).split("#", 1)[0].strip().strip('"').strip()
    body = parts[2] if len(parts) >= 3 else text
    tm = re.search(r"^#\s+(.+)$", body, re.M)
    om = re.search(r"^One-liner:\s*(.*?)(?:\n\s*\n|\Z)", body, re.M | re.S)
    return (fm, tm.group(1).strip() if tm else path.stem,
            re.sub(r"\s+", " ", om.group(1)).strip() if om else "")

def park_set_front(path, **kv):
    """Update frontmatter values in place, preserving inline # comments."""
    text = path.read_text()
    parts = text.split("---", 2)
    fm = parts[1]
    for k, v in kv.items():
        if re.search(rf"^{k}:", fm, re.M):
            fm = re.sub(rf"^({k}:\s*)[^\n#]*", lambda m: m.group(1) + v + " ",
                        fm, count=1, flags=re.M)
        else:
            fm = fm.rstrip("\n") + f"\n{k}: {v}\n"
    path.write_text(parts[0] + "---" + fm + "---" + parts[2])

def refresh_park():
    subprocess.run(["python3", str(HERE / "collect.py"), "parkinglot"], timeout=60)
    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)

class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=str(SITE), **kw)

    def log_message(self, fmt, *args):
        pass  # quiet

    def send_response(self, code, message=None):
        super().send_response(code, message)
        self.send_header("Cache-Control", "no-store")  # page must never go stale

    def do_GET(self):
        # Identity endpoint so launcher/serve.sh can tell "ours already
        # running" apart from a foreign process holding the port.
        if self.path == "/api/health":
            return self._json(200, {"app": "wednesday-dashboard", "ok": True})
        if self.path == "/api/chatlog":
            # Live-poll endpoint for the chat-with-Wed view (no regeneration).
            # Each message is joined with its ack state (key = message ts) so
            # the sidebar renders seen/actioning/done/action_requested live.
            cpath = ROOT / "0_Brain" / "dashboard" / "data" / "chat_log.json"
            log = json.loads(cpath.read_text()) if cpath.exists() else []
            if not isinstance(log, list):
                log = []
            apath = ROOT / "0_Brain" / "dashboard" / "data" / "ack_state.json"
            ack = json.loads(apath.read_text()) if apath.exists() else {}
            if not isinstance(ack, dict):
                ack = {}
            out = []
            for m in log:
                m = dict(m)
                a = ack.get(m.get("ts", ""))
                if isinstance(a, dict) and a.get("state"):
                    m["ack"] = a
                out.append(m)
            return self._json(200, {"messages": out})
        return super().do_GET()

    def _json(self, code, payload):
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        try:
            length = int(self.headers.get("Content-Length", 0))
            data = json.loads(self.rfile.read(length) or b"{}")
            if self.path == "/api/add":
                title = (data.get("title") or "").strip()[:200]
                prio = int(data.get("priority") or 3)
                if not title:
                    return self._json(400, {"error": "empty title"})
                if prio not in (1, 2, 3, 4):
                    prio = 3
                r = gql('mutation($input: IssueCreateInput!){ issueCreate(input:$input){ issue{ identifier } } }',
                        {"input": {"teamId": ENV["LINEAR_TEAM_ID"], "title": title,
                                   "priority": prio,
                                   "description": "Added from the Day Dashboard add-box."}})
                ident = r["data"]["issueCreate"]["issue"]["identifier"]
                refresh_site()
                return self._json(200, {"ok": True, "created": ident})
            if self.path == "/api/chat":
                text = (data.get("text") or "").strip()[:2000]
                if not text:
                    return self._json(400, {"error": "empty message"})
                cpath = ROOT / "0_Brain" / "dashboard" / "data" / "chat_log.json"
                log = json.loads(cpath.read_text()) if cpath.exists() else []
                log.append({"role": "kam", "text": text,
                            "ts": datetime.datetime.now().astimezone().isoformat()})
                cpath.write_text(json.dumps(log, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True})
            if self.path == "/api/mute":
                key = (data.get("key") or "").strip()[:300]
                if not key:
                    return self._json(400, {"error": "empty key"})
                mpath = ROOT / "0_Brain" / "dashboard" / "data" / "muted.json"
                muted = json.loads(mpath.read_text()) if mpath.exists() else []
                if key in muted:
                    muted.remove(key); state = "unmuted"
                else:
                    muted.append(key); state = "muted"
                mpath.write_text(json.dumps(muted, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True, "state": state})
            if self.path == "/api/layout":
                tiles = {"stats", "calendars", "flags", "family", "board",
                         "chat", "tickets", "email", "news", "parkinglot"}
                tint_keys = {"slate", "moss", "plum", "sand", "teal"}
                groups = {"datasec", "secuura", "personal", "family"}
                lpath = ROOT / "0_Brain" / "dashboard" / "data" / "layout.json"
                layout = json.loads(lpath.read_text()) if lpath.exists() else {}
                if not isinstance(layout, dict):   # corrupt/list file must not 500 a save
                    layout = {}
                if "order" in data:
                    layout["order"] = [t for t in data["order"] if t in tiles]
                    # keep tiles missing from the DOM (hidden ones) at the end
                    layout["order"] += [t for t in tiles if t not in layout["order"]]
                if "scales" in data:
                    layout["scales"] = {k: max(0.7, min(1.8, float(v)))
                                        for k, v in data["scales"].items() if k in tiles}
                if "sizes" in data:
                    layout["sizes"] = {k: {"w": max(1, min(3, int(v.get("w", 1)))),
                                           "h": max(0, min(20, int(v.get("h", 0))))}
                                       for k, v in data["sizes"].items() if k in tiles and isinstance(v, dict)}
                if "hidden_tiles" in data:
                    layout["hidden_tiles"] = [t for t in data["hidden_tiles"] if t in tiles]
                if "chat_mode" in data and data["chat_mode"] in ("message", "full", "sidebar"):
                    layout["chat_mode"] = data["chat_mode"]
                if "hidden_groups" in data:
                    layout["hidden_groups"] = [g for g in data["hidden_groups"] if g in groups]
                if "tile_groups" in data and isinstance(data["tile_groups"], dict):
                    # per-tile source filters: {tile: [group,...]} — both keys validated,
                    # empty lists dropped so the reset control really clears the state
                    tg = {}
                    for t, gs in data["tile_groups"].items():
                        if t in tiles and isinstance(gs, list):
                            keep = [g for g in gs if g in groups]
                            if keep:
                                tg[t] = keep
                    layout["tile_groups"] = tg
                if "tints" in data and isinstance(data["tints"], dict):
                    # "none"/invalid values simply drop the entry (no tint)
                    layout["tints"] = {k: v for k, v in data["tints"].items()
                                       if k in tiles and v in tint_keys}
                if "separators" in data and isinstance(data["separators"], list):
                    seps = []
                    for s in data["separators"]:
                        if isinstance(s, dict) and s.get("before") in tiles:
                            seps.append({"before": s["before"],
                                         "label": str(s.get("label") or "").strip()[:40]})
                    layout["separators"] = seps[:6]
                lpath.write_text(json.dumps(layout, indent=1))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True})
            if self.path == "/api/views":
                # Named favourite views: snapshot / apply / delete whole-layout presets.
                action = (data.get("action") or "").strip()
                name = (data.get("name") or "").strip()[:40]
                if not name:
                    return self._json(400, {"error": "empty view name"})
                vpath = ROOT / "0_Brain" / "dashboard" / "data" / "views.json"
                views = json.loads(vpath.read_text()) if vpath.exists() else {}
                if not isinstance(views, dict):   # corrupt/list file must not 500 a save
                    views = {}
                lpath = ROOT / "0_Brain" / "dashboard" / "data" / "layout.json"
                if action == "save":
                    if name not in views and len(views) >= 12:
                        return self._json(400, {"error": "max 12 saved views — delete one first"})
                    snap = json.loads(lpath.read_text()) if lpath.exists() else {}
                    views[name] = snap if isinstance(snap, dict) else {}
                    vpath.write_text(json.dumps(views, indent=1, ensure_ascii=False))
                    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                    return self._json(200, {"ok": True, "saved": name})
                if action == "apply":
                    if name not in views:
                        return self._json(400, {"error": f"no view named {name!r}"})
                    lpath.write_text(json.dumps(views[name], indent=1))
                    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                    return self._json(200, {"ok": True, "applied": name})
                if action == "delete":
                    if name not in views:
                        return self._json(400, {"error": f"no view named {name!r}"})
                    del views[name]
                    vpath.write_text(json.dumps(views, indent=1, ensure_ascii=False))
                    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                    return self._json(200, {"ok": True, "deleted": name})
                return self._json(400, {"error": "action must be save|apply|delete"})
            if self.path == "/api/pin":
                text = (data.get("text") or "").strip()[:200]
                if not text:
                    return self._json(400, {"error": "empty"})
                ppath = ROOT / "0_Brain" / "dashboard" / "data" / "pinned.json"
                pinned = json.loads(ppath.read_text()) if ppath.exists() else []
                state = "unpinned" if text in pinned else "pinned"
                pinned = [x for x in pinned if x != text] if state == "unpinned" else pinned + [text]
                ppath.write_text(json.dumps(pinned, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True, "state": state})
            if self.path == "/api/focus":
                text = (data.get("text") or "").strip()[:200]
                import datetime as _dt
                fpath = ROOT / "0_Brain" / "dashboard" / "data" / "focus.json"
                if text:
                    fpath.write_text(json.dumps({"text": text, "ts": _dt.datetime.now().astimezone().isoformat()}))
                elif fpath.exists():
                    fpath.unlink()
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True})
            if self.path == "/api/actionnow":
                # HONESTY RULE (WED-73): this endpoint may ONLY ever write
                # "action_requested". seen/actioning/done are written
                # exclusively by Wednesday's own session, out-of-band.
                key = (data.get("key") or "").strip()[:300]
                label = (data.get("label") or "").strip()[:200]
                if not key:
                    return self._json(400, {"error": "empty key"})
                import datetime as _dt
                now = _dt.datetime.now().astimezone().isoformat()
                apath = ROOT / "0_Brain" / "dashboard" / "data" / "ack_state.json"
                ack = json.loads(apath.read_text()) if apath.exists() else {}
                if not isinstance(ack, dict):
                    ack = {}
                ack[key] = {"state": "action_requested", "ts": now, "label": label or key}
                apath.write_text(json.dumps(ack, indent=1, ensure_ascii=False))
                cpath = ROOT / "0_Brain" / "dashboard" / "data" / "chat_log.json"
                log = json.loads(cpath.read_text()) if cpath.exists() else []
                if not isinstance(log, list):
                    log = []
                log.append({"role": "kam", "text": f"ACTION NOW: {label or key}", "ts": now})
                cpath.write_text(json.dumps(log, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True, "key": key})
            if self.path == "/api/archive":
                ident = (data.get("id") or "").strip()
                key = (data.get("key") or "").strip()[:300]
                label = (data.get("label") or "").strip()[:200]
                def log_archive(key_or_id):
                    # local record feeding the topbar "archived" panel
                    import datetime as _dt
                    lgpath = ROOT / "0_Brain" / "dashboard" / "data" / "archived_log.json"
                    lg = json.loads(lgpath.read_text()) if lgpath.exists() else []
                    if not isinstance(lg, list):
                        lg = []
                    lg.append({"key_or_id": key_or_id, "label": label,
                               "ts": _dt.datetime.now().astimezone().isoformat()})
                    lgpath.write_text(json.dumps(lg, indent=1, ensure_ascii=False))
                if ident:
                    if not ident.startswith("WED-"):
                        return self._json(400, {"error": "WED ids only"})
                    gql('mutation($id:String!){ issueArchive(id:$id){ success } }', {"id": issue_id(ident)})
                    log_archive(ident)
                    refresh_site()
                    return self._json(200, {"ok": True, "archived": ident})
                if key:
                    apath = ROOT / "0_Brain" / "dashboard" / "data" / "archived.json"
                    arch = json.loads(apath.read_text()) if apath.exists() else []
                    if not isinstance(arch, list):
                        arch = []
                    if key not in arch:
                        arch.append(key)
                    apath.write_text(json.dumps(arch, indent=1, ensure_ascii=False))
                    log_archive(key)
                    subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                    return self._json(200, {"ok": True, "archived": key})
                return self._json(400, {"error": "need id or key"})
            if self.path == "/api/parkadd":
                # Add flow: the mode choice is EXPLICIT — no silent default.
                text = (data.get("text") or "").strip()[:500]
                mode = (data.get("mode") or "").strip()
                source = (data.get("source") or "").strip()[:200]
                if not text:
                    return self._json(400, {"error": "empty one-liner"})
                if mode not in ("parked", "research"):
                    return self._json(400, {"error": "mode must be 'parked' or 'research' — no default"})
                today = datetime.date.today().isoformat()
                slug = re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.lower()[:60])).strip("-") or "item"
                name = f"{today}_{slug}.md"
                n = 2
                while (PARK / name).exists():
                    name = f"{today}_{slug}-{n}.md"; n += 1
                src_line = f'source: "{source}"' if source else 'source: ""'
                (PARK / name).write_text(
                    f"---\ndate: {today}\nmode: {mode}\nstatus: open        "
                    f"# open | promoted | dropped\n{src_line}\npromoted_to: \"\"\n---\n\n"
                    f"# {text[:120]}\n\nOne-liner: {text}\n")
                refresh_park()
                return self._json(200, {"ok": True, "file": name, "mode": mode})
            if self.path == "/api/parkdrop":
                p = park_path(data.get("file"))
                if not p:
                    return self._json(400, {"error": "unknown parking-lot file"})
                park_set_front(p, status="dropped")
                refresh_park()
                return self._json(200, {"ok": True, "dropped": p.name})
            if self.path == "/api/parkpromote":
                p = park_path(data.get("file"))
                if not p:
                    return self._json(400, {"error": "unknown parking-lot file"})
                fm, title, one_liner = park_parse(p)
                if fm.get("status") == "promoted":
                    return self._json(400, {"error": f"already promoted ({fm.get('promoted_to', '?')})"})
                desc = ((one_liner or title) +
                        f"\n\nBrain file: 0_Brain/parkinglot/{p.name} (parking-lot promotion)")
                if data.get("dry_run"):
                    # test hook: everything up to the Linear call, no write anywhere
                    return self._json(200, {"ok": True, "dry_run": True,
                                            "would_create": {"title": title[:200], "description": desc}})
                r = gql('mutation($input: IssueCreateInput!){ issueCreate(input:$input){ issue{ identifier } } }',
                        {"input": {"teamId": ENV["LINEAR_TEAM_ID"], "title": title[:200],
                                   "description": desc}})
                ident = r["data"]["issueCreate"]["issue"]["identifier"]
                park_set_front(p, status="promoted", promoted_to=f'"{ident}"')
                subprocess.run(["python3", str(HERE / "collect.py"), "linear", "parkinglot"], timeout=60)
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True, "created": ident})
            if self.path == "/api/parkdiscuss":
                p = park_path(data.get("file"))
                if not p:
                    return self._json(400, {"error": "unknown parking-lot file"})
                _fm, title, _one = park_parse(p)
                cpath = ROOT / "0_Brain" / "dashboard" / "data" / "chat_log.json"
                log = json.loads(cpath.read_text()) if cpath.exists() else []
                if not isinstance(log, list):
                    log = []
                log.append({"role": "kam",
                            "text": f"Discuss parking-lot item: {title} — 0_Brain/parkinglot/{p.name}",
                            "ts": datetime.datetime.now().astimezone().isoformat()})
                cpath.write_text(json.dumps(log, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True})
            if self.path == "/api/flag":
                # "Flag for Wed" — marks an item for Wednesday's attention WITHOUT
                # touching the ticket, its status, or anything upstream. Kam's point:
                # nothing should change until Wednesday has actually seen it, which is
                # exactly why the label is "flag for Wed" and not "move to in progress".
                key = (data.get("key") or "").strip()[:300]
                if not key:
                    return self._json(400, {"error": "need key"})
                on = bool(data.get("on", True))
                fpath = ROOT / "0_Brain" / "dashboard" / "data" / "wedflags.json"
                fl = json.loads(fpath.read_text()) if fpath.exists() else {}
                if not isinstance(fl, dict):
                    fl = {}
                if on:
                    import datetime as _dt
                    fl[key] = {"label": (data.get("label") or "").strip()[:300],
                               "kind": (data.get("kind") or "item").strip()[:24],
                               # payload lets a flagged item SURVIVE its source feed:
                               # a flagged headline stays put tomorrow even once the
                               # news feed has moved on, until Kam unflags it.
                               "payload": data.get("payload") if isinstance(data.get("payload"), dict) else None,
                               "ts": _dt.datetime.now().astimezone().isoformat()}
                else:
                    fl.pop(key, None)
                fpath.write_text(json.dumps(fl, indent=1, ensure_ascii=False))
                subprocess.run(["python3", str(HERE / "generate.py")], timeout=60)
                return self._json(200, {"ok": True, "flagged": on, "key": key})
            if self.path in ("/api/prioritise", "/api/start"):
                ident = data.get("id", "")
                if not ident.startswith("WED-"):
                    return self._json(400, {"error": "WED ids only"})
                iid = issue_id(ident)
                if self.path == "/api/prioritise":
                    gql('mutation($id:String!){ issueUpdate(id:$id, input:{priority:1}){ success } }', {"id": iid})
                else:
                    gql('mutation($id:String!,$s:String!){ issueUpdate(id:$id, input:{stateId:$s}){ success } }',
                        {"id": iid, "s": state_id("In Progress")})
                refresh_site()
                return self._json(200, {"ok": True, "issue": ident})
            return self._json(404, {"error": "unknown endpoint"})
        except Exception as e:
            return self._json(500, {"error": str(e)})

if __name__ == "__main__":
    try:
        srv = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    except OSError as e:
        raise SystemExit(f"dashboard: cannot bind 127.0.0.1:{PORT} ({e}) — "
                         "port held? See 2_Project_Files/PORTS.md; never kill the holder.")
    print(f"dashboard: http://127.0.0.1:{PORT} (static + write API, WED board only)")
    srv.serve_forever()
