LAUNCH BRIEF (Seat E 11th): successor of Seat E 10th on pane `Secuura/Blockchain-E`. **A RAISE SEAT, ONE OF FOUR PARALLEL SEATS (R 18th, E 11th, G 4th, F 5th) on ONE checkout and ONE inbox. YOURS IS THE OPENAPI SEAT: every Spark pass that touches the generated contract `Blockchain/Dev/docs/openapi/secuura-api.yaml` is in THIS seat and no other.** In order: (1) ITEM 0, bounded, then a plan confirmation and WAIT; (2) a FRESH RAISE_BASE accepted by Wednesday BY NAME; (3) RAISE the KS-1449 nft pair (ONE PR), then KS-591 (ONE PR, five passes), then KS-1364 (ONE PR, five passes), each to READY FOR QA — order and shape per Q-PRSHAPE18. No merge, no gate, no deploy. Secuura NEVER force-pushes. Usage: Kam's new-account grant, clause RAISE, `WED_USAGE_STOP=100`.

## SEND AMENDMENT (Wednesday fills at send: pane ids for all four seats, rulings on the QUESTIONS at the foot, ticket reads in PROVENANCE)
- @@FILL@@

# LAUNCH BRIEF: Seat E 11th, Secuura/Blockchain, lane E (pane `Secuura/Blockchain-E`). From Wednesday (DRAFT: staged by Wednesday's brief drafter 2026-10-08 ~16:3x AEDT, NOT sent, NOT launched)

## BLUF
- **Seat number derived, not counted:** E 10th's handover opens "FOR E 11th, THE FIRST THREE THINGS" (`5_Project_History/HANDOVER-seatE10-2026-10-07.md:3`; 248 lines, sha256/16 `e7bb132c8848d3a7`, drafter); history.md's newest E entry is E 10th (`:210`). E 10th's two PRs are MERGED since: #1408 (KS-1435, squash `2c27ddfeef51`) and #1410 (KS-591 custody, squash `3d570510bdb3`) (census + `git log`, P2).
- **develop = `0a6177ea5482227e83d5045b68b8577a56326ffc`** (read 05:12:22Z and 05:26:15Z, unmoved). Peter merges in bursts: re-read before EVERY ref decision.
- 🔴 **THE YAML COMPANIONS ARE A TRAP: NEVER `git apply` ONE.** Each openapi pass ships an `openapi-yaml.companion.diff` (`local-model/night/briefs/<brief>/`) cut against YAML blob `52310cab1`; develop's YAML is `146bae7edb87` (+87 lines since: #1394 and #1410). Their hunks carry GENERIC context (`security / bearerAuth / requestBody: / content: / application/json:`), so `git apply` lands them by offset search on the NEAREST matching operation. **The drafter measured 5 of 12 landing `required: true` on the WRONG operation at `0a6177ea`, every one rc 0** (P4): `KS-1364 billing-credits-use` -> `post /api/billing/admin/credits` (the one REVIEW says stays OPEN as a contract decision) instead of `post /api/billing/credits/use`; `KS-591 platform-tenants-create-status` -> `delete /api/platform/tenants/{id}` instead of `patch …/{id}/status`; `KS-591 transfer-delegation-posts` -> `post /api/timestamps/verify` instead of `post /api/transfers`; `KS-1364 apigw-batch-certify-delegate` -> `post /api/batch/verify` instead of `post /api/batch/delegations`; `KS-1364 nft-ipfs-pin-unpin-size` -> `post /api/nft/ipfs/upload` instead of `post /api/nft/ipfs/unpin`. **8 of 12 companions also RE-APPLY cleanly on top of themselves** (the re-apply control cannot fire). **The YAML is GENERATED** (`Blockchain/Dev/scripts/generate-openapi.ts:1-19`, npm `generate-openapi` / `check:openapi`, `Blockchain/Dev/package.json:42`, `:48`; the preflight runs `check:openapi`). So: apply the `.ts` payloads, run `npm run generate-openapi`, and PROVE the YAML diff (QUEUE E, YAML PROOF).
- **THREE OTHER SEATS LAUNCH BESIDE YOU.** Your payload files are disjoint from theirs (P5); the two platform docs are SHARED-APPEND for all four. Mail naming R 18th, G 4th or F 5th is not yours.
- **This is a 12-pass, 3-PR seat. Expect 1-2 raises, then E 12th.** That is planned.

## NOT IN YOUR QUEUE — written so you do not improvise
- E 10th's E3 (KS-1432) and the second tenant pass `KS-591 platform-tenant-id-uuid`: **REVIEW-held, not raised by anyone this round.** The tenant pass shares `tenant-provisioning.openapi.ts` with your `platform-tenants-create-status`; when it is reviewed it comes to the E lane, stacked.
- R 18th's files (trivy job + suites, `api-gateway/src/routes/{notifications,batch,audit-export}.ts`, `smoke-test.sh`), G 4th's (`originate/src/routes/*`, the ks1293 hermetic list, `ks593-*`, `ks1171-*`), F 5th's (`run-migrations.sh`, `stack_guard.sh`, `kyc` `db.retry.test.ts`).
- #1383 HELD; KS-1250 never; a GO of any kind = mail the mismatch.

## FOR E 11th, THE FIRST THREE THINGS (E 10th's handover `:3-24`, adjusted by the drafter for this round; the tool wins)
1. **E 10th's next row (E3, KS-1432) is NOT yours this round** (REVIEW-held). Your queue is QUEUE E below.
2. **Two worktrees STAY and both are E 10th's: `s-e9-ks1435` and `s-e10-ks591c`.** Their PRs (#1408, #1410) are MERGED, so their bases are stale for you. **Recommend: cut FRESH `s-e11-*` worktrees and adopt neither** (Q-E10WT18); your namecheck will read them FOREIGN, which is correct. Their removal is drive hygiene for Wednesday to route, not yours.
3. 🔴 **`commite4.sh` carries E 10th's four fixes, and its `LOCK_SEAT` gate (`:58`) is `*" e10")`: re-key it to `e11` or every commit is REFUSED.** Its STAGE step now stages "TRACKED or PRESENT ON DISK" paths (E 10th TOOL NOTES 2): **your PRs carry 11-27 paths each, far more than E 10th's five** — re-read the stage list logic and drive it with a planted absent path before the first commit; `git add --` on an unmodified path returns rc 0 and stages NOTHING.
- 🔴 **Your matcher's forward-add is LIVE:** the PARSED `OTHER_SEATS` (`inbox_matche4.py:209`, 163 entries) contains `"e 11th"`; `MINE` (`:102`) is `'e 10th'` (drafter, `ast`, P7). REMOVE `e 11th`/`seat e 11th`; ADD `e 10th`/`seat e 10th`; FORWARD-ADD `e 12th`/`seat e 12th`; set `MINE` to `e 11th` preserving the quote char. **Parallel-seat arms:** the parsed set holds NEITHER `r 17th` nor `r 18th`, nor `g 4th`, nor `f 5th`: ADD all four (+ `seat …` forms) and drive the real tagger on `[Wednesday -> Secuura/Blockchain-R] GO (Seat R 18th): …`, `… -G] ANSWER: plan (Seat G 4th)`, `… -F] ANSWER: plan (Seat F 5th)` and the UNSUFFIXED `[Wednesday -> Secuura/Blockchain] ANSWER: plan (Seat R 18th)` -> FOREIGN; your own `[Wednesday -> Secuura/Blockchain-E] ANSWER: plan (Seat E 11th)` -> FOR ME; an addressee in NEITHER list (e.g. `(Seat E 19th)`) -> UNKNOWN ADDRESSEE (STANDING_LINES `:412`, `:414`). Prove by `ast` AND by import, never by grep.
- **`namechecke4.py` had SIX MINE-side fixtures keyed to the predecessor last round** (`:815 :819 :824 :864 :903`, predicate `:1061` + print `:1072`): move predicate and printed subject in the SAME edit. Add the `ra` lane through `ra18`, `g4`, `f5` to its foreign set with anchored forms (a bare short token like `g4` matches inside hex: STANDING_LINES `:359`, `:365`).
- **E 10th's other traps (`:178-248`) bind:** a vacuous tamper arm on a scratch tree missing `support/html_docs_check.mjs`; a heredoc after `|| exit 1` never runs; `twolocke4.sh:53` carries the generation token; read the CODE, not the brief, before mailing a reading.

## THE PARTITION, FROM BOTH SIDES (raise round after KS-1450; drafter's measurement at develop `0a6177ea5482`, P3-P5)
**Four seats launch in parallel on ONE checkout and ONE inbox (`secuura-blockchain@agentmail.to`).** Pane ids are assigned at launch: Wednesday writes each `%id` into the SEND AMENDMENT. A mail whose subject names another seat is NOT yours, even on your own pane tag.

| Seat | Pane (id at launch) | Lane token / lock | PAYLOAD files (repo-relative; `Dev/` = `Blockchain/Dev/`, `svc/` = `Blockchain/Dev/services/`) | PRs expected |
|---|---|---|---|---|
| **R 18th** | `Secuura/Blockchain-R` (`%<id at launch>`) | `ra18` / `.push-lock-d8` | `Blockchain/Testing/jobs/04-container-trivy.sh` · `Dev/scripts/__tests__/container_trivy_{failed_scan_is_loud,exit_code_env_keeps_findings,image_filter}.test.sh` · `svc/api-gateway/src/routes/{notifications,batch,audit-export}.ts` · `svc/api-gateway/src/__tests__/ks1410-*.test.ts` (2 NEW) · `Dev/scripts/smoke-test.sh` · `Dev/scripts/__tests__/smoke_test_counters_survive_errexit.test.sh` (NEW) | 3 |
| **E 11th** | `Secuura/Blockchain-E` (`%<id at launch>`) | `e11` / `.push-lock-e4` | `Dev/docs/openapi/secuura-api.yaml` (REGENERATED, never hand-applied) · `svc/{anchoring,billing,tenant-provisioning,staking,transfer,analytics,originate,m365-integration,api-gateway,nft-certificate}/src/<svc>.openapi.ts` (10 files) · 12 NEW `svc/<svc>/src/__tests__/ks591-*` / `ks1364-*` body-required tests | 3 |
| **G 4th** | `Secuura/Blockchain-G` (`%<id at launch>`) | `g4` / `.push-lock-g1` | `svc/originate/src/routes/{adminConfig,documents,signatories}.ts` · `svc/originate/src/__tests__/ks1293-originate-suite-is-hermetic.test.ts` (EDIT) · 3 NEW `svc/originate/src/__tests__/ks593-*.test.ts` · NEW `svc/anchoring/src/__tests__/ks1171-b1-absent-boundary-is-inclusive.test.ts` | 2 |
| **F 5th** | `Secuura/Blockchain-F` (`%<id at launch>`) | `f5` / `.push-lock-f3` | `Dev/scripts/run-migrations.sh` · NEW `Dev/scripts/__tests__/ks808_run_migrations_counts_skips_apart.test.sh` · `Dev/scripts/stack_guard.sh` · `Dev/scripts/__tests__/stack_guard.test.sh` · `svc/kyc/src/__tests__/db.retry.test.ts` | 3 |

- **Measured disjoint** (drafter, P5): every pair of seats shares **0** payload files (6 pairs), with the docs pair as the positive control that reads non-empty for every seat. Same-directory neighbours are NOT a collision but are named so nobody "tidies" across the line: `svc/anchoring/src/__tests__/` (E: `ks591-anchors-…`, G: `ks1171-…`), `svc/originate/src/` (E: `originate.openapi.ts` + `ks1364-share-system-errors-…`; G: `routes/*` + `ks593-*` + the ks1293 hermetic list), `svc/api-gateway/src/` (R: `routes/{notifications,batch,audit-export}.ts`; E: `api-gateway.openapi.ts`), `Dev/scripts/` (R: `smoke-test.sh` + trivy suites; F: `run-migrations.sh`, `stack_guard.sh`).
- 🔴 **THE ONE FILE PAIR EVERY SEAT SHARES — by rule, not by choice:** `Projects Documents/API_Security_Functional_Testing_Architecture_Flow_Diagrams.html` and `Projects Documents/QA_Tool_Cheat_Sheet_Secuura_API_Testing.html`. SKILL §4 (`.claude/skills/secuura-test-discipline/SKILL.md:360-363` at develop) puts BOTH in the SAME commit as every test change, so no partition can make them disjoint. **They are SHARED-APPEND:** each PR appends ONE flow block and ONE cheat section at the tail, never edits an existing block (`docblockra3.py`'s byte-for-byte read-back), and uses ONLY the flow number Wednesday allocated to it below. Every PR is cut from its seat's RAISE_BASE independently, so all PRs in this round append at the SAME tail (flow `26.`, cheat `KS-1164`, read at develop `0a6177ea5482`): **keep-both merge-ins at merge time are EXPECTED and are Wednesday's to sequence, not a partition failure.** A collision on a NUMBER is a STOP (Q-N5).
- **Flow-number allocation (drafter's PROPOSAL, Q-NUM18 — the SEND AMENDMENT rules it):** `32.` stays RESERVED for KS-1432 (E 10th's E3, now REVIEW-held). R 18th: `35.` KS-1274, `36.` KS-1410, `37.` KS-1139 (Q-N10 / Q-N1139, carried). E 11th: `33.` KS-591, `34.` KS-1364 (E 10th's reservations), `38.` KS-1449. G 4th: `39.` KS-593, `40.` KS-1171. F 5th: `41.` KS-808, `42.` KS-1355, `43.` KS-1328. At develop: 30 numbers, 0 duplicates, tail `… 25 30 31 26`, `32`-`45` ALL absent (P3).
- **Locks:** the four lane locks are pairwise distinct and are already each other's declared WAIT set in the inherited R and E tools (`{56, f3, g1, d8, e4}`, E 10th handover `:185`). **Re-assert in YOUR lock AND push tools that the WAIT set holds the other three seats' locks and not your own.** 0 `.push-lock-*` under `worktrees/` at drafting (maxdepth 1; a planted scratch `.push-lock-ZZTEST` read 1 through the same `find`, P6).
- **Never touch, any seat:** `s-ra14-ks1274` (R 14th's build; R 18th READS it only), `s-ra16-ks1450`, `s-ra13-*`, `s-ra3-*`, `s-ra4-*`, `s-e9-ks1435`, `s-e10-ks591c`, `s-g3-advlock`, `s-f2-ks1401`, any `s-d*`, `s-b*`, `s-c*`, `s-l*`, any other seat's lock, mail, records or pane. **#1383 (KS 1401) is HELD** (docs-only overlap with every PR here). KS-1250 is Kam's: NEVER raised. The D lane is not in this round (deploy lane; never demo, kintsugi or any deploy script).
- **REVIEW-held, in NO seat** (Q-REVIEW18): KS-865-r2, KS-948-r3, KS-1355 dev-reload-r2, KS-1432, KS-591 platform-tenant-id-uuid. 🔴 The last one shares `svc/tenant-provisioning/src/tenant-provisioning.openapi.ts` with E 11th's `platform-tenants-create-status`: when it is reviewed it goes to the E lane, stacked, and nowhere else.

## ITEM 0 — BOUNDED, read-only; then `QUESTION: plan confirmation (Seat E 11th)` and WAIT for the ANSWER
Before the ANSWER, NONE of: lock take, objects transfer, worktree add, ref write, install in a project worktree, ticket write, comment, PR create or edit. You MAY write in your record folder `5_Project_History/<UTC boot date>_seatE-11th/` and YOUR scratch clone.
- **(a) Refs:** `ls-remote` develop; every `-e11-`/`-e12-`/`-ra18-`/`-g4-`/`-f5-` branch with the controls `-e10-` = 2 (`…-e10-1`, `…-e10-2`) in the same call; highest `refs/pull`; `date -u`.
- **(b) Doc tails at develop** by BLOB HASH (flow `576a4687c995`, cheat `3481baae3dd9`, P3) with document-shaped controls: flow 30 numbers, tail `… 31 26`, `32`-`45` absent; cheat 19 sections, tail `… KS-591 KS-1164`. **Also the KEY COUNTS that decide Q-DOCKEY18:** `KS-591` occurs 2× in the flow doc and 2× in the cheat doc, `KS-1364` 0× / 1×, `KS-1449` 0× / 0× (drafter `grep -o | wc -l`, controls `KS-1164` 4 / 3).
- **(c) Payloads:** the 12 `out.md.checker/patch.diff` re-hashed against QUEUE E, each strict at develop (forward rc 0, reverse rc 1, per section), each PR's group stacked in both orders, the 12-stack (drafter `4080373dee39` both orders, the YAML companions included — but see the YAML trap: that tree is NOT the target). **The YAML landing table** for all 12 companions (intended op vs where `git apply` lands it), reproducing the drafter's 5 mismatches — that is your positive control that the trap is real.
- **(d) Tools:** copy receipt vs the TOOLS table; THE SWEEP; re-key (generic clause first); membership by `ast` + import; the parallel-seat arms; provenance arms if your toolset carries a provenance checker (if not, say so). Re-key the watcher and matcher FIRST and arm the watcher.
- **(e) Shared store, read verbs:** `rev-parse --all` count + sha; locks by holder `seat`, two polls, planted control; `cat-file -t` develop + `deadbeef`; `s-e*` on disk (drafter: `s-e1-ks1005`, `s-e10-ks591c`, `s-e2-ks1210`, `s-e3-ks938`, `s-e9-ks1435`).
- **(f) Seat facts:** `$TMUX_PANE` + cockpit name + ancestry; watcher pid from a ps FILE; `df -m`; launcher warnings VERBATIM; `WED_USAGE_STOP`; boot pull ran or READ-ONLY.
- **(g) Linear, read-only:** KS-591, KS-1364, KS-1449 (state, assignee, newest comment), fabricated-key control in its own query.
**Budget: mailed by ~25% ctx.**

## QUEUE E — RAISE_BASE, THEN THREE PRs (one at a time; ONE local commit per PR; each ends at READY FOR QA)
**On the plan ANSWER and a ctx reading < 45%:** `STATUS: raise base (Seat E 11th)` with develop's 40-hex, the doc tails and key counts, the 12 strict applies, the YAML landing table, the objects result (recorded no-op or ONE objects-only transfer under `.push-lock-e4`). **Hold for acceptance BY NAME.**
**Payloads** (`/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/local-model/runs/spark_secuura_<run>/out.md.checker/patch.diff`; drafter `wc -c` + `shasum -a 256 | cut -c1-16`; per-section strict forward rc 0 / reverse rc 1 at `0a6177ea`; tree by `write-tree` of the payload alone, NO YAML; P4) and the operations each must flip to `requestBody.required: true` (read from the companion against ITS OWN base blob `52310cab1`, P4):
| PR (flow) | run (`spark_secuura_…`) | bytes, sha256/16 | tree at `0a6177ea` | YAML ops it must flip (the ONLY ones) | READY in `night/` |
|---|---|---|---|---|---|
| **E-A KS-1449 (`38.`)** | `2026-10-05_KS-591-nft-mint-upload-fee` | 4,488 `0e1e9fff6da681ea` | `003ac7f43d70` | post /api/nft/mint · post /api/nft/ipfs/upload · put /api/nft/admin/platform-fee | `READY_KS-591-MINTUPLOADFEE-1_…_2026-10-08` |
| | `2026-10-05_KS-1364-nft-ipfs-pin-unpin-size` | 4,456 `ec4027fd2ec5b236` | `2994018ca8e8` | post /api/nft/ipfs/pin · post /api/nft/ipfs/unpin · post /api/nft/metadata/estimate-size | `READY_KS-1364-IPFSPINUNPIN-1_…_2026-10-08` |
| **E-B KS-591 (`33.`)** | `2026-10-05_KS-591-anchors-post-thread-mint` | 3,764 `4a5d142b7b42d88b` | `5f55f07bfb6e` | post /api/anchors · post /api/anchors/thread-mint | `READY_KS-591-ANCHORSPOSTTHREADMINT-1_…_2026-10-08` |
| | `2026-10-05_KS-591-billing-customers-bundle` | 4,145 `4f11747d45815f69` | `6ff089502094` | post /api/billing/customers · post /api/billing/checkout/bundle | `READY_KS-591-BILLINGCUSTOMERSBUNDLE-1_…_2026-10-08` |
| | `2026-10-05_KS-591-platform-tenants-create-status` | 3,931 `59d5a7494a4b5dfa` | `0bbe8148f633` | post /api/platform/tenants · patch /api/platform/tenants/{id}/status | `READY_KS-591-PLATFORMTENANTSCREATESTA-1_…_2026-10-08` |
| | `2026-10-05_KS-591-stake-complete-unstake` | 2,931 `d2be46c54029d6ad` | `28309f75e513` | post /api/stake/complete-unstake | `READY_KS-591-STAKECOMPLETEUNSTAKE-1_…_2026-10-08` |
| | `2026-10-05_KS-591-transfer-delegation-posts` | 4,915 `6e5c24ec038351a6` | `b53857cdcc41` | post /api/transfers · post /api/delegations · post /api/delegations/validate | `READY_KS-591-TRANSFERDELEGATIONPOSTS-1_…_2026-10-08` |
| **E-C KS-1364 (`34.`)** | `2026-10-05_KS-1364-analytics-exports-r4` | 3,216 `01d9871acdf82534` | `ebc82e99ba40` | post /api/analytics/exports | none (never held: Q-HOLD18) |
| | `2026-10-05_KS-1364-billing-credits-use-r4` | 2,676 `1a56b9d2758c41f2` | `6890964e63fd` | post /api/billing/credits/use (**NOT** `/api/billing/admin/credits`) | none (Q-HOLD18) |
| | `2026-10-05_KS-1364-originate-share-system-errors` | 4,531 `a8db2535d43a011d` | `33c2c00253ba` | post /api/documents/{id}/share · post /api/system-errors/ingest · post /api/system-errors/resolve-by-service | `READY_KS-1364-ORIGINATESHARESYSTEMERRO-1_…_2026-10-08` |
| | `2026-10-05_KS-1364-teams-webhook-notify` | 4,474 `7b626312b7122ba8` | `ab79115b8baf` | post /api/teams/webhook-config · post /api/teams/notify | `READY_KS-1364-TEAMSWEBHOOKNOTIFY-1_…_2026-10-08` |
| | `2026-10-06_KS-1364-apigw-batch-certify-delegate` | 3,794 `e0ca095d8b0f7107` | `61658d188d31` | post /api/batch/certifications · post /api/batch/delegations | `READY_KS-1364-APIGW-BATCH-CERTIFY-DELEGATE-1_…_2026-10-06` |
- **Stacks (drafter, P4):** E-A 4 patches (2 payloads + 2 companions) `4150c9f1adf5` both orders; E-B 10 patches `a36fe62024c0` both orders; E-C 10 patches `f0b4c8986bc8` both orders. **These trees include the git-applied companions and are therefore NOT the targets**; they prove only that the `.ts` halves compose. Your target tree is payloads + the GENERATED YAML + the two doc blocks.
- **Shared files inside your seat:** `billing.openapi.ts` (E-B billing-customers-bundle + E-C billing-credits-use), `nft-certificate.openapi.ts` (both E-A passes), `secuura-api.yaml` (all three PRs). Each PR is cut from RAISE_BASE independently (lane convention); disjoint hunks in one file merge cleanly in git, and the YAML of the later-merged PR is REGENERATED in its merge-in, never hand-resolved.
- **Drifted product files (offset applies, drafter-checked):** `anchoring.openapi.ts` changed since the Spark tip (`5d0a1b9eb19b` -> `b18bb656f3e7`, #1394): hunk 2 of anchors-post-thread-mint lands at offset 43 on `ThreadMintRequestSchema` (correct). `originate.openapi.ts` changed (`62234903ea15` -> `2be63a792ead`, #1410/#1422): hunks 2-3 of originate-share land at offset 3 on `/api/system-errors/ingest` and `/resolve-by-service` (correct). Re-check on YOUR worktree with `git apply -v` and name every offset.
- 🔴 **YAML PROOF, per PR (the ruled shape is Q-YAML18):** in the worktree after the `.ts` apply: `npm ci --ignore-scripts` + build `packages/shared` (asserted), then `npm run generate-openapi` in `Blockchain/Dev`; then a STRUCTURAL reader (parse base and head YAML; compare every `paths[p][m].requestBody.required`) must show **exactly** this PR's op set flipping to `true` and NOTHING else changing — print the count checked, the set, and the full-document diff size. **Controls:** (1) a scratch copy with the real companion `git apply`-ed for one of the five MISLANDING rows must FAIL the reader (wrong op) — that is your firing control; (2) `npm run check:openapi` rc 0 on your head and rc 1 on that scratch copy. **Never hand-edit the YAML; never commit a companion.**
- **Per-PR notes from the REVIEWs (each `REVIEW.md` in the run dir; read each whole):** every row: `Refs` its ticket, **do not close it**, "commit from a real `git diff`, add the regenerated YAML, run `check:openapi`". E-A carries `Refs KS-1449` (the spec half; the runtime half needs a live sweep), KS 591 / KS 1364 de-hyphenated (Wednesday's note, appended to both nft READYs `:121`/`:123`). `billing-credits-use`: `POST /api/billing/admin/credits` stays OPEN as a contract decision — say so. `transfer-delegation-posts`: its REVIEW says "Refs KS-591 and KS-1364": **one `Refs` only** (Q-REFS18). `teams-webhook-notify`: does not address KS 784 (the 503). `originate-share`: the three handlers' 400 on an absent body is READ, not driven. All: no Schemathesis run; the served `/api/docs` not read.
- **Tier:** rec **TIER 2** for all three (product bytes change in the published contract; every READY says "AT LEAST tier 2"). Live sweep owed; the tickets do not move to Done.
- **Doc blocks:** `docblockra3.py` REFUSES a `--new-key` that already occurs in either doc (`:83-84`, `:138-139`; it exits 2), and `KS-591` (2/2) and `KS-1364` (0/1) already occur. **E-A (`KS-1449`, 0/0) is unaffected and goes FIRST.** E-B and E-C wait on Q-DOCKEY18.
- **Per PR mechanics:** E 10th's QUEUE shape with your re-keyed tools: ctx QUESTION before each build; `git worktree add --detach /Volumes/DevMASTER/!CODING/Secuura/Blockchain/worktrees/s-e11-<slug> <RAISE_BASE>` under the lock, never `-b`; S-1 installs; strict apply with `--check` first, `cmp` vs payload; each service's suite through ITS OWN npm script, RED at base / GREEN after per pass, whole-suite no new reds (name the pre-existing `threadTokenMint` red in anchoring, KS-562, if it appears); YAML PROOF; doc blocks; `commite4.sh` (re-keyed) 0 trailers vs a non-zero control, subject <= 92 as it LANDS; pathgate with a firing control; **before the PUSH: `QUESTION: ctx read (Seat E 11th)`**; push ONCE with your push tool BARE (`env -u GIT_SSH_COMMAND`); result = the tool's `.rc` + `ls-remote` + the API; quote THAT push's gate lines; raise by REST (HTTP 201, head == origin, body sha256 read back). Branches `feature/ks-<n>-<slug>-e11-<k>`, IN FULL in every mail.

## PR BODIES (written by YOU, who ran the tests; QUOTED heredocs)
- `Refs KS-NNNN` + its Linear URL; "Raised from Wednesday-held Spark passes (list each run dir), re-proved by Seat E 11th on develop `<12-hex>`." Name each pass's operation set, the YAML PROOF numbers, and that the YAML was REGENERATED (not the Spark companion, which mislands at this develop). Test Evidence per pass (node / npm / vitest versions READ from `node_modules`; red/green counts YOU ran). The platform suites UNMEASURED. NARROWING: each PR covers N of the ticket's operations; the rest OPEN.

## TOOLS (copy from `5_Project_History/2026-10-07_seatE-10th/raise/`; iterate an ARRAY; hash into `_COPY_HASHES_e11.txt`; `cmp`; compare to THIS table — a different hash is a STOP and a mail)
Drafter (`shasum -a 256 | cut -c1-16`, newline count; == E 10th's handover table where it lists them, P7): `inbox_matche4.py` `b538371588d22986` (546) · `inbox_watche4.sh` `53463a6f1c970fd9` (159) · `namechecke4.py` `12913dede1a1091a` (1089) · `restraisee7.py` `1375dfeec54dfc10` (70) · `twolocke4.sh` `bb10478135b3ce8e` (261) · `commite4.sh` `9e08f8409b03d8d3` (206) · `locke4.sh` `7a1291f3280d0722` (622) · `pushe7.sh` `7202eb3fe814e007` (254) · `pathgatee4.py` `5a1feeb2338c6115` (138) · `gatelinese4.py` `b5e7923f605af9da` (73) · `keyscane4.py` `e85a0c6e624087c9` (56) · `h2reade7.py` `11680bb470b4a578` (66) · `docblockra3.py` `c4827645b53bce19` (168) · `split_sections.py` `1137163a37027609` (25) · `sendguarde7.sh` `efcb1da71c2da9c4` (11).
- **Re-key: the generic clause binds** (every lane-bearing declaration incl. `LOCK_SEAT` gates, fixtures, BRANCHES/SUBJECTS row tables, env prefixes, banners); THE SWEEP before ANY first run (two-digit ordinals; `e1` is a prefix of `e10`/`e11`); `0 checked` is a FAIL; positive control FIRST.

## PARALLEL-SEAT STANDING BLOCK (verbatim from `0_Brain/learnings/2026-09-09_parallel-seats-on-one-project-grant.md:86-91`, sha256/16 `eb5ca4263e5f5f48`; it is NOT in `fleet/STANDING_LINES.md`, which carries no such block: see Q-SL18)
**The rule, extended — every parallel-seat brief on ONE checkout carries this STANDING BLOCK, verbatim, from both seats' sides:**
- **PUSH-WINDOW LOCK:** an advisory `mkdir` lock OUTSIDE every worktree (`<Project>/worktrees/.push-lock-<round>/`; `holder` file + a 60-s `heartbeat`); taken before `snapshot`, released after `verify` (the holder's rmdir is the one delete); the other seat makes NO ref write while it is held; a bounded wait (20 min) then STOP-and-mail; a stale lock (heartbeat > 5 min AND dead pid) is reported, never removed by the non-holder. Built into the push tool, not remembered.
- **ATTRIBUTION BY NAMESPACE, both conditions:** a foreign diff line is attributed to the other seat only when it matches the other seat's namespace by NAME (its `s-<seat>-*` worktrees; `feature/ks-<one of ITS keys>-…-r15-…`) AND origin holds my branch at my sha. Anything else is a STOP.
- **THE BOARD GUARD, same rule, four conditions:** a NEW attachment on the OTHER seat's key is attributed when the URL is a project PR ∧ its head ref is `feature/ks-<that SAME key>-…` ∧ the author is the board login inside the round ∧ the change is addition-only — where the ONLY tolerated state change is the bot's Backlog → In Progress walk coincident with the PR open. A guard condition enters a binding mail only after the round's own ordinary events (a PR open, the bot walk, a squash) have been put through it and the exception written ([[2026-09-08_a-new-rule-is-most-dangerous-just-after-adoption]]).
- **PROCESS NAMESPACE:** kills by ancestry (`ps -o pid=,ppid=` filtered on the seat's own claude pid) or by port + cwd, never a basename; long-running scripts carry the seat's suffix in their argv where the tooling allows.
- **Test by its handle:** for every resource the two seats SHARE — the inbox, `.git`, the process table, the board, the machine's load — name the instrument each seat uses to tell "mine" from "the other seat's" BEFORE the launch. A partition that names only the files has named one of five.
**How it binds THIS round (four seats, one checkout):** the push-window lock is your lane lock (table above), taken and released by your push tool in ONE invocation; "the other seat" means EACH of the other three. **Namespace by NAME:** the other seats' worktrees are `s-ra18-*`, `s-e11-*`, `s-g4-*`, `s-f5-*` and their branches end `-ra18-<k>`, `-e11-<k>`, `-g4-<k>`, `-f5-<k>` (minus your own). **Board guard:** the other seats' keys this round are KS-1274, KS-1410, KS-1139, KS-1450 (R) · KS-591, KS-1364, KS-1449 (E) · KS-593, KS-1171 (G) · KS-808, KS-1355, KS-1328 (F); a bot Backlog -> In Progress walk on another seat's key at its PR open is THEIR event. **Process namespace:** kill only by ancestry from YOUR claude pid; build `ps` patterns at runtime and exclude your own shell pid.

## USAGE AUTHORITY
- **Kam, 2026-10-08 ~14:3x AEDT, verbatim:** *"I have logged you into a new account. This resets tomorrow so feel free to use as much as you like. Push and merge what you can, test what you need to do as much as possible"* -> `0_Brain/learnings/2026-10-08_new-account-push-merge-test-as-much-as-possible.md`, clause **RAISE**. This seat launches with `WED_USAGE_STOP=100` naming that file.
- Gauge at drafting: **86%** (`usage_gate.sh --check` rc 0, gauge age 3 min, 2026-10-08 16:2x AEDT, P9). The 90% stop does NOT apply to this seat; **at 100%, WRAP COLD at the next safe boundary.** Expiry is an EVENT (the account's renewal ~Fri 9 Oct morning, an account switch, or Kam's word); never renewed by inference.
- **Unchanged by the grant:** the signature classes; the QA gate before every merge; **no merge, no gate and no deploy in this seat.**
- **Ctx lines (carried):** a build starts only under 45%; a push at 45-64% only on Wednesday's per-step word; **hard ceiling 65% -> WRAP COLD.** A seat cannot read its own context: mail `QUESTION: ctx read (<your seat>)` before every BUILD and every PUSH and hold for Wednesday's reading.

## HOLDS
- **Never `--no-verify`. Never force (Secuura never force-pushes: `.githooks/pre-push:46-70`). No `--admin`. No merge, no gate, no deploy**, no `az`, no SSH, no migration run, no Docker, no observability stack.
- **Signature classes pause for Kam:** production · money · external communication to any human · anything irreversible.
- **Client-facing communication is TICKET COMMENTS only, and this seat writes NONE** (Q-NOTIFY12 carried; the project notify rule `/Volumes/DevMASTER/!CODING/Secuura/Blockchain/CLAUDE.md:185` is met by a TEST BLOCK Wednesday batches: STANDING_LINES `:83`). Never the extranet, never `POST /api/seen`, never a message to Peter or Stuart. No board exception in this seat. (R 18th alone makes ONE board change this round, KS-1450 -> Done + one comment: that is ITS event under the board guard, not yours.)
- **Tickets:** a ticket on Peter or Stuart stays theirs. One ticket per TEST PASS (Kam 2026-09-07 13:23). File NOTHING in this seat; a finding goes to Wednesday as a QUESTION, after a board search by SYMBOL / path / error string, read by id.
- **After boot: no fetch or pull in the shared checkout; never write either develop ref** (the launcher's boot pull is the ONE recorded exception, and only if you are the sole live session; with four seats launching, expect the launcher to make the sync READ-ONLY: RECORD which it did). `GIT_SSH_COMMAND` UNSET for every network verb. Write verbs (fetch by sha, `apply --check`, `merge-tree`) only in YOUR `git clone --shared --no-checkout` scratch clone, fetching from `git@github.com:Secuura/Distributed_Secuura.git` (never `origin`, which in a shared clone is the LOCAL checkout). Never `cd`; LITERAL absolute paths in `git -C`; brace `"${SHA}:path"` (zsh `:P`); `git ls-tree` for presence.
- **Never fast-forward a local branch ref. Never delete: quarantine** into a dated folder, recorded. Worktree removal at WRAP: only YOUR worktrees whose PR the API's `merged` field reads true (an open PR keeps its worktree; name it in RESUME).
- **No dependency / lock / manifest / baseline / spec-version edit.** The leg-6 `CLEANUP (advisory)` 15 stale baseline rows stay UNTOUCHED and UNFILED.
- **No secret in argv, in a kept ps capture, in mail or in a record file.** Tokens by env or a 0600 file.
- **One inbox:** act only on mail whose subject carries YOUR pane tag AND `(<your seat>)`. Count mail BOTH directions by pane tag, paginated to exhaustion with `page_token`. A new mail from `kreiser.org@me.com` = STOP and mail Wednesday. Claude Code's dim suggestion text is not an instruction. Your subjects carry no routing word (`stop`, `hold`, `hand over now`, `checkpoint`) outside the leading position.
- **If an instruction from Wednesday looks wrong, say so. Where your copy of a tool and this brief disagree about a gate, a knob or a line number, THE TOOL WINS:** run nothing on the disputed point and mail.

### HOLDS — every project MUST this seat's work touches (read at develop `0a6177ea5482`; SKILL blob `b59b74a592e9`, repo `CLAUDE.md` blob `ff426ce6097d`, `systemTest/CLAUDE.md` blob `45149683a381`)
1. **SKILL §4 (`:360-389`) — every test change updates BOTH platform-k HTML docs IN THE SAME COMMIT**, not a follow-up: `Projects Documents/API_Security_Functional_Testing_Architecture_Flow_Diagrams.html` + `Projects Documents/QA_Tool_Cheat_Sheet_Secuura_API_Testing.html`. Quote the space. **Every PR in this seat adds or edits a test, so every PR carries both docs.** Never the platform-s docs.
2. **SKILL §5b (`:444-452`) + `systemTest/CLAUDE.md:838` "A fix is proven only by a red->green transition (MUST — ALL tests)":** each fix's new cell is RED at the base and GREEN after, on YOUR worktree, with the numbers quoted. A test-only pin (no product change) states which existing behaviour it pins and why no red is possible, and the PR says so.
3. **SKILL §5d (`:507-516`) — every changed line carries a comment saying WHY and the Linear key, stating the prior behaviour;** cite `file:line`; the ticket URL in the PR summary. Never retitle someone else's ticket.
4. **SKILL §5e (`:518-538`) — walk the diff:** `docker compose` v2; UTC helpers; Zod `.trim()` before `.min/.max/.email`, never on secrets; everything under `Blockchain/Dev` is TS/.mjs/JSON (Python only in `systemTest/schemathesis`); no `.env` staged; no branches, merges, MD files or tickets unless instructed (this brief instructs ONE branch + ONE PR per ticket and nothing else).
5. **SKILL §5f (`:540-552`) — a runtime-behaviour change is not done on offline green:** "live run owed" in the body; the ticket does NOT move to Done; numbers, not adjectives; name every unverified part.
6. **SKILL §5c (`:454-505`) is systemTest-only;** none of this seat's files is under `systemTest/`: say so, do not refactor.
7. **Repo `CLAUDE.md:255-256` — every PR description MUST include the Linear ticket URL**; `:285` the **Test Evidence** block (touched / ran / NOT run / migrations+config), written by you who ran the tests; `:296` never push straight to `develop`.
8. **Repo `CLAUDE.md:167-175` + `systemTest/CLAUDE.md:909-930` "No links to other organisations' issues or PRs in git metadata (MUST)":** read every commit message and PR body back for `github.com/` and `owner/repo#N` (owner not `Secuura`) before commit / create / edit.
9. **Repo `CLAUDE.md:209-226` slot MUSTs:** no per-slot literal (`6982`, `secuura-s2-…`) in code, tests or docs; a test that needs a slot value computes it from slot 1.
10. **Key hygiene (STANDING_LINES `:278`, `:296-297`):** the PR's OWN key hyphenated in `Refs KS-NNNN`, its URL and verbatim-quoted file content only (Q-KEYOWN14 carried); every FOREIGN key de-hyphenated in title, body and commit; **no two `Refs` in one PR** (the board guard, Q-BUNDLE); strict closing regex = 0 on each SENT body with a planted control that fires; 0 `Co-Authored-By`.
11. **READY FOR QA is an ARTEFACT (STANDING_LINES `:17-46`):** a PR number, its head read from origin in the same action, the Test Evidence block, and what was NOT done. (Item 3, the ticket comment naming the PR, is Wednesday's batch under Q-NOTIFY12: say so in the READY.)
12. **S-1 (STANDING_LINES `:429`), carried:** before ANY push from a worktree, `npm ci --ignore-scripts` in `Blockchain/Dev` + `npm run build --workspace=packages/shared` with `dist/index.js` ASSERTED, AND `npm ci` in ALL FOUR `systemTest/{akto,api-explorer,performance,playwright}`; assert 0 tracked files modified after. Run every package's tests through ITS OWN npm script (the `vitest.unit.config.ts` runner trap).
13. **The four platform suites** (Schemathesis, Akto, Playwright, Performance/k6) are UNMEASURED (no local stack): quote only the SKIP lines THAT push printed. **Never a pass.** `html_docs_matrix.test.sh` 12/0 is NOT evidence an appended block is well-formed (STANDING_LINES R 14th line): quote docblock's byte-for-byte read-back and tag counts.

## MAIL FORMATS (to `wednesday-agent@agentmail.to`; prefix `[Secuura/Blockchain-E -> Wednesday] `; every subject names `(Seat E 11th)`)
- `QUESTION: plan confirmation | ctx read | <topic> (Seat E 11th)`, one question per mail; body Context / Question / Meanwhile / Needed-by.
- `STATUS: raise base (Seat E 11th)`; `STATUS: pushed <branch IN FULL>, raised #<n> (Seat E 11th)` (head, THAT push's gate lines verbatim, both ref side effects, Actions on COMPLETED runs only), each with the LIVE watcher pid from a ps file (or "0 live", never an empty value).
- ONE `READY FOR QA (Seat E 11th): … -> <gate Wednesday names>` at the end, naming every UNRAISED row of your queue as UNRAISED.
- `WRAP (Seat E 11th): …` with the ps file showing 0 live watchers; the handover `5_Project_History/HANDOVER-seatE11-<date>.md` (sha256/16, `wc -c`) opening **"FOR E 12th, THE FIRST THREE THINGS"** (incl. your forward-add trap and the next sweep class as an EXPECTATION), a RESUME block naming the next item exactly and every built-but-unpushed / pushed-but-unraised branch IN FULL with its head, and a RECORD of every ref write; every lesson in the handover itself; the history entry at the TOP of `5_Project_History/history.md`, re-read immediately before writing, insert-only PROVED by strip-and-compare; UNMERGED / UNRAISED / UNMEASURED / UNFILED; `df -m` before/after; mail counted both directions; drive hygiene (GB freed); the tool hashes your successor inherits; "this seat = 1 Claude launch, clause: raise (carrying N Spark tasks)".

## UNMEASURED (with why, and the instrument that closes it)
- Whether `npm run generate-openapi` at `0a6177ea` is drift-free BEFORE your change (the drafter cannot run npm): your base run of `check:openapi`.
- Whether the generator emits `required: true` exactly where the `.ts` payload adds it, and nothing else: your YAML PROOF.
- RAISE_BASE, trees with the generated YAML, pushes, preflight legs, Actions: none exists.
- Open PR state (no API token): file overlap measured over `refs/pull/1300-1426/head` instead (P6); 0 open-looking heads touch your files.
- KS-591 / KS-1364 / KS-1449 states (no Linear access here). ITEM 0 (g).
- The runtime half of every pass (handlers' 400 on an absent body): no stack. Named in each body.

## RULED, STILL OPERATIVE (restate, do not ask)
Q-N5 (flow numbers UNIQUE, keyed by ticket; a collision is a STOP); Q-BUNDLE (one PR per ticket; no two `Refs`); Q-1410 precedent (several passes of ONE ticket in ONE PR); Q-SRC2 (raise from `out.md.checker/patch.diff`); Q-BASE10R (RAISE_BASE BY NAME); Q-OBJ13's transfer shape; Q-KEYOWN14; Q-NOTIFY12; E 10th's rulings on its own queue carried only where this brief does not supersede them (E3 KS-1432 is superseded: REVIEW-held).

## QUESTIONS (OPEN unless the SEND AMENDMENT rules them; each HOLDS only the item it names)
- **Q-PRSHAPE18 (HOLDS the first build):** **Recommend** one PR per TICKET (Q-BUNDLE + the Q-1410 precedent): E-A KS-1449 (2 passes), E-B KS-591 (5), E-C KS-1364 (5) = 3 PRs, 3 flow blocks. Against: E-B/E-C touch 7 and 6 services; one PR per PASS (12 PRs) would mean 12 doc blocks and 12 merge-ins. **Default:** recommended; E-A first.
- **Q-DOCKEY18 (HOLDS E-B's and E-C's doc blocks only):** `docblockra3.py` refuses `KS-591` and `KS-1364` (already present). **Recommend (a):** a re-keyed copy `docblocke11.py` with a REQUIRED `--key-count-before <flow>,<cheat>` knob replacing the zero-occurrence refusal (exact counts asserted before, +1 section after), proved with an arm that refuses a wrong count; the cheat sheet then carries a SECOND `KS-591` section (declared, so the next reader's 0-duplicates assert is expected to change). (b) key E-B/E-C on a distinct heading token. **Default:** (a); until ruled, build E-A only.
- **Q-YAML18 (HOLDS each PR's commit):** **Recommend** the YAML PROOF above (generate, structural reader, two controls). **Default:** as recommended; a companion is NEVER `git apply`-ed into a pushed worktree.
- **Q-REFS18:** `transfer-delegation-posts`'s REVIEW asks for "Refs KS-591 and KS-1364". **Recommend** `Refs KS-591` only (it rides in E-B), `KS 1364` de-hyphenated in words. **Default:** as recommended.
- **Q-HOLD18:** `analytics-exports-r4` and `billing-credits-use-r4` have a HOLD REVIEW but NO READY file (the pickup's "still to hold"). **Recommend** Wednesday writes both READYs (`hold_ready.py`) before send; the seat raises from `patch.diff` either way (Q-SRC2). **Default:** raise from the REVIEW + `checker.out`, naming the missing READY in the body.
- **Q-E10WT18:** **Recommend** fresh `s-e11-*` worktrees; `s-e9-ks1435`, `s-e10-ks591c` untouched and named in your WRAP. **Default:** as recommended.
- **Q-NUM18:** `33.` KS-591, `34.` KS-1364, `38.` KS-1449. **Default:** as proposed.

PROVENANCE:
- KS-591 (state, assignee, newest comment) | to be read by Wednesday at send | —
- KS-1364 (state, assignee; REVIEWs say "Wednesday confirms that no seat holds KS-1364" — #1365/#1368 await a live sweep) | to be read by Wednesday at send | —
- KS-1449 (state, assignee; the spec half of it) | to be read by Wednesday at send | —
- KS-784, KS-1015 (named de-hyphenated only) | to be read by Wednesday at send | —
- P1 develop `0a6177ea5482227e83d5045b68b8577a56326ffc` at 05:12:22Z and 05:26:15Z, 0 `-e11-`/`-ra18-`/`-g4-`/`-f5-` | `env -u GIT_SSH_COMMAND git -C "/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files" -c core.sshCommand=<the checkout's own> ls-remote git@github.com:Secuura/Distributed_Secuura.git` rc 0 (`raise18/lsr1.out`, `lsr2.out`) | read 2026-10-08
- P2 #1408 -> `2c27ddfeef51`, #1410 -> `3d570510b` (5 paths incl. `secuura-api.yaml` +1), #1394 -> `4eaf7741a` (`secuura-api.yaml` +86) | `git show --stat` in the drafter's scratch clone | read 2026-10-08
- P3 doc tails and key counts as in ITEM 0 (b) | `ls-tree` + `cat-file blob`, `raise18/bin/tails.py`, `grep -o | wc -l` | read 2026-10-08
- P4 per-section strict apply + whole-patch + re-apply control at `0a6177ea` (table); stacks; YAML landing: companion base blob `52310cab1` vs develop `146bae7edb87` (`+1 @ 6908`, `+86 @ 14462`); 12 companions applied alone at develop: 7 land as intended, 5 mis-land (listed in BLUF); 8 re-apply rc 0 on themselves; `where()` control discriminates (`post /api/billing/credits/use` vs `post /api/analytics/exports` at two known lines) | `raise18/bin/measure.py`, `stack.py`, `yamlwhere.py` | read 2026-10-08
- P5 cross-seat payload overlap 0 for all 6 pairs; docs control non-empty | `raise18/bin/partition.py` | read 2026-10-08
- P6 122 `refs/pull/1300-1426/head` fetched by sha into the drafter's scratch clone; only #1360 still forward-applies (0 overlap) | `raise18/bin/pulls.py` (`pulls_overlap.txt`) | read 2026-10-08
- P7 E-lane tool hashes (table) and the matcher by `ast`: `MINE` `'e 10th'` `:102`; `OTHER_SEATS` `:209`, 163 entries, `e 11th` True, `e 10th` False, `r 17th`/`r 18th`/`g 4th`/`f 5th` False, `g 3rd`/`f 4th` True | `raise18/bin/lanetools.py` (`lanetools.out`) | read 2026-10-08
- P8 REVIEW.md "For the raise" sections of all 12 passes read; `generate-openapi.ts:1-19`; `package.json:42,48`; `preflight_deps.test.sh:92-95` (preflight runs `check:openapi`) | `sed -n`, `git grep` at `0a6177ea` | read 2026-10-08
- P9 weekly usage 86% | `usage_gate.sh --check` rc 0 | read 2026-10-08 16:2x AEDT
SELF-CHECK: re-read end-to-end for contradictions | @FILL@
