#!/usr/bin/env python3
"""gen_launcher_1019r2.py — derive launch_qa_secuura_ks1187_1019r2.sh from launchers/launch_qa_secuura_ks1187_1019.sh (the #1019 ROUND 1 launcher, itself generated by
gen_launcher_1019.py) by ASSERTED substitutions: every anchor must occur exactly as often as stated, or the generator refuses and writes nothing. Re-points at #1019
(KS-1187) ROUND 2 (a delta): head 82f09c8bd (a merge of develop f8c7aaa39 into the round-2 commit 4d551f104, parent 8b8996f8b) / merge-base = develop f8c7aaa39
(now an ANCESTOR of the head): compare develop...head = merge_base f8c7aaa39 ahead 4 files 3 (behind NOT asserted). The develop arm keeps round 1's CONTENT
judgement, re-pinned at f8c7aaa39: #1017's five files are now DEVELOP's own blobs (d7e95cd9f squash) and DEV_CONTENT_ALLOWED is EMPTY; LANDED (exit 19) takes the
round-1 OR round-2 PR blobs; config/services.ts (the suspicious-path pattern brief item 4 reads) is judged too (21 files); proxy.ts region judgement unchanged (develop's
proxy.ts is still b99f45a4c, region sha re-computed = the round-1 WANT). Round-2 exits: 15 ROUND 2; 23 the ROUND 2 subject; 24 + the ROUND-1 REPORT in brief AND prompt;
25 + CLOSED / STILL OPEN / NEW in brief AND prompt. Test hooks renamed QA1019R2_*. Then a RESIDUAL GUARD, output controls, heredoc parity, no git write verb, no control
bytes, bash -n. Never overwrites an existing output (writes a .pre-* copy first).
Usage: gen_launcher_1019r2.py <template launcher> <output launcher>
Exit: 0 written · 1 an anchor/control count disagreed · 2 a residual token survived · 3 bash -n failed"""
import hashlib, os, re, shutil, subprocess, sys
TPL, OUT = sys.argv[1], sys.argv[2]
GS = os.path.dirname(os.path.abspath(__file__))
s = open(TPL).read()
def now(f='+%Y-%m-%d %H:%M:%S %Z'): return subprocess.run(['date', f], capture_output=True, text=True).stdout.strip()
print('gen_launcher_1019r2', now(), '| template sha256', hashlib.sha256(s.encode()).hexdigest()[:16], 'lines', s.count('\n'))
def cut(start, end_incl):
    assert s.count(start) == 1, ('cut start', start[:50], s.count(start))
    i = s.index(start); j = s.index(end_incl, i) + len(end_incl); return s[i:j]
# region WANT re-computed from develop's proxy.ts (src/D.routes_proxy.ts, git blob asserted b99f45a4c) with the template's own SEGS
dev_px = open(GS + '/src/D.routes_proxy.ts', 'rb').read(); assert hashlib.sha1(b'blob %d\0' % len(dev_px) + dev_px).hexdigest().startswith('b99f45a4c')
SEGS = [["import { CircuitBreaker } from '@secuura/shared';", "// Factory"], ["  const erasureDoor = Router();", "proxy('originate', { '^/api/gdpr': '/api/gdpr' }),"]]
t = dev_px.decode(); parts = []
for a, b in SEGS:
    assert t.count(a) == 1 and t.count(b) == 1; i = t.index(a); j = t.index(b); parts.append(t[i:j + len(b)])
WANT = hashlib.sha256('\n@@SEG@@\n'.join(parts).encode()).hexdigest(); print('region WANT from develop proxy.ts', WANT)
assert s.count(WANT) == 1, 'the round-1 WANT differs from develop f8c7aaa39 region sha — re-derive, do not carry'
REPORT_DIR = '/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019r2-82f09c8bd-tier1-r2/'
R1_REPORT = '/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019-8b8996f8b-tier1-r1/'
HEADER_OLD = cut('# launch_qa_secuura_ks1187_1019.sh', "# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused\n")
HEADER_NEW = """# launch_qa_secuura_ks1187_1019r2.sh — cross-project QA agent, ONE TIER 1 ROUND 2 DELTA gate (round 2 of 2 under the cap) over Secuura/Blockchain PR #1019
# (KS-1187, Seat A) @ 82f09c8bd1bfab28e4d23c180cbaffea251685be — round 1 (head 8b8996f8b) was NO GO on F-1019-1: the canonical door verdict popped the door segment
# for a dot segment after it (erasures/..), judged not-door, and the gateway forwarded the RAW path that originate routes to /erasures/:externalRef. The round-2 commit
# 4d551f104 (parent 8b8996f8b): routes/proxy.ts +13 -3 (erasureDoorVerdict answers undetermined for any . or .. segment once the resolved first segment names the door,
# under the door router case rule), the ks1187 test +148 (31 new cells: dot verdicts, real-app test + production, F-1019-2 case-sensitive router, F-1019-3 restore).
# 82f09c8bd = a merge of develop f8c7aaa39 (#1017 squash d7e95cd9f + #1020 squash) into 4d551f104; no file overlap. TIER 1: an authorisation door on a GDPR erasure
# route. ROUND 2 of 2 is the CAP: a NO GO ships the closed instances and tickets the residue.
#
# THE SHAPE, as read 16:44-16:51 AEST 2026-09-17 (git ls-remote x3 + the PR, compare and contents APIs agree): develop f8c7aaa39 is the head merge-base AND an ANCESTOR
# of the head, so compare develop...head = merge_base f8c7aaa39, ahead 4, behind 0, files 3 (asserted as merge_base + ahead + files, exit 10; behind NOT asserted).
# Merged tree over develop = the head tree 99df1503e (= merge-tree 4d551f104 x f8c7aaa39 in the drafter clone = the seat's prediction).
#
# The develop pin is judged by CONTENT, not bare: (a) TWENTY-ONE files by blob at the CURRENT develop — the PR's three (proxy.ts b99f45a4c, the ks843 scope-gate test
# a3c554121, the ks1187 test ABSENT; at their round-1 OR round-2 head blobs -> exit 19 LANDED), #1017's five at their develop blobs (d7e95cd9f), normalisePath.ts,
# scopes.ts, security.ts, config/services.ts, versioning.ts, the ks843 path-bypass test, api-gateway package.json / vitest.config.ts / vitest.setup.ts / tsconfig.json,
# Dev eslint.config.mjs, originate routes/gdpr.ts and originate index.ts — any blob nobody pinned -> exit 18; proxy.ts at ANY OTHER blob is judged by REGION content
# (the import block through the Factory banner, and the erasure door through the gdpr catch-all mount): a move into a region refuses (exit 18), a move outside clears;
# (b) if develop moved past f8c7aaa39, the compare pinned...develop REFUSES (exit 18) when the delta touches a GUARDED path — services/api-gateway/src/ and its config
# files, originate routes/gdpr.ts + index.ts, eslint.config.mjs, the Dev lockfile — unless the hit is proxy.ts cleared by its region judgement (DEV_CONTENT_ALLOWED is
# EMPTY), or the move cannot be judged.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate's R-6: a wholesale link can write through to the checkout's .vite).
# exit 23: the prompt must carry the exact ROUND 2 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the round-2 REPORT DIRECTORY and the ROUND-1 REPORT path (the QA agent has no inbox), and the prompt must name
#          NOT-TESTED.written-first.md (written FIRST, before any run).
# exit 25: brief AND prompt must carry the MERGE ADDENDUM and require the per-finding CLOSED / STILL OPEN / NEW disposition (round 2 of 2: closed instances ship,
#          residue is ticketed).
# QA1019R2_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# QA1019R2_PROXY_FILE (test fixture, --check only): a local file stands in for develop's routes/proxy.ts (content AND git blob) so the region judgement's
# clear and refuse arms, and the LANDED arm, can be proven without a real develop commit.
# A launch with any QA1019R2_* override or fixture set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1019r2/gen_launcher_1019r2.py from launch_qa_secuura_ks1187_1019.sh (asserted substitutions + residual
# guard + output controls + bash -n): same guard set and exit codes 2..23, re-pointed at #1019 ROUND 2, with round-2 exits 24/25. Exit codes 2..25 (19 = LANDED).
#
# Usage: launch_qa_secuura_ks1187_1019r2.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
"""
JUDGED_OLD = cut('S17 = "develop = #1017 squash"\n', '  D + "services/originate/src/index.ts":                               ({"44d4e4f341f5d314f5b95405b209a9450cde1d3e": "base"}, {}),\n}\n')
JUDGED_NEW = '''DV = "develop"
S17 = "develop = #1017 squash d7e95cd9f"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  PX:                                                                  ({"b99f45a4c9c89088a7809de5f26c4f56fc94819c": DV}, {"db1534753c571e7496c5e47d58bd9304515132c1": "#1019 round-1 own", "795ae7ca3bdc76be3e563e87fc34a8cc221e5632": "#1019 round-2 own"}),
  G + "src/__tests__/ks843-erasure-scope-gate.test.ts":                ({"a3c5541216a2b6052bc1396310004b12ea89fc25": DV}, {"06b499605e79ff0cc882ff3af82d2d3dd7569455": "#1019 own, rounds 1 and 2"}),
  G + "src/__tests__/ks1187-erasure-door-judges-the-canonical-path.test.ts": ({"ABSENT": DV}, {"389e51e1df153c295064b288c243a41289479513": "#1019 round-1 own", "76c0137ee0accb5c37b376f53565c45789e09890": "#1019 round-2 own"}),
  G + "src/middleware/auth.ts":                                        ({"7c985bdcefc26293815bfbe0cbf315f929b48835": S17}, {}),
  G + "src/middleware/rateLimitEnforce.ts":                            ({"90bd29378508c8fee54e010b54cdc72ff992aafa": S17}, {}),
  G + "src/index.ts":                                                  ({"db127dbfa5dd899b0a8e0d844690890d91e27f10": S17}, {}),
  G + "src/__tests__/ks1195-per-key-rate-limiter-runs-after-authentication.test.ts": ({"4b1fc017da158de4e7a3a47565b7dbccc1ea3872": S17}, {}),
  D + "packages/shared/src/__tests__/ks781-p3-3-body-parser-order.test.ts": ({"bc4815c4ec9cae2f065e29dec6b938cdf49f2d23": S17}, {}),
  G + "src/middleware/normalisePath.ts":                               ({"1a7312a8675ffdfe263060bb5d60aa837111431a": DV}, {}),
  G + "src/middleware/scopes.ts":                                      ({"7aef335b93acf7a94fbcadc61c353d7a5dde90c5": DV}, {}),
  G + "src/middleware/security.ts":                                    ({"69273561925c0924f33b98f5ff9c6d6cf72c2896": DV}, {}),
  G + "src/config/services.ts":                                        ({"6110888aac8c834c291b5385710943f9b6adf57b": DV}, {}),
  G + "src/routes/versioning.ts":                                      ({"697bbb48bd93775572c7bde41c303eb4775ee920": DV}, {}),
  G + "src/__tests__/ks843-erasure-path-bypass.test.ts":                ({"2c8783ac86644ef690201d73f055b3a25b766d41": DV}, {}),
  G + "package.json":                                                  ({"841d8c6adcd71e885c01e65c22da9418daff276a": DV}, {}),
  G + "vitest.config.ts":                                              ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": DV}, {}),
  G + "vitest.setup.ts":                                               ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": DV}, {}),
  G + "tsconfig.json":                                                 ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": DV}, {}),
  D + "eslint.config.mjs":                                             ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": DV}, {}),
  D + "services/originate/src/routes/gdpr.ts":                         ({"a1c7482a250f37b0c2fbd2531e67cd5f367f1045": DV}, {}),
  D + "services/originate/src/index.ts":                               ({"44d4e4f341f5d314f5b95405b209a9450cde1d3e": DV}, {}),
}
'''
ALLOW_OLD = cut('# CONTENT-JUDGED allowlist: a hit under a GUARDED path clears ONLY if', '  G + "src/__tests__/ks1195-per-key-rate-limiter-runs-after-authentication.test.ts": ["ade08ac1ebd2a7305a7e253a79a78c63099bf5c0", "4b1fc017da158de4e7a3a47565b7dbccc1ea3872"],\n}\n')
ALLOW_NEW = '''# CONTENT-JUDGED allowlist: EMPTY for round 2. #1017 has MERGED (its squash d7e95cd9f is on develop f8c7aaa39, the pin), so no sibling blob is pre-cleared.
# proxy.ts is judged by its REGION above. Every other guarded hit falls through to exit 18. Re-pin deliberately.
DEV_CONTENT_ALLOWED = {}
'''
REPL = [
 ('header', HEADER_OLD, HEADER_NEW, 1),
 ('brief var', 'BRIEF="${QA1019_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019-ks1187-tier1.md}"', 'BRIEF="${QA1019R2_BRIEF:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.md}"', 1),
 ('prompt var', 'PROMPT_FILE="${QA1019_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019-ks1187-tier1.prompt.txt}"', 'PROMPT_FILE="${QA1019R2_PROMPT:-$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.prompt.txt}"', 1),
 ('head var', 'HEAD_SHA="${QA1019_HEAD:-8b8996f8b290ef55c35721c30f8671f982fa5a91}"', 'HEAD_SHA="${QA1019R2_HEAD:-82f09c8bd1bfab28e4d23c180cbaffea251685be}"', 1),
 ('merge-base', "MERGE_BASE='fa887f382b212b8da4a0a4a556bacb05ea34daaa'   # the merge-base of the head with develop = the PR parent of 50a4b749a (#1014s squash)",
  "MERGE_BASE='f8c7aaa39dabfe6a3916e5be55d9ccd752e7d8ed'   # the merge-base of the head with develop = develop itself, the second parent of the head merge 82f09c8bd (#1020s squash on #1017s squash)", 1),
 ('develop', "DEVELOP_SHA='fa887f382b212b8da4a0a4a556bacb05ea34daaa'   # develop at draft close = the PR parent (branches API 09:35:53, git ls-remote 09:18:55 and 09:37:10 AEST)",
  "DEVELOP_SHA='f8c7aaa39dabfe6a3916e5be55d9ccd752e7d8ed'   # develop at round-2 drafting, an ANCESTOR of the head (git ls-remote 16:44:13, 16:44:54, 16:48:17; branches API 16:50 AEST)", 1),
 ('report dir', "REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019-8b8996f8b-tier1-r1/'\n", "REPORT_DIR='" + REPORT_DIR + "'\nR1_REPORT='" + R1_REPORT + "'\n", 1),
 ('real brief', 'REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019-ks1187-tier1.md"', 'REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1019r2-ks1187-tier1.md"', 1),
 ('head refuse', 'REFUSING: #1019 — $HEAD_SHA', 'REFUSING: #1019 ROUND 2 — $HEAD_SHA', 1),
 ('compare comment', '# develop...#1019 = fa887f382 ahead 2 files 3 (behind 0 at draft close; behind deliberately not asserted).', '# develop...#1019 ROUND 2 = f8c7aaa39 ahead 4 files 3 (behind 0 at draft close; behind deliberately not asserted).', 1),
 ('compare assert', '''[ "$COMPARE" = "$MERGE_BASE ahead=2 files=3" ] || { echo "REFUSING: #1019 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=2 files=3'" >&2; exit 10; }''',
                    '''[ "$COMPARE" = "$MERGE_BASE ahead=4 files=3" ] || { echo "REFUSING: #1019 ROUND 2 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=4 files=3'" >&2; exit 10; }''', 1),
 ('cur dev', 'CUR_DEV="${QA1019_CUR_DEV:-', 'CUR_DEV="${QA1019R2_CUR_DEV:-', 1),
 ('develop comment 2', '# The develop pin, judged by CONTENT (see the header): twenty files by blob', '# The develop pin, judged by CONTENT (see the header): twenty-one files by blob', 1),
 ('judged', JUDGED_OLD, JUDGED_NEW, 1),
 ('S17R2 def gone', 'S17R2 = "develop = #1017 round-2 squash"\n', '', 0),
 ('region comment', '# REGION judgement for routes/proxy.ts (brief items 1-7 stand on it); two segments of the base file; the SHA was computed by the generator from the base blob.',
                    '# REGION judgement for routes/proxy.ts (brief items 1-7 stand on it); two segments of develop f8c7aaa39 proxy.ts b99f45a4c = the round-1 base blob; SHA re-computed by gen_launcher_1019r2.py, equal to round 1.', 1),
 ('fixture env', 'os.environ.get("QA1019_PROXY_FILE", "")', 'os.environ.get("QA1019R2_PROXY_FILE", "")', 1),
 ('landed msg', '" — #1019 has landed; this brief is stale"', '" — #1019 has landed; this ROUND 2 brief is stale"', 1),
 ('ok pinned', '" (= the PR parent: merged tree = the head tree 3bc12a363d0e7161be3b5de683aa0e6ae00ac052; git ls-remote)"',
               '" (= the head merge-base, an ANCESTOR of the head: merged tree = the head tree 99df1503e4f18ac444baed015659fecbb912bbb0; git ls-remote)"', 1),
 ('allowlist', ALLOW_OLD, ALLOW_NEW, 1),
 ('tail', 'tail = "the gate merges the then-current develop onto 8b8996f8b in its own clone, rebuilds the shared dist there, runs the api-gateway suite and the door census in test AND production mode on the MERGED tree beside the base and head trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 2, 3, 9)"',
          'tail = "the gate merges the then-current develop onto 82f09c8bd in its own clone, rebuilds the shared dist there, re-runs the round-1 harness census on the MERGED tree beside the round-1, round-2 and head trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 2, 5)"', 1),
 ('moved msg', 'or cleared by the proxy.ts region judgement or #1017s exact blobs; %s', 'or cleared by the proxy.ts region judgement; %s', 1),
 ('refuse repin msg', '(launcher DEVELOP_SHA / JUDGED blobs / DEV_CONTENT_ALLOWED + brief TARGET + prompt)', '(launcher DEVELOP_SHA / JUDGED blobs + brief TARGET + prompt)', 1),
 ('round grep', '''grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }''',
                '''grep -q 'ROUND 2' "$BRIEF" && grep -q 'ROUND 2' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 2)" >&2; exit 15; }''', 1),
 ('subject + round-2 rules',
  '''grep -qF '[QA -> Wednesday] TIER 1 GATE #1019 (KS-1187) 8b8996f8b' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \\
  || { echo "REFUSING: prompt does not carry the exact verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" \\
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR, or the prompt does not name NOT-TESTED.written-first.md — the report must land where Wednesday reads it, NOT-TESTED first" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" \\
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM — the merge seat's equality targets and the In Progress hold ride on it" >&2; exit 25; }
''',
  '''grep -qF '[QA -> Wednesday] TIER 1 GATE #1019 ROUND 2 (KS-1187) 82f09c8bd' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \\
  || { echo "REFUSING: prompt does not carry the exact ROUND 2 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$REPORT_DIR" "$PROMPT_FILE" && grep -qF "$REPORT_DIR" "$BRIEF" && grep -qF 'NOT-TESTED.written-first.md' "$PROMPT_FILE" && grep -qF "$R1_REPORT" "$PROMPT_FILE" && grep -qF "$R1_REPORT" "$BRIEF" \\
  || { echo "REFUSING: brief or prompt does not name the report directory $REPORT_DIR and the ROUND-1 REPORT $R1_REPORT, or the prompt does not name NOT-TESTED.written-first.md — the QA agent has no inbox; a carry-forward with no pointer can only be answered with I could not" >&2; exit 24; }
grep -qF 'MERGE ADDENDUM' "$PROMPT_FILE" && grep -qF 'MERGE ADDENDUM' "$BRIEF" && grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \\
  || { echo "REFUSING: brief or prompt does not carry the MERGE ADDENDUM and the per-finding CLOSED / STILL OPEN / NEW disposition — round 2 of 2: closed instances ship and residue is ticketed" >&2; exit 25; }
''', 1),
 ('check head', 'echo "  head on origin: #1019 $HEAD_SHA at $BRANCH"', 'echo "  head on origin: #1019 ROUND 2 $HEAD_SHA at $BRANCH"', 1),
 ('check compare', 'echo "  compare (GitHub API): develop...#1019 = $COMPARE"', 'echo "  compare (GitHub API): develop...#1019 ROUND 2 = $COMPARE"', 1),
 ('check round', 'echo "  brief and prompt agree on TIER 1 and ROUND 1"', 'echo "  brief and prompt agree on TIER 1 and ROUND 2"', 1),
 ('check subject', 'echo "  prompt carries the exact verdict subject, coagent@ sender, wednesday-agent@ recipient"\n  echo "  brief and prompt name the report directory; prompt names NOT-TESTED.written-first.md"\n  echo "  brief and prompt carry the MERGE ADDENDUM"\n',
                   'echo "  prompt carries the exact ROUND 2 verdict subject, coagent@ sender, wednesday-agent@ recipient"\n  echo "  brief and prompt name the round-2 report directory and the ROUND-1 REPORT; prompt names NOT-TESTED.written-first.md"\n  echo "  brief and prompt carry the MERGE ADDENDUM and require CLOSED / STILL OPEN / NEW per finding"\n', 1),
 ('check fixture echo', '  [ -n "${QA1019_CUR_DEV:-}" ] && echo "  (develop read from the QA1019_CUR_DEV test override, not ls-remote)"\n  [ -n "${QA1019_PROXY_FILE:-}" ] && echo "  (develop routes/proxy.ts read from the QA1019_PROXY_FILE fixture, not the contents API)"\n',
  '  [ -n "${QA1019R2_CUR_DEV:-}" ] && echo "  (develop read from the QA1019R2_CUR_DEV test override, not ls-remote)"\n  [ -n "${QA1019R2_PROXY_FILE:-}" ] && echo "  (develop routes/proxy.ts read from the QA1019R2_PROXY_FILE fixture, not the contents API)"\n', 1),
 ('exit16 fixture', '[ -z "${QA1019_BRIEF:-}${QA1019_PROMPT:-}${QA1019_HEAD:-}${QA1019_CUR_DEV:-}${QA1019_PROXY_FILE:-}" ]', '[ -z "${QA1019R2_BRIEF:-}${QA1019R2_PROMPT:-}${QA1019R2_HEAD:-}${QA1019R2_CUR_DEV:-}${QA1019R2_PROXY_FILE:-}" ]', 1),
]
bad = 0
for label, old, new, want in REPL:
    n = s.count(old)
    if n != want: print('ANCHOR COUNT', label, n, '!=', want); bad += 1; continue
    if n: s = s.replace(old, new)
    print('  ok', label, n)
if bad: print('REFUSING: %d anchors disagreed; nothing written' % bad); sys.exit(1)
RESID = ['QA1019_', 'ROUND 1', 'ahead=2', '8b8996f8b290ef55c35721c30f8671f982fa5a91', 'fa887f382', '3bc12a363', 'cbe29597d', 'a067d4e3e', 'S17R2', '8fbe102eb', 'f4b66aa1a', 'ade08ac1e',
         'ca1fe34a7', '20311010d', 'fc5c5a4d9', '6f38c819e', "REPORT_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019-8b8996f8b-tier1-r1/'",
         '"#1019 own"', 'launch_qa_secuura_ks1187_1019.sh —', 'brief items 1, 2, 3, 9', 'onto 8b8996f8b', '#1017s exact blobs', 'gated first and may merge first']
PERMITTED = {'from launch_qa_secuura_ks1187_1019.sh': 1, "R1_REPORT='/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1187-1019-8b8996f8b-tier1-r1/'": 1,
             'round 1 (head 8b8996f8b)': 1, 'parent 8b8996f8b': 1}
stripped = s
for k, v in PERMITTED.items():
    if stripped.count(k) != v: print('PERMITTED count', repr(k), stripped.count(k), '!=', v); sys.exit(1)
    stripped = stripped.replace(k, '')
res = {t: stripped.count(t) for t in RESID if t in stripped}
if res: print('REFUSING: residual tokens', res); sys.exit(2)
CTL = {'82f09c8bd1bfab28e4d23c180cbaffea251685be': 2, 'f8c7aaa39dabfe6a3916e5be55d9ccd752e7d8ed': 2, '99df1503e4f18ac444baed015659fecbb912bbb0': 1, WANT: 1,
       REPORT_DIR: 1, R1_REPORT: 1, '"$R1_REPORT"': 2, 'ahead=4 files=3': 2, 'QA1019R2_PROXY_FILE': 5, 'QA1019R2_CUR_DEV': 5,
       '795ae7ca3bdc76be3e563e87fc34a8cc221e5632': 1, '76c0137ee0accb5c37b376f53565c45789e09890': 1, 'db1534753c571e7496c5e47d58bd9304515132c1': 1, '389e51e1df153c295064b288c243a41289479513': 1,
       '06b499605e79ff0cc882ff3af82d2d3dd7569455': 1, '6110888aac8c834c291b5385710943f9b6adf57b': 1, 'DEV_CONTENT_ALLOWED = {}': 1, ': S17}': 5, ': DV}': 16,
       "grep -q 'ROUND 2'": 2, 'CLOSED / STILL OPEN / NEW': None, 'MERGE ADDENDUM': None, 'NOT-TESTED.written-first.md': None, 'content_cleared': 3,
       'exit 19': None, 'exit 21': None, 'exit 22': None, 'exit 23': None, 'exit 24': None, 'exit 25': None, 'exit 16': None, '[QA -> Wednesday] TIER 1 GATE #1019 ROUND 2 (KS-1187) 82f09c8bd': 1}
got = {k: s.count(k) for k in CTL}
print('output controls', {(k[:24] + '…' if len(k) > 24 else k): v for k, v in got.items()})
for k, v in CTL.items():
    if (v is not None and got[k] != v) or got[k] == 0: print('CONTROL DISAGREED', k, got[k], v); sys.exit(1)
for tag in ("<<'PY'\n", "<<'PYJ'\n"):
    i = s.index(tag); j = s.index('\nPY' + ('J' if 'PYJ' in tag else '') + '\n', i); blk = s[i:j]
    print('heredoc', tag.strip(), "apostrophes", blk.count("'") - 2, 'parens (', blk.count('('), ')', blk.count(')'))
    if (blk.count("'") - 2) % 2 or blk.count('(') != blk.count(')'): print('REFUSING: heredoc parity'); sys.exit(1)
if re.search(r'git -C "\$REPO" (fetch|push|checkout|merge|reset|worktree|commit|switch|pull)\b', s): print('REFUSING: git write verb'); sys.exit(1)
if re.search(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', s): print('REFUSING: control bytes'); sys.exit(1)
if os.path.exists(OUT):
    pre = OUT + '.pre-' + now('+%H%M%S'); shutil.copyfile(OUT, pre); print('existing output copied to', pre)
open(OUT, 'w').write(s); os.chmod(OUT, 0o755)
p = subprocess.run(['bash', '-n', OUT], capture_output=True, text=True)
print('bash -n rc', p.returncode, p.stderr.strip()[:300])
if p.returncode: sys.exit(3)
print('written', OUT, 'mode', oct(os.stat(OUT).st_mode & 0o777), 'sha256', hashlib.sha256(s.encode()).hexdigest()[:16], 'lines', s.count('\n'))
