#!/bin/bash
# launch_qa_secuura_batch1323.sh — cross-project QA agent, ONE BATCH gate (gate36, T1 x2 + T2 x2) over 4 Secuura/Blockchain PRs of round 36, FROZEN at four:
# #1323 KS-1129 (B 38th (local-model patch, the Spark: KS-1129 item 4 LIVESCAN — api-gateway routes/verification.ts gives the LIVE chain-scan read the three shape guards KS-1069 gave the persisted read + 8 cells inserted into the existing ks1069 cell file), T1) · #1324 KS-1124 (B 38th (local-model patch, the Spark: KS-1124 O1 MINTMERGE — originate routes/documents.ts's thread-token cache write re-reads the document and merges into the blob as persisted, not the create-time copy + 3 cells inserted into the existing ks520 cell file; NARROWS the overwrite race, does not close it), T1) · #1325 KS-1227 (B 38th (seat-written, TEST-ONLY: the ks1072 anchor-store witness keeps count-every-stub-request, gains a comment recording the choice, and its message says ASKED; R1's toContain follows it), T2) · #1326 KS-1351 (B 38th (seat-written, TYPES-ONLY: KS-1351 item 1 — packages/shared vc/types.ts declares revoked / revokedAt / revocationReason on a NEW SecuuraCredentialStatus extends VCCredentialStatus and narrows SecuuraCredential.credentialStatus to it; item 2 — vc-issuer credentialRepo.ts:95 let -> const), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate36.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-28T08:14:41Z, never adopted
# from a mail. develop at generation d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817; the PRs' merge-bases: d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817 for #1323, #1324, #1325, #1326; END_TREE 36d6a2425ecf27c0e898b61e17e1a6280971387b.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate36: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate36.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  four rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate36.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at four.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the #1323 live-scan row. exit 41: the #1324 mintmerge row. exit 42: the #1325 test-only row. exit 43: the #1326 types-only row. exit 44: the READY identity. exit 46: the Linear link kinds. exit 47: the MG-3 key scan. exit 48: the squash-subject rule. exit 49: the no-op vs overlap keys. exit 50: the same-service pair on END_TREE. exit 51: the GO subject names the merge seat. exit 35: no Docker / no stack / no port.
# QAB36_CUR_DEV / QAB36_HEAD_<n> / QAB36_PATHS_<n> / QAB36_BRIEF / QAB36_PROMPT: test overrides (--check only); a launch with any QAB36_* set refuses (16).
# Generated by fill_gate36.py at 2026-09-28T08:20:44Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1323.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-28_gate36'
BRIEF="${QAB36_BRIEF:-$GS/mail_gate36_ready.md}"
PROMPT_FILE="${QAB36_PROMPT:-$GS/2026-09-28_secuura-batch1323.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1323|KS-1129|refs/heads/feature/ks-1129-livescan-shape-guards-b38-1|1a509947caf936bcc9b05f7817af6fcbcc974289|2|1|d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817|0|Blockchain/Dev/services/api-gateway/src/__tests__/ks1069-persisted-anchored-input-shape.test.ts,Blockchain/Dev/services/api-gateway/src/routes/verification.ts|T1"
  "1324|KS-1124|refs/heads/feature/ks-1124-mintmerge-persisted-blob-b38-2|47c4579b0199df1168220fa226805718c26fbbb3|2|1|d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817|0|Blockchain/Dev/services/originate/src/__tests__/ks520-anchor-fail-closed.test.ts,Blockchain/Dev/services/originate/src/routes/documents.ts|T1"
  "1325|KS-1227|refs/heads/feature/ks-1227-witness-counting-rule-b38-3|39f4922d391dabc7f3f99c9c0c8ea2ddde1b596f|1|1|d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817|0|Blockchain/Dev/services/api-gateway/src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts|T2"
  "1326|KS-1351|refs/heads/feature/ks-1351-secuura-status-revocation-fields-b38-4|3f569dfc701c757253aa71ed8b91b81ce9c84c93|2|1|d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817|0|Blockchain/Dev/packages/shared/src/vc/types.ts,Blockchain/Dev/services/vc-issuer/src/repositories/credentialRepo.ts|T2"
)
DEVELOP_SHA='d9ce1403d1581ff1584ab799fbbf7fc6f9f8d817'
END_TREE='36d6a2425ecf27c0e898b61e17e1a6280971387b'
STACKS=''
_ovr() { local v="QAB36_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate36.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 4 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 4 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate36_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB36_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate36.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at four' && has 'T1 ROWS ARE GRADED THROUGH CODE AND AT RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at four" >&2; exit 7; }
for _w in \
  '6 failed / 14 passed of 20' \
  '781 passed (781)' \
  'L5 is a behaviour choice, not a bug fix.' \
  'no recorded hold was found' \
  '29 errors at base, 29 patched' \
  '1 failed / 5 passed of 6' \
  '1055 passed (1055)' \
  'It NARROWS the race. It does not close it.' \
  'This path runs only with `STATE_THREAD_NFT_ENABLED=true`.' \
  'TS6133' \
  '1 failed / 7 passed of 8' \
  'Cell count is unchanged, as it should be' \
  'Types only. No runtime change' \
  'is invisible to every consumer until that package is rebuilt' \
  '15 files / 140 tests passed, identical at base and with the change' \
  'declare their own local type with `revoked?: boolean`' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'LIVE-GUARDS-THREE' \
  'STRICT-VERIFIED' \
  'PLACEHOLDER-HASH' \
  'STRICT-HEIGHT' \
  'SIMULATED-REPLY' \
  'MOCK-REPLY' \
  'STRING-HEIGHT' \
  'MIXED-ECHO' \
  'GUARD-PARITY' \
  'HELD-SURFACE' \
  'MINTMERGE-NARROWS' \
  'WINDOW-REMAINS' \
  'MIRROR-ERASES-THREADTOKEN' \
  'READ-FAILURE-FALLBACK' \
  'FLAG-GATED' \
  'ARM-NOT-LOADFAIL' \
  'COUNT-EVERY-REQUEST' \
  'COUPLING-R1' \
  'CELL-COUNT-UNCHANGED' \
  'TS2339-FOUR-TO-ZERO' \
  'SHARED-REBUILT-FIRST' \
  'EMIT-UNCHANGED' \
  'NARROWING-NOT-WIDENING' \
  'KS1352-NOT-THIS-PR' \
  'READY-IDENTITY' \
  'SLIDE-EQUAL' \
  'GIT-APPLY-NOT-PATCH' \
  'ONE-BASE' \
  'SUBJECT-LANDS-AT' \
  'NOOP-VS-OVERLAP' \
  'NO-FOREIGN-KEY' \
  'GATEWAY-COUNTS' \
  'ORIGINATE-COUNTS' \
  'VCISSUER-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'LOCAL-MODEL-PROVENANCE' \
  'TIERING'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'THE LIVE-SCAN ROW (#1323;' && has 'THROUGH THE REAL ROUTE' && has 'a simulated reply, a mock reply and a string-height reply' && has 'if your control is not on-chain at the head' || { echo "REFUSING: the #1323 live-scan row" >&2; exit 40; }
has 'THE MINTMERGE ROW (#1324;' && has 'it narrows the overwrite race and does not close it' && has 'THE GATE SAYS WHAT REMAINS' || { echo "REFUSING: the #1324 mintmerge row" >&2; exit 41; }
has 'THE WITNESS ROW (#1325;' && has 'TEST-ONLY: no product byte' || { echo "REFUSING: the #1325 test-only row" >&2; exit 42; }
has 'THE TYPES ROW (#1326;' && has 'It must show the TS2339 errors gone and nothing new, and no runtime change' && has 'REBUILD packages/shared in EACH worktree' || { echo "REFUSING: the #1326 types-only row" >&2; exit 43; }
has 'READY-IDENTITY: the drafter compared' && has 'SLIDE-EQUAL is not IDENTICAL' || { echo "REFUSING: the READY identity" >&2; exit 44; }
has 'all four PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'SQUASH SUBJECTS ARE DECLARED WITHOUT THE (#n) SUFFIX' && has 'len(declared) + len(" (#n)") <= 92' && has 'the merge tool refuses a declared subject matching' || { echo "REFUSING: the squash-subject rule" >&2; exit 48; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 49; }
has 'THE SAME-SERVICE PAIR (#1323 + #1325, api-gateway)' && has 'run the api-gateway suite ON END_TREE' || { echo "REFUSING: the same-service pair on END_TREE" >&2; exit 50; }
has 'the SUBJECT of the GO mail NAMES Seat B 38th' && has 'GO (Seat B 38th): merge 1323 1324 1325 1326 on gate36' || { echo "REFUSING: the GO subject names the merge seat" >&2; exit 51; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1323, #1324, #1325, #1326 batch`' && has 'so all four are squashed by Seat B 38th, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (7 over 7 paths) for #1323, #1324, #1325 and #1326' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE36 batch #1323 #1324 #1325 #1326 (Seat B38, round 36; T1 x2 + T2 x2: KS-1129 livescan, KS-1124 mintmerge, KS-1227, KS-1351)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB36_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 4 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 17 seat items; the prompt carries 37 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the #1323 live-scan row / the #1324 mintmerge row / the #1325 test-only row / the #1326 types-only row / the READY identity / the Linear link kinds / the MG-3 key scan / the squash-subject rule / the no-op vs overlap keys / the same-service pair on END_TREE / the GO subject names the merge seat / no Docker / no stack / no port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB36_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
