#!/bin/bash
# launch_qa_secuura_batch1339.sh — cross-project QA agent, ONE BATCH gate (gate41, T1) over 1 Secuura/Blockchain PR(s) of round 41, FROZEN at one:
# #1339 KS-1378 + KS-729 (B 43rd (seat-written, per Kam's ruling (a) on card secuura-five-new-advisories-block-every-push-0929 at 2026-09-29 11:43:09 AEST: bump all four packages with a quick reachability check; no baseline row added or edited; KS-729 rides as Refs because the ip-address bump clears its advisory as a measured side effect), T1)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate41.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-29T02:33:18Z, never adopted
# from a mail. develop at generation 8af6ab8216007462e596daed6b0adcd1e87e34ee; the PRs' merge-bases: 8af6ab8216007462e596daed6b0adcd1e87e34ee for #1339; END_TREE acb9823fc182adc4031dd420c2e60ddab8aa9142.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate41: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate41.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  one rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate41.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at one.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: requirement 1: a CLEAN install, nodemailer 10.0.x proved to be what runs. exit 41: requirement 2: auth AND originate suites green on nodemailer 10, originate proved at the base. exit 42: requirement 3: the 9 -> 10 changelog against both call sites per service. exit 43: requirement 4: audit legs 6 and 7 at the head, baseline untouched, the two CLEANUP rows named. exit 44: requirement 5: morgan 'combined' still logs and escapes a planted quote. exit 46: requirement 6: undici scoped to jsdom, ip-address nested copies overridden. exit 47: requirement 7: every suite a changed lock touches, before/after counts. exit 48: requirement 8: the cross-package guards. exit 49: requirement 9: the GO string, the subject rule, Refs KS-1378 and KS-729. exit 50: Tier 1 and the two-NO-GO cap, round 1. exit 51: the MG-3 key scan. exit 52: the addendum one-line-per-PR shape. exit 53: the Linear link kinds. exit 54: the no-op vs overlap keys. exit 55: the disk rule: Data volume, STOP on ENOSPC. exit 35: no Docker / no stack / npm-only egress.
# QAB41_CUR_DEV / QAB41_HEAD_<n> / QAB41_PATHS_<n> / QAB41_BRIEF / QAB41_PROMPT: test overrides (--check only); a launch with any QAB41_* set refuses (16).
# Generated by fill_gate41.py at 2026-09-29T02:33:27Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1339.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-29_gate41'
BRIEF="${QAB41_BRIEF:-$GS/mail_gate41_ready.md}"
PROMPT_FILE="${QAB41_PROMPT:-$GS/2026-09-29_secuura-batch1339.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1339|KS-1378 + KS-729|refs/heads/feature/ks-1378-bump-four-advisory-packages-b43-7|8c1b25b24782d851817f8c7bb1c02d390fe750d7|28|1|8af6ab8216007462e596daed6b0adcd1e87e34ee|0|Blockchain/Dev/frontend/issuer/package-lock.json,Blockchain/Dev/frontend/issuer/package.json,Blockchain/Dev/package-lock.json,Blockchain/Dev/package.json,Blockchain/Dev/packages/shared/package-lock.json,Blockchain/Dev/packages/shared/package.json,Blockchain/Dev/services/anchoring/package-lock.json,Blockchain/Dev/services/anchoring/package.json,Blockchain/Dev/services/api-gateway/package-lock.json,Blockchain/Dev/services/api-gateway/package.json,Blockchain/Dev/services/auth/package-lock.json,Blockchain/Dev/services/auth/package.json,Blockchain/Dev/services/demo-service/package-lock.json,Blockchain/Dev/services/demo-service/package.json,Blockchain/Dev/services/guardian/package-lock.json,Blockchain/Dev/services/guardian/package.json,Blockchain/Dev/services/m365-integration/package-lock.json,Blockchain/Dev/services/m365-integration/package.json,Blockchain/Dev/services/originate/package-lock.json,Blockchain/Dev/services/originate/package.json,Blockchain/Dev/services/prism/package-lock.json,Blockchain/Dev/services/prism/package.json,Blockchain/Dev/services/queue/package-lock.json,Blockchain/Dev/services/queue/package.json,Blockchain/Dev/services/security/package-lock.json,Blockchain/Dev/services/security/package.json,Blockchain/Dev/services/timestamping/package-lock.json,Blockchain/Dev/services/timestamping/package.json|T1"
)
DEVELOP_SHA='8af6ab8216007462e596daed6b0adcd1e87e34ee'
END_TREE='acb9823fc182adc4031dd420c2e60ddab8aa9142'
STACKS=''
_ovr() { local v="QAB41_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate41.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 1 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 1 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate41_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB41_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate41.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at one' && has 'T1 ROWS ARE GRADED THROUGH CODE AND AT RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at one" >&2; exit 7; }
for _w in \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.' \
  'legs 3 4 8 — local stack not up; you can clear this by starting it.' \
  'audit-gate: 23 distinct advisories reported, 25 baselined.' \
  'OK — no advisories outside the triaged baseline.' \
  '18 advisories match, 18 already baselined.' \
  'CLEANUP (advisory): 2 baseline entries are no longer reported' \
  'Zero vulnerable copies of any of the four remain' \
  '77 files / 836 tests passed against 9.1.1' \
  'Cannot find module '\''../routes/anchors'\''' \
  'npm error code EOVERRIDE' \
  'install rc=0' \
  'nodemailer now: 9.1.1' \
  'the ROOT undici 5.29.0 (via @connectrpc/connect-node) is NOT vulnerable' \
  'ip-address: @cardano-sdk/core asks ^9.0.5 and 9.x has NO fix, so only an' \
  'host npm 11.5.1 dies with "Cannot read properties of null (reading '\''edgesOut'\'')"' \
  'Regenerated in node:24-alpine' \
  'FOUND: **NOT REACHABLE as written.**' \
  'FOUND: **REACHABLE.**' \
  'Both services create exactly **one** transport, memoised:' \
  'The root `morgan` override is redundant now that all ten declarers say ^1.12.1.' \
  'No baseline entry added or removed. No --no-verify. Nothing deployed.' \
  'the audit fuse — 21.9 h, computed 2026-09-29T02:08Z.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'CLEAN-INSTALL' \
  'NODEMAILER-10-RUNS' \
  'EOVERRIDE-GOTCHA' \
  'ROOT-AND-STANDALONE-INSTALL' \
  'AUTH-SUITE-ON-10' \
  'ORIGINATE-SUITE-ON-10' \
  'ORIGINATE-PRE-EXISTING-AT-BASE' \
  'ORIGINATE-RUNNER-IS-JEST' \
  'NODEMAILER-CHANGELOG-9-TO-10' \
  'CALL-SITES-PER-SERVICE' \
  'TYPES-BUNDLED-VS-AT-TYPES' \
  'ESM-CJS-DUAL-BUILD' \
  'AUDIT-LEG-6' \
  'AUDIT-LEG-7' \
  'BASELINE-UNTOUCHED' \
  'CLEANUP-ROWS-NAMED' \
  'OUT-OF-SCOPE-LOCKS' \
  'MORGAN-COMBINED-LOGS' \
  'MORGAN-QUOTE-ESCAPED' \
  'UNDICI-SCOPED-TO-JSDOM' \
  'ROOT-UNDICI-UNTOUCHED' \
  'IP-ADDRESS-NO-9X' \
  'CARDANO-NESTED-OVERRIDDEN' \
  'LOCK-SUITES-BEFORE-AFTER' \
  'CROSS-PACKAGE-GUARDS' \
  'LOCK-DISCOVERY-CONTRACT' \
  'DECLARED-OPEN-OVERLAPS' \
  'SUBJECT-LANDS-AT' \
  'REFS-TWO-KEYS' \
  'NOOP-VS-OVERLAP' \
  'NO-FOREIGN-KEY' \
  'ADDENDUM-ONE-LINE-PER-PR' \
  'TSC-EXCLUDES-TESTS' \
  'AUDIT-FUSE' \
  'DISK-ENOSPC' \
  'TIER1-CAP-ROUND-1' \
  'TIERING'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'A CLEAN INSTALL (requirement 1' && has '`npm ci` per affected lock, never an incremental install' && has 'print the RESOLVED nodemailer version from node_modules' && has 'A gate that repeats the EOVERRIDE install has not tested the bump' || { echo "REFUSING: requirement 1: a CLEAN install, nodemailer 10.0.x proved to be what runs" >&2; exit 40; }
has 'services/auth AND services/originate SUITES GREEN ON NODEMAILER 10 (requirement 2' && has 'prove the seat'\''s PRE-EXISTING claim at the BASE 8af6ab82' && has 'or find that it is the bump'\''s' || { echo "REFUSING: requirement 2: auth AND originate suites green on nodemailer 10, originate proved at the base" >&2; exit 41; }
has 'NODEMAILER 9 -> 10 BREAKING CHANGES (requirement 3' && has 'read its changelog for 9 -> 10' && has 'transport creation and the sendMail options, per service' || { echo "REFUSING: requirement 3: the 9 -> 10 changelog against both call sites per service" >&2; exit 42; }
has 'AUDIT LEGS 6 AND 7 PASS AT THE HEAD (requirement 4' && has 're-run the repo'\''s own audit scripts' && has 'no baseline row was added or edited' && has 'GHSA-v2v4-37r5-5v8g and GHSA-mwp4-54f8-5fhr' && has 'without acting on them' || { echo "REFUSING: requirement 4: audit legs 6 and 7 at the head, baseline untouched, the two CLEANUP rows named" >&2; exit 43; }
has 'MORGAN 1.12.1 (requirement 5' && has 'the '\''combined'\'' format still logs' && has 'a planted double quote in User-Agent is escaped in the log line' || { echo "REFUSING: requirement 5: morgan 'combined' still logs and escapes a planted quote" >&2; exit 44; }
has 'THE UNDICI OVERRIDE IS SCOPED TO jsdom (requirement 6' && has 'the root undici 5.29.0 is untouched' && has 'no 9.x copy of ip-address remains' || { echo "REFUSING: requirement 6: undici scoped to jsdom, ip-address nested copies overridden" >&2; exit 46; }
has 'EVERY SUITE TOUCHED BY A CHANGED LOCKFILE (requirement 7' && has 'all 10 morgan services, packages/shared, frontend/issuer, anchoring' && has 'with before/after counts' && has 'a lock change can break a service without touching its code' || { echo "REFUSING: requirement 7: every suite a changed lock touches, before/after counts" >&2; exit 47; }
has 'CROSS-PACKAGE GUARDS (requirement 8' && has '`git grep -l '\''<changed path>'\''`' && has 'the audit contract suites' || { echo "REFUSING: requirement 8: the cross-package guards" >&2; exit 48; }
has 'THE GO STRING AND THE SUBJECT (requirement 9' && has 'the squash subject is declared WITHOUT `(#n)` and checked as declared + " (#1339)" <= 92 chars' && has 'Refs KS-1378 and Refs KS-729' || { echo "REFUSING: requirement 9: the GO string, the subject rule, Refs KS-1378 and KS-729" >&2; exit 49; }
has 'TIER 1 AND THE TWO-NO-GO CAP (TIER1-CAP-ROUND-1' && has 'this is ROUND 1 for this class' || { echo "REFUSING: Tier 1 and the two-NO-GO cap, round 1" >&2; exit 50; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'the key scanner over every mandated body' && has 'the audit tool prints advisory keys and ticket keys hyphenated' || { echo "REFUSING: the MG-3 key scan" >&2; exit 51; }
has 'THE ADDENDUM IS ONE LINE PER PR in exactly this shape' && has '- #NNNN · head <sha12> · subject: `<subject>`' && has 'NO sub-bullets' || { echo "REFUSING: the addendum one-line-per-PR shape" >&2; exit 52; }
has 'every PR links its ticket as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 53; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 54; }
has 'DISK: every clone, worktree, install and build goes on the Data volume' && has 'STOP on any ENOSPC' && has 'never under /Volumes/DevMASTER' || { echo "REFUSING: the disk rule: Data volume, STOP on ENOSPC" >&2; exit 55; }
has 'NO DOCKER, NO STACK, NO TCP LISTENER beyond 127.0.0.1 port 0 in this gate' && has 'the ONLY outbound requests are the npm registry and the npm advisory API' || { echo "REFUSING: no Docker / no stack / npm-only egress" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO (Seat B 44th): merge 1339 on gate41`' && has 'it is squashed by the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (28 over 28 paths) for #1339' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE41 batch #1339 (Seat B43, round 41; T1: KS-1378 the four-package advisory bump, nodemailer 9 -> 10)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB41_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 1 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 22 seat items; the prompt carries 37 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / requirement 1: a CLEAN install, nodemailer 10.0.x proved to be what runs / requirement 2: auth AND originate suites green on nodemailer 10, originate proved at the base / requirement 3: the 9 -> 10 changelog against both call sites per service / requirement 4: audit legs 6 and 7 at the head, baseline untouched, the two CLEANUP rows named / requirement 5: morgan 'combined' still logs and escapes a planted quote / requirement 6: undici scoped to jsdom, ip-address nested copies overridden / requirement 7: every suite a changed lock touches, before/after counts / requirement 8: the cross-package guards / requirement 9: the GO string, the subject rule, Refs KS-1378 and KS-729 / Tier 1 and the two-NO-GO cap, round 1 / the MG-3 key scan / the addendum one-line-per-PR shape / the Linear link kinds / the no-op vs overlap keys / the disk rule: Data volume, STOP on ENOSPC / no Docker / no stack / npm-only egress rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB41_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
