#!/usr/bin/env python3
"""make_readme_gate41.py <scratchpad> — writes README.md for gate41 (the directory this script lives in). Every figure is READ from the kit's own output
files at the moment it runs (pins_gate41.json, predict_1.out, predict_sim_*.out(.rc), installprobe_gate41.json, fill_1.out, keyscan_1.out, rekey_1.out,
launcher_check_1.out, repin_dryrun_N.out, controls_1.out / controls_2.out (+ .rc), final_lsremote_1.out), each named beside it; the prose (doubts,
questions) is the drafter's. Shape copied from gate40's make_readme (gate39 -> gate38 lineage), re-keyed to gate41. The README ENDS with §8, the ONE
launch command; its argument 2 is the EXISTING scratchpad passed here."""
import json, os, re, glob, hashlib, datetime, sys
D = os.path.dirname(os.path.abspath(__file__)); K = json.load(open(D + '/kit.json')); kit = K['kit']
SP = sys.argv[1] if len(sys.argv) > 1 else ''
if not (SP.startswith('/private/tmp/claude-501/') and '/scratchpad' in SP and os.path.isdir(SP)): sys.exit('usage: make_readme_gate41.py <an EXISTING scratchpad dir under /private/tmp/claude-501/*/scratchpad*> (argument 2 of the launch command)')
P = json.load(open('%s/pins_%s.json' % (D, kit))); IP = json.load(open('%s/installprobe_%s.json' % (D, kit)))
def rd(f): return open(os.path.join(D, f), encoding='utf-8').read() if os.path.exists(os.path.join(D, f)) else ''
def last(f, rx):
    m = [l for l in rd(f).splitlines() if re.search(rx, l)]; return m[-1].strip() if m else 'ABSENT'
def rc(f): return rd(f).strip() or '?'
def strip(s): return re.sub(r'^(PASS )?#1339 ', '', s)
def j(x): return json.dumps(x, ensure_ascii=False, default=str)
DRY = sorted(glob.glob(D + '/repin_dryrun_[0-9]*.out'), key=lambda f: int(re.search(r'_(\d+)\.out$', f).group(1)))
DRYF = os.path.basename(DRY[-1]) if DRY else 'repin_dryrun_1.out'
fill = rd('fill_1.out'); now = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
L = os.path.join(D, K['launcher']); PR = os.path.join(D, K['prompt']); CAP = os.path.join(D, 'mail_%s_ready.md' % kit)
def sz(p): b = open(p, 'rb').read(); return '`%s` %d bytes sha256 `%s`' % (os.path.basename(p), len(b), hashlib.sha256(b).hexdigest())
SU = IP['_summary']
sims = {os.path.basename(f)[len('predict_sim_'):-len('.out')]: (rc(os.path.basename(f) + '.rc'), last(os.path.basename(f), r'^(PASS|REFUSED):')[:44]) for f in sorted(glob.glob(D + '/predict_sim_*.out'))}
fl = rd('final_lsremote_1.out').strip().replace('\n', ' | ')
n = '1339'; pr = P['prs'][n]
cur = pr['head'] in fl and P['develop'] in fl
CH, CD = '8c1b25b24782d851817f8c7bb1c02d390fe750d7', '8af6ab8216007462e596daed6b0adcd1e87e34ee'   # the values Wednesday's commission named (ls-remote 12:0x AEST)
launch = '%s/repin_and_launch_%s.sh %s %s' % (D, kit, L, SP)
m = re.search(r'#%s (\d+)->(\d+)' % n, fill)
row = '| #%s | %s | %s | `%s` | %d on `%s` | %d (14 package.json + 14 package-lock.json) | %s -> %s |' % (n, ' + '.join(K['prs'][n]['keys']), K['prs'][n]['tier'], pr['head'], len(pr['commits']), pr['merge_base'][:12],
      len(pr['paths']), m.group(1) if m else '?', m.group(2) if m else '?')
DOS = sorted(K.get('dead_open_declared', {}), key=int, reverse=True)
out = ['# Gateset %s — README for Wednesday' % os.path.basename(D), '',
 'Written %s by the drafter (make_readme_gate41.py; every figure below is read from the kit\'s own output files at that moment, each named beside it).' % now,
 'The drafter launched nothing, sent no mail, tapped no pane, merged nothing, committed nothing, pushed nothing, posted nothing, changed no ticket or PR and deleted nothing. It wrote this kit directory (TEXT files only) and scratch on the DATA volume under its session scratchpad (the scratch clone `g41_sp/clone.git` — `git clone --bare --shared --no-checkout` of the checkout, fetched FROM ORIGIN with the checkout\'s repo-local key; the four standalone service installs `g41/ip/{base,head}_{auth,originate}` (+ the first round moved aside as `*.prev1`, never removed) and their npm cache `g41/npmcache`; per-run outputs under `g41/`; the control workdirs `g41_controls_*`; one `__pycache__` the drafter\'s own syntax check wrote into the kit, MOVED to `g41/_quarantine_2026-09-29/kit_pycache_1`, not deleted). Every long-running output was written in the scratchpad first and copied in, byte-compared. It did NOT write the routing line (§4).',
 'The Secuura checkout was touched only by read verbs (ls-remote, `config --get`, `show`, `cat-file`, `ls-tree`, `grep`, `merge-base`, and `clone --shared` as a source). Seat B 43rd\'s handover, record folder and session scratchpad were READ. GitHub: REST GET only. Linear: queries only. npm: the registry, for four `npm ci --ignore-scripts` runs of committed locks (no advisory call). AgentMail: ONE read-only API listing of wednesday-agent@ (GET messages?limit=100 — touches no seen-state; used ONLY to find the READY mail\'s id by the commissioned subject prefix) and ONE by-id read (inbox_digest.sh full); nothing sent. decisions.json and inbox_routing.conf: read only.', '',
 '**gate41 = ONE PR (T1), one kit, no sibling, NO stack, ONE merge-base (develop itself), pinned over the CURRENT develop; eleven OPEN PRs DECLARED as overlapping (manifests / locks).**', '',
 '| PR | tickets | tier | head (API == ls-remote pull/head == branch == fetched) | commits on merge-base | files | subject declared -> lands |', '|---|---|---|---|---|---|---|', row, '',
 'Routing `%s` (**NOT added by the drafter** — §4). The GO string, as the GO mail\'s SUBJECT: `GO (Seat B 44th): merge 1339 on gate41` — it names the SUCCESSOR merge seat (Seat B 43rd has wrapped; Seat B 44th is not yet launched; launcher exit 26; kit rule 49 carries requirement 9). The squash subject is the PR title verbatim, declared explicitly (fill_gate41.py SHORT), lands at %s; body `Refs KS-1378` + `Refs KS-729`.' % (K['pane'], m.group(2) if m else '?'),
 '', '## 1. BLUF',
 '- **Kit: READY to launch once the routing line is added** — launcher `--check` (launcher_check_1.out: `%s`); repin `--dry-run` (%s: %s).' % (last('launcher_check_1.out', r'all guards pass|REFUSING'), DRYF, last(DRYF, r'DRY RUN COMPLETE|REFUSING|exit')[:200]),
 '- **Heads read at pin vs the commission:** #1339 head `%s` (commission `%s`: **%s**); develop `%s` (commission `%s`: **%s**). Re-read by `ls-remote` AND the PULLS API AND the fetch (predict_1.out), again by the dry run (%s) and a final `ls-remote` (final_lsremote_1.out): %s — every pin still current: **%s**.' % (
     pr['head'], CH, 'EQUAL' if pr['head'] == CH else 'DIFFERENT', P['develop'], CD, 'EQUAL' if P['develop'] == CD else 'DIFFERENT', DRYF, fl, cur),
 '  - Develop tree `%s`; merge-base `%s` (develop itself, move EMPTY); **END_TREE `%s`** (%s); diff(develop, END) == the 28 own paths, every END blob == the head blob (MG-1).' % (P['develop_tree'], pr['merge_base'][:12], P['end_tree'], P['end_shortstat']),
 '- **Controls, both ways (controls_gate41.sh):**',
 '  - normal (controls_1.out, rc %s): `%s`' % (rc('controls_1.rc'), last('controls_1.out', r'^SUMMARY')),
 '  - `--invert` (controls_2.out, rc %s): `%s`' % (rc('controls_2.rc'), last('controls_2.out', r'^SUMMARY')),
 '- **Simulations (predict):** %s (`moved` must PASS; `foreign<n>` must REFUSE).' % '; '.join('%s -> rc %s %s' % (k, v[0], v[1]) for k, v in sims.items()),
 '- **Pinned predict** (predict_1.out, rc %s): `%s`.' % (rc('predict_1.out.rc'), last('predict_1.out', r'^(PASS|REFUSED):')),
 '- **Requirement 1 — the clean install (MEASURED by the drafter, installprobe_1.out, rc %s: standalone `npm ci --ignore-scripts` of each service lock — the Dockerfile\'s own install line — npm %s, node %s, controls %s):** %s. So a CLEAN install of the head\'s locks DOES resolve nodemailer 10.0.12, and host npm 11.5.1 runs `npm ci` from these locks fine (the seat\'s `edgesOut` crash was `npm install`). The ROOT workspace install the suites run from is NOT measured — the gate owes it.' % (
     rc('installprobe_1.rc'), IP['npm'], IP['node'], 'ALL PASS' if all(IP['controls'].values()) else j(IP['controls']), j({k: '%s (%s)' % (v['nodemailer'], v['nodemailer_entry']) for k, v in SU.items()})),
 '- **Requirement 5 — morgan (MEASURED, same installs):** base morgan %s logs the planted quote RAW (escaped %s — the injection the advisory names, and the proof the probe can see it); head morgan %s escapes it (escaped %s); the control request logs in full on both.' % (
     SU['base_auth']['morgan'], SU['base_auth']['morgan_planted_quote_escaped'], SU['head_auth']['morgan'], SU['head_auth']['morgan_planted_quote_escaped']),
 '- **Requirements 2-4, 6-9 (READ by the drafter, owed by the gate):** originate — %s; audit — %s; %s; undici — %s; ip-address — %s; subject %s.' % (
     strip(last('predict_1.out', r"ORIGINATE'S RUNNER IS JEST")).split('ORIGINATE\'S RUNNER IS JEST, NOT VITEST: ')[-1][:260], strip(last('predict_1.out', r'AUDIT BASELINE'))[:260], strip(last('predict_1.out', r'IN-SCOPE locks'))[:240],
     strip(last('predict_1.out', r'UNDICI root copy'))[:160], strip(last('predict_1.out', r'IP-ADDRESS: a 9.x copy'))[:160], strip(last('keyscan_1.out', r'MANDATED squash text'))[:200]),
 '- **Linear:** %s. **Key scan:** title KS-1378; body KS-1378 + KS-729 (both own); commit message KS-1378 only (keyscan_1.out). **Kam\'s card (decisions.json, READ):** %s.' % (last('linear_reads_1.out', r'^#1339 attachmentsForURL')[:200], strip(last('predict_1.out', r"Kam's card"))[:200]),
 '- **Re-key / namespace (rekey_1.out, gate40\'s AND gate39\'s namespaces):** %s' % last('rekey_1.out', r'^RESULT'),
 '- **Sizes / sha256:** %s; %s; %s.' % (sz(PR), sz(L), sz(CAP)), '',
 '## 2. Doubts and contradictions the drafter found (each READ or MEASURED as stated)',
 '1. **The seat\'s "PRE-EXISTING" originate failure is most likely an instrument fault, not a product state (READ):** services/originate\'s `test` script is `jest` (jest ^29.7 + ts-jest, jest.config.js; 73 test files call `jest.mock(`, 0 import vitest). The seat\'s transcript (nmtest.out) prints vitest\'s `Test Files  93 failed (93)` / `Tests  no tests` shape — a VITEST run over a JEST suite. The gate (requirement 2) runs originate with `npm test` at base and head; until then "pre-existing" and "does not load" are both unproven.',
 '2. **The seat\'s install harness printed "install rc=0" after "npm error code EOVERRIDE" (READ, nmtest.out)** — a piped rc; the next line "nodemailer now: 9.1.1" is what exposed it. Every suite count in the READY and the PR body ran on nodemailer 9.1.1.',
 '3. **"Zero vulnerable copies of any of the four remain" is true IN SCOPE (READ):** 0 across the 39 in-scope locks; the declared out-of-scope tree `Blockchain/Dev/mobile/secuura-app` (lock-discovery.mjs OUT_OF_SCOPE_LOCKS, KS-769 — Kam ruled it "Dormant but kept"; leg 7 does not audit it) pins **undici 6.28.0**, below the seat\'s own typed first-patched 6.28.1. Whether 6.28.0 is inside GHSA-3wwx-pv8p-q78v\'s real range the gate reads from the advisory. Not a blocker by itself (out of scope, not shipped); a qualifier the claim needs.',
 '4. **ELEVEN OPEN PRs overlap #1339\'s paths (MEASURED, predict (c)) — declared, not disjoint:** dependabot %s and #920 (KS-734). gate40\'s kit.json listed ten of them as disjoint in-flight PRs; for a lock bump they are not. After #1339 lands every one conflicts on the root package-lock.json / package.json and service manifests (dependabot rebases its own; #920 needs its owner). If Wednesday or anyone merges one of them FIRST, develop moves over #1339\'s own paths and the launch refuses rc 10 (a re-draft; the seat would also have to regenerate locks).' % ', '.join('#' + x for x in DOS if x != '920'),
 '5. **@types/nodemailer 8.0.2 sits beside nodemailer 10, which ships its OWN declarations (READ + MEASURED layout):** 10.0.0 migrated to TypeScript, `"type": "module"`, exports map import -> dist/esm, require -> dist/cjs; the CJS entry exports createTransport both directly and on `.default` (`__esModule` true). Which declarations tsc picks for `import nodemailer from \'nodemailer\'` / `nodemailer.Transporter` is unmeasured — the gate\'s tsc per service decides it.',
 '6. **The only 9 -> 10 BREAKING CHANGE listed is "Node.js 20 or newer is required" (READ, CHANGELOG.md of the installed 10.0.12)** — the services run node:24-alpine (auth Dockerfile READ) and the host v24.7.0. Both call sites are byte-identical base -> head; both option shapes built on 10.0.12 (MEASURED, streamTransport / no connection). No real SMTP exchange was driven.',
 '7. **The mandated body carries `Refs KS-729` although the commit message does not (READ):** the PR body has both Refs lines and Linear links both as `contributes`; the commit message carries only `Refs KS-1378`. The merger composes. The audit tool prints the CLEANUP rows with KS-470 / KS-729 HYPHENATED (leg6.out) — quoting them verbatim in the squash body would attach KS-470 (Done, archived): a foreign key.',
 '8. **The audit fuse (READ, handover + READY):** "the audit fuse — 21.9 h, computed 2026-09-29T02:08Z" — after 2026-09-30T00:00Z every Blockchain/Dev push and merge is refused unless Kam\'s own DKIM mail reaches secuura-blockchain@. A GO issued after it may not be mergeable. Not this PR\'s defect; Kam\'s clock.',
 '9. **The six HELD `-b43-` branches (READ, handover):** KS-1371 / KS-1359 / KS-1369 / KS-1360 / KS-1375 / KS-1054 committed, NOT pushed, all waiting for #1339 to merge. The WIDEN census refuses the launch (rc 15) if any is opened as a PR first — as intended; the successor must not push them before this gate launches.',
 '10. **GitHub mergeable_state `unstable`** (gh_read_1.out) — mergeable True; not measured further (Actions are retired; no claim either way).',
 '11. **Two push logs exist; the READY cites the second (READ):** the seat\'s first push returned RC 1 with nothing pushed; push1378.out ends `RC=0` and the branch is at origin (ls-remote). The push log is in the seat\'s SESSION SCRATCHPAD, not its record folder — it can vanish on a reboot; the capture holds its STOP counts and its last 40 lines.', '',
 '## 3. Pins and what the gate owes',
 '- Prompt `%s` — the NINE requirements BY NAME as kit rules 40-44 / 46-49 (+ 50 the Tier-1 cap; the launcher refuses a prompt missing any; the R<exit> controls split each): the clean install with the resolved nodemailer version; auth AND originate on nodemailer 10 with originate proved at the base; the 9 -> 10 changelog against both call sites per service; audit legs 6 and 7 at the head, baseline untouched, the two CLEANUP rows named; morgan combined + a planted quote escaped; undici scoped to jsdom and ip-address with no 9.x; every lock-touched suite with before/after counts; the cross-package guards; the GO string, the subject rule and Refs KS-1378 + KS-729. `## MERGE ADDENDUM` last, ONE LINE (rule 52).' % K['prompt'],
 '- Report dir `/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/%s/` (TEXT only); mail FROM coagent@ TO wednesday-agent@, subject `[QA -> Wednesday] GATE41 batch #1339 (Seat B43, round 41; T1: KS-1378 the four-package advisory bump, nodemailer 9 -> 10)`.' % K['report'], '',
 '## 4. Routing line — NOT added',
 'Add this ONE line to `/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/inbox_routing.conf` (beside the other QA/Secuura batch lines) — backup first:',
 '```', '%s|coagent@agentmail.to|yes' % K['pane'], '```',
 'Until it is present the launch action\'s step 0 refuses rc 1 (%s reports it: `%s`; control RB measures the real refusal rc 1). The dry run found NO other refusal.' % (DRYF, last(DRYF, r'line present:')), '',
 '## 5. Controls: `controls_gate41.sh <scratchpad> [--invert]`',
 '- gate40\'s arms re-cut for #1339: wrong heads (C2 = the develop sha as the head), a moved develop (predev = the #1332 squash, MERGED), a path rename, capture / prompt doctoring, every kit rule 35 / 40-44 / 46-55 SPLIT (the nine requirements among them), the GO string and merge authority, the addendum, the verdict subject, a wrong END_TREE, a moved launcher, the non-TTY launch path, repin argv / routing / WIDEN by title and by branch (the twin matches #1339\'s own `-b43-7`) / a false (self-)STACK / the REAL re-pin across a move in a copy / RE-RN-RO plants and **RDO (NEW: one declared open-PR overlap dropped -> the re-pin refuses rc 10)**, predict `--simulate foreign1339` and `moved`, fill from SIM / failed pins, SJ1-SJ4 subject plants (SJ4: NO declared subject must refuse — gate41\'s fill never defaults to the title), and NS[<spelling>] over gate40\'s AND gate39\'s namespaces.',
 '- Not controlled: exit 16 (needs a TTY), repin steps 4-6 (usage gate, cockpit add), a `mergeable=False` refusal, installprobe beyond its built-in controls (CT1-CT6).', '',
 '## 6. Could not measure (the drafter\'s NOT-MEASURED list)',
 '- The ROOT workspace `npm ci` (1936 packages + a postinstall that builds every workspace) and require.resolve from each service dir; any vitest / jest suite (auth 836, originate, the other nine, packages/shared, frontend/issuer); tsc; eslint; audit legs 6 / 7 and the audit contract (they call the npm advisory API — the drafter made no advisory call); a real SMTP exchange on nodemailer 10; morgan through a real service app (only through the installed package); the real advisory range for the mobile tree\'s undici 6.28.0. Every suite figure (77 files / 836, "93 failed", legs 23/25 and 18/18) is a seat claim.', '',
 '## 7. Files',
 '- Kit: kit.json · COMMISSION.md (make_commission_gate41.py) · README.md (make_readme_gate41.py) · rekey_check_gate41.py -> rekey_1.out',
 '- Pins: predict_gate41.py -> predict_1.out(.rc), predict_sim_*.out(.rc), pins_gate41.json (+ .SIM-*.json) · keyscan_gate41.py -> keyscan_1.out · final_lsremote_1.out',
 '- Measurements: installprobe_gate41.py + installprobe_gate41.cjs -> installprobe_1.out (+ .rc), installprobe_gate41.json',
 '- Reads: gh_read_gate41.py -> gh_read_1.out, gh_body_1339.md, gh_comments_1339.md · linear_reads_gate41.py -> linear_reads_1.out, linear_KS-1378.md, linear_KS-729.md · capture_mail_gate41.py -> capture_1.out, mail_gate41_ready.md, stopcounts_gate41.json · _api_peek_gate41.py -> _api_peek_1.out',
 '- Prompt/launcher: prompt_gate41.TEMPLATE.txt, launcher_gate41.TEMPLATE.sh.txt, fill_gate41.py -> %s + %s (fill_1.out), launcher_check_1.out · repin_and_launch_gate41.sh -> %s · controls_gate41.sh -> controls_1.out / controls_2.out (+ .rc) — both complete runs of ONE unedited script (its sha256 taken before the first run and compared after the second: controls_sha.txt). Every controls run wrote to the Data-volume scratchpad and was copied in, byte-checked. One COSMETIC slip in that script, left unedited so both runs stay runs of the same bytes: control SJ4\'s LABEL still reads gate40\'s "(the PR title as read, landing at 93)"; the control itself refuses for gate41\'s reason (SJ4.out: `#1339 has NO declared subject (SHORT)`).' % (K['prompt'], K['launcher'], ', '.join(os.path.basename(f) for f in DRY)), '',
 '## 8. The ONE launch command (after the routing line, §4)', '```', launch, '```',
 '- Dry run: append `--dry-run`. Argument 2 may be ANY existing Claude session scratchpad dir (`/private/tmp/claude-501/*/scratchpad*`, the Data volume); if `g41_sp/clone.git` is absent there, predict rebuilds it on a re-pin (installprobe is NOT re-run by a re-pin). A develop move re-pins in the same action (step 3b); an own-path move (e.g. a declared dependabot PR merging first), an undeclared open-PR overlap or an END-tree disagreement refuses rc 10; a further `-b43-<n>` PR (any of Seat B 43rd\'s six held branches) or a KS-1378-titled PR refuses rc 15; a moved head refuses rc 11.']
open(os.path.join(D, 'README.md'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('wrote %s (%d lines) — launch: %s' % (os.path.join(D, 'README.md'), len(out), launch))
