#!/bin/bash
# launch_qa_secuura_batch1346.sh — cross-project QA agent, ONE BATCH gate (gate44, round 44) over TWO Secuura/Blockchain PRs, FROZEN at TWO:
# #1346 KS-1054 (T1, a deploy-path change) · #1347 KS-1374 (T2). Merge order 1346 1347. Author and merger: Seat B 45th.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate44.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-29T09:22:56Z.
# develop bd740147c3d88fbf45af109fd68fd35f602c2914; END_TREE 0c16f76bd6ccffb38130966e428f47ba2e8da82d (the two squashes chained in order). Shape copied from gate44's launcher, cut to two rows.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  a head is not at its branch AND refs/pull/<n>/head on origin.   exit 8: thinking directive / capture + commission named / an unfilled token / row count.
# exit 10: a GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name every head in full.   exit 7: the tier lines + FROZEN at TWO.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state the tickets.   exit 33: the by-name keyword ladder.   exit 39: the HOLDS.
# exit 26: merge authority + the GO string.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST (nothing into report.md after the mail).   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G44_* test override set.
# G44_CUR_DEV / G44_HEAD_<n> / G44_PATHS_<n> / G44_BRIEF / G44_PROMPT: test overrides (--check only).
# Generated by fill_gate44.py at 2026-09-29T09:29:11Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1346.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-29_gate44'
BRIEF="${G44_BRIEF:-$GS/mail_gate44_ready.md}"
PROMPT_FILE="${G44_PROMPT:-$GS/2026-09-29_secuura-batch1346.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1346|KS-1054|refs/heads/feature/ks-1054-deploy-scripts-read-startupmigrations-b43-6|2075c3ec70789d9a87a6359fccf1a58d97db3255|4|1|0aa9b52c691bb852e3fd1b796514fe9122ebc054|5|Blockchain/Dev/deployment/azure/check-startup-migrations.sh,Blockchain/Dev/deployment/azure/deploy-all.sh,Blockchain/Dev/deployment/azure/deploy.sh,Blockchain/Dev/scripts/__tests__/ks1054_deploy_scripts_read_startup_migrations.test.sh|T1"
  "1347|KS-1374|refs/heads/feature/ks-1374-local-templates-10000-and-akto-reads-platform-b45-1|2c4b98253b1fa820c4fe08585dad5da57947ffb4|5|1|bd740147c3d88fbf45af109fd68fd35f602c2914|0|Blockchain/Dev/.env.example,Blockchain/Dev/env.example,Blockchain/Dev/services/api-gateway/src/__tests__/ks1374-global-limiter-at-demo-limit.test.ts,systemTest/akto/src/setup/aktoRateLimit.ts,systemTest/akto/tests/unit/setup/ks1374-platform-limit-from-env.test.ts|T2"
)
DEVELOP_SHA='bd740147c3d88fbf45af109fd68fd35f602c2914'
END_TREE='0c16f76bd6ccffb38130966e428f47ba2e8da82d'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate44.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is TWO PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate44_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" && grep -qF "$GS/linear_gate44.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture, the Linear read and the commission at $GS" >&2; exit 8; }
[ -s "$GS/linear_gate44.md" ] || { echo "REFUSING: the Linear read $GS/linear_gate44.md is missing or empty" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + every branch + every pull/head
CUR_DEV="${G44_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate44.sh (it re-pins and re-fills in one action)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G44_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G44_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
for _kt in 'PR #1346 is KS-1054' 'PR #1347 is KS-1374'; do
  has "$_kt" && grep -qF -- "${_kt#PR }" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state '$_kt'" >&2; exit 32; }
done
has '#1346 T1' && has '#1347 T2' && has 'The batch is FROZEN at TWO PRs' && has 'TIER 1 = FULL WEIGHT' && has 'TIER 2 = THROUGH-CODE ONLY' && has 'a DEPLOY-PATH change' || { echo "REFUSING: the tier lines / FROZEN at TWO" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control" >&2; exit 33; }
for _w in RED-AT-BASE GREEN-AT-HEAD TAMPER-RIGHT-REASON TAMPER-UNIQUE-ANCHOR RESTORE-SHA256 WHOLE-SUITE-BEFORE-AFTER NO-NEW-RED TSC-BEFORE-AFTER SUITES-AT-END CENSUS-TESTS-RUN CENSUS-LISTED SUBJECT-KEY-SCAN SUBJECT-LANDS-AT REFS-OWN-KEY NO-CLOSING-KEYWORD END-TREE MERGE-ORDER-T1-FIRST OVERLAP-MEASURED NO-REBASE-NEEDED BEHIND-5-NOT-2 MODE-100755-RECORDED-1346 TAMPER-MODE-100644-1346 TAMPER-KEY-ON-ERROR-1346 ABSENT-FIELD-PASSES-WARNS-1346 TEST-HALF-0-11-1346 DEPLOY-PATH-DRIVEN-1346 DEPLOY-SH-EXIT-CODE-1346 RAN-FALSE-1346 PASS-LINE-ON-SKIP-1346 W1-GREEN-AT-BASE-1347 AKTO-OWN-NPM-CI-1347 DOTENV-ORDER-1347 LOWER-LIMIT-1-UNPACED-1347 PROD-COMPOSE-TEMPLATE-1347 CI-TEMPLATE-1347 CORRECTION-LINES-1347 PETER-0914-1347 DISK-ENOSPC TIERING REPORT-HASH-LAST; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the heads" && has 'GO (Seat B 45th): merge 1346 1347 on gate44' && has 'The merge seat is Seat B 45th' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after these merges' && has 'MG-1 9 over 9 paths' && has 'MODE check-startup-migrations.sh 100755' && has 'is the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE44 batch #1346 #1347 (Seat B45, round 44; T1: KS-1054 deploy scripts read startupMigrations; T2: KS-1374 local limit + Akto reads it)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-09-29-batch1346-g44/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G44_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-400
  echo "  capture, Linear read, prompt, QA project and repo present; kit at its filled home; TWO rows; thinking directive; capture + Linear read + commission named; no unfilled token"
  echo "  2 of 2 heads at branch AND pull/head (whole-field); 2 of 2 GitHub compares == the pins; capture and prompt BOTH carry every head in full and the tickets"
  echo "  the prompt carries 40 by-name keywords, the tier lines, the holds, the GO string, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G44_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
