#!/bin/bash
# launch_qa_secuura_batch1369.sh — cross-project QA agent, ONE gate (gate53, round 53) over ONE Secuura/Blockchain PR, FROZEN at ONE:
# #1369 KS-530 (T1, ROUND 1): a scoped @prisma/dev override in the root manifest, the one nested @hono/node-server 1.19.11 lock entry pruned,
# the GHSA-frvp-7c67-39w9 audit-baseline row removed.
# Merger: Seat B 54th (author). EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate53.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-10-01T14:37:32Z.
# develop ea6fcecc3a6f71a4f397ea678da54a06df130cd7; END_TREE d0f0389e191820ff3dc2d9c98d9d661336eb90e3 (the simulated squash, == the seat's PREDICTED tree). Shape copied from gate51a's / gate52's launchers (a NEW COPY, never an edit), one row.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  the head is not at its branch AND refs/pull/<n>/head on origin.   exit 8: thinking directive / the kit files + rulings named + present / an unfilled token / row count.
# exit 10: the GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name the head in full.   exit 7: the tier line + FROZEN at ONE + the round + the tiering rule.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state the ticket.   exit 33: the by-name keyword ladder (each keyword AS A TOKEN) + the filename rule.   exit 39: the HOLDS + the named exceptions.
# exit 34: the NO-SERVER rule (no live server, no Schemathesis, no prisma dev server, no database, no deploy).
# exit 35: the 11 -> 9 rule (EXPLAIN WHICH ADVISORIES STOPPED BEING REPORTED, GHSA-92pp named, "two OTHER" ruled).
# exit 36: the REAL-FIX rule (an override that moves the lock but not the executed code is a FALSE FIX; bundled?; ERR_PACKAGE_PATH_NOT_EXPORTED; never from memory).
# exit 37: the NOT-THE-GATE'S items (KS-530 state, mergeable_state, the GHSA-92pp cleanup).   exit 38: the proportionality line (THE CHANGE IS SMALL, the usage figure, hard stop 90%, Kam's grant).
# exit 26: merge authority + the GO string.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST.   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G53_* test override set.
# G53_CUR_DEV / G53_HEAD_<n> / G53_PATHS_<n> / G53_BRIEF / G53_PROMPT: test overrides (--check only).
# Generated by fill_gate53.py at 2026-10-01T15:03:39Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1369.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-10-02_gate53'
BRIEF="${G53_BRIEF:-$GS/READY_1369_mail.md}"
PROMPT_FILE="${G53_PROMPT:-$GS/2026-10-02_secuura-batch1369.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
RULINGS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/briefs_staged'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1369|KS-530|refs/heads/feature/ks-530-hono-node-server-override-b54-1|ce051988b787f510c7ca5db5bbc474ef4b8a8492|3|1|ea6fcecc3a6f71a4f397ea678da54a06df130cd7|0|Blockchain/Dev/package-lock.json,Blockchain/Dev/package.json,Blockchain/Dev/scripts/audit/audit-baseline.json|T1"
)
DEVELOP_SHA='ea6fcecc3a6f71a4f397ea678da54a06df130cd7'
END_TREE='d0f0389e191820ff3dc2d9c98d9d661336eb90e3'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate53.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 1 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is ONE PR (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
for _f in READY_1369_mail.md COMMISSION.md lockdiff_1.out auditset_1.out registry_1.out images_1.out gh_read_1.out keyscan_1.out end_tree_crosscheck_1.out gh_body_1369.md npm_audit_base_1.json npm_audit_head_1.json; do
  [ -s "$GS/$_f" ] && grep -qF "$GS/$_f" "$PROMPT_FILE" || { echo "REFUSING: the kit file $GS/$_f is missing, empty, or not named in the prompt" >&2; exit 8; }
done
for _f in 2026-10-02_answer_seatB54_method.md 2026-10-01_answer_seatB54_q5.md 2026-10-01_seatB54_frvp-override.md; do
  [ -s "$RULINGS/$_f" ] && grep -qF "$RULINGS/$_f" "$PROMPT_FILE" || { echo "REFUSING: the ruling / brief $RULINGS/$_f is missing, empty, or not named in the prompt" >&2; exit 8; }
done
grep -qF "2026-10-01-batch1367-g52/report.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the previous round report (gate52)" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
grep -qF '<''PR>' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries the unpinned PR placeholder" >&2; exit 8; }   # spelled split so this file itself carries no placeholder
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + the branch + pull/head
CUR_DEV="${G53_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate53.sh (a develop move is a re-draft for this kit)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G53_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G53_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'PR #1369 is KS-530' && grep -qF -- '#1369 (KS-530)' "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state the ticket ('PR #1369 is KS-530' / '#1369 (KS-530)')" >&2; exit 32; }
has '#1369 T1' && has 'The gate is FROZEN at ONE PR' && has 'TIER 1 = A DEPENDENCY-RESOLUTION CHANGE ON THE SECURITY AUDIT PATH' && has 'ROUND 1 of its own PR' && has 'a round-1 NO GO goes back to the author for round 2' && has 'ship the closed instances, ticket the residue' || { echo "REFUSING: the tier line / FROZEN at ONE / the round / the tiering rule" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' && has 'ASSERT THE FILENAME TOO' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control / the filename rule" >&2; exit 33; }
for _w in NO-COLLATERAL PRISMA-DEV-BYTE-EQUAL OTHER-LOCKS-UNTOUCHED NPM-CI-HEAD LOCK-IDEMPOTENT INDEPENDENT-RESOLVE COUNTERFACTUAL EXTERNAL-NOT-BUNDLED RESOLVES-HOISTED PRISMA-RUNS CARET-NOT-GTE RED-FIRST AUDIT-LEGS REPORTED-11-TO-9 CLEANUP-VERBATIM ROW-KEYSET COHORT-TWO NO-IMAGE-READS-ROOT-LOCK SUITES-0-NEW-REDS TSC-NO-REGRESSION KEYSCAN-OWN-KEY NO-CLOSING-KEYWORD METHOD-STATED NO-TRAILER SUBJECT-LANDS-AT SUBJECT-TRUE-OF-DIFF PR-BODY-CLAIMS COLLISION-CENSUS NOT-TESTED-LIST CLEAN-MERGE END-TREE MODES TIERING DISK-ENOSPC REPORT-HASH-LAST; do   # AS A TOKEN: bounded by a non-[A-Za-z0-9-] character (MODES is not satisfied by MODES-X)
  printf '%s' "$PROMPT_JOINED" | grep -qE -- "(^|[^A-Za-z0-9-])$_w([^A-Za-z0-9-]|\$)" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'THE NO-SERVER RULE' && has 'No live server is started, no Schemathesis is run, and no prisma dev server is started in this gate' && has 'NO DATABASE IS READ IN THIS GATE' && has 'no deploy' || { echo "REFUSING: the NO-SERVER rule (no live server / no Schemathesis / no prisma dev server / no database)" >&2; exit 34; }
has 'EXPLAIN WHICH ADVISORIES STOPPED BEING REPORTED' && has 'GHSA-92pp-h63x-v22m' && has 'two OTHER advisories' && has 'an unexplained one is a Major' || { echo "REFUSING: the 11 -> 9 rule" >&2; exit 35; }
has 'AN OVERRIDE THAT MOVES THE LOCK BUT NOT THE EXECUTED CODE IS A FALSE FIX AND A BLOCKER' && has 'bundles' && has 'ERR_PACKAGE_PATH_NOT_EXPORTED' && has 'never from memory' || { echo "REFUSING: the REAL-FIX rule (requirement 3)" >&2; exit 36; }
has "NOT THE GATE'S TO RULE" && has "TICKET STATE IS WEDNESDAY'S" && has 'You change no ticket state' && has 'it is NOT this PR' || { echo "REFUSING: the NOT-THE-GATE'S items" >&2; exit 37; }
has 'THE CHANGE IS SMALL' && has 'KEEP THE PASS PROPORTIONATE' && has 'is at 95%' && has 'the hard stop is 90%' && has "Kam's 17:40:22 grant" || { echo "REFUSING: the proportionality line" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' && has 'Never read or write a real `.env`' && has 'No SSH to any host, no database read' && has 'NO checklist tick' && has 'no Akto scan against any stack' && has 'Reverts and plants live only in a SCRATCH worktree you created' && has 'THE NAMED EXCEPTIONS to those holds — these and NO others' && has 'No image is built unless requirement 6 names one that copies the root lock.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the head" && has 'GO (Seat B 54th): merge 1369 on gate53' && has 'The merge seat is Seat B 54th' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE' && has 'KEY-FREE' && has 'MG-11 subject <= 92' && has 'the FLEET STOP after this merge' && has 'MG-1 3 over 3 paths' && has 'LOCK 1 removed 0 added 0 changed 0 flips' && has 'BASELINE 25 -> 24' && has 'external not bundled' && has 'NO TRAILER' && has 'EVERY SUBJECT YOU PROPOSE MUST BE TRUE OF THE DIFF' && has 'is the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE53 #1369 (Seat B54 author and merger, round 53; T1 dependency resolution: a scoped @prisma/dev override, one nested lock entry pruned, the frvp baseline row removed)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-10-02-batch1369-g53/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G53_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-400
  echo "  capture (READY_1369), lockdiff / auditset (+ its two advisory reports) / registry / images / gh / keyscan / END cross-check reads, the PR body, the method + Q5 rulings and the brief, prompt, QA project and repo present; kit at its filled home; ONE row; thinking directive; every kit file + commission + gate52 report named; no unfilled token, no PR placeholder"
  echo "  1 of 1 head at branch AND pull/head (whole-field); the GitHub compare == the pins; capture and prompt BOTH carry the head in full and the ticket"
  echo "  the prompt carries 35 by-name keywords (as tokens), the tier line, the NO-SERVER rule, the 11 -> 9 rule, the REAL-FIX rule, the NOT-THE-GATE'S items, the proportionality line, the holds + named exceptions, the GO string, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G53_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
