#!/usr/bin/env python3
"""repin_brief_1034.py — RE-PIN the #1034 brief fd81a75f0 -> e4624218b by ASSERTED substitutions + one inserted RE-PIN section (the fd81a75f0 body is kept
as history; the RE-PIN section wins). Census numbers are read from GS/repin_census_bullet.md (written from out_repin/repin_table.out). Backup .pre-0918-repin."""
import hashlib, re
GS = '/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-17_gate1034'
B = '/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1034-ks1215-tier1.md'
s = open(B).read(); assert s == open(B + '.pre-0918-repin').read()
CENSUS = open(GS + '/repin_census_bullet.md').read().rstrip('\n')
def sub(old, new, n=1):
    global s
    c = s.count(old); assert c == n, (old[:90], c, n); s = s.replace(old, new)
sub("# QA Agent Invocation Brief — Secuura/Blockchain **TIER 1** **ROUND 1** gate (round 1 of 2 under the cap): PR #1034 (KS-1215, Seat A) @ `fd81a75f0688f6cbe1e5f79b061bb1369c88f477` — ",
    "# QA Agent Invocation Brief — Secuura/Blockchain **TIER 1** **ROUND 1** gate (round 1 of 2 under the cap): PR #1034 (KS-1215, Seat A) @ `e4624218bc29cda4c07b2d31ca18bba422cfbc3e` (**RE-PINNED** from `fd81a75f0`: develop `3961c2add` merged in, then the pre-gate register-connector fix) — ")
sub("**This gate does NOT authorise a merge. The merge waits for Kam's tap.**",
    "**This gate does not itself authorise a merge: #1034 merges on WEDNESDAY'S signed GO naming the head after this verdict (the TESTED grant). Kam's tap is #1032's condition, not this PR's** (the drafted set carried a copied Kam's-tap line; corrected at the re-pin, launcher exit 26).")
sub("**Drafted** 2026-09-17 23:02–23:4x AEST (clocks from `date`) by Wednesday's drafting subagent.",
    "**Drafted** 2026-09-17 23:02–23:4x AEST (clocks from `date`) by Wednesday's drafting subagent at `fd81a75f0`; **RE-PINNED 2026-09-18 01:38–02:xx AEST to `e4624218b`** by a re-pinning subagent (section RE-PIN below).")
REPIN = """
## RE-PIN — head `e4624218b`, develop `3961c2add` (read this before anything below; where a number differs, THIS section wins)

No gate ran on `fd81a75f0`. Inputs: the seat's HEAD MOVED mail `GS/mail_1034_headmoved.md` (15:33:54Z, spf/dkim/dmarc pass; its tamper tables are the **7th** successor's, the `rawAuthorization` sweep the 8th's own) and Wednesday's PRE-GATE ruling `GS/answer_pregate_register_connector.md` (13:51:51Z: fix it in #1034 before the gate; tier stays 1). Re-pinner scripts `GS/repin_*_1034.py`, outputs `GS/out_repin/`, clone + worktrees `wt_head` / `wt_dev` under the re-pinner's scratch `…/scratchpad/gate1034r/wd_Gy0cU2/`. **Rows marked re-pinner (measured) ran ONCE: still PREDICTIONS — re-measure.**

- **Shape (MEASURED, `out_repin/repin_setup.out`, `out_repin/compare_read.out`).** A fast-forward: `fd81a75f0` → **`96d859467`** (merge, parents `fd81a75f0` + `3961c2add`, tree `92256f2df` = `merge-tree fd81a75f0 × 3961c2add` = the drafter's prediction) → **`e4624218bc29cda4c07b2d31ca18bba422cfbc3e`** (the fix, one parent, tree **`6f912843b54cdcbcc7e6398d6766398f0e0c5ca9`**). `refs/pull/1034/head` and the branch = `e4624218b`, origin develop = **`3961c2add8e1637b32e638f8f0952c328c00833e`** (ls-remote 01:38:08, 01:40:22; branches API 01:38:38). merge-base(head, develop) = `3961c2add` = develop (is-ancestor rc 0).
- **The compare guard, re-pinned:** GitHub `compare develop...e4624218b` (01:38:38) = merge_base `3961c2add`, **status ahead, ahead 4** (`6c6fdc94e`, `fd81a75f0`, `96d859467`, `e4624218b`), behind 0, **files 3**; `git rev-list --count 3961c2add..e4624218b` = 4 (reverse 0); `git diff --name-only 3961c2add e4624218b` = the same 3. The launcher now asserts `3961c2add… ahead=4 files=3` (was `27e53ec3a… ahead=2 files=2`). PR API: head.sha `e4624218b`, 4 commits, 3 files, +419 −6, open, mergeable true (unstable), 0 reviews, 0 review comments; body 15,301 chars, `Refs KS-1215` ×2.
- **The 3 files vs develop (blob equality targets):** `middleware/auth.ts` `6e1668362` → **`bf09d315a`** (+9; unchanged since `fd81a75f0`; patch-id `70144bde53f1` = `0a2b1603f..6c6fdc94e`'s) · `routes/platform.ts` `4550401f8` → **`b80a8cd8d`** (+9 −6: `authHeaders` is `const auth = req.headers.authorization;` — the `rawAuthorization` preference gone; comment rewritten; patch-id `6f342c6049bf`) · the ks1215 test ABSENT → **`75006b5cf`** (+401, **20 cells** = the 16 + 🔴 register-connector key + REVOKED JWT (exchange OK and refused) · 🔴 key + LIVE JWT (exchange OK only) · control JWT-only SYSTEM_ADMIN 201 with its own Bearer · control key-only; the `../db` mock became SQL-aware, `organizations:register` joined the stub scopes, `TENANT_PROVISIONING_URL` is stubbed). `index.ts` stays `db127dbfa`; every other JUDGED file = develop.
- **Merge-in (MEASURED).** Brought `fd81a75f0..96d859467` = 8 files = develop's own delta `27e53ec3a..3961c2add` (#1031 originate, #1033 mysql2 override + audit baseline), every brought blob = develop's (control: not all = `fd81a75f0`'s); 0 api-gateway or shared files in it. **Merged tree over the current develop = `merge-tree e4624218b × 3961c2add` = `6f912843b` = the head tree** (develop is an ancestor): merged = head. **develop `3961c2add`'s api-gateway (`dea998d3f`) and shared (`dbd72dea0`) subtrees equal `27e53ec3a`'s**, so the drafter's develop census, HANG arms and suite counts stand for `3961c2add` by content; the gate still re-runs develop.
- **Checks (re-pinner, MEASURED 01:40:56–01:41:43, vitest 4.1.11 side install from `3961c2add`'s lock, 38/38 closure pins; load 6.5 → 17.4, other gates live; `out_repin/repin_suites.out`).** develop `3961c2add` **57 / 556** at default AND at 60 s, 0 failed, 0 pending · head **58 / 576** both ways, **ks1215 20 / 20** · project tsc rc 0 both (491 files, 0 tests) · test-including program (`Blockchain/Dev/qa_tsc_1034/`): develop 623 files / 57 tests rc 2 **32 lines in 11 files**; head 624 / 58, ks1215 IN it and NOT in the project program, **32 lines, identical per-file map, 0 in ks1215**; plant +1 (33, ks1215 1), restored sha-equal · eslint by rule and message: `auth.ts` `@typescript-eslint/no-unused-vars` "'error' is defined but never used." `:415` → `:424`; **`platform.ts` the same rule, "'err' is defined but never used." `:980` → `:983`** (pre-existing, +3 lines); the test 0 / 0; planted control fires (`:403`), restored.
- **Tampers at head (re-pinner, MEASURED 01:42:25–01:46:44, `GS/repin_tamper_1034.py`, `out_repin/tamper/`; every row 58 / 576 / pending 0, tsc 0, anchors 1, restored blob-equal, `git diff --quiet`; load 18–48).** The seat's r3 tables parsed from `…/seatA-7th/ks1215/r1-pregate/tamper_1215_r3_auth.py` (sha256 `990f28f704eed0a1`) and `…_r3_platform.py` (`1a454c0349e0e563`) by the restricted AST evaluator, never executed: **11 / 11 exactly as the HEAD MOVED mail, 35 reds, all AssertionError** — T0 0 · T0-DEFAULT 0 · RP-DEV 10 (the 9 + register revoked) · DELETE-REMOVED 10 · **O1 2 (STRUCTURAL ×2 only: all 18 runtime cells, the 4 register-connector cells included, stay green)** · AFTER-AWAIT 2 (STRUCTURAL) · NOSET 9 (ks1215 ×7 + ks480 ×2) · TI 0 · platform T0 0 · **RAW-BACK 2 (register revoked, register live)** · TI 0. Drafter rows re-run at the new head: X-DELETE-CASED **10** (was 9) · X-REQUIRED-ONLY 5 · X-EMPTY-NOT-DELETE 3 · X-ONPROXYREQ-RAW 9 · **X-BEARER-PREFIX-ONLY 0 · X-FETCH-RAW 0** (still unpinned; item 3) · X-PLATFORM-NO-RAW not re-run (it is now the shipped code). Re-pinner rows: **R-PLATFORM-RAW-FALLBACK** (`req.headers.authorization || rawAuthorization`) **1 red — register revoked only** (its refused-exchange half); the LIVE cell drives exchange OK only, so a fallback for a LIVE caller on a refused / dropped exchange has no dedicated cell (Minor test-gap candidate) · R-PLATFORM-EMPTY-BEARER (`?? ''`) 0 (inert control).
""" + CENSUS + """
- **NOT re-run by the re-pinner (left to the gate):** the develop census at `3961c2add` (content-identical subtrees to the drafter's `27e53ec3a` run: 558 forwards, 24 on register-connector); the HANG harness (`auth.ts` `bf09d315a` and `index.ts` `db127dbfa` are byte-identical to `fd81a75f0`, `platform.ts` is not on that path); the drafter's consequence runs; the legitimate-caller census (item 4); Linear.
- **Checkout readings (01:40:19, 01:40:25):** porcelain 0, `.git/worktrees` 112, **`.git/config` sha256 `2716d950dd2834b2`** (draft close read `f9ef2cb7e4b9fa5a`: another session changed it between 23:46 and 01:40 — record, not ours), refs 947, branch `feature/ks-597-b-caller-scoped-externalref`, api-gateway `node_modules/.vite` present. Listen census 01:47:28: 18 rows, 0 node listeners, 0 `login_stub.mjs` node processes (a plain `ps | grep login_stub.mjs` counts a live gate's own `claude` argv — match `node` in argv[0]).
- **The seat's worktree `worktrees/raise-0916-a` now holds KS-1101 WIP.** The r1-pregate runners hard-code it: parse, never execute, never enter.
- **In the sections below the `fd81a75f0` text is history.** Where it differs, THIS section wins: head **`e4624218b`**, tree **`6f912843b`**, develop / merge-base **`3961c2add`**, compare **ahead 4 files 3**, suites **57 / 556 → 58 / 576**, ks1215 **20** cells, merged tree **= head**, the seat's table **11 rows / 35 reds**, report directory **`/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks1215-1034-e4624218b-tier1-r1/`**.

### L0 — THE LEAD QUESTION AT THIS HEAD: the pre-gate round (measure before items 1–9)
**On the REAL gateway, does `POST /api/platform/organizations/register-connector` with a REVOKED Bearer + a valid key still reach `/api/tenants`, `/api/keys` (the security key mint) or `/api/audit` carrying the caller's Authorization?** Drafter at `fd81a75f0`: **24** such forwards, all on this route (every exchange outcome incl. OK × LIVE / REVOKED × 3 legs, 201), = develop's 24. **Now expected: 0.**
- Re-run the drafter's whole census (**3,258 requests per tree**: 85 `authenticateToken` routes + `/api/batch/verify` × {NOKEY, JUNK, OK, REFUSED, DROPPED, NONJSON} × {NONE, LIVE, REVOKED}; test `/api` + the `/api/v1` subset + production `/api/v1`) on **develop `3961c2add`** and **head `e4624218b`**; merged = head (tree-equal). Template: `GS/src/qa1034r-repin-probe.template.ts` (the drafter's + ONE extra `it` driving register-connector with a JWT-only SYSTEM_ADMIN). Grade: **at head, any connector-branch cell whose upstream hit carries the caller's Authorization = Blocker** (item 1's rule, unchanged). Planted controls: a develop N-1 row AND a `fd81a75f0` register-connector row must both be flagged.
- **Must hold:** a **JWT-only SYSTEM_ADMIN still 201** on register-connector with **its own Bearer** on all three upstream calls (legitimate shape L8 below); a **key-only connector still `connector-jwt`** on every hit; head vs develop differs ONLY on connector-branch caller forwards (now 558 → 0), **0 status differences**, 0 on NOKEY / JUNK keys or Bearer-less callers. The fix touches every `authHeaders` reader (`/api/platform/tenants*`, `/audit-log`, `/tenant-key*`, register-connector): say per route whether anything but the connector-branch forward changed.
- **The O1 structural-only result:** re-measure (re-pinner: 2 STRUCTURAL reds, every runtime cell green) and say whether any runtime cell distinguishes O1 from O3.
- **The two TICKET candidates stay leads graded TICKET, not Blockers, unless you MEASURE them reachable:** (a) the cache-get-throws HANG (drafter: not request-reachable; identical at develop; `exit` mode kills the process, `survive` hangs one request); (b) the exchange / key-validate fetch with no timeout (drafter: a request-reachable per-request hang, process keeps serving, both trees). If (a) is measured reachable by a request, item 2's rule applies.
- **Heavy runs, stated:** the re-pinner re-ran the head census only (above); the develop census, the HANG harness and the consequence runs are the gate's.
"""
anchor = "\n## Charter (read first, in full)"
assert s.count(anchor) == 1; s = s.replace(anchor, REPIN + anchor)
sub("| REPORT DIRECTORY | `/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1215-1034-fd81a75f0-tier1-r1/`.",
    "| REPORT DIRECTORY | `/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks1215-1034-e4624218b-tier1-r1/` (re-pinned; the `fd81a75f0` directory was never created).")
sub("## 1. Target (read 23:03–23:46 AEST", "## 1. Target — HISTORY at `fd81a75f0` (the RE-PIN section wins) (read 23:03–23:46 AEST")
sub("| L7 | junk key + live JWT on an optional mount | the JWT principal (KS-1207) | drafter (= develop) |\nL1–L5 and L7 must not change (Blocker). L6 is the intended change.",
    "| L7 | junk key + live JWT on an optional mount | the JWT principal (KS-1207) | drafter (= develop) |\n| L8 | JWT-only SYSTEM_ADMIN on register-connector | 201, its OWN Bearer on `/api/tenants`, `/api/keys`, `/api/audit` | ks1215 control cell; re-pinner census admin cells |\n| L9 | valid key + live / revoked JWT on register-connector | `connector-jwt` (exchange OK) or no Bearer (refused / dropped / non-JSON), never the caller's | re-pinner (e4624218b); develop / fd81a75f0: the caller's |\nL1–L5, L7 and L8 must not change (Blocker). L6 and L9 are the intended change.")
sub("**3. O3 placement, by tamper, on the WHOLE api-gateway suite at HEAD** (vitest 4.1.11, `--testTimeout=60000 --hookTimeout=60000` unless the row says default; denominator asserted 58/572/pending 0;",
    "**3. O3 placement, by tamper, on the WHOLE api-gateway suite at HEAD** (vitest 4.1.11, `--testTimeout=60000 --hookTimeout=60000` unless the row says default; denominator asserted **58/576**/pending 0 at `e4624218b` (58/572 was `fd81a75f0`);")
sub("The seat's 8 rows from its `ROWS` literal EXACTLY (drafter: 8/8, 28 reds).",
    "The seat's rows EXACTLY: at `e4624218b` the r3 tables, 11 rows (re-pinner: 11/11, 35 reds; the r2 8-row table below is `fd81a75f0` history).")
sub("Round 1 of 2: a NO GO goes back to the seat for one fix round.", "Round 1 of 2 (the pre-gate fix spent no round): a NO GO goes back to the seat for one fix round.")
sub("ONE line — GO, GO WITH FINDINGS, or NO GO — on `fd81a75f0688f6cbe1e5f79b061bb1369c88f477`, as the delta over develop `27e53ec3a` AND on the merged tree",
    "ONE line — GO, GO WITH FINDINGS, or NO GO — on `e4624218bc29cda4c07b2d31ca18bba422cfbc3e`, as the delta over develop `3961c2add` AND on the merged tree")
sub('**MERGE ADDENDUM** (give the merge seat this line, filled): "on Kam\'s tap only: squash fd81a75f0 onto develop <then-current; 27e53ec3a = the head\'s second parent; 3961c2add at draft close> (merged tree <OID>; drafter 92256f2df over 3961c2add, 6339c404c over 27e53ec3a);',
    '**MERGE ADDENDUM** (give the merge seat this line, filled): "on Wednesday\'s signed GO naming the head: squash e4624218b onto develop <then-current; 3961c2add = the merge-base at the re-pin> (merged tree <OID>; re-pinner 6f912843b = the head tree over 3961c2add);')
sub("equality targets after the squash: auth.ts blob bf09d315a / ks1215 test 5b7431af0 (ks1207 test stays f56bd48b9, ks480 test eca492723); api-gateway 57/556 at 27e53ec3a -> 58/572 at head",
    "equality targets after the squash: auth.ts blob bf09d315a / platform.ts b80a8cd8d / ks1215 test 75006b5cf (index.ts stays db127dbfa, ks1207 test f56bd48b9, ks480 test eca492723); api-gateway 57/556 at 3961c2add -> 58/576 at head")
sub("the register-connector forward <your ruling>,", "the register-connector forward <CLOSED / STILL OPEN at e4624218b, per your census>,")
sub("Subject EXACTLY: `[QA -> Wednesday] TIER 1 GATE #1034 (KS-1215) fd81a75f0 — <GO | GO WITH FINDINGS | NO GO>`",
    "Subject EXACTLY: `[QA -> Wednesday] TIER 1 GATE #1034 (KS-1215) e4624218b — <GO | GO WITH FINDINGS | NO GO>`")
sub("Report into **`/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1215-1034-fd81a75f0-tier1-r1/`**",
    "Report into **`/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-18-ks1215-1034-e4624218b-tier1-r1/`**")
sub("## RULE BEFORE LAUNCH (the drafter asks Wednesday — the gate grades by this section)",
    "## RULE BEFORE LAUNCH — RULED (Wednesday, 13:51:51Z; the gate grades by this section)\n**RULED: in #1034's scope — fixed before the gate** (`GS/answer_pregate_register_connector.md`): *\"A revoked session reaching the key mint is not a ship-with. Fix it in #1034 now, before its gate launches.\"* The seat pushed the fix at `e4624218b`. **The grading at this head: item 1's rule stands in full — any head connector-branch cell forwarding the caller's Authorization, register-connector included, is a Blocker (NO GO).** The re-pinner predicts 0 (RE-PIN census). The text below is the drafter's pre-ruling question at `fd81a75f0`, kept as history.\n\n### (history) the drafter's question at `fd81a75f0`")
bad = [l[:100] for l in s.split('\n') if "Kam's tap" in l and "Kam's tap is #1032's" not in l and 'copied Kam' not in l]
print("Kam's tap lines left:", bad); assert not bad
assert not re.search(r"waits for Kam.s tap|on Kam.s tap only", s) and "WEDNESDAY'S signed GO" in s
assert '\x00' not in s and 'e4624218bc29cda4c07b2d31ca18bba422cfbc3e' in s and 'ROUND 1' in s and 'TIER 1' in s and 'MERGE ADDENDUM' in s and 'CLOSED / STILL OPEN / NEW' in s
open(B, 'w').write(s); print('brief bytes', len(s.encode()), 'sha256', hashlib.sha256(s.encode()).hexdigest()[:16])
