#!/bin/bash
# launch_qa_secuura_1241-r2-t2.sh — cross-project QA agent, ONE TIER-2 gate over ONE Secuura/Blockchain PR of round 21: #1241 KS-1226 item 2,
# ROUND 2 OF 2 (the cap: a NO GO ships nothing and tickets the residue). Seat B 27th; a fast-forward of the round-1 head e2d0518df (gate21T2d: NO GO,
# LIVE-SHAPE NULL). systemTest/performance unitSuiteSlotIndependence.test.ts (its own product). LIVE-SHAPE through the REAL function owed. No Docker.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate21T2e.py, a scratch clone fetched from origin) at 2026-09-25T12:18:12Z, never adopted from a mail.
# BASE-INVARIANT: the PR was cut from the OLD develop aa600af94d69ad59db279d32cbbd7596931a739b; develop at generation 33ccff807eb2bb0a43c5d03ceb88d877b86950e1 (11 ahead of BASE); END_TREE (== the merged
# tree, one PR) c0f0e7c91b2efd8c754becb341185ddd871874cd. NO declared overlap. The compare check is three-dot (develop...head): merge_base, ahead 2, behind AND the file NAME.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate21T2e.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: the head is not at its branch AND refs/pull/1241/head on origin (a STALE HEAD REFUSES).
# exit 8:  one row; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head: merge_base == BASE, ahead 2, behind == pinned, files == the PR's OWN path by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate21T2e.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name the head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 23: verdict subject / sender.  exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 7: tier line + ROUND 2 OF 2.
# exit 30: capture AND prompt BOTH carry the seat items.  exit 31: BASE / develop / END_TREE in full.  exit 32: capture AND prompt state the ticket.
# exit 33: the by-name keyword ladder.  exit 34: BASE-INVARIANT rule (no declared overlap).  exit 35: NO DOCKER / NO DATABASE.  exit 36: the RED-PROOF rule.
# exit 37: the fleet STOP count is NOT claimable for #1241 + NO standalone run.  exit 38: LOAD (KS-1155, F4) + the anchoring wording.  exit 39: HOLDS.
# exit 40: LIVE-SHAPE rule (the real function, every real shape, NULL = NO GO).  exit 41: T-103 / T-CALL rule.  exit 42: ROUND-2 CAP rule.
# exit 43: the LOGIN_STUB REAPER rule.  exit 44: item 1 OUT of scope.
# QAB1241R2_CUR_DEV / QAB1241R2_HEAD / QAB1241R2_PATHS / QAB1241R2_BRIEF / QAB1241R2_PROMPT: test overrides (--check only); a launch with any set refuses (16).
# Generated by fill_gate21T2e.py at 2026-09-25T12:18:20Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_1241-r2-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-25_gate21T2e'
BRIEF="${QAB1241R2_BRIEF:-$GS/mail_gate21T2e_ready.md}"
PROMPT_FILE="${QAB1241R2_PROMPT:-$GS/2026-09-25_secuura-1241-r2-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|the PR's own paths (sorted, comma-joined — the base-invariant compare target)
PRS=(
  "1241|KS-1226|refs/heads/feature/ks-1226-unitsuiteslotindependence-summary-regex-returns-null-on-skipped-r22-skippedsummary-1|b4427d416592b40eb5ddb8727b2d6c31f3c7d067|1|2|systemTest/performance/tests/unit/utils/unitSuiteSlotIndependence.test.ts"
)
BASE_SHA='aa600af94d69ad59db279d32cbbd7596931a739b'
DEVELOP_SHA='33ccff807eb2bb0a43c5d03ceb88d877b86950e1'
DEV_BEHIND='11'
END_TREE='c0f0e7c91b2efd8c754becb341185ddd871874cd'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate21T2e.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 1 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is ONE PR" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate21T2e_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p <<< "$_pr"
  [ -n "${QAB1241R2_HEAD:-}" ] && _h="$QAB1241R2_HEAD"
  _lsr="$(git -C "$REPO" ls-remote origin "$_br" "refs/pull/$_n/head")"
  if ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]${_br}\$" || ! printf '%s\n' "$_lsr" | grep -q "^${_h}[[:space:]]refs/pull/${_n}/head\$"; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB1241R2_CUR_DEV:-$(git -C "$REPO" ls-remote origin refs/heads/develop | cut -f1)}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate21T2e.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_FLAT="${PRS[*]}" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
for pr in os.environ["PRS_FLAT"].split():
    n, tk, br, h, nf, na, paths = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p <<< "$_pr"
  [ -n "${QAB1241R2_PATHS:-}" ] && _p="$QAB1241R2_PATHS"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${BASE_SHA} ahead=${_a} behind=${DEV_BEHIND} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: the compare is not merge_base $BASE_SHA / ahead as pinned / behind $DEV_BEHIND / files == the PR's OWN path by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _p <<< "$_pr"
  grep -qF "$_h" "$BRIEF" && grep -qF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -F "#$_n" "$BRIEF" | grep -qF -- "$_t" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n T2" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n T2'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'TIER 2: THROUGH-CODE' && has 'ROUND 2 OF 2' || { echo "REFUSING: TIER 2 / ROUND 2 OF 2" >&2; exit 7; }
for _w in \
  'b4427d416592b40eb5ddb8727b2d6c31f3c7d067' \
  'e2d0518df402' \
  '12e840dc-9775-4267-bd00-5b07ff4f43ee' \
  '`passed` emitted unconditionally' \
  'two-word label' \
  'read by segment NAME, not position' \
  '5 cells RED' \
  '4 cells RED' \
  'Restored byte-identical both times' \
  '10/10 green' \
  'Full file 13/13' \
  '`childSuiteCounts` reads LIVE' \
  'binding, and tampering it reds them' \
  'Package unit suite 1095/1095' \
  '`tsc --noEmit -p tsconfig.json` clean' \
  'Your N-1 and N-2 findings are' \
  'the 15-leg preflight DID NOT RUN on this push' \
  '6 seconds' \
  'KS-1306' \
  'KS-1307' \
  'KS-1308' \
  'KS-1309' \
  'There is no N-4' \
  '3bad652d17cf' \
  'shared store delta 0' \
  'still In Progress' \
  'getStateString'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'TIER 2: THROUGH-CODE' \
  'THROUGH-CODE REVIEW' \
  'RED-PROOF CHECK OF THE PR'"'"'S OWN PROOF' \
  'RED AT BASE and GREEN AT HEAD' \
  'RESTORE BYTE-IDENTICALLY' \
  'A red proof must NAME WHY it went red' \
  'FINDINGS ONLY' \
  'A VERDICT IS VALID ONLY AT ITS HEAD' \
  'State the FAIL condition before each run' \
  'ROUND 2 OF 2 — THE CAP' \
  'SHIPS NOTHING and TICKETS THE RESIDUE' \
  'RESIDUE TICKET' \
  'is a DECISION and OUT of scope' \
  'ORIGIN ROUNDS' \
  '2026-09-25-batch1241-t2d' \
  'B-1 LIVE-SKIP-SHAPE' \
  'N-1 SUMMARY-READ-103' \
  'N-2 SELFREAD-SHAPE' \
  '2026-09-17-ks1211-1030-e43af4934-tier2-r1' \
  'RE-READ develop at your start' \
  'answer_seatB25_movedbase' \
  'THERE IS NO DECLARED OVERLAP' \
  'FAST-FORWARD' \
  'e68e2f0e837df86da527d775a3a49c631b0f5b17' \
  'module-private' \
  'NOT exported' \
  'index.UpGiHP7g.js' \
  'utils.BS4fH3nR.js' \
  'SummaryReporter' \
  'if (!this.isTTY) this.options.summary = false;' \
  'CONDITIONAL' \
  'LIVE-SHAPE (MANDATORY' \
  '(L1) CAPTURE' \
  '(L2) THROUGH THE REAL FUNCTION' \
  '(L3) THROUGH childSuiteCounts() ITSELF' \
  '(L4) BYTE FOR BYTE' \
  '(S1) skip+fail+pass' \
  '(S2) skip+pass' \
  '(S3) todo+pass' \
  '(S4) expected-fail+pass' \
  '(S5) pass-only' \
  '(S6) fail-only' \
  '(S7) a MULTI-FILE summary' \
  '(S8) skip-only' \
  '(S9) todo-only' \
  '(S10) orientation' \
  'it.skip' \
  'it.todo' \
  'it.fails' \
  '--reporter=default' \
  'cat -v' \
  'GATE-PROBE' \
  'fixturesSlot.test.ts' \
  '(E1)' \
  '(E4)' \
  'THE RULE' \
  'od -c' \
  '(R-A)' \
  '(R-D)' \
  '(R-B)' \
  '(R-C) T-CALL' \
  '(R-E)' \
  'T-103' \
  'Tamper :93 ALONE' \
  'PACKAGE SUITE, BEFORE / AFTER' \
  '--no-file-parallelism' \
  'PRESUITE-URLPATH' \
  'slotGateEntrypoints.test.ts' \
  '1095' \
  '1099' \
  'PER-FILE TYPECHECK DELTA 0' \
  'TS2322' \
  'prettier --check' \
  'THE FLEET STOP COUNT: NOT CLAIMABLE FOR #1241' \
  'NO DOCKER, NO DATABASE' \
  'LOAD (standing' \
  'KS-1155' \
  'LOGIN_STUB REAPER — YOUR OWN ONLY' \
  'LEADS for you to grade' \
  'THE RENDERER' \
  'CALLSITE' \
  'SYMMETRIC-FIXTURE' \
  'FIRST-MATCH' \
  'STALE-BODY' \
  'CAPTURE-PROVENANCE' \
  'LIVE-SHAPE-FAILONLY' \
  'report.md:188' \
  'INTEGRATION-UNWIRED' \
  'BY-NAME ITEMS' \
  'TIER AND ROUND' \
  'CENSUS v2' \
  'LINEAR LINK HYGIENE' \
  'MERGE ADDENDUM' \
  'MG-1' \
  'MG-3' \
  'MG-11' \
  'STAYS In Progress' \
  'KEY-FREE' \
  'NOT-PINNED' \
  'CARRY-FORWARD' \
  'READ THE WHOLE TEST FILE' \
  'NEVER `git clone --shared`' \
  'CLONE FROM ORIGIN' \
  'NEVER a fetch into it' \
  'Never enter any seat worktree' \
  '.push-lock-21' \
  'RESTORE DISK MODES FROM THE INDEX' \
  'ENDED BY PID' \
  'lsof -nP -iTCP -sTCP:LISTEN' \
  'never print a credential value' \
  'No memory maintenance' \
  'Datasec files and mail are out of scope entirely' \
  'EVIDENCE CLASS' \
  'NOT-TESTED.written-first.md' \
  'THE CONTEXT RULE' \
  'WRITE report.md BEFORE THE MAIL' \
  'coagent@agentmail.to' \
  'wednesday-agent@agentmail.to' \
  '2026-09-25-batch1241-t2e' \
  '2026-09-25-batch1218-t2c' \
  'the merging seat re-predicts' \
  'HOLDS (standing)' \
  'mail_gate21T2e_ready.md' \
  'COMMISSION.md'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'a sibling batch merging is not a difference' && has 'THERE IS NO DECLARED OVERLAP' && has 'there is no declared exception here' || { echo "REFUSING: the BASE-INVARIANT rule (no declared overlap)" >&2; exit 34; }
has 'NO DOCKER, NO DATABASE — none is needed' && has 'NEVER connect to it' && has 'NO Docker action of any kind' || { echo "REFUSING: the NO DOCKER / NO DATABASE rule" >&2; exit 35; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'RED on BOTH the round-1 reading and develop' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has 'THE FLEET STOP COUNT: NOT CLAIMABLE FOR #1241' && has 'there is NO 28/0 to claim for #1241' && has 'NO STANDALONE RUN of' || { echo "REFUSING: the fleet STOP count is not claimable / no standalone run" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; F4 for :127)' && has 'an ASSERTION failure is REAL' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed (the residue ticket is DESCRIBED, never filed)' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'LIVE-SHAPE (MANDATORY' && has 'THROUGH THE REAL CODE PATH — never a lifted regex, never a re-implementation, never a Python port' && has 'stdout AND stderr PIPED' && has 'NULL, a throw, or wrong counts on ANY real shape is NO GO for #1241 (blocking)' && has '(S6) fail-only' && has '(S7) a MULTI-FILE summary' && has 'BYTE FOR BYTE' || { echo "REFUSING: the LIVE-SHAPE rule" >&2; exit 40; }
has 'Tamper :93 ALONE' && has 'At least one KS-1226 cell must red on a :93-only change' && has 'T-CALL — the OTHER successor of round 1' || { echo "REFUSING: the T-103 / T-CALL rule" >&2; exit 41; }
has 'A NO GO at round 2 SHIPS NOTHING and TICKETS THE RESIDUE' && has 'you describe the RESIDUE TICKET for Wednesday to file' || { echo "REFUSING: the ROUND-2 CAP rule" >&2; exit 42; }
has 'never by name, never pid 1' && has 'report the count before / after' || { echo "REFUSING: the LOGIN_STUB REAPER rule" >&2; exit 43; }
has 'is a DECISION and OUT of scope' && has 'grade nothing about the budget' || { echo "REFUSING: item 1 OUT of scope" >&2; exit 44; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1241 batch`' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (1 over 1 path)' && has 'KEY-FREE' && has 'subject <= 92 chars' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 GATE #1241 round 2 of 2 (KS-1226 item 2, Seat B 27th)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$BASE_SHA" "$PROMPT_FILE" && grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: BASE / the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of BASE $BASE_SHA); head at branch AND pull/1241/head:$HEADS_NOTE; END_TREE $END_TREE"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head (merge_base, ahead, behind, the PR's own path by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; one row; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry the head in full, the ticket and 27 seat items; the prompt carries 124 by-name keywords and the base-invariant / no-docker / red-proof / fleet-STOP / load+anchoring / holds / LIVE-SHAPE / T-103+T-CALL / round-2 cap / reaper / item-1 rules, the GO string, the addendum rules, the verdict subject, BASE / develop / END_TREE in full"
  [ -n "${QAB1241R2_CUR_DEV:-}${QAB1241R2_HEAD:-}${QAB1241R2_PATHS:-}${QAB1241R2_BRIEF:-}${QAB1241R2_PROMPT:-}" ] && echo "  (a QAB1241R2_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ -z "${QAB1241R2_BRIEF:-}${QAB1241R2_PROMPT:-}${QAB1241R2_HEAD:-}${QAB1241R2_PATHS:-}${QAB1241R2_CUR_DEV:-}" ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
