#!/bin/bash
# launch_qa_secuura_batch1268-t2.sh — cross-project QA agent, ONE BATCH gate (gate25T2, tier 2 + tier 3) over FOUR Secuura/Blockchain PRs of round 25, FROZEN at four:
# #1268 KS-1318 + KS-1142 + KS-1316 (L7, T2) · #1270 KS-1275 (B 29th, T3) · #1271 KS-1164 (L7, T2) · #1273 KS-1321 (B 29th, T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate25.py, a --no-local scratch clone fetched from origin) at 2026-09-25T22:20:23Z, never adopted
# from a mail. develop at generation df5e9f5da6d23411e7b38a79a58aa20c04b6afe2 (10 ahead of the PRs' parent 4db87c3e4b98); END_TREE 8624ef60b994062290ff3772f568dddc63889b19.
# The compare check is three-dot (develop...head): merge_base, ahead, behind AND the file NAMES, per PR.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate25T2.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  four rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate25T2.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at four.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: THE READER RULE (#1268, #1273). exit 47: #1270's TIER-3 PROOF. exit 48: #1271's MAGIC-WORD-CLOSES + TITLE-OVER-92. exit 35: no Docker / no stack / no port. exit 37: #1271's fleet STOP is NOT APPLICABLE. exit 44: the declared scope. exit 49: B 29th's merge authority.
# QAB25T2_CUR_DEV / QAB25T2_HEAD_<n> / QAB25T2_PATHS_<n> / QAB25T2_BRIEF / QAB25T2_PROMPT: test overrides (--check only); a launch with any QAB25T2_* set refuses (16).
# Generated by fill_gate25.py at 2026-09-25T22:20:28Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1268-t2.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-26_gate25T2'
BRIEF="${QAB25T2_BRIEF:-$GS/mail_gate25T2_ready.md}"
PROMPT_FILE="${QAB25T2_PROMPT:-$GS/2026-09-26_secuura-batch1268-t2.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1268|KS-1318 + KS-1142 + KS-1316|refs/heads/feature/ks-1318-ks781-default-shapes-tag-set-l7r25-1|a8e0fca70ed41ef061cc99a325b610d27f08c7fb|2|1|4db87c3e4b98b8e366c3dd60d5f399917bad5086|10|Blockchain/Dev/packages/shared/src/__tests__/entrypoint-corpus.test.ts,Blockchain/Dev/packages/shared/src/__tests__/ks781-p3-3-body-parser-order.test.ts|T2"
  "1270|KS-1275|refs/heads/feature/ks-1275-lifecycle-verb-prose-b29-1|448b8b7fdd87a145acc895c4138811f34aa53c59|2|1|4db87c3e4b98b8e366c3dd60d5f399917bad5086|10|Blockchain/Dev/services/originate/src/repositories/lifecycleEventRepo.ts,Blockchain/Dev/services/originate/src/routes/documents.ts|T3"
  "1271|KS-1164|refs/heads/feature/ks-1164-gate-report-samepath-refusal-l7r25-1|c9ea1dc1705f10f4b40ccc786604da6768a2c2fb|4|1|4db87c3e4b98b8e366c3dd60d5f399917bad5086|10|systemTest/performance/gate/report.ts,systemTest/performance/runner/k6_docker.ts,systemTest/performance/tests/unit/gate/ks1164-write-gate-report-never-overwrites-its-input.test.ts,systemTest/performance/tests/unit/runner/ks1164-k6-log-mount-never-collides.test.ts|T2"
  "1273|KS-1321|refs/heads/feature/ks-1321-description-word-boundary-b29-2|b800791a3295f048b40f920435b080a270c65106|1|1|4db87c3e4b98b8e366c3dd60d5f399917bad5086|10|Blockchain/Dev/services/originate/src/__tests__/ks978-published-contract-organizationuuid.test.ts|T2"
)
DEVELOP_SHA='df5e9f5da6d23411e7b38a79a58aa20c04b6afe2'
DEV_BEHIND='10'
END_TREE='8624ef60b994062290ff3772f568dddc63889b19'
_ovr() { local v="QAB25T2_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate25T2.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 4 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is FOUR PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate25T2_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB25T2_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate25T2.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        c = get(api + os.environ["CUR_DEV"] + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at four' && has 'TIER 2: THROUGH-CODE' || { echo "REFUSING: the tier definition / FROZEN at four" >&2; exit 7; }
for _w in \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.' \
  'EQUIVALENT at 3155 and 89849 bytes, 0 diagnostics.' \
  'includes() returns ["version"] for ALL THREE' \
  'Under develop'\''s walk with these cells present: exactly ONE red, W9.' \
  'the three ks781 errors marked "after #1268 merges"' \
  '**60 passed, 0 failed, 0 skipped (of 60)**'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'MAGIC-WORD-CLOSES' \
  'TITLE-OVER-92' \
  'NO-REFS-LINE' \
  'BACKTICK-SPAN' \
  'SUBSET-NOT-EQUAL' \
  'W13-UNDECIDED' \
  'KS1329-TSC' \
  'SYMLINK-SAMEPATH' \
  'SYSTEMTEST-NO-PREFLIGHT' \
  'EMIT-PROOF' \
  'COMMENT-CLAIMS' \
  'K1B-SOURCE-TEXT' \
  'CALL-SHAPES' \
  'PARAGRAPH-JOIN'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'A WRONG READING ON ANY REAL SHAPE = NO GO for that PR (blocking)' && has 'NAMES it (as a shape the check catches OR as a shape it declares safe)' && has 'THROUGH THE REAL CODE PATH — never a lifted regex, never a Python port' && has 'Do not soften the rule yourself' || { echo "REFUSING: THE READER RULE (#1268, #1273)" >&2; exit 40; }
has 'TIER 3 (#1270): THROUGH-CODE ONLY' && has 'TIER-3 PROOF FOR #1270 (EMIT-PROOF)' && has 'an instrument that cannot say DIFFERENT proves nothing' && has 'A DIFFERENT emit, or a code line in the diff = NO GO for that PR (blocking)' || { echo "REFUSING: #1270's TIER-3 PROOF" >&2; exit 47; }
has 'Linear linked KS-1164 to #1271 as **`closes`**' && has 'the merge addendum must carry a shortened subject' && has '(measured: 90, 74, 101 and 83 chars with ` (#NNNN)` — #1271 OVER)' || { echo "REFUSING: #1271's MAGIC-WORD-CLOSES + TITLE-OVER-92" >&2; exit 48; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has '#1271 is a systemTest/ push: NOT APPLICABLE' || { echo "REFUSING: #1271's fleet STOP is NOT APPLICABLE" >&2; exit 37; }
has 'DECLARED SCOPE (grade as disclosed scope, never as a defect of the PR)' && has 'A declared-scope item is still graded by THE READER RULE' || { echo "REFUSING: the declared scope" >&2; exit 44; }
has 'if it is LIVE at the GO it squashes its own PRs, otherwise the merge seat does' || { echo "REFUSING: B 29th's merge authority" >&2; exit 49; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1268, #1270, #1271, #1273 batch`' && has 'so #1268 and #1271 are squashed by a MERGE SEAT Wednesday names, never by an author' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (2 over 2 paths) for #1268 and #1270, (4 over 4 paths) for #1271, (1 over 1 path) for #1273' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] TIER-2 GATE batch #1268 #1270 #1271 #1273 (Seats L7 B29, round 25)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop ($DEV_BEHIND ahead of 4db87c3e4b98); heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE"
_ANY_OVR="$(env | grep -c '^QAB25T2_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; four rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 6 seat items; the prompt carries 14 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / THE READER RULE (#1268, #1273) / #1270's TIER-3 PROOF / #1271's MAGIC-WORD-CLOSES + TITLE-OVER-92 / no Docker / no stack / no port / #1271's fleet STOP is NOT APPLICABLE / the declared scope / B 29th's merge authority rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB25T2_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
