#!/usr/bin/env python3
"""family_index.py — the FAMILY-WEIGHT INDEX recommended by the 2026-09-10 ledger-fire
measurement (Kam ruled `measure-first` on card wed-boot-read-exceeds-the-context-window).

WHY: the resident ledger costs ~135K boot tokens and that measurement could trace ZERO
behaviour changes to reading a ROW. What WOULD be lost by archiving the prose is the
WEIGHT CONTINUITY — how a recurrence is recognised as a recurrence. This index keeps
exactly that, in a few KB, and leaves the prose one grep away in the archive.

METHOD, and its limits, because a count is a claim:
  * A "family" is keyed by the LESSON FILE a row cites via [[wikilink]] — 98% of rows do.
  * Rows are matched by regex over the WHOLE line, never by column index: row prose
    contains `|`, so field counts run 6..17 and an index-based parse silently reads the
    wrong field (it reported 2% of rows carrying a weight; the true figure is 47%).
  * `rows` is a HARD count: how many ledger rows cite this lesson. Trust it.
  * `max_w` is SOFT: the largest w=N appearing in a row that cites this lesson. A row
    citing several lessons attributes its weight to each, so max_w can overstate. It is
    a retrieval aid for "is this family high?", not an authority.
"""
import re, os, sys, collections, datetime

BRAIN = '/Volumes/DevMASTER/WEDNESDAY/0_Brain/learnings'
SRC   = [os.path.join(BRAIN, '_ledger.md'), os.path.join(BRAIN, '_ledger_archive.md')]
OUT   = os.path.join(BRAIN, '_family_index.md')

def rows():
    for path in SRC:
        if not os.path.exists(path):
            sys.exit(f"family_index: missing source {path} — refusing to write a partial index")
        for line in open(path):
            if line.startswith('| 2026-'):
                yield os.path.basename(path), line

def build():
    fams = collections.defaultdict(lambda: {'rows': 0, 'max_w': 0, 'last': '', 'resident': 0})
    total = linked = 0
    for src, line in rows():
        total += 1
        date = re.match(r'\| (\d{4}-\d{2}-\d{2})', line).group(1)
        ws   = [int(w) for w in re.findall(r'\bw=(\d+)', line)]
        links = {m.strip() for m in re.findall(r'\[\[([^\]|#]+)', line)}
        if links:
            linked += 1
        for l in links:
            f = fams[l]
            f['rows'] += 1
            f['max_w'] = max(f['max_w'], max(ws) if ws else 0)
            f['last']  = max(f['last'], date)
            if src == '_ledger.md':
                f['resident'] += 1
    return fams, total, linked

def main():
    fams, total, linked = build()
    on_disk = {f[:-3] for f in os.listdir(BRAIN) if f.endswith('.md') and not f.startswith('_')}
    broken  = sorted(k for k in fams if k not in on_disk)
    silent  = sorted(on_disk - set(fams))
    # Sort by the HARD count. Sorting by max_w put five different families at 144 —
    # multi-link rows attribute their weight to every lesson they cite, so that column
    # is an aid, not an order. The number you can defend is the one that sorts.
    order   = sorted(fams.items(), key=lambda kv: (-kv[1]['rows'], -kv[1]['max_w'], kv[0]))

    L = []
    L.append('---')
    L.append(f'date: {datetime.date.today()}')
    L.append('type: index')
    L.append('source: GENERATED by 2_Project_Files/tools/family_index.py — never hand-edit; the ledger and its archive are the source of truth')
    L.append('status: live')
    L.append('---')
    L.append('')
    L.append('# Family-weight index — what a recurrence is measured against')
    L.append('')
    L.append(f'Generated from **{total} ledger rows** ({linked} = {100*linked//total}% cite a lesson file) '
             f'across `_ledger.md` + `_ledger_archive.md`. **{len(fams)} families.**')
    L.append('')
    L.append('**`rows` is the hard count** — how many ledger rows cite this lesson; that is the number to '
             'quote when assigning a weight. **`max_w` is soft** — the largest `w=N` in any row citing it, '
             'and a row citing several lessons attributes its weight to each, so it can overstate. '
             '**Sorted by `rows`, not `max_w`** — five families share a max_w of 144 for that reason. '
             'Use `max_w` only to ask *"is this family high?"*, then `grep` the archive for the prose.')
    L.append('')
    L.append('| family (lesson file) | rows | resident | max_w | last |')
    L.append('|---|---|---|---|---|')
    for name, f in order:
        mark = '' if name in on_disk else ' ⚠ NO FILE'
        L.append(f"| [[{name}]]{mark} | {f['rows']} | {f['resident']} | {f['max_w'] or '—'} | {f['last']} |")
    L.append('')
    if broken:
        L.append(f'## ⚠ {len(broken)} cited names with no lesson file on disk')
        L.append('')
        L.append('A row points at a rule that cannot be opened — a rename, an alias, or a lesson never written.')
        L.append('')
        for b in broken:
            L.append(f'- `{b}` — {fams[b]["rows"]} row(s), last {fams[b]["last"]}')
        L.append('')
    if silent:
        L.append(f'## {len(silent)} lesson files never cited by any ledger row')
        L.append('')
        L.append('Not necessarily dead: a rule that never recurred is a rule that is WORKING. '
                 'But a rule nothing has ever cited is also how an unretrievable lesson looks.')
        L.append('')
        for s in silent:
            L.append(f'- [[{s}]]')
        L.append('')
    open(OUT, 'w').write('\n'.join(L) + '\n')
    print(f'family_index: {len(fams)} families from {total} rows -> {OUT}')
    print(f'  {len(broken)} broken link name(s), {len(silent)} never-cited lesson file(s)')

if __name__ == '__main__':
    main()
