#!/bin/bash
# safe_pull.sh — `git pull --rebase` for the WEDNESDAY repo that cannot lose dashboard STATE.
#
# WHY (ledger w=3, 2026-10-06 19:4x — "dashboard state swept by a stash"): three times in one day a
# bare `pull --rebase --autostash` (or a wholesale stash of 0_Brain/dashboard/data/) swept STATE files
# in with the generated feeds: the KS-1402 card in decisions.json vanished (09:5x), the Spark done.md
# rows sat in an unpopped autostash (10:5x), 12 panel posts in chat_wednesday.json rode an autostash
# (19:3x). Inspecting afterwards caught all three; this script is the prevention.
#
# WHAT IT DOES, in order:
#   1. Refuses if anything OUTSIDE 0_Brain/dashboard/data/ is dirty (commit your own files by pathspec
#      first — notes, briefs and tools are never this script's to stash or commit). Refuses mid-rebase.
#   2. Dashboard data, split by an ALLOW-LIST of generated feeds (GEN below):
#        GENERATED + dirty -> copied to 2_Project_Files/fleet/state/safe_pull/<stamp>/ (gitignored,
#                             KEPT — never deleted), then `git checkout --` so the rebase can run.
#        anything else dirty (decisions.json, the chat streams, pins, views, …) = STATE -> committed by
#                             pathspec in one "safe_pull: state" commit. State is never stashed.
#   3. `git pull --rebase` (NO --autostash). On a conflict: a STATE file holding a JSON list is UNIONED
#      (key = id, else (ts, text)); its order is origin's then ours-only. Any other conflict -> rebase
#      --abort, the copied feeds are restored, rc 3.
#   4. Copies the generated feeds back over the working tree (they are regenerated anyway; ours are
#      the newer reading). Prints what it did. Never drops a stash, never deletes a file.
# Exit: 0 ok · 2 refused before touching anything · 3 conflict it would not resolve (tree restored) ·
#       4 rebase failed for another reason (tree restored).
# Usage: safe_pull.sh [--dry-run]      (WED_REPO overrides the repo root, for the arms only)
set -u
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${WED_REPO:-$(cd "$SELF_DIR/../.." && pwd)}"
DATA="0_Brain/dashboard/data"
DRY=0; [ "${1:-}" = "--dry-run" ] && DRY=1
G() { git -C "$REPO" "$@"; }
say() { echo "safe_pull: $*"; }
die() { echo "safe_pull: REFUSED — $*" >&2; exit 2; }

# Generated feeds (regenerated by panel_sync / the dashboard collectors). Allow-list on purpose:
# a file not named here is treated as STATE, which is the safe direction.
is_gen() {
  case "$(basename "$1")" in
    agentmail.json|brain_state.json|news.json|parkinglot.json|tickets.json|chat_log.json) return 0 ;;
    datasec_calendar.json|personal_calendar.json|secuura_calendar.json) return 0 ;;
    linear_wed.json|linear_personal.json) return 0 ;;
    usage_*.json|*_error.json) return 0 ;;
  esac
  return 1
}

[ -d "$REPO/.git" ] || die "$REPO is not a git checkout"
[ -d "$REPO/.git/rebase-merge" ] || [ -d "$REPO/.git/rebase-apply" ] && die "a rebase is already in progress — finish or abort it by hand first"

# --- 1. classify the dirty set (tracked changes only; untracked files do not block a rebase) ---
DIRTY=$(G diff --name-only HEAD --) || die "git diff failed"
STAGED_OTHER=$(G diff --cached --name-only -- | grep -v "^$DATA/" || true)
[ -n "$STAGED_OTHER" ] && die "paths are STAGED outside $DATA (a pre-staged file rides into the next commit): $(echo $STAGED_OTHER)"
OUTSIDE=""; GEN=""; STATE=""
while IFS= read -r p; do
  [ -z "$p" ] && continue
  case "$p" in
    "$DATA"/*) if is_gen "$p"; then GEN="$GEN$p"$'\n'; else STATE="$STATE$p"$'\n'; fi ;;
    *) OUTSIDE="$OUTSIDE$p"$'\n' ;;
  esac
done <<< "$DIRTY"
[ -n "$OUTSIDE" ] && die "dirty outside $DATA — commit these by pathspec first: $(echo $OUTSIDE)"
say "generated feeds dirty: $(echo "$GEN" | grep -c . ) · state files dirty: $(echo "$STATE" | grep -c .)"
[ -n "$STATE" ] && say "state: $(echo $STATE)"
if [ "$DRY" = 1 ]; then say "dry run — nothing touched"; exit 0; fi

# --- 2. copy out generated feeds; commit state ---
STAMP=$(date +%Y%m%d-%H%M%S)
KEEP="$REPO/2_Project_Files/fleet/state/safe_pull/$STAMP"
mkdir -p "$KEEP" || { echo "safe_pull: cannot create $KEEP" >&2; exit 2; }
restore_gen() {
  [ -z "$GEN" ] && return 0
  while IFS= read -r p; do [ -n "$p" ] && cp -p "$KEEP/$p" "$REPO/$p"; done <<< "$GEN"
  say "generated feeds restored from $KEEP (copies kept)"
}
if [ -n "$GEN" ]; then
  while IFS= read -r p; do
    [ -z "$p" ] && continue
    mkdir -p "$KEEP/$(dirname "$p")" && cp -p "$REPO/$p" "$KEEP/$p" || { echo "safe_pull: copy-out FAILED for $p" >&2; exit 2; }
  done <<< "$GEN"
  # shellcheck disable=SC2086
  echo "$GEN" | grep . | while IFS= read -r p; do G checkout -- "$p"; done
  say "copied $(echo "$GEN" | grep -c .) generated feed(s) to $KEEP and reset them"
fi
if [ -n "$STATE" ]; then
  # shellcheck disable=SC2046
  G add -- $(echo $STATE) && G commit -q -m "safe_pull: state files ($(echo "$STATE" | grep -c .))" -- $(echo $STATE) \
    || { echo "safe_pull: state commit FAILED" >&2; restore_gen; exit 4; }
  say "committed state: $(G log -1 --format=%h)"
fi

# --- 3. pull --rebase, union state conflicts ---
union_json() {  # $1 = repo-relative path; writes the union of :2 (ours) and :3 (theirs)
  python3 -I - "$REPO" "$1" <<'PY'
import json, subprocess, sys
repo, path = sys.argv[1], sys.argv[2]
def stage(n):
    out = subprocess.run(["git", "-C", repo, "show", f":{n}:{path}"], capture_output=True, text=True)
    if out.returncode != 0: sys.exit(f"cannot read stage {n}: {out.stderr.strip()}")
    return json.loads(out.stdout)
a, b = stage(3), stage(2)          # during a rebase :3 is the commit being replayed (ours), :2 upstream
if not (isinstance(a, list) and isinstance(b, list)): sys.exit("not a JSON list — will not union")
def key(m):
    if isinstance(m, dict) and "id" in m: return ("id", m["id"])
    if isinstance(m, dict): return ("tt", m.get("ts"), m.get("text"))
    return ("raw", json.dumps(m, sort_keys=True))
seen, out = set(), []
for m in b + a:
    k = key(m)
    if k in seen: continue
    seen.add(k); out.append(m)
json.dump(out, open(f"{repo}/{path}", "w"), ensure_ascii=False, indent=1)
print(f"union {path}: upstream {len(b)} + ours-only {len(out)-len(b)} = {len(out)}")
PY
}
if ! G pull --rebase --no-autostash -q >"$KEEP.pull.out" 2>&1 && [ ! -d "$REPO/.git/rebase-merge" ] && [ ! -d "$REPO/.git/rebase-apply" ]; then
  echo "safe_pull: pull failed before any rebase:" >&2; cat "$KEEP.pull.out" >&2; restore_gen; exit 4
fi
ROUNDS=0
while [ -d "$REPO/.git/rebase-merge" ] || [ -d "$REPO/.git/rebase-apply" ]; do
  ROUNDS=$((ROUNDS+1)); [ $ROUNDS -gt 20 ] && { G rebase --abort; restore_gen; echo "safe_pull: >20 rebase rounds, aborted" >&2; exit 4; }
  CONF=$(G diff --name-only --diff-filter=U)
  [ -z "$CONF" ] && { GIT_EDITOR=true G rebase --continue >/dev/null 2>>"$KEEP.pull.out" || G rebase --skip >/dev/null 2>>"$KEEP.pull.out"; continue; }
  while IFS= read -r p; do
    [ -z "$p" ] && continue
    case "$p" in
      "$DATA"/*) if is_gen "$p" || ! union_json "$p"; then
                   G rebase --abort; restore_gen; echo "safe_pull: conflict in $p not unionable — aborted, tree restored" >&2; exit 3; fi
                 G add -- "$p" ;;
      *) G rebase --abort; restore_gen; echo "safe_pull: conflict outside dashboard data ($p) — aborted, tree restored" >&2; exit 3 ;;
    esac
  done <<< "$CONF"
  GIT_EDITOR=true G rebase --continue >/dev/null 2>>"$KEEP.pull.out" || true
done

# --- 4. put the generated feeds back ---
restore_gen
say "OK — HEAD $(G log -1 --format=%h) · ahead of origin: $(G rev-list --count @{u}..HEAD 2>/dev/null)"
