#!/bin/bash
# launch_qa_secuura_batch1316.sh — cross-project QA agent, ONE BATCH gate (gate34, T1 x4 + T2 x1) over 5 Secuura/Blockchain PRs of round 34, FROZEN at five:
# #1316 KS-1346 (B 36th (local-model patch, the Spark: KS-1346 C — originate routes/adminConfig.ts fail500 type-and-field-names + a NEW ks1346c cell), T1) · #1317 KS-1346 (B 36th (local-model patch, the Spark: KS-1346 D — originate routes/webhooks.ts fail500 type-and-field-names + a NEW ks1346d cell incl. the rotate-secret pin D7), T1) · #1318 KS-747 (B 36th (local-model patch, the Spark: KS-747 R2 — security security.openapi.ts declares organizationId (required, uuid) as a query parameter on GET /api/security/keys (the published path; the service's own route is GET /api/keys, which already answers 400 without it) + the regenerated docs/openapi/secuura-api.yaml companion + a NEW ks747 cell), T2) · #1319 KS-908 (B 36th (local-model patch, the Spark: KS-908 R2 — security index.ts returns connectorId from POST and GET /api/keys + a NEW ks908 cell), T1) · #1320 KS-692 (B 36th (local-model patch, the Spark: KS-692 R2 — vc-issuer routes/status.ts drops ISSUER_ADMIN from STATUS_WRITE_ROLES, Kam 2026-09-16 'Narrow now, bind-creator later' + a NEW ks692 cell; raised 22:25Z, AFTER the commission), T1)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate34.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-27T22:48:37Z, never adopted
# from a mail. develop at generation ec32c40e2b1e2698d2e855a916f390d48dad1b45; the PRs' merge-bases: ec32c40e2b1e2698d2e855a916f390d48dad1b45 for #1316, #1317, #1318, #1319, #1320; END_TREE 14b9382edbd7d605552402aaba7cd614e8bf8f3f.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate34: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate34.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  five rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate34.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at five.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the fail500 WIDEN rule. exit 41: the #1316 / #1317 fail500 rows. exit 42: the rotate-secret pin. exit 43: the #1319 keys row. exit 44: the READY identity. exit 46: the Linear link kinds. exit 47: the MG-3 key scan. exit 48: the squash-subject rule. exit 49: the no-op vs overlap keys. exit 50: the #1318 spec row. exit 51: the #1320 authorization row. exit 35: no Docker / no stack / no port.
# QAB34_CUR_DEV / QAB34_HEAD_<n> / QAB34_PATHS_<n> / QAB34_BRIEF / QAB34_PROMPT: test overrides (--check only); a launch with any QAB34_* set refuses (16).
# Generated by fill_gate34.py at 2026-09-27T22:48:41Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1316.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-28_gate34'
BRIEF="${QAB34_BRIEF:-$GS/mail_gate34_ready.md}"
PROMPT_FILE="${QAB34_PROMPT:-$GS/2026-09-28_secuura-batch1316.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1316|KS-1346|refs/heads/feature/ks-1346-adminconfig-fail500-type-and-field-names-b36-1|14fc80fb144c2b95f016cc325885c2684105c7cc|2|1|ec32c40e2b1e2698d2e855a916f390d48dad1b45|0|Blockchain/Dev/services/originate/src/__tests__/ks1346c-adminconfig-fail500-logs-type-and-field-names.test.ts,Blockchain/Dev/services/originate/src/routes/adminConfig.ts|T1"
  "1317|KS-1346|refs/heads/feature/ks-1346-webhooks-fail500-type-and-field-names-b36-2|2a688b24054929a66c85f7b9a9852a46f2edb8f6|2|1|ec32c40e2b1e2698d2e855a916f390d48dad1b45|0|Blockchain/Dev/services/originate/src/__tests__/ks1346d-webhooks-fail500-logs-type-and-field-names.test.ts,Blockchain/Dev/services/originate/src/routes/webhooks.ts|T1"
  "1318|KS-747|refs/heads/feature/ks-747-keys-list-spec-declares-organizationid-b36-3|62f9a288cf6032263ff183dfdc00ac1b60811f9d|3|1|ec32c40e2b1e2698d2e855a916f390d48dad1b45|0|Blockchain/Dev/docs/openapi/secuura-api.yaml,Blockchain/Dev/services/security/src/__tests__/ks747-keys-list-spec-declares-organizationid.test.ts,Blockchain/Dev/services/security/src/security.openapi.ts|T2"
  "1319|KS-908|refs/heads/feature/ks-908-connector-id-read-back-b36-4|07f42897e2afe381e5f91f54f04225077cf659d9|2|1|ec32c40e2b1e2698d2e855a916f390d48dad1b45|0|Blockchain/Dev/services/security/src/__tests__/ks908-connector-id-read-back.test.ts,Blockchain/Dev/services/security/src/index.ts|T1"
  "1320|KS-692|refs/heads/feature/ks-692-status-write-platform-only-b36-5|b9111f2bfad28f1bd63e787ae69a2de6b71a2d11|2|1|ec32c40e2b1e2698d2e855a916f390d48dad1b45|0|Blockchain/Dev/services/vc-issuer/src/__tests__/ks692-status-write-platform-only.test.ts,Blockchain/Dev/services/vc-issuer/src/routes/status.ts|T1"
)
DEVELOP_SHA='ec32c40e2b1e2698d2e855a916f390d48dad1b45'
END_TREE='14b9382edbd7d605552402aaba7cd614e8bf8f3f'
STACKS=''
_ovr() { local v="QAB34_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate34.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 5 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 5 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate34_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB34_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate34.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at five' && has 'MIXED TIERS, EACH PR GRADED AT ITS OWN TIER' || { echo "REFUSING: the tier definition / FROZEN at five" >&2; exit 7; }
for _w in \
  'Type and field names only' \
  '4 failed / 11 passed / 15' \
  '9 failed / 15' \
  '87 suites / 1028 tests / 0 failed' \
  '3 failed / 10 passed / 13' \
  '7 failed / 13' \
  '87 suites / 1026 tests / 0 failed' \
  'D7 is a pin, not a red.' \
  '2 failed / 3 passed / 5' \
  '24 files / 252 tests / 0 failed' \
  '`npm run check:openapi`: rc 0' \
  '2 failed / 2 passed / 4' \
  '24 files / 251 tests / 0 failed' \
  '(1 failed / 3 passed)' \
  '`services/security` has no `lint` script' \
  'Narrow now, bind-creator later' \
  '15 files / 140 tests / 0 failed' \
  'Tenant admins lose status writes' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'FAIL500-WIDEN' \
  'VALUES-NEVER-LOGGED' \
  'FIELD-NAMES-AS-DATA' \
  'TYPE-NAME-AS-DATA' \
  'THROWING-OWNKEYS' \
  'UNDER-1310-LOGGER' \
  'FAIL500-FAMILY-CLOSED' \
  'TYPE-AND-FIELD-NAMES' \
  'ADD1-INSPECT-ARM' \
  'SAME-KEY-TWO-PRS' \
  'ROTATE-SECRET-PIN' \
  'SPEC-DECLARES-NOT-ENFORCES' \
  'GENERATED-YAML' \
  'UUID-NOT-ENFORCED' \
  'CONNECTORID-READBACK' \
  'NO-KEYHASH-NO-PLAINTEXT' \
  'CROSS-TENANT-LIST' \
  'NARROW-NOW' \
  'NAMED-CONSEQUENCE' \
  'ALLOCATE-AND-CREATE-TOO' \
  'KS586-EACH-SHRINKS' \
  'READY-IDENTITY' \
  'GIT-APPLY-NOT-PATCH' \
  'ONE-BASE' \
  'SUBJECT-LANDS-AT' \
  'NOOP-VS-OVERLAP' \
  'FOREIGN-KEY-IN-COMMIT' \
  'ORIGINATE-COUNTS' \
  'SECURITY-COUNTS' \
  'VC-ISSUER-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'SECURITY-HAS-NO-LINT' \
  'LOCAL-MODEL-PROVENANCE'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'WIDEN — WHAT REACHES A LOG LINE OR A PRODUCTION LOG FILE FROM THE FAIL500 PATHS' && has 'grade by the rule, name the fields' && has 'a sentinel of YOUR OWN' || { echo "REFUSING: the fail500 WIDEN rule" >&2; exit 40; }
has 'THE FAIL500 ROWS (#1316, #1317;' && has 'Type and field names only' && has 'BOTH the C1 AND the C6 rows' || { echo "REFUSING: the #1316 / #1317 fail500 rows" >&2; exit 41; }
has 'THE ROTATE-SECRET PIN (#1317 D7;' && has 'a PIN, not a red' || { echo "REFUSING: the rotate-secret pin" >&2; exit 42; }
has 'THE KEYS ROW (#1319;' && has 'THROUGH THE ROUTE' && has 'no keyHash and no plaintext key in any list row' || { echo "REFUSING: the #1319 keys row" >&2; exit 43; }
has 'READY-IDENTITY: the drafter compared' && has 'the generated yaml' || { echo "REFUSING: the READY identity" >&2; exit 44; }
has 'all five PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'SQUASH SUBJECTS ARE DECLARED WITHOUT THE (#n) SUFFIX' && has 'len(declared) + len(" (#n)") <= 92' && has 'the merge tool refuses a declared subject matching' || { echo "REFUSING: the squash-subject rule" >&2; exit 48; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 49; }
has 'THE SPEC ROW (#1318;' && has 'the contract DECLARES, not what the endpoint enforces' || { echo "REFUSING: the #1318 spec row" >&2; exit 50; }
has 'THE AUTHORIZATION ROW (#1320;' && has 'Narrow now, bind-creator later' && has 'THE NAMED CONSEQUENCE' || { echo "REFUSING: the #1320 authorization row" >&2; exit 51; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1316, #1317, #1318, #1319, #1320 batch`' && has 'so all five are squashed by Seat B 36th, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (11 over 11 paths) for #1316, #1317, #1318, #1319 and #1320' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE34 batch #1316 #1317 #1318 #1319 #1320 (Seat B36, round 34; T1 x4 + T2 x1: KS-1346 C, KS-1346 D, KS-747, KS-908, KS-692)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB34_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 5 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 19 seat items; the prompt carries 33 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the fail500 WIDEN rule / the #1316 / #1317 fail500 rows / the rotate-secret pin / the #1319 keys row / the READY identity / the Linear link kinds / the MG-3 key scan / the squash-subject rule / the no-op vs overlap keys / the #1318 spec row / the #1320 authorization row / no Docker / no stack / no port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB34_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
