#!/usr/bin/env python3
"""gen_launcher_1014r2.py — derive launch_qa_secuura_ks1176_1014r2.sh from launchers/launch_qa_secuura_ks1176_1014.sh (the #1014 ROUND 1 launcher, itself
generated by gen_launcher_1014.py) by ASSERTED substitutions: every anchor must occur exactly as often as stated, or the generator refuses and writes nothing.
Re-points at the ROUND 2 head 9ba0caf78 (parent = round-1 head 616c766a5) / merge-base e0f41a8fa / develop eb1051fd3 (#1015's squash, auth only, NOT an
ancestor of the head: compare develop...head = merge_base e0f41a8fa ahead 2 behind 2 files 3); JUDGED 18 files (round 1's 16 + the #1016 ks1072 test + originate
routes/documents.ts, with the three #1014 files LANDED at their round-1 OR round-2 blobs and verification.ts / the ks1072 test also clearing at #1016's exact
head blobs); GUARDED = round 1's list + originate routes/documents.ts; DEV_CONTENT_ALLOWED = #1016's two exact blobs (judged by content). Adds the round-N rules
of the #1011 round-2 launcher: exit 24 (brief AND prompt name the prior round's REPORT path) and exit 25 (brief AND prompt require CLOSED / STILL OPEN / NEW),
and turns exit 15 / exit 23 to ROUND 2. Then a RESIDUAL GUARD (no round-1-only token survives outside the permitted mentions), output controls, heredoc
apostrophe/paren parity, no git write verb, no control bytes, bash -n. Never overwrites an existing output (writes a .pre-* copy first if one exists).
Usage: gen_launcher_1014r2.py <template launcher> <output launcher>
Exit: 0 written · 1 an anchor/control count disagreed · 2 a residual token survived · 3 bash -n failed"""
import datetime, hashlib, os, re, shutil, subprocess, sys
TPL, OUT = sys.argv[1], sys.argv[2]
s = open(TPL).read()
print('gen_launcher_1014r2', datetime.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z'), '| template sha256', hashlib.sha256(s.encode()).hexdigest()[:16], 'lines', s.count('\n'))

def cut(start, end_incl):
    i = s.index(start); j = s.index(end_incl, i) + len(end_incl); return s[i:j]

R1_REPORT = '/Volumes/DevMASTER/!CODING/Testing Agent MAIN/projects/secuura/reports/2026-09-17-ks1176-1014-616c766a5-tier1-r1/'

HEADER_OLD = cut('# launch_qa_secuura_ks1176_1014.sh', "# Exit: 0 launched (or guards passed under --check) · 2..23 a guard refused\n")
HEADER_NEW = """# launch_qa_secuura_ks1176_1014r2.sh — cross-project QA agent, ONE TIER 1 ROUND 2 DELTA gate (round 2 of 2 under the cap) over Secuura/Blockchain
# PR #1014 (KS-1176, Seat A) @ 9ba0caf78b8ddb737541df38303b776c982521d2 — ONE new commit on the round-1 head 616c766a5 (round 1: GO WITH FINDINGS,
# F-1 MAJOR ruled SHIPS-WITH): routes/verification.ts +6 -2 (the connector allow-list at :1216 resolves `body.documentType || body.type`, the key
# enforcement.ts:100 reads), enforcement.ts +3 -3 (why-comment reworded) and the ks1176 test +75 -5 (header reworded + describe F, five cells).
# TIER 1: an AUTHORISATION decision on POST /api/documents. The cap: a second NO GO ships the closed instances and tickets the residue.
#
# THE SHAPE, as read 07:29-07:53 AEST 2026-09-17 (git ls-remote + the compare API agree): merge-base = the PR parent e0f41a8fa (#1013's squash);
# develop has moved to eb1051fd3 (#1015's squash, KS-1018: services/auth routes/users.ts + a ks1018 test, landed 07:12:51) on 523f283c6 (#1011's
# squash), so develop is NOT an ancestor of the head: compare develop...head = merge_base e0f41a8fa, diverged, ahead 2, behind 2, files 3. The
# compare is asserted as merge_base + ahead + files (exit 10); `behind` is deliberately NOT asserted — the develop arm judges every move by CONTENT.
#
# The develop pin is judged by CONTENT, not bare: (a) EIGHTEEN files by blob at the CURRENT develop — the three #1014 files (enforcement.ts base
# 533cd309c, ks1176 test ABSENT, verification.ts base 04b3d980f; their round-1 OR round-2 blobs -> exit 19 LANDED), verification.ts ALSO clearing at
# #1016's head blob a7a6d4605 and the ks1072 test clearing ABSENT or at #1016's 4ad1cdcd1 (#1016, KS-1072, is open and gating: its hunk is @@ -298 in
# makeFetchDocFromAnchorStore, ~900 lines from #1014's @@ -1213; drafter merge-tree #1014 x #1016 clean), middleware/auth.ts, routes/admin.ts,
# services/redis.ts, src/index.ts, middleware/rateLimitEnforce.ts, middleware/audit.ts (a7be8626f OR #1011's 052131de0), api-gateway package.json /
# vitest.config.ts / vitest.setup.ts / tsconfig.json, Dev eslint.config.mjs, packages/shared crypto/jwks.ts, docs/openapi/secuura-api.yaml and
# services/originate/src/routes/documents.ts (brief item 3 reads its type resolution) — any blob nobody pinned -> exit 18; (b) if develop moved past
# eb1051fd3, the compare pinned...develop REFUSES (exit 18) when the delta touches a GUARDED path — services/api-gateway/src/ and its config files,
# packages/shared/src/crypto/ + middleware/ + verification/, the auth connector-JWT mint + internal route + authenticate + types, originate
# routes/documents.ts, the frontend DocumentUpload copy, docs/openapi/, eslint.config.mjs, the Dev lockfile — unless the file's blob is EXACTLY
# #1016's (DEV_CONTENT_ALLOWED), or the move cannot be judged. The #1016-landed arm is proven only up to the blob loop (fixture N10: the JUDGED loop
# accepts a7a6d4605 / 4ad1cdcd1 and the compare then refuses a diverged develop); no develop containing #1016 existed at draft time.
#
# exit 21: the LAUNCH path refuses when stdin is not a TTY. This launcher execs an interactive agent; run it in a cockpit
# pane, never inside a Bash tool — and never run it without --check to "prove" this guard. `--check` runs headless (it launches nothing).
# exit 22: the prompt must require node_modules farmed PER ENTRY (the #1009 gate's R-6: a wholesale link can write through to the checkout's .vite).
# exit 23: the prompt must carry the exact ROUND 2 verdict subject and name coagent@ as the sender and wednesday-agent@ as the recipient.
# exit 24: brief AND prompt must name the prior round's REPORT path (BRIEF_TEMPLATE round-N rule: the QA agent has no inbox).
# exit 25: brief AND prompt must require the per-finding CLOSED / STILL OPEN / NEW disposition (round 2 of 2: closed instances ship, residue is ticketed).
# QA1014R2_CUR_DEV (test override, --check only): stands in for origin develop so the LANDED / GUARDED refusals can be proven.
# A launch with any QA1014R2_* override set refuses (exit 16).
#
# Generated by gatesets/2026-09-17_gate1014r2/gen_launcher_1014r2.py from launch_qa_secuura_ks1176_1014.sh (asserted substitutions + residual
# guard + output controls + bash -n): same guards and exit codes, re-pointed at round 2, plus exits 24/25. Exit codes 2..25 (19 = LANDED).
#
# Usage: launch_qa_secuura_ks1176_1014r2.sh [--check]
# Exit: 0 launched (or guards passed under --check) · 2..25 a guard refused
"""

JUDGED_OLD = cut('G = D + "services/api-gateway/"\n', '  D + "docs/openapi/secuura-api.yaml":                                 ({"122d3a2f84cf77bf2b7e2dc51489a0d5f823db1f": "base"}, {}),\n}\n')
JUDGED_NEW = '''G = D + "services/api-gateway/"
# file -> (develop-OK blobs {blob: label}, LANDED blobs {blob: label}); ABSENT = the contents API answers 404 at develop
JUDGED = {
  G + "src/services/enforcement.ts":                                   ({"533cd309c56b8167ebe00b620744259b3cc186cc": "base"}, {"be466fbf444178bbb41293fb1d811957e55e1d2d": "#1014 round-2 own", "3e314ba116f85df0a8a37549272f8078c4c95ccd": "#1014 round-1 own"}),
  G + "src/__tests__/ks1176-connector-key-level-ranks-as-none.test.ts": ({"ABSENT": "base"}, {"43cebf8d75376f5a40252c5096fd02747c4f0a9e": "#1014 round-2 own", "5820520ae769aa5d118de2c1c5db4d1204d762e6": "#1014 round-1 own"}),
  G + "src/routes/verification.ts":                                    ({"04b3d980f657b13717060e9547d92970100b2557": "base", "a7a6d46057a18b3460e7d08bbec5df12ab763a81": "#1016 head a226d94fe KS-1072, judged by content"}, {"6bd095f621183b2aaf7a3611222815b5bf1026a3": "#1014 round-2 own"}),
  G + "src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts": ({"ABSENT": "base", "4ad1cdcd1e45044efdbb0b8e4e6eaf358453d780": "#1016 head a226d94fe KS-1072"}, {}),
  G + "src/middleware/auth.ts":                                        ({"20311010db0eb8ba097644ce105cf8df966ce456": "base"}, {}),
  G + "src/routes/admin.ts":                                           ({"f47dd6a655702ffbfc402ca920a33c4619d62c4b": "base"}, {}),
  G + "src/services/redis.ts":                                         ({"47659ee9c9f06acf9ac64e09b2dc207113ba92ea": "base"}, {}),
  G + "src/index.ts":                                                  ({"6f38c819e48162e3179aaf557085766f91beecc1": "base"}, {}),
  G + "src/middleware/rateLimitEnforce.ts":                            ({"fc5c5a4d934384745565e730cd12c0a0fcfcaa70": "base"}, {}),
  G + "src/middleware/audit.ts":                                       ({"a7be8626ff1d79a0887fb8d31c44286472157644": "base", "052131de06c3f510e4bcaadc9b6831d0cca617c2": "#1011 squash"}, {}),
  G + "package.json":                                                  ({"841d8c6adcd71e885c01e65c22da9418daff276a": "base"}, {}),
  G + "vitest.config.ts":                                              ({"5888e0b320d934f6f434e0e5ca3c74a995cecc02": "base"}, {}),
  G + "vitest.setup.ts":                                               ({"22c1107683b8192df3bfd3e929aa94aff3dc7d45": "base"}, {}),
  G + "tsconfig.json":                                                 ({"c981e6a92fdd2417fa35070eb979c5f1c77ffbcd": "base"}, {}),
  D + "eslint.config.mjs":                                             ({"8c5374c6022eb0a3f449f41a570db61294aa63f1": "base"}, {}),
  D + "packages/shared/src/crypto/jwks.ts":                            ({"a131d32caa3faf0f55ca9af1a4fcd889a1affa17": "base"}, {}),
  D + "docs/openapi/secuura-api.yaml":                                 ({"122d3a2f84cf77bf2b7e2dc51489a0d5f823db1f": "base"}, {}),
  D + "services/originate/src/routes/documents.ts":                    ({"c3a818ac8ac8de1b385540d15e3fbb23200cea30": "base"}, {}),
}
'''

ALLOW_OLD = cut('# pinned here. EMPTY for this gate:', 'DEV_CONTENT_ALLOWED = {\n}\n')
ALLOW_NEW = '''# pinned here. For this gate: the two files of #1016 KS-1072 at its head a226d94fe, judged by content at draft time 07:5x AEST: verification.ts
# hunk -298 in makeFetchDocFromAnchorStore only, 0 lines in POST /api/documents or the verify gate, merge-tree with #1014 clean in the drafter clone.
# Any other version of either file, and every other guarded hit, falls through to exit 18 — dependabot #649 / #575, the lockfile PRs and #922 included.
DEV_CONTENT_ALLOWED = {
  G + "src/routes/verification.ts": "a7a6d46057a18b3460e7d08bbec5df12ab763a81",
  G + "src/__tests__/ks1072-the-latest-anchor-selector-documents-a.test.ts": "4ad1cdcd1e45044efdbb0b8e4e6eaf358453d780",
}
'''

REPL = [
  # (label, old, new, expected count)
  ('header', HEADER_OLD, HEADER_NEW, 1),
  ('brief path', 'briefs/2026-09-17_secuura-1014-ks1176-tier1.md', 'briefs/2026-09-17_secuura-1014r2-ks1176-tier1.md', 2),
  ('prompt path', 'briefs/2026-09-17_secuura-1014-ks1176-tier1.prompt.txt', 'briefs/2026-09-17_secuura-1014r2-ks1176-tier1.prompt.txt', 1),
  ('override prefix', 'QA1014_', 'QA1014R2_', 10),
  ('head sha', 'HEAD_SHA="${QA1014R2_HEAD:-616c766a57a51238450c99bbf1d59bb109e3841c}"', 'HEAD_SHA="${QA1014R2_HEAD:-9ba0caf78b8ddb737541df38303b776c982521d2}"', 1),
  ('merge base', "MERGE_BASE='e0f41a8fafd64fa31524390cfeab320e822f3d15'   # the merge-base of the head with develop = the PR parent e0f41a8fa (#1013's squash)",
                 "MERGE_BASE='e0f41a8fafd64fa31524390cfeab320e822f3d15'   # the merge-base of the head with develop = the PR's base e0f41a8fa (#1013's squash); the round-2 head's own parent is the round-1 head 616c766a5", 1),
  ('develop sha', "DEVELOP_SHA='523f283c6cd2550263ec9869dc5ee722be40df4e'   # develop at draft time = #1011's squash on the PR parent, NOT an ancestor of the head (git ls-remote 06:11:56 and 06:22:44, branches API 06:20 AEST)",
                  "DEVELOP_SHA='eb1051fd39fe3edab4e0b1d1967515b758d4ba3f'   # develop at draft time = #1015's squash on #1011's, NOT an ancestor of the head (git ls-remote 07:29:17, 07:34:32 and 07:51:52, branches API 07:33 AEST)", 1),
  ('r1 report var', 'REAL_BRIEF="$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1014r2-ks1176-tier1.md"\n',
                    "R1_REPORT='" + R1_REPORT + "'\nREAL_BRIEF=\"$WED/2_Project_Files/fleet/qa-agent/briefs/2026-09-17_secuura-1014r2-ks1176-tier1.md\"\n", 1),
  ('head refuse', 'REFUSING: #1014 — $HEAD_SHA', 'REFUSING: #1014 ROUND 2 — $HEAD_SHA', 1),
  ('compare comment', '# develop...#1014 = e0f41a8fa ahead 1 files 2 (behind 1 at draft time; behind deliberately not asserted).', '# develop...#1014 = e0f41a8fa ahead 2 files 3 (behind 2 at draft time; behind deliberately not asserted).', 1),
  ('compare assert', '''[ "$COMPARE" = "$MERGE_BASE ahead=1 files=2" ] || { echo "REFUSING: #1014 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=1 files=2'" >&2; exit 10; }''',
                     '''[ "$COMPARE" = "$MERGE_BASE ahead=2 files=3" ] || { echo "REFUSING: #1014 ROUND 2 develop...head reads '$COMPARE', brief pins '$MERGE_BASE ahead=2 files=3'" >&2; exit 10; }''', 1),
  ('count comment', 'sixteen files by blob at the CURRENT develop', 'eighteen files by blob at the CURRENT develop', 1),
  ('judged', JUDGED_OLD, JUDGED_NEW, 1),
  ('landed msg', '#1014 has landed; this brief is stale', '#1014 (round 1 or round 2) has landed; this brief is stale', 1),
  ('ok same', '(= #1011 squash on the PR parent e0f41a8fa, NOT an ancestor of the head: the gate merges it; drafter merged tree 8589933267963afda8fc352279c4b694ed5bb3de; git ls-remote)',
              '(= #1015 squash on #1011 squash, NOT an ancestor of the head: the gate merges it; drafter merged tree 1372b3b66b6749e6fd9458db37b672ca753e28d7; #1016 still open; git ls-remote)', 1),
  ('guarded originate', '           D + "services/auth/src/types/index.ts",\n', '           D + "services/auth/src/types/index.ts",\n           D + "services/originate/src/routes/documents.ts",\n', 1),
  ('allow', ALLOW_OLD, ALLOW_NEW, 1),
  ('tail', 'the gate merges the then-current develop onto 616c766a5 in its own clone, rebuilds the shared dist there, runs the api-gateway suite and the principal census on the MERGED tree beside the base and head trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 7, 9)',
           'the gate merges the then-current develop onto 9ba0caf78 in its own clone, rebuilds the shared dist there, runs the api-gateway suite, the spelling census and the round-1 level census on the MERGED tree beside the base, r1 and head trees, names the merged-tree OID and re-derives every count, above all the api-gateway denominator (brief items 1, 2, 7)', 1),
  ('ok moved', 'disjoint from the GUARDED list (services/api-gateway/src/ + its config files, packages/shared/src/crypto|middleware|verification/, the auth connector-JWT mint + internal route + authenticate + types, the frontend DocumentUpload copy, docs/openapi/, eslint.config.mjs, the Dev lockfile)',
               'disjoint from the GUARDED list (services/api-gateway/src/ + its config files, packages/shared/src/crypto|middleware|verification/, the auth connector-JWT mint + internal route + authenticate + types, originate routes/documents.ts, the frontend DocumentUpload copy, docs/openapi/, eslint.config.mjs, the Dev lockfile) or cleared at the exact #1016 head blobs', 1),
  ('round grep', '''grep -q 'ROUND 1' "$BRIEF" && grep -q 'ROUND 1' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 1)" >&2; exit 15; }''',
                 '''grep -q 'ROUND 2' "$BRIEF" && grep -q 'ROUND 2' "$PROMPT_FILE" || { echo "REFUSING: brief and prompt disagree about the round (ROUND 2)" >&2; exit 15; }''', 1),
  ('subject + round-N rules',
   '''grep -qF '[QA -> Wednesday] TIER 1 GATE #1014 (KS-1176) 616c766a5' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \\
  || { echo "REFUSING: prompt does not carry the exact verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
''',
   '''grep -qF '[QA -> Wednesday] TIER 1 GATE #1014 ROUND 2 (KS-1176) 9ba0caf78' "$PROMPT_FILE" && grep -qF 'coagent@agentmail.to' "$PROMPT_FILE" && grep -qF 'wednesday-agent@agentmail.to' "$PROMPT_FILE" \\
  || { echo "REFUSING: prompt does not carry the exact ROUND 2 verdict subject, the coagent@ sender and the wednesday-agent@ recipient" >&2; exit 23; }
grep -qF "$R1_REPORT" "$PROMPT_FILE" && grep -qF "$R1_REPORT" "$BRIEF" \\
  || { echo "REFUSING: brief or prompt does not name the prior round REPORT path $R1_REPORT — the QA agent has no inbox; a carry-forward with no pointer can only be answered with I could not" >&2; exit 24; }
grep -qF 'CLOSED / STILL OPEN / NEW' "$PROMPT_FILE" && grep -qF 'CLOSED / STILL OPEN / NEW' "$BRIEF" \\
  || { echo "REFUSING: brief or prompt does not require the per-finding CLOSED / STILL OPEN / NEW disposition — round 2 of 2: closed instances ship and residue is ticketed" >&2; exit 25; }
''', 1),
  ('check round', 'echo "  brief and prompt agree on TIER 1 and ROUND 1"', 'echo "  brief and prompt agree on TIER 1 and ROUND 2"', 1),
  ('check subject', 'echo "  prompt carries the exact verdict subject, coagent@ sender, wednesday-agent@ recipient"\n',
                    'echo "  prompt carries the exact ROUND 2 verdict subject, coagent@ sender, wednesday-agent@ recipient"\n  echo "  brief and prompt name the prior round REPORT path"\n  echo "  brief and prompt require CLOSED / STILL OPEN / NEW per finding"\n', 1),
  ('check head', 'echo "  head on origin: #1014 $HEAD_SHA at $BRANCH"', 'echo "  head on origin: #1014 ROUND 2 $HEAD_SHA at $BRANCH"', 1),
  ('check compare', 'echo "  compare (GitHub API): develop...#1014 = $COMPARE"', 'echo "  compare (GitHub API): develop...#1014 ROUND 2 = $COMPARE"', 1),
]
bad = 0
for label, old, new, want in REPL:
    n = s.count(old)
    if n != want:
        print('ANCHOR COUNT', label, n, '!=', want); bad += 1; continue
    s = s.replace(old, new); print('  ok', label, n)
if bad: print('REFUSING: %d anchors disagreed; nothing written' % bad); sys.exit(1)
RESID = ['QA1014_', 'ROUND 1', 'sixteen', '8589933267', '523f283c6cd2550263ec9869dc5ee722be40df4e', 'ahead=1 files=2', '616c766a57a51238450c99bbf1d59bb109e3841c', 'principal census', 'tier1-r1/', 'launch_qa_secuura_ks1176_1014.sh']
PERMITTED = {'from launch_qa_secuura_ks1176_1014.sh': 1, R1_REPORT: 1}  # the template-name provenance mention; the R1_REPORT variable (it names the round-1 report on purpose)
stripped = s
for k, v in PERMITTED.items():
    if stripped.count(k) != v: print('PERMITTED count', repr(k), stripped.count(k), '!=', v); sys.exit(1)
    stripped = stripped.replace(k, '')
res = {t: stripped.count(t) for t in RESID if t in stripped}
if res: print('REFUSING: residual tokens', res); sys.exit(2)
CTL = {'#1014': None, '9ba0caf78b8ddb737541df38303b776c982521d2': 2, 'e0f41a8fafd64fa31524390cfeab320e822f3d15': 1, 'eb1051fd39fe3edab4e0b1d1967515b758d4ba3f': 1,
       'QA1014R2_': 12, '"ABSENT"': None, 'exit 19': None, 'exit 22': None, 'exit 23': None, 'exit 24': None, 'exit 25': None, 'exit 21': None, 'exit 16': None,
       'KS-1176': None, 'a7a6d46057a18b3460e7d08bbec5df12ab763a81': 2, '4ad1cdcd1e45044efdbb0b8e4e6eaf358453d780': 2, 'ROUND 2': None, 'CLOSED / STILL OPEN / NEW': None}
got = {k: s.count(k) for k in CTL}
print('output controls', got)
for k, v in CTL.items():
    if (v is not None and got[k] != v) or got[k] == 0: print('CONTROL DISAGREED', k, got[k], v); sys.exit(1)
for tag in ("<<'PY'\n", "<<'PYJ'\n"):
    i = s.index(tag); j = s.index('\nPY' + ('J' if 'PYJ' in tag else '') + '\n', i); blk = s[i:j]
    print('heredoc', tag.strip(), "apostrophes", blk.count("'") - 2, 'parens (', blk.count('('), ')', blk.count(')'))
    if (blk.count("'") - 2) % 2 or blk.count('(') != blk.count(')'): print('REFUSING: heredoc parity'); sys.exit(1)
if re.search(r'git -C "\$REPO" (fetch|push|checkout|merge|reset|worktree|commit|switch|pull)\b', s): print('REFUSING: git write verb'); sys.exit(1)
if re.search(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', s): print('REFUSING: control bytes'); sys.exit(1)
if os.path.exists(OUT):
    pre = OUT + '.pre-' + datetime.datetime.now().strftime('%H%M%S'); shutil.copyfile(OUT, pre); print('existing output copied to', pre)
open(OUT, 'w').write(s); os.chmod(OUT, 0o755)
p = subprocess.run(['bash', '-n', OUT], capture_output=True, text=True)
print('bash -n rc', p.returncode, p.stderr.strip()[:300])
if p.returncode: sys.exit(3)
print('written', OUT, 'sha256', hashlib.sha256(s.encode()).hexdigest()[:16], 'lines', s.count('\n'))
