#!/bin/bash
# launch_qa_secuura_batch1337.sh — cross-project QA agent, ONE BATCH gate (gate39, T2 + T1) over 2 Secuura/Blockchain PRs of round 39, FROZEN at two:
# #1332 KS-1054 (B 41st (ROUND 2 of 2, ITEM 2, seat-written, a fast-forward of Seat B 40th's round 1 f5381338: KS-1054 — a new 038a_ks1054_core_tables_before_039.sql creates oauth_apps, svc_webhooks, certifications and charge_events (DDL derived from CORE) so 039 finds them on its only pass under either runner (shape b); the CORE-stage catches now add to totalFailed (N-1332-2) and the recorded summary carries `error` (N-1332-3); round 1's 039 guard, /health field and four widened annotations unchanged), T1) · #1337 KS-888 (B 41st (ITEM 1, from a local-model READY: KS-888 / the KS 764 guard — TEST-ONLY, one file: both copies of the security revoke pattern in packages/shared ks764-key-revoke-call-site-guard.test.ts (CALL_SITES :84, REVOKE_WRITES :104) widened from an 80-character window to a pattern that admits ONLY whitespace, whole // comment lines and one try { between the flip and the save; a Spark golden, canonical patch == golden == the held checker patch), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate39.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-28T19:25:03Z, never adopted
# from a mail. develop at generation 215cc6875e2bac0b6d6b38918572384fbfcbdb77; the PRs' merge-bases: 0d156d12cc0fc45fc323397c6999898565c44c54 for #1332; 215cc6875e2bac0b6d6b38918572384fbfcbdb77 for #1337; END_TREE b5362672fb7f4d06aaa15a0c9c1f4d9c658040f8.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate39: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate39.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  two rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate39.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at two.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the #1337 guard row. exit 41: the #1332 three-path start-up row. exit 42: the #1332 disclosed not-covered. exit 43: the real-Postgres rule. exit 44: the merge order, #1337 first. exit 46: the Linear link kinds. exit 47: the MG-3 key scan. exit 48: the squash-subject rule. exit 49: the no-op vs overlap keys. exit 51: the GO subject names the merge seat. exit 52: the addendum one-line-per-PR shape. exit 53: the pre-existing red, named, green after #1337. exit 54: the cross-package guards. exit 55: the last round under the two-NO-GO cap. exit 56: the full-disk rule: Data volume, STOP on ENOSPC. exit 35: no Docker / no stack / no TCP port.
# QAB39_CUR_DEV / QAB39_HEAD_<n> / QAB39_PATHS_<n> / QAB39_BRIEF / QAB39_PROMPT: test overrides (--check only); a launch with any QAB39_* set refuses (16).
# Generated by fill_gate39.py at 2026-09-28T19:25:56Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1337.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-29_gate39'
BRIEF="${QAB39_BRIEF:-$GS/mail_gate39_ready.md}"
PROMPT_FILE="${QAB39_PROMPT:-$GS/2026-09-29_secuura-batch1337.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1332|KS-1054|refs/heads/feature/ks-1054-startup-migration-failure-on-health-b40-2|f2423bf7aa6c64952cf425d4160a048a55ffaaee|11|2|0d156d12cc0fc45fc323397c6999898565c44c54|35|Blockchain/Dev/migrations/038a_ks1054_core_tables_before_039.sql,Blockchain/Dev/migrations/039_rls_fail_closed.sql,Blockchain/Dev/services/api-gateway/src/__tests__/ks1054-startup-migration-failure-on-health.test.ts,Blockchain/Dev/services/api-gateway/src/__tests__/ks1054r2-core-throw-and-error-field.test.ts,Blockchain/Dev/services/api-gateway/src/__tests__/ks1062-startup-migrations-tenant-summary-first-error.test.ts,Blockchain/Dev/services/api-gateway/src/__tests__/ks1125-api-gateway-startup-migrations-the-tenant.test.ts,Blockchain/Dev/services/api-gateway/src/__tests__/ks1128-platform-tenant-seed-failure-warns.test.ts,Blockchain/Dev/services/api-gateway/src/__tests__/ks1272-platform-dedup-uuid-tenant-id.test.ts,Blockchain/Dev/services/api-gateway/src/services/health.ts,Blockchain/Dev/services/api-gateway/src/services/startupMigrationStatus.ts,Blockchain/Dev/services/api-gateway/src/startup-migrations.ts|T1"
  "1337|KS-888|refs/heads/feature/ks-888-ks764-guard-accepts-revoke-shape-b41-1|bb0067dde82ecda05d7c8ca465715d5a897a008d|1|1|215cc6875e2bac0b6d6b38918572384fbfcbdb77|0|Blockchain/Dev/packages/shared/src/__tests__/ks764-key-revoke-call-site-guard.test.ts|T2"
)
DEVELOP_SHA='215cc6875e2bac0b6d6b38918572384fbfcbdb77'
END_TREE='b5362672fb7f4d06aaa15a0c9c1f4d9c658040f8'
STACKS=''
_ovr() { local v="QAB39_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate39.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 2 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 2 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate39_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB39_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate39.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at two' && has 'T1 ROWS ARE GRADED THROUGH CODE AND AT RUNTIME' || { echo "REFUSING: the tier definition / FROZEN at two" >&2; exit 7; }
for _w in \
  '1 failed / 14 passed (15)' \
  '48 files, 1 failed / 944 (945)' \
  '48 files, 945 / 945' \
  '36 problems (1 error, 35 warnings)' \
  '14 passed / 1 failed' \
  'A hunk-offset mutation is NOT a valid control for `git apply --check`' \
  'The READY'\''s own A4 line is wrong.' \
  'Two of the three sides you named were NOT driven' \
  'The gateway runner was not driven' \
  'A second pass changes none of those five on mine.' \
  '88 files, 795 tests, 0 failed' \
  '29 → 29, delta 0' \
  'Three migrations that fail forever on the other two trees now succeed' \
  'reference these four tables, so an earlier number changes far more than the blocker needs' \
  'CORE'\''s definitions alone vs 038a alone, two bare databases, four tables' \
  'N-1332-5 is NOT in this commit' \
  'The KS 764 guard reds on this branch' \
  'A deploy must rebuild BOTH the migrations image and the api-gateway image.' \
  '10 → 8 passed / 2 failed' \
  'blind to a letter-suffixed migration' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'GUARD-GREEN-ON-END' \
  'PATCH-EQUALS-HELD-SPARK' \
  'GUARD-REDS-ON-BROKEN-REVOKE' \
  'GUARD-ARMS-ON-PRODUCT' \
  'A4-RED-COUNT' \
  'SWEEP-DRIFT-UNSEEN' \
  'ESLINT-DELTA-ZERO' \
  'OFFSET-NOT-A-CONTROL' \
  'THREE-PATHS-DRILL' \
  'GATEWAY-RUNNER-TWICE' \
  'RUNMIG-THEN-GATEWAY' \
  'INIT-THEN-GATEWAY' \
  'SECOND-BOOT-CHANGES-NOTHING' \
  'SCHEMA-EQUALITY-PG-DUMP' \
  'CERTIFICATIONS-NO-TENANT-POLICY' \
  'APP-ROLE-PROBE' \
  'LEXICAL-POSITION-038A' \
  'LOCALE-COLLATION' \
  'MIGRATIONS-006-008-047' \
  'OTHER-MIGRATIONS-UNCHANGED' \
  'CORE-THROW-COUNTED' \
  'ERROR-FIELD-SET' \
  'PLATFORM-CORE-CATCH' \
  'RUN-RECORD-WIRING' \
  'HEALTH-BODIES-AS-SERVED' \
  'READY-CODE-UNCHANGED' \
  'DEPLOY-READS-FAILED' \
  'COMPOSE-RUNNER-EXIT' \
  'ROUND1-DB-NOT-HEALED' \
  'MIGRATIONS-IMAGE-REBUILD' \
  'TS2322-DELTA-ZERO' \
  'THE-POSTGRES' \
  'LAST-ROUND-CAP' \
  'PRE-EXISTING-RED' \
  'CROSS-PACKAGE-GUARDS' \
  'KS764-DRIFT-CELL' \
  'MERGE-ORDER-1337-FIRST' \
  'TWO-BASES' \
  'SUBJECT-LANDS-AT' \
  'NOOP-VS-OVERLAP' \
  'NO-FOREIGN-KEY' \
  'ADDENDUM-ONE-LINE-PER-PR' \
  'SHARED-COUNTS' \
  'GATEWAY-COUNTS' \
  'AUTH-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'LOCAL-MODEL-PROVENANCE' \
  'DISK-ENOSPC' \
  'TIERING'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'THE GUARD ROW (#1337;' && has 'the PR diff EQUALS the held Spark patch' && has 'packages/shared 1 failed / 945 -> 945 / 945' && has 'the guard must still RED on a broken revoke' || { echo "REFUSING: the #1337 guard row" >&2; exit 40; }
has 'THE START-UP ROW (#1332 ROUND 2 of 2;' && has 'on a REAL PostgreSQL over a unix socket (no TCP)' && has '(i) a bare database through the GATEWAY runner' && has '(ii) a bare database through `scripts/run-migrations.sh` THEN a gateway boot' && has '(iii) a docker/init-seeded database then a gateway boot' && has 'byte-identical across (i), (ii), (iii) and develop'\''s seeded path' || { echo "REFUSING: the #1332 three-path start-up row" >&2; exit 41; }
has 'NOT COVERED, DISCLOSED (#1332):' && has 'N-1332-5 (the deploy scripts read the flag) is UNRAISED by ruling' && has 'it is not a NO GO for this round' || { echo "REFUSING: the #1332 disclosed not-covered" >&2; exit 42; }
has 'THE POSTGRES (#1332):' && has 'SAY SO PLAINLY' && has 'a socket directory shorter than 103 bytes' && has 'NEVER the native Postgres on :5432, never a container' || { echo "REFUSING: the real-Postgres rule" >&2; exit 43; }
has 'MERGE ORDER: #1337 FIRST' && has 'the pre-existing KS-764 guard red that #1337 fixes' || { echo "REFUSING: the merge order, #1337 first" >&2; exit 44; }
has 'every PR links its ticket as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' && has 'startup-migrations.ts and 038a carry foreign hyphenated keys as CONTENT' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'SQUASH SUBJECTS ARE DECLARED WITHOUT THE (#n) SUFFIX' && has 'len(declared) + len(" (#n)") <= 92' && has 'the merge tool refuses a declared subject matching' || { echo "REFUSING: the squash-subject rule" >&2; exit 48; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 49; }
has 'the SUBJECT of the GO mail NAMES Seat B 41st' && has 'GO (Seat B 41st): merge 1337 1332 on gate39' || { echo "REFUSING: the GO subject names the merge seat" >&2; exit 51; }
has 'THE ADDENDUM IS ONE LINE PER PR in exactly this shape' && has '- #NNNN · head <sha12> · subject: `<subject>`' && has 'NO sub-bullets' || { echo "REFUSING: the addendum one-line-per-PR shape" >&2; exit 52; }
has 'PRE-EXISTING RED, NAMED (standing requirement 1' && has 'must be GREEN on END_TREE after #1337' || { echo "REFUSING: the pre-existing red, named, green after #1337" >&2; exit 53; }
has 'CROSS-PACKAGE GUARDS (standing requirement 2' && has 'RUN every suite that references a changed path' && has 'every suite that reads the migrations DIRECTORY' || { echo "REFUSING: the cross-package guards" >&2; exit 54; }
has 'THE LAST ROUND (the two-NO-GO cap' && has 'this is ROUND 2 of 2 for #1332' || { echo "REFUSING: the last round under the two-NO-GO cap" >&2; exit 55; }
has 'DISK: /Volumes/DevMASTER is FULL' && has 'STOP on any ENOSPC' && has 'goes on the Data volume' || { echo "REFUSING: the full-disk rule: Data volume, STOP on ENOSPC" >&2; exit 56; }
has 'NO DOCKER, NO STACK, NO TCP PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no TCP port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1337, #1332 batch`' && has 'so both are squashed by Seat B 41st, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (12 over 12 paths) for #1337 and #1332' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE39 batch #1337 #1332 (Seat B41, round 39; T2 + T1: KS-888 the KS 764 guard, KS-1054 round 2 of 2)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB39_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 2 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 21 seat items; the prompt carries 49 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the #1337 guard row / the #1332 three-path start-up row / the #1332 disclosed not-covered / the real-Postgres rule / the merge order, #1337 first / the Linear link kinds / the MG-3 key scan / the squash-subject rule / the no-op vs overlap keys / the GO subject names the merge seat / the addendum one-line-per-PR shape / the pre-existing red, named, green after #1337 / the cross-package guards / the last round under the two-NO-GO cap / the full-disk rule: Data volume, STOP on ENOSPC / no Docker / no stack / no TCP port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB39_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
