#!/usr/bin/env python3
"""make_task.py <out task.md> — the code_patch2 task text, DERIVED from tasks/code_patch/task.md at run time (2026-10-05).

code_patch2 is code_patch with a declared multi-file touched set, so the model's contract is code_patch's task.md with
exactly two clauses replaced (never a second hand-maintained copy that drifts from the first):
  rule 3   "The diff touches EXACTLY two files ..."            -> the declared set (input.product_files + test_files)
  rule 4   "The checker applies the test hunk ALONE first ..." -> ALL test sections first, then ALL product sections
Each replaced clause is located by its exact opening text; if either anchor is missing (code_patch's task.md was
rewritten) this REFUSES (rc 2) rather than emit a task that says two contradictory things. rc 0 ok · 2 anchor missing.
"""
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
SRC = os.path.join(os.path.dirname(HERE), "code_patch", "task.md")

R3_START = "3. The diff touches EXACTLY two files:"
R3_END = "3a. "
R3_NEW = """3. CODE_PATCH2 (multi-file): the diff touches EXACTLY the files the input DECLARES - every path in
   `product_files` (1-3 product files, each modified in place) and every path in `test_files` (1-2 test files:
   `status: new` is a NEW file with `--- /dev/null`; `status: modified` is an EXISTING file modified in place).
   One file section per declared file, in the order the brief's `## The mode` gives. Not one file more, not one
   fewer: an undeclared file, or a declared file left untouched, fails the checker before any test runs. Never
   touch package.json, lockfiles, configs, or the reference test file. `product_file` names the FIRST product
   only; the full set is `product_files`.
"""
R4_OLD = "The checker applies the test hunk ALONE first"
R4_NEW = "The checker applies ALL the test sections ALONE first (no product section)"
R4_OLD2 = "then the product hunk (must pass)."
R4_NEW2 = "then ALL the product sections (every declared test must pass)."


def main():
    if len(sys.argv) != 2:
        print("usage: make_task.py <out task.md>", file=sys.stderr)
        return 64
    t = open(SRC, encoding="utf-8").read()
    i = t.find(R3_START)
    j = t.find(R3_END, i + 1) if i >= 0 else -1
    missing = [a for a, ok in ((R3_START, i >= 0), (R3_END, j > i), (R4_OLD, R4_OLD in t), (R4_OLD2, R4_OLD2 in t)) if not ok]
    if missing:
        print(f"make_task: REFUSED — anchor(s) not found in {SRC}: {missing} (code_patch's task.md changed; update this "
              f"derivation, do not run with a contradictory task)", file=sys.stderr)
        return 2
    t = t[:i] + R3_NEW + t[j:]
    t = t.replace(R4_OLD, R4_NEW, 1).replace(R4_OLD2, R4_NEW2, 1)
    t = ("<!-- GENERATED by tasks/code_patch2/make_task.py from tasks/code_patch/task.md; rules 3 and 4 replaced -->\n" + t)
    open(sys.argv[1], "w", encoding="utf-8").write(t)
    print(f"make_task: wrote {sys.argv[1]} ({len(t)} B) from {SRC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
