#!/bin/bash
# launch_qa_secuura_batch1310.sh — cross-project QA agent, ONE BATCH gate (gate33, T1 x4 + T2 x2) over 6 Secuura/Blockchain PRs of round 33, FROZEN at six:
# #1310 KS-1348 (B 35th (local-model patch, the Spark: KS-1348 r2 — originate utils/logger.ts redact-then-JSON + a NEW ks1348 cell; replaces #1302), T1) · #1311 KS-1346 (B 35th (local-model patch, the Spark: KS-1346 A — originate routes/systemErrors.ts fail500 type-and-field-names + a NEW ks1346a cell; replaces #1296), T1) · #1312 KS-1346 (B 35th (local-model patch, the Spark: KS-1346 B — originate routes/gdpr.ts fail500 type-and-field-names + a NEW ks1346b cell; replaces #1297), T1) · #1313 KS-1121 (B 35th (local-model patch, the Spark: vc-issuer repositories/credentialRepo.ts exact-id-only + its test edited in place; two disclosed pre-existing-class conditions, follow-up KS-1351), T1) · #1314 KS-1221 (B 35th (local-model patch, Ornith, REGENERATED by Wednesday: TEST-ONLY, the api-gateway ks744 cells edited in place, R4 + R5), T2) · #1315 KS-1220 (B 35th (local-model patch, the Spark: TEST-ONLY, the auth ks839 cells edited in place, R5 non-ASCII carriers; auth runs VITEST), T2)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate33.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-27T15:31:30Z, never adopted
# from a mail. develop at generation 958df2465368c3c7c68acacd68b1833f13a3b752; the PRs' merge-bases: a24db57e65c9d0b96e8560ea7feaa0c764dee564 for #1310; 94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812 for #1311, #1312, #1313, #1314, #1315; END_TREE 220baf79ea6722d124bad88b4c20be3056ee9f4d.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): '' (gate33: NONE — every PR is compared against the launch develop; a stack would use the parent's pinned head).
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate33.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  six rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate33.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at six.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the logging WIDEN rule. exit 41: the #1310 logger row. exit 42: the #1311 / #1312 fail500 rows. exit 43: the #1313 lookup row. exit 44: the READY identity. exit 46: the Linear link kinds. exit 47: the MG-3 key scan. exit 48: the squash-subject rule. exit 49: the no-op vs overlap keys. exit 50: the two-bases rule. exit 51: the two test-only tamper arms. exit 35: no Docker / no stack / no port.
# QAB33_CUR_DEV / QAB33_HEAD_<n> / QAB33_PATHS_<n> / QAB33_BRIEF / QAB33_PROMPT: test overrides (--check only); a launch with any QAB33_* set refuses (16).
# Generated by fill_gate33.py at 2026-09-27T15:37:21Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1310.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-28_gate33'
BRIEF="${QAB33_BRIEF:-$GS/mail_gate33_ready.md}"
PROMPT_FILE="${QAB33_PROMPT:-$GS/2026-09-28_secuura-batch1310.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1310|KS-1348|refs/heads/feature/ks-1348-redact-before-json-file-logs-b35-1|2cd351fad72da3e4547a9cf5b887575239afb36f|2|1|a24db57e65c9d0b96e8560ea7feaa0c764dee564|6|Blockchain/Dev/services/originate/src/__tests__/ks1348-production-file-logs-redact-secrets.test.ts,Blockchain/Dev/services/originate/src/utils/logger.ts|T1"
  "1311|KS-1346|refs/heads/feature/ks-1346-systemerrors-type-and-field-names-b35-2|451a36e8e825d3001e16f5fca6bb3517a81dbe06|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|9|Blockchain/Dev/services/originate/src/__tests__/ks1346a-systemerrors-fail500-logs-type-and-field-names.test.ts,Blockchain/Dev/services/originate/src/routes/systemErrors.ts|T1"
  "1312|KS-1346|refs/heads/feature/ks-1346-gdpr-type-and-field-names-b35-3|7421e843c5f69c21c639c52d888aeea144da626e|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|9|Blockchain/Dev/services/originate/src/__tests__/ks1346b-gdpr-fail500-logs-type-and-field-names.test.ts,Blockchain/Dev/services/originate/src/routes/gdpr.ts|T1"
  "1313|KS-1121|refs/heads/feature/ks-1121-credentialrepo-exact-id-only-b35-4|380e1e022ccfc6685346947bd9ff8eb08a0a07b7|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|9|Blockchain/Dev/services/vc-issuer/src/__tests__/credentialRepo.test.ts,Blockchain/Dev/services/vc-issuer/src/repositories/credentialRepo.ts|T1"
  "1314|KS-1221|refs/heads/feature/ks-1221-ks744-falsy-level-claim-cells-b35-5|eedce88bfd34fbb49aeafa4f0c085e549edce0c3|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|9|Blockchain/Dev/services/api-gateway/src/__tests__/ks744-a-token-missing-a-claim-is-proxied-not-500.test.ts|T2"
  "1315|KS-1220|refs/heads/feature/ks-1220-ks839-unicode-wildcard-carriers-b35-6|f02ae1a09d90d8254c027e8e89b9069c9c153000|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|9|Blockchain/Dev/services/auth/src/__tests__/ks839-a-wildcard-allow-list-grants-nothing.test.ts|T2"
)
DEVELOP_SHA='958df2465368c3c7c68acacd68b1833f13a3b752'
END_TREE='220baf79ea6722d124bad88b4c20be3056ee9f4d'
STACKS=''
_ovr() { local v="QAB33_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate33.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 6 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 6 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate33_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB33_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate33.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at six' && has 'MIXED TIERS, EACH PR GRADED AT ITS OWN TIER' || { echo "REFUSING: the tier definition / FROZEN at six" >&2; exit 7; }
for _w in \
  'Redact first, then JSON files' \
  '5 failed / 5 passed / 10 total' \
  '993 passed / 993, 85 suites, 0 failed' \
  'Error instances nested in metadata pass through unredacted' \
  'key matching is case-insensitive on the key ENDING' \
  'Type and field names only' \
  '4 failed / 11 passed / 15' \
  '8 failed / 7 passed / 15' \
  'the four A6 rows red' \
  'the four B6 rows red' \
  '994 passed / 994' \
  'delete the substring branch exactly as #966 did for presentations' \
  '3 failed / 8 passed / 11' \
  '136 passed / 136' \
  'a prefer-const warning created by deleting' \
  '2 failed / 5 passed of 7' \
  '756 passed / 756' \
  '1 failed / 7 passed of 8' \
  '836 passed / 836' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'LOG-FILE-WIDEN' \
  'NESTED-ERROR-PASSTHROUGH' \
  'SUFFIX-KEY-GAPS' \
  'FIELD-NAMES-AS-DATA' \
  'OTHER-CATCH-PATHS' \
  'REDACT-THEN-JSON' \
  'REDACT-ALL-ENVS' \
  'EXTRA-1302-ARM' \
  'TYPE-AND-FIELD-NAMES' \
  'ADD1-INSPECT-ARM' \
  'SAME-KEY-TWO-PRS' \
  'EXACT-ID-404' \
  'REVOKE-BY-FRAGMENT' \
  'SUBSTRING-CLASS-WIDEN' \
  'DISCLOSED-TS2339-PREFER-CONST' \
  'KS744-FALSY-CLAIM' \
  'KS1221-TAMPER-407' \
  'KS839-UNICODE-CARRIERS' \
  'AUTH-RUNS-VITEST' \
  'READY-IDENTITY' \
  'NON-MINIMAL-READY' \
  'GIT-APPLY-NOT-PATCH' \
  'TWO-BASES' \
  'SUBJECT-LANDS-AT' \
  'NOOP-VS-OVERLAP' \
  'ORIGINATE-COUNTS' \
  'VC-ISSUER-COUNTS' \
  'API-GATEWAY-COUNTS' \
  'AUTH-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'BASE-FIGURES-PER-PR' \
  'LOCAL-MODEL-PROVENANCE'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'WIDEN — WHAT REACHES A LOG LINE OR A PRODUCTION LOG FILE' && has 'grade by the rule, name the fields' && has 'a sentinel of YOUR OWN' || { echo "REFUSING: the logging WIDEN rule" >&2; exit 40; }
has 'THE LOGGER ROW (#1310;' && has 'Redact first, then JSON files' && has 'the REAL utils/logger' || { echo "REFUSING: the #1310 logger row" >&2; exit 41; }
has 'THE FAIL500 ROWS (#1311, #1312;' && has 'Type and field names only' && has 'BOTH the A1 AND the A6 rows' || { echo "REFUSING: the #1311 / #1312 fail500 rows" >&2; exit 42; }
has 'THE LOOKUP ROW (#1313;' && has 'THROUGH THE ROUTE' && has 'revoke-by-fragment revokes nothing' || { echo "REFUSING: the #1313 lookup row" >&2; exit 43; }
has 'READY-IDENTITY: the drafter compared' && has 'judged by BLOBS' || { echo "REFUSING: the READY identity" >&2; exit 44; }
has 'all six PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'SQUASH SUBJECTS ARE DECLARED WITHOUT THE (#n) SUFFIX' && has 'len(declared) + len(" (#n)") <= 92' && has 'the merge tool refuses a declared subject matching' || { echo "REFUSING: the squash-subject rule" >&2; exit 48; }
has 'THE DECLARATION KEYS (NOOP-VS-OVERLAP;' && has '`merged_blob_paths` (a GENUINE overlap' && has '`noop_paths` (a squash-stack NO-OP' || { echo "REFUSING: the no-op vs overlap keys" >&2; exit 49; }
has 'THE TWO BASES (TWO-BASES)' && has 'merge-tree with each PR'\''s own merge-base' || { echo "REFUSING: the two-bases rule" >&2; exit 50; }
has 'THE TAMPER ARMS FOR THE TWO TEST-ONLY CELLS' && has 'A tamper that does not red its declared cell is a FAIL of the arm' || { echo "REFUSING: the two test-only tamper arms" >&2; exit 51; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1310, #1311, #1312, #1313, #1314, #1315 batch`' && has 'so all six are squashed by Seat B 35th, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (10 over 10 paths) for #1310, #1311, #1312, #1313, #1314 and #1315' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE33 batch #1310 #1311 #1312 #1313 #1314 #1315 (Seat B35, round 33; T1 x4 + T2 x2: KS-1348, KS-1346 A, KS-1346 B, KS-1121, KS-1221, KS-1220)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks '${STACKS:-none}'"
_ANY_OVR="$(env | grep -c '^QAB33_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 6 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 20 seat items; the prompt carries 32 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the logging WIDEN rule / the #1310 logger row / the #1311 / #1312 fail500 rows / the #1313 lookup row / the READY identity / the Linear link kinds / the MG-3 key scan / the squash-subject rule / the no-op vs overlap keys / the two-bases rule / the two test-only tamper arms / no Docker / no stack / no port rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB33_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
