#!/usr/bin/env python3
"""make_commission_gate33.py — writes COMMISSION.md for gate33 (the directory this script lives in). Every SHA / tree / count in it is READ from
pins_gate33.json, stopcounts_gate33.json, gh_read_1.out and predict_1.out beside it (never typed); the prose rows are the drafter's.
Shape copied from gate32's make_commission (gate31 -> gate30T1 lineage), re-keyed to gate33's six MIXED-tier rows, no stack, two bases."""
import json, os, re
D = os.path.dirname(os.path.abspath(__file__)); K = json.load(open(D + '/kit.json')); kit = K['kit']
P = json.load(open('%s/pins_%s.json' % (D, kit))); S = json.load(open('%s/stopcounts_%s.json' % (D, kit)))
gh = open(D + '/gh_read_1.out').read()
fill = open(D + '/fill_1.out').read()
def subj_len(n):
    m = re.search(r'=== #%s head.*?\ntitle \((\d+) chars.*?= (\d+) chars' % n, gh, re.S); return m.group(2) if m else '?'
def lands(n):
    m = re.search(r'#%s (\d+)->(\d+)' % n, fill); return '%s -> lands %s' % (m.group(1), m.group(2)) if m else '?'
WHY = {
 '1310': ('KS-1348', '**T1 LOGGING (widens LOG STORAGE, ruled)**: originate utils/logger.ts — a logger-level redactSecrets() (value of any key ENDING in a secret/PII name -> [REDACTED], any depth) LAST in combine(), then combine(json()) on both production File transports; + a NEW ks1348 cell. Kam 2026-09-27 "Redact first, then JSON files". Golden-EXACT (`git apply --cached --check`, MEASURED). WIDEN MEASURED by the drafter (logprobe_1.out): the six ruled keys redacted in every sink; a NESTED Error\'s enumerable props and seven unmatched keys NOW reach both files (they wrote `undefined` at develop).'),
 '1311': ('KS-1346', '**T1 LOGGING (ruled)**: originate routes/systemErrors.ts fail500 logs `thrown <Ctor> with fields [...]` for a non-Error object (never values) + a NEW ks1346a cell. Kam 2026-09-27 "Type and field names only". Golden-EXACT (MEASURED). ADD1: the inspect tamper reds A1 AND A6. FIELD NAMES that are data (an email as a key) reach stdout + both files on END_TREE (logprobe P6, MEASURED).'),
 '1312': ('KS-1346', '**T1 LOGGING (ruled)**: originate routes/gdpr.ts, the SAME fail500 line (identical modulo indent on END_TREE, READ) + a NEW ks1346b cell. Same ruling. Golden-EXACT (MEASURED). ADD1: B1 AND B6 red under inspect. P7 as P6 (MEASURED).'),
 '1313': ('KS-1121', '**T1 LOOKUP (authorization-shaped)**: vc-issuer credentialRepo.getById loses the LIKE fallback and the includes() scan (exact id only; revoke inherits) + its test in place. Kam 2026-09-16 "delete the substring branch exactly as #966 did for presentations". Canonical patch.diff applies strict to the head blobs (MEASURED; its test section is NON-MINIMAL by one empty -/+ pair). Disclosed: TS2339 3 -> 4, prefer-const 0 -> 1 (KS-1351).'),
 '1314': ('KS-1221', '**T2 TEST-ONLY**: the api-gateway ks744 cells in place (R4 empty-string, R5 null verificationLevel; EXPECTED_CELLS 4 -> 6). Diff REGENERATED by Wednesday (applies strict, blob-EXACT, MEASURED). Tamper middleware/auth.ts — the brief said :398; the drafter READ :407 at head, develop and END_TREE.'),
 '1315': ('KS-1220', '**T2 TEST-ONLY**: the auth ks839 cells in place (R5 five non-ASCII carriers via String.fromCharCode; EXPECTED_CELLS 6 -> 7; auth runs VITEST). READY-identical (MEASURED). Tamper services/oauth.ts:353 (READ at head, develop and END_TREE).'),
}
rows = []
for n in sorted(K['prs']):
    pr = P['prs'][n]
    files = ', '.join('%s +%s/-%s' % (os.path.basename(x.split('\t')[2]), x.split('\t')[0], x.split('\t')[1]) for x in pr['numstat'])
    rows.append('| #%s | %s | `%s` | %d on `%s` | %s | %s (declared %s) | %s |' % (n, WHY[n][0], pr['head'], len(pr['commits']), pr['merge_base'][:12], files, subj_len(n), lands(n), WHY[n][1]))
out = ['# COMMISSION — DRAFT the round-33 batch gate kit "%s" over %d PRs (MIXED: T1 x4, T2 x2). Do NOT launch.' % (kit, len(K['prs'])), '',
 'Commissioned by Wednesday to the drafter on 2026-09-28 (~01:1x AEST) for Seat B 35th\'s round: #1310 (KS-1348 r2), #1311 (KS-1346 A), #1312 (KS-1346 B), #1313 (KS-1121),',
 '#1314 (KS-1221) and #1315 (KS-1220, "expected; being pushed now" — it EXISTED when the drafter censused at 15:21Z, head f02ae1a09d90, so the kit is SIX). All raised',
 'by Seat B 35th, which merges its own on Wednesday\'s signed GO. Kam rulings to verify IN THE PRODUCT: #1310 "Redact first, then JSON files" (2026-09-27 19:06, card',
 'secuura-ks1348-log-files-persist-secrets = a); #1311/#1312 "Type and field names only" (2026-09-27 16:32, card secuura-ks1346-logging-thrown-objects-leaks-secrets = a);',
 '#1313 "delete the substring branch exactly as #966 did for presentations" (2026-09-16). The T1 rows carry a WIDEN measurement for #1302\'s class (gate31\'s NO GO).',
 'Shape copied from `gatesets/2026-09-27_gate32/` (newest; T2 x6) and `gatesets/2026-09-27_gate31/` (MIXED with T1, the #1302 WIDEN logprobe): JSON pins, routing-file',
 'override, controls both ways with `--invert`, a declared commit count, a not-stacked check for every pair, the key scan, a HARD WIDEN census (titles AND Seat B 35th\'s',
 'branch segment) in predict and in the launch action (rc 15), and the STANDING_LINES of 2026-09-27/28 (subjects without the suffix, landed <= 92; no-op vs overlap',
 'keys; every spelling of a namespace token; rev-parse on unfetched objects; verified bytes == used bytes; `patch -F0` is not `git apply --check`; a copied tool is keyed',
 'to its author\'s position and a re-key tool is in its own token map).', '',
 '## The batch — every head re-read by the drafter from origin (ls-remote + a fetch into a `--shared --no-checkout` scratch clone + the PULLS API; all agree)',
 '| PR | ticket | head | commits on merge-base | files | title lands at (`<title> (#n)`) and the DECLARED subject | tier — why, from the DIFF |', '|---|---|---|---|---|---|---|'] + rows + ['',
 'Linear: every PR links its ticket as `contributes`; none `closes` (linear_reads_1.out); no PR title, body or commit message puts a closing word before a key (keyscan_1.out).',
 'NOT STACKED (measured): no head is another\'s ancestor; every pair\'s merge-base is on develop. MG-11 as it LANDS: every title is the declared subject, WITHOUT the (#n) suffix; landed lengths from fill_1.out in the table (all <= 92; no SHORT subject this round).', '',
 '## Develop at the pin',
 'Pinned over develop **`%s`** (tree `%s`), READ by ls-remote and fetched — gate32\'s six squashes in (its tree equals gate32\'s own END_TREE `977c6a48635341fe9d29f48a0c7e83c843dd9895`, READ). TWO merge-bases, MEASURED: `a24db57e65c9` for #1310, `94c9c7aa9be7` for the other five (each head\'s one commit has that parent); develop moved 6 squashes since a24db57e65c9 and 9 since 94c9c7aa9be7 (move ∩ every own path EMPTY). END_TREE **`%s`** (%s), identical in all %d orders (%d merge-tree calls, each with the PR\'s own merge-base).' % (
     P['develop'], P['develop_tree'], P['end_tree'], P['end_shortstat'], P['orders'], P['merge_tree_calls']),
 'The launch action\'s step 3b re-pins on any move.', '',
 '## Overlaps — NONE declared, NONE found',
 '- Kit pairs: all disjoint. Every other OPEN PR at the pin (%d, the PULLS API census): disjoint from every kit path. The predecessors #1302 / #1296 / #1297 are CLOSED unmerged (gh_read_1.out).' % len(P['inflight']),
 '- `merged_blob_paths` (a genuine overlap) NONE and `noop_paths` (a squash-stack no-op) NONE — two different declarations, each asserted empty by predict (c).', '',
 '## Fleet STOP (READ, bounded region, NOT-FOUND control)']
for n in sorted(K['prs']):
    s = S[n]
    out.append('- #%s `%s` (%d lines, rc %s): %s' % (n, os.path.basename(s['log']), s['lines'], s['rc'],
        ('%s · %s · %s · %s; "%s"' % (s['pre_push_hook_base'], s['fixture_guard'], s['run_shell_suites_region'], s['shell_suites'], s['verdict_line'])) if s['preflight_ran'] else 'NO PREFLIGHT (a systemTest/ push: the format gate only) — NOT APPLICABLE'))
out += ['- By path class no kit PR changes the count (originate / vc-issuer .ts files and jest / vitest cells — no `*.test.sh`): after this merge 28/0 · 6/0 · 49/0 · 60 of 60.', '']
out += ['## LEGITIMATE SHAPES — the drafter\'s READ predictions (the gate MEASURES every row; a row saying MEASURED is a drafter\'s run, still not the gate\'s evidence)', '| PR | prediction | predicted-by |', '|---|---|---|']
for l in open(D + '/predict_1.out').read().splitlines():
    m = re.match(r'^  #(\d+) (.*)$', l)
    if m and not m.group(2).startswith(('PRODUCT files', 'NO product file')):
        out.append('| #%s | %s | drafter %s (predict_1.out) |' % (m.group(1), m.group(2).replace('|', '/')[:1300], 'MEASURED' if 'MEASURED' in m.group(2)[:120] else 'READ'))
open(D + '/COMMISSION.md', 'w').write('\n'.join(out) + '\n')
print('wrote', D + '/COMMISSION.md', len(out), 'lines')
