#!/bin/bash
# launch_qa_secuura_batch1354.sh — cross-project QA agent, ONE gate (gate48a, round 48a) over ONE Secuura/Blockchain PR, FROZEN at ONE:
# #1354 KS-470 (T2): js-yaml 5.4.2 in systemTest/performance (a FIX) + ONE audit-baseline row for undici GHSA-r53p expiring 2026-10-09.
# Author and merger: Seat B 47th. ROUND 1 of its own PR.
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (pin_gate48a.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-29T21:56:28Z.
# develop 37205947ddd2775a72a417beb5b7ac8e3240fbf3; END_TREE bcac9e18943fa6aa97b394a7c8b4424124af6ea9 (the squash on develop == the head's tree). Shape copied from the gate47 launcher, cut to ONE row.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT).   exit 3-5: capture / prompt / repo missing.
# exit 6:  the head is not at its branch AND refs/pull/1354/head on origin.   exit 8: thinking directive / the kit files named + present / an unfilled token / row count.
# exit 10: the GitHub compare develop...head: merge_base / ahead / behind / files != the pins.   exit 17: origin develop != the pinned develop.
# exit 20: capture AND prompt name the head in full.   exit 7: the tier lines + FROZEN at ONE + ROUND 1 + the tiering rule.   exit 31: develop / END_TREE in full.
# exit 32: the prompt and the capture state the ticket.   exit 33: the by-name keyword ladder (each keyword AS A TOKEN).   exit 39: the HOLDS + the named exceptions.
# exit 34: the EXCEPTION-FIRST rule.   exit 26: merge authority + the GO string.   exit 25: MERGE ADDENDUM rules + REPORT-HASH-LAST.   exit 23: verdict subject / sender / report dir.
# exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).   exit 16: a launch with a G48A_* test override set.
# G48A_CUR_DEV / G48A_HEAD_1354 / G48A_PATHS_1354 / G48A_BRIEF / G48A_PROMPT: test overrides (--check only).
# Generated by fill_gate48a.py at 2026-09-29T22:26:13Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1354.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-30_gate48a'
BRIEF="${G48A_BRIEF:-$GS/mail_gate48a_ready.md}"
PROMPT_FILE="${G48A_PROMPT:-$GS/2026-09-30_secuura-batch1354.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|tickets|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined)|tier
PRS=(
  "1354|KS-470|refs/heads/feature/ks-470-jsyaml-542-and-accept-ghsa-r53p-b47-3|4370be410bbf37b839b1030f3e28f95d11c454fe|2|1|37205947ddd2775a72a417beb5b7ac8e3240fbf3|0|Blockchain/Dev/scripts/audit/audit-baseline.json,systemTest/performance/package-lock.json|T2"
)
DEVELOP_SHA='37205947ddd2775a72a417beb5b7ac8e3240fbf3'
END_TREE='bcac9e18943fa6aa97b394a7c8b4424124af6ea9'
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate48a.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 1 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is ONE PR (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
for _f in mail_gate48a_ready.md COMMISSION.md drafted_texts_gate48a.md row_reason_gate48a.md lockdiff_1.out baseline_1.out lockcensus_1.out gh_read_1.out gh_body_1354.md; do
  [ -s "$GS/$_f" ] && grep -qF "$GS/$_f" "$PROMPT_FILE" || { echo "REFUSING: the kit file $GS/$_f is missing, empty, or not named in the prompt" >&2; exit 8; }
done
grep -qF "2026-09-30-batch1349-g47/report.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the previous round report (gate47)" >&2; exit 8; }
grep -qF "**Title:** undici under @connectrpc/connect-node" "$GS/drafted_texts_gate48a.md" && grep -qF "**Title:** lockfile-cleanroom.sh prints a remediation command" "$GS/drafted_texts_gate48a.md" || { echo "REFUSING: the drafted texts lack one of the two tickets" >&2; exit 8; }
grep -qF 'GHSA-r53p-7pc4-xj5r' "$GS/row_reason_gate48a.md" && grep -qE '^1[0-9]?\. ' "$GS/row_reason_gate48a.md" || { echo "REFUSING: the row reason file lacks the row id or its numbered sentences" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
_REFS="refs/heads/develop"
for _row in "${PRS[@]}"; do IFS='|' read -r _n _t _br _rest <<< "$_row"; _REFS="$_REFS $_br refs/pull/$_n/head"; done
_LSALL="$(git -C "$REPO" ls-remote origin $_REFS)"   # ONE read of origin for develop + the branch + pull/head
CUR_DEV="${G48A_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned develop $DEVELOP_SHA — run repin_and_launch_gate48a.sh (it re-pins and re-fills in one action)" >&2; exit 17; }
NOTE="origin develop $CUR_DEV == the pinned develop; END_TREE $END_TREE"
for _row in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_row"
  _ov="G48A_HEAD_$_n"; [ -n "${!_ov:-}" ] && _h="${!_ov}"
  _ov="G48A_PATHS_$_n"; [ -n "${!_ov:-}" ] && _p="${!_ov}"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix
  if [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_LSALL" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n — $_h is not at $_br AND refs/pull/$_n/head on origin — the head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_LSALL" >&2; exit 6
  fi
  COMPARE="$(set -a; . "$SECUURA_ENV"; set +a   # the token lives only in this subshell, never in the exec'd agent's env
  H="$_h" DEV="$CUR_DEV" python3 - <<'PY'
import json, os, urllib.request
t = os.environ.get("GH_TOKEN", "")
try:
    c = json.load(urllib.request.urlopen(urllib.request.Request("https://api.github.com/repos/Secuura/Distributed_Secuura/compare/%s...%s" % (os.environ["DEV"], os.environ["H"]), headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
    fs = sorted(x["filename"] for x in (c.get("files") or []))
    print("%s ahead=%d behind=%d files=%d paths=%s" % (c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
except Exception as e: print("ERROR %s" % e)
PY
)"
  [ "$COMPARE" = "${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" ] || { echo "REFUSING: #$_n — the compare is not the pinned merge_base / ahead / behind / files:" >&2; echo "  got  $COMPARE" >&2; echo "  want ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" >&2; exit 10; }
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  NOTE="$NOTE | #$_n $_ti ${_h:0:12} compare ok (behind $_bh)"
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'PR #1354 is KS-470' && grep -qF -- '#1354 is KS-470' "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state 'PR #1354 is KS-470'" >&2; exit 32; }
has '#1354 T2' && has 'The gate is FROZEN at ONE PR' && has 'TIER 2 = THROUGH-CODE ONLY' && has 'ROUND 1 of its own PR' && has 'a round-1 NO GO goes back to the author for round 2' && has 'ship the closed instances, ticket the residue' || { echo "REFUSING: the tier lines / FROZEN at ONE / ROUND 1 / the tiering rule" >&2; exit 7; }
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' && has 'NAMES THE TREE' && has 'A check that prints nothing needs a control that prints' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS / NAMES THE TREE / the printing control" >&2; exit 33; }
for _w in LOCK-DIFF-ONE-ENTRY JSYAML-OUT-OF-RANGE BASELINE-ROW-FIELDS CONTRACT-BYTE-EQUAL FUSE-COUNT AUDIT-GATES-HEAD-END CLAUSE2-REMEASURE EXCEPTION-CHECKED GRANT-CLAUSES REASON-TEXT-TRUE DRAFTED-TICKETS-CHECKED CLEAN-MERGE END-TREE MODES OUT-OF-KIT-CENSUS SUBJECT-KEY-SCAN SUBJECT-LANDS-AT SUBJECT-TRUE-OF-DIFF REFS-OWN-KEY NO-CLOSING-KEYWORD PR-BODY-CLAIMS TIERING DISK-ENOSPC REPORT-HASH-LAST; do   # AS A TOKEN: bounded by a non-[A-Za-z0-9-] character (MODES is not satisfied by MODES-X)
  printf '%s' "$PROMPT_JOINED" | grep -qE -- "(^|[^A-Za-z0-9-])$_w([^A-Za-z0-9-]|\$)" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'If the exception fires, the verdict is NO GO and you say so FIRST' && has 'the EXCEPTION line FIRST' && has 'stops for Kam' || { echo "REFUSING: the EXCEPTION-FIRST rule" >&2; exit 34; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' && has 'Never `rm`' && has 'No `az` command of any kind' && has 'You NEVER reply to Peter' && has 'Never read or write a real `.env`' && has 'Docker runs are `--rm --network none` with the source mounted READ-ONLY' && has 'NO checklist tick' && has 'no Akto scan against any stack' && has 'No audit-baseline row edited' && has 'THE NAMED EXCEPTIONS to those holds — these and NO others' && has 'NEVER `up`, `down`' && has '"no lock regenerated" means no REAL lock' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has "WEDNESDAY'S signed GO naming the heads" && has 'GO (Seat B 47th): merge 1354 on gate48a' && has 'The merge seat is Seat B 47th' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'ONE LINE' && has 'KEY-FREE' && has 'MG-11 subject <= 92' && has 'the FLEET STOP after this merge' && has 'MG-1 2 over 2 paths' && has 'CONTRACT baseline-contract.mjs == base blob' && has 'FUSE 2026-10-09 rows at END' && has 'drafted tickets: override' && has 'TRUE of its diff' && has 'EVERY SUBJECT YOU PROPOSE MUST BE TRUE OF THE DIFF' && has 'is the LAST thing you write to report.md' && has 'NOTHING to report.md after you send the verdict mail' && has 'sha256 report.md = <hex>' || { echo "REFUSING: the MERGE ADDENDUM rules / REPORT-HASH-LAST" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE48A #1354 (Seat B47 author and merger, round 48a; T2: KS-470 js-yaml 5.4.2 fixed, undici GHSA-r53p accepted to 2026-10-09)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' && has 'reports/2026-09-30-batch1354-g48a/' || { echo "REFUSING: the verdict subject / sender / report dir" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE not in full" >&2; exit 31; }
_ANY_OVR="$(env | grep -c '^G48A_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE" | cut -c1-400
  echo "  capture, drafted tickets, row reason, lockdiff / baseline / lockcensus / gh reads, PR body, prompt, QA project and repo present; kit at its filled home; ONE row; thinking directive; every kit file + commission + gate47 report named; no unfilled token"
  echo "  1 of 1 head at branch AND pull/head (whole-field); 1 of 1 GitHub compare == the pins; capture and prompt BOTH carry the head in full and the ticket"
  echo "  the prompt carries 24 by-name keywords (as tokens), the tier lines, the EXCEPTION-FIRST rule, the holds + named exceptions, the GO string, the addendum + REPORT-HASH-LAST rules, the verdict subject + report dir, develop / END_TREE in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a G48A_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
