#!/bin/bash
# launch_qa_secuura_batch1300.sh — cross-project QA agent, ONE BATCH gate (gate31, mixed tiers) over 4 Secuura/Blockchain PRs of round 31, FROZEN at four:
# #1300 KS-1334 (B 33rd (local-model patch, Spark on an EXCERPTED input, brief KS-1334-B; the golden is checked EXACT by predict), T1) · #1301 KS-1349 (B 33rd (test-only, stacked on #1300), T2) · #1302 KS-1348 (B 33rd (production File transports get a json() format: WIDENS what reaches LOG STORAGE), T1) · #1303 KS-1350 (B 33rd (WIDEN row: comment-only edit of the webhooks fail500 docblock), T3)
# EVERY VALUE HERE WAS MEASURED BY THE DRAFTER (predict_gate31.py, a --shared --no-checkout scratch clone fetched from origin) at 2026-09-27T05:47:05Z, never adopted
# from a mail. develop at generation 94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812; the PRs' merge-bases: 94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812 for #1300, #1302, #1303; 5bd58f0ebd14bcf89fcde1fbb37434edee008eb5 for #1301 (STACKED on #1300: its chain base is #1300's head); END_TREE 035399116152909d64fb5c6d66c4a5c9d5da80bc.
# The compare check is three-dot (develop...head; for a STACKED child <parent head>...head): merge_base, ahead, behind AND the file NAMES, per PR.
# STACKS (child:parent): 1301:1300 — the child's compare base is the parent's pinned head, never develop.
# exit 2:  QA project missing, or this launcher is not in the gateset dir it was filled for (a MOVED KIT — repin_and_launch_gate31.sh re-fills there).
# exit 3-5: capture / prompt / repo missing.   exit 6: a head is not at its branch AND refs/pull/<n>/head on origin.
# exit 8:  four rows; the prompt opens with the thinking directive, names the capture + the commission, carries no unfilled fill token.
# exit 10: the GitHub compare develop...head (stacked: parent...head) per PR: merge_base / ahead / behind == the pins, files == the PR's OWN paths by name.
# exit 17: origin develop != the pinned launch develop — re-pin with repin_and_launch_gate31.sh (it re-reads, re-measures and re-fills in ONE action).
# exit 20: capture AND prompt name every head in full.  exit 21: the LAUNCH path refuses when stdin is not a TTY (`--check` is headless).
# exit 7:  tier lines + FROZEN at four.  exit 30: capture AND prompt BOTH carry the seat items.  exit 31: develop / END_TREE / RETARGET tree in full.
# exit 32: capture AND prompt state each ticket.  exit 33: the by-name keyword ladder.  exit 23: verdict subject / sender.
# exit 25: MERGE ADDENDUM rules.  exit 26: merge authority + the GO string.  exit 40: the #1300 T1 runtime probe. exit 41: the #1300 in-place ks730c edits. exit 42: the KS-1334 5f close. exit 43: the #1301 tamper arm. exit 44: the #1301 stack and retarget. exit 48: the GO retarget step and merge order. exit 50: the #1302 log-file widen rule. exit 51: the #1303 token equivalence. exit 35: no Docker / no stack / no port. exit 47: the MG-3 key scan. exit 46: the Linear link kinds.
# QAB31_CUR_DEV / QAB31_HEAD_<n> / QAB31_PATHS_<n> / QAB31_BRIEF / QAB31_PROMPT: test overrides (--check only); a launch with any QAB31_* set refuses (16).
# Generated by fill_gate31.py at 2026-09-27T05:48:31Z. Opus by the configured default: the exec line carries NO --model.
# Usage: launch_qa_secuura_batch1300.sh [--check]
set -u
QA_DIR='/Volumes/DevMASTER/!CODING/Testing Agent MAIN'
GS='/Volumes/DevMASTER/WEDNESDAY/2_Project_Files/fleet/qa-agent/gatesets/2026-09-27_gate31'
BRIEF="${QAB31_BRIEF:-$GS/mail_gate31_ready.md}"
PROMPT_FILE="${QAB31_PROMPT:-$GS/2026-09-27_secuura-batch1300.prompt.txt}"
REPO='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/2_Project_Files'
SECUURA_ENV='/Volumes/DevMASTER/!CODING/Secuura/Blockchain/4_Credentials/.env'
# row: PR|ticket|branch ref|head|files|ahead|merge_base|behind|the PR's own paths (sorted, comma-joined — the base-invariant compare target)|tier
PRS=(
  "1300|KS-1334|refs/heads/feature/ks-1334-adminconfig-500-part-b-b33-1|5bd58f0ebd14bcf89fcde1fbb37434edee008eb5|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|0|Blockchain/Dev/services/originate/src/__tests__/ks730c-adminconfig-500-never-answers-err-message.test.ts,Blockchain/Dev/services/originate/src/routes/adminConfig.ts|T1"
  "1301|KS-1349|refs/heads/feature/ks-1349-ks730c-per-env-mockclear-b33-2|3b7e71f461ef4dd789f019cbf07e06be258a31fd|1|1|5bd58f0ebd14bcf89fcde1fbb37434edee008eb5|0|Blockchain/Dev/services/originate/src/__tests__/ks730c-adminconfig-500-never-answers-err-message.test.ts|T2"
  "1302|KS-1348|refs/heads/feature/ks-1348-prod-logger-file-json-format-b33-3|99374a3dbef16de9ae4a3a1759cf64e81a8b136f|2|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|0|Blockchain/Dev/services/originate/src/__tests__/ks1348-production-file-log-lines-are-json.test.ts,Blockchain/Dev/services/originate/src/utils/logger.ts|T1"
  "1303|KS-1350|refs/heads/feature/ks-1350-fail500-docblock-b33-4|0103e2dd5ab6d6d211d84602c47b937edfba2430|1|1|94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812|0|Blockchain/Dev/services/originate/src/routes/webhooks.ts|T3"
)
DEVELOP_SHA='94c9c7aa9be7f0c05f4a89cdc532ec6f2fef3812'
END_TREE='035399116152909d64fb5c6d66c4a5c9d5da80bc'
RETARGET_TREE='d1786ca641ca4f3f38550f03fb6e69a064bf8672'
STACKS='1301:1300'
_ovr() { local v="QAB31_$1"; printf '%s' "${!v:-}"; }
[ -d "$QA_DIR" ]      || { echo "QA project missing: $QA_DIR" >&2; exit 2; }
_here="$(dirname "$(/bin/realpath "$0")")"
[ "$_here" = "$GS" ] || { echo "REFUSING: this launcher lives in $_here but was filled for $GS — a MOVED KIT: run repin_and_launch_gate31.sh from its new home (it re-fills there)" >&2; exit 2; }
[ -s "$BRIEF" ]       || { echo "capture missing or empty: $BRIEF" >&2; exit 3; }
[ -s "$PROMPT_FILE" ] || { echo "prompt file missing or empty: $PROMPT_FILE" >&2; exit 4; }
[ -d "$REPO" ]        || { echo "repo under test missing: $REPO" >&2; exit 5; }
[ "${#PRS[@]}" -eq 4 ] || { echo "REFUSING: ${#PRS[@]} rows, this gate is 4 PRs (frozen)" >&2; exit 8; }
[ "$(head -n 1 "$PROMPT_FILE")" = "ultrathink" ] || { echo "REFUSING: the prompt does not open with the thinking directive" >&2; exit 8; }
grep -qF "$GS/mail_gate31_ready.md" "$PROMPT_FILE" && grep -qF "$GS/COMMISSION.md" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not name the capture and the commission at $GS" >&2; exit 8; }
grep -qE '\{\{[A-Z0-9_]+\}\}' "$PROMPT_FILE" && { echo "REFUSING: the prompt carries an unfilled double-brace fill token" >&2; exit 8; }
HEADS_NOTE=""
_LSREFS=(refs/heads/develop)
for _pr in "${PRS[@]}"; do IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"; _LSREFS+=("$_br" "refs/pull/$_n/head"); done
_LSALL="$(git -C "$REPO" ls-remote origin "${_LSREFS[@]}")"   # ONE read of origin for every row and develop
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "HEAD_$_n")" ] && _h="$(_ovr "HEAD_$_n")"
  _lsr="$(printf '%s\n' "$_LSALL" | awk -v a="$_br" -v b="refs/pull/$_n/head" '$2==a || $2==b')"
  # WHOLE-FIELD equality (awk $1==h), never a regex prefix: a planted head that merely CONTAINS or EXTENDS the real one must refuse
  if [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="$_br" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ] || [ "$(printf '%s\n' "$_lsr" | awk -v h="$_h" -v r="refs/pull/$_n/head" '$1==h && $2==r' | wc -l | tr -d ' ')" != 1 ]; then
    echo "REFUSING: #$_n $_t — $_h is not at $_br AND refs/pull/$_n/head on origin — that head moved (or the pin is wrong); a verdict is valid ONLY at its head" >&2
    printf '%s\n' "$_lsr" >&2
    exit 6
  fi
  HEADS_NOTE="$HEADS_NOTE #$_n@${_h:0:9}"
done
CUR_DEV="${QAB31_CUR_DEV:-$(printf '%s\n' "$_LSALL" | awk '$2=="refs/heads/develop"{print $1}')}"
[ "$CUR_DEV" = "$DEVELOP_SHA" ] || { echo "REFUSING: origin develop $CUR_DEV != the pinned launch develop $DEVELOP_SHA — the END_TREE $END_TREE is unverified there: run repin_and_launch_gate31.sh (it re-reads, re-measures and re-fills in one action)" >&2; exit 17; }
COMPARE="$(
  set -a; . "$SECUURA_ENV"; set +a
  PRS_LINES="$(printf '%s\n' "${PRS[@]}")" CUR_DEV="$CUR_DEV" STACKS="$STACKS" python3 - <<'PY'
import json, os, time, urllib.request, urllib.error
t = os.environ.get("GH_TOKEN", ""); api = "https://api.github.com/repos/Secuura/Distributed_Secuura/compare/"
ST = dict(x.split(":") for x in os.environ.get("STACKS", "").split() if ":" in x)
HD = {l.split("|")[0]: l.split("|")[3] for l in os.environ["PRS_LINES"].splitlines() if l.strip()}
def get(u):
    for i in range(4):
        try: return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"Authorization": "Bearer " + t, "Accept": "application/vnd.github+json"}), timeout=60))
        except urllib.error.HTTPError as e:
            if e.code < 500 or i == 3: raise
            time.sleep(10)
for pr in os.environ["PRS_LINES"].splitlines():
    if not pr.strip(): continue
    n, tk, br, h, nf, na, mb, bh, paths, ti = pr.split("|")
    try:
        base = HD[ST[n]] if n in ST else os.environ["CUR_DEV"]   # a STACKED child is compared against the pinned head of its parent
        c = get(api + base + "..." + h); fs = sorted(x["filename"] for x in (c.get("files") or []))
        print("%s %s ahead=%d behind=%d files=%d paths=%s" % (n, c["merge_base_commit"]["sha"], c["ahead_by"], c["behind_by"], len(fs), ",".join(fs)))
    except Exception as e: print("%s ERROR %s" % (n, e))
PY
)"
_bad=0
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  [ -n "$(_ovr "PATHS_$_n")" ] && _p="$(_ovr "PATHS_$_n")"
  printf '%s\n' "$COMPARE" | grep -qxF "${_n} ${_mb} ahead=${_a} behind=${_bh} files=${_f} paths=${_p}" || _bad=1
done
[ "$_bad" = 0 ] || { echo "REFUSING: a compare is not the pinned merge_base / ahead / behind / files == the PR's OWN paths by name (base-invariant):" >&2; printf '%s\n' "$COMPARE" >&2; exit 10; }
for _pr in "${PRS[@]}"; do
  IFS='|' read -r _n _t _br _h _f _a _mb _bh _p _ti <<< "$_pr"
  grep -qwF "$_h" "$BRIEF" && grep -qwF "$_h" "$PROMPT_FILE" || { echo "REFUSING: the capture and the prompt do not both name #$_n's head $_h in full" >&2; exit 20; }
  grep -qF -- "PR #$_n is $_t." "$PROMPT_FILE" && grep -qF -- "#$_n is $_t." "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH state that #$_n is $_t" >&2; exit 32; }
  grep -qF -- "#$_n $_ti" "$PROMPT_FILE" || { echo "REFUSING: the prompt does not carry the tier line '#$_n $_ti'" >&2; exit 7; }
done
PROMPT_JOINED="$(python3 -c 'import re,sys; print(re.sub(r"\n\s*", " ", open(sys.argv[1], encoding="utf-8").read()))' "$PROMPT_FILE")"
has() { printf '%s' "$PROMPT_JOINED" | grep -qF -- "$1"; }
has 'The batch is FROZEN at four' && has 'MIXED TIERS, EACH PR GRADED AT ITS OWN TIER' || { echo "REFUSING: the tier definition / FROZEN at four" >&2; exit 7; }
for _w in \
  '4 failed / 19 passed / 23 total' \
  'These are sites 4 of 4.' \
  '983 passed / 983 total' \
  'go 48 → 50' \
  '4 GREEN — the blindness, reproduced' \
  '8 failed / 15 passed / 23' \
  'Why the ticket'\''s own tamper is not used:' \
  'Its base is retargeted to `develop` once #1300 merges.' \
  'The production log files will now really hold logged error text.' \
  '2 failed / 3 passed / 5 total' \
  '984 passed / 984' \
  'Not measured, and worth a reviewer'\''s judgement.' \
  '2789 parser leaves before, 2789 after, identical' \
  'Two earlier versions of this instrument were wrong, and control B is what caught both.' \
  'COMMENTS ONLY.' \
  'PREFLIGHT INCOMPLETE — 12/15 legs ran, 3 SKIPPED. Nothing failed.'; do
  grep -qF -- "$_w" "$PROMPT_FILE" && grep -qF -- "$_w" "$BRIEF" || { echo "REFUSING: the capture and the prompt do not BOTH carry the seat item '$_w'" >&2; exit 30; }
done
has 'MEASURE, not conclude' && has 'RULE WHETHER IT BLOCKS' || { echo "REFUSING: MEASURE, not conclude / RULE WHETHER IT BLOCKS" >&2; exit 30; }
for _w in \
  'ADMINCONFIG-B-RUNTIME-PROBE' \
  'MERGE-BASE-MUST-LEAK' \
  'CATCH-REACHED-PER-ENV' \
  'NON-ERROR-THROWS' \
  'ALL-FOUR-AT-HEAD' \
  'FIFTH-SITE-DECLARED' \
  'IN-PLACE-KS730C-B' \
  'KS1334-NOT-DONE-5F' \
  'EXCERPTED-INPUT' \
  'LOG-FILE-SECRET-PII' \
  'REAL-LOGGER-FILE-CAPTURE' \
  'FAIL500-TEXT-TO-FILE' \
  'SAME-CLASS-AS-KS1346' \
  'STDOUT-ALREADY-CARRIES' \
  'KS1348-CELL-NO-SENTINEL' \
  'TAMPER-ARM-2X2' \
  'COMMISSION-TAMPER-SLIP' \
  'SINGLE-ENV-SWEEP' \
  'STACKED-1301' \
  'RETARGET-STEP' \
  'TOKEN-EQUIVALENCE' \
  'JSDOC-KIND-FILTER' \
  'COMMENT-ONLY' \
  'DOCBLOCK-SENTENCES-TRUE' \
  'GOLDEN-BLOB-IDENTITY' \
  'LOCAL-MODEL-PROVENANCE' \
  'ORIGINATE-COUNTS' \
  'TSC-EXCLUDES-TESTS' \
  'LINT-22-WARNINGS' \
  'BASE-FIGURES-PER-PR'; do
  has "$_w" || { echo "REFUSING: the prompt does not carry the by-name keyword '$_w'" >&2; exit 33; }
done
has 'EVERY MERGE CHECK IS BASE-INVARIANT' && has 'A sibling batch merging is not a difference' && has 'PAIRWISE PATH-DISJOINT' && has 'declare any overlap you find with its merged-blob target' || { echo "REFUSING: the BASE-INVARIANT / PAIRWISE rule" >&2; exit 34; }
has 'THE RED PROOFS — RE-RUN, RED AT BASE AND GREEN AT HEAD' && has 'RESTORE BYTE-IDENTICALLY' && has 'restore by bytes' && has 'A red proof must NAME WHY it went red' && has 'in YOUR OWN clone' || { echo "REFUSING: the RED-PROOF rule" >&2; exit 36; }
has '`pre_push_hook_base` 28/0 · `pre_push_hook_base_fixture_guard` 6/0 · `run_shell_suites` 49/0 · shell suites 60 of 60' && has 'NO STANDALONE RUN of' && has 'the count after this merge stays 28/0 · 6/0 · 49/0 · 60 of 60' || { echo "REFUSING: the fleet STOP count rule" >&2; exit 37; }
has 'KNOWN FALSE-RED class (ticket KS-1155; wall-clock under load)' && has 'an ASSERTION failure is REAL' && has 'a green on the re-run with the load recorded is NOT a NO GO' && has '"anchoring N passed / 1 failed; the one failure is threadTokenMint.test.ts > … deterministic per-seed policyId, pre-existing (KS-562), not caused by this change"' || { echo "REFUSING: the LOAD rule / the anchoring wording" >&2; exit 38; }
has 'NO MERGE, NO PUSH to any PR branch, NO ticket state change' && has 'NO ticket filed' && has 'NEVER WRITE THE SHARED CHECKOUT. Findings only.' || { echo "REFUSING: the HOLDS" >&2; exit 39; }
has 'They are NOT RUN in this gate' && has 'legs 3/4/8 NOT run (no stack' || { echo "REFUSING: legs 3/4/8 NOT run" >&2; exit 45; }
has 'RUNTIME PROBE FOR #1300 — THROUGH THE REAL ROUTER' && has 'MERGE-BASE-MUST-LEAK: at the merge-base' && has 'the catch was REACHED IN THAT ENVIRONMENT' || { echo "REFUSING: the #1300 T1 runtime probe" >&2; exit 40; }
has 'THE IN-PLACE ks730c EDITS (IN-PLACE-KS730C-B)' && has 'KS-1334'\''s Done-when item 2' || { echo "REFUSING: the #1300 in-place ks730c edits" >&2; exit 41; }
has 'KS-1334 IS NOT DONE AFTER THIS MERGE' && has 'the handle `live sweep owed` lowercase' || { echo "REFUSING: the KS-1334 5f close" >&2; exit 42; }
has 'THE TAMPER ARM FOR #1301 — AT THE STACKED HEAD' && has 'The drafter PREDICTS A SLIP in that sentence' && has 'SINGLE-ENV-SWEEP: tamper to log ONLY under each one' || { echo "REFUSING: the #1301 tamper arm" >&2; exit 43; }
has 'THE STACK AND THE RETARGET (STACKED-1301, RETARGET-STEP)' && has 'a conflict there is a STOP' || { echo "REFUSING: the #1301 stack and retarget" >&2; exit 44; }
has 'THE RETARGET STEP, carried in the GO' && has 'A CONFLICT, ANY OTHER PATH OR ANY OTHER BLOB = STOP' && has 'MERGE ORDER: #1300 BEFORE #1301' || { echo "REFUSING: the GO retarget step and merge order" >&2; exit 48; }
has 'WIDEN #1302 — WHAT NEW FIELDS REACH THE PRODUCTION LOG FILES' && has 'or grade #1302 NO GO if it can' && has 'SAME-CLASS-AS-KS1346: then SAY PLAINLY whether #1302 is the same class' || { echo "REFUSING: the #1302 log-file widen rule" >&2; exit 50; }
has 'CODE-TOKEN EQUIVALENCE FOR #1303' && has 'only "parser leaves minus the JSDoc kind range" was sound' || { echo "REFUSING: the #1303 token equivalence" >&2; exit 51; }
has 'NO DOCKER, NO STACK, NO PORT in this gate' && has 'NEVER connect to the native Postgres on :5432' || { echo "REFUSING: no Docker / no stack / no port" >&2; exit 35; }
has 'MG-3 KEY SCAN (measured by the drafter' && has 'a squash body is NEVER "the verbatim head commit message" here' || { echo "REFUSING: the MG-3 key scan" >&2; exit 47; }
has 'all four PRs link their tickets as `contributes`, none as `closes`' || { echo "REFUSING: the Linear link kinds" >&2; exit 46; }
has "WEDNESDAY'S signed GO naming the head" && has '`GO: merge #1300, #1301, #1302, #1303 batch`' && has 'so all four are squashed by Seat B 33rd, the merge seat Wednesday names for this GO' || { echo "REFUSING: merge authority / the GO string" >&2; exit 26; }
has '## MERGE ADDENDUM' && has 'PER PR FILE (6 over 5 paths) for #1300, #1301, #1302 and #1303' && has 'KEY-FREE' && has 'MG-11 each subject <= 92' && has 'the FLEET STOP after this merge' || { echo "REFUSING: the MERGE ADDENDUM rules" >&2; exit 25; }
grep -qF -- '[QA -> Wednesday] GATE31 batch #1300 #1301 #1302 #1303 (Seat B33, round 31; T1 KS-1334 B, T2 KS-1349, T1 KS-1348, T3 KS-1350)' "$PROMPT_FILE" && has 'FROM coagent@agentmail.to' || { echo "REFUSING: the verdict subject / sender" >&2; exit 23; }
grep -qF -- "$DEVELOP_SHA" "$PROMPT_FILE" && grep -qF -- "$END_TREE" "$PROMPT_FILE" && grep -qF -- "$RETARGET_TREE" "$PROMPT_FILE" || { echo "REFUSING: the launch develop / the END_TREE / the RETARGET tree not in full" >&2; exit 31; }
NOTE="origin develop $CUR_DEV == the pinned launch develop; heads at branch AND pull/<n>/head:$HEADS_NOTE; END_TREE $END_TREE; stacks $STACKS (RETARGET tree $RETARGET_TREE)"
_ANY_OVR="$(env | grep -c '^QAB31_')"
if [ "${1:-}" = "--check" ]; then
  echo "all guards pass:"
  echo "  $NOTE"
  echo "  compare (GitHub API), develop...head per PR, parent...head for a stacked child (merge_base, ahead, behind, the PR's own paths by name):"; printf '%s\n' "$COMPARE" | sed 's/^/    /' | cut -c1-240
  echo "  capture, prompt, QA project and repo present; kit at its filled home; 4 rows; thinking directive; capture + commission named; no unfilled token"
  echo "  capture and prompt BOTH carry every head in full, every ticket and 16 seat items; the prompt carries 30 by-name keywords and the base-invariant+pairwise / red-proof / fleet-STOP / load+anchoring / holds / legs-3/4/8 / the #1300 T1 runtime probe / the #1300 in-place ks730c edits / the KS-1334 5f close / the #1301 tamper arm / the #1301 stack and retarget / the GO retarget step and merge order / the #1302 log-file widen rule / the #1303 token equivalence / no Docker / no stack / no port / the MG-3 key scan / the Linear link kinds rules, the GO string, the addendum rules, the verdict subject, develop / END_TREE / RETARGET tree in full"
  [ "$_ANY_OVR" != 0 ] && echo "  (a QAB31_* TEST OVERRIDE is set)"
  echo "  a launch (not --check) will refuse unless stdin is a TTY (exit 21)"
  exit 0
fi
[ -t 0 ] || { echo "REFUSING: stdin is not a TTY — run this launcher in a cockpit pane, never inside a Bash tool" >&2; exit 21; }
[ "$_ANY_OVR" = 0 ] || { echo "REFUSING: a launch with test overrides set" >&2; exit 16; }
echo "$NOTE" >&2
cd "$QA_DIR" || { echo "cannot enter $QA_DIR" >&2; exit 16; }
exec claude --dangerously-skip-permissions "$(cat "$PROMPT_FILE")"
